### DISCUSSION TITLE
IngressRoute for Traefik Dashboard Not Being Created

### DISCUSSION THREAD

**Discussion by natenberenstein** [k3s-io/k3s#10013] [Q&A] [answered]
## Environment Info
**Cluster setup**
- 1 server node
- 2 agent nodes

**K3s Version**
```
k3s version v1.28.7+k3s1 (051b14b2)
go version go1.21.7
```

## Describe the issue
I have a virtual IP with the domain name `traefik-kube.com` and I created a `HelmChartConfig` resource to override the ingressRoute values so that I can have the Traefik dashboard routed to the Virtual IP.  I'm also using keepalived to access the Virtual IP.  Below is my configuration:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
      ingressRoute:
          dashboard:
              enabled: true
              matchRule: Host(`traefik-kube.com`)
      ports:
          traefik:
              expose: true
      providers:
          kubernetesCRD:
              allowCrossNamespace: true
```

## Expected Behavior
When I restart the K3s server, I expect `IngressRoute` resource for traefik-dashboard to created in`kube-system` namespace and the dashboard to be rendered at `traefik-kube.com/dashboard`.

## Actual Behavior
The `IngressRoute` resources for traefik-dashboard is not created.

## Discussion
I'm not exactly sure how to debug this issue and determine if the `HelmChartConfig` resource was actually applied.  I did look into the pods located in `kube-system` namespace and looked over the `traefik` pod details, but the configuration I provided isn't reflected there.  Here are the pods in `kube-system` after restarting k3s:

| NAME   |READY  | STATUS   |   RESTARTS     |   AGE|
|------|--------|------|------|------|
|local-path-provisioner-6c86858495-gz9rz |  1/1    | Running   |  3| (5d19h ago)   27d|
|coredns-6799fbcd5-5x9hl                 |  1/1  |   Running    | 2| (5d19h ago)   27d|
|metrics-server-67c658944b-r8nqr         |  1/1    | Running    | 3 |(5d19h ago)   27d|
|helm-install-traefik-65m44           |     0/1    | Completed   |1      |         14m|
|svclb-traefik-fca57f53-twnsq          |    3/3   |  Running    | 0           |    14m|
|svclb-traefik-fca57f53-7tswz          |    3/3   | Running    | 0           |    14m|
|svclb-traefik-fca57f53-dmvbl         |     3/3    | Running     |0          |     14m|
|traefik-74b6d5bfc4-qqncl               |   1/1   |  Running     |0           |    14m|

When I run `kubectl get ingressroute -A`, no resources exist.

**Comment by natenberenstein** [comment, marked as answer]
While I don't see `IngressRoute` resource for traefik-dashboard, I was able to get the Traefik dashboard to route to `traefik-kube.com` by providing the following entry points: "web" and "websecure".  Below is my new configuration:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
      deployment:
          labels: {lab:  "enterprise"}
      ingressRoute:
          dashboard:
              enabled: true
              matchRule: Host(`traefik-kube.com`)
              entryPoints: ["web", "websecure"]
          healthcheck:
              enabled: true
              entryPoints: ["traefik", "web", "websecure"]
      ports:
        traefik:
            expose: true
      providers:
          kubernetesCRD:
            allowCrossNamespace: true
```

Though, I am still open to other advice that would help me consider other stuff (e.g. security).
