### DISCUSSION TITLE
Is `ImageMaximumGCAge` supported through the configuration system?

### DISCUSSION THREAD

**Discussion by Mixih** [k3s-io/k3s#10125] [Q&A] [answered]
Thanks for the great project!

I was looking through the documentation, and saw that the conclusion in https://github.com/k3s-io/k3s/issues/2116 and https://github.com/k3s-io/k3s/issues/5488 is to continue relying on `kubelet-arg`'s cli options documented here (https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) for kubelet configuration. However, we'd like to use the `ImageMaximumGCAge` options to configure a time-based GC for images since we're running on heavily storage constrained nodes. Per https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images this is kube 1.30 beta feature and the feature flags is already in the CLI, but there is no CLI option yet to actually set the value. Would K3S support any way of configuring this setting, or are beta settings present only in the kubelet config file a WONTFIX?

Thanks again!

**Comment by brandond** [comment, marked as answer]
You'd want to start k3s with `--kubelet-arg=config=/etc/rancher/k3s/kubelet-config.yaml` and then create that configuration file:

```yaml
# /etc/rancher/k3s/kubelet-config.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
imageMaximumGCAge: 1d
featureGates:
  ImageMaximumGCAge: true
```
