### DISCUSSION TITLE
I can't configure the docker.io image repository

### DISCUSSION THREAD

**Discussion by ihezebin** [k3s-io/k3s#10344] [Q&A] [answered]
curl -sfLk https://get.k3s.io | INSTALL_K3S_VERSION=v1.28.9+k3s1 sh -s - --disable traefik --disable-default-registry-endpoint

centos7

vi /etc/rancher/k3s/registries.yaml

```yaml
mirrors:
  "docker.io":
    endpoint:
      - "https://uph96ue9.mirror.aliyuncs.com",
      - "https://mirror.ccs.tencentyun.com",
      - "https://hub-mirror.c.163.com",
      - "https://mirror.baidubce.com"
  "ccr.ccs.tencentyun.com":
    endpoint:
      - "https://ccr.ccs.tencentyun.com"
  "registry.cn-hangzhou.aliyuncs.com":
    endpoint:
      - "https://registry.cn-hangzhou.aliyuncs.com"
configs:
  "registry.cn-hangzhou.aliyuncs.com":
    auth:
      username: ihezebin
      password: xxxx
  "ccr.ccs.tencentyun.com":
    auth:
      username: 100009173056
      password: xxxx
```

sudo systemctl restart k3s

`cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml` not have any changes

```
[root@hezebin-k3s-master ~]# k get nodes
NAME                 STATUS     ROLES                  AGE     VERSION
hezebin-k3s-master   NotReady   control-plane,master   2m50s   v1.28.9+k3s1
```

but if remove the docker config, like this:
```
mirrors:
  "ccr.ccs.tencentyun.com":
    endpoint:
      - "https://ccr.ccs.tencentyun.com"
  "registry.cn-hangzhou.aliyuncs.com":
    endpoint:
      - "https://registry.cn-hangzhou.aliyuncs.com"
configs:
  "registry.cn-hangzhou.aliyuncs.com":
    auth:
      username: ihezebin
      password: xxxxxx
  "ccr.ccs.tencentyun.com":
    auth:
      username: 100009173056
      password: xxxx
```
<img width="707" alt="image" src="https://github.com/k3s-io/k3s/assets/36706912/be650f61-1757-4663-856e-1f5405da9a4d">

**Comment by ihezebin** [comment]
What I want to achieve is something like docker's

```bash
sudo mkdir -p /etc/docker

sudo tee /etc/docker/daemon.json <<-'EOF'
{
  "registry-mirrors": [
    "https://uph96ue9.mirror.aliyuncs.com",
    "https://mirror.ccs.tencentyun.com",
    "https://hub-mirror.c.163.com",
    "https://mirror.baidubce.com"
  ],
  "exec-opts": ["native.cgroupdriver=systemd"]
}
EOF

sudo systemctl daemon-reload
sudo systemctl restart docker
```

**Comment by brandond** [comment, marked as answer]
That's not valid YAML... you shouldn't put a trailing comma at the end of each list entry. You're not seeing anything in config.toml because it's throwing an error when loading your registries.yaml, which probably shows up in the logs if you'd looked at them.

Either do
```yaml
mirrors:
  "docker.io":
    endpoint: ["https://uph96ue9.mirror.aliyuncs.com", "https://mirror.ccs.tencentyun.com"]
```
or
```yaml
mirrors:
  "docker.io":
    endpoint:
      - "https://uph96ue9.mirror.aliyuncs.com"
      - "https://mirror.ccs.tencentyun.com"

```
but not
```yaml
mirrors:
  "docker.io":
    endpoint:
      - "https://uph96ue9.mirror.aliyuncs.com",
      - "https://mirror.ccs.tencentyun.com"
```
