### DISCUSSION TITLE
Mount entire NFS share as a pod volume as-is.

### DISCUSSION THREAD

**Discussion by IngwiePhoenix** [k3s-io/k3s#10361] [General]
I want to move my Jellyfin installation off docker-compose and into my k3s cluster (2x arm64 nodes) but since Jellyfin accesses media directly in a prepared folder, I wanted to just mount my whole network share as a volume to the pod.

One way would be to just specify the `.nfs` options directly on the volume. But, I would like to re-use this more efficiently across a few services like TubeArchivist, TVHeadend and friends. So, I tried to create a PersistentVolume + Claim in order to try and handle this. But, no dice.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bunker-generic-pv
  namespace: jellyfin
  labels:
    store: bunker
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Ti
  nfs:
    server: 100.64.0.11
    path: /mnt/vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bunker-generic-pvc
  namespace: jellyfin
spec:
  selector:
    matchLabels:
      store: bunker
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-mounter
  namespace: jellyfin
  labels:
    app: example-mounter
spec:
  selector:
    matchLabels:
      app: example-mounter
  template:
    metadata:
      labels:
        app: example-mounter
    spec:
      volumes:
        - name: bunker-generic-vol
          persistentVolumeClaim:
            claimName: bunker-generic-pvc
      containers:
        - name: app
          image: alpine:stable
          command: ["/bin/sh", "-c", "sleep infinity"]
          volumeMounts:
            - mountPath: /mnt/vol1
              name: bunker-generic-vol
```

What am I missing here? When deployed, I see this in the events overview:
```
jellyfin      0s (x19 over 4m17s)     Normal    ExternalProvisioning   PersistentVolumeClaim/bunker-generic-pvc   Waiting for a volume to be created either by the external provisioner 'rancher.io/local-path' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
```

...thing is, I am not asking for dynamic provisioning; I know _exactly_ where the volume is, I just want to be able to point Jellyfin and possibly a few adjacent services to the same PVC so I would only have to change the IP once, not a dozen times over instead.

Bonus: The ability to define this kind of volume once, and reuse it across namespaces, so I don't have to copypaste it into different namespaces or lumb things together into one just to share the same PV+PVC.

Thank you and kind regards,
Ingwie
