### DISCUSSION TITLE
Configuration problem with static CPU manager

### DISCUSSION THREAD

**Discussion by ninjab3s** [k3s-io/k3s#10423] [Q&A]
I am trying to configure the static CPU manager on K3s. I successfully did it on K8s but I cannot figure out how to do this in K3s. In k8s I would use the following config:

```
cpuManagerPolicy: static
reservedSystemCPUs: 0,12
featureGates:
  CPUManager: true
  CPUManagerPolicyOptions: true
cpuManagerPolicyOptions:
  full-pcpus-only: "true"
  align-by-socket: true
  distribute-cpus-across-numa: false
```

I have already checked the docs but I cannot figure out what arguments to use since I cannot find anything similar there. Any help appreciated! Thank you in advance!
