### DISCUSSION TITLE
Does local-path provisioner work with RWO access mode for multiple pods

### DISCUSSION THREAD

**Discussion by cwrx777** [k3s-io/k3s#10538] [Q&A]
I have created a PV with the following yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-db-primary-data-pv
  labels:
    component: primary-data
    app.kubernetes.io/component: primary-data
spec:
  storageClassName: local-path
  capacity:
    storage: {{ $.Values.primary.persistence.data.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ tpl .Values.primary.persistence.data.hostPath . }}
  nodeAffinity: 
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: {{ $.Values.global.pv.nodeAffinity.selector.key }}
              operator: In
              values:
                -  {{ $.Values.global.pv.nodeAffinity.selector.value }}
```

and this PVC
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-db-primary-data-pvc
  labels:
    component: primary-data
    app.kubernetes.io/component: primary-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.primary.persistence.data.size }}
  storageClassName: local-path
  selector:
    matchLabels:
      component: primary-data
```
And I want to create two pods, e.g. mysql and mysql-backup to be able to access the PV for accessing mysql data-dir at the same time. both pods are using the same PVC.
Will that work?
