### DISCUSSION TITLE
Cluster won't start is I set "node-external-ip" option

### DISCUSSION THREAD

**Discussion by davidshen84** [k3s-io/k3s#10615] [Q&A]
Hi,

I installed my k3s in my WSL 2 and I want to access from any other computer in the same network.

I used this configuration file and it used to be working.

```yaml
write-kubeconfig-mode: "0644"
token: k3s-home
node-external-ip: 192.168.86.109
disable:
  - traefik
```

But recently, some system pods started to fail. I did some troubleshooting and discovered the `node-external-ip` option is causing the problem.

However, I did not find any update relating to this option on the official website.

What is the right/new way to expose a different cluster ip?

Thanks
