### DISCUSSION TITLE
helm upgrade traefik dual-stack ipv6 is removed for traefik service

### DISCUSSION THREAD

**Discussion by shakibamoshiri** [k3s-io/k3s#10683] [Q&A] [answered]
Installed k3s with traefik enabled in dual stack , no issue 
installing traefik helm package 
helm uninstall traefik -n kube-system
and 
helm install traefik -n kube-system
the version has been upgraded to v3.1 but no longer the service is listing on ipv6 

```bash
 k3s --version 
k3s version v1.30.3+k3s1 (f6466040)
go version go1.22.5
```

What has gone wrong ?
Regards

**Comment by shakibamoshiri** [comment]
The new traefik service is not configured for dual-stack 

```yaml
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv6
  - IPv4
```

Testing the service with `kubectl edit svc trafic` enabled IPv6 , better to update help chart or find a helm chart configured for dual-stack

**Comment by shakibamoshiri** [comment]
we can use helm upgrade, modifying the key we need,
in this case we need to update `ipFamilyPolicy` which by default has been set to `SingleStack`

1. [install and deploy traefik using helm](https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-helm-chart)

2. get the heml's values  `helm show values traefik/traefik > value.yaml`

3. update the key `vim value.yaml` and
```yaml
  ## One of SingleStack, PreferDualStack, or RequireDualStack.
  ipFamilyPolicy: RequireDualStack
```

4. apply changes `helm upgrade traefik  traefik/traefik -f value.yaml -n kube-system`

5. check the changes `k get svc traefik -n kube-system  -o yaml` and we should see

```yaml
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
```

NOTE
you should know the namespace of traefik , otherwise you will get errors like this (mine was in `-n kube-system`)

```
helm upgrade traefik  traefik/traefik -f value.yaml
Error: UPGRADE FAILED: "traefik" has no deployed releases
```

the error is not describe enough , it should like 

```bash
Error: UPGRADE FAILED: "traefik" has no deployed releases in "default" namespace
```

[k8s doc](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services)

**Reply by brandond** [reply, marked as answer]
Don't do that. Customize the chart values as described in the documentation.

https://docs.k3s.io/helm#customizing-packaged-components-with-helmchartconfig

**Reply by AndrewSav** [reply]
@brandond this does not seem to work.

With

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: 3.2.0
```

Result:

```
Failed to pull image "rancher/mirrored-library-traefik:3.2.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/mirrored-library-traefik:3.2.0": failed to resolve reference "docker.io/rancher/mirrored-library-traefik:3.2.0": docker.io/rancher/mirrored-library-traefik:3.2.0: not found
```

It looks like it is trying to pull "rancher/mirrored-library-traefik:3.2.0" from docker hub, which does not exist. How do we fix that?
