### DISCUSSION TITLE
Does NetworkPolicies in K3s (with Kuberouter) supporting external Networktraffic?

### DISCUSSION THREAD

**Discussion by janbaer** [k3s-io/k3s#11097] [Q&A] [answered]
I'm trying to configure a Networkpolicy that should block Network-traffic from a specific external IP-address.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-requests-from-internal-api-only
  namespace: verbu-22164
spec:
  podSelector:
    matchLabels:
      role: service
  policyTypes:
    - Ingress
  ingress:
    - from:
      - ipBlock:
        cidr: 10.2.201.0/24
        except:
          - 10.2.201.113/32
```

So the Network-range I specified here, is not the IP-range that is used internally in the K3s cluster, but in the network where also K3s is running. For some reason this is blocking all traffic from any IP-address outside of the cluster to all pods with the label service. But it should block it only for the one IP address is specified in the except list.

Is this feature supported by the Kuberouter at all, or is it only for handling traffic between the pod, when they are talking directly with each other over internal network?
