### DISCUSSION TITLE
Clarification on Traefik Ingress in k3s - Gateway API vs. Ingress Resource

### DISCUSSION THREAD

**Discussion by wanclem** [k3s-io/k3s#11100] [Q&A] [answered]
Hello everyone,

I'm in the process of installing k3s and have a question regarding the Traefik ingress controller that comes bundled with it. Does the default Traefik setup in k3s use the Gateway API, or is it still based on the traditional Ingress resource?

I would prefer to use the Gateway API with HTTPRoute for managing ingress. If Traefik in k3s doesn't use the Gateway API by default, could you guide me on how to disable the traditional Ingress controller and switch to Traefik Gateway Fabric instead?

Any advice or guidance would be greatly appreciated. Thanks in advance!

```

curl -sfL https://get.k3s.io | sh -s - server --cluster-init --cluster-cidr="$CLUSTER_CIDR" --node-label="control-plane"

```

**Comment by teekennedy** [comment, marked as answer]
You can customize the Traefik deployment using [Helm Controller](https://docs.k3s.io/helm), which is included with k3s.

Here's the minimal values you'd need to change to enable Traefik's Gateway API:
```yaml
# /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesGateway:
        enabled: true
```

Write that yaml to a file under /var/lib/rancher/k3s/server/manifests/ and it will be automatically picked up and applied by Helm Controller. There is no need to restart k3s.

If you run into issues, you can troubleshoot using the logs of the `helm-install-traefik` job in the `kube-system` namespace.

_Edited to remove the redundant and deprecated experimental version of the flag_
