### DISCUSSION TITLE
Cannot get HelmChartConfig to override traefik settings

### DISCUSSION THREAD

**Discussion by dprothero** [k3s-io/k3s#11176] [Q&A] [answered]
I am following [this documentation](https://docs.k3s.io/helm#customizing-packaged-components-with-helmchartconfig) to create a `/var/lib/rancher/k3s/server/manifests/traefik-config.yaml` to override the values for the Traefik addon. I used the example YAML from the doc and, after saving the file, it seemed to work. I ran the following command:

```bash
helm -n kube-system get values traefik
```

And it showed the updated values for the image tag and the `forwardedHeaders`. Then I tried the following for my file:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        redirectTo: websecure
```

That didn't work. In fact, running `helm -n kube-system get values traefik` still showed the previous values with the old `2.9.10` tag!

Then, I deleted the `/var/lib/rancher/k3s/server/manifests/traefik-config.yaml` file, looked at the values again, and they still hadn't changed from the original customization.

Finally, I restarted k3s using `systemctl` and _still_, the original customized values are in place!

As a noob, there's clearly something going on here that I don't understand, but strictly from my noob's lens through the documentation, something seems broken.

Is this a documentation issue (and, if so, what essential piece of information about the behavior of this system is it missing), or is there truly a problem with how this addon customization setup works?
