### DISCUSSION TITLE
k3s air-gapped env resolve dns fails for statefulset

### DISCUSSION THREAD

**Discussion by 7ff5fC1E397d** [k3s-io/k3s#11343] [Q&A] [answered]
An air-gapped env has been configured with one master and a worker.

### k3s

```bash
k3s version v1.30.3+k3s1 (f6466040)
go version go1.22.5
```

### os
```bash
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### master

```bash
#!/bin/bash

set -ex

cp -v ./k3s /usr/local/bin/

export INSTALL_K3S_SKIP_DOWNLOAD=true
export INSTALL_K3S_EXEC="--disable=traefik --cluster-cidr=10.42.0.0/16 --service-cidr=10.43.0.0/16 --node-external-ip=172.16.110.124 --node-ip=172.16.110.124 --node-label=100m1"

./install.sh
```

### worker

```bash
#!/bin/bash

set -ex

cp -v ./k3s /usr/local/bin/

export INSTALL_K3S_SKIP_DOWNLOAD=true
export K3S_URL=https://172.16.110.124:6443
export INSTALL_K3S_EXEC="--node-external-ip=172.16.110.126 --node-ip=172.16.110.126"
export K3S_TOKEN='xyz'

./install.sh
```

### sample pod
Two pods have been created and set on a single node

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  labels:
    app: nginx
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # hostname: nginx
      subdomain: nginx     # to resolve dns
      nodeName: 100w3    # <-- the worker
      containers:
      - name: nginx
        image: nginx:stable-alpine3.20
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www
        emptyDir: {}
```

### issue
On this air-gapped env **web-0** and **web-1** cannot see (`ping`) each other. On **web-0** pod, it can `ping` itself but not **web-1** and vice versa , on **web-1** it can `ping` itself but not **web-0** even if we use subdomain 

 - web-0.nginx
 - web-1.nginx

### tests
Out of the air-gapped env, (public access to Internet) with the exact same k3s version and nginx config it works fine.

### question
Is this issue because of air-gapped env ?
Or perhaps any extra or  special configs are needed ?

### screenshots

air-gapped

![2024-11-19-121306_950x518_scrot](https://github.com/user-attachments/assets/ac1afbd5-7fea-4fee-9ae6-a935943c104c)

public 
![2024-11-19-121504_950x519_scrot](https://github.com/user-attachments/assets/192517d9-cb5f-48cd-bf70-86391bfdde2a)

### more info

Nothing has been blocked on machines, all ports and  protos are allowed . Using `nc` tested that udp 53 are passed.

kubectl get svc 
```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   40m
nginx        ClusterIP   None         <none>        80/TCP    30m
```

kubectl get ep 
```
NAME         ENDPOINTS                   AGE
kubernetes   172.16.110.124:6443         41m
nginx        10.42.1.2:80,10.42.1.3:80   32m
```

kubectl get ep -n kube-system
```
NAME             ENDPOINTS                                  AGE
kube-dns         10.42.0.3:53,10.42.0.3:53,10.42.0.3:9153   41m
metrics-server   10.42.0.2:10250                            41m
```

kubectl get pods -n kube-system
NAME                                      READY   STATUS    RESTARTS   AGE
```
coredns-576bfc4dc7-4zftj                  1/1     Running   0          53m
local-path-provisioner-6795b5f9d8-hprmm   1/1     Running   0          53m
metrics-server-557ff575fb-vjwrh           1/1     Running   0          53m
```

crictl image ls

```
IMAGE                                        TAG                 IMAGE ID            SIZE
docker.io/library/nginx                      stable-alpine3.20   60847f99ea697       20.9MB
docker.io/rancher/local-path-provisioner     v0.0.28             5d221316a3c61       18.4MB
docker.io/rancher/mirrored-coredns-coredns   1.10.1              ead0a4a53df89       16.2MB
docker.io/rancher/mirrored-metrics-server    v0.7.0              b9a5a1927366a       19.4MB
docker.io/rancher/mirrored-pause             3.6                 6270bb605e12e       301kB
```

both web-0 and web-1 can `ping` directly using their IPs, but  using name, no, so the issue is DNS

Does anyone have any idea ?

Regards
