### DISCUSSION TITLE
how to change agent's traefik port?

### DISCUSSION THREAD

**Discussion by ashesofdream** [k3s-io/k3s#11409] [Q&A]
**Environmental Info:**
K3s Version: 

1.30.6
Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

1 master,1 agent

**Describe the bug:**

I have change master's traefik  by  kubectl apply -f:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        exposedPort: 8080
      websecure:
        exposedPort: 8443
```
But agent seems  still take 443 and 80 port ,that my transparent proxy cannot run,how can i fix?
