### DISCUSSION TITLE
work with 3 master

### DISCUSSION THREAD

**Discussion by gpahlevanzadeh** [k3s-io/k3s#11508] [Q&A]
I have 3 masters and they're HA. 
Now I create a worker such as: 
`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.31.4+k3s1  K3S_NODE_NAME=worker1 K3S_URL=https://192.168.1.106:6443 K3S_TOKEN=mohsenjoojoo sh -
`
My cluster master is `192.168.1.106` and my token is `mohsenjoojoo`.
Now if 192.168.1.106 will be down, How this worker switch to another master?
My worker config is:
```
root@worker1:~# cat .kube/config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXpRNU9UTXpNVGN3SGhjTk1qUXhNakl6TWpJek5URTNXaGNOTXpReE1qSXhNakl6TlRFMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXpRNU9UTXpNVGN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTSHErd0FTODZnb3NUbGx1N05TOFJjUlVHZFhTL2Y4ME40N1VQVXVCR04KMzYyRTJldWkrM1JHL3JSTnhkVDVBWmJxd29VdkFXY3BPNG4vNm9qMWVOTzVvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUNsdURGMzNacG9ibVZoSjVneWdCCmtWU3p5QkV3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQVBaUTlIOHpWTk1VZWdwOXBuWEttbGFkQnJoY2VUNzQKYmh2bC9UVU1FeFB5QWlFQS9XdXh1WVgyemRXYU9UbUZaMkVvM25SL1Q3cGVUZWtsazNvTUJoR2Vhd1E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.1.106:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJZVNGUzhkMktnVTR3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOek0wT1Rrek16RTNNQjRYRFRJME1USXlNekl5TXpVeE4xb1hEVEkxTVRJeQpNekl5TXpVeE4xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPUW9ma1ROdGZUaU9wSEEKYTcrajkwQmEwTFZUM2xFdmZHR05QK2F1TXV0ckJteHZQcEQ4cUtaUzV6SHR6MU1FMyt1cWlFdTVmdFBOVy9LZgptL21zMjk2alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUnloZFZ6ZEdyV25UZnpNWGU4WWkvdzF5MDZBVEFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQWo3Nkw0SXlvRldheDRtOWdPbEJ2c3IxeVJhbUx1NW53MHkralM2UWxYL1lDSUdXMHNFdzgrZ2pnVmM0bwppNGZiUmFUTEJJaUxHaytJL1V2R2kwL0c3a29GCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTXpRNU9UTXpNVGN3SGhjTk1qUXhNakl6TWpJek5URTNXaGNOTXpReE1qSXhNakl6TlRFMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTXpRNU9UTXpNVGN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSbXlqTXpNYmQyNXhTaEtta0ZGN09VajdodEM5SW1aWU1KQlkvTVdkQ2gKR2I1N1gzYlloMkxwWlBiRGN1NW5CdHNTTnRZV2dpOTZ0Z2FubEtrMzh0WmpvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWNvWFZjM1JxMXAwMzh6RjN2R0l2CjhOY3RPZ0V3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnTUVoVDl0ZXBQMVB2RHZ1ZTNld3BTUW1rSDd4THE2MC8KaUNxMnExcncrSFlDSVFDQm00cTkyOFNJT0xXY09VT3dXSUNRRDlkMHloQW1EZkxBYk1lQ3FvMnViZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBHWklEVUZ1MkFWbERZS0VSQkNMZEtubHVMMTYwaFN5dkhzdzV2WGR3UldvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNUNoK1JNMjE5T0k2a2NCcnY2UDNRRnJRdFZQZVVTOThZWTAvNXE0eTYyc0diRzgra1B5bwpwbExuTWUzUFV3VGY2NnFJUzdsKzA4MWI4cCtiK2F6YjNnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
root@worker1:~# 


```

Can I add another server to my worker? If yes, How to?
