### DISCUSSION TITLE
Bypassing from proxy

### DISCUSSION THREAD

**Discussion by gpahlevanzadeh** [k3s-io/k3s#11518] [Q&A] [answered]
I'm living in Iran and our regime has a filtering system that we can't access to many sites.
I bought a VM in out my country and encrypt my data on port 81 and send to my VM and VM route my packets to Internet.
I set 127.0.0.1:81 in my browser and I can access to many sites filtered.
google cloud banned IPs of Iran. For pulling from `https://console.cloud.google.com/artifacts/tags/google-samples/us/containers/gke%2Fgb-frontend/v5` I get the 403 forbidden.
I set the following variable in `.bashrc` :
```
export https_proxy=http://127.0.0.1:81
export http_proxy=http://127.0.0.1:81
export HTTP_PROXY=${http_proxy}
export HTTPS_PROXY=${https_proxy}
export no_proxy=127.0.0.1,localhost,debian
export NO_PROXY=${no_proxy}
```
Then I reload `.bashrc` via `source /root/.bashrc`
Then I apply my replicaset such as:
```
root@debian:~/lab# kubectl apply -f frontend.yaml 
replicaset.apps/frontend created
root@debian:~/lab# cat frontend.yaml 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
```
After apply, I get the following POD of `frontend`:
```
root@debian:~/lab# kubectl get pods
NAME             READY   STATUS             RESTARTS           AGE
frontend-79j6j   0/1     ImagePullBackOff   0                  94s
frontend-vqzdr   0/1     ImagePullBackOff   0                  94s
frontend-zh6zb   0/1     ImagePullBackOff   0                  94s
mohsennginx      1/1     Running            0                  3d
```

How can I tell to `kubectl` or `k3s` use a proxy for pulling?
