### DISCUSSION TITLE
ImagePullBackOff with ReplicaSet

### DISCUSSION THREAD

**Discussion by gpahlevanzadeh** [k3s-io/k3s#11627] [Q&A] [answered]
I have the following yaml file:
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs-pod
  template:
    metadata:
      labels:
        app: nginx-rs-pod
        env: dev
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
```
Before apply above yaml I don't have any pod. After applying above yaml file I have the 3 pods such as :
```
root@debian:~/lab/pods# kubectl get pods
NAME                     READY   STATUS             RESTARTS   AGE
nginx-replicaset-57qm5   0/1     ImagePullBackOff   0          4m32s
nginx-replicaset-btb5m   0/1     ImagePullBackOff   0          4m32s
nginx-replicaset-tcjdj   1/1     Running            0          4m32s
```
I don't know about `ImagePullBackOff` status. Why do I get running a pod, but two others have `ImagePullBackOff`?
