### DISCUSSION TITLE
v1.31.2+k3s1 Failed to get logs on some specific nodes of the cluster

### DISCUSSION THREAD

**Discussion by Gab-Menezes** [k3s-io/k3s#11847] [Q&A] [answered]
**Environmental Info:**
K3s Version:  `v1.31.2+k3s1`

Node(s) CPU architecture, OS, and Version:  `Linux **** 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration: `5 servers, 91 agents`

**Describe the bug:**
I think my problem is similar to https://github.com/k3s-io/k3s/issues/10444, https://github.com/k3s-io/k3s/issues/10474, https://github.com/k3s-io/k3s/issues/10547, https://github.com/k3s-io/k3s/issues/10653,https://github.com/k3s-io/k3s/issues/11418, but not exactly the same.

What is happening is that depending on which server is configured in my `~/.kube/config` I get this error, for example. If I change my `~/.kube/config` to use node 1 and try to get logs of pods running on node 58 I get:
```
Defaulted container "patroni" out of: patroni, envoy, pgbouncer, prometheus-postgres-exporter, postgres-util, cluster-controller, setup-arbitrary-user (init), setup-scripts (init), relocate-binaries (init), pgbouncer-auth-file (init), cluster-reconciliation-cycle (init)
Error from server: Get "https://172.19.35.30:10250/containerLogs/default/pg-prod-2/patroni": proxy error from 127.0.0.1:6443 while dialing 172.19.35.30:10250, code 502: 502 Bad Gateway
```
Where `172.19.35.30` is the ip of node 58. If I change my `~/.kube/config` to use node 2 this problem goes away.

What I have tested:

* I'm pretty sure I'm not using the `bind-address` flag.
* I have tested the connectivity between node 1 and 58 and node 2 and 58, by doing a `kubectl debug` in both, running `nc -lvn -p 8090 0.0.0.0` in node 58 and `telnet 172.19.35.30 8090` in node 1 and 2 and this works fine.
* Even tried running `telnet 172.19.35.30 10250` and it's fine.

Here is the `/etc/rancher/k3s/config.yaml` for node 1:

```yaml
kube-controller-manager-arg:
  - bind-address=0.0.0.0
kube-proxy-arg:
  - metrics-bind-address=0.0.0.0
kube-scheduler-arg:
  - bind-address=0.0.0.0
etcd-expose-metrics: true
cluster-init: true
kubelet-arg:
  - container-log-max-files=5
  - container-log-max-size=20Mi
secrets-encryption: true
disable:
  - servicelb
  - traefik
```

And node 2 is very similar but without the `cluster-init: true`.

But if I try to get logs from other nodes things work fine, is just this weird problem that happens some specific server nodes and agents.

The weird thing is why can I access the node using `telnet` while running `kubectl debug` but the not when running `kubectl logs` ?

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:** All serve nodes should be able to communicate equally with all other nodes.

**Actual behavior:** Some server nodes can communicate while others can't.

**Additional context / logs:**
