### DISCUSSION TITLE
A chart's CRDs not installed when using helm controller

### DISCUSSION THREAD

**Discussion by firekind** [k3s-io/k3s#12023] [Q&A]
Hello,
Does the helm controller install crds that a chart defines? I'm trying to apply the following envoy gateway config:

```
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gateway-helm
  namespace: envoy-gateway-system
spec:
  chart: gateway-helm
  repo: oci://docker.io/envoyproxy
  version: 1.3.2
  targetNamespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway-class
  labels:
    app: gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  gatewayClassName: envoy-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
```

and when i apply this, i get the following error:

```
namespace/envoy-gateway-system created
helmchart.helm.cattle.io/gateway-helm created
Error from server (NotFound): error when creating "gateway.yaml": the server could not find the requested resource (post gatewayclasses.gateway.networking.k8s.io)
Error from server (NotFound): error when creating "gateway.yaml": the server could not find the requested resource (post gateways.gateway.networking.k8s.io)
```

the crds for Gateway and GatewayClass are present in the crds folder of the gateway-helm helm chart. Is there any additional configuration that needs to be done to tell the helm controller to apply the crds? Or am i doing something wrong here?
