### DISCUSSION TITLE
The K3s agent doesn't use the Private Registry to pull remote images.

### DISCUSSION THREAD

**Discussion by shangjianan2** [k3s-io/k3s#12324] [Q&A] [answered]
I deployed two k3s-services and one k3s-agent by referring to this link: https://docs.k3s.io/installation/airgap. The hostname of the host where the k3s-agent is located is node3.

Resource list
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k3s-test
  namespace: zbwt-prod
  labels:
    app: app-k3s-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-k3s-test
  template:
    metadata:
      labels:
        app: app-k3s-test
    spec:
      nodeSelector:
        zbwt-node-name: node3
      containers:
        - name: app-k3s-test-container
          image: 10.111.160.21:39435/app-k3s-test-img:1747040141
          env:
            - name: ZBWT_PROFILE
              value: "xxzxtest"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-k3s-test-service
  namespace: zbwt-prod
spec:
  selector:
    app: app-k3s-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
```

but pod not run
```
[root@dbSlave app-k3s-test]# kubectl --kubeconfig=/home/wjl/dockerCompose/gitlab-runner-k3s/k3s/config get pods -n zbwt-prod -o wide
NAME                            READY   STATUS              RESTARTS   AGE   IP       NODE    NOMINATED NODE   READINESS GATES
app-k3s-test-555bddb6b9-brwpv   0/1     ContainerCreating   0          4s    <none>   node3   <none>           <none>
[root@dbSlave app-k3s-test]# kubectl --kubeconfig=/home/wjl/dockerCompose/gitlab-runner-k3s/k3s/config describe pod app-k3s-test-555bddb6b9-brwpv -n zbwt-prod
Name:             app-k3s-test-555bddb6b9-brwpv
Namespace:        zbwt-prod
Priority:         0
Service Account:  default
Node:             node3/10.111.160.14
Start Time:       Mon, 12 May 2025 18:50:59 +0800
Labels:           app=app-k3s-test
                  pod-template-hash=555bddb6b9
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/app-k3s-test-555bddb6b9
Containers:
  app-k3s-test-container:
    Container ID:   
    Image:          10.111.160.21:39435/app-k3s-test-img:1747040141
    Image ID:       
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      ZBWT_PROFILE:  xxzxtest
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fj7d5 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   False 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  kube-api-access-fj7d5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              zbwt-node-name=node3
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               33s   default-scheduler  Successfully assigned zbwt-prod/app-k3s-test-555bddb6b9-brwpv to node3
  Warning  FailedCreatePodSandBox  33s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox "412e610bba2ddf42b9402b4a59ba1dc0c6b027ecf0b8a5f279af170ae500bd89": failed to get sandbox image "rancher/mirrored-pause:3.6": failed to pull image "rancher/mirrored-pause:3.6": failed to pull and unpack image "docker.io/rancher/mirrored-pause:3.6": failed to resolve reference "docker.io/rancher/mirrored-pause:3.6": pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials
  Warning  FailedCreatePodSandBox  16s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox "7eb5490c2325e04f16d243829e6647086cb8f0676e63d0d3ebef15274ffe88cb": failed to get sandbox image "rancher/mirrored-pause:3.6": failed to pull image "rancher/mirrored-pause:3.6": failed to pull and unpack image "docker.io/rancher/mirrored-pause:3.6": failed to resolve reference "docker.io/rancher/mirrored-pause:3.6": pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials
  Warning  FailedCreatePodSandBox  2s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox "4cd708a9a463f401240b01b783018d1428540c2bf724837b87ad8ac3a08ea6ae": failed to get sandbox image "rancher/mirrored-pause:3.6": failed to pull image "rancher/mirrored-pause:3.6": failed to pull and unpack image "docker.io/rancher/mirrored-pause:3.6": failed to resolve reference "docker.io/rancher/mirrored-pause:3.6": pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials
[root@dbSlave app-k3s-test]#
```

I configured /etc/rancher/k3s/registries.yaml on each node, and the content is as follows. 
```
mirrors:
  "*":
    endpoint:
      - "http://10.111.160.21:39435"
configs:
  "*":
    auth:
      username: admin
      password: Zbwt_123456
```

Why does K3s keep trying to pull images from docker.io? Which step did I do wrong? How should I further identify the problem?
