### DISCUSSION TITLE
Unable to limit resources for Docker-in-containerd containers

### DISCUSSION THREAD

**Discussion by manning-ncsa** [k3s-io/k3s#12377] [Q&A] [answered]
When my k8s cluster was installed using RKE and managed by Rancher, the container runtime was Docker, and my Docker-in-Docker application was constrained by the standard resource limit mechanism. Since migrating to a new K3s cluster, where the container runtime is instead containerd, my application (now "docker-in-containerd" ) still runs properly but is no longer constrained by the resource limits. I have tested and verified this effect explicitly by running a simple Ubuntu-based container with the `stress` package installed.

I would have thought that the container running the official `docker:dind` image would be treated like any other process and would be limited, but perhaps because it must run with "privileged" securityContext it is able to avoid enforcement? Is there a way to configure K3s to constrain Docker containers?

### Cluster information:

Kubernetes version: v1.30.6+k3s1
Cloud being used: OpenStack (non-commercial)
Installation method: K3s
Host OS: Ubuntu 24.04

**Comment by brandond** [comment]
I'm not aware of any issues with pod resource limits, regardless of what is running within the pod.

Can you provide an example pod manifest that demonstrates the issue?

**Comment by manning-ncsa** [comment]
The pod manifest I used to demonstrate the problem is copied below. The resource limits in the container spec have no effect. However, if you add `docker run` options `--cpus="1.0" --memory="1280m"`, for example, the process will be constrained.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: stress-tester
  namespace: default
  labels:
    app.kubernetes.io/component: stress-tester
spec:
  terminationGracePeriodSeconds: 5
  volumes:
    - name: dind-daemon
      emptyDir: {}
  containers:
    # DinD daemon
    - name: dind
      image: docker:dind
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      args: ["-G", "1000"]
      env:
        - name: DOCKER_HOST
          value: unix:///shared/docker.sock
        - name: DOCKER_CLIENT_TIMEOUT
          value: "120"
      volumeMounts:
        - name: dind-daemon
          mountPath: /shared
      resources:
        limits:
          memory: "1Gi"
          cpu: "1000m"
        requests:
          memory: "100Mi"
          cpu: "100m"
    # Stress tester: Docker
    - name: stress-tester-docker
      image: stress-tester:latest
      imagePullPolicy: IfNotPresent
      command:
        - /bin/bash
      args:
        - -c
        - |
          sleep 5 && \
          docker run --rm --entrypoint "/bin/bash" \
          stress-tester:latest \
          -c "
              /usr/bin/stress \
                --verbose \
                --cpu "4" \
                --vm "1" \
                --vm-bytes "1500M" \
                --vm-keep \
            "
      env:
        - name: DOCKER_HOST
          value: unix:///shared/docker.sock
        - name: DOCKER_CLIENT_TIMEOUT
          value: "120"
      volumeMounts:
        - name: dind-daemon
          mountPath: /shared
      resources:
        limits:
          memory: "1Gi"
          cpu: "1000m"
        requests:
          memory: "100Mi"
          cpu: "100m"
```

`stress-tester` Dockerfile:

```dockerfile
FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
    stress \
    && rm -rf /var/lib/apt/lists/*

COPY ./install_docker.sh /tmp/
RUN bash /tmp/install_docker.sh
```

**Reply by dereknola** [reply]
So this setup isn't actually using Docker-in-Docker? You are mounting the host docker socket, escaping all the controls k8s has over the pod. 

The pod itself will use almost no resources, its just a bash script of 4 lines that launch a docker command. 

This is effectively the same as just running `docker run --rm --entrypoint "/bin/bash"...` on the host. So k3s has no control over the resulting docker container.

**Reply by brandond** [reply]
`E0520 19:18:55.925653      54 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"stress-tester-docker\" with ErrImagePull: \"failed to pull and unpack image \\\"docker.io/library/stress-tester:latest\\\": failed to resolve reference \\\"docker.io/library/stress-tester:latest\\\": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed\"" pod="default/stress-tester" podUID="057a33e1-9556-4835-ad75-6119baf4bc48"`

```console
brandond@dev01:~$ docker pull stress-tester:latest
Error response from daemon: pull access denied for stress-tester, repository does not exist or may require 'docker login'
```

What is this image that you're running? It does not seem to exist.

**Reply by manning-ncsa** [reply]
> What is this image that you're running? It does not seem to exist.

It is a local image built from the Dockerfile [at the bottom of my post this morning](https://github.com/k3s-io/k3s/discussions/12377#discussioncomment-13208940).

**Reply by brandond** [reply]
OK and what is `./install_docker.sh`?

I assume that the COPY/RUN lines could be replaced with
```
ADD https://get.docker.com /tmp/docker_install.sh
RUN sh /tmp/docker_install.sh
```

**Reply by manning-ncsa** [reply]
You are correct. My `install_docker.sh` is copied below. The purpose is to install the Docker CLI in the "stress-test" container.

```bash
#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive

# Add Docker's official GPG key:
apt-get update
apt-get install -y --no-install-recommends ca-certificates curl
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install -y --no-install-recommends docker-ce-cli
rm -rf /var/lib/apt/list/*
```

**Reply by brandond** [reply, marked as answer]
You're running dind as a privileged container. As such, it is able to launch processes outside the cgroup hierarchy managed by the kubelet. If you don't want it to be able to do this, don't run it privileged.

```console
root@k3s-server-001:~# ps
PID   USER     COMMAND
    1 root     /bin/k3s init
   54 root     {exe} k3s server
   72 root     containerd
  741 root     /bin/containerd-shim-runc-v2 -namespace k8s.io -id 2996a9b70d30a65d07aba7d630bfee61e8f492cdef47cd3bb0721acdc6da1edd -address /run/k3s/containerd/containerd.sock -debug
  812 root     /bin/containerd-shim-runc-v2 -namespace k8s.io -id d73bead1299c76eb4034cecfff47b37ff639fd21749804c5119850a6148407e2 -address /run/k3s/containerd/containerd.sock -debug
  852 root     /bin/containerd-shim-runc-v2 -namespace k8s.io -id 4ac15420562648f7599afd1fd6d840e99ec7fc71f26fd52b5282ebd28c48b306 -address /run/k3s/containerd/containerd.sock -debug
  863 65535    /pause
  907 65535    /pause
  926 65535    /pause
 1132 root     local-path-provisioner start --config /etc/config/config.json
 1175 1000     /metrics-server --cert-dir=/tmp --secure-port=10250 --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --kubelet-use-node-status-port --metric-resolution=15s --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_
 1212 65532    /coredns -conf /etc/coredns/Corefile
 1748 root     /bin/containerd-shim-runc-v2 -namespace k8s.io -id 2cbf00135a3920b064c526e95f9a4b6f1d61d967928cf4a7d57b96ae2578bfce -address /run/k3s/containerd/containerd.sock -debug
 1768 65535    /pause
 1828 root     /bin/containerd-shim-runc-v2 -namespace k8s.io -id ec8a675c9d6871bd6d8919ec80d250bd885c7777363d1283b124ccb30e4479d8 -address /run/k3s/containerd/containerd.sock -debug
 1847 65532    /pause
 2090 root     {entry} /bin/sh /usr/bin/entry
 2136 root     {entry} /bin/sh /usr/bin/entry
 2218 65532    traefik traefik --global.checknewversion --global.sendanonymoususage --entrypoints.metrics.address=:9100/tcp --entrypoints.traefik.address=:9000/tcp --entrypoints.web.address=:8000/tcp --entrypoints.websecure.address=
 2360 root     /bin/containerd-shim-runc-v2 -namespace k8s.io -id 700bea50ddf4d15597bf68b9e3fec0695434592306aa25efadd7ea43381b1296 -address /run/k3s/containerd/containerd.sock -debug
 2380 65535    /pause
 2473 root     docker-init -- dockerd --host=unix:///shared/docker.sock --host=tcp://0.0.0.0:2376 --tlsverify --tlscacert /certs/server/ca.pem --tlscert /certs/server/cert.pem --tlskey /certs/server/key.pem -G 1000
 2538 root     dockerd --host=unix:///shared/docker.sock --host=tcp://0.0.0.0:2376 --tlsverify --tlscacert /certs/server/ca.pem --tlscert /certs/server/cert.pem --tlskey /certs/server/key.pem -G 1000
 2552 root     containerd --config /var/run/docker/containerd/containerd.toml
 2774 root     docker run --rm --entrypoint /bin/bash docker.io/brandond/stress-tester:latest -c      /usr/bin/stress       --verbose       --cpu 4       --vm 1       --vm-bytes 1500M       --vm-keep
 2881 root     /usr/local/bin/containerd-shim-runc-v2 -namespace moby -id 0debe79ffe5d932a8c4c80ae09f0d0059e3879be7fc3e163f749e8ae8156559f -address /var/run/docker/containerd/containerd.sock
 2903 root     /usr/bin/stress --verbose --cpu 4 --vm 1 --vm-bytes 1500M --vm-keep
 2918 root     /usr/bin/stress --verbose --cpu 4 --vm 1 --vm-bytes 1500M --vm-keep
 2919 root     /usr/bin/stress --verbose --cpu 4 --vm 1 --vm-bytes 1500M --vm-keep
 2920 root     /usr/bin/stress --verbose --cpu 4 --vm 1 --vm-bytes 1500M --vm-keep
 2921 root     /usr/bin/stress --verbose --cpu 4 --vm 1 --vm-bytes 1500M --vm-keep
 2922 root     /usr/bin/stress --verbose --cpu 4 --vm 1 --vm-bytes 1500M --vm-keep
 3333 root     sh
 3729 root     ps

root@k3s-server-001:~# cat /proc/2538/cgroup
0::/kubepods/burstable/podf3a7f204-9246-41ee-8f96-9b8732915ef7/959ea2cb9a363f91e8950870c25f85540cec72056f0b7d968d4c6660d4e99233

root@k3s-server-001:~# cat /sys/fs/cgroup/kubepods/burstable/podf3a7f204-9246-41ee-8f96-9b8732915ef7/959ea2cb9a363f91e8950870c25f85540cec72056f0b7d968d4c6660d4e99233/memory.max
1073741824

root@k3s-server-001:~# cat /proc/2903/cgroup
0::/docker/0debe79ffe5d932a8c4c80ae09f0d0059e3879be7fc3e163f749e8ae8156559f

root@k3s-server-001:~# cat /sys/fs/cgroup/docker/0debe79ffe5d932a8c4c80ae09f0d0059e3879be7fc3e163f749e8ae8156559f/memory.max
max
```

**Reply by brandond** [reply]
You might consider setting the `--cgroup-parent` option in the dockerd container. From the dockerd docs:

> The --cgroup-parent option lets you set the default cgroup parent for containers. If this option isn't set, it defaults to /docker for the cgroupfs driver, and system.slice for the systemd cgroup driver.
> 
> If the cgroup has a leading forward slash (/), the cgroup is created under the root cgroup, otherwise the cgroup is created under the daemon cgroup.

Although even with that it seems like the limits are overridden by dockerd:
```console
# dockerd container cgroup
root@k3s-server-001:~# cat /sys/fs/cgroup/kubepods/burstable/podceaa2b58-5c85-40a7-af30-e1f90bfd9b7c/d7e82edeb05d13e164e162abe7b8e21fb46cc54618626c7e2ef7ded9a328b135/memory.max
1073741824

# stress container cgroup
root@k3s-server-001:~# cat /sys/fs/cgroup/kubepods/burstable/podceaa2b58-5c85-40a7-af30-e1f90bfd9b7c/docker/14028fa2203ad731146149b9fde265ce3367c05e30ed8b28cab8bd7cfac5dfb5/memory.max
max

# dockerd-managed group-parent cgroup
root@k3s-server-001:~# cat /sys/fs/cgroup/kubepods/burstable/podceaa2b58-5c85-40a7-af30-e1f90bfd9b7c/docker/memory.max
max

# pod root cgroup
root@k3s-server-001:~# cat /sys/fs/cgroup/kubepods/burstable/podceaa2b58-5c85-40a7-af30-e1f90bfd9b7c/memory.max
2147483648
```

**Reply by manning-ncsa** [reply]
Thanks for explaining the root cause of the problem. Indeed I was worried that cgroups were the culprit based on my research, but I do not understand cgroups enough to know how to investigate further.

But good news: This discussion sparked the idea to try the `docker:dind-rootless` image instead of `docker:dind`, and sure enough, the Kubernetes resource constraints are enforced! No other changes to the manifest are needed. Thanks to you and @dereknola for taking the time to help me solve this.

**Reply by brandond** [reply]
That's great! I haven't tinkered with rootless dind much. 

After a bit of tinkering, this seems to work too, if you need a privileged docker for some reason:
```yaml
  containers:
    # DinD daemon
    - name: dind
      image: docker:dind
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command: 
        - "/bin/sh"
      args:
        - -c
        - | 
          exec dockerd-entrypoint.sh -G 1000 --cgroup-parent $(cut -d: -f3 /proc/self/cgroup)/docker
```
