### DISCUSSION TITLE
Cilium with ipam cluster-pool mode - what are the effects of --cluster-cidr and --service-cidr on k3s?

### DISCUSSION THREAD

**Discussion by cytrinox** [k3s-io/k3s#12437] [Q&A] [answered]
I'm testing a k3s deployment with 7 nodes (3 server, 4 agents) on Hetzner Cloud. I want to use Cilium and k3s without servicelb/kube-proxy.

For cilium, my helm config looks like:

```yaml
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: "10.144.0.0/14"
encryption:
  enabled: true
  type: 'wireguard'
  nodeEncryption: true
```

I'm confused about `--cluster-cidr` and `--service-cidr` arguments for k3s-server. Are they relevant in cluster-pool mode at all?
