### DISCUSSION TITLE
How to set the `readOnlyPort` parameter?

### DISCUSSION THREAD

**Discussion by shangjianan2** [k3s-io/k3s#12489] [Q&A] [answered]
With reference to the link "https://docs.k3s.io/installation/airgap", I successfully deployed a k3s cluster. Now I want to view and modify the readOnlyPort configuration to close the 10255 port.

I checked the corresponding introduction in the article "https://docs.k3s.io/security/self-assessment-1.23?_highlight=readonlyport#424-ensure-that-the---read-only-port-argument-is-set-to-0-manual", but I still don't know how to modify the parameter.

According to the content of the article "https://docs.k3s.io/security/self-assessment-1.23?_highlight=readonlyport#424-ensure-that-the---read-only-port-argument-is-set-to-0-manual", I made the following attempt:
First, execute the command journalctl -D /var/log/journal -u k3s | grep 'Running kubelet' | tail -n1 | grep 'read-only-port' to check the current value.

```
[root@dbSlave kubelet.conf.d]# journalctl -D /var/log/journal -u k3s | grep 'Running kubelet' | tail -n1 | grep 'read-only-port'
[root@dbSlave kubelet.conf.d]# journalctl -D /var/log/journal -u k3s | grep 'Running kubelet' | tail -n1
May 13 10:59:03 dbSlave k3s[3069]: time="2025-05-13T10:59:03+08:00" level=info msg="Running kubelet --cloud-provider=external --config-dir=/var/lib/rancher/k3s/agent/etc/kubelet.conf.d --containerd=/run/k3s/containerd/containerd.sock --hostname-override=dbslave --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --node-ip=10.111.160.26 --node-labels="
[root@dbSlave kubelet.conf.d]# 
```

The command journalctl -D /var/log/journal -u k3s | grep 'Running kubelet' | tail -n1 | grep 'read-only-port' produced no output.

Next, I want to set read-only-port to 0 but don't know which file to modify. I don't have the /etc/systemd/system/kubelet.service.d/10-kubeadm.conf file mentioned in the article. Additionally, the output of journalctl -D /var/log/journal -u k3s | grep 'Running kubelet' | tail -n1 mentions --config-dir=/var/lib/rancher/k3s/agent/etc/kubelet.conf.d, which appears to be the configuration directory. However, the configuration files in this directory do not include the read-only-port setting.
```
[root@dbSlave kubelet.conf.d]# pwd
/var/lib/rancher/k3s/agent/etc/kubelet.conf.d
[root@dbSlave kubelet.conf.d]# cat 00-k3s-defaults.conf 
address: 0.0.0.0
allowedUnsafeSysctls:
- net.ipv4.ip_forward
- net.ipv6.conf.all.forwarding
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /var/lib/rancher/k3s/agent/client-ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
clusterDNS:
- 10.43.0.10
clusterDomain: cluster.local
containerRuntimeEndpoint: unix:///run/k3s/containerd/containerd.sock
cpuManagerReconcilePeriod: 10s
crashLoopBackOff: {}
evictionHard:
  imagefs.available: 5%
  nodefs.available: 5%
evictionMinimumReclaim:
  imagefs.available: 10%
  nodefs.available: 10%
evictionPressureTransitionPeriod: 5m0s
failSwapOn: false
fileCheckFrequency: 20s
healthzBindAddress: 127.0.0.1
httpCheckFrequency: 20s
imageMaximumGCAge: 0s
imageMinimumGCAge: 2m0s
kind: KubeletConfiguration
logging:
  flushFrequency: 5s
  format: text
  options:
    json:
      infoBufferSize: "0"
    text:
      infoBufferSize: "0"
  verbosity: 0
memorySwap: {}
nodeStatusReportFrequency: 5m0s
nodeStatusUpdateFrequency: 10s
resolvConf: /etc/resolv.conf
runtimeRequestTimeout: 2m0s
serializeImagePulls: false
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /var/lib/rancher/k3s/agent/pod-manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
tlsCertFile: /var/lib/rancher/k3s/agent/serving-kubelet.crt
tlsPrivateKeyFile: /var/lib/rancher/k3s/agent/serving-kubelet.key
volumeStatsAggPeriod: 1m0s
[root@dbSlave kubelet.conf.d]# 
```

So how should I modify the `read-only-port`?
