### DISCUSSION TITLE
k3s configmap volume mount behavior

### DISCUSSION THREAD

**Discussion by hholst80** [k3s-io/k3s#3109] [Q&A]
I am not sure if this is intended behavior or not, but I tried to update a ConfigMap and I could not see that the ConfigMap was updated inside the container that target the configmap as a volume mount. The man page is a bit detailed on how the mapping is eventually updated so maybe this is expected behavior idk?

https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically

**Environmental Info:**
K3s Version: 

    k3s version v1.20.2+k3s1 (1d4adb03)
    go version go1.15.5

Node(s) CPU architecture, OS, and Version: 

     Linux centsoft 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

    single node

**Describe the bug:**

Volume mounted configmap not updated on `kubectl apply -f cm.yaml`

**Steps To Reproduce:**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  STAGED-prometheus.yml: |
    nothing-important: here
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: victoriametrics/victoria-metrics:v1.56.0
        ports:
        - containerPort: 8428
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/STAGED-prometheus.yml
          subPath: STAGED-prometheus.yml
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
```
