### DISCUSSION TITLE
Show limited mem and cpu **inside** containers

### DISCUSSION THREAD

**Discussion by nsoubelet** [k3s-io/k3s#3190] [Q&A]
Hello,

After several weeks of investigation of an issue which I don't really know how to solve, just decided to drop it here in case anyone else ever wonder about it.

Basically when using resource limits in k3s (I assume k8s behaves the same), inside the container the total available is always host's.
This happens in Docker and Containerd.
Just to give an example, we've got the following limits in a Pod:

```
resources:
    requests:
      cpu: "0.50"
      memory: "512Mi"
      ephemeral-storage: "512Mi"
    limits:
      cpu: "0.50"
      memory: "512Mi"
      ephemeral-storage: "512Mi"
```
However, when running `cat /proc/meminfo` **inside** the container I see the following values:
```
MemTotal:        4039316 kB
MemFree:          638464 kB
MemAvailable:    1766156 kB
```
... which is host's.

I am not saying that effectively containers in pod exceeds limits, it's just that I find surprising that the information given does not reflect container's limits.
I could not find too much people complaining about it so I wonder whether it is only me seeing this (a misconfiguration?) or this is something accepted in general.

Hope anyone is interested in the topic.

Thanks
