### DISCUSSION TITLE
traefik metrics disabled by default ?

### DISCUSSION THREAD

**Discussion by jeanpommier** [k3s-io/k3s#3522] [Q&A] [answered]
Hi,
I was pretty much certain that the Traefik metrics were available by default, for scrape by prometheus. But apparently, they are not
![image](https://user-images.githubusercontent.com/4491521/123665831-eebc0600-d838-11eb-9509-2f221123aee7.png)

It seems like a pity, to me. Is there an easy way to enable them ?
Thanks

**Comment by ChristianCiach** [comment, marked as answer]
You can customize the bundled Traefik by deploying a `HelmChartConfig`:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - '--metrics.prometheus=true'
      - '--metrics.prometheus.entryPoint=metrics'
    ports:
      metrics:
        port: 8082
```

See https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig
