### DISCUSSION TITLE
Unable to connect to pod's container IP; works in Docker

### DISCUSSION THREAD

**Discussion by budney** [k3s-io/k3s#3915] [Q&A] [answered]
**Environmental Info:**
K3s Version: v1.21.3+k3s1 (1d1f220f)

Node(s) CPU architecture, OS, and Version: Linux k8s-01 5.11.0-1016-raspi #17-Ubuntu SMP PREEMPT aarch64 GNU/Linux

Cluster Configuration: 1 node, 1 server, out-of-the-box setup

My pod runs a DNS resolver on port 53. From a shell in the same container, I can connect to the resolver on 127.0.0.1, but NOT on the container's IP address (10.42.0.99). Running the same image in Docker, I can connect to either IP address. I've attached steps to reproduce the failure in k3s and the success in Docker. Just to add to the mystery, I installed nmap and it claims port 53 is open on the container IP -- but nslookup nevertheless times out trying to connect to it.

**Steps To Reproduce:**
1. Install k3s: `curl -sfL https://get.k3s.io | sh -`
2. Don't install any worker nodes.
3. `sudo kubectl apply -f dnscache.yaml`
4. `sudo kubectl get pods`
5. `sudo kubectl exec --stdin --tty pod/dnscache-65b994b978-lwm59 -- /bin/sh`
6. Inside the container: `nslookup cnn.com 127.0.0.1` (This works as expected.)
7. `nslookup cnn.com $(ifconfig eth0 | sed -nr '/.*inet addr:1/s/^.*inet addr:([^ ]+).*$/\1/p')`
The latter command times out with the message, "no servers could be reached."

- Installed K3s: 

**Expected behavior:**

`nslookup` should succeed when pointed at either IP address. When these steps are followed in a Docker container based on the same image, it works exactly as expected.

**Actual behavior:**

`nslookup` times out when pointed at the eth0 IP address, but succeeds when pointed at 127.0.0.1.

**Additional context / logs:**

I've attached the deployment/service YAML file that I used, renamed to dnscache.txt because the .yaml was rejected.
[dnscache.txt](https://github.com/k3s-io/k3s/files/7050570/dnscache.txt)

**Backporting**

- [ ] Needs backporting to older releases

**Comment by ChristianCiach** [comment]
> nslookup cnn.com $(ifconfig eth0

I don't understand what you're trying to do here. This will get you the IP address of the host, *not* the IP adress of the container. If this really works with your docker setup (which you haven't shown us), then you surely mapped the port 53/udp to your host.

There are multiple ways to do that with Kubernetes. For example, when using K3s, you can use the integrated load balancer (klipper-lb). To use that, change the type of your Service to LoadBalancer:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: dnscache
spec:
  selector:
    app: dnscache
  ports:
    - name: dnscache-53-udp
      port: 53
      protocol: UDP
      targetPort: 53
  type: LoadBalancer
```

Alternatively, you could ditch the Service altogether and just bind the Pod directly to the host by adding the `hostPort` attribute:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnscache
  labels:
    app: dnscache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnscache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dnscache
    spec:
      containers:
        - name: dnscache
          image: budney/djbdns
          env:
            - name: delegate
              value: lan.jeenyus.net:153.18.172.in-addr.arpa
            - name: service
              value: dnscache
          ports:
            - name: dnscache-53-udp
              containerPort: 53
              hostPort: 53
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /docker-compose.yml
              name: dnscache-hostpath0
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /etc/djbdns/docker-compose.yml
          name: dnscache-hostpath0
```

Anyway, why are you mounting a docker-compose-file into the container?

Edit: You seem to be new to Kubernetes and this looks more like a question than an issue. I think this issue should be moved to "Discussions".
