### DISCUSSION TITLE
unable to figure out how to configure credentials for dockerhub

### DISCUSSION THREAD

**Discussion by itai-codefresh** [k3s-io/k3s#3938] [Q&A]
i am trying to configure credentials for dockerhub in registry configuration file so that i will not hit rate limit

i have tried endless configuration without success.

what am i doing wrong?

```
mirrors:
  docker.io:
    endpoint:
      - https://registry-1.docker.io
configs:
  docker.io:
    auth:
      username: ***
      password: ***
```
