### DISCUSSION TITLE
Failed to initialize NVML in K3s

### DISCUSSION THREAD

**Discussion by audrey-siqueira** [k3s-io/k3s#4081] [Q&A]
Hi, my company has  a local server with cpu and 2 GPUs, we are working with docker and Kubernetes.
The problem is that trying to use K3s , I only can set up Kubernetes working in cpu , if I try follow the steps to setup Kubernetes in the GPUs I get the error related with NVML failure.

I tried to follow the steps in this article : https://itnext.io/enabling-nvidia-gpus-on-k3s-for-cuda-workloads-a11b96f967b0

and also tried with this github page : https://github.com/NVIDIA/k8s-device-plugin

I have installed the following:
- Nvidia driver 
- Nvidia container toolkit with Docker and Containerd
- Nvidia K8s device plugin.

As I am using K3s , I dont know if the problem is related with the plugin being K8s.

Below I will write my following logs: 

Node(s) CPU architecture, OS, and Version: 
Linux vdrd 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Cluster with just a single node 

NAME   STATUS   ROLES    AGE   VERSION
vdrd   Ready    master   78m   v1.15.4-k3s.1

**Describe the bug:**
When I analize my Nvidia device plugin I get this output:

(base) bizon@vdrd:~$ sudo ./k3s kubectl get pod -n kube-system
NAME                                   READY   STATUS      RESTARTS   AGE
helm-install-traefik-sg6pz       0/1     Completed   0          91m
svclb-traefik-7tdqk                  3/3     Running     0          91m
nvidia-device-plugin-daemonset-zhv25   1/1     Running     0          40m

(base) bizon@vdrd:~$ sudo ./k3s kubectl logs nvidia-device-plugin-daemonset-zhv25  -n kube-system
2021/09/23 18:57:59 Loading NVML
2021/09/23 18:57:59 Failed to initialize NVML: could not load NVML library.
2021/09/23 18:57:59 If this is a GPU node, did you set the docker default runtime to `nvidia`?
2021/09/23 18:57:59 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2021/09/23 18:57:59 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
2021/09/23 18:57:59 If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes

**Additional context / logs:**

(base) bizon@vdrd:~$ sudo ./k3s kubectl describe pod -n kube-system
Name:           helm-install-traefik-sg6pz
Namespace:      kube-system
Priority:       0
Node:           vdrd/10.18.0.208
Start Time:     Thu, 23 Sep 2021 13:06:32 -0500
Labels:         controller-uid=a5ae2c71-14e1-46df-b3f8-18f4203eafbc
                helmcharts.helm.cattle.io/chart=traefik
                job-name=helm-install-traefik
Annotations:    <none>
Status:         Succeeded
IP:             10.42.0.52
Controlled By:  Job/helm-install-traefik
Containers:
  helm:
    Container ID:  containerd://33992d1953262fa1b461fa3f74a4f8526e853e4348ab4675e7ed617293c673cc
    Image:         rancher/klipper-helm:v0.1.5
    Image ID:      docker.io/rancher/klipper-helm@sha256:72690de1ae2259a41075e87ff453936a74e0f2dbf2ad1dd96a4f72136a48038d
    Port:          <none>
    Host Port:     <none>
    Args:
      install
      --name
      traefik
      https://%{KUBERNETES_API}%/static/charts/traefik-1.77.1.tgz
      --set-string
      kubernetes.ingressEndpoint.useDefaultPublishedService=true
      --set-string
      metrics.prometheus.enabled=true
      --set-string
      rbac.enabled=true
      --set-string
      ssl.enabled=true
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 23 Sep 2021 13:06:42 -0500
      Finished:     Thu, 23 Sep 2021 13:06:44 -0500
    Ready:          False
    Restart Count:  0
    Environment:
      NAME:         traefik
      VERSION:      
      REPO:         
      VALUES_HASH:  e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      NO_PROXY:     ,10.42.0.0/16,10.43.0.0/16
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from helm-traefik-token-vcgc2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  helm-traefik-token-vcgc2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  helm-traefik-token-vcgc2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

Name:           svclb-traefik-7tdqk
Namespace:      kube-system
Priority:       0
Node:           vdrd/10.18.0.208
Start Time:     Thu, 23 Sep 2021 13:06:44 -0500
Labels:         app=svclb-traefik
                controller-revision-hash=654fd96bbb
                pod-template-generation=1
                svccontroller.k3s.cattle.io/svcname=traefik
Annotations:    <none>
Status:         Running
IP:             10.42.0.54
Controlled By:  DaemonSet/svclb-traefik
Containers:
  lb-port-80:
    Container ID:   containerd://e63a0698d070f2eaa189d47ceb344f4bb67406c1b55560307d58e0147a31752a
    Image:          rancher/klipper-lb:v0.1.1
    Image ID:       docker.io/rancher/klipper-lb@sha256:2cff68f14dd050a5ab16b59a55d5ba34d6edc3f6edfc1ec5bd4e437d4ba47290
    Port:           80/TCP
    Host Port:      80/TCP
    State:          Running
      Started:      Thu, 23 Sep 2021 13:06:48 -0500
    Ready:          True
    Restart Count:  0
    Environment:
      SRC_PORT:    80
      DEST_PROTO:  TCP
      DEST_PORT:   80
      DEST_IP:     10.43.238.124
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5pwlw (ro)
  lb-port-443:
    Container ID:   containerd://88e9dc96b6113f5e12239c5bc90b970d74d023548623095fc2f4ae4bd6a773da
    Image:          rancher/klipper-lb:v0.1.1
    Image ID:       docker.io/rancher/klipper-lb@sha256:2cff68f14dd050a5ab16b59a55d5ba34d6edc3f6edfc1ec5bd4e437d4ba47290
    Port:           443/TCP
    Host Port:      443/TCP
    State:          Running
      Started:      Thu, 23 Sep 2021 13:06:48 -0500
    Ready:          True
    Restart Count:  0
    Environment:
      SRC_PORT:    443
      DEST_PROTO:  TCP
      DEST_PORT:   443
      DEST_IP:     10.43.238.124
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5pwlw (ro)
  lb-port-8080:
    Container ID:   containerd://973ceadecc2a98bb84b2e82cdf742c85cec29a299f630459b1c279bdc88c8966
    Image:          rancher/klipper-lb:v0.1.1
    Image ID:       docker.io/rancher/klipper-lb@sha256:2cff68f14dd050a5ab16b59a55d5ba34d6edc3f6edfc1ec5bd4e437d4ba47290
    Port:           8080/TCP
    Host Port:      8080/TCP
    State:          Running
      Started:      Thu, 23 Sep 2021 13:06:48 -0500
    Ready:          True
    Restart Count:  0
    Environment:
      SRC_PORT:    8080
      DEST_PROTO:  TCP
      DEST_PORT:   8080
      DEST_IP:     10.43.238.124
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5pwlw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-5pwlw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5pwlw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:          <none>

Name:                 nvidia-device-plugin-daemonset-zhv25
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 vdrd/10.18.0.208
Start Time:           Thu, 23 Sep 2021 13:57:48 -0500
Labels:               controller-revision-hash=777485bb46
                      name=nvidia-device-plugin-ds
                      pod-template-generation=1
Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Running
IP:                   10.42.0.59
Controlled By:        DaemonSet/nvidia-device-plugin-daemonset
Containers:
  nvidia-device-plugin-ctr:
    Container ID:  containerd://852a448c80cbdd69738c66295ce8a301accf6c50e9d62bf582d7a29280242c5c
    Image:         nvcr.io/nvidia/k8s-device-plugin:v0.9.0
    Image ID:      nvcr.io/nvidia/k8s-device-plugin@sha256:964847cc3fd85ead286be1d74d961f53d638cd4875af51166178b17bba90192f
    Port:          <none>
    Host Port:     <none>
    Args:
      --fail-on-init-error=false
    State:          Running
      Started:      Thu, 23 Sep 2021 13:57:59 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5pwlw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:  
  default-token-5pwlw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5pwlw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
                 nvidia.com/gpu:NoSchedule
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  38m   default-scheduler  Successfully assigned kube-system/nvidia-device-plugin-daemonset-zhv25 to vdrd
  Normal  Pulling    38m   kubelet, vdrd      Pulling image "nvcr.io/nvidia/k8s-device-plugin:v0.9.0"
  Normal  Pulled     38m   kubelet, vdrd      Successfully pulled image "nvcr.io/nvidia/k8s-device-plugin:v0.9.0"
  Normal  Created    38m   kubelet, vdrd      Created container nvidia-device-plugin-ctr
  Normal  Started    38m   kubelet, vdrd      Started container nvidia-device-plugin-ctr

I edited my daemon json file to turn nvidia runtime container as my default like this:

{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}

I installed the plugin using this command:  $ kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.9.0/nvidia-device-plugin.yml

I was investigating and checked that could be any miss understanding involving /var/lib/kubelet/  and /var/lib/rancher/k3s/agent/kubelet 

Anyone could help me? I really need to set K3s working with GPUs.

**Comment by brandond** [comment]
You might give 1.22 a try once it's out later today. All you should need to do is install the correct runtime package on your node and then you can create and use the appropriate RuntimeClass for your pods.

* https://github.com/k3s-io/k3s/pull/3890

**Comment by audrey-siqueira** [comment]
Thank you for your quickly anwser.

I just installed 1.22 version now  but is not clear how to proceed now , could you explain in more details?

What do you mean with correct runtime package? k3s package itself?

Since that I already have the new version I dont need change config template?

Should I use the daemonset plugin yet?

I would appreciate if you give me more details

thanks

**Comment by brandond** [comment]
no... just install the nvidia-container-runtime package for your distro.  K3s will find it if it's present during startup, and create the appropriate containerd runtime definitions.
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

You will still need to create the Kubernetes RuntimeClass manually, and specify it on your pods.

**Comment by brandond** [comment]
@kralicky do you have a quickstart guide for this anywhere?

**Comment by audrey-siqueira** [comment]
Got it, I already have nvidia container toolkit installed for my distro.

What would be Runtime Class ?

Specify for my pods would be these commands below? 

resources:
            limits:
              nvidia.com/gpu: 1

Whats about nvidia plugin? Should be installed yet?

@kralicky , could you provide me this quickstart guide or at least few commands to get my GPU working in K3s?

**Comment by audrey-siqueira** [comment]
This is the config.toml in /var/lib/rancher/k3s/agent/etc/containerd    available in version 1.22


```toml
[plugins.opt]
  path = "/var/lib/rancher/k3s/agent/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "rancher/mirrored-pause:3.1"

[plugins.cri.containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true


[plugins.cri.cni]
  bin_dir = "/var/lib/rancher/k3s/data/b99dacddf9c5d24f43e2af7402f9cbc0438f77f463d06ce93937cdff081fc9a8/bin"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"


[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins.cri.containerd.runtimes."nvidia"]
  runtime_type = "io.containerd.runc.v2"
[plugins.cri.containerd.runtimes."nvidia".options]
  BinaryName = "/usr/bin/nvidia-container-runtime"
```

From what i understand , I should create a **runtimeclass.yaml** file like this :

```yaml
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
   name:"nvidia"
handler:"nvidia"
```

**But I dont know if  (" ") are allowed, it is returning me an error of conversion when I try :** 
`sudo ./k3s kubectl apply -f runtimeclass.yaml`

Then I should include in my deployment file like this :

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clasificacion-total-deployment

spec: 
  replicas: 4
  selector:
    matchLabels:
        app: clasificacion-total-deployment

  template:
    metadata:
      labels:
        app: clasificacion-total-deployment

    spec:
      runtimeClassName:"nvidia"
      containers:
        - name: clasificacion-total-deployment
          image: audrey1990/clasificacion:latest

          resources:
               limits:
                 nvidia.com/gpu: 1

          ports:
            
            - containerPort: 8501
              name: restapi
       
            - containerPort: 8500
              name: grpc
```

**I dont know if I really need to create the nvidia device plugin yet**
**I dont know if I should keep   **resources: limits: nvidia.com/gpu: 1**  in my deployment file.**

Is this how to proceed? Or should I do anything different? I wasnt able yet to conect the GPU.
