### DISCUSSION TITLE
Customizing Packaged Components with HelmChartConfig not working

### DISCUSSION THREAD

**Discussion by hlacikd** [k3s-io/k3s#4415] [Q&A] [answered]
Hello, I am trying to override terminationGracePeriodSeconds in kube-dns  and local-path-provisioner components. According to doc https://rancher.com/docs/k3s/latest/en/helm/ it can be customized using HelmChartConfig,
so I made this

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: kube-dns
  namespace: kube-system
spec:
  valuesContent: |-
    terminationGracePeriodSeconds: 10

---

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  valuesContent: |-
    terminationGracePeriodSeconds: 10
```

and put it to /var/lib/rancher/k3s/server/manifests/custom-config.yaml
However after restarting k3s nothing has changed .

What Am i Doing wrong?
