### DISCUSSION TITLE
Get Traefik to serve IPv6 traffic in dual-stack setup

### DISCUSSION THREAD

**Discussion by strayer** [k3s-io/k3s#5003] [Q&A] [answered]
Based on the recent changes I got a simple dual-stack cluster running in a VM but discovered that the Traefik ingress still is set to only run on IPv4.

I assume this was not yet updated… should I remove the default Traefik ingress and try to get this working myself or is it possible to change the Traefik deployment to utilize dual stack?

**Comment by strayer** [comment, marked as answer]
In case anyone is having the same problem, this helm chart config seems to have made Traefik dual-stack aware:

```yaml
# /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        ipFamilyPolicy: RequireDualStack
```
