### DISCUSSION TITLE
how to transfer a docker container to k3s?

### DISCUSSION THREAD

**Discussion by lidh15** [k3s-io/k3s#5845] [Q&A]
Previously I have a container started with something like
"docker run --rm -it --shm-size 32G -privileged --cap-add IPC_LOCK -p 8000:80 -v /home/myhome:/workspace -d myimages /usr/sbin/init"

you see I have used following arguments:
--rm
-it
--shm-size
--privileged
--cap-add
-p
-v
-d

And now it seems that I need to run "k3s crictl run container-config.json pod-config.json"

But I don't know how I should put these arguments into the "config.json"s.

Would you please offer an example supporting these arguments?

**Comment by brandond** [comment]
I would probably convert it to a proper Kubernetes pod, not just continue running it standalone. Is there any particular reason you're installing Kubernetes but still running containers by hand?

**Comment by lidh15** [comment]
> I would probably convert it to a proper Kubernetes pod, not just continue running it standalone. Is there any particular reason you're installing Kubernetes but still running containers by hand?

yes I'm eager to convert it to a pod, and Googled for the whole weekend. 

Seems that I need to use Helm and build all my stuffs into a private chart (or "application" called something else).

In Helm we can manipulate those tons of YAMLs and hopefully find positions for all my arguments.

Am I right? I see repo Helm-controller under k3s-io, is it what I'm looking for?

**Comment by brandond** [comment]
If you're just getting started I would probably not go straight to Helm. For an initial introduction to Kubernetes, just convert your `docker run` command to a Pod definition, or perhaps a Deployment since pods are not usually created directly.

**Comment by lidh15** [comment]
> If you're just getting started I would probably not go straight to Helm. For an initial introduction to Kubernetes, just convert your `docker run` command to a Pod definition, or perhaps a Deployment since pods are not usually created directly.

okay, start from creating Deployment, as I still have no idea how to put my arguments into the yaml, I found the following deployment.yaml online for test:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      # manage pods with the label app: nginx
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

And then I tried `k3s kubectl create -f deployment.yaml` 

it created the app but when I get the pods they are stuck in Container Creating status.

describe pods returned that kubelet failed to create pod sandbox: rpc error, error response from daemon: docker-containerd-shim not installed on system.
