### DISCUSSION TITLE
extra bind feature like rke and service_node_port_range?

### DISCUSSION THREAD

**Discussion by segator** [k3s-io/k3s#5887] [General]
How can I set up 
```
services:
    kube-api:
      service_node_port_range: 30000-32767
    kubelet:
      extra_binds:
        - "/mnt:/mnt:shared"
```
for k3s command line?

Thanks!
