### DISCUSSION TITLE
traefik daemon edit not working

### DISCUSSION THREAD

**Discussion by lidh15** [k3s-io/k3s#5917] [General]
using k3s-1.24.2-k3s1 as 80 port is not available at my machine, I tried to `k3s kubectl edit daemonset svclb-traefik-53792b1c -n kube-system`

I changed the environment variable SRC_PORT in  spec.template.spec.containers.env from 80 to 8080, and spec.template.spec.containers.env.ports.hostPort also from 80 to 8080.

but edit neither one nor both worked.
I described the daemonset and it said that the pods are reload, but still with the original config.

Am I doing something wrong? Or it is not likely to modifying listening host port of traefik daemon set?

**Comment by lidh15** [comment]
okay I googled and it said that this is a feature of k3s, fine fine, but I still need to know how to modify listening port.

**Comment by brandond** [comment]
You need to edit the Traefik helmchart deployment, not the loadbalancer daemonset created to expose traefik.

https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L312

in particular, what you'd want to change would look something like:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        exposedPort: 8080
```
