### DISCUSSION TITLE
Klipper LB does not work with Pod Security

### DISCUSSION THREAD

**Discussion by DmSilkin** [k3s-io/k3s#6106] [Q&A] [answered]
I'm trying to make service running on K3s in rootless mode accessible from company network. As stated in doc  https://rancher.com/docs/k3s/latest/en/advanced/#known-issues-with-rootless-mode , I must use LoadBalancer:
```
apiVersion: v1
kind: Service
metadata: 
  name: my-svc
  labels:
    app: opcua
  namespace: my-namespace
spec:
  ports:
  - port: 48041
    targetPort: 48041 
    name: "driver-port"
  type: LoadBalancer
  selector:
    app: my-app
```

It works fine, but if i apply the PodSecurityPolicy (which is deprecated) or Pod Security Admission with baseline\restricted profile, i get errors:
`my-namespace   2s          Warning   FailedCreate        daemonset/svclb-my-svc                     (combined from similar events): Error creating: pods "svclb-my-svc-s7xlm" is forbidden: violates PodSecurity "baseline:v1.25": non-default capabilities (container "lb-tcp-48041" must not include "NET_ADMIN" in securityContext.capabilities.add), hostPort (container "lb-tcp-48041" uses hostPort 48041)`

How shoud i configure LoadBalancer manifest, so it would work with Pod Security Admission?
