### DISCUSSION TITLE
HelmChart with cert-manager is not working

### DISCUSSION THREAD

**Discussion by hlacikd** [k3s-io/k3s#6243] [Q&A] [answered]
Guys, this is helmchart i am applying to k3s v1.24.4+k3s1 , with kubectl apply -f 

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  targetNamespace: cert-manager
  version: v1.9.1
  repo: https://charts.jetstack.io
  set:
    installCRDs: true
    prometheus.enabled: false
```

it shows OK when applied, however there is not any kind of helm-install action whatsoever inside kube-system namespace

```
➜  k8s-chania git:(main) ✗ kubectl -n kube-system get po
NAME                                      READY   STATUS      RESTARTS        AGE
helm-install-traefik-crd-wwpct            0/1     Completed   0               55m
helm-install-traefik-r6pbx                0/1     Completed   3               55m
svclb-traefik-9aaec338-cwrzr              2/2     Running     6 (6m9s ago)    53m
local-path-provisioner-7b7dc8d6f5-z2k2j   1/1     Running     4 (6m9s ago)    55m
coredns-b96499967-hr2l8                   1/1     Running     4 (6m9s ago)    55m
svclb-traefik-9aaec338-7spzl              2/2     Running     4 (5m58s ago)   53m
metrics-server-668d979685-ghfzg           1/1     Running     4 (6m9s ago)    55m
traefik-7cd4fcff68-hvtsk                  1/1     Running     2 (5m58s ago)   53m
```

what is wrong? ... trying to figure it for 2 days already

**Comment by brandond** [comment]
Check the K3s service logs, do you have any errors from the helm controller?

Also, confirm that your target namespace exists. I usually use a manifest like this:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  targetNamespace: cert-manager
  version: v1.6.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
```

**Comment by RobertoMachorro** [comment, marked as answer]
This issue is showing as un-answered, I just went through this myself and the following works for me under RKE2 and K3S:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: helmcharts
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: 1.17.0
  targetNamespace: cert-manager
  createNamespace: true
  set:
    crds.enabled: "true"
```

* Note that I keep my charts in the _helmcharts_ namespace, edit to your own setup.
