### DISCUSSION TITLE
Traefik & HTTPS backend showing 404 page not found, HTTP working fine

### DISCUSSION THREAD

**Discussion by t-grzelak** [k3s-io/k3s#6256] [Q&A] [answered]
Hello,

I've been struggling for couple of days with a simple setup, but have no idea, what I'm missing. I guess it's a small tiny thing, but I've just run our of all my clues at the moment.
I've set up an apache application with a self-signed certificate and I can reach to the application via NodePorts on both http and https protocols (this is the apache-http(s) application):

```
k3os-01 [~]$ kubectl get service -o wide
NAME           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE     SELECTOR
kubernetes     ClusterIP   10.43.0.1      <none>        443/TCP         5d20h   <none>
apache-http    NodePort    10.43.177.47   <none>        80:32085/TCP    4d19h   app=app-apache
apache-https   NodePort    10.43.43.8     <none>        443:30772/TCP   4d19h   app=app-apache
```

I can get a proper response via the NodePorts on both prototcols while sending requests to the pods directly (the name **_www.local_** points to the IP of the cluster node, 10.200.66.250):

**HTTP:**
```
curl http://www.local:32085/
<html><body><h2>Hello from WWW</h2><br><hr><h4>[ buildkitsandbox ]</h4></body></html>
```

**HTTPS:**
```
curl -kL https://www.local:30772/
<html><body><h2>Hello from WWW</h2><br><hr><h4>[ buildkitsandbox ]</h4></body></html>
```

Now I want to expose the application on regular web ports via Traefik by using Ingress. Exposing this (on the http backend) is working as expected as well:

```
curl -kL https://www.local/
<html><body><h2>Hello from WWW</h2><br><hr><h4>[ buildkitsandbox ]</h4></body></html>
```

My Ingress is set up like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache
  namespace: default
  annotations:

spec:
  rules:
    - host: www.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-http
                port:
                  number: 80
```

```
k3os-01 [~]$ kubectl describe ingress
Name:             apache
Namespace:        default
Address:          10.200.66.250,10.200.66.252,10.200.66.253
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  www.local
              /   apache-http:80 (10.42.4.4:80,10.42.4.5:80)
Annotations:  <none>
Events:       <none>
```

However, when switching to the https backend (and enabling the 'insecureSkipVerify') I'm always getting '404 page not found':

```
curl -kL https://www.local/
404 page not found
```

The Ingress for HTTPS backend is set up as:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.insecureSkipVerify: "true"

spec:
  rules:
    - host: www.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-https
                port:
                  number: 443
```
```
k3os-01 [~/src/k3s/apache]$ kubectl describe ingress
Name:             apache
Namespace:        default
Address:          10.200.66.250,10.200.66.252,10.200.66.253
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  www.local
              /   apache-https:443 (10.42.4.4:443,10.42.4.5:443)
Annotations:  traefik.ingress.kubernetes.io/router.insecureSkipVerify: true
Events:       <none>
```
```
k3os-01 [~/src/k3s/apache]$ kubectl describe service
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.43.0.1
IPs:               10.43.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         10.200.66.250:6443
Session Affinity:  None
Events:            <none>


Name:                     apache-http
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=app-apache
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.177.47
IPs:                      10.43.177.47
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  32085/TCP
Endpoints:                10.42.4.4:80,10.42.4.5:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>


Name:                     apache-https
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=app-apache
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.43.8
IPs:                      10.43.43.8
Port:                     <unset>  443/TCP
TargetPort:               443/TCP
NodePort:                 <unset>  30772/TCP
Endpoints:                10.42.4.4:443,10.42.4.5:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

What am I missing that the connection is failing on the https backed?

I would appreciate your help, as I've been fighting with it for a couple of days already, without any success.

Thank you,
Tomasz

**Comment by brandond** [comment]
You might consider asking this on the Traefik project. It doesn't appear that your issue is with anything unique to the K3s packaging of Traefik.

**Comment by t-grzelak** [comment, marked as answer]
Alright, I found the problem - maybe it will be useful for someone.
The issue was, that the **insecureSkipVerify** flag couldn't be set on the **Ingress** object, but should have be placed in a **ServersTransport** object instead.
I didn't know, how to make it work with **Ingress**, so I replaced it with **IngressRoute** in the following way, and the https backend is working for me now:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: apache
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`www.local`)
    services:
    - name: apache-https
      port: 443
      scheme: https
      serversTransport: apache-servers-transport
  tls: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: apache-servers-transport
  namespace: default
spec:
  insecureSkipVerify: true
```

I'm still getting some Traefik error though, but it's not preventing my setup from working as expected:
```
level=error msg="servers transport not found apache-servers-transport@kubernetescrd" entryPointName=websecure routerName=default-apache-d698ee2d8269c2956c89@kubernetescrd
```

Anyone knows what's missing still?
