### DISCUSSION TITLE
Deployment not respecting tolerations to taint

### DISCUSSION THREAD

**Discussion by UntestedEngineer** [k3s-io/k3s#6258] [Q&A]
**Environmental Info:**
Two different environments facing the same issue:

**K3s Version:** 
k3s version v1.24.6+k3s1 (a8e0c66d)
go version go1.18.6

k3s version v1.24.2+k3s1 (b0ed1348)
go version go1.18.1

**Node(s) CPU architecture, OS, and Version:** 
Linux  5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Cluster Configuration:**
- 3 Control Nodes
- 2 Worker Nodes 

- Control nodes run control-plane, etcd and are master

- Utilizing kube-vip (v0.4.4) as a control plane HA VIP instead of dedicated HA proxy.
- Utilizing antrea (v1.8.0) for CNI

**Describe the bug:**
I have tainted the control nodes for NoExecute so that I can add tolerations to coredns and antrea-controller, however it appears the deployments are not respecting the tolerations and scheduling coredns + antrea-controller on worker nodes.

**Steps To Reproduce:**
Add the following taints to the control nodes.  Keep in mind I never needed the NoSchedule taint before, as I have only used NoExecute but I added it to be on the safe side (It did not make a difference).  No matter how many times I restart the coredns and antrea-controller deployment they keep getting scheduled on worker nodes.  However, I can manually cordon + drain both worker nodes and the pods will get scheduled on the control-plane nodes.
```yaml
  taints:
    - key: k3s-controlplane
      value: 'true'
      effect: NoExecute
    - key: node-role.kubernetes.io/control-plane
      value: 'true'
      effect: NoSchedule
```

Add tolerations to deployment coredns and antrea-controller:
```yaml
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
```

**Expected behavior:**
I expected the referenced coredns and antrea-controller deployments to be only scheduled on control-plane nodes since I have added the appropriate taints + tolerations.

**Actual behavior:**
coredns and antrea-controller deployments are getting scheduled on worker nodes instead

**Additional context / logs:**
No logs are visible that I can see are an issue.
