### DISCUSSION TITLE
cannot set hostPort with UDP

### DISCUSSION THREAD

**Discussion by aserraric** [k3s-io/k3s#6289] [Q&A]
**Environmental Info:**
K3s Version: 
v1.24.6+k3s1 

Node(s) CPU architecture, OS, and Version: 
Linux 5.15.70-1-MANJARO-ARM-RPI #1 SMP PREEMPT Tue Sep 27 04:58:34 UTC 2022 aarch64 GNU/Linux

Cluster Configuration:
1 server, 0 agents

**Describe the bug:**
I'm trying to expose a port on a container as a hostport (DNS, in my case). This works fine for ports that have TCP (implicit or explicit) as their protocol. But if I try to set a hostport value for a UDP port, the value is silently ignored and missing when reading the YAML back.

**Steps To Reproduce:**

- Installed K3s: no options on install script, this is my /etc/rancher/k3s/config.yaml
 ```
  write-kubeconfig-mode: 644
  node-ip: <ipv4 redacted>,<ipv6 redacted>
  cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
  service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
  flannel-ipv6-masq: true
 ```
- Added a deployment for pihole
- added this to the ports section of the container spec:
 ```
 - containerPort: 53
   name: dns
   protocol: TCP
 - containerPort: 53
   hostPort: 5335
   name: dns-udp
   protocol: UDP
```

**Expected behavior:**
port 5335 on the host to be reachable with UDP and connected to the pihole container

**Actual behavior:**
Port is not reachable, no error on apply, reading back the YAML shows:
 ```
 - containerPort: 53
   name: dns
   protocol: TCP
 - containerPort: 53
   name: dns-udp
   protocol: UDP
```

**Notes**
I actually want to do this with port 53, but I currently have traefik using that port as an entrypoint to be able to reach pihole at all.

**Comment by brandond** [comment]
I would consult the Kubernetes docs at https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#ports - note that if you are trying to use hostNetwork + hostPort then the containerPort and hostPort must match. Also note that you can't change ports after the pod has already been deployed.

This is just core Kubernetes behavior; not something customized by K3s. If you're having trouble getting it working then I would check your manifest and confirm that you've set things up properly. If you'd like to post the complete YAML manifest that you're deploying, it might be easier to see what you're missing.

**Reply by brandond** [reply]
> I actually want to do this with port 53, but I currently have traefik using that port as an entrypoint to be able to reach pihole at all.

Why not just expose it as a Service then, instead of mucking about with hostports and tcp/udp ingress routes?

**Reply by aserraric** [reply]
I'm currently exposing it as a ClusterIP service (and then via a IngressRouteUDP), because that's the only way I could get it to work. However, I lose part of pihole functionality, since pihole can not tell clients apart anymore and only sees traefik.

Can I configure k3s to allow port 53 as a NodePort (which I assume is what you mean by "exposing it as a service)? 

Also, in my first attempts, I actually tried to set both containerPort and hostPort to 53 (after disabling the entrypoint on port 53 in traefik), but that didn't work either. Or rather, it worked for TCP, but not UDP.

**Reply by aserraric** [reply]
Okay, I tried to replicate it with a minimal case. This works:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-test  
  labels:
    app: echo-test
spec:
  selector:
    matchLabels:
      app: echo-test      
  template:
    metadata:      
      labels:
        app: echo-test        
    spec:      
      hostNetwork: false
      containers:
        - name: echo-test
          image: wbitt/network-multitool:alpine-extra
          imagePullPolicy: Always          
          ports:   
          - containerPort: 54
            name: echo-tcp
            protocol: TCP          
            hostPort: 54
          - containerPort: 54
            name: echo-udp
            protocol: UDP          
            hostPort: 54
          resources:
            limits:
              memory: 128Mi
              cpu: 200m
    
```
If I run  `socat -v udp-l:54,fork exec:'/bin/cat'` inside this container, and connect to hostport 54/udp, I get an echo back.

This is my pihole deployment, which is not reachable on hostport 53/udp:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
    chart: pihole-2.9.3
    release: pihole
    heritage: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pihole
      release: pihole
  template:
    metadata:
      labels:
        app: pihole
        release: pihole
    spec:
      hostname:
      hostNetwork: false
      containers:
        - name: pihole
          env:
          - name: 'WEB_PORT'
            value: "80"
          - name: VIRTUAL_HOST
            value: pi.hole
          - name: WEBPASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: pihole-admin
          - name: 'PIHOLE_DNS_'
            value: '10.43.106.100;10.43.106.100'
          image: "pihole/pihole:2022.09.4"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 53
            name: dns
            protocol: TCP
            hostPort: 53
          - containerPort: 53
            name: dns-udp
            protocol: UDP
            hostPort: 53
          - containerPort:  443
            name: https
            protocol: TCP
          - containerPort: 67
            name: client-udp
            protocol: UDP
          livenessProbe:
            httpGet:
              path: /admin.index.php
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /admin.index.php
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /etc/pihole
            name: config
          - mountPath: /etc/dnsmasq.d/02-custom.conf
            name: custom-dnsmasq
            subPath: 02-custom.conf
          - mountPath: /etc/addn-hosts
            name: custom-dnsmasq
            subPath: addn-hosts
          - mountPath: /etc/dnsmasq.d/05-pihole-custom-cname.conf
            name: custom-dnsmasq
            subPath: 05-pihole-custom-cname.conf
          resources:
            {}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pihole
      - configMap:
          defaultMode: 420
          name: pihole-custom-dnsmasq
        name: custom-dnsmasq
```
