### DISCUSSION TITLE
NetworkPolicy is blocking traffic to ingress IP

### DISCUSSION THREAD

**Discussion by ameyp** [k3s-io/k3s#6548] [Q&A] [answered]
**Environmental Info:**
K3s Version: v1.24.1+k3s1 (0581808f)

Node(s) CPU architecture, OS, and Version: Linux leader 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 1 on the control plane, 5 agents

**Describe the bug:**
I'm running a Pod with two containers: a VPN container (using [gluetun](https://github.com/qdm12/gluetun)) and another container. The VPN is configured to not tunnel traffic headed for CIDR `192.168.99.99/32` and `10.0.0.0/8`. I'm applying a network policy that denies all egress other than:
- UDP traffic, VPN port, all IPs
- UDP traffic, DNS port, `10.0.0.0/8`
- TCP traffic, HTTPS port, `192.168.99.99/32`

My goal is to allow all external traffic via the VPN, and internal traffic only too `192.168.99.99`, which is the LoadBalancer IP for Traefik running on my cluster as an ingress controller. With this policy applied, VPN traffic works as expected, but any traffic to any ingress is blocked with `connection refused`. If I delete the policy, I'm able to reach all ingresses from the pod.

**Steps To Reproduce:**

- Installed K3s: Using https://github.com/k3s-io/k3s-ansible 

Apply the following YAML:

```
apiVersion: v1
kind: Namespace
metadata:
  name: policy
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: policy-test
  name: policy
  namespace: policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: policy-test
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: 10.0.0.0/8
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
---
apiVersion: v1
kind: Pod
metadata:
  name: policy-test
  namespace: policy
  labels:
    app.kubernetes.io/name: policy-test
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
```

Inside the running pod, execute `wget https://ingress.hostname.cluster.com` where `ingress.hostname.cluster.com` is any ingress endpoint.

**Expected behavior:**
Get a valid HTTP response

**Actual behavior:**
```
Connecting to ingress.hostname.cluster.com (192.168.99.99:443)
wget: can't connect to remote host (192.168.99.99): Connection refused
```

**Additional context / logs:**

**Comment by brandond** [comment, marked as answer]
Network policies can be pretty difficult to author; we don't really have the resources to assist with their development or troubleshooting but I can at least suggest that you check the policies that apply to the ingress pods (and to the servicelb pod, if you're using that) to confirm that the traffic is allowed through those as well.

**Reply by ameyp** [reply]
I don't have any other network policies in the container, which is what leads me to believe that this might be a k3s/kube-router issue.

**Reply by brandond** [reply]
I'm not aware of any issues with kube-router that cause it to block traffic when it should not.

You said you don't have any other policies affecting this container, what about other pods in the cluster, or other namespaces?

**Reply by ameyp** [reply]
Sorry, I mistyped, I don't have any other policies in the cluster.

**Reply by brandond** [reply]
v1.24.1 is from early June. Do you see the same behavior with the most recent v1.24 or v1.25 releases?

**Reply by ameyp** [reply]
I haven't tried upgrading, I can try that, it's just a really weird issue. I read that kube-router uses iptables and ipset, so I dumped the rule created for the policy, and at least the dst host and port were correct.

Perhaps out of scope for this discussion, but would an upgrade from 1.24.1 be trivial and uneventful?

**Reply by brandond** [reply]
To the latest 1.24, yeah probably.

**Reply by ameyp** [reply]
Could this issue be due to https://github.com/kubernetes/kubernetes/issues/66607?

(I tried changing the allowed ipblock to the cluster IP, but sadly didn't fix it)

**Reply by brandond** [reply]
Possibly? You might try specifically allowing egress to the ingress-controller pod instead of just using a cidr block?

**Reply by ameyp** [reply]
Yep, that did the trick - specifically, allowing egress to the ingress controller **namespace** on the port that the pod is listening. A `podSelector` that uses `matchLabels` doesn't work, but that seems out of the scope of this discussion.

Evidently the misbehaving network policy is due to the issue I linked after all! What an annoying and unexpected behavior on `kube-proxy`'s part. Thanks for helping me get past it!

**Reply by ameyp** [reply]
Last mystery solved too: the `podSelector` by itself only allows traffic to/from selected pods in the same namespace as the policy, so a `namespaceSelector` and a `podSelector` must be used together to allow traffic to/from specific pods in other namespaces.

**Reply by raghibomar786** [reply]
Hey @ameyp, I'm facing a similar issue. Can you share your updated NetworkPolicy that solved the issue?

**Reply by ameyp** [reply]
```
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - isolated-app
  egress:
    - ports:
        - protocol: UDP
          port: 51820
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - ports:
        - protocol: TCP
          port: 1234
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: allowed-app
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: allowed-app
  policyTypes:
    - Egress
 ```
