### DISCUSSION TITLE
syslog fills up quickly

### DISCUSSION THREAD

**Discussion by hholst80** [k3s-io/k3s#6671] [Q&A]
**Environmental Info:**
K3s Version: 
```
k3s version v1.26.0+k3s1 (fae88176)
go version go1.19.4
```

Node(s) CPU architecture, OS, and Version: 
```
Linux *** 5.15.0-1029-azure #36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
single server, single agent.

**Describe the bug:**
syslog fills up with message:
```
Dec 23 21:28:28 *** k3s[791]: I1223 21:28:28.356923     791 log.go:198] http: superfluous response.WriteHeader call from github.com/emicklei/go-restful/v3.(*Response).WriteHeader (response.go:221)
```

**Comment by brandond** [comment]
How frequently do you see that message? Do you have something hitting the k3s supervisor endpoint unusually frequently? Like a misconfigured health check or something?

**Reply by hholst80** [reply]
I would say we see about +10 new entries per second right now, but I am confident that we saw a larger burst before in the 100s per second.

k3s-serve has 100K files open. is that alot? i would think so. but uvicorn also has a suspiciously large count which we might want to look into.  we use uvicorn in our stack. red hearing? none of the pods are running above 100 mcpu now in idle mode. 

```
lsof | awk '{print $1}'|sort|uniq -c|sort -rnk 1
```

```
107187 k3s-serve
  53295 uvicorn
  41962 container
   7788 node
   6600 npm\x20st
   2665 prometheu
   2663 dragent
   1210 kubectl
   1166 gunicorn
    855 python3
    600 java
    546 cointerfa
    518 promscrap
    400 udisksd
    285 ModemMana
    266 metrics-s
    245 multipath
    238 coredns
    224 rkubelog
    223 sh
    195 argo
    178 systemd
    162 accounts-
    157 sshd
    156 workflow-
    132 polkitd
    132 pause
    130 local-pat
    128 rsyslogd
    112 unattende
...
```

test environment (where we see no errors). functionally equivalent deployment.

```
  33798 k3s-serve
  23144 container
   9845 uvicorn
   3905 node
   3300 npm\x20st
   2369 prometheu
   1834 dragent
..
```

**Reply by brandond** [reply]
that seems like an unusually high open file count. What are they all?

**Comment by hholst80** [comment]
we have a few redundant kubectl proxy running that we might clean up if that is indeed the issue? but I still think this error message is rather unhelpful and causes problems on itself.

**Reply by brandond** [reply]
Why do you have `kubectl proxy` commands left running?

**Reply by brandond** [reply]
I don't see this message at all on my clusters. I am also running v1.26 and have been since before it was released. I wonder what is different about your environment?

**Reply by hholst80** [reply]
If you google for it you can find it in Redhat Openshift as well. It was fixed there.

https://bugzilla.redhat.com/show_bug.cgi?id=2006654

kubectl proxy should not cause k3s to misbehave like this but yes it is a connection to the control plane that we are using, but maybe kubectl proxy spawns up too many?

I have 5 different clusters up and running using K3s this error message is only available on the single one. The one we use in production. Of course.

**Reply by brandond** [reply]
That openshift issue does not appear to be at all related, other than triggering the same warning in go-restful.

Can you isolate what specifically triggers this message?

**Reply by hholst80** [reply]
Functionally all deployments are the same. We have the same functions and services deployed in all environments so there should be no difference besides the number of connections. I could bring down say all kubectl proxy services but we have them deployed in other environments without seeing the same error/warning log.

**Reply by brandond** [reply]
Can you explain what you mean by "kubectl proxy services"? Are you using `kubectl proxy` to expose services outside the cluster, instead of using nodeport or loadbalancer services?

**Reply by hholst80** [reply]
to access the control plane over plain http w/o any need to juggle with TLS certs in all pod services. think service mesh.

**Reply by brandond** [reply]
That sounds like an odd pattern, I can't say I've seen anyone else doing that. Can you provide an example of how you're doing this in order to create the excessive log messages?

**Reply by hholst80** [reply]
The log statement says the call is redundant so it is a bug in K3s. For the fifty eleventh time all Deployments are functionally equivalent so I cannot do more than to State that you have a bug in K3s in how you're using a library in K3s.

**Reply by brandond** [reply]
If you can provide instructions on how to reproduce this on demand, on a fresh installation of k3s, please do so. This is all deep in the core Kubernetes code and not something custom to K3s.

**Comment by hholst80** [comment]
We think we have found a workaround for the problem. This system setting correlated completely with shutting down the noise in syslog.

Edit: The same problem popped up on our dev environment and there the fix did not resolve the issue.

```
sudo sysctl fs.inotify.max_user_instances=512
```

**Reply by hholst80** [reply]
The following deployment seems to trigger it in our dev env:

```yaml
# Copyright 2019 SolarWinds Worldwide, LLC.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rkubelog
  namespace: papertrail
  labels:
    app: rkubelog
spec:
  selector:
    matchLabels:
      app: rkubelog
  template:
    metadata:
      labels:
        kail.ignore: "true"
        app: rkubelog
    spec:
      containers:
      - image: ghcr.io/solarwinds/rkubelog:r17
        imagePullPolicy: Always
        name: "rkubelog"
        command:
        - /app/rkubelog
        env:
        - name: PAPERTRAIL_PROTOCOL
          value: "$PAPERTRAIL_PROTOCOL"
        - name: PAPERTRAIL_HOST
          value: "$PAPERTRAIL_HOST"
        - name: PAPERTRAIL_PORT
          value: "$PAPERTRAIL_PORT"
```

```sh
 ~/D/G/o/k/v/k8s-papertrail  master  > cat ACME-test.env
PAPERTRAIL_PROTOCOL=tls
PAPERTRAIL_HOST=logsXXX.papertrailapp.com
PAPERTRAIL_PORT=NNNNN
KALI_NS=ACME-test
 ~/D/G/o/k/v/k8s-papertrail  master > # export (grep -v # < ACME-test.env | xargs)
 ~/D/G/o/k/v/k8s-papertrail  master > # envsubst < ACME-test.env | kubectl apply -f
```
