### DISCUSSION TITLE
How to configure ephemeral limits (`ephemeral-storage`) after installation?

### DISCUSSION THREAD

**Discussion by hholst80** [k3s-io/k3s#6844] [General]
I installed k3s with both server and agent on the same node (which might have been a mistake otherwise I could just have removed the node as well). I felt the disk space was running a bit short so I increased the space available for k3s (/var/lib/rancher/k3s) to double the capacity. However, the node still shows the same ephemeral limits as before.

I managed to bump up the Pod limit(?) per node to 500 by creating a config

```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 500
evictionHard:
    memory.available: "1Gi"
```

and specifying that to k3s at start. but how do I configure the ephemeral limits? They do not seem to be recomputed by restarting kubelet either. Is it looking at / ? because that is around 30GB in size.

```
  allocatable:
    cpu: "8"
    ephemeral-storage: "29474065590"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 32876448Ki
    pods: "500"
  capacity:
    cpu: "8"
    ephemeral-storage: 30298176Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 32876448Ki
    pods: "500"
```
