### DISCUSSION TITLE
HelmChartConfig issue with entrypoint in IngressRoute for Traefik

### DISCUSSION THREAD

**Discussion by slmingol** [k3s-io/k3s#7069] [Q&A]
**Environmental Info:**
K3s Version: 

```
k3s -v
k3s version v1.25.6+k3s1 (9176e03c)
go version go1.19.5
```

Node(s) CPU architecture, OS, and Version: 

```
uname -a
Linux k8s-02a 5.15.0-1025-raspi #27-Ubuntu SMP PREEMPT Thu Feb 16 17:09:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
````

Cluster Configuration:

1 master, 4 agents

**Describe the bug:**

I recently wiped and rebuilt my k3s cluster and was setting up Traefik so that the dashboard could be accessed with  having to forward to it. In doing so I created a HelmChartConfig override file like so:
```
cat /var/lib/rancher/k3s/server/manifests/traefik-override-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--accesslog"
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
    ports:
      traefik:
        expose: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
```

When that completes turning over the Traefik PODs the resulting IngressRoute looks like this:
```
 $ ▶ k describe ingressroute/traefik-dashboard -n kube-system
Name:         traefik-dashboard
Namespace:    kube-system
Labels:       app.kubernetes.io/instance=traefik-kube-system
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=traefik
              helm.sh/chart=traefik-20.3.1_up20.3.0
Annotations:  helm.sh/hook: post-install,post-upgrade
              meta.helm.sh/release-name: traefik
              meta.helm.sh/release-namespace: kube-system
API Version:  traefik.containo.us/v1alpha1
Kind:         IngressRoute
Metadata:
  Creation Timestamp:  2023-03-12T20:33:57Z
  Generation:          1
  Managed Fields:
    API Version:  traefik.containo.us/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:helm.sh/hook:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:helm.sh/chart:
      f:spec:
        .:
        f:entryPoints:
        f:routes:
    Manager:         helm
    Operation:       Update
    Time:            2023-03-12T20:33:57Z
  Resource Version:  16955
  UID:               2b3f134e-a775-464b-9e5c-68ef5a00ae9f
Spec:
  Entry Points:
    traefik
  Routes:
    Kind:   Rule
    Match:  PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    Services:
      Kind:  TraefikService
      Name:  api@internal
Events:      <none>
```

**Steps To Reproduce:**

- Installed K3s: 

With the above setup in place, I'm not able to access the `/dashboard/`, unless I include the port 9000 in the call.

```
# doesn't work
 $ ▶ curl -I traefik.k3s-apps.lamotech.org
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Sun, 12 Mar 2023 20:40:19 GMT
Content-Length: 19

# works
 $ ▶ curl -I traefik.k3s-apps.lamotech.org:9000 -L
HTTP/1.1 308 Permanent Redirect
Location: http://traefik.k3s-apps.lamotech.org:9000/dashboard/
Date: Sun, 12 Mar 2023 20:40:36 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 3124
Content-Security-Policy: frame-src 'self' https://traefik.io https://*.traefik.io;
Content-Type: text/html; charset=utf-8
Date: Sun, 12 Mar 2023 20:40:36 GMT
```

If I amend the `IngressRoute` so that it points to `websecure` instead of `traefik` for the `EntryPoint` it works as expected.

```
Spec:
  Entry Points:
    websecure
  Routes:
    Kind:   Rule
    Match:  PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    Services:
      Kind:  TraefikService
      Name:  api@internal
```

```
 $ ▶ curl -ks https://traefik.k3s-apps.lamotech.org/dashboard/ | cut -c -50
<!DOCTYPE html><html><head><title>Traefik</title><
```

Is there a way to include the use of `websecure` for the `EntryPoint` in the `HelmChartConfig` or is there something broken in this particular Helm Chart?

**Expected behavior:**

When specifying `HelmChartConfig` I'd expect the resulting `IngressRoute` to work after.

**Actual behavior:**

`IngressRoute` appears to be pointing to the wrong `EntryPoint` for Traefik. I'd expect to be able to access the Traefik Dashboard without the inclusion of the port 9000.

**Additional context / logs:**
