### DISCUSSION TITLE
Accessing node port from inside pod

### DISCUSSION THREAD

**Discussion by woopla** [k3s-io/k3s#7390] [Q&A] [answered]
Hello,

Our Linux VMs at work use a tool that joins them to our Active Directory domain. This tool exposes LDAP on `localhost:10000`, which is very convenient for authentication queries. With Docker Compose, all I have to do is to add this to the YAML:

```yaml
    extra_hosts:
      - host.docker.internal:host-gateway
```

And I can then use `host.docker.internal:10000` as the LDAP server, and I'm all good. K3d exposes the same thing through `host.k3d.internal` (see https://github.com/k3d-io/k3d/pull/360), but that *also* uses Docker.

Is there a K3s/`containerd` equivalent here? Or do I have to switch to using Docker?

**Comment by woopla** [comment, marked as answer]
I figured out that I can use the `cni0` IP from the node to contact the service from any host. I've also added this `ConfigMap` for CoreDNS:

```yaml
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: coredns-custom
          namespace: kube-system
        data:
          vas.server: | 
            k3s.internal  {
              hosts {
                {{ ansible_cni0.ipv4.address }} ingress.k3s.internal
                fallthrough
              }
            }
```

Everything is working now. I just wish K3s had the same option as K3d 😃
