### DISCUSSION TITLE
entrypoints missing

### DISCUSSION THREAD

**Discussion by MiggyMan** [k3s-io/k3s#7592] [Q&A] [answered]
**K3s Version:** 

k3s version v1.26.4+k3s1 (8d0255af)
go version go1.19.8

**Node(s) CPU architecture, OS, and Version:** 

Nodes and sever are the same in terms of OS/kernel
Ubuntu 22.04.2 LTS
Linux k8s-control 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 Server, 2 Agents

**Issue**

I've installed k3s with the goal of eventually moving a lot of my currently co-lo hosted services over to it and so far, so good, the setup is "headless" style with traefik being used with ingress behind a load balancer provided by hetzner, I've reached the point where I'm adding some non http/https services but I'm having an issue getting the new entry points detected by the load balancer.

**Steps To Reproduce:**

- Installed K3s: 

Installed using a wrapper script

Server:

export HTTP_PROXY=10.0.0.5:3128
export HTTPS_PROXY=10.0.0.5:3128
export K3S_RESOLV_CONF=/run/systemd/resolve/resolv.conf
./install-k3s.sh

Agents:

#!/bin/bash

export HTTP_PROXY=http://10.0.0.5:3128
export HTTPS_PROXY=http://10.0.0.5:3128
export K3S_TOKEN=<redacted>
export K3S_URL=https://10.0.0.2:6443
export K3S_RESOLV_CONF=/run/systemd/resolve/resolv.conf
./install-k3s.sh

Entrypoint config:

 /var/lib/rancher/k3s/server/manifests/traefik-config.yaml

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.trustedIPs=10.0.0.6,10.42.0.0/16"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.6,10.42.0.0/16"
      - "--entryPoints.websecure.proxyProtocol.trustedIPs=10.0.0.6,10.42.0.0/16"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.6,10.42.0.0/16"
      - "--entryPoints.ssh.address=:10022/tcp"
      - "--entryPoints.smtp.address=:10025/tcp""
    ports:
      smtp:
        port: 10025
        exposed: true
        exposedport: 10025
        protocol: TCP
      ssh:
        port: 10022
        exposed: true
        exposedport: 10022
        protocol: TCP
```

The service being used to test this is as follows

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  labels:
    chart: generic-service
    app: postfix
spec:
  selector:
    matchLabels:
      app: postfix
  replicas: 1
  template:
    metadata:
      labels:
        app: postfix
    spec:
      serviceAccountName: default
      containers:
        - name: postfix
          image: 10.0.0.5:5001/postfix
          ports:
            - name: postfix-25
              containerPort: 25
              protocol: TCP
          volumeMounts:
            - name: core
              mountPath: /opt/mailman
            - name: config
              mountPath: /etc/postfix
      volumes:
        - name:  core
          hostPath:
            path: /mnt/gluster-k8s/mailman/core
        - name:  config
          hostPath:
            path: /mnt/gluster-k8s/postfix/etc
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
          - "postfix"

---
# Source: generic-service/templates/ingress.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: postfix-main
  labels:
    app: postfix
spec:
  entryPoints:
    - smtp
  routes:
  - match: "HostSNI(`*`)"
    services:
    - name: postfix-25
      port: 25
```

**Expected behavior:**

Load balancer sees the ports as active and brings the service online (service at the lb level)

**Actual behavior:**

Nada, squat, didly, there are no lights on at the inn, as far as the load balancer is concerned this is not responding.

**Additional context / logs:**

Output trimmed to remove unrelated stuff, saves people reading :D

```
NAMESPACE      NAME                                      READY   STATUS      RESTARTS   AGE
default        postfix-7df978896b-vnbxg                  1/1     Running     0          2d9h
cert-manager   cert-manager-webhook-5594f5c99b-ft86m     1/1     Running     0          40h
kube-system    helm-install-traefik-crd-66jwv            0/1     Completed   0          39h
kube-system    metrics-server-76d86976f8-7xxf6           1/1     Running     0          40h
kube-system    svclb-traefik-d10f3dca-sddjv              2/2     Running     0          38h
kube-system    svclb-traefik-d10f3dca-z2k4k              2/2     Running     0          38h
kube-system    svclb-traefik-d10f3dca-s98fg              2/2     Running     0          38h
kube-system    traefik-b65bd5d48-ffj9h                   1/1     Running     0          38h
kube-system    helm-install-traefik-86fst                0/1     Completed   0          29h

NAMESPACE      NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP                  PORT(S)                      AGE
default        postfix-25             ClusterIP      10.43.164.98    <none>                       25/TCP                       2d9h
kube-system    traefik                LoadBalancer   10.43.86.185    10.0.0.2,10.0.0.3,10.0.0.4   80:31613/TCP,443:32666/TCP   38h
```

**Comment by brandond** [comment]
Assuming you didn't copy-paste something incorrectly when opening this issue, your HelmChartConfig's values appear to contain invalid YAML. You have an extra quote on the end of the last additional argument:

```yaml
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.trustedIPs=10.0.0.6,10.42.0.0/16"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.6,10.42.0.0/16"
      - "--entryPoints.websecure.proxyProtocol.trustedIPs=10.0.0.6,10.42.0.0/16"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.6,10.42.0.0/16"
      - "--entryPoints.ssh.address=:10022/tcp"
      - "--entryPoints.smtp.address=:10025/tcp""
  #                                     HERE --^
```
