### DISCUSSION TITLE
helm would not install

### DISCUSSION THREAD

**Discussion by profhase** [k3s-io/k3s#7811] [Q&A]
**Environmental Info:**
K3s Version: 

k3s version v1.25.10+k3s1 (613a3bc8)
go version go1.19.9

Cluster Configuration:
1 master + 1 node

**Describe the bug:**
Trying to install a helm chart via manifest from a repo the helm chart does not install and i see the following error in the pod's logs

```
Error: INSTALLATION FAILED: chart "jetstack/cert-manager" matching v1.12.2 not found in cert-manager index. (try 'helm repo update'): no chart name found
```

The version exists (local install works)

**Steps To Reproduce:**

put the following `cert-manager.yml` into the manifests folder:

```
---

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: jetstack/cert-manager 
  repo: https://charts.jetstack.io
  version: "v1.12.2"
  targetNamespace: cert-manager
  set:
    installCRDs: "true"
```

**Expected behavior:**
chart installs

**Actual behavior:**
ns is being created, chart does not install
