### DISCUSSION TITLE
how k3s use prometheus gather default cadvisor,http status 403

### DISCUSSION THREAD

**Discussion by baerwang** [k3s-io/k3s#7823] [Q&A]
prometheus config file

```yaml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: cadvisor
    scheme: https
    metrics_path: /metrics/cadvisor
    bearer_token_file: /prometheus/k3s/token
    tls_config:
        ca_file: /prometheus/k3s/ca.crt
        insecure_skip_verify: true
    static_configs:
    - targets:
        - domain.com:998
```
use kubectl get cadvisor info

```shell
kubectl get --raw /api/v1/nodes/localhost.localdomain/proxy/metrics/cadvisor
```

<img width="2227" alt="image" src="https://github.com/k3s-io/k3s/assets/52104949/746099a6-9238-4542-9e53-aaa2a47d4d8e">
