### DISCUSSION TITLE
Build-in traefik Ingress Controller

### DISCUSSION THREAD

**Discussion by jakobmolander** [k3s-io/k3s#8039] [Q&A] [answered]
Hi

I have a Rancher k3s v1.26.6 cluster with the default traefik ingress controller. I run a pod with the gitlab/gitlab-ce image exposed with a ClusterIP Service:

```
apiVersion: v1
kind: Service
metadata:
 name: gitlab-service
 namespace: gitlab
spec:
 type: ClusterIP
 selector:
  k8s-app: gitlab
 ports:
 - name: "ssh"
  port: 22
  protocol: TCP
  targetPort: 22
 - name: "http"
  port: 80
  protocol: TCP
  targetPort: 80
 - name: "https"
  port: 443
  protocol: TCP
  targetPort: 443
```

The pod and service functions as expected and I can access the https port (443) of the service with no problem. The Ingress Rule fails to connect to the https port (443):

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: gitlab-ingress
 namespace: gitlab
spec:
 ingressClassName: traefik
 tls:
 - hosts:
  - gitlab.jmol.dk
  secretName: gitlab-tls
 rules:
 - host: gitlab.jmol.dk
  http:
   paths:
   - path: /
    pathType: Prefix
    backend:
     service:
      name: gitlab-service
      port:
       number: 443
```

What annotations do I have to include in the Ingress specification for it to work? I have tried:

1. No annotations
2. [traefik.ingress.kubernetes.io/router.insecureSkipVerify](http://traefik.ingress.kubernetes.io/router.insecureSkipVerify): "true"
3. [traefik.ingress.kubernetes.io/service.serversscheme](http://traefik.ingress.kubernetes.io/service.serversscheme): https
4. [traefik.ingress.kubernetes.io/router.tls](http://traefik.ingress.kubernetes.io/router.tls): "true"
5. [traefik.ingress.kubernetes.io/router.entrypoints](http://traefik.ingress.kubernetes.io/router.entrypoints): websecure

None seem to work.

Thank you in advance.

Kind regards,
Jakob

**Comment by brandond** [comment]
Have you considered asking at https://community.traefik.io/ ? This repo isn't really the best place to ask for help with Traefik.

**Comment by jakobmolander** [comment]
Hi @brandond,

I asked the question in both locations simultaniously:

https://community.traefik.io/t/rancher-k3s-build-in-traefik-ingress-not-connecting-to-https-backend-service/19320

I do not know, if the problem is within traefik itself or K3s setup or configuration of it. I was hoping, that someone with a better understanding than me, could try to reproduce the problem and maybe see some details on what goes wrong.

Kind regards, @jakobmolander

**Comment by jakobmolander** [comment, marked as answer]
The solution was to deactivate the certificate verification by creating a ServersTransport object:

```
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: mytransport
  namespace: default

spec:
    insecureSkipVerify: true
```

And then annotate the Service object:

```
traefik.ingress.kubernetes.io/service.serverstransport: default-mytransport@kubernetescrd
```
