### DISCUSSION TITLE
Unable to Add K3s Cluster to Rancher UI - "Pending" Status and "error: no objects passed to apply"

### DISCUSSION THREAD

**Discussion by Zolboo21** [k3s-io/k3s#8183] [Q&A]
Issue Description:
I have followed the steps outlined in the tutorial on the [Raspberry Pi Super Computer with Kubernetes (K3s) Cluster](https://learn.networkchuck.com/courses/take/raspberry-pi-projects/lessons/29763478-i-built-a-raspberry-pi-super-computer-ft-kubernetes-k3s-cluster-w-rancher) by NetworkChuck. I was able to successfully set up the Raspberry Pi cluster with K3s and Rancher as per the instructions.

Problem:
However, after installing Rancher, I encountered an issue when trying to add my K3s cluster to the Rancher web UI. The cluster status remains "Pending" and I am unable to proceed further. Additionally, when attempting to use kubectl, I receive an "error: no objects passed to apply" message.

Steps Taken:

I have meticulously followed all the steps in the tutorial, including the Raspberry Pi headless setup, K3s preparation, K3s master installation, and K3s node setup.
The K3s cluster appears to be running correctly as I can SSH into the nodes and verify their status using kubectl get nodes.
Expected Outcome:
I expected to be able to successfully add my K3s cluster to the Rancher web UI and manage it from there. However, I am unable to proceed past the "Pending" status and encounter issues with kubectl.

Commands and Outputs:
Here are the commands I executed and the outputs I received:

kubectl apply -f rancher.yaml resulted in "error: no objects passed to apply".
Attempting to add the cluster using the Rancher UI keeps the cluster status as "Pending" without progressing.
Additional Information:

I have reviewed the YAML file provided by Rancher for compatibility with K3s and adjusted the namespace from cattle-system to kube-system as per the K3s setup.
I have checked for any typos or mistakes in the configurations and YAML files, but everything appears to be correct according to the tutorial.
Request for Assistance:
I would appreciate any guidance or assistance in resolving this issue. I have exhausted my troubleshooting efforts and am unsure about the root cause of the problem. If there are any specific steps I may have overlooked or configurations that need adjustment, please let me know. Your support is highly valued, and I'm looking forward to successfully integrating my K3s cluster with Rancher.

Thank you in advance for your help.

Best regards,
Zolboo

**Comment by brandond** [comment]
This isn't really the right place for this question, as it appears that your problem is with Rancher, not K3s. However, I can take a shot at getting you on the right path.

> `kubectl apply -f rancher.yaml resulted in "error: no objects passed to apply".`

This suggests that your `rancher.yaml` file is empty or does not contain any valid Kubernetes objects. Have you confirmed that it was successfully downloaded from the Rancher server?

**Reply by Zolboo21** [reply]
First and foremost, I'd like to extend my apologies as I am relatively new to this and thank you for transitioning this from an issue to a discussion. I have reviewed the YAML file, and it starts with:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-clusterrole-kubeapiserver
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics
  - nodes/proxy
  - nodes/stats
  - nodes/log
  - nodes/spec
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-role-binding-kubernetes-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxy-clusterrole-kubeapiserver
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube-apiserver
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
```

Having examined this, I am quite certain that the link provided by the Rancher UI is not empty. However, I am still facing difficulties. Could you offer any suggestions or advice on how to proceed? Your assistance is greatly appreciated. Thank you.
