### DISCUSSION TITLE
k3s service load balancer is in a create and terminate pod loop

### DISCUSSION THREAD

**Discussion by migs35323** [k3s-io/k3s#8319] [Q&A]
**Environmental Info:**
K3s Version: 1.24.16 (this also happened in previous patch versions)

Node(s) CPU architecture, OS, and Version: 5 vps, ubuntu 22 servers

Cluster Configuration: 1 master 4 workers

**Describe the bug:**

so when i something happens to one a node and the load balancer needs to "rebalance" or there is new service load balancer created, klipper goes into a loop of creating and destroying containers, see picture.
anyone can give me an idea on the cause of this situation, basically i have traefik as a daemonset setted up in a 5 node machine,
nodes are hosted in cloud and are all using an external ip address
this is my traefik load balancer service:

(ip and ports are "censored")
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["1.1.1.1","2.2.2.2","3.3.3.3"],"port":80,"protocol":"TCP","serviceName":"kube-system:traefik","allNodes":false},{"addresses":["1.1.1.1","2.2.2.2","3.3.3.3"],"port":443,"protocol":"TCP","serviceName":"kube-system:traefik","allNodes":false}]
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: kube-system
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik
  name: traefik
  namespace: kube-system
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.999.999
  clusterIPs:
    - 10.43.333.999
  externalIPs:
    - 1.1.1.1
    - 3.3.3.3
    - 4.4.4.4
    - 2.2.2.2
    - 5.5.5.5
  externalTrafficPolicy: Local
  healthCheckNodePort: 99999
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: PreferDualStack
  loadBalancerSourceRanges:
    - 1.1.1.1/32
    - 3.3.3.3/32
    - 4.4.4.4/32
    - 2.2.2.2/32
    - 5.5.5.5/32
  ports:
    - name: web
      nodePort: 99998
      port: 80
      protocol: TCP
      targetPort: web
    - name: websecure
      nodePort: 99997
      port: 443
      protocol: TCP
      targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 1.1.1.1
      - ip: 2.2.2.2
      - ip: 3.3.3.3

``` 
klipper daemon set that gets created:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: '9414'
    field.cattle.io/publicEndpoints: >-
      [{"nodeName":":vps-1","addresses":["1.1.1.1"],"port":80,"protocol":"TCP","podName":"kube-system:svclb-traefik-091f1f66-5f6zl","allNodes":false},{"nodeName":":vps-1","addresses":["1.1.1.1"],"port":443,"protocol":"TCP","podName":"kube-system:svclb-traefik-091f1f66-5f6zl","allNodes":false},{"nodeName":":vps-2","addresses":["4.4.4.4"],"port":80,"protocol":"TCP","podName":"kube-system:svclb-traefik-091f1f66-9jzvv","allNodes":false},{"nodeName":":vps-2","addresses":["4.4.4.4"],"port":443,"protocol":"TCP","podName":"kube-system:svclb-traefik-091f1f66-9jzvv","allNodes":false}]
    objectset.rio.cattle.io/id: ''
    objectset.rio.cattle.io/owner-gvk: /v1, Kind=Service
    objectset.rio.cattle.io/owner-name: traefik
    objectset.rio.cattle.io/owner-namespace: kube-system
  generation: 9414
  labels:
    svccontroller.k3s.cattle.io/nodeselector: 'true'
    svccontroller.k3s.cattle.io/svcname: traefik
    svccontroller.k3s.cattle.io/svcnamespace: kube-system
  name: svclb-traefik-091f1f66
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: svclb-traefik-091f1f66
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: svclb-traefik-091f1f66
        svccontroller.k3s.cattle.io/svcname: traefik
        svccontroller.k3s.cattle.io/svcnamespace: kube-system
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: SRC_PORT
              value: '80'
            - name: SRC_RANGES
              value: >-
                2.2.2.2/32 3.3.3.3/32 1.1.1.1/32
                4.4.4.4/32 5.5.5.5/32
            - name: DEST_PROTO
              value: TCP
            - name: DEST_PORT
              value: '31817'
            - name: DEST_IPS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: rancher/klipper-lb:v0.4.4
          imagePullPolicy: IfNotPresent
          name: lb-tcp-80
          ports:
            - containerPort: 80
              hostPort: 80
              name: lb-tcp-80
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - env:
            - name: SRC_PORT
              value: '443'
            - name: SRC_RANGES
              value: >-
                3.3.3.3/32 1.1.1.1/32 4.4.4.4/32
                5.5.5.5/32 2.2.2.2/32
            - name: DEST_PROTO
              value: TCP
            - name: DEST_PORT
              value: '31763'
            - name: DEST_IPS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: rancher/klipper-lb:v0.4.4
          imagePullPolicy: IfNotPresent
          name: lb-tcp-443
          ports:
            - containerPort: 443
              hostPort: 443
              name: lb-tcp-443
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        svccontroller.k3s.cattle.io/enablelb: 'true'
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        sysctls:
          - name: net.ipv4.ip_forward
            value: '1'
      serviceAccount: svclb
      serviceAccountName: svclb
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 5
  desiredNumberScheduled: 5
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  numberUnavailable: 2
  observedGeneration: 9414
  updatedNumberScheduled: 1

```
pictures:
![Screenshot from 2023-09-07 15-52-29](https://github.com/k3s-io/k3s/assets/92784574/d2e1ee3d-c771-4ee6-a0fa-f44fbbfd68d9)

extra notes:

all my current nodes have the svccontroller.k3s.cattle.io/enablelb=true
i have all the nodes with svccontroller.k3s.cattle.io/lbpool=pool1
and one single node with svccontroller.k3s.cattle.io/lbpool=pool2

the load balancer config is based of several attempts and threads found in this repository so my services get to see the clients addresses
eventually after a very long time the "loop" stops and it all the klipper pods get ok, but this is taking a very long time...
