### DISCUSSION TITLE
Performance Problems with Network Policies - Request for Help

### DISCUSSION THREAD

**Discussion by maltelehmann** [k3s-io/k3s#8321] [General]
Hi all!

first, thank you very much for k3s, we are really enjoy working with it!

On our testing clusters, we activated network policies with default deny-all. Afterwards, we observed that between pod start and reacheability of coredns pod, it takes >=20sec. According to some k3s/kube-router issues regarding network policies, we would expect only a couple of seconds. 
We only get a delay of a couple of seconds when we reduce the number of network policies (see below). We consider our cluster and the number of network policies as rather small, there seems to be a problem in our configuration or maybe a bug? 

Our investigations (below) did not give us any hint on what is the root cause of the performance problems. Do you have any recommendations how we could proceed to find the root cause?

Thank you for your help!

Malte 

#### OS

```bash
cat /etc/redhat-release 
CentOS Linux release 8.3.2011
```

- iptables service is running with egress allow all and ingress only from specific hosts etc.

- we have the following amount of resulting iptables rules and ipset rules:

```bash
sudo ipset list | wc -l
14387
sudo iptables-save | wc -l
1104
```

#### k3s

* version: `v1.26.6+k3s1`

* config.yaml
```yaml
token: 'mytoken'
data-dir: '/ssd/k3s'
node-ip: 'mynodeip'

prefer-bundled-bin: true

flannel-iface: 'eth0'

kubelet-arg:
  - 'root-dir=/ssd/k3s/kubelet'
  - 'image-gc-high-threshold=70'
  - 'image-gc-low-threshold=50'

debug: true

node-taint:
- CriticalAddonsOnly=true:NoExecute

cluster-cidr: '10.42.0.0/16'
service-cidr: '10.43.0.0/16'
flannel-backend: 'host-gw'
tls-san: [mngr1.mydomain, mngr2.mydomain, mngr3.mydomain]

etcd-expose-metrics: true

secrets-encryption: true
```

* we have the following cluster size:

```bash
kubectl get no | wc -l
25

kubectl get po --all-namespaces | wc -l
248

kubectl get svc --all-namespaces | wc -l
119

kubectl get netpol --all-namespaces | wc -l
170
```

### Debugging

- `k3s` Logs with `debug: true` -> do not show any error or hint on the delay
- `prefer-bundled-bin: false` -> no change in performance
- disable host iptables service and reboot -> no change in performance
- `sudo ipset list | grep "<my_pod_ip> "` during pod startup -> it can be observed that the result is first 1 line, after some seconds 2 lines, and finally 6 lines and then the DNS is reacheable. So it seems that the update of the ipset rules takes really long
- removing most pods such that we ending up with 54 (before: 248) -> no change in performance
- removing most netwokr policeis ending up with 38 (before: 170) -> **performance improves to 1sec!**

**Comment by brandond** [comment]
@manuelbuil @rbrtbnfgl do you have any suggestions on where we might look for this? 248 pods and 170 policies is probably more than we test with regularly, but I'm curious if there's anywhere in particular we could look for performance improvements.

**Reply by brandond** [reply]
@maltelehmann you might also reach out to the [kube-router project](https://github.com/cloudnativelabs/kube-router) directly - we embed a very lightly modified version of their firewall controller to provide network policy enforcement via ipsets.

**Reply by ChristianCiach** [reply]
Hi Brad, thank you for your super quick response as always!

I am actually a coworker of @maltelehmann and we have been trying to track down this issue for quite some time now. We actually debated if we should create this discussion here or to create an issue over at kube-router instead, but we decided to post here first. Following your suggestion, we will create an issue at kube-router early next week.

In the meantime, we will be happy to provide any further data about our clusters if you have any questions.

**Reply by brandond** [reply]
It won't be available for a few minutes, but you might try installing commit `1ccdb7e4b22a7f1d1c49ac70e3a16982b6b65a44` from https://github.com/k3s-io/k3s/pull/8332 and monitor the two kube_router metrics to see what the sync time is for those two loops?

**Reply by ChristianCiach** [reply]
We will do that, but probably not over the weekend :) Thanks!

**Reply by brandond** [reply]
You can also try `f1f70d76f0b6ea6c5ebf23bd52b28c80d3914e52` to see if you are by any chance running into api rate-limits in the netpol controller's Kubernetes client.

**Reply by ChristianCiach** [reply]
I didn't even know that that's a thing. Interesting stuff.

We will come back to you as soon as possible. Until then, have a nice weekend!

**Reply by manuelbuil** [reply]
Interesting! Check Brad's PR and let's see what you get. I can investigate further

**Reply by ChristianCiach** [reply]
I am sorry for not having a lot of news for you today. Malte and I are busy putting out some unexpected fires.

What I can tell you right now:

* We've installed https://github.com/k3s-io/k3s/commit/0c1157a6 on all nodes of the cluster and restarted all k3s instances (double checked via `kubectl get nodes`).
* There are no metrics named `kube_router_*` found anywhere. I assume you expect them to be reported at `kubectl proxy; curl http://localhost:8001/metrics`, right? 
* There is no difference in performance. Pods still take around 20s until they can call out to other services (for example to CoreDNS).
* Grafana reports no changes in the amount of requests to the apiserver. I am not really a prometheus/grafana expert, so maybe I am reading this wrong. @maltelehmann may want to add something to this.

**Reply by ChristianCiach** [reply]
I almost forgot this: Very rarely (like once every two days, but if it happens, it happens multiple times in quick succession) we see this inside the logs:

```
Sep 11 08:33:34 mngr1.censored-hostname k3s[1428602]: E0911 08:33:34.400202 1428602 network_policy_controller.go:265] Aborting sync. Failed to sync network policy chains: failed to perform ipset restore: ipset v7.15: Error in line 2521: Kernel error received: Resource busy
```

This does not timely correlate with the creation of new pods (or at least I cannot trigger it by creating new pods that are subject to network policies) and I also haven't seen this today at all, so I don't expect this to be the issue. Anyway, this seems to be the same issue as reported in https://github.com/k3s-io/k3s/issues/6328

**Reply by ChristianCiach** [reply]
The missing metrics by kube-router are probably related to this:

```
E0912 15:03:04.915858 1974977 health_controller.go:147] Metrics Controller heartbeat missed
```

I didn't notice that the `health_controller.go` is part of kube-router, so I didn't think it was related at first. But this error started to appear directly after installing https://github.com/k3s-io/k3s/commit/0c1157a6 . I am not sure why this happens...

**Reply by ChristianCiach** [reply]
Since we were still using CentOS 8 (which is EOL since quite a while) and I wanted to rule out an old distribution or kernel as the culprit, I finally came around to migrate the nodes to AlmaLinux. All nodes are now running AlmaLinux:

```
$ cat /etc/redhat-release 
AlmaLinux release 8.8 (Sapphire Caracal)
$ uname -rv
4.18.0-477.21.1.el8_8.x86_64 #1 SMP Thu Aug 10 13:51:50 EDT 2023
````
(was `4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021` before).

Unfortunately, this changes nothing :disappointed:

**Reply by brandond** [reply]
Its possible there's another bit of kube-router that we need to start up to enable its metrics; it's been a while since I poked at it.

**Reply by ChristianCiach** [reply]
Interesting observation: The `egress` rule that allows all pods of the namespace to connect to coredns seems to take effect pretty much instantaneously. It seems to be the corresponding `ingress` rule in `kube-system` that triggers the issue.

Concrete example:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-policy
  namespace: some-customer
spec:
  podSelector: {}
  policyTypes:
    - Ingress  # No ingress rules defined below ==> Deny all incoming by default
    - Egress
  egress:
    # kubernetes dns
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - 'kube-system'
          podSelector:
            matchExpressions:
              - key: k8s-app
                operator: In
                values:
                  - 'kube-dns'
      ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns
  namespace: kube-system
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  ingress:
    - from:
        - namespaceSelector: {}
          podSelector: {}
      ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
  egress:
    - to: []
      ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
```

If I remove the `coredns` policy from `kube-system`, everything becomes super fast!

Here is how I currently measure the delay:

```sh
$ kubectl run --rm -i --tty waitforit --image=ph4r5h4d/wait4it --restart=Never -- -type=tcp -p=53 -h=10.43.0.10
```

... where `10.43.0.10` is the ClusterIP of the kube-dns service.


**Edit**: I need to check tomorrow if I can reduce the issue to these two policies or if the "amount" of policies actually plays any role in this issue.

**Edit 2**: But the issue is not just with coredns of course. A pod trying to reach a `mariadb` pod inside the same namespace triggers the issue just the same, since the pair of ingress- and egress-policies is essentially the same as with the coredns-example shown above, but constrained to a single namespace.

**Reply by brandond** [reply]
OK, so it sounds like the issue is not in creating egress rules for the new pod, but rather delays in syncing the ingress ipset for the other pods. That is likely a very large ipset since it matches all pods in all namespaces, and is going to have to change EVERY TIME a pod comes or goes anywhere in the cluster.

**Reply by ChristianCiach** [reply]
That sounds logical, but as described in my `Edit 2` the same issue happens on a smaller scope within a single namespace, which are of course way fewer pods. And the delay is pretty much the same. Curious.

Anyway, it's very late evening in Germany, so I am off for today.

**Reply by brandond** [reply]
Have you considered replacing exceptionally broad selectors with `ipBlock` matches that allow traffic from your cluster CIDR instead? Or just... not using ingress rules if you want to allow all traffic to those pods?

**Reply by ChristianCiach** [reply]
Wait, are you saying that the coredns policy that targets all pods in all namespaces may actually be the culprit for seemingly unrelated policies as well? So if I remove the coredns ingress policy, the mariadb-client that connects to the mariadb-server inside the same namespace may be "fixed" by the removed coredns policy? I am already on mobile, but I will test this first thing tomorrow.

**Reply by brandond** [reply]
Not quite.

The coredns policy only matches the coredns pod (`k8s-app: kube-dns`) but it has an ingress rule that matches all pods in all namespaces. That means that the backing kernel ipset for every coredns pod needs to be updated every time any other pod is created or deleted. The same is true of any other ingress or egress rules that has an exceptionally broad set of selectors.

**Reply by ChristianCiach** [reply]
I know of no other policy that has such a broad set of selectors. There may be some that target all pods of the local namespace (just as the default-deny ingress policy in each namespace except for kube-system), but the amount of pods should be in the low tens per namespace.

But at least I now have something to look deeper into. I will come back to you as soon as I find out anything new.

**Reply by ChristianCiach** [reply]
By implementing your suggestions I was able to "fix" the issues regarding `coredns` (by using a static CIDR or allowing ingress from all sources altogether). But as I suspected, even within a single namespace the performance is just as bad.

Example: We have a MariaDB-pod that should be reachable by all pods within the same namespace:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-policy
  namespace: my-namespace
spec:
  podSelector: {}
  policyTypes:
    - Ingress  # No ingress rules defined below ==> Deny all incoming by default
    - Egress
  egress:
    # Many other array elements removed for brevity
    - to:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - 'mariadb'
      ports:
        - protocol: TCP
          port: 3306

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mariadb
  namespace: my-namespace
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: 'mariadb'
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}  # all pods in same namespace
      ports:
        - port: 3306
          protocol: TCP

```

New pods still need to wait 15 to 25 seconds before they can connect to 3306/tcp of the mariadb pod, with very few exceptions where it takes slightly under 10 seconds.

The namespace in question currently contains 67 pods. I get the feeling that kube-router is just not designed for anything more than one or two dozens of pods.

I am at my wits' end here :/ I really hope we don't have to migrate all of our clusters to another CNI just to make network policies work reliably.

We've probably reached a point were we should take this issue over to the kube-router project.
