### DISCUSSION TITLE
How to configure request body size

### DISCUSSION THREAD

**Discussion by yhan219** [k3s-io/k3s#8376] [Q&A]
**Environmental Info:**
K3s Version: 

```
k3s version v1.27.5+k3s1 (8d074ecb)
go version go1.20.7
```
Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

```
Linux ecs-202012141540440001.novalocal 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
**Describe the bug:**

I'm a newbie and I want to configure the request body size. How do I configure it?

**Steps To Reproduce:**

- Installed K3s: curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn  sh -
- my traefik version:
```
# k3s crictl images | grep traefik
docker.io/rancher/mirrored-library-traefik   2.9.10                 d1e26b5f8193d       39.6MB
```
- install CRD
```
kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.9/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.9/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml

```
- my pods
```
# kubectl get pods -n kube-system
NAME                                     READY   STATUS      RESTARTS   AGE
local-path-provisioner-957fdf8bc-jvhnp   1/1     Running     0          4m43s
coredns-77ccd57875-jcjp5                 1/1     Running     0          4m43s
helm-install-traefik-crd-g4cpb           0/1     Completed   0          4m43s
helm-install-traefik-89k4v               0/1     Completed   1          4m43s
svclb-traefik-58751ffc-jr8cl             2/2     Running     0          4m14s
traefik-64f55bb67d-ftm88                 1/1     Running     0          4m14s
metrics-server-648b5df564-phfn7          1/1     Running     0          4m43s
```
- my yaml
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: request-body-limit
spec:
  buffering:
    maxRequestBodyBytes: 10000000000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    traefik.ingress.kubernetes.io/middleware: default/request-body-limit
spec:
  rules:
    - host: test.mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 80

```
**Expected behavior:**

can upload big file
**Actual behavior:**

cant upload
**Additional context / logs:**
