### DISCUSSION TITLE
NodePort only working on nodes with pod

### DISCUSSION THREAD

**Discussion by nvollmar** [k3s-io/k3s#8707] [Q&A]
**Environmental Info:**
K3s Version: 
k3s version v1.28.2+k3s1 (6330a5b4)
go version go1.20.8

Node(s) CPU architecture, OS, and Version: 
Linux k3s-worker-0 6.5.0-rc5-edge-rockchip-rk3588 #3 SMP PREEMPT Sun Aug  6 22:07:51 UTC 2023 aarch64 GNU/Linux

Cluster Configuration:
2 master nodes, 2 worker nodes

**Describe the bug:**
I've set up a service with a NodePort and it is only reachable on the node which the pod is running on.

Service definition:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
  namespace: home
spec:
  clusterIP: 10.43.208.9
  clusterIPs:
  - 10.43.208.9
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: mqtt
    nodePort: 31883
    port: 1883
    protocol: TCP
    targetPort: mqtt
  selector:
    app: mosquitto
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

**Steps To Reproduce:**
k3s installed using k3s-ansible project with HA. Server args:
```
apiserver_endpoint: "10.3.0.1"
apiserver_dns: "k3s-lb.vollmar.local"

extra_server_args: >
  --tls-san={{ apiserver_endpoint }} --tls-san={{ apiserver_dns }} --advertise-address={{ apiserver_endpoint }} 
  --disable local-storage --disable traefik --disable metrics-server --disable-cloud-controller --disable-helm-controller 
  --egress-selector-mode=disabled
```

**Expected behavior:**
NodePort should be reachable on all nodes

**Actual behavior:**
NodePort only working on node with the pod running
