### DISCUSSION TITLE
etcd db dir getting created after upgrade (  for a cluster configured as external data store )

### DISCUSSION THREAD

**Discussion by fmoral2** [k3s-io/k3s#8746] [General]
**Environmental Info:**
K3s Version: 

- Any

Node(s) CPU architecture, OS, and Version: 

- tested on ubuntu and sles15  
- 
Cluster Configuration:

- 1 server
-  local datastore_type=external
- datastore_endpoint={datastoreendpoint}

**Describe the bug:**

- Creating a cluster there is not a etcd/db dir as expected 
 ```
 cat: can't open '/var/lib/rancher/k3s/server/db/etcd/config': No such file or directory
```
But after upgrading is there:
```
 -sudo -i cat /var/lib/rancher/k3s/server/db/etcd/config
advertise-client-urls: https://172.31.8.123:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
heartbeat-interval: 500
listen-client-urls: https://127.0.0.1:2379,https://172.31.8.123:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://127.0.0.1:2380,https://172.31.8.123:2380
log-outputs:
- stderr
logger: zap
name: ip-172-31-8-123-bf38ff4c
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.c
```

**Steps To Reproduce:**

- Installed K3s with config pointing to external datastore endpoint
sh -s - server --datastore-endpoint={datastoreendpoint}

**Expected behavior:**

- should not have etcd/db dir after upgrade
**Actual behavior:**

- it does have the etcd.db dir 
**Additional context / logs:**
