### DISCUSSION TITLE
Etcd doesn't start after updating to v1.27.7+k3s1

### DISCUSSION THREAD

**Discussion by ChristianCiach** [k3s-io/k3s#8780] [Q&A] [answered]
I am creating this as a discussion because I've seen no one else having this issue.

When updating our clusters from `v1.27.6+k3s1` to `v1.27.7+k3s1`, the embedded Etcd doesn't seem to come up correctly. Even when adding `debug: true` the logs don't show anything helpful, just that the etcd-client cannot connect.

Please see the attached logs: [k3s.1.27.7.debug.log](https://github.com/k3s-io/k3s/files/13251021/k3s.1.27.7.debug.log)

It doesn't matter which of the three server nodes I try to update first. The first node I try to update always refuses to come up.

Our  `config.yaml` looks like this:

```
## COMMON CONFIGURATION

debug: true
token: 'topsecret'
data-dir: '/ssd/k3s'
node-ip: '172.28.180.138'

prefer-bundled-bin: true

flannel-iface: 'eth0'

kubelet-arg:
  - 'root-dir=/ssd/k3s/kubelet'
  - 'image-gc-high-threshold=70'
  - 'image-gc-low-threshold=50'

node-taint:
- CriticalAddonsOnly=true:NoExecute

## SERVER SPECIFIC CONFIGURATION

cluster-cidr: '10.42.0.0/16'
service-cidr: '10.43.0.0/16'
flannel-backend: 'host-gw'
tls-san: [mngr1.mycompany.local, mngr2.mycompany.local, mngr3.mycompany.local]


disable-network-policy: true

etcd-expose-metrics: true

secrets-encryption: true

```

I wish I could describe the issue better, but the logs don't give me much to work with.

**Edit:** The logs created by `v1.27.6+k3s1` look pretty much identical, except for the non-failing etcd-client.

**Edit 2:** `v1.28.3+k3s1` fails for us, too. `v1.26.10+k3s1` is working fine.

**Comment by ChristianCiach** [comment]
I wonder if it has something to do with https://github.com/k3s-io/k3s/issues/8415 . Do the port requirements have changed? Our hosts are configured with pretty strict iptables rules, with only the ports opened as described at https://docs.k3s.io/installation/requirements#inbound-rules-for-k3s-server-nodes .

**Reply by ChristianCiach** [reply]
No, that cannot be it. This change is also included in `v1.26.10+k3s1`, **which is working for us**.

**Comment by ChristianCiach** [comment]
Okay, it seems to have something to do with `iptables`. When I stop k3s, flush all rules and then start k3s, then it works fine.

**But** it also works fine when I reboot the node, and on reboot our custom iptables rules are restored *before* starting k3s. This should mean that the new k3s version crashes due to some iptables rules that were created by the previous k3s version, since our custom rules seem to work fine, even with the new k3s versions.

**Reply by ChristianCiach** [reply]
My workaround is to just restart the `iptables` service after stopping the k3s service (edit: actually, we don't to that. We just replace the binary and execute the install script, as described by the docs) but before starting the service of the new k3s version. I don't really understand *why* this is suddenly necessary, but it's good enough as a migration strategy.

```yaml
- name: Copy k3s binary
  ansible.builtin.copy:
    src: '{{ k3s_download_dir }}/k3s'
    dest: /usr/local/bin/k3s
    mode: 0o755

- name: Restart iptables
  ansible.builtin.systemd_service:
    name: iptables
    state: restarted

- name: Install K3s
  ansible.builtin.script:
    cmd: >-
      {{ k3s_download_dir }}/install.sh
      {{ k3s_role }}
      {% if k3s_initial_server and k3s_embedded_etcd %}--cluster-init{% endif %}
      {% if not k3s_initial_server %}--server {{ k3s_server_url }}{% endif %}
  ignore_errors: true
  environment: '{{ lookup("template", "install.env.yaml.j2") | from_yaml }}'

- name: Wait for k3s server to be up and running
  ansible.builtin.command:
    cmd: 'systemctl is-active --quiet k3s'
  retries: 10

```
