### DISCUSSION TITLE
Changes regarding the NodePort external exposure feature

### DISCUSSION THREAD

**Discussion by hanjeongsang** [k3s-io/k3s#8940] [Q&A] [answered]
hi have a nice day.

In the past k3s version (INSTALL_K3S_VERSION="v1.17.4+k3s1"), i could connect from the outside just by creating a nodeport service. However, in the latest version (1.26), it seems that the nodeport service cannot be accessed from outside. 
Looking at the netstat command, nodeport is not LISTEN.

my test is simple 
1. run pod, service
```
#service_np.yaml
apiVersion: v1
kind: Service
metadata:
  name: mynginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    run: mynginx

```
```
#nginx.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginx
  name: mynginx
spec:
  containers:
  - name: nginx
    image: nginx

```

2. Access nginx page from outside via nodeport

v1.17 >> OK
v1.26 >> can't access

Have there been any changes related to the network layer?

Since I am a beginner, there are many conceptually difficult parts. I would appreciate it if you could give me some advice.

thank you.
