### DISCUSSION TITLE
How to get /var/run/docker.sock for docker in docker ?

### DISCUSSION THREAD

**Discussion by jackchuong** [k3s-io/k3s#8949] [Q&A] [answered]
Hi all,
I deploy k8s cluster with k3s as below
`curl -sfL https://get.k3s.io | sh -s - --disable=servicelb,traefik,local-storage`
So it used containerd instead of docker by default ?
If I have a demo.yaml as below
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  containers:
   - name: dockercontainer
     image: docker:20
     command: ["sleep", "43200"]
     volumeMounts:
       - name: docker
         mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
```
How can I provide sock file for this pod ?
