### DISCUSSION TITLE
IP whitelisting on hostPort and NodePort

### DISCUSSION THREAD

**Discussion by pascalw** [k3s-io/k3s#9234] [Q&A] [answered]
I ran into this a couple of times already, but never found a solution. How can I use iptables rules to limit access to `hostPort`s and `NodePort`s? It seems that due to the way that k3s exposes hostPort and NodePorts, regular INPUT iptables rules don't work.

**Example**
NodePort

```yaml
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 30022
    protocol: TCP
```

Iptables rule:

```
*filter

-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP

# abbreviated

-A INPUT -p tcp -m tcp --dport 30022 -j REJECT

## FORWARD ##
-A FORWARD -j ACCEPT
-P FORWARD ACCEPT

## OUTPUT ##
-A OUTPUT -j ACCEPT

COMMIT
```

With this in place, the port can still be accesd externally. Same for ports exposed with `hostPort`. Is there any way to affect exposed `hostPort`s and `NodePort`s with iptables rules?

**Comment by brandond** [comment, marked as answer]
Have you tried using network policy?

**Reply by pascalw** [reply]
Thanks @brandond! I wasn't aware of network policy. It indeed works fine for this use case. For others that might be looking here:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: example-network-policy
spec:
  podSelector:
    matchLabels:
      name: example
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            # ip or block here to allow
            cidr: 1.1.1.1/32
      ports:
        - protocol: TCP
          port: 1234
```

This blocks all incoming traffic to the pod(s), except for what is explicitly allowed.
