### DISCUSSION TITLE
LoadBalancer (ServiceLB) service doesn't seem to respect firewalld

### DISCUSSION THREAD

**Discussion by n-p-e** [k3s-io/k3s#9525] [Q&A]
I encountered this on a Fedora host with firewalld installed and enabled. The service's port is exposed (accessible from outside) even if the firewall is configured to reject the packets.

This is a minimal example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-http-server
  template:
    metadata:
      labels:
        app: python-http-server
    spec:
      containers:
      - name: python
        image: python:3.9-slim
        command: ["python3", "-m", "http.server", "8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-http-service
spec:
  type: LoadBalancer
  selector:
    app: python-http-server
  ports:
    - port: 8080
      targetPort: 8080

```

Through looking at the output of `nft -s list ruleset` my guess is that the iptables-nft rules defined by ServiceLB took precedence over firewalld, specifically these lines: (note lower priority means higher precedence)

```
	chain KUBE-SERVICES {
		meta l4proto tcp ip daddr 10.43.170.54  tcp dport 8080 counter jump KUBE-SVC-CVG3OEGEH7H5P3HQ
		meta l4proto tcp ip daddr 192.168.0.100  tcp dport 8080 counter jump KUBE-EXT-CVG3OEGEH7H5P3HQ
                ... other similar rules ...
		 fib daddr type local counter jump KUBE-NODEPORTS
	}


	chain OUTPUT {
		type nat hook output priority -100; policy accept;
		 counter jump KUBE-SERVICES
		fib daddr type local counter jump CNI-HOSTPORT-DNAT
		fib daddr type local counter jump NETAVARK-HOSTPORT-DNAT
	}

	chain PREROUTING {
		type nat hook prerouting priority dstnat; policy accept;
		 counter jump KUBE-SERVICES
		fib daddr type local counter jump CNI-HOSTPORT-DNAT
		fib daddr type local counter jump NETAVARK-HOSTPORT-DNAT
	}
```

I'm not sure if this behaviour is intended or not. Although by creating a LoadBalancer you probably do want this service to be exposed, there are use cases where you use the firewall to restrict it to internal IP range, for example. And unknowingly have your service open to the internet can be a security risk.

My temporary fix is to define nft rules like this:

```
flush table inet k3s_fix

table inet k3s_fix {
    chain prerouting {
        type filter hook prerouting priority -110; policy accept;
        jump rejected
    }
    chain input {
        type filter hook input priority -110; policy accept;
        jump rejected
    }

    chain rejected {
        ip daddr 192.168.0.100 tcp dport 5432 reject
    }
}
```

But it would be nicer if firewalld can be used instead.
