### DISCUSSION TITLE
k3s AES-CBC encryption at rest feature not working

### DISCUSSION THREAD

**Discussion by VivekSheshadari** [k3s-io/k3s#9565] [Q&A] [answered]
**Environmental Info:**
K3s Version: 
k3s version v1.27.4+k3s1 (36645e73)
go version go1.20.6

Node(s) CPU architecture, OS, and Version: 
Linux k3d-my-cluster-server-0 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux

Cluster Configuration:
1 server, 2 agents

**Describe the bug:**
k3s AES-CBC encryption at rest feature not working, i have tried the below steps.
started the k3s cluster with argument `--secrets-encryption `
and inside cluster i have tried commands below and the status show perfectly ok, but no secrets are encryted.
```
k3s secrets-encrypt prepare
k3s secrets-encrypt rotate
```
even i have tried with commands like force and reencrypt
![image](https://github.com/k3s-io/k3s/assets/116068845/0e11702b-8941-475c-9410-4113af79b8e3)

**Steps To Reproduce:**
I have used k3d with below configuration to start k3s cluster in local: 
Note: I have also tried the same version of k3s with argument --secrets-encryption it didn't work.
```
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: my-cluster
servers: 1
agents: 2
kubeAPI:
  host: "k3d.test.domain"
  hostIP: "127.0.0.1"
  hostPort: "6445"
# image: my-k3s:latest
image: rancher/k3s:v1.27.4-k3s1
# network: k3d-custom-net
# subnet: "172.28.0.0/16"
token: superSecretToken
volumes:
  - volume: C:\\Users\\Vivek.Sheshadari\\CUSTOM\\GIT\\DevOps\\K3D\\application-volume:/tmp
    nodeFilters:
      - server:0
      - agent:*
  - volume: C:\\Users\\Vivek.Sheshadari\\CUSTOM\\GIT\\DevOps\\K3D\\configs:/var/lib/rancher/k3s/server/manifests
    nodeFilters:
      - server:0
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
env:
  - envVar: bar=baz
    nodeFilters:
      - server:0
hostAliases:
  - ip: 127.0.0.1
    hostnames: 
      - localhost
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
        - settings.workerConnections=2048
  k3s:
    extraArgs:
      - arg: "--cluster-init"
        nodeFilters:
          - server:*
      - arg: "--tls-san=k3d.test.domain"
        nodeFilters:
          - server:*
      - arg: "--kube-apiserver-arg=encryption-provider-config=/var/lib/rancher/k3s/server/manifests/secret_config.yaml"
        nodeFilters:
          - server:*
      - arg: "--secrets-encryption"
        nodeFilters:
          - server:* 
    nodeLabels:
      - label: role=agent
        nodeFilters:
          - agent:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    # gpuRequest: all
    labels:
      - label: role=agent
        nodeFilters:
          - agent:*
    ulimits:
      - name: nofile
        soft: 26677
        hard: 26677
```

- Installed K3s: 

**Expected behavior:**
The secret should be encrypted as per AES_CBC standards and I should not able to decode the secret with base64 command locally.

**Actual behavior:**
The secret should be encrypted as per AES_CBC standards and i should not able to decode the secret with base64 command locally.

**Additional context / logs:**
when i run "`k3s secrets-encrypt status`"
```
Encryption Status: Enabled
Current Rotation Stage: rotate
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2024-02-23T11:42:33Z
        AES-CBC   aescbckey
```
