### DISCUSSION TITLE
port-forwarding doesn't work

### DISCUSSION THREAD

**Discussion by ostapkostyk** [k3s-io/k3s#9704] [Q&A] [answered]
Hello,

I can't get port-forwarding to work (can't access pod from the internet).
I have simple nginx deployment that serves simple html page. Also, I have Traefik IngressRoute and tls encryption. All that works pretty good, I can open a test page from the internet.
But if I try to access the same pod via port-forwarding, it doesn't work.
The port is open in a firewall on a host (I test it with a windows client ```tnc <IP> -port 3003``` and it says ```TcpTestSucceeded : True```)

I turn port forwarding on as follows:
```
user@vmi3:~$ sudo kubectl port-forward -n test test-6c7bcc5f8f-s4tl7 3003:80
[sudo] password for user:
Forwarding from 127.0.0.1:3003 -> 80
```
Then, when I try to reach it from outside, if fails:
```
$ curl http://<HOST_IP>:3003/
curl: (7) Failed to connect to <HOST_IP> port 3003 after 145 ms: Connection refused
```

From the Live Manifest of that pod:
```
spec:
  containers:
    - image: 'nginx:latest'
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 80
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      name: nginx
      ports:
        - containerPort: 80
          name: web
          protocol: TCP
```
and
```
status:
  hostIP: <external_IP_of_the_host>
```

Do I do something wrong?

The above example is just for testing, I have some real deployment where I have networking issues and can't reach a pod with port-forwarding, so I tried to debug it and this led me to this simple example with nginx.
