### DISCUSSION TITLE
Is the kubernetes-dashboard compatible with k3s?

### DISCUSSION THREAD

**Discussion by senpro-ingwersenk** [k3s-io/k3s#9889] [Q&A]
Hello!

I have a few not-so-terminal-savy people in my company that would also like to see what the Kubernetes cluster is doing - so I found this: https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard?modal=values

Most of it should be fine, but since k3s uses Traefik by default for it's ingress, I would like to know if that can still be made working?

I am still relatively new to Kubernetes; now that I understand most of what we have here and how to deploy stuff, I want to expand my knowledge with helm charts - and this seems like a pretty good example.

As far as I understand, I will at least need this:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-dashboard
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: k8s-dashboard
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard 
  targetNamespace: k8s-dashboard
  valuesContent: |-
    # Values here...
```

But do I also need to add an `IngressRoute` (`apiVersion: traefik.containo.us/v1alpha1`) or can I just configure that through the values itself? We mainly use those to set quick connectors like this:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: someservice
  namespace: insomenamespace
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`someservice.our.domain`)
      services:
        - name: someservice
          port: 80
```

Thanks!
