### DISCUSSION TITLE
Private registry mirrors are not registered by K3s even though they are defined in registries.yaml

### DISCUSSION THREAD

**Discussion by natenberenstein** [k3s-io/k3s#9903] [Q&A]
**Environmental Info**
K3s version: v1.28.7+k3s1
go version: go1.21.7

Cluster Configuration:
- 1 server (Centos 7)
- 2 agents (Centos 7)

**Describe the Bug**
When defining the private registry configuration in `/etc/rancher/k3s/registries.yaml` and restarting the k3s server and agents, the mirror configuration is still not defined.  Issue was discovered when I was applying a manifests that creates a Pod and pulls an image from a private docker registry.

**Additional info**
`registries.yaml` in server node is defined as
```yaml
mirrors:
    docker-swpl.com:80:
        endpoint:
            - "http://docker-proxy.com:80" 

config:
    docker-swpl.com:80:
        auth:
            username: "foo"
            password: "bar"
```
When running `crictl info` after restarting the nodes, I get the following info
```
{
...
"config": {
    "registry": {
          "configPath": "/var/lib/rancher/k3s/agent/etc/containerd/certs.d",
          "mirrors": null,
          "configs": null,
          "auths": null,
          "headers": null
    },
    }
}
```
`docker-swpl.com:80` is an insecure registry and `http://docker-proxy.com:80` is a registry-mirror. 

Here is the hosts.toml file generated by k3s for one of the agent nodes:
```
server = "https://docker-swpl.com:80/v2"
capabilities = ["pull", "resolve", "push"]

[host."https://docker-proxy.com:80/v2"]
  capabilities = ["pull", "resolve"]
```

**Expected behavior**
Private registry configuration would be acknowledged by K3s.

**Actual behavior**
The private registry configuration is not acknowledge by K3s based on `crictl info`.
