### DISCUSSION TITLE
CrashLoopBackOff on svclb-traefik pods

### DISCUSSION THREAD

**Discussion by pfaelzerchen** [k3s-io/k3s#9973] [Q&A] [answered]
I deployed k3s without traefik and (accidentaly) with ipv4 single stack operation.

I then deployed the traefik with its helm chart. The service definition is
```yaml
        service:
          # -- Additional entries here will be added to the service spec.
          # -- Cannot contain type, selector or ports entries.
          spec:
            externalTrafficPolicy: Local
          ## List of IP families (e.g. IPv4 and/or IPv6).
          ## ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services
          ipFamilies:
            - IPv4
          #   - IPv6
```

`kubectl -n kube-system get pods` shows 
```
svclb-traefik-8d54e317-5grpr              0/5     CrashLoopBackOff   35 (2m51s ago)   13m
svclb-traefik-8d54e317-h9rfl              0/5     CrashLoopBackOff   35 (3m4s ago)    13m
svclb-traefik-8d54e317-vthz4              0/5     CrashLoopBackOff   35 (3m7s ago)    13m
```
and the log reads like
```
+ trap exit TERM INT
+ BIN_DIR=/sbin
+ check_iptables_mode
+ set +e
+ lsmod
+ grep -qF nf_tables
+ '[' 0 '=' 0 ]
+ mode=nft
+ set -e
+ info 'nft mode detected'
[INFO]  nft mode detected
+ set_nft
+ ln -sf /sbin/xtables-nft-multi /sbin/iptables
+ ln -sf /sbin/xtables-nft-multi /sbin/iptables-save
+ ln -sf /sbin/xtables-nft-multi /sbin/iptables-restore
+ ln -sf /sbin/xtables-nft-multi /sbin/ip6tables
+ start_proxy
+ echo 0.0.0.0/0
+ grep -Eq :
+ iptables -t filter -I FORWARD -s 0.0.0.0/0 -p TCP --dport 32294 -j ACCEPT
+ echo 192.168.1.53
+ grep -Eq :
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 1 '==' 1 ]
+ iptables -t filter -A FORWARD -d 192.168.1.53/32 -p TCP --dport 32294 -j DROP
+ iptables -t nat -I PREROUTING -p TCP --dport 33322 -j DNAT --to 192.168.1.53:32294
+ iptables -t nat -I POSTROUTING -d 192.168.1.53/32 -p TCP -j MASQUERADE
+ echo 2003:c5:a718:100:4a21:bff:fe51:cd9f
+ grep -Eq :
+ cat /proc/sys/net/ipv6/conf/all/forwarding
+ '[' 0 '==' 1 ]
+ exit 1
```

The Error seems to come from `cat /proc/sys/net/ipv6/conf/all/forwarding` being set to '0'. But since the traefik svc specifies single stack operation for ipv4 I would suppose that ipv6 should not be setup after all.

The error is not mission critical as ipv4 is setup and working before the error occurs. However, kubernetes tries regularly to bring the pod back failing again and again.

Did I miss something?
