### ISSUE TITLE
container didn't get the environment var from CONTAINERD_XXX

### ISSUE THREAD

**Issue by ActivePeter** [k3s-io/k3s#10110]
I'm using the k3s with https://github.com/k3s-io/k3s/releases/download/v1.30.0%2Bk3s1/k3s & https://github.com/k3s-io/k3s/releases/download/v1.30.0%2Bk3s1/k3s-airgap-images-amd64.tar.gz.

I found the right configuration of proxy is as follows:

- https://github.com/k3s-io/k3s/pull/3553

- https://docs.k3s.io/advanced#configuring-an-http-proxy

As description, I just need to export the proxy variables when I install the k3s as following:

```
PROXY="http://192.168.31.53:7890"
os.environ['HTTP_PROXY']=PROXY
os.environ['HTTPS_PROXY']=PROXY
os.environ['NO_PROXY']="127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
os.environ['CONTAINERD_HTTP_PROXY']=PROXY
os.environ['CONTAINERD_HTTPS_PROXY']=PROXY
os.environ['CONTAINERD_NO_PROXY']="127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
```

And the environment vars will be added to /etc/systemd/system/k3s.service.env which can be verified.

<img width="546" alt="image" src="https://github.com/k3s-io/k3s/assets/8100696/f37256ad-4745-441e-a2cd-a82b9612f5b8">

However, I started a test daemonset to echo the env in pod (containerd), and I got empty environment var:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: environment-check-daemonset
spec:
  selector:
    matchLabels:
      app: environment-check
  template:
    metadata:
      labels:
        app: environment-check
    spec:
      containers:
      - name: environment-check-container
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - echo "http_proxy=$http_proxy" && echo "HTTP_PROXY=$HTTP_PROXY" && echo "https_proxy=$https_proxy" && echo "HTTPS_PROXY=$HTTPS_PROXY" && echo "no_proxy=$no_proxy" && echo "NO_PROXY=$NO_PROXY" && env
```

Result:
<img width="480" alt="image" src="https://github.com/k3s-io/k3s/assets/8100696/b51b25b4-34ba-46e7-87fb-07d4ac262262">
