### ISSUE TITLE
can't add private registry. isn't listed on k3s crictl info

### ISSUE THREAD

**Issue by UriZafrir** [k3s-io/k3s#10135]
**Environmental Info:**
K3s Version: 
k3s version v1.30.0+k3s1 (14549535)
go version go1.22.2

Node(s) CPU architecture, OS, and Version: 
Linux  5.15.0-107-generic #117~20.04.1-Ubuntu SMP Tue Apr 30 10:35:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
single node cluster

**Describe the bug:**
hi everyone.
I'm running k3s 1.30.0 and can't seem to operate the private registries.
I've created  a registries.yaml file:
```
mirrors:
  abc.sm.local:
    endpoint:
      - "https://abc.sm.local:443"
  configs:
    "abc.sm.local:443":
      auth:
        username: abc
        password: abc
      tls:
        insecure_skip_verify: TRUE
```
but when i look at crictl i get:
```
sudo k3s crictl info  | jq '.config.registry'
{
  "configPath": "/var/lib/rancher/k3s/agent/etc/containerd/certs.d",
  "mirrors": null,
  "configs": null,
  "auths": null,
  "headers": null
}
```
i can see the file is added, with /v2
```
/var/lib/rancher/k3s/agent/etc/containerd/certs.d/abc.sm.local# cat hosts.toml
# File generated by k3s. DO NOT EDIT.

server = "https://abc.sm.local/v2"
capabilities = ["pull", "resolve", "push"]


[host]
[host."https://abc.sm.local:443/v2"]
  capabilities = ["pull", "resolve"]
```
I know that means there's a problem. what am I missing? I tried downgrading to k3s 1.27 but it didn't work.
would love for assistance.

**Steps To Reproduce:**
download files for air-gapped install,
 Install K3s, 
generate registries.yaml, 
copy it to /etc/rancher/k3s/,
sudo systemctl restart k3s
sudo k3s crictl info  | jq '.config.registry'

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Please read the docs at https://docs.k3s.io/installation/private-registry and check your indentation. The `configs` section does NOT belong under the `mirrors` section. Also, you don't need to explicitly list an endpoint for `abc.sm.local` if it is using HTTPS on the default port; that is assumed. The following should suffice:

```yaml
configs:
  abc.sm.local:
    auth:
      username: abc
      password: abc
    tls:
      insecure_skip_verify: TRUE
```
