### ISSUE TITLE
k3s is unable to start sidecar container

### ISSUE THREAD

**Issue by ansidev** [k3s-io/k3s#10264]
**Environmental Info:**
K3s Version: (I use k3d)

k3d version v5.6.3
k3s version v1.28.8-k3s1 (default)

Node(s) CPU architecture, OS, and Version: 

`Linux k3d-k3s-local-server-0 6.7.12-orbstack-00202-g57474688ffbd #1 SMP Mon May 27 09:21:34 UTC 2024 aarch64 GNU/Linux`

Cluster Configuration:

1 server and 2 agents

**Describe the bug:**

**Steps To Reproduce:**

- Install dependencies: `brew install k3d helm`
- Installed K3s:
```
k3d cluster create k3s-local \
          --api-port 6550 \
          --port "8080:80@loadbalancer" \
          --agents 2 \
          --k3s-arg "--kubelet-arg=feature-gates=CloudDualStackNodeIPs=true,SidecarContainers=true@agent:0" \
          --k3s-arg "--kubelet-arg=feature-gates=CloudDualStackNodeIPs=true,SidecarContainers=true@agent:1"
```
- Waiting until the cluster is ready.
- Deploy app (https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: alpine:latest
          command: ['sh', '-c', 'while true; do echo "logging" >> /opt/logs.txt; sleep 1; done']
          volumeMounts:
            - name: data
              mountPath: /opt
      initContainers:
        - name: logshipper
          image: alpine:latest
          restartPolicy: Always
          command: ['sh', '-c', 'tail -F /opt/logs.txt']
          volumeMounts:
            - name: data
              mountPath: /opt
      volumes:
        - name: data
          emptyDir: {}
```

**Expected behavior:**

Deployment is finished successfully.

**Actual behavior:**

Deployment is failed.

**Additional context / logs:**

```
kubectl --namespace k3s-local get pod nginx-sidecar

NAME            READY   STATUS       RESTARTS      AGE
nginx-sidecar   0/1     Init:Error   4 (65s ago)   118s
```

```
kubectl --namespace k3s-local describe pod nginx-sidecar

Name:             nginx-sidecar
Namespace:        k3s-local
Priority:         0
Service Account:  default
Node:             k3d-k3s-local-agent-1/192.168.214.4
Start Time:       Sat, 01 Jun 2024 02:22:49 +0700
Labels:           app=nginx
Annotations:      <none>
Status:           Pending
IP:               10.42.1.8
IPs:
  IP:  10.42.1.8
Init Containers:
  nginx-log:
    Container ID:  containerd://ddc4e374a8c79c2bdd21844d12f6d8c3f93aae34c7616e88a49b6abd1959900c
    Image:         busybox
    Image ID:      docker.io/library/busybox@sha256:5eef5ed34e1e1ff0a4ae850395cbf665c4de6b4b83a32a0bc7bcb998e24e7bbb
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      tail -f /var/log/nginx/access.log
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 01 Jun 2024 02:24:39 +0700
      Finished:     Sat, 01 Jun 2024 02:24:39 +0700
    Ready:          False
    Restart Count:  4
    Environment:    <none>
    Mounts:
      /var/log/nginx from logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-g4js9 (ro)
Containers:
  nginx-app:
    Container ID:
    Image:          nginx:latest
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/log/nginx from logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-g4js9 (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  logs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-g4js9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  2m55s                 default-scheduler  Successfully assigned k3s-local/nginx-sidecar to k3d-k3s-local-agent-1
  Normal   Pulled     2m52s                 kubelet            Successfully pulled image "busybox" in 3.083s (3.083s including waiting)
  Normal   Pulled     2m49s                 kubelet            Successfully pulled image "busybox" in 2.921s (2.921s including waiting)
  Normal   Pulled     2m32s                 kubelet            Successfully pulled image "busybox" in 2.895s (2.895s including waiting)
  Normal   Pulled     2m3s                  kubelet            Successfully pulled image "busybox" in 2.809s (2.809s including waiting)
  Normal   Created    2m3s (x4 over 2m52s)  kubelet            Created container nginx-log
  Normal   Started    2m3s (x4 over 2m52s)  kubelet            Started container nginx-log
  Warning  BackOff    84s (x8 over 2m49s)   kubelet            Back-off restarting failed container nginx-log in pod nginx-sidecar_k3s-local(4f492808-bc78-479e-b5bb-df5f1fdd8fe0)
  Normal   Pulling    69s (x5 over 2m55s)   kubelet            Pulling image "busybox"
```

```
kubectl get --raw '/api/v1/nodes/k3d-k3s-local-server-0/proxy/configz' | jq .kubeletconfig.featureGates

{
  "CloudDualStackNodeIPs": true
}
```

```
kubectl get --raw '/api/v1/nodes/k3d-k3s-local-agent-0/proxy/configz' | jq .kubeletconfig.featureGates

{
  "CloudDualStackNodeIPs": true,
  "SidecarContainers": true
}
```

```
kubectl get --raw '/api/v1/nodes/k3d-k3s-local-agent-1/proxy/configz' | jq .kubeletconfig.featureGates

{
  "CloudDualStackNodeIPs": true,
  "SidecarContainers": true
}
```
