### ISSUE TITLE
I can't configure the docker.io image repository

### ISSUE THREAD

**Issue by ihezebin** [k3s-io/k3s#10343]
curl -sfLk https://get.k3s.io | INSTALL_K3S_VERSION=v1.28.9+k3s1 sh -s - --disable traefik --disable-default-registry-endpoint

centos7

vi /etc/rancher/k3s/registries.yaml

```yaml
mirrors:
  "docker.io":
    endpoint:
      - "https://uph96ue9.mirror.aliyuncs.com",
      - "https://mirror.ccs.tencentyun.com",
      - "https://hub-mirror.c.163.com",
      - "https://mirror.baidubce.com"
  "ccr.ccs.tencentyun.com":
    endpoint:
      - "https://ccr.ccs.tencentyun.com"
  "registry.cn-hangzhou.aliyuncs.com":
    endpoint:
      - "https://registry.cn-hangzhou.aliyuncs.com"
configs:
  "registry.cn-hangzhou.aliyuncs.com":
    auth:
      username: ihezebin
      password: xxxx
  "ccr.ccs.tencentyun.com":
    auth:
      username: 100009173056
      password: xxxx
```

sudo systemctl restart k3s

`cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml` not have any changes

```
[root@hezebin-k3s-master ~]# k get nodes
NAME                 STATUS     ROLES                  AGE     VERSION
hezebin-k3s-master   NotReady   control-plane,master   2m50s   v1.28.9+k3s1
```

but if remove the docker config, like this:
```
mirrors:
  "ccr.ccs.tencentyun.com":
    endpoint:
      - "https://ccr.ccs.tencentyun.com"
  "registry.cn-hangzhou.aliyuncs.com":
    endpoint:
      - "https://registry.cn-hangzhou.aliyuncs.com"
configs:
  "registry.cn-hangzhou.aliyuncs.com":
    auth:
      username: ihezebin
      password: xxxxxx
  "ccr.ccs.tencentyun.com":
    auth:
      username: 100009173056
      password: xxxx
```
<img width="707" alt="image" src="https://github.com/k3s-io/k3s/assets/36706912/be650f61-1757-4663-856e-1f5405da9a4d">
