### ISSUE TITLE
Allow configuration of Rootlesskit's CopyUpDirs through an environment variable

### ISSUE THREAD

**Issue by ludost** [k3s-io/k3s#10385]
**Is your feature request related to a problem? Please describe.**

In our use-case, (see also issue:  #10295) we are running a K3S Agent in a Rootless environment at the end-user's own workstation. This works well (enough), but we also want to provide access to the local folders (through e.g. HostPath volume mounts). But the Agent runs inside the rootless namespace, disallowing read/write access to the actual file-system.

Currently the rootless configuration is hardcoded where the CopyUpDirs are concerned. With this issue, I've created a PR that allows the Agent to setup extra "CopyUpDirs" entries, through an environment variable called "K3S_ROOTLESS_COPYUPDIRS". This environment variable can receive a comma-separated list absolute paths, which will be added to the existing list.

**Describe the solution you'd like**

See the related PR.

**Describe alternatives you've considered**

Within the context of running rootless I see no alternative to this change. The namespace container is meant specifically to block this kind of access, with the CopyUpDirs parameter the "normal" way of explicitly exposing external folders. We can also consider a more advanced configuration model, but the rest of the rootless package is using environment variables as well for this purpose.

**Additional context**

**Comment by brandond** [comment]
Unstale, we can evaluate for 2024-10

**Comment by brandond** [comment]
@ludost can you address PR feedback and rebase your PR? If so we can look at this for the October cycle.

**Comment by mdrahman-suse** [comment]
@ludost I am not able to validate the issue by following the steps mentioned: https://github.com/k3s-io/k3s/pull/10386#issue-2364619647 as I see the same behavior on previous versions and master commit, regardless of using the env var `K3S_ROOTLESS_COPYUPDIRS`. Using single node Ubuntu server

```
$ systemctl --user status k3s-rootless
● k3s-rootless.service - k3s (Rootless)
     Loaded: loaded (/home/ubuntu/.config/systemd/user/k3s-rootless.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-10-10 03:23:52 UTC; 10min ago
   Main PID: 903 (k3s-server)
      Tasks: 187
     Memory: 1.9G
        CPU: 1min 53.010s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/k3s-rootless.service
```

I deployed a simple nginx pod
```
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "basic"
  labels:
    name: "basic"
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: "basic"
      image: nginx:1.14.2
      ports:
        - containerPort: 80
          name: "basic"
      volumeMounts:
        - mountPath: "/my_share/"
          name: "container-share"
  volumes:
    - hostPath:
        path: "/home/ubuntu/containerShare/"
        type: ""
      name: "container-share"
```
and also created a local folder `containerShare`. When I created a file inside the container, I was able to see the file on the local folder, even on the older version (v1.31.1+k3s1). So I am not sure if I am missing any steps. I am following these steps to enable k3s-rootless.service on an ubuntu instance: https://github.com/k3s-io/k3s/issues/3636#issuecomment-1631586671

Please advice. 
CC @brandond @ShylajaDevadiga 

On previous version v1.31.1+k3s1, (Downloaded `k3s-rootless.service` for that version)
```
$ k3s -v
k3s version v1.31.1+k3s1 (452dbbc1)
go version go1.22.6

$ kubectl exec -it pod/basic -- touch my_share/hello.txt
$ kubectl exec -it pod/basic -- ls my_share
hello.txt
$ ls containerShare/
hello.txt
```
On master commit (Downloaded `k3s-rootless.service` from master)
```
$ k3s -v
k3s version v1.31.1+k3s-e475ba70 (e475ba70)
go version go1.22.6

$ kubectl exec -it pod/basic -- touch my_share/hello.txt
$ kubectl exec -it pod/basic -- ls my_share
hello.txt
$ ls containerShare/
hello.txt
```
