### ISSUE TITLE
Cannot override k3s default kubelet-args via user-provided kubelet config file

### ISSUE THREAD

**Issue by fmunteanu** [k3s-io/k3s#10399]
**Environmental Info:**
K3s Version: 

```
k3s version v1.29.4+k3s1 (94e29e2e)
go version go1.21.9
```

Node(s) CPU architecture, OS, and Version: 

```
Linux apollo 6.8.0-1005-raspi #5-Ubuntu SMP PREEMPT_DYNAMIC Wed May 22 15:01:35 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

Cluster Configuration:

- 3 control planes
- 5 workers

**Describe the bug:**

While using:

```
kubelet-arg:
  - config=/etc/rancher/k3s/kubelet.yaml
```

With `/etc/rancher/k3s/kubelet.yaml` contents:

```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
evictionHard:
  memory.available: "500Mi"
  nodefs.available: "10%"
  nodefs.inodesFree: "5%"
evictionSoft:
  memory.available: "1Gi"
  nodefs.available: "30%"
  nodefs.inodesFree: "15%"
evictionSoftGracePeriod:
  memory.available: "30s"
  nodefs.available: "30s"
  nodefs.inodesFree: "30s"
evictionMaxPodGracePeriod: 60
systemReserved:
  cpu: "1"
  ephemeral-storage: "5Gi"
  memory: "1Gi"
```

`evictionHard` arg/values are ignored, while other settings are properly reflected, when I run:

```
$ curl -X GET http://127.0.0.1:8001/api/v1/nodes/apollo/proxy/configz -s | jq .kubeletconfig
  "evictionHard": {
    "imagefs.available": "5%",
    "nodefs.available": "5%"
  },
  "evictionSoft": {
    "memory.available": "1Gi",
    "nodefs.available": "30%",
    "nodefs.inodesFree": "15%"
  },
  "evictionSoftGracePeriod": {
    "memory.available": "30s",
    "nodefs.available": "30s",
    "nodefs.inodesFree": "30s"
  },
  "evictionMaxPodGracePeriod": 60
```

**Steps To Reproduce:**

Current `config.yaml`:

```
# cat /etc/rancher/k3s/config.yaml
bind-address: 192.168.4.2
cluster-dns: 10.43.0.10
cluster-domain: cluster.local
disable:
  - local-storage
  - servicelb
  - traefik
disable-cloud-controller: true
disable-kube-proxy: true
disable-network-policy: true
embedded-registry: true
etcd-expose-metrics: true
flannel-backend: none
kubelet-arg:
  - config=/etc/rancher/k3s/kubelet.yaml
node-taint:
  - node.cilium.io/agent-not-ready:NoExecute
  - node-role.kubernetes.io/control-plane:NoSchedule
server: https://192.168.4.10:6443
tls-san:
  - 192.168.4.10
token: redacted
```

However, if I pass directly the arg/values into `config.yaml`, everything works as expected.

New `config.yaml`:

```
# cat /etc/rancher/k3s/config.yaml
bind-address: 192.168.4.2
cluster-dns: 10.43.0.10
cluster-domain: cluster.local
disable:
  - local-storage
  - servicelb
  - traefik
disable-cloud-controller: true
disable-kube-proxy: true
disable-network-policy: true
embedded-registry: true
etcd-expose-metrics: true
flannel-backend: none
kubelet-arg:
  - eviction-hard=memory.available<500Mi,nodefs.available<10%,nodefs.inodesFree<5%
  - eviction-max-pod-grace-period=60
  - eviction-soft=memory.available<1Gi,nodefs.available<30%,nodefs.inodesFree<15%
  - eviction-soft-grace-period=memory.available=30s,nodefs.available=30s,nodefs.inodesFree=30s
  - system-reserved=cpu=1,ephemeral-storage=5Gi,memory=1Gi
node-taint:
  - node.cilium.io/agent-not-ready:NoExecute
  - node-role.kubernetes.io/control-plane:NoSchedule
server: https://192.168.4.10:6443
tls-san:
  - 192.168.4.10
token: redacted
```

Settings are correct:

```
$ curl -X GET http://127.0.0.1:8001/api/v1/nodes/apollo/proxy/configz -s | jq .kubeletconfig
  "evictionHard": {
    "memory.available": "500Mi",
    "nodefs.available": "10%",
    "nodefs.inodesFree": "5%"
  },
  "evictionSoft": {
    "memory.available": "1Gi",
    "nodefs.available": "30%",
    "nodefs.inodesFree": "15%"
  },
  "evictionSoftGracePeriod": {
    "memory.available": "30s",
    "nodefs.available": "30s",
    "nodefs.inodesFree": "30s"
  },
  "evictionMaxPodGracePeriod": 60
```

Edit: Same issue occurs for `evictionMinimumReclaim`, it only works if you pass the values directly, not through `kubelet.yaml` configuration:

```
evictionMinimumReclaim:
  imagefs.available: "10%"
  imagefs.inodesFree: "5%"
  memory.available: "500Mi"
  nodefs.available: "10%"
  nodefs.inodesFree: "5%"
```

Actual settings:

```
$ curl -X GET http://127.0.0.1:8001/api/v1/nodes/apollo/proxy/configz -s | jq .kubeletconfig
  "evictionMinimumReclaim": {
    "imagefs.available": "10%",
    "nodefs.available": "10%"
  }
```
