### ISSUE TITLE
Node cannot get it´s IP - host IP unknown; known addresses: []

### ISSUE THREAD

**Issue by brpaz** [k3s-io/k3s#10407]
**Environmental Info:**
K3s Version: 
k3s version v1.29.5+k3s1 (4e53a323)
go version go1.21.9

Node(s) CPU architecture, OS, and Version: 
Linux k3s-control-plane 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single node cluster deployed on Hetnzer cloud.

**Describe the bug:**
I have set up a single-node  k3s cluster On the Hetnzer cloud, with:

``` 
curl -sfL https://get.k3s.io | sh 
``` 

and the following configuration file:

```yaml
 node-name: ${hostname}
  cluster-init: true
  kubelet-arg:
    - "cloud-provider=external"
    - "max-pods=500"
  disable:
    - traefik
    - servicelb
    - metrics-server
  flannel-backend: none
  disable-cloud-controller: true
  disable-network-policy: true
  disable-helm-controller: true
  write-kubeconfig-mode: 644
  kube-apiserver-arg:
    - "--kubelet-preferred-address-types=InternalIP,ExternalIP"
```

The server starts, and I got some messages in the logs, saying the `cni` is not initialized, which makes sense, since I disabled the `flannel backend`.

I then, went to install Cilium, following the instructions on the Cilium website. But I got the following error on Cilium pods:

```
   unable to retrieve cilium status: error with exec request (pod=kube-system/cilium-vxb9w, container=cilium-agent): no preferred addresses found; known addresses: []
```

After checking the k3s logs in more detail, I noticed the following errors that could be the cause:

```
Jun 26 10:47:26 k3s-control-plane k3s[13209]: E0626 10:47:26.494755   13209 server.go:1044] "Failed to retrieve node IPs" err="host IP unknown; known addresses: []"
Jun 26 10:47:45 k3s-control-plane k3s[13209]: E0626 10:47:45.240590   13209 server.go:1044] "Failed to retrieve node IPs" err="host IP unknown; known addresses: []"
Jun 26 10:47:45 k3s-control-plane k3s[13209]: I0626 10:47:45.240676   13209 server.go:1020] "Can't determine this node's IP, assuming loopback; if this is incorrect, please set the --bind-address flag"
```

So, it seems that k3s cannot detect the node IP properly for some reason. I tried set `node-ip` in the k3s config, `tls-san` but nothing seems to work.

Not sure if can be something related with Hetnzer. I have been able to install k3s before but I used a different approach (Ansible) and an older version.

Also, I have following this guide https://community.hetzner.com/tutorials/setup-your-own-scalable-kubernetes-cluster, using exactly the same network configs. 

I spent the entire morning on this. I don´t know what to do anymore.

**Steps To Reproduce:**
- Provision  Hetnzer instance
- Installed K3s with the previous configuration
- `run cilium install` to install Cilium

**Expected behavior:**
Cluster should start and be able to install Cilium

**Actual behavior:**
CIlium gives error on install.

**Additional context / logs:**
[full_logs.txt](https://github.com/user-attachments/files/15987256/full_logs.txt)
