### ISSUE TITLE
terminated-pod-gc-threshold appears to have no effect

### ISSUE THREAD

**Issue by dns2utf8-novaziun** [k3s-io/k3s#10448]
**Environmental Info:**
K3s Version:

k3s version v1.30.1+k3s1 (80978b5b)
go version go1.22.2

Node(s) CPU architecture, OS, and Version: 

6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux

Cluster Configuration:

**Describe the bug:**

In the hardening guide there is a hint that adding `'terminated-pod-gc-threshold=10'` in `/etc/rancher/k3s/config.yaml` should tell k3s to cleanup after 10 pods have terminated.
https://docs.k3s.io/security/hardening-guide#configuration-for-kubernetes-components

**Steps To Reproduce:**

- Installed K3s: 
- Install a 7 containers
- Update these containers over and over and over again (same tag, different content)
- Watch the disk fill up

**Expected behavior:**

After 10 (like configured)  Updates I would expect the kubelet to free up some space again.

**Actual behavior:**

Watch the disk fill up, consider reinstalling the server every 3 months.

**Additional context / logs:**

Apart from the disk usage it works really well.
What I noticed is that the GC kicks in when the disk space is about to run out. But that is very stressful and makes planing hard.

**Comment by brandond** [comment]
What does your config.yaml look like? Did you put it in the kubelet-args section as shown in the docs? There are other arts that also affect the GC thresholds, you can reference the upstream Kubelet docs for more information.

**Comment by dns2utf8-novaziun** [comment]
This is the full config of the cluster:

```yaml
write-kubeconfig-mode: "0644"
tls-san:
  - "example.net"
  - "*.example.net
node-label:
  - "datacenter_powersource=hydro"
  - "something=amazing"
cluster-init: true
kubelet-arg:
  - "resolv-conf=/etc/k3s-resolv.conf"
kube-controller-manager-arg:
  - 'terminated-pod-gc-threshold=10'
```
