### ISSUE TITLE
Getting net.ipv6.conf.all.forwarding=1 restriction when using IPv4 ipFamily with ipFamilyPolicy SingleStack

### ISSUE THREAD

**Issue by eugene-chernyshenko** [k3s-io/k3s#10690]
Applying this demo service I get net.ipv6.conf.all.forwarding restriction

```
kubectl -n kube-system get ds svclb-test-35e2e1e5 -o yaml  | grep sysctls -A 4
        sysctls:
        - name: net.ipv4.ip_forward
          value: "1"
        - name: net.ipv6.conf.all.forwarding
          value: "1"
``` 
      
```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: some
      port: 4319
      protocol: TCP
      targetPort: 4319
  selector:
    app.kubernetes.io/instance: some
    app.kubernetes.io/name: some
    component: some
  type: LoadBalancer
```

I specified  only IPv4 ipFamilies value and also ipFamilyPolicy SingleStack

According to [this code ](https://github.com/k3s-io/k3s/blob/b11486d3cd4aa40f3102577ab7352de5992ca43d/pkg/cloudprovider/servicelb.go#L446) ipv6 restriction should not be created

```
k3s --version
k3s version v1.30.3+k3s1 (f6466040)
go version go1.22.5
```
