### ISSUE TITLE
[Release-1.30] - Customize servicelb daemonset tolerations (traefik)

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10698]
Backport fix for Customize servicelb daemonset tolerations (traefik)

* #1988

**Comment by mdrahman-suse** [comment]
# Validation with RC v1.30.4-rc1+k3s1

## Environment and config
```
Ubuntu 22.04, Single server
```
- /etc/rancher/k3s/config.yaml
```
write-kubeconfig-mode: 644
cluster-init: true
node-name: server1
```
## Additional files
- lb.yaml

<details>

```
apiVersion: v1
kind: Namespace
metadata:
  name: test-loadbalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-loadbalancer
  namespace: test-loadbalancer
spec:
  selector:
    matchLabels:
      k8s-app: nginx-app-loadbalancer
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: nginx-app-loadbalancer
    spec:
      containers:
        - name: nginx
          image: ranchertest/mytestcontainer:unprivileged
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-svc
  namespace: test-loadbalancer
  labels:
    k8s-app: nginx-app-loadbalancer
  annotations:
    svccontroller.k3s.cattle.io/tolerations: |
      - effect: NoSchedule
        key: public
        operator: Exists
      - effect: NoExecute
        key: disk
        operator: Equal
        value: ssd
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    k8s-app: nginx-app-loadbalancer
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-nginxlb-svclbtraefik-ingress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      svccontroller.k3s.cattle.io/svcname: nginx-loadbalancer-svc
  ingress:
    - {}
  policyTypes:
    - Ingress
```

</details>

## Testing

- Install k3s
- Ensure cluster is up and running
- Apply the example lb.yaml that contains service the annotations below:
```
annotations:
    svccontroller.k3s.cattle.io/tolerations: |
      - effect: NoSchedule
        key: public
        operator: Exists
      - effect: NoExecute
        key: disk
        operator: Equal
        value: ssd
```
- Check toleration is applied on the svclb pod

## Replication
```
k3s -v
k3s version v1.30.3+k3s1 (f6466040)
go version go1.22.5
```
- Custom annotations are not observed
```
$ k get daemonset -A
NAMESPACE     NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   svclb-nginx-loadbalancer-svc-bcd1b865   1         1         1       1            1           <none>          81s
kube-system   svclb-traefik-315193d8                  1         1         1       1            1           <none>          15m

$ k describe -n kube-system pod/svclb-nginx-loadbalancer-svc-bcd1b865-qj9p4
Name:                 svclb-nginx-loadbalancer-svc-bcd1b865-qj9p4
Namespace:            kube-system
...
Tolerations:                  CriticalAddonsOnly op=Exists
                              node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                              node-role.kubernetes.io/master:NoSchedule op=Exists
                              node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                              node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                              node.kubernetes.io/not-ready:NoExecute op=Exists
                              node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                              node.kubernetes.io/unreachable:NoExecute op=Exists
                              node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  2m27s  default-scheduler  Successfully assigned kube-system/svclb-nginx-loadbalancer-svc-bcd1b865-qj9p4 to server1
...
```

## Validation
```
$ k3s -v
k3s version v1.30.4-rc1+k3s1 (98262b5d)
go version go1.22.5
```
- Custom annotations are observed
```
$ k get daemonset -A
NAMESPACE     NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   svclb-nginx-loadbalancer-svc-93fa7998   1         1         1       1            1           <none>          31s
kube-system   svclb-traefik-d9bf3885                  1         1         1       1            1           <none>          5m50s

$ k describe -n kube-system pod/svclb-nginx-loadbalancer-svc-93fa7998-ln2pw
Name:                 svclb-nginx-loadbalancer-svc-93fa7998-ln2pw
Namespace:            kube-system
...
Tolerations:                  CriticalAddonsOnly op=Exists
                              disk=ssd:NoExecute
                              node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                              node-role.kubernetes.io/master:NoSchedule op=Exists
                              node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                              node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                              node.kubernetes.io/not-ready:NoExecute op=Exists
                              node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                              node.kubernetes.io/unreachable:NoExecute op=Exists
                              node.kubernetes.io/unschedulable:NoSchedule op=Exists
                              public:NoSchedule op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  54s   default-scheduler  Successfully assigned kube-system/svclb-nginx-loadbalancer-svc-93fa7998-ln2pw to server1
```
