### ISSUE TITLE
Enabling `hostIPC` does not have any effect

### ISSUE THREAD

**Issue by remod** [k3s-io/k3s#10757]
**Environmental Info:**
K3s Version: 

```
k3s version v1.30.1+k3s1 (80978b5b)
go version go1.22.2
```

Node(s) CPU architecture, OS, and Version: 

```
Linux remod-p1 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

1 server, 1 agent

**Describe the bug:**

It seems that enabling `hostIPC` does not have any effect.

**Steps To Reproduce:**

- Installed K3s: `curl -sfL https://get.k3s.io | sh -`
- Create a pod definition:
```
echo "apiVersion: v1
kind: Pod
metadata:
  name: test-ipc
spec:
  hostIPC: true
  containers:
    - name: test-ipc
      image: ubuntu:focal
      command: [\"sh\", \"-c\"]
      args: [\"while true; do echo 'foo'; sleep 1; done;\"]" > test-ipc-pod.yaml
 ```
- Install pod: `kubectl apply -f  test-ipc-pod.yaml`
- Check IPC mode: `docker inspect $(docker ps -q --filter "name=k8s_test-ipc") | grep IpcMode`

**Expected behavior:**

The `IpcMode` is set as if you'd run a docker image with `--ipc=host`:

`"IpcMode": "host",`

**Actual behavior:**

`"IpcMode": "container:e86cde4006dd4ebb82229db13e77b223e248b4969dc3738d58600971874ff372",`

**Additional context / logs:**

I've noticed that the `POD` sibling of the container uses `"IpcMode": "host"`, but that seems to be independent of whether I am setting `hostIPC` to `true` or `false`:

```
$ docker inspect $(docker ps -q --filter "name=k8s_POD_test-ipc") | grep IpcMode
            "IpcMode": "host",
```
