### ISSUE TITLE
[Bug/Feature Request] K3s fails to use secondary mirror when primary mirror lacks required images

### ISSUE THREAD

**Issue by gowy222** [k3s-io/k3s#10756]
Title: [Bug/Feature Request] K3s fails to use secondary mirror when primary mirror lacks required images

env: v1.30.4+k3s1

Description:
When configuring multiple mirror endpoints for a registry in the `registries.yaml` file, K3s does not automatically switch to the second endpoint if the first one fails to provide the required image. This behavior severely impacts the reliability of Kubernetes clusters, especially in scenarios where the primary mirror is incomplete but must be kept as the first option due to some business requirements.

Current Behavior:
K3s persistently attempts to use only the first specified mirror endpoint, even when it fails to provide the required image. It does not attempt to use the second mirror, which is known to have the missing image.

Expected Behavior:
When multiple mirror endpoints are configured for a registry, K3s should attempt to use them in the order specified. If the first endpoint fails to provide the required image, K3s should automatically try the next endpoint in the list.

Example Configuration:
```
yaml
mirrors:
  docker.io:
    endpoint:
      - "https://mirror.ccs.tencentyun.com"     # public
      - "https://docker.example2.com"           # private need auth
    rewrite:
      "^rancher/(.*)": "docker.example2.com/rancher/$1"

configs:
  "docker.example2.com":
    auth:
      username: custom_mirror_username
      password: custom_mirror_password
    tls:
      insecure_skip_verify: true
```

log no rewrite :
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image
 "rancher/mirrored-pause:3.6": failed to pull image
 "rancher/mirrored-pause:3.6": failed to pull 
and unpack image
 "docker.io/rancher/mirrored-pause:3.6": failed to copy:
 httpReadSeeker: failed open: failed to do request: 
Get "https://mirror.ccs.tencentyun.com/v2/rancher/mirrored-pause/blobs/sha256:7d46a07936af93fcce097459055f93ab07331509aa55f4a2a90d95a3ace1850e?ns=docker.io": 
dial tcp: lookup mirror.ccs.tencentyun.com: no such host

```

log: with rewrite BUG?
```
Failed to create pod sandbox: rpc error: code = Unknown desc = 
failed to get sandbox image "rancher/mirrored-pause:3.6": 
failed to pull image "rancher/mirrored-pause:3.6":
 failed to pull and unpack image "docker.io/rancher/mirrored-pause:3.6": 
failed to copy: httpReadSeeker: failed open: failed to do request:

 Get "https://mirror.ccs.tencentyun.com/v2/docker.example2.com/rancher/mirrored- //BUG?

pause/blobs/sha256:7d46a07936af93fcce097459055f93ab07331509aa55f4a2a90d95a3ace1850e?ns=docker.io": dial tcp: lookup mirror.ccs.tencentyun.com: no such host

```
