### ISSUE TITLE
failed to get docker runtime info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

### ISSUE THREAD

**Issue by 2694484453** [k3s-io/k3s#10782]
###########################################
docker version
```console
root@iZbp1chs1na7nj4qz70ep1Z:/# docker version
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.3
 Git commit:        24.0.5-0ubuntu1~20.04.1
 Built:             Mon Aug 21 19:50:14 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       24.0.5-0ubuntu1~20.04.1
  Built:            Mon Aug 21 19:50:14 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.2
  GitCommit:        
 runc:
  Version:          1.1.7-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:      
```
#################################################
service
```
 docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-08-30 03:01:10 CST; 7h ago
```
##################################################
docker-compose.yml
```yaml
version: "3"
services:
  k3s-node1:
    image: registry.cn-hangzhou.aliyuncs.com/gpg_dev/k3s:v1.24.10-k3s1
    container_name: k3s-1
    privileged: true
    hostname: k3s-node1
    ports:
      - "6443:6443"
      - "19090:19090"
    tmpfs:
      - /run
      - /var/run
    environment:
      - K3S_KUBECONFIG_OUTPUT=/root/.kube/config
      - K3S_KUBECONFIG_MODE=644
    command:
      - server
     # - --disable=traefik  #不需要部署的组件，删除任何已部署的组件 (有效项目：coredns, servicelb, traefik,local-storage, metrics-server)
      - --etcd-expose-metrics=true #将 etcd 指标公开给客户端界面。(默认为 false)
      - --private-registry="/etc/rancher/k3s/registries.yaml" #私有镜像仓库配置文件
      # - --pause-image="docker.io/rancher/pause:3.1"  #针对 containerd 或 Docker 的自定义 pause 镜像
      - --docker #docker代替containerd
    volumes:
      #- ./k3s.yaml:/etc/rancher/k3s/k3s.yaml
      - /root/.kube:/root/.kube
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml
      - ./velero-7.0.1.tgz:/var/lib/rancher/k3s/server/static/charts/velero-7.0.1.tgz
      - ./kubernetes-dashboard-7.5.0.tgz:/var/lib/rancher/k3s/server/static/charts/kubernetes-dashboard-7.5.0.tgz
      - ./velero.yaml:/var/lib/rancher/k3s/server/manifests/velero.yaml
      - ./kubernetes-dashboard.yaml:/var/lib/rancher/k3s/server/manifests/kubernetes-dashboard.yaml
```
########################################################
failed
```
level=fatal msg="failed to get docker runtime info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
```
![image](https://github.com/user-attachments/assets/567db971-2039-49a6-be3f-cf375dda8550)
