### ISSUE TITLE
'kubectl node top' get 'error: Metrics API not available' when metrics-server is allocated on agent node 

### ISSUE THREAD

**Issue by piliplaker** [k3s-io/k3s#10859]
**Environmental Info:**
K3s Version: 
v1.30.4+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux k3s-master 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
Linux k3s-worker1-debian 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64 GNU/Linux
Linux k3s-worker2-debian 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64 GNU/Linux
Linux k3s-worker3-debian 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64 GNU/Linux

Cluster Configuration:
1 server , 3 agents

**Describe the bug:**
When the metric server is assigned to the server node, 'kubectl top node'' can work normally, but when it is assigned to the agent node, an 'error: Metrics API not available' will be reported.

**Steps To Reproduce:**
on server node :
```yaml
token: 123456
node-label:
- "role=normal"
node-name: master-nas
disable:
- servicelb
embedded-registry: true
write-kubeconfig-mode: "0644"
node-taint:
  - k3s-controlplane=true:PreferNoSchedule
```
use `curl -sfL https://get.k3s.io | sh - ` to install

on agent node:
```yaml
token: 123456
node-label:
- "role=normal"
node-name: worker-cube
server: https://192.168.1.116:6443
```
use `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=agent sh - ` to install 

Initially, the metric server was running on the server node. and the cpu and mem indicators can be displayed normally in k9s
and then I use k9s to delete the pod running on server node trying to release some resource on server node, 
then i found that cpu and mem metrics show n/a , I waited for a while till the pod running  and it still looked like this
and then i run 'kubectl top node' get  'error: Metrics API not available'
ant then i delete the pod working on agent node , the new pod was allocated back to the server node, the cpu and mem came back 

**Expected behavior:**
No matter where the metric server is allocated, it should be able to operate normally.

**Actual behavior:**
it is looks like that metrics server only works well on server node, 

**Additional context / logs:**
when the metric server running on agent node 
![1725767308922](https://github.com/user-attachments/assets/422efbe3-364c-4c09-9c7a-62c7fe5eb40b)
![1725767360019](https://github.com/user-attachments/assets/1cd6ead0-fce7-4941-bbc9-f5d5e9314854)
