### ISSUE TITLE
[Release-1.31] - Support for NodeExternalDNS

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#10854]
Backport fix for Support for NodeExternalDNS

* #10848

**Comment by VestigeJ** [comment]
New Feature 


export CONTROL_PLANE_MACHINE_COUNT=1;export WORKER_MACHINE_COUNT=1;export RKE2_VERSION=v1.30.4+rke2r1;export AWS_NODE_MACHINE_TYPE=t2.medium;export AWS_CONTROL_PLANE_MACHINE_TYPE=t2.medium;export AWS_SSH_KEY_NAME="justin-qa-ed";export AWS_AMI_ID="ami-0371c70ae504994fd";export AWS_REGION="us-east-2"



cctl generate cluster --from https://github.com/rancher/cluster-api-provider-rke2/blob/main/samples/aws/cluster-template.yaml -n aws rke2-aws > aws-rke2-clusterctl.yaml






















{"level":"error","ts":"2024-09-12T21:25:10Z","msg":"Reconciler error","controller":"bundledeployment","controllerGroup":"fleet.cattle.io","controllerKind":"BundleDeployment","BundleDeployment":{"name":"fleetsk3s","namespace":"cluster-fleet-local-local-1a3d67d0a899"},"namespace":"cluster-fleet-local-local-1a3d67d0a899","name":"fleetsk3s","reconcileID":"acb45668-d98b-43d3-88e3-d2dab6e6f8b3","error":"failed deploying bundle: unable to build kubernetes objects from release manifest: [resource mapping not found for name: \"ebs-csi-controller\" namespace: \"kube-system\" from \"\": no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"testclusteraws6\" namespace: \"\" from \"\": no matches for kind \"AWSCluster\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"testclusteraws6-control-plane\" namespace: \"\" from \"\": no matches for kind \"AWSMachineTemplate\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"testclusteraws6-md-0\" namespace: \"\" from \"\": no matches for kind \"AWSMachineTemplate\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"${CLUSTER_NAME}\" namespace: \"\" from \"\": no matches for kind \"AWSCluster\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"${CLUSTER_NAME}-control-plane\" namespace: \"\" from \"\": no matches for kind \"AWSMachineTemplate\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"${CLUSTER_NAME}-md-0\" namespace: \"\" from \"\": no matches for kind \"AWSMachineTemplate\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first]","errorCauses":[{"error":"failed deploying bundle: unable to build kubernetes objects from release manifest: [resource mapping not found for name: \"ebs-csi-controller\" namespace: \"kube-system\" from \"\": no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"testclusteraws6\" namespace: \"\" from \"\": no matches for kind \"AWSCluster\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"testclusteraws6-control-plane\" namespace: \"\" from \"\": no matches for kind \"AWSMachineTemplate\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"testclusteraws6-md-0\" namespace: \"\" from \"\": no matches for kind \"AWSMachineTemplate\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"${CLUSTER_NAME}\" namespace: \"\" from \"\": no matches for kind \"AWSCluster\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"${CLUSTER_NAME}-control-plane\" namespace: \"\" from \"\": no matches for kind \"AWSMachineTemplate\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first, resource mapping not found for name: \"${CLUSTER_NAME}-md-0\" namespace: \"\" from \"\": no matches for kind \"AWSMachineTemplate\" in version \"infrastructure.cluster.x-k8s.io/v1beta1\"\nensure CRDs are installed first]"}],"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}







$ kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
```
pod/dnsutils created
```

$ kgp dnsutils
```
NAME       READY   STATUS    RESTARTS   AGE
dnsutils   1/1     Running   0          6s
```

$ k exec -it dnsutils -- nslookup cloudflare.com
```
Server:		10.43.0.10
Address:	10.43.0.10#53

Non-authoritative answer:
Name:	cloudflare.com
Address: 104.16.133.229
Name:	cloudflare.com
Address: 104.16.132.229
Name:	cloudflare.com
Address: 2611111:1111::::
Name:	cloudflare.com
Address: 2611:1111::::
```

$ k exec -it dnsutils -- nslookup -debug cloudflare.com
```
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com.default.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1726525239
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find cloudflare.com.default.svc.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1726525239
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find cloudflare.com.svc.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1726525239
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find cloudflare.com.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com.us-east-2.compute.internal, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  us-east-2.compute.internal
	origin = ns0.us-east-2.compute.internal
	mail addr = hostmaster.amazon.com
	serial = 2012103100
	refresh = 3600
	retry = 3600
	expire = 3600
	minimum = 60
	ttl = 30
    ADDITIONAL RECORDS:
------------
** server can't find cloudflare.com.us-east-2.compute.internal: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com, type = A, class = IN
    ANSWERS:
    ->  cloudflare.com
	internet address = 104.16.132.229
	ttl = 30
    ->  cloudflare.com
	internet address = 104.16.133.229
	ttl = 30
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
Name:	cloudflare.com
Address: 104.16.132.229
Name:	cloudflare.com
Address: 104.16.133.229
------------
    QUESTIONS:
	cloudflare.com, type = AAAA, class = IN
    ANSWERS:
    ->  cloudflare.com
	has AAAA address 2611:1111::::
	ttl = 30
    ->  cloudflare.com
	has AAAA address 2611111:1111::::
	ttl = 30
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Name:	cloudflare.com
Address: 2611:1111::::
Name:	cloudflare.com
Address: 2611111:1111::::
```

$ kgn -o yaml
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      alpha.kubernetes.io/provided-node-ip: 1.1.1.14,110:1111:1131:1101:119b:311:1191:1117
      etcd.k3s.cattle.io/local-snapshots-timestamp: "2024-09-16T22:20:09Z"
      etcd.k3s.cattle.io/node-address: 1.1.1.14
      etcd.k3s.cattle.io/node-name: ip-ip-8ead0505
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"ea:3b:e6:61:1a:94"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 172.31.11.144
      k3s.io/external-ip: 1.2.3.4
      k3s.io/hostname: ip-ip
      k3s.io/internal-ip: 1.1.1.14,110:1111:1131:1101:119b:311:1191:1117
      k3s.io/node-args: '["server","--node-external-ip","1.2.3.4","--node-external-dns","cloudflare.com","--node-external-dns","arc.k3s.com","--token","********","--write-kubeconfig-mode","644","--debug","true","--cluster-init","true","--embedded-registry","true"]'
      k3s.io/node-config-hash: 61111117Y565JXGI11111111111111111CWHBQ====
      k3s.io/node-env: '{}'
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
```

**Comment by VestigeJ** [comment]
##Environment Details
Validated using COMMIT=f7b482642a73ac485e91961ecb44ca48a0fbbc93

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

Linux 6.4.0-150600.23.17-default x86_64 GNU/Linux
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP6"

*Cluster Configuration:*

```
NAME             STATUS   ROLES                       AGE     VERSION
ip-1-1-1-3       Ready    control-plane,etcd,master   8m23s   v1.31.1+k3s-f7b48264
```

*Config.yaml:*

```
node-external-ip: 1.1.1.3
token: YOUR_TOKEN_HERE
write-kubeconfig-mode: 644
debug: true
cluster-init: true
node-external-dns:
- cloudflare.com
- google.com
- arc.k3s.com
```

<details><summmary><h4>Reproduction</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ COMMIT=f7b482642a73ac485e91961ecb44ca48a0fbbc93
$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=server ./install-k3s.sh
$ k apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
$ kgp dnsutils
$ kgn -o yaml | grep -i dns
$ k3s -v
$ k exec -it dnsutils -- nslookup -debug cloudflare.com > cloudflare
$ k exec -it dnsutils -- nslookup -debug google.com > google
$ k exec -it dnsutils -- nslookup -debug arc.k3s.com > arc
```

**Results:**

$ kgn -o yaml | grep -i dns
```
      k3s.io/node-args: '["server","--node-external-ip","3.3.3.7","--token","********","--write-kubeconfig-mode","644","--debug","true","--cluster-init","true","--node-external-dns","cloudflare.com","--node-external-dns","google.com","--node-external-dns","arc.k3s.com"]'
```

$ k3s -v
```
k3s version v1.31.1+k3s-f7b48264 (f7b48264)
go version go1.22.6
```


cloudflare

```
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com.default.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1728333368
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find cloudflare.com.default.svc.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1728333368
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find cloudflare.com.svc.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1728333368
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find cloudflare.com.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com.us-east-2.compute.internal, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  us-north-9.compute.internal
	origin = ns0.us-north-9.compute.internal
	mail addr = hostmaster.amazon.com
	serial = 2024103100
	refresh = 3600
	retry = 3600
	expire = 3600
	minimum = 60
	ttl = 18
    ADDITIONAL RECORDS:
------------
** server can't find cloudflare.com.us-north-9.compute.internal: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	cloudflare.com, type = A, class = IN
    ANSWERS:
    ->  cloudflare.com
	internet address = 104.16.133.229
	ttl = 8
    ->  cloudflare.com
	internet address = 104.16.132.229
	ttl = 8
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Name:	cloudflare.com
Address: 104.16.133.229
Name:	cloudflare.com
Address: 104.16.132.229
------------
    QUESTIONS:
	cloudflare.com, type = AAAA, class = IN
    ANSWERS:
    ->  cloudflare.com
	has AAAA address 2606:4700::6810:85e5
	ttl = 8
    ->  cloudflare.com
	has AAAA address 2606:4700::6810:84e5
	ttl = 8
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Name:	cloudflare.com
Address: 2606:4700::6810:85e5
Name:	cloudflare.com
Address: 2606:4700::6810:84e5

```

google
```
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	google.com.default.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1728333368
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find google.com.default.svc.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	google.com.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1728333368
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find google.com.svc.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	google.com.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1728333368
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find google.com.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	google.com.us-north-9.compute.internal, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  us-north-9.compute.internal
	origin = ns0.us-north-9.compute.internal
	mail addr = hostmaster.amazon.com
	serial = 20345103100
	refresh = 3600
	retry = 3600
	expire = 3600
	minimum = 60
	ttl = 22
    ADDITIONAL RECORDS:
------------
** server can't find google.com.us-north-9.compute.internal: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	google.com, type = A, class = IN
    ANSWERS:
    ->  google.com
	internet address = 142.250.191.206
	ttl = 22
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Name:	google.com
Address: 142.250.191.206
------------
    QUESTIONS:
	google.com, type = AAAA, class = IN
    ANSWERS:
    ->  google.com
	has AAAA address 2607:f8b0:4009:809::200e
	ttl = 22
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Name:	google.com
Address: 2607:f8b0:4009:809::200e

```

arc
```
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	arc.k3s.com.default.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1728333368
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find arc.k3s.com.default.svc.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	arc.k3s.com.svc.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 1728333368
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find arc.k3s.com.svc.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	arc.k3s.com.cluster.local, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  cluster.local
	origin = ns.dns.cluster.local
	mail addr = hostmaster.cluster.local
	serial = 179993368
	refresh = 7200
	retry = 1800
	expire = 86400
	minimum = 5
	ttl = 5
    ADDITIONAL RECORDS:
------------
** server can't find arc.k3s.com.cluster.local: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	arc.k3s.com.us-north-9.compute.internal, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  us-north-9.compute.internal
	origin = ns0.us-north-9.compute.internal
	mail addr = hostmaster.amazon.com
	serial = 2012103100
	refresh = 3600
	retry = 3600
	expire = 3600
	minimum = 60
	ttl = 30
    ADDITIONAL RECORDS:
------------
** server can't find arc.k3s.com.us-north-9.compute.internal: NXDOMAIN
Server:		10.43.0.10
Address:	10.43.0.10#53

------------
    QUESTIONS:
	arc.k3s.com, type = A, class = IN
    ANSWERS:
    ->  arc.k3s.com
	internet address = 1.1.1.13
	ttl = 30
    ->  arc.k3s.com
	internet address = 1.1.1.3
	ttl = 30
    ->  arc.k3s.com
	internet address = 1.1.1.3
	ttl = 30
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
Name:	arc.k3s.com
Address: 1.1.1.13
Name:	arc.k3s.com
Address: 1.1.1.3
Name:	arc.k3s.com
Address: 1.1.1.3
------------
    QUESTIONS:
	arc.k3s.com, type = AAAA, class = IN
    ANSWERS:
    ->  arc.k3s.com
	has AAAA address cafe:4700:20::arce:526
	ttl = 30
    ->  arc.k3s.com
	has AAAA address cafe:4700:20::arce:426
	ttl = 30
    ->  arc.k3s.com
	has AAAA address cafe:4700:20::arce:480d
	ttl = 30
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Name:	arc.k3s.com
Address: cafe:4700:20::arce:526
Name:	arc.k3s.com
Address: cafe:4700:20::arce:426
Name:	arc.k3s.com
Address: cafe:4700:20::arce:480d

```


</details>

**Comment by VestigeJ** [comment]
Previous release node configuration behavior 

$ kgn -o yaml | grep -i dns -B1 -A3
```
      k3s.io/internal-ip: 1.1.1.14
      k3s.io/node-args: '["server","--token","********","--write-kubeconfig-mode","644","--debug","true","--cluster-init","true","--embedded-registry","true","--node-external-dns","cloudflare.com","--node-external-dns","google.com","--node-external-dns","arc.k3s.com","--node-internal-dns","k3s.server.qa"]'
      k3s.io/node-config-hash: IG22GUHALZPSO6THTTTHA====
      k3s.io/node-env: '{}'
      node.alpha.kubernetes.io/ttl: "0"
--
    - names:
      - docker.io/rancher/mirrored-coredns-coredns@sha256:8461f69c1d8252a73f4c217ca17c75ac704af1c54c2332c199c637ab2815536a
      - docker.io/rancher/mirrored-coredns-coredns:1.11.3
      sizeBytes: 18561302
    - names:
      - docker.io/rancher/local-path-provisioner@sha256:f77fa34dd9d000daf6fd6029bf05de6b351b4fe4287cbc0ad2abb11a91df2ced
```

$ get_figs
```
=========== k3s config ===========
token: YOUR_TOKEN_HERE
write-kubeconfig-mode: 644
debug: true
cluster-init: true
embedded-registry: true
node-external-dns:
- cloudflare.com
- google.com
- arc.k3s.com
node-internal-dns:
- k3s.server.qa
```

$ k3s -v
```
k3s version v1.31.1+k3s1 (452dbbc1)
go version go1.22.6
```

Validated no configuration changed to reflect same configuration values

$ kgn -o yaml | grep -i dns -B1 -A3
```
DEBU[0000] Asset dir /var/lib/rancher/k3s/data/c5bb48fbd7c6f4f16681f98f7b9abffc97b8d04ea73b768df78ea17e7e31809f
DEBU[0000] Running /var/lib/rancher/k3s/data/c5bb48fbd7c6f4f16681f98f7b9abffc97b8d04ea73b768df78ea17e7e31809f/bin/kubectl [kubectl get nodes -o yaml]
      flannel.alpha.coreos.com/public-ip: 1.1.1.114
      k3s.io/external-dns: cloudflare.com,google.com,arc.k3s.com
      k3s.io/hostname: ip-1-1-1-114
      k3s.io/internal-dns: k3s.server.qa
      k3s.io/internal-ip: 1.1.1.114
      k3s.io/node-args: '["server","--token","********","--write-kubeconfig-mode","644","--debug","true","--cluster-init","true","--embedded-registry","true","--node-external-dns","cloudflare.com","--node-external-dns","google.com","--node-external-dns","arc.k3s.com","--node-internal-dns","k3s.server.qa"]'
      k3s.io/node-config-hash: IG2UHKBBQ7222X====
      k3s.io/node-env: '{}'
      node.alpha.kubernetes.io/ttl: "0"
--
    - address: k3s.server.qa
      type: InternalDNS
    - address: cloudflare.com
      type: ExternalDNS
    - address: google.com
      type: ExternalDNS
    - address: arc.k3s.com
      type: ExternalDNS
    - address: ip-1-1-1-114
      type: Hostname
    allocatable:
--
    - names:
      - docker.io/rancher/mirrored-coredns-coredns@sha256:82979ddf442c593027a57239ad90616deb874e90c365d1a96ad508c2104bdea5
      - docker.io/rancher/mirrored-coredns-coredns:1.12.0
      sizeBytes: 20938299
    - names:
      - docker.io/rancher/mirrored-metrics-server@sha256:dccf8474fb910fef261d31d9483d7e4c1df7b86cf4d638fb6a7d7c88bd51600a
```

$ get_figs
```
=========== k3s config ===========
token: YOUR_TOKEN_HERE
write-kubeconfig-mode: 644
debug: true
cluster-init: true
embedded-registry: true
node-external-dns:
- cloudflare.com
- google.com
- arc.k3s.com
node-internal-dns:
- k3s.server.qa
```

$ k3s -v
```
k3s version v1.31.4-rc1+k3s1 (a562d090)
go version go1.22.9
```
