### ISSUE TITLE
k3s + traefik， how to custom define externalTrafficPolicy = Local

### ISSUE THREAD

**Issue by bxter** [k3s-io/k3s#10875]
in the document, I found the custom define method
<img width="1014" alt="image" src="https://github.com/user-attachments/assets/fcecc9d0-e8d5-47fc-8a30-afd003d9c801">

I want change the externalTrafficPolicy using follow
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      externalTrafficPolicy: Local
    ports:
      web:
        proxyProtocol:
          trustedIPs:
            - "0.0.0.0/0"
```

But this is uneffected, how can it work, thanks

**Comment by brandond** [comment]
It does not appear that the traefik helm chart supports this:
https://github.com/traefik/traefik-helm-chart/blob/v25.0.0/traefik/templates/_service.tpl

Feel free to open an issue at https://github.com/traefik/traefik-helm-chart/

**Comment by Smartich0ke** [comment]
> It does not appear that the traefik helm chart supports this: https://github.com/traefik/traefik-helm-chart/blob/v25.0.0/traefik/templates/_service.tpl
> 
> Feel free to open an issue at https://github.com/traefik/traefik-helm-chart/
> ### edit
> 
> I take that back, it looks like you should be able do that via `service.spec`: https://github.com/traefik/traefik-helm-chart/blob/v25.0.0/traefik/templates/_service.tpl#L15
> 
> ```yaml
> spec:
>   valuesContent: |-
>     service:
>       spec:
>         externalTrafficPolicy: Local
> ```

I have tried this but it still has no effect:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      kind: DaemonSet
    service:
      spec:
        externalTrafficPolicy: Local
```
