### ISSUE TITLE
Support Traefik 3.1.0

### ISSUE THREAD

**Issue by SIMULATAN** [k3s-io/k3s#10934]
**Is your feature request related to a problem? Please describe.**
Upgrading Traefik from `3.0.x` to `3.1.x` causes the ingress controller to seize to function entirely. Traefik cannot start up due to missing permissions to access `nodes` and `endpointslices`.

**Describe the solution you'd like**
If the Traefik image version (`image.tag`) is greater than or equal to `3.1.0`, add the required permissions to the [helm chart ClusterRole](https://github.com/k3s-io/k3s-charts/blob/47e7316c29d1b4c2f24f84b3443f63da1fcdf8c6/charts/traefik/25.0.3%2Bup25.0.0/templates/rbac/clusterrole.yaml).
```yml
- apiGroups:
    - discovery.k8s.io
  resources:
    - endpointslices
  verbs:
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - watch
```

**Describe alternatives you've considered**
Manually patching the ClusterRole for now.
Will come up during the implementation of #10526 
I wouldn't consider this a duplicate though, as 3.x is supported in theory and the linked issue is meerly to upgrade the default.

**Additional context**
https://doc.traefik.io/traefik/v3.1/migration/v3/#kubernetes-provider-rbacs

**Suggested action**
I'd happily implement this myself and open a PR against the [k3s-io/k3s-charts](https://github.com/k3s-io/k3s-charts) repo. However, I'm unsure if I have to copy-paste the latest version chart folder ([charts/traefik/25.0.3+up25.0.0](https://github.com/k3s-io/k3s-charts/tree/main/charts/traefik/25.0.3%2Bup25.0.0)) or can make the changes in the existing one.
