### ISSUE TITLE
80 port is not used, but lb stay pending 

### ISSUE THREAD

**Issue by Jamlee** [k3s-io/k3s#1107]
**Version:**
k3s version v1.0.0-rc5 (99b8222e)

**Describe the bug**
the port 80 is not used, but lb is stay pending.
![image](https://user-images.githubusercontent.com/5196641/69220745-a6465c00-0bb0-11ea-9f02-a81c834a0d7b.png)
![image](https://user-images.githubusercontent.com/5196641/69220805-c0803a00-0bb0-11ea-9acc-013b506892cf.png)
![image](https://user-images.githubusercontent.com/5196641/69220834-d2fa7380-0bb0-11ea-9a28-5723d9205de0.png)

**To Reproduce**
https://github.com/dapr/samples/tree/master/2.hello-kubernetes

```
kind: Service
apiVersion: v1
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
```
