### ISSUE TITLE
traefik v2.11.2 changes readTimeout and requires helm chart v28.0.0+ to configure

### ISSUE THREAD

**Issue by vihangm** [k3s-io/k3s#11107]
**Is your feature request related to a problem? Please describe.**
My k3s cluster recently upgraded and thus the app version of traefik changed from v2.10.7 to v2.11.8 see [commit](https://github.com/k3s-io/k3s/commit/bd45aa5c45977725e58840bd81fea2d41b4c176a)

In v2.11.2 traefik changed the default readTimeout from 0s (no timeout) to 60s. https://doc.traefik.io/traefik/migration/v2/#entrypointtransportrespondingtimeoutsreadtimeout

This causes some of my requests to the cluster to fail.

This is configurable via the traefik helm chart, see [commit](https://github.com/traefik/traefik-helm-chart/commit/47e0f28a7413def68a48489140db521e99617187) however this is only available in chart versions v28.0.0 and higher.

**Describe the solution you'd like**
Upgrade the traefik helm chart to v28.0.0 or higher so that the timeout can be configured.

**Describe alternatives you've considered**
I can manually pin my traefik app version to the older version to restore behavior, but ideally we can use the newer version so that bug fixes and security patches are pulled in.

**Comment by brandond** [comment]
You can add CLI flags via any version of the chart... just do this:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.transport.respondingTimeouts.readTimeout=120s"
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=120s"
```
