### ISSUE TITLE
Allow setting containerd device_ownership_from_security_context from config

### ISSUE THREAD

**Issue by nick123pig** [k3s-io/k3s#11168]
**Is your feature request related to a problem? Please describe.**
Yes - I was trying to set the containerd config item `device_ownership_from_security_context = true` per the instructions [here](https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/#see-non-root-containers-using-devices-after-the-fix). 

I was attempting to use the `config.toml.tmpl` strategy by extended the base and just adding my one config item, but unfortunately you can't redefine a table, so i kept getting `containerd: failed to load TOML: /var/lib/rancher/k3s/agent/etc/containerd/config.toml: (47, 4): duplicated tables` 

I had to settle by copying the entire config.toml to the config.toml.tmpl and then adding my one line. However, this will make upgrades a pain as I will have to re-sync the base.tmpl

**Describe the solution you'd like**
A lot of this section is [already templated](https://github.com/k3s-io/k3s/blob/master/pkg/agent/templates/templates_linux.go#L20) from config, so I would suggest adding it as a config item.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by brandond** [comment]
If it was not for the security considerations I would lean towards just enabling this by default. Since it is security related I think it probably deserves a CLI flag, but the field in the config is so ungodly long... I sure don't want a k3s flag named `--containerd-device-ownership-from-security-context`.

Open to suggestions, I guess?

**Comment by brandond** [comment]
Yeah something like`--nonroot-devices`? I'll discuss it with the team.

**Comment by VestigeJ** [comment]
Existing releases config.toml emitted file on startup for comparison against this new feature.
$ k3s -v
```
k3s version v1.31.2+k3s1 (6da20424)
go version go1.22.8
```
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml
```
# File generated by k3s. DO NOT EDIT. Use config.toml.tmpl instead.
version = 2
[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/k3s/agent/containerd"
[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true
  sandbox_image = "rancher/mirrored-pause:3.6"
[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true
  
[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/var/lib/rancher/k3s/data/cni"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = true
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/var/lib/rancher/k3s/agent/etc/containerd/certs.d"
```
New COMMIT_ID build tested config.toml attention to "device_ownership_from_security_context = true"
```
$ COMMIT=c946875f318ac49a407c71a7bad961705538e4e9
$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC="server --nonroot-devices" ./install-k3s.sh 
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml
```
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml
```
# File generated by k3s. DO NOT EDIT. Use config.toml.tmpl instead.
version = 2
[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/k3s/agent/containerd"
[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true
  device_ownership_from_security_context = true
  sandbox_image = "rancher/mirrored-pause:3.6"
[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true
  
[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/var/lib/rancher/k3s/data/cni"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = true
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/var/lib/rancher/k3s/agent/etc/containerd/certs.d"
```

I have no name!@dnsutils:/$ id
```
uid=1000 gid=2000 groups=2000,3000
```

I have no name!@dnsutils:/$ ls -lahr /tested
```
total 0
drwxr-xr-x 1 root root 42 Nov 12 21:45 ..
drwxrwsrwx 2 root 3000  6 Nov 12 21:45 .
```


$ cat hugepages.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: testpod-hugepage
spec:
  containers:
  - name: dpdk-test
    image: debian
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
      readOnly: False
    resources:
      requests:
        memory: "512Mi"
        hugepages-2Mi: "512Mi"
      limits:
        memory: "512Mi"
        hugepages-2Mi: "512Mi"
      runAsUser: 0
      privileged: false
  volumes:
  - name: hugepage
    hostPath:
      path: /dev/hugepages
      type: Directory
```

$ cat vdevs.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing-devices
  namespace: default
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: testing-devices
  volumeMode: Block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testing-devices
spec:
  local:
    path: /tmp/shutthefs
  storageClassName: ""
  volumeMode: Block
  claimRef:
    name: testing-devices
    namespace: default
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["NODE_NAME_HERE"]
---
kind: Pod
apiVersion: v1
metadata:
  name: dnsutils
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  containers:
  - name: dnsutils
    image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
    volumeMounts:
    - mountPath: /tested
      name: testing-devices
    command:
      - sleep
      - "3600"
    resources:
      requests:
        cpu: "1"
        memory: "128Mi"
        hugepages-2Mi: "128Mi"
      limits:
        cpu: "1"
        memory: "128Mi"
        hugepages-2Mi: "128Mi"
  volumes:
    - name: testing-devices
```

$ k exec -it dnsutils -- ls -l /dev/fd/
```
total 0
lrwx------    1 1000     2000            64 Nov  7 23:53 0 -> /dev/pts/0
lrwx------    1 1000     2000            64 Nov  7 23:53 1 -> /dev/pts/0
lrwx------    1 1000     2000            64 Nov  7 23:53 2 -> /dev/pts/0
lr-x------    1 1000     2000            64 Nov  7 23:53 3
```
