### ISSUE TITLE
K3s server/agent in docker compose fails starting up in 1.31.1 (works in previous release)

### ISSUE THREAD

**Issue by krisgeus** [k3s-io/k3s#11165]
**Environmental Info:**
K3S Version: 1.31.1+k3s1

Cluster Configuration:
1 server, 1 agent in docker compose

**Describe the bug:**
K3S server keeps failing to boot and restarts when bumping version from 1.30.1+k3s1 to 1.31.1+k3s1

**Steps To Reproduce:**
export K3S_VERSION=v1.31.1-k3s1
docker compose up

with the following compose.yaml file
```
services:

  k3stestserver.local:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command:
    - server
    - "--tls-san"
    - "k3stestserver.local"
    - "--bind-address"
    - "k3stestserver.local"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=26576147927211
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    - K3S_NODE_NAME=k3stestserver.local
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .k3s:/output
    ports:
    - 6443:6443  # Kubernetes API Server
    - 80:80      # Ingress controller port 80
    - 443:443    # Ingress controller port 443

  k3stestagent.local:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://k3stestserver.local:6443
    - K3S_TOKEN=26576147927211
    - K3S_NODE_NAME=k3stestagent.local
    volumes:
    - k3s-agent:/var/lib/rancher/k3s

volumes:
  k3s-server: {}
  k3s-agent: {}

```

**Expected behavior:**
`kubectl --kubeconfig .k3s/kubeconfig.yaml get nodes` should return 2 healthy nodes

**Actual behavior:**
E1024 12:29:49.719871   39506 memcache.go:265] couldn't get current server API group list: Get "https://k3stestserver.local:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
E1024 12:29:54.724324   39506 memcache.go:265] couldn't get current server API group list: Get "https://k3stestserver.local:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused

**Additional context / logs:**

Added good and bad log file (good is form version 1.30.1+k3s1, bad is fo r1.31.1+k3s1

[bad-log.txt](https://github.com/user-attachments/files/17505936/bad-log.txt)
[good-log.txt](https://github.com/user-attachments/files/17505937/good-log.txt)
