### ISSUE TITLE
Kube scheduler config not recognized

### ISSUE THREAD

**Issue by didlawowo** [k3s-io/k3s#11179]
i'm trying to setup kubescheduler inside my k3S cluster

**Environmental Info:**
K3s Version: 1.30

Node(s) CPU architecture, OS, and Version: 
three arm64 node, and 2 amd64 node

Cluster Configuration:
 "3 servers, 2 agents"

**Describe the bug:**
i want to apply a kube scheduler config but crd not exist:
```
# scheduler-config.yaml
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
metadata:
  name: custom-scheduler-config
profiles:
- schedulerName: default-scheduler
  plugins:
    score:
      disabled:
      - name: NodeResourcesBalancedAllocation
      - name: NodeResourcesFit
      enabled:
      - name: NodePreferAvoid
        weight: 100
  pluginConfig:
  - name: NodePreferAvoid
    args:
      scoreStrategy:
        type: MostAllocated
        resources:
        - name: cpu
          weight: 1
        - name: memory
          weight: 1
      preferredNodes:
      - nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - ryzen
      avoidNodes:
      - nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - rtx

---
# Apply this to your kube-scheduler configuration in /etc/kubernetes/manifests/kube-scheduler.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - name: kube-scheduler
    image: k8s.gcr.io/kube-scheduler:v1.30.0 # Use your cluster's version
    command:
    - kube-scheduler
    - --config=/etc/kubernetes/scheduler-config.yaml # Point to your config
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler-config.yaml
      name: scheduler-config
      readOnly: true
  volumes:
  - name: scheduler-config
    hostPath:
      path: /etc/kubernetes/scheduler-config.yaml
      type: File

```
**Steps To Reproduce:**
apply this config

 

**Expected behavior:**
existing crd

**Actual behavior:**
not exist

**Additional context / logs:**
```
The Kubernetes API could not find kubescheduler.config.k8s.io/KubeSchedulerConfiguration for requested resource kube-infra/custom-scheduler-config. Make sure the "KubeSchedulerConfiguration" CRD is installed on the destination cluster.
```
