### ISSUE TITLE
Traefik 2.0 integration

### ISSUE THREAD

**Issue by Zikoel** [k3s-io/k3s#1141]
**Is your feature request related to a problem? Please describe.**
The feature tls-passthrough is missing.
Es. Installing argocd on the cluster is difficult due the missing of this feature.

**Describe the solution you'd like**
Substitute the actual version < 2.0 with the actual (that reach the GA with version 2.0)

**Describe alternatives you've considered**
Describe a reproducible way for remove the actual version in favor of the most updated version.

**Additional context**
The version of Traefik 2.0 seems most kubernetes friendly so, this seems to me a very natural step to do!

**Comment by sebastien-prudhomme** [comment]
It seems that Traefik 2.0 drops Ingress support and so drops compatibility with most of the community Helm charts.

So i don't think it's a good idea if it's really the case, even if Ingress has some limitations.

**Comment by Zikoel** [comment]
From the documentation [Traefik & Kubernetes](https://docs.traefik.io/providers/kubernetes-ingress/) seems that the **Ingress** support is not dropped but fully supported, more of this there is another custom Ingress the with enhanced capabilities for complex routes and middlewares!

**Comment by sebastien-prudhomme** [comment]
Thanks for reading the full doc! It was not clear as also talk on migrating to their new CRD.

As k3s is using a chart to deploy Traefik, i guess we need to wait for the new version of the chart which is still not ready for production: https://github.com/containous/traefik/issues/5440

**Comment by denysvitali** [comment]
I'm using this and it works pretty well once you disable the original traefik:
```
write_files:
- encoding: ""
  content: |-
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: traefik
      namespace: kube-system
    spec:
      chart: traefik
      repo: https://nanosapp.github.io/chart-releases/stable
      targetNamespace: kube-system
      set:
        image.tag: 2.0.4
        ports.web.port: 80
        ports.websecure.port: 443
  owner: root
  path: /var/lib/rancher/k3s/server/manifests/traefik.yaml
  permissions: '0600'
```

```
k3os:
  dns_nameservers:
    - 1.1.1.1
    - 8.8.8.8
  labels:
    region: uk1
  k3s_args:
    - server
    - "--no-deploy=traefik"
```

**Comment by sotiris84** [comment]
Looking forward as well the update to Traefik 2.0

**Comment by brandond** [comment]
@denysvitali that repo appears to be gone; do you have a substitute that you're still using?

**Comment by denysvitali** [comment]
@brandond Nope, that repo should still work, look at https://github.com/nanosapp/chart-releases/tree/gh-pages/stable/traefik and you'll see the chart source. I've created that repo and the company I work for owns it 👍

**Comment by brandond** [comment]
I'll give it another try. I'll admit to not actually loading the chart, I just hit the repo with my browser and got a 404.

**Comment by denysvitali** [comment]
That's just because Chart repos do not need an index.html. If you visit the repo + '/index.yaml'

**Comment by mickkael** [comment]
The Helm chart is now production ready
https://github.com/containous/traefik-helm-chart/pull/104

https://github.com/containous/traefik-helm-chart/blob/master/traefik/Chart.yaml

**Comment by r1cebank** [comment]
Been trying to get the Helm chart to work, but had not a lot of luck, followed the documentation on Traefik's website and got it working with k3s. The ansible role is here https://github.com/r1cebank/geck/tree/traefik-v2/roles/traefik

**Comment by mamiu** [comment]
@r1cebank 
Create a yaml file with following content:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik
  repo: https://containous.github.io/traefik-helm-chart
  set:
    image.tag: "2.2"
```

Then place this file in `/var/lib/rancher/k3s/server/manifests` and install or run the k3s server with `--no-deploy traefik`.

**Comment by torpinouche** [comment]
I am not sure no-deply is the right one, it is listed as deprecated in the documentation [here](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/)

`--disable value` sounds the option you should use.

**Comment by mamiu** [comment]
@torpinouche You're absolutely right! Thanks, I've adapted my comment.

**Comment by FlomoN** [comment]
@mamiu applying that yaml started all the proper traefik pods and deployments, but none of my IngressRoutes seem to work. I deployed the IngressRoute for ArgoCD https://argoproj.github.io/argo-cd/operator-manual/ingress/, but all I get is the default 404 page of Traefik.

**Comment by SayakMukhopadhyay** [comment]
Hi,
I see that this issue has been added to the 1.20 backlog, does that mean that Traefik 2.0 integration is only coming with kubernetes 1.20 and wont be there in 1.18.x and 1.19.x?

**Comment by notsureifkevin** [comment]
o/ greetings from Containous. If you need any assistance with the transition to v2 of Traefik please don't hesitate to reach out to myself or anyone on the team. cc @SantoDE

**Comment by kbrowder** [comment]
@notsureifkevin fwict values content is pretty different in the contanious chart, specifically values that go into the toml in the traefik v1 chart aren't there (basically you need to bring your own toml).  Am I understanding that right?

**Comment by notsureifkevin** [comment]
@kbrowder I believe your observation is correct, we are working to abstract some of these use cases into more helm-friendly `values.yml` approach, but for the purpose of k3s, either providing a toml or specifying the command line arguments through https://github.com/containous/traefik-helm-chart/blob/master/traefik/values.yaml#L118-L129 may be the best approach at the moment. cc @SantoDE

**Comment by Thalooka** [comment]
would love to see this coming sooner since traefik 2.0 is released since over a year now

**Comment by samirsss** [comment]
Bump on this one. We've run into an issue with the current installation of k3s (bundled traefik helm chart 1.81.0), only allows single external IP. The newer versions of Traefik charts support externalIPs as an array.

**Comment by SantoDE** [comment]
If you wanna tackle that @samirsss, I guess feel free.

We are happy to help :)

**Comment by mamiu** [comment]
We use Traefik 2.3 on a k3s multi node cluster in production for a few weeks now and it's working without any issues so far.

Fist I installed the k3s cluster with the `--disable=traefik` option. Here's a simplified version of our install command:

```bash
curl -sfL https://get.k3s.io | bash -s - \
  --write-kubeconfig-mode "0644" \
  --disable=traefik
```

Then I apply a file called `traefik2.yaml` (for whatever reason `traefik.yaml` didn't work - maybe because we disabled it in the first step and then k3s automatically removes `traefik.yaml` files or so). We use Traefik also for the automated certificate handling process but if you want to use other solutions like the [cert-manager](https://cert-manager.io/) just delete all the certificate related lines. Since we have our domains on [OVH](https://www.ovh.com/) the following example has `ovh` as a dns challange provider, but of course you can use one of all the [other providers](https://doc.traefik.io/traefik/https/acme/#providers).

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
  namespace: traefik
type: Opaque
data:
  OVH_APPLICATION_KEY: PoBhNa...     # the base64 encoded application key
  OVH_APPLICATION_SECRET: ReFGac...  # the base64 encoded application secret
  OVH_CONSUMER_KEY: YlaEW...         # the base64 encoded consumer key
  OVH_ENDPOINT: b3ZoLWV1

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://containous.github.io/traefik-helm-chart
  chart: traefik
  bootstrap: true
  targetNamespace: traefik
  valuesContent: |-

    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=your.email@mail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      # Let's Encrypt staging API:
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # Let's Encrypt production API:
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.dnschallenge.provider=ovh"

      # If you want to use jaeger tracing for traefik uncomment these lines and adjust them to your jaeger installation
      # - "--tracing=true"
      # - "--tracing.serviceName=traefik"
      # - "--tracing.jaeger=true"
      # - "--tracing.jaeger.propagation=jaeger"
      # - "--tracing.jaeger.traceContextHeaderName=uber-trace-id"
      # - "--tracing.jaeger.samplingServerURL=http://jaeger-agent.jaeger.svc.cluster.local:5778/sampling"
      # - "--tracing.jaeger.localAgentHostPort=jaeger-agent.jaeger.svc.cluster.local:6831"
      # - "--tracing.jaeger.collector.endpoint=http://jaeger-collector.jaeger.svc.cluster.local:14268/api/traces?format=jaeger.thrift"

      # If you want to use prometheus monitoring for traefik uncomment these lines
      # - "--metrics=true"
      # - "--metrics.prometheus=true"
      # - "--metrics.prometheus.addServicesLabels=true"

      - "--accesslog=true"
      - "--log.level=INFO"

    persistence:
      enabled: true
      path: /data

    podAnnotations: 
      prometheus.io/port: '8082'
      prometheus.io/scrape: 'true'

    # We will apply our own ingress rule for the dashboard in the next step
    ingressRoute:
      dashboard:
        enabled: false

    envFrom:
      - secretRef:
          name: ovh-credentials
```

If you don't want to use Traefiks dashboard just ignore the next step.
Otherwise make sure that the Traefik installation is done and was successful. As soon as that's the case apply a file with the following content (adjusted to your needs):

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: admin-dashboard-auth
  namespace: traefik
data:
  # This is the base64 and openssl encoded version of "user" as user and "password" as password
  users: dXNlcjokYXByMSRxWVFuaS9FZSRqRHNNN3pnb1RoL01QeHJZTjlxVlEvCg==

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-auth
  namespace: traefik
spec:
  basicAuth:
    secret: admin-dashboard-auth

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.example.com`)
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: admin-auth
  tls:
    certResolver: letsencrypt
    domains:
      - main: "*.example.com"
```

Now Traefik 2.3 is installed in a k3s cluster with a dashboard reachable on *traefik.example.com*. If it doesn't work as expected please let me know because this is a highly simplified version of the one we're using and maybe I deleted something essential.
