### ISSUE TITLE
`rancher/k3s:v1.31.3-k3s1`  messing with network device permissions

### ISSUE THREAD

**Issue by robjackstewart** [k3s-io/k3s#11429]
**Environmental Info:**
K3s Version: 
`1.31.3-k3s1`

Node(s) CPU architecture, OS, and Version: 
`Linux k3d-home-media-server-server-0 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 GNU/Linux`

Cluster Configuration:
``` yaml
# k3d-config.yaml
apiVersion: k3d.io/v1alpha5
kind: Simple 
metadata:
  name: k3s-1.31.3-test
servers: 1
agents: 0
image: rancher/k3s:v1.31.2-k3s1 # changing to rancher/k3s:v1.31.3-k3s1 causes aforementioned error
network: test-network
```

**Describe the bug:**
Upgrading the rancher image from ` rancher/k3s:v1.31.2-k3s1` to `rancher/k3s:v1.31.3-k3s1` causes permissions errors when accessing `/dev/net/tun` inside the `gluetun` container.

Please find the file structure and contents as follows.

File structure:
``` yaml
- k3d-config.broken.yaml
- k3d-config.working.yaml
- templates/
  - gluetun.yaml
- Chart.yaml
```

File contents:
``` yaml
# k3d-config.broken.yaml
apiVersion: k3d.io/v1alpha5
kind: Simple 
metadata:
  name: k3s-1.31.3-broken
servers: 1
agents: 0
image: rancher/k3s:v1.31.3-k3s1
network: test-network
```

``` yaml
# k3d-config.working.yaml
apiVersion: k3d.io/v1alpha5
kind: Simple 
metadata:
  name: k3s-1.31.3-working
servers: 1
agents: 0
image: rancher/k3s:v1.31.2-k3s1
network: test-network
```

``` yaml
# Chart.yaml
apiVersion: v2
name: k3s-1.31.3-test
version: 0.0.1
appVersion: v0.0.1
```

``` yaml
# templates/gluetun.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gluetun
spec:
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: mullvad
            - name: VPN_TYPE
              value: openvpn
            - name: OPENVPN_USER
              value: # redacted
            - name: OPENVPN_PASSWORD
              value: m
            - name: SERVER_COUNTRIES
              value: UK
            - name: OWNED_ONLY
              value: 'yes'
```

**Steps To Reproduce:**
1. Clone [this repo](https://github.com/robjackstewart/k3s-1.31.3-gluetun-test) for reproduction
1. Populate appropriate `mullvad` username as the value of the `OPENVPN_USER` environment variable in `templates/gluetun.yaml`
1. Run `k3d cluster create --config k3d-config.working.yaml`
1. Run `helm upgrade --install k3s-1.31.3-test .`
1. Wait for the `glueton-0` pod to `Running`
1. Run `kubectl logs gluetun-0` and note successfully running
1. Run `k3d cluster create --config k3d-config.broken.yaml`
1. Run `helm upgrade --install k3s-1.31.3-test .`
1. Wait for the `glueton-0` pod to `Error`
1. Run `kubectl logs gluetun-0` and note permission denied error for `/dev/net/tun`

**Expected behavior:**
The `/dev/net/tun` file should be accessible as it was in `v1.31.2-k3s1`.

**Actual behavior:**
Getting the a permission denied error inside the gluetun container when attempting to open the `/dev/net/tun` device.

**Additional context / logs:**

Error from inside gluetun container when using `v1.31.3-k3s1`
``` text
2024-12-08T12:51:29Z INFO [routing] default route found: interface eth0, gateway 10.42.0.1, assigned IP 10.42.0.15 and family v4
2024-12-08T12:51:29Z INFO [routing] adding route for 0.0.0.0/0
2024-12-08T12:51:29Z INFO [firewall] setting allowed subnets...
2024-12-08T12:51:29Z INFO [routing] default route found: interface eth0, gateway 10.42.0.1, assigned IP 10.42.0.15 and family v4
2024-12-08T12:51:29Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2024-12-08T12:51:29Z INFO [routing] routing cleanup...
2024-12-08T12:51:29Z INFO [routing] default route found: interface eth0, gateway 10.42.0.1, assigned IP 10.42.0.15 and family v4
2024-12-08T12:51:29Z INFO [routing] deleting route for 0.0.0.0/0
2024-12-08T12:51:29Z ERROR creating tun device: unix opening TUN device file: operation not permitted (did you specify --device /dev/net/tun to your container command?)
2024-12-08T12:51:29Z INFO Shutdown successful
```
