### ISSUE TITLE
Traefik Ingress should process IPv6 traffic

### ISSUE THREAD

**Issue by weber-software** [k3s-io/k3s#1162]
**Version:**
`k3s version v1.0.0 (18bd921c)`

**Describe the bug**
When using the traefik ingress controller it is only listening on my public IPv4 address.
I would expect the ingress to listen on my IPv6 address also by default.
But maybe i just need to add some flags?

**To Reproduce**
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  backend:
    serviceName: hello-world
    servicePort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    app: hello-world
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-world
        tier: frontend
    spec:
      containers:
      - image: tutum/hello-world:latest
        name: hello-world
        ports:
        - containerPort: 80
          name: hello-world
```

**Expected behavior**
Ingress should accept traffic from my IPv4 AND IPv6 address.

**Actual behavior**
It only accepts traffic from my IPv4 address.

**Additional context**

**Comment by chrisnew** [comment]
To get that working the whole networking must become dualstack aware. I think that’s a long way considering the use of flannel. I’m looking forward to proper IPv6 support, especially when the selling point is targetting IoT and edge. :-)

**Comment by leifnel** [comment]
If the host is connected to a modern network at an educated hosting-provider, which gives an ipv6-range, is it then possible to give each container a real public ipv6?
Besides the load-balancing stuff, one of the reasons for traefik is the need to run multiple hosts on a single legacy IPv4 address.

Alas, there are ignorant providers which only gives a /128 address, who can't route a block of addresses to a single machine, in which case we appearently have to wait for traefik/docker to be upgraded to modern adresses.

**Comment by chrisnew** [comment]
Not sure about K3s, but I run K8s IPv6-only with kubenet as network plugin. It works just fine with a routed IPv6 network to each node. The pods are getting IPs assigned out of that space as well and they reach the Internet and vice versa.

**Comment by chris2k20** [comment]
Any news on the IPv6 support here?

**Comment by brandond** [comment]
We're still waiting on flannel itself to support ipv6; until that happens we probably won't worry too much about stuff like servicelb not supporting ipv6 for routing to the ingress service.

**Comment by vzuevsky** [comment]
what about calico?

**Comment by genofire** [comment]
i use flannel with vxlan / default - that works, my service got a cluster-ip with ipv6 either.

but i need that the default loadbalancer to be accessible per ipv6

**Comment by ntrp** [comment]
I installed the latest version from scratch and specified the IPv6 cidrs as per documentation (https://rancher.com/docs/k3s/latest/en/installation/network-options/):

```
write-kubeconfig-mode: 644
node-ip: <ipv4>,<ipv6>
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
flannel-ipv6-masq: true
disable-network-policy: true
```
Then after a while of research I managed to make it work by setting proper config on the traefik service:
```
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
```
Now traefik receives traffic on both IPv4 and IPv6 (80,443)

**Comment by ShylajaDevadiga** [comment]
Validated using commit id k3s version v1.23.6+k3s-2f22703c (2f22703c)
```
status:
  loadBalancer:
    ingress:
    - ip: 192.168.11.48
    - ip: 192.168.19.35
    - ip: 192.168.21.173
    - ip: 192.168.22.125
    - ip: 2600:<REDACTED>
    - ip: 2600:<REDACTED>
    - ip: 2600:<REDACTED>
    - ip: 2600:<REDACTED>
```
Loadbalancer can we reached using ipv6 
```
curl http://\[2600:<REDACTED>\]:8082
<html><body><h1>It works!</h1></body></html>
curl http://\[2600:<REDACTED>\]:8084
<html><body><h1>It works!</h1></body></html>
```
```
curl  --header host:testds.com http://\[2600:<REDACTED>\]/name.html
ds-clusterip-pod-69f9978b55-v9dqh
curl  --header host:testds.com http://\[2600:<REDACTED>\]/name.html
ds-clusterip-pod-69f9978b55-hjtdc
```
