### ISSUE TITLE
Traefik upgrade fail during K3S Update

### ISSUE THREAD

**Issue by h00lig4n** [k3s-io/k3s#11815]
Hi,

K3S Installation with default traefik setup. While applying a K3S update to v1.31.5 this has happened:

if [[ ${KUBERNETES_SERVICE_HOST} =~ .*:.* ]]; then
        echo "KUBERNETES_SERVICE_HOST is using IPv6"
        CHART="${CHART//%\{KUBERNETES_API\}%/[${KUBERNETES_SERVICE_HOST}]:${KUBERNETES_SERVICE_PORT}}"
chart path is a url, skipping repo update
else
        CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
fi

set +v -x
+ [[ '' == \v\2 ]]
+ shopt -s nullglob
+ [[ -f /config/ca-file.pem ]]
+ [[ -f /tmp/ca-file.pem ]]
+ [[ false == \t\r\u\e ]]
+ [[ false == \t\r\u\e ]]
+ [[ -n '' ]]
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/tmp/traefik.tgz
+ [[ ! -f /chart/traefik.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
+ echo 'chart path is a url, skipping repo update'
+ helm repo remove stable
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string global.systemDefaultRegistry=
++ helm ls --all -f '^traefik$' --namespace kube-system --output json
++ jq -r '"\(.[0].chart),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
+ LINE=null,null
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ null =~ ^(|null)$ ]]
+ [[ null =~ ^(|null)$ ]]
+ echo 'Installing helm chart'
+ helm install --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-27.0.201+up27.0.2.tgz --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml   
coalesce.go:286: warning: cannot overwrite table with non table for traefik.ports.traefik.expose (map[default:false])
Error: INSTALLATION FAILED: template: traefik/templates/service.yaml:27:12: executing "traefik/templates/service.yaml" at <index (default dict $config.expose) $name>: error calling index: can't index item of type bool

**Comment by brandond** [comment]
What values do you have in your traefik HelmChartConfig?

**Comment by h00lig4n** [comment]
Looks like this:
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    api:
      insecure: false
      dashboard: true
    ports:
      traefik:
        expose: false
      mqtt:
        port: 8883
        expose: true
        exposedport: 8883
    logs:
      access:
        enabled: true

I have experimented with changing to the following but doesn't help:
    ports:
      traefik:
        expose: 
           default: false

**Comment by h00lig4n** [comment]
ok. We'll I removed the custom MQTT setup and the error is gone now.
Need to work out what it should look like since the update.

**Comment by h00lig4n** [comment]
I will close this now. Everything is up and running again.

Completely removing the HelmChartConfig did not resolve the problem. I was under the impression the valuescontent only overrides, but it seemed like it had cached the values.

Ended up removing traefik, and  HelmChartConfig file, then reinstalling it using the install scripts. After that I re-added the valid  HelmChartConfig and it worked.

This is the updated config that is working, with expose being the item that changed.
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    api:
      insecure: false
      dashboard: true
    ports:
      traefik:
        expose:
          default: false
      mqtt:
        port: 8883
        expose:
          default: true
        exposedPort: 8883
      mqtt-insecure:
        port: 1883
        expose:
          default: true
        exposedPort: 1883
    logs:
      access:
        enabled: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
```
