### ISSUE TITLE
Add a notice to the K3s documentation, if someone is trying to use a galera cluster as datastore

### ISSUE THREAD

**Issue by lirtistan** [k3s-io/k3s#11816]
**Is your feature request related to a problem? Please describe.**

I installed a test cluster and tried some of the datastore solutions (just to understand that always ongoing disk IO thing from etcd store)...
So i installed a mariadb with galera (wsrep with `mariabackup` as SST method), after that multi master setup became online/ready i deployed the first control-plane just to make sure everything is working together.

The (ansible) config for the first control-plane looks like this...

```yaml
##################################
# K3s setting
##################################
k3s:
  role: agent
  version: v1.32.1+k3s1
  token_from: staging1
  config: |
    flannel-backend: none
    disable-kube-proxy: true
    disable-network-policy: true
    disable-helm-controller: true
    disable:
    - servicelb
    - traefik
    tls-san:
    - cluster
    - staging1
    - staging2
    - 172.16.0.1
    - 172.16.0.2
    - 192.168.122.246
    - 192.168.122.90
    server: "https://cluster:6443"
    #bind-address: "172.16.0.1"
    #kubelet-arg:
    #- "node-ip=172.16.0.1"
    cluster-cidr: "10.42.0.0/16"
    cluster-dns : "10.43.0.10"
    service-cidr: "10.43.0.0/16"
    debug: false
    #datastore-endpoint: "mysql://k3s:{{ secrets["all"]["k3s"]["datastore"]["password"] }}@tcp(cluster:3306)/k3s"
  modules:
  - name: dm_crypt
  - name: br_netfilter
  packages:
  - nfs-common
  - open-iscsi
  - cryptsetup
  - dmsetup
  post_install:
  - plugin: cilium
    actions:
    - name: install
      action: |
        cilium install \
        --set k8sServiceHost=cluster \
        --set k8sServicePort=6443 \
        --set kubeProxyReplacement=true \
        --helm-set operator.replicas=1
    - name: enable hubble
      action: |
        cilium enable hubble
        cilium enable hubble --ui
```

The server came up with an installed/running cilium CNI.
After a short visit into the logs (just to make sure everything is working and no major side-effects popping) ,i keept that setup running over night, watching for growing things (like the `k3s` database `kine` table), i realized that there is a fluctuation between incoming data vs deleting/compacting, so i visited a couple of those event but it wasn't high (`kine` table entries where under 3000), so i went to bed but keept the watcher running over night.
On the next morning (after round about 6hr) the count was over 70000 and i started searching for the root cause, i also searched for reported issues in github and came to #10619 where it turns out that galera was never tested as reported here https://github.com/k3s-io/k3s/issues/10619#issuecomment-2261503309

**Describe the solution you'd like**

Whould be nice to add such things to the documentation.
