### ISSUE TITLE
Cannot enable 1.32 feature gates: agent kubelet emulated version 1.31

### ISSUE THREAD

**Issue by LarssonOliver** [k3s-io/k3s#11937]
**Environmental Info:**
K3s Version: 

```
k3s version v1.32.2+k3s1 (381620ef)
go version go1.23.6
```
```
$ kubectl get nodes
NAME   STATUS   ROLES                  AGE    VERSION
[..]   Ready    <none>                 189d   v1.32.2+k3s1
[..]   Ready    control-plane,master   189d   v1.32.2+k3s1
```

Node(s) CPU architecture, OS, and Version: 

server (ubuntu 22.04): `Linux [..] 5.15.0-134-generic #145-Ubuntu SMP Wed Feb 12 20:08:39 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`
agent (ubuntu 24.04): `Linux [..] 6.8.0-55-generic #57-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 12 23:42:21 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

1 server, 1 agent

**Describe the bug:**

I'm attempting to enable the `InPlacePodVerticalScalingAllocatedStatus` and `InPlacePodVerticalScalingExclusiveCPUs` feature gates placed in alpha in 1.32. Works fine on the server side components, but when passed to the kubelet on the agent node as config through:
```yaml
  kubelet-arg:
    - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
    - --cpu-manager-policy=static
    - --reserved-cpus=0

```
The agent fails to start, throwing this message in the logs:
```
mar 11 08:12:48 [..] k3s[1749050]: Error: failed to set feature gates from initial flags-based config: [cannot set feature gate InPlacePodVerticalScalingAllocatedStatus to true, feature is PreAlpha at emulated version 1.31, cannot set feature gate InPlacePodVerticalScalingExclusiveCPUs to true, feature is PreAlpha at emulated version 1.31]
mar 11 08:12:48 [..] k3s[1749050]: time="2025-03-11T08:12:48Z" level=error msg="kubelet exited: failed to set feature gates from initial flags-based config: [cannot set feature gate InPlacePodVerticalScalingAllocatedStatus to true, feature is PreAlpha at emulated version 1.31, cannot set feature gate InPlacePodVerticalScalingExclusiveCPUs to true, feature is PreAlpha at emulated version 1.31]"
```
I have not explicitly set the emulated version argument. Even if I do and set it to `--emulated-version=1.32` in the server `kube-apiserver-arg` option, same thing happens.

**Steps To Reproduce:**

- Installed K3s: 
- Config:
```yaml
--- # server
kube-apiserver-arg: &feature-gates
    - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kubelet-arg: *feature-gates
kube-scheduler-arg: *feature-gates
kube-controller-manager-arg: *feature-gates
--- # agent
kubelet-arg:
  - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
  - --cpu-manager-policy=static
  - --reserved-cpus=0
```
- Attempt to start agent

**Expected behavior:**

Server and agent starts with features enabled.

**Actual behavior:**

Server starts, but agent exits due to error described above.

**Additional context / logs:**

Removing the two newer feature gates from the agent config allows works as expected (obviously without the new alpha features enabled). 

I'm a bit confused as to why the agent kubelet thinks it needs to emulate 1.31... The server kubelet seems to accept the feature gate just fine.

**Comment by brandond** [comment]
Seems to work fine for me... do you have something else in your environment that is setting the emulated version? That is not something we set or have ever set by default.

```console
brandond@dev01:~$ kubectl get node -o wide
NAME                       STATUS   ROLES                  AGE    VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION   CONTAINER-RUNTIME
k3s-server-1.example.com   Ready    control-plane,master   2m3s   v1.32.2+k3s1   172.17.0.4    <none>        K3s v1.32.2+k3s1   
6.8.0-1016-aws   containerd://2.0.2-k3s2

brandond@dev01:~$ kubectl get node -o yaml | grep k3s.io/node-
      k3s.io/node-args: '["server","--kubelet-arg","system-reserved=cpu=6","--kubelet-arg","image-gc-high-threshold=100","--kubelet-arg","feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true","--kube-scheduler-arg","feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true","--kube-controller-manager-arg","feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true","--kube-apiserver-arg","feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true","--kube-proxy-arg","feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true"]'
      k3s.io/node-config-hash: E7F4ULJRPYLKZVMXS3UZE4YWT76EXSQGHUTDDHS4RZSRXPVTVXNQ====
      k3s.io/node-env: '{}'
```

Passing the same args via yaml seems to work fine as well:
```console
root@systemd-node-1:/# kubectl get node -o wide
NAME             STATUS   ROLES                  AGE   VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
systemd-node-1   Ready    control-plane,master   9s    v1.32.2+k3s1   172.17.0.4    <none>        openSUSE Leap 15.4   6.8.0-1016-aws   containerd://2.0.2-k3s2

root@systemd-node-1:/# cat /etc/rancher/k3s/config.yaml
kubelet-arg:
  - system-reserved=cpu=6
  - image-gc-high-threshold=100
  - feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kube-scheduler-arg:
  - feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kube-controller-manager-arg:
  - feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kube-apiserver-arg:
  - feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kube-proxy-arg:
  - feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
```

**Comment by brandond** [comment]
I suspect that your issue is probably related to not enabling the flag on all components. In particular you seem to have missed setting it on kube-proxy.

As discussed at https://github.com/k3s-io/k3s/issues/11853#issuecomment-2688779268 feature-gates generally should be consistently set across all components.

**Comment by LarssonOliver** [comment]
Hi again,

From what I can tell you only tested the server and not the agent? The server works as expected on my end too, it's the agent that's not.

I managed to reproduce this using two freshly installed Ubuntu 2404 VMs.

My full reproduction sequence:

1. Install two fresh ubuntu server 24.04 VMs.
2. Server node:
  - `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.32.2+k3s1 sh -`
  - Edit `/etc/systemd/system/k3s.service` to include `--config <path to config file>`
  - Full config file below:
  ```yaml
---
kube-apiserver-arg:
  - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kube-controller-manager-arg:
  - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kube-proxy-arg:
  - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kube-scheduler-arg:
  - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kubelet-arg:
  - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
```
  - `sudo systemctl daemon-reload && sudo systemctl restart k3s`
  - Works as expected.

3. Agent node:
  - `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.32.2+k3s1 K3S_URL=https://[...]:6443 K3S_TOKEN=[...] sh -`
  - Edit `/etc/systemd/system/k3s-agent.service` to include `--config <path to config file>`
  - Full config file below:
```yaml
---
kubelet-arg:
  - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
kube-proxy-arg:
  - --feature-gates=InPlacePodVerticalScaling=true,InPlacePodVerticalScalingAllocatedStatus=true,InPlacePodVerticalScalingExclusiveCPUs=true
```
  - `sudo systemctl daemon-reload && sudo systemctl restart k3s-agent`
  - Breaks as logs above indicate.
  - `sudo journalctl -f -u k3s-agent`

Been digging around in the code a bit and haven't been able to figure it out so far.
