### ISSUE TITLE
Deploy controller only deletes GVKs present in addon file

### ISSUE THREAD

**Issue by rorosen** [k3s-io/k3s#11975]
**Environmental Info:**
K3s Version: 

```
k3s version v1.32.2+k3s1 (381620ef)
go version go1.24.1
```

Node(s) CPU architecture, OS, and Version: 

```
Linux nixos 6.12.19 #1-NixOS SMP PREEMPT_DYNAMIC Thu Mar 13 12:02:20 UTC 2025 x86_64 GNU/Linux
```

Cluster Configuration:

Single node cluster, 1 server

**Describe the bug:**

The [AddOn controller](https://docs.k3s.io/installation/packaged-components?_highlight=addon#auto-deploying-manifests-addons) doesn't delete all created resources, if a corresponding `--delete` flag is set, but the related manifest file in `/var/lib/rancher/k3s/server/manifests` doesn't list all GVKs that were previously created by this addon.

**Steps To Reproduce:**

- Installed K3s: via the NixOS package but this applies to all k3s installations
- Create an addon file at `/var/lib/rancher/k3s/server/manifests/foo.yaml`
    <details>
    
    <summary>Content</summary>
    
    ```yaml
    apiVersion: v1
    kind: Namespace
    metadata:
      name: test
    
    ---
    apiVersion: v1
    data:
      player_initial_lives: '3'
      ui_properties_file_name: user-interface.properties
    kind: ConfigMap
    metadata:
      name: bar
    
    ---
    apiVersion: v1
    data:
      player_initial_lives: '3'
      ui_properties_file_name: user-interface.properties
    kind: ConfigMap
    metadata:
      name: baz
    ```
    
    </details>
- All resources of the file are created
- An addon resource is created
    <details>
    
    <summary>Content</summary>
    
    ```yaml
    apiVersion: k3s.cattle.io/v1
    kind: Addon
    metadata:
      annotations:
        addon.k3s.cattle.io/gvks: /v1, Kind=Namespace;/v1, Kind=ConfigMap
      creationTimestamp: "2025-03-17T07:04:48Z"
      generation: 2
      name: foo
      namespace: kube-system
      resourceVersion: "268"
      uid: c1eb794f-3818-4beb-9a95-3a066fc5c29a
    spec:
      checksum: 4476eadc7c38e4eccc8087f096f37208248b5c327b052b1424275c0b5d8264f1
      source: /var/lib/rancher/k3s/server/manifests/foo.yaml
    ```
    
    </details>
- Stop k3s
- Modify `/var/lib/rancher/k3s/server/manifests/foo.yaml`
    <details>
    
    <summary>New content</summary>
    
    ```yaml
    apiVersion: v1
    data:
      player_initial_lives: '3'
      ui_properties_file_name: user-interface.properties
    kind: ConfigMap
    metadata:
      name: baz
    ```
    
    </details>
- Start k3s with `--disable foo` flag
- The addon resource is deleted
- Both(!) ConfigMaps are deleted
- The `test` namespace still exists

**Expected behavior:**

All resources that were previously applied by the addon are deleted, including the `test` namespace.

**Actual behavior:**

Only resources with a GVK that is still present in `/var/lib/rancher/k3s/server/manifests/foo.yaml` are deleted.

**Additional context / logs:**

I did some testing and the problem is this line: https://github.com/k3s-io/k3s/blob/master/pkg/deploy/controller.go#L309. The first time the controller runs with `--disable foo`, it correctly merges all GVKs from the addon resource and the file content. However, it then deletes the addon resource (which I suppose returns with `err == nil`) and thus returns early with a `nil` error, **before** applying an empty set with owner & GVK data to delete [here](https://github.com/k3s-io/k3s/blob/master/pkg/deploy/controller.go#L314) and removing the manifest file.

The next time the controller runs, it only has access to the GVKs in the file. This time deleting the addon resource should return with a `Not Found` error, so it doesn't return early, applies the empty set with the GVKs from the file and finally removes the file.

The comment in [line 307](https://github.com/k3s-io/k3s/blob/master/pkg/deploy/controller.go#L307) indicates that the early returning if `err == nil` is intentional, but I don't understand the background. Everything works as expected, if I change `err == nil || !apierrors.IsNotFound(err)` to `err != nil && !apierrors.IsNotFound(err)` in line 309. I will open a PR, but I'm not sure about this due to the comment.

## More Background

I already created an issue for this some time ago (https://github.com/k3s-io/k3s/issues/9359) but I had no time to look into this until now. I aim to manage resources declaratively via the deploy controller, which requires deleting all resources created by an addon file, without needing to know the file's previous contents. The change mentioned above works also when `--disable foo` is set and `/var/lib/rancher/k3s/server/manifests/foo.yaml` is empty (`{}`), which is what I finally want to do.
