### ISSUE TITLE
Traefik Dashboard has stopped working with v1.32.2

### ISSUE THREAD

**Issue by boomam** [k3s-io/k3s#12010]
**Environmental Info:**
K3s Version: v1.32.2+k3s1

Node(s) CPU architecture, OS, and Version: n/a

Cluster Configuration: 3x nodes.

**Describe the bug:**
Upgrading to v1.32.2+k3s1 from 1.32.1 (and thus Traefik v2 to v3) breaks the Traefik dashboard accessibility, with a 404 error.

**Steps To Reproduce:**
Use system upgrade plan to upgrade to v1.32.2

**Expected behavior:**
Dashboard to work.
**Actual behavior:**
Dashboard does not work. Port 9000/tcp is not getting added to the Traefik service.

**Additional context / logs:**
Dashboard was previously enabled with the following yaml - 
```
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: kube-system
  labels:
   app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik-dashboard
spec:
  type: ClusterIP
  ports:
  - name: traefik
    port: 9000
    targetPort: traefik
    protocol: TCP
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: "issuer"
spec:
  rules:
    - host: traefik.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik-dashboard
                port:
                  number: 9000
  tls:
  - hosts:
    - traefik.domain.com
    secretName: traefik-dashboard
```
