### ISSUE TITLE
SystemOOM with a lot of free RAM

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [k3s-io/k3s#12028]
**Environmental Info:**
K3s Version: 
3s version v1.32.3+k3s1 (079ffa8d)
go version go1.23.6

Node(s) CPU architecture, OS, and Version: 
Linux peque 6.14.0-3-cachyos #1 SMP PREEMPT_DYNAMIC Wed, 26 Mar 2025 06:38:53 +0000 x86_64 GNU/Linux

Cluster Configuration:
1 node

**Describe the bug:**
I used to use normally k3s.
But now, I'm getting constantly SystemOOM, even though my system has enough resources.

**Steps To Reproduce:**
- Installed K3s: 
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -s -
```
I start the `web-vision` pod and I get a SystemOOM.
On other colleagues that are working in the same project:
```
kubectl top pod
NAME                             CPU(cores)   MEMORY(bytes)   
bd-55bc89fd9f-mnwvm              3m           415Mi           
cypress-local-5777947674-b7qpb   0m           2Mi             
httpd-build-56c4d9684c-s77mc     1m           15Mi            
minio-84fcbf6ddc-mbhsg           1m           144Mi           
redis-6586f58ffc-rcr5n           2m           10Mi            
sbt-56cf649958-6bszq             0m           1Mi             
sftp-7467467966-jwnd6            0m           8Mi             
visor-5b5669b558-89msn           1m           644Mi           
web-frontal-854f97f448-zttm8     1m           8Mi             
web-vision-577fbfbc97-d6k85      1m           2860Mi
````
and
```+ kubectl top node
NAME         CPU(cores)   CPU(%)   MEMORY(bytes)   MEMORY(%)   
ismael-fcc   1503m        5%       22125Mi         69%
```
In my workstation:
```
❯ k top no
NAME    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
peque   656m         4%     15778Mi         54%   
```

**Expected behavior:**
No SystemOOM under low loads

**Actual behavior:**
I cannot work with k3s on my system, all pods are constantly dying.

**Additional context / logs:**
```
top - 11:50:21 up  2:24,  1 user,  load average: 0,45, 0,73, 0,84
Tarefas: 550 total, 1 running, 549 sleep, 0 d-sleep, 0 stopped, 0 zombie
%CPU(s):  1,9 us,  0,7 sy,  0,0 ni, 97,0 id,  0,0 wa,  0,2 hi,  0,1 si,  0,0 st 
MB mem :  28985,6 total,   2470,8 free,  14886,2 used,  12556,6 buff/cache
```
![Image](https://github.com/user-attachments/assets/de40ab06-9f06-4130-a01f-7d52f252880d)
```
❯ k describe node
Name:               peque
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=peque
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=true
                    node-role.kubernetes.io/master=true
                    node.kubernetes.io/instance-type=k3s
Annotations:        alpha.kubernetes.io/provided-node-ip: 192.168.1.15
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"ee:bc:22:1a:6f:28"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 192.168.1.15
                    k3s.io/hostname: peque
                    k3s.io/internal-ip: 192.168.1.15
                    k3s.io/node-args: ["server","--disable","traefik"]
                    k3s.io/node-config-hash: JVBB3FE3SQ2RU6T2GURBXU6C47XOVCA74HYNFW3O6TZXT2YKPLNA====
                    k3s.io/node-env: {}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Fri, 28 Mar 2025 11:06:11 +0100
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  peque
  AcquireTime:     <unset>
  RenewTime:       Mon, 31 Mar 2025 12:53:52 +0200
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Mon, 31 Mar 2025 12:51:53 +0200   Fri, 28 Mar 2025 11:06:11 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 31 Mar 2025 12:51:53 +0200   Fri, 28 Mar 2025 11:06:11 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Mon, 31 Mar 2025 12:51:53 +0200   Fri, 28 Mar 2025 11:06:11 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Mon, 31 Mar 2025 12:51:53 +0200   Fri, 28 Mar 2025 11:06:13 +0100   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.1.15
  Hostname:    peque
Capacity:
  cpu:                16
  ephemeral-storage:  46089Mi
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             29681268Ki
  pods:               110
Allocatable:
  cpu:                16
  ephemeral-storage:  45911428265
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             29681268Ki
  pods:               110
System Info:
  Machine ID:                 4e91b70d41124638b77ad7db6fdc7e81
  System UUID:                03000200-0400-0500-0006-000700080009
  Boot ID:                    efb44996-85e7-4f6a-97f8-41f256f96af4
  Kernel Version:             6.14.0-3-cachyos
  OS Image:                   CachyOS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://2.0.4-k3s2
  Kubelet Version:            v1.32.3+k3s1
  Kube-Proxy Version:         v1.32.3+k3s1
PodCIDR:                      10.42.0.0/24
PodCIDRs:                     10.42.0.0/24
ProviderID:                   k3s://peque
Non-terminated Pods:          (14 in total)
  Namespace                   Name                                             CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                             ------------  ----------  ---------------  -------------  ---
  ingress-nginx               ingress-nginx-controller-7d76478684-59wlt        100m (0%)     0 (0%)      90Mi (0%)        0 (0%)         3d
  kube-system                 coredns-ff8999cc5-9hr4k                          100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)     3d
  kube-system                 local-path-provisioner-774c6665dc-pgfz2          0 (0%)        0 (0%)      0 (0%)           0 (0%)         3d
  kube-system                 metrics-server-6f4c6675d5-knnc5                  100m (0%)     0 (0%)      70Mi (0%)        0 (0%)         3d
  kube-system                 svclb-ingress-nginx-controller-f4867240-776v5    0 (0%)        0 (0%)      0 (0%)           0 (0%)         3d
  sbt                         bd-55bc89fd9f-79hms                              1500m (9%)    1500m (9%)  1500Mi (5%)      1500Mi (5%)    49m
  sbt                         cypress-local-dcd75d547-v5rtr                    0 (0%)        0 (0%)      0 (0%)           0 (0%)         49m
  sbt                         httpd-build-56c4d9684c-zwnb5                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         49m
  sbt                         minio-9fb584c78-ss9wj                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         49m
  sbt                         redis-869755497b-hddtt                           0 (0%)        0 (0%)      0 (0%)           0 (0%)         49m
  sbt                         sbt-6996cc9774-l5bj5                             0 (0%)        0 (0%)      0 (0%)           0 (0%)         49m
  sbt                         sftp-5fc8489d45-wqrzf                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         49m
  sbt                         web-frontal-6c9dcdcb57-9npws                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         49m
  sbt                         web-vision-7949879c55-26zp2                      0 (0%)        0 (0%)      0 (0%)           0 (0%)         49m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                1800m (11%)  1500m (9%)
  memory             1730Mi (5%)  1670Mi (5%)
  ephemeral-storage  0 (0%)       0 (0%)
  hugepages-1Gi      0 (0%)       0 (0%)
  hugepages-2Mi      0 (0%)       0 (0%)
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  SystemOOM  50m (x123 over 159m)  kubelet  (combined from similar events): System OOM encountered, victim process: node, pid: 141753
```

**Comment by brandond** [comment]
OOM indicates that one of the pods exceeded its memory limits. Remove the limits from the pod spec, or raise them above what the pod actually needs.

**Comment by DavidPerezIngeniero** [comment]
None of my pods have memory constraints.
Only we have memory constraints in production, not for developing locally.
Here is the pod that is dying more often:
```yaml
Name:             web-vision-546c7b7bc4-b7vnt
Namespace:        sbt
Priority:         0
Service Account:  default
Node:             peque/192.168.1.15
Start Time:       Tue, 01 Apr 2025 09:01:42 +0200
Labels:           app=web-vision
                  pod-template-hash=546c7b7bc4
                  role=web-vision
Annotations:      <none>
Status:           Running
IP:               10.42.0.24
IPs:
  IP:           10.42.0.24
Controlled By:  ReplicaSet/web-vision-546c7b7bc4
Containers:
  node-dev:
    Container ID:   containerd://727b8f2fa6e0ab9f7f7229c8acca29da3d0c1e70374ca69ddd947b80607ce725
    Image:          registro-local:5000/node-dev:0.15
    Image ID:       registro-local:5000/node-dev@sha256:50a08bc5f521a70070c99c1c4fb8696d12c78a5450d7628510bfc2aa065b21d7
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 01 Apr 2025 09:01:49 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /web/vision from espacio-trabajo (rw)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  espacio-trabajo:
    Type:          HostPath (bare host directory volume)
    Path:          /home/david/p/rds/web/vision
    HostPathType:  Directory
QoS Class:         BestEffort
Node-Selectors:    <none>
Tolerations:       node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                   node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  37s   default-scheduler  Successfully assigned sbt/web-vision-546c7b7bc4-b7vnt to peque
  Normal  Pulled     32s   kubelet            Container image "registro-local:5000/node-dev:0.15" already present on machine
  Normal  Created    31s   kubelet            Created container: node-dev
  Normal  Started    31s   kubelet            Started container node-dev
```

My colleagues work normally, and I used to.
The main difference is that I'm using CachyOS (Arch Linux based) and BTRFS and my colleagues Ubuntu and ext4 as a file system.
