### ISSUE TITLE
incorrect node-ip/tls-san result in tls error when installing cilium

### ISSUE THREAD

**Issue by brpaz** [k3s-io/k3s#12238]
**Environmental Info:**
K3s Version: 
k3s version v1.32.4+k3s1 (6b330558)
go version go1.23.6

Node(s) CPU architecture, OS, and Version: 
Linux k3s-control-plane-01 6.8.0-58-generic #60-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 14 18:09:50 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
single node

**Describe the bug:**

Hello. I am having issues installing Cilium in my K3s cluster. It seems when I set my `node-ip` to my private ip address on kubelet: `node-ip=10.115.1.2`, the tls certificate is not correctly generated, resulitng in the follow error during Cilium installation:

```
error dialing backend: tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, 91.99.21.120, 2a01:4f8:c0c:ed7d::1, not 10.115.1.2
```

In this example: `91.99.21.120` is my public network ip, while the other one is the internal ip.

If I set node_ip to the public ip it works fine.

I tried to add the private ip to tls san, but it gives the same error.

**Steps To Reproduce:**

**Create `/etc/rancher/k3s/config.yaml`:**

```yaml
node-name: k3s-control-plane-01
cluster-init: true
disable:
  - traefik
  - servicelb
  - metrics-server
disable-cloud-controller: true
disable-network-policy: true
disable-helm-controller: true
disable-kube-proxy: true
flannel-backend: none
write-kubeconfig-mode: 644
kube-apiserver-arg:
  - "--kubelet-preferred-address-types=InternalIP,ExternalIP"
kubelet-arg:
  - "cloud-provider=external"
  - "max-pods=500"
  - "node-ip=10.115.1.2"

# TLS SANs for the control plane. Set this for with the LB IP if using a load balancer.
tls-san:
  - 10.115.1.2
``` 

**Install k3s**

`curl -sfL https://get.k3s.io | sh -`

**Install cillium**

```
cilium install --version 1.17.3
``` 

**Expected behavior:**
Cilium should be installed when k3s have node-ip set to private ip

**Actual behavior:**

``` 
error dialing backend: tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, 91.99.21.120, 2a01:4f8:c0c:ed7d::1, not 10.115.1.2
``` 

**Additional context / logs:**
