### ISSUE TITLE
Add a topologySpreadConstraint with `topology.kubernetes.io/zone` key to CoreDNS manifest

### ISSUE THREAD

**Issue by l2dy** [k3s-io/k3s#12433]
**Is your feature request related to a problem? Please describe.**

Currently, K3s spreads CoreDNS pods across nodes if more replicas is set, but nodes could be in the same zone and fail together.

```yaml
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              k8s-app: kube-dns
```

**Describe the solution you'd like**
Add a `topologySpreadConstraints` on `topology.kubernetes.io/zone` like what EKS did in https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html.

```yaml
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        k8s-app: kube-dns
```

**Describe alternatives you've considered**
1. Disable the bulit-in manifest and ship a copy myself, but templating like `%{CLUSTER_DNS_IPFAMILYPOLICY}%` is not supported in custom manifests, which complicates the process.

**Additional context**
