### ISSUE TITLE
Unable to access services from outside in Buster, even with iptables set to legacy,

### ISSUE THREAD

**Issue by Ripolak** [k3s-io/k3s#1250]
**Version:**
k3s version v1.0.1 (e94a3c60)

**Describe the bug**
I set up a K3S cluster on 3 raspberry pis running Raspbian Buster. When I attempt exposing a service to the outside world, even if I use NodePort instead of Traefik (I tried Traefik first and wanted to try NodePort, but both did not work at all), accessing the master node from outside starts an infinite loading from both Chrome or the Curl command. Accessing the inside service IP from the cluster itself works though. 

I read on another topic (https://github.com/alexellis/k3sup/issues/89) that it could be the fault of me not using iptables-legacy, so I ran the following command on all my nodes: 

`update-alternatives --set iptables /usr/sbin/iptables-legacy` 

And deleted k3s and reinstalled it, but things still don't seem to work.

**To Reproduce**

I tried running the following deployments:

Without Traefik:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:latest
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: default
spec:
  selector:
    app: consul
  type: NodePort
  ports:
  - name: http
    port: 8500
    targetPort: 8500
    nodePort: 30036
    protocol: TCP
```

With Traefik:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consul 
  template:
    metadata:
      labels:
        app: consul 
    spec:
      containers:
      - name: consul
        image: consul:latest
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 8500
    port: 80
  selector:
    app: consul
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul
  annotations:
    kubernetes.io/ingress.class: "traefik"

spec:
  rules:
  - host: consul.example.org
    # I tried adding consul.example.org to my hosts file, but to no effect.
    http:
      paths:
      - path: /
        backend:
          serviceName: consul
          servicePort: http
```

**Expected behavior**
Entering the service from either port 80 with the right DNS (when deploying with Traefik) Or the exposed port (3****) should work the same as accessing within the cluster.

**Actual behavior**
The connection from within the cluster works, but connection from outside of it does not.

**Additional context**
None so far, I'll update if anything else comes to mind.
