### ISSUE TITLE
Dangling replicaset occurs after kubectl set of deployment container image

### ISSUE THREAD

**Issue by brianpclab** [k3s-io/k3s#1253]
**Version:**
k3s version v1.0.1 (e94a3c60)

**Describe the bug**

Performed a kubectl set on the deployment container image and then watched the pods being created and terminated. 
`kubectl set image deployment.apps/ktest02-deployment ktest02=index.docker.io/brianpclab/kubernetestest02:20191230015032`

 Afterwards I did a kubectl get all and noticed that there were dangling replica sets

**To Reproduce**
**Step 1**
> kubectl apply -f _service.yaml_ -f _deployment.yaml_ 

**service.yaml**
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ktest02-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ktest02
  type: NodePort
```
**deployment.yaml**
```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ktest02-deployment
spec:
  selector:
    matchLabels:
      app: ktest02
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ktest02
    spec:      
      containers:
      - name: ktest02
        image: index.docker.io/brianpclab/kubernetestest02:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: API_PATH_BASE
          value: "/ktest02"
      nodeSelector:
         kubernetes.io/arch: arm64
```
**Step 2**

> kubectl get all

_Below is the result of the command above_

```
NAME                                      READY   STATUS    RESTARTS   AGE
pod/ktest02-deployment-758966df99-qgmfj   1/1     Running   0          113s
pod/ktest02-deployment-758966df99-b4sjk   1/1     Running   0          113s

NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
service/kubernetes        ClusterIP   10.43.0.1      <none>        443/TCP        7d22h
service/ktest03-service   NodePort    10.43.24.74    <none>        80:32633/TCP   24h
service/ktest02-service   NodePort    10.43.150.34   <none>        80:31156/TCP   24h

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ktest02-deployment   2/2     2            2           113s

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/ktest02-deployment-758966df99   2         2         2       113s
```

**Step 3**

> kubectl set image deployment.apps/ktest02-deployment ktest02=index.docker.io/brianpclab/kubernetestest02:20191230015032

**Step 4**
> kubectl get all

**Expected behavior**
I would expect that the count of replica sets would be one.

**Actual behavior**

```
NAME                                      READY   STATUS    RESTARTS   AGE
pod/ktest02-deployment-85647b8cd7-shkg4   1/1     Running   0          4m19s
pod/ktest02-deployment-85647b8cd7-bmqhf   1/1     Running   0          4m7s

NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
service/kubernetes        ClusterIP   10.43.0.1      <none>        443/TCP        7d22h
service/ktest03-service   NodePort    10.43.24.74    <none>        80:32633/TCP   24h
service/ktest02-service   NodePort    10.43.150.34   <none>        80:31156/TCP   24h

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ktest02-deployment   2/2     2            2           7m6s

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/ktest02-deployment-85647b8cd7   2         2         2       4m19s
replicaset.apps/ktest02-deployment-758966df99   0         0         0       7m6s
```
**Additional context**
I noticed that if I edited the deployment.ymal file, updated the image and then did a

> kubectl apply -f deployment.yaml

 I did not see the dangling replica sets.  In my attempt to remove the dangling sets I had to actually perform a

> kubectl delete -f deployment.yaml

before they were cleaned up.
The docker repository is public.
The image is an ASP.NET Core 3.1 application that you can see at
https://brianpclab.net/ktest02

Attached are the nodes in my cluster.  
[nodes.zip](https://github.com/rancher/k3s/files/4008869/nodes.zip)
