### ISSUE TITLE
Flannel unable to route IPv6 traffic across nodes

### ISSUE THREAD

**Issue by Mulgish** [k3s-io/k3s#12538]
**Environmental Info:**
K3s Version: v1.32.5+k3s1 (8e8f2a47)

Node(s) CPU architecture, OS, and Version: 6.14.11-300.fc42.x86_64 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

Cluster Configuration: 3 control plane nodes

**Describe the bug:**
When forming a k3s cluster in DualStack or IPV6 only mode, Flannel is not routing IPV6 traffic across nodes.
IPv4 routing works fine.

**Steps To Reproduce:**

- Install [Fedora 42](https://fedoraproject.org/server/download)
- Disable firewall with `sudo systemctl stop firewalld`  for the purpose of reproducing the issue
- Set selinux in permissive mode `sudo setenforce 0`
- Setup a `bond0` interface in failover mode across eth0 and eth1
   `bond0` has a static IPv4. 
  Lets imagine that node 1 has `192.168.1.101`, node 2 has `192.168.1.102` and node 3 has `192.168.1.103`.

   `bond0` IPv6 address is set via RA advertisements.
  Lets imagine that node 1 has `2001:db8:85a3::1`, node 2 has `2001:db8:85a3::2` and node 3 has `2001:db8:85a3::3`.

- Install K3s on the first node with
  ```shell
  curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --cluster-init --bind-address=:: --node-ip=2001:db8:85a3::1,192.168.1.101 --cluster-cidr=2001:cafe:42::/56,10.42.0.0/16 --service-cidr=2001:cafe:43::/112,10.43.0.0/16 --flannel-backend=vxlan --selinux --flannel-ipv6-masq --tls-san=2001:db8:85a3::1 --tls-san=192.168.1.101" sh -s - server
  ```
- Add other K3s nodes with 
  Note! Make sure to replace `{{ k3s_token }}` with the result of `cat /var/lib/rancher/k3s/server/token` from the first node.
  ```shell
  curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --token={{ k3s_token }} --server=https://2001:db8:85a3::1:6443 --bind-address=:: --node-ip=2001:db8:85a3::2,192.168.1.102 --cluster-cidr=2001:cafe:42::/56,10.42.0.0/16 --service-cidr=2001:cafe:43::/112,10.43.0.0/16 --flannel-backend=vxlan --selinux --flannel-ipv6-masq --tls-san=2001:db8:85a3::2 --tls-san=192.168.1.102" sh -s - server
  ```
     ```shell
  curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --token={{ k3s_token }} --server=https://2001:db8:85a3::1:6443 --bind-address=:: --node-ip=2001:db8:85a3::3,192.168.1.103 --cluster-cidr=2001:cafe:42::/56,10.42.0.0/16 --service-cidr=2001:cafe:43::/112,10.43.0.0/16 --flannel-backend=vxlan --selinux --flannel-ipv6-masq --tls-san=2001:db8:85a3::3 --tls-san=192.168.1.103" sh -s - server
  ```
- Deploy below `DaemonSet` and a `curl` deployment into `default` namespace:
  ```yaml
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: simple-daemonset
  spec:
    selector:
      matchLabels:
        app: simple-daemonset
    template:
      metadata:
        labels:
          app: simple-daemonset
      spec:
        containers:
          - name: http-server
            image: hashicorp/http-echo:0.2.3
            args:
              - "-text=Hello from $(NODE_NAME)"
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            ports:
              - containerPort: 5678
                name: http
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: simple-daemonset-svc
  spec:
    selector:
      app: simple-daemonset
    ports:
      - protocol: TCP
        port: 5678
        targetPort: http
        name: http
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv6
      - IPv4
    type: ClusterIP
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    name: curlpod
  spec:
    containers:
      - name: curl
        image: curlimages/curl:latest
        command: [ "sleep", "3600" ]
  ```
- Execute IPV4 connectivity checks at least 3 times
  ```shell
   kubectl exec pods/curlpod -n default -- curl -4v simple-daemonset-svc.default:5678
  ```
- Observe `Hello from <Node hostname>` messages from all nodes in the cluster
- Now try the same for IPV6
    ```shell
   kubectl exec pods/curlpod -n default -- curl -6v simple-daemonset-svc.default:5678
  ```
- Observe intermittent connection timeout for nodes which don't have `pods/curpod` running
  This seems to be due to Flannel not forwarding IPv6 traffic for whatever reason.

**Expected behavior:**
IPV6 overlay networking should work

**Actual behavior:**
IPV6 overlay networking is broken for all Flannel backends

**Additional context / logs:**
N/A
