### ISSUE TITLE
`object` type without properties (in CRD) are empty

### ISSUE THREAD

**Issue by xunleii** [k3s-io/k3s#1406]
**Version:** `k3s version v1.17.2+k3s1 (cdab19b0)`

**Describe the bug**
I am currently installing the Prometheus Operator (https://github.com/coreos/prometheus-operator) on k3s and it is currently impossible to define the `name` field in `spec.storage.volumeClaimTemplate.metadata` in a new `Prometheus` resource.
The `spec.storage.volumeClaimTemplate.metadata` is defined as an object type and, when I run `kubectl get prometheuses.monitoring.coreos.com <name> -oyaml`, the `metadata` field is empty.  
After some tries, I can easily reproduce this behavior if I set `object` type for any field of a CRD, without properties.

The only field not affected by this behavior is the `metadata` field at the root level.

**To Reproduce**
1. New CRD `ObjectType` (`objecttype.crd.yaml` for example)
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: objecttypes.crd.k3s.io
spec:
  group: crd.k3s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                subSpec:
                  type: object
                  properties:
                    string:
                      type: string
                    integer:
                      type: integer
                    object:
                      type: object
                string:
                  type: string
                integer:
                  type: integer
                object:
                  type: object
            object:
              type: object
  scope: Namespaced
  names:
    plural: objecttypes
    singular: objecttype
    kind: ObjectType
    shortNames:
    - ot
```
2. New `ObjectType` resource (`ot-test.yaml` for example)
```
apiVersion: crd.k3s.io/v1
kind: ObjectType
metadata:
  name: ot-test
spec:
  subSpec:
    string: aaa
    integer: 999
    object:
      string: aaa
      integer: 999
  string: aaa
  integer: 999
  object:
    string: aaa
    integer: 999
object:
  string: aaa
  integer: 999
```
3. `kubectl create -f objecttype.crd.yaml && kubectl create -f ot-test.yaml -oyaml`

**Expected behavior**
```
apiVersion: crd.k3s.io/v1
kind: ObjectType
metadata:
  name: ot-test
  namespace: default
object:
  integer: 999
  string: aaa
spec:
  integer: 999
  object:
    integer: 999
    string: aaa
  string: aaa
  subSpec:
    integer: 999
    object:
      integer: 999
      string: aaa
    string: aaa
```
> Can be generated by `kubectl create -oyaml --dry-run ot-test.yaml`

**Actual behavior**
```
apiVersion: crd.k3s.io/v1
kind: ObjectType
metadata:
  creationTimestamp: "2020-02-11T22:00:00Z"
  generation: 1
  name: ot-test
  namespace: default
  resourceVersion: "45073"
  selfLink: /apis/crd.k3s.io/v1/namespaces/default/objecttypes/ot-test
  uid: bc0e13bd-5aee-454d-84bc-5087b7293523
object: {}
spec:
  integer: 999
  object: {}
  string: aaa
  subSpec:
    integer: 999
    object: {}
    string: aaa
```
> Can be generated by `kubectl create -oyaml ot-test.yaml`

**Additional context**
