### ISSUE TITLE
 Auto Deploying not work

### ISSUE THREAD

**Issue by thetruechar** [k3s-io/k3s#1428]
**Version:**
1.0.0

**Describe the bug**
when I change the content in /var/lib/rancher/k3s/server/manifests/traefik.yaml(add the setting service.nodePorts.http: 30080), the service/traefik is not changed.
content of  /var/lib/rancher/k3s/server/manifests/traefik.yaml:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.77.1.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "false"
    service.nodePorts.http: 30080
```
but the describe show the nodePort 30080 is not take effect:
```
kubectl describe svc/traefik  -n=kube_system
Name:                     traefik
Namespace:                kube-system
Labels:                   app=traefik
                          chart=traefik-1.77.1
                          heritage=Tiller
                          release=traefik
Annotations:              <none>
Selector:                 app=traefik,release=traefik
Type:                     LoadBalancer
IP:                       10.43.20.185
LoadBalancer Ingress:     172.16.24.138
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30579/TCP
Endpoints:                10.42.0.6:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  30051/TCP
Endpoints:                10.42.0.6:443
Port:                     metrics  8080/TCP
TargetPort:               dash/TCP
NodePort:                 metrics  32535/TCP
Endpoints:                10.42.0.6:8080
Session Affinity:         None
External Traffic Policy:  Cluster
```

**To Reproduce**
After installing, edit the file /var/lib/rancher/k3s/server/manifests/traefik.yaml

**Expected behavior**
service/traefik is changed reflecting the content of  /var/lib/rancher/k3s/server/manifests/traefik.yaml

**Actual behavior**
service/traefik is not changed
