### ISSUE TITLE
Insecure Registry Support

### ISSUE THREAD

**Issue by nnordrum** [k3s-io/k3s#145]
**Is your feature request related to a problem? Please describe.**
As a user, I cannot access insecure registries from my k3s instance.

**Describe the solution you'd like**
Add --insecure-registry to `server` and/or `node`.

**Describe alternatives you've considered**
I'm specifically trying to address this with the proxy team, but it should be added regardless.

**Additional context**
Behind a corporate proxy, it might use a different cert. It is what it is...

**Comment by ibuildthecloud** [comment]
I think it make sense to add `--insecure-registry` argument to the agent to address this.

**Comment by xiaosuiba** [comment]
@ibuildthecloud I think expose a --containerd-config argument also make sense. With the configuration file, I could customize containerd with `insecure-registry`, `sandbox-image`, etc.

**Comment by nnordrum** [comment]
+1 on the `--containerd-config`

**Comment by debianmaster** [comment]
+1 for --containerd-config

**Comment by AlbertoPeon** [comment]
👍  this would be nice to have !

Are there any alternatives to make it work with an insecure registry at the moment? Or setting a custom CA somewhere? Thanks!

**Comment by oraoto** [comment]
In k3s 0.5, you can config containerd with the template file `<data-dir>/etc/containerd/config.toml.tmpl`.

To add insecure registory:

```toml
[plugins.opt]
path = "{{ .NodeConfig.Containerd.Opt }}"

[plugins.cri]
stream_server_address = "{{ .NodeConfig.AgentConfig.NodeName }}"
stream_server_port = "10010"

[plugins.cri.registry.mirrors]
  [plugins.cri.registry.mirrors."docker.io"]
    endpoint = ["https://registry-1.docker.io"]
  [plugins.cri.registry.mirrors."your-insecure-registory:5000"]
    endpoint = ["http://your-insecure-registory:5000"]
```

Doc:  [containerd and Docker](https://github.com/rancher/k3s/blob/1d42fc97555e28767cb0f2687bffd5992071d284/README.md#containerd-and-docker)

**Comment by debianmaster** [comment]
@oraoto   do you know how to configure for selfsigned registries?

**Comment by oraoto** [comment]
@debianmaster https://github.com/containerd/containerd/issues/3071

**Comment by flxs** [comment]
@debianmaster I've been playing around with this while waiting for the proper fix, and I was able to get it to work by adding the CA cert to the host system's trusted CAs (Ubuntu 18.04 in my case) and configuring it via kubectl like any other registry.

**Comment by debianmaster** [comment]
@flxs  can you expand this a bit more?  what have you done?  `configuring it via kubectl like any other registry.` .

**Comment by SwagMuffinMcYoloPants** [comment]
> In k3s 0.5, you can config containerd with the template file `<data-dir>/etc/containerd/config.toml.tmpl`.
> 
> To add insecure registory:
> 
> ```toml
> [plugins.opt]
> path = "{{ .NodeConfig.Containerd.Opt }}"
> 
> [plugins.cri]
> stream_server_address = "{{ .NodeConfig.AgentConfig.NodeName }}"
> stream_server_port = "10010"
> 
> [plugins.cri.registry.mirrors]
>   [plugins.cri.registry.mirrors."docker.io"]
>     endpoint = ["https://registry-1.docker.io"]
>   [plugins.cri.registry.mirrors."your-insecure-registory:5000"]
>     endpoint = ["http://your-insecure-registory:5000"]
> ```
> 
> Doc: [containerd and Docker](https://github.com/rancher/k3s/blob/1d42fc97555e28767cb0f2687bffd5992071d284/README.md#containerd-and-docker)

I couldn't get this to work until I changed

```
[plugins.cri]
stream_server_address = "{{ .NodeConfig.AgentConfig.NodeName }}"
stream_server_port = "10010"
```

to

```
[plugins.cri]
stream_server_address = "{{ .NodeConfig.AgentConfig.NodeName }}"
stream_server_port = "10010"
  [plugins.cri.cni]
    bin_dir = "/bin"
    conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"
```

**Comment by rcarmo** [comment]
Actually, that should be:

```toml
[plugins.cri]
stream_server_address = "{{ .NodeConfig.AgentConfig.NodeName }}"
stream_server_port = "10010"
  [plugins.cri.cni]
    bin_dir = "{{ .NodeConfig.AgentConfig.CNIBinDir }}"
    conf_dir = "{{ .NodeConfig.AgentConfig.CNIConfDir }}"
```

At least that is what works for me with `v0.5.0`.

**Comment by rcarmo** [comment]
FYI, this stopped working for me with 0.7.0 on `armhf`. I have yet to figure out why.

**Comment by Duske** [comment]
I cannot get it to work as well. I use 0.7.0 and default `k3s`

**Comment by Duske** [comment]
@rcarmo This issue could related to it: https://github.com/containerd/cri/issues/1201, especially the merged PR https://github.com/containerd/containerd/pull/3400

**Comment by rcarmo** [comment]
Thanks. I’m going to try reverting to 0.6.0 in the meantime. since I really need support for an HTTP-only registry for dev/test/CI (it is a royal pain to do certificates for .lan/.local/anything private, and not worth the hassle).

**Comment by Duske** [comment]
The problem was a not 100%-conform  HTTP API V2 custom Docker registry.
After fixing the registry, it works with k3s in version 0.7.0.

**Comment by rcarmo** [comment]
Weird. I’m using registry2, which shouldn’t have those issues, and couldn’t get it to work yet on 0.7.0...

**Comment by keksecops** [comment]
Any news on this issue ? I'm having the same problem here I guess. 
The output of _crictl info_  regarding registries:

```
...
   "registry": {
      "mirrors": {
        "docker.io": {
          "endpoint": [
            "https://registry-1.docker.io"
          ]
        },
        "xxx.yyy.zzz:5000": {
          "endpoint": [
            "http://xxx.yyy.zzz:5000"
          ]
        }
      },
      "auths": null
    },
...
```

And the error that it gives me :
` pulling image failed: rpc error: code = Unknown desc = failed to resolve image "xxx.yyy.zzz:5000/abc/alpine-curl:latest": no available registry endpoint: failed to do request: Head https://xxx.yyy.zzz:5000/v2/abc/alpine-curl/manifests/latest: http: server gave HTTP response to HTTPS client `

But I can pull the image fine on my machine using docker.
Any advice ?

**Comment by rcarmo** [comment]
> And the error that it gives me :
> pulling image failed: rpc error: code = Unknown desc = failed to resolve image "xxx.yyy.zzz:5000/abc/alpine-curl:latest": no available registry endpoint: failed to do request: Head https://xxx.yyy.zzz:5000/v2/abc/alpine-curl/manifests/latest: http: server gave HTTP response to HTTPS client
> 

I have the exact same situation and error message on 0.7.0, identical config, Docker works fine too.

**Comment by solsson** [comment]
The status of this issue wasn't entirely clear to me, but I can report that with current installer (d8c4f3811e96d75f82bebc82f4ef8f82fbe70637), k3s v0.8.0 and multipass (Ubuntu 18.04.2) I get a **working** insecure registry support box after:

```
INSTALL_K3S_SKIP_START=true ./install.sh
mkdir -p     /var/lib/rancher/k3s/agent/etc/containerd
cat <<EOF >> /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
[plugins.opt]
path = "{{ .NodeConfig.Containerd.Opt }}"

[plugins.cri]
  stream_server_address = "{{ .NodeConfig.AgentConfig.NodeName }}"
  stream_server_port = "10010"

  [plugins.cri.cni]
    bin_dir = "{{ .NodeConfig.AgentConfig.CNIBinDir }}"
    conf_dir = "{{ .NodeConfig.AgentConfig.CNIConfDir }}"

  [plugins.cri.registry]
    [plugins.cri.registry.mirrors]
      [plugins.cri.registry.mirrors."my.registry.local"]
        endpoint = ["http://my.registry.local"]
EOF
service k3s start
#  confirm using k3s crictl info
```

Found in a different issue that the template to base the changes on is in https://github.com/rancher/k3s/blob/master/pkg/agent/templates/templates.go. I guess it will evolve.

**Comment by rcarmo** [comment]
I don’t see the Docker registry listed there. Can you use both your private registry and Docker Hub without adding that specifically?

**Comment by solsson** [comment]
@rcarmo I didn't bother with adding that one as it appears in `crictl info` anyway, and it works:

```
    "registry": {
      "mirrors": {
        "docker.io": {
          "endpoint": [
            "https://registry-1.docker.io"
          ]
        },
        "my.registry.local": {
          "endpoint": [
            "http://my.registry.local"
          ]
        }
      },
      "auths": null
    },
```

**Comment by rcarmo** [comment]
Thanks. I’ll test ASAP on armv7.

**Comment by xiaods** [comment]
@solsson cloud you please share more config steps.

**Comment by solsson** [comment]
@xiaods You don't need to duplicate+modify the config template anymore, since #867. For example: https://github.com/y-stack/ystack/commit/010f778728a6579537868212c97e0f313d4cf55c#diff-80191cda07fc223f8e1185f90d7c6a37

**Comment by xiaods** [comment]
@solsson thanks for your help. got it.

**Comment by erikh** [comment]
Please document this, it took me half a day of googling and starting in on my own ticket to find this issue.

**Comment by VladoPortos** [comment]
So is there a documentation about how to put private insecure registry inside pod, and have it working with cluster ? I'm googling for a week now, and finding little to no answer ( without using external domain )

**Comment by erikh** [comment]
VladoPortos:

edit to taste and put in /etc/rancher/k3s/registries.yaml:

mirrors:
  "10.0.0.220:5000":
    endpoint:
      - "http://10.0.0.220:5000"

then sudo service k3s restart

**Comment by erikh** [comment]
Please note that does not cover actually launching the registry with a
service definition that supports that. That's more of a general topic.

**Comment by VladoPortos** [comment]
Thanks @erikh  I managed to get the registry working with helm help :) and now its running as pod inside cluster, that is as far as I got today, when I return from work I'll continue and try to push, pull, deploy to k3s with the edit you mentioned above. Many thanks.

**Comment by VladoPortos** [comment]
Well no luck, or partial luck at least :D I can push / pull via docker to the private registry, and I can confirm its there:

```
curl -X GET http://192.168.0.189:30500/v2/_catalog 
{"repositories":["vladoportos/python","vladoportos/app"]}
curl -X GET http://192.168.0.189:30500/v2/vladoportos/app/tags/list
{"name":"vladoportos/app","tags":["latest"]}
```
and my /etc/rancher/k3s/registries.yaml: looks like:
```
mirrors:
  "192.168.0.189:30500":
    endpoint:
      - "http://192.168.0.189:30500"
```
The private docker register is running inside of one pod on K3s cluster and the IP is just ip of one of the nodes ( it gets routed to the correct pod all the time ) 

in my app deployment I refer to it as:
image: 192.168.0.189:30500/vladoportos/app:latest

But this fails to pull the image:
`  Warning  Failed     5s         kubelet, cube-04   Failed to pull image "192.168.0.189:30500/vladoportos/app:latest": rpc error: code = Unknown desc = failed to pull and unpack image "192.168.0.189:30500/vladoportos/app:latest": failed to resolve reference "192.168.0.189:30500/vladoportos/app:latest": failed to do request: Head https://192.168.0.189:30500/v2/vladoportos/app/manifests/latest: dial tcp 192.168.0.189:30500: i/o timeout`

Looks like it can't reach it ? ( also why its trying https, that would fail )

**Comment by VladoPortos** [comment]
I have changed the nodes from containerd to docker, and now I have this error message:

`Failed to pull image "192.168.0.189:30500/vladoportos/app:latest": rpc error: code = Unknown desc = Error response from daemon: Get http://192.168.0.189:30500/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

It is driving me nuts

**Comment by cjellick** [comment]
Lots of history here. This is possibly a documentation issue at this point?

**Comment by xiaods** [comment]
please document these tips. thanks a lot.

**Comment by littlebenlittle** [comment]
I'm getting `http: server gave HTTP response to HTTPS client` when trying to pull an image from a local registry. I've mounted the mirrors config in `/etc/rancher/k3s/registries.yaml', but it look like containerd is still trying to make an HTTPS request.

After running `docker-compose up`, pushing an image, and creating a pod with a container that pulls that image, I can inspect the pod and see the above error.

## docker-compose.yaml

```
version: '3'
services:

  server:
    image: 'rancher/k3s'
    command: 'server'
    tmpfs:
      - '/run'
      - '/var/run'
    privileged: 'True'
    environment:
      - 'K3S_TOKEN=${K3S_TOKEN:?err}'
      - 'K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml'
      - 'K3S_KUBECONFIG_MODE=666'
    volumes:
      - 'k3s-server:/var/lib/rancher/k3s'
      - '.:/output'
      - './registries.yaml:/etc/rancher/k3s/registries.yaml:ro'
    ports:
      - '6443:6443'

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - '/run'
    - '/var/run'
    privileged: 'True'
    environment:
    - 'K3S_URL=https://server:6443'
    - 'K3S_TOKEN=${K3S_TOKEN:?err}'
    volumes:
      - './registries.yaml:/etc/rancher/k3s/registries.yaml:ro'

  registry:
    image: 'registry'
    expose:
      - '5000'
    ports:
      - '5000:5000'
    environment:
      - 'REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data'
    volumes:
      - 'registry-data:/data'

volumes:
  k3s-server: {}
  registry-data: {}

```

## registries.yaml

```
mirrors:
  registry:
    endpoint:
      - 'http://registry:5000'

```
