### ISSUE TITLE
CIS 1.6 Scan in Rancher

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1504]
We will need to create a unique set of benchmarks for K3s.
K3s CIS scan in Rancher 2.5.~7~8 should work.

**Comment by davidnuzik** [comment]
Related to CIS story: https://github.com/rancher/k3s/issues/826

**Comment by davidnuzik** [comment]
Related: Docs for k3s cis 1.5: https://github.com/k3s-io/k3s/issues/2541

**Comment by davidnuzik** [comment]
Related (RKE2) https://github.com/rancher/rke2/issues/350

**Comment by cjellick** [comment]
For k3s, we just need the automated testing for CIS 1.6 integrated rancher

**Comment by rancher-max** [comment]
#### Validated using k3s v1.20.6+k3s1 and Rancher v2.5.8-rc12
In Rancher, I deployed CIS Benchmark app v1.0.400 with default values.yaml, which at the time of this writing is:
```
affinity: {}
alerts:
  enabled: false
  metricsPort: 8080
  severity: warning
global:
  cattle:
    clusterName: ''
    systemDefaultRegistry: ''
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.4-rc5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.3-rc5
  sonobuoy:
    repository: rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.16.3
nodeSelector: {}
resources: {}
tolerations: []

```

- 1.20.4 and below gives expected error: `Error validating ClusterScanProfile k3s-cis-1.6-profile-permissive, error: Kubernetes version mismatch, ClusterScanProfile k3s-cis-1.6-profile-permissive is not valid for this cluster's K8s version v1.20.4+k3s1`
- Running permissive scan on cluster that has not gone through the hardening guide is successful, and running hardened scan fails expectedly:
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/55997940/116485280-af286c00-a83f-11eb-85ac-26a755c7095e.png">
Note there are more passes in the hardened. The below three are those listed, and this is because some of those controls are "Manual" and therefore will show up as "Warn" in the 1.6 checks, and the one "Automated" one is marked "Not Applicable" because this check should not apply in a more permissive cluster.

```
- 4.2.7 | Ensure that the --make-iptables-util-chains argument is set to true (Automated) 
- 5.3.2 | Ensure that all Namespaces have Network Policies defined (Manual)
- 5.7.4 | The default namespace should not be used (Manual)
```

- Running both permissive and hardened scans on clusters that have gone through the hardening guide are successful:
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/55997940/116486139-c1a3a500-a841-11eb-8502-ed5a2af140b8.png">

- k3s hardening guide remains the same and is still applicable for 1.6. The checks still pass/fail exactly as mentioned in our docs.
- Validated on Ubuntu, SLES, and Centos8 with both permissive and hardened clusters.
