### ISSUE TITLE
index.yml missing

### ISSUE THREAD

**Issue by mash-graz** [k3s-io/k3s#1564]
**Version:**
k3s version v1.17.3+k3s1 (5b17a175)

**K3s arguments:**
k3s server --disable-agent --no-deploy traefik (in docker-compose environment)

**Describe the bug**
putting this file into `manifests`:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  repo: https://github.com/containous/traefik-helm-chart
  set:
    image.tag: "2.2"
    rbac.enabled: "true"
    ssl.enabled: "true"
```
the package will not be installed and i found is error message in the logs:

```
+ helm_v3 repo add traefik https://github.com/containous/traefik-helm-chart
Error: looks like "https://github.com/containous/traefik-helm-chart" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/containous/traefik-helm-chart/index.yaml : 404 Not Found
```

but installing traefik2 by very similar instructions utilizing the `helm3` CLI works resp. accepts this particular github based repo.

i already reported this flaw to the maintainers of of the helm chart (https://github.com/containous/traefik-helm-chart/issues/121), because it's perhaps easier to figure out a workaround there, but the noticeable difference in the behavior of the CLI tool and the integrated helm chart handling mechanism could indicate some defect on k3s side as well.
