### ISSUE TITLE
Cannot route to services from Traefik ingress

### ISSUE THREAD

**Issue by c16a** [k3s-io/k3s#1646]
**Version:**

k3s version v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**

--docker

**Describe the bug**
When an `Ingress` resource is created against the default Traefik service, the default backend correctly shows a `404 Not Found`, but any new routes give a `504 Gateway Timeout`

**To Reproduce**
I have a 4 node K3s cluster (1 master + 3 workers). The below ports are open in each of them
| Node type | Open ports                                                               |
|-----------|--------------------------------------------------------------------------|
| master    | **6443**(TCP-KUBEAPI), **8472**(UDP-VXLAN), **10250**(TCP-KUBELET), **30000-32767**(TCP) |
| worker    | **8472**(UDP-VXLAN), **10250**(TCP-KUBELET), **30000-32767**(TCP)                    |

The master node is in one Auto Scaling Group (ASG) on AWS, and the 3 worker nodes are in another (ASG). Clustering is successful, so I guess peering ports are fine.

```
kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"
---
kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  selector:
    app: apple
  ports:
    - port: 5678 # Default port for image
---
kind: Pod
apiVersion: v1
metadata:
  name: banana-app
  labels:
    app: banana
spec:
  containers:
    - name: banana-app
      image: hashicorp/http-echo
      args:
        - "-text=banana"
---
kind: Service
apiVersion: v1
metadata:
  name: banana-service
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fruits-traefik-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /apple
            backend:
              serviceName: apple-service
              servicePort: 5678
          - path: /banana
            backend:
              serviceName: banana-service
              servicePort: 5678
```

**Expected behavior**

On the master node, the below works
```
curl -X <master-ip>:80
404 page not found
```
```
curl -X <master-ip>:80/apple
apple
```

**Actual behavior**

Below times out
```
curl -X <master-ip>:80/apple
```

**Additional context / logs**

All pods of `apple` and `banana` are scheduled on other nodes. So I am pretty sure it is a networking / firewall issue.

Can someone help?
