### ISSUE TITLE
Ingress only works on the nodes that happen to run the sole traefik pod

### ISSUE THREAD

**Issue by ocisly** [k3s-io/k3s#1684]
**Version:**

```
k3s version v1.17.4+k3s1 (3eee8ac3)
```

**K3s arguments:**
(none)

**Describe the bug**

Traefik only responds to traffic on a single node. If the cluster consists of multiple nodes, most of them do not accept external traffic.

**To Reproduce**

1. Install the K3s master node:
     ```
    curl -sfL https://get.k3s.io | sh -
    ```
2. Install a K3s worker node: 
    ```
    curl -sfL https://get.k3s.io | K3S_URL=master_url K3S_TOKEN=token sh -
    ```
3. Make an HTTP request to the master node
    ```
    $ curl master_url
    404 page not found
    ```
    This is the expected behaviour, since no ingress exists yet for the route.

4. Make an HTTP request to the worker
    ```
    $ curl worker_url
    curl: (7) Failed to connect to <IP ADDRESS> port 80: Operation timed out
    ```
    This is unexpected.

**Expected behavior**
All nodes in the cluster should always respond to HTTP traffic.

**Actual behavior**
Only one of the nodes in the cluster is able to receive traffic.

**Additional context / logs**
K3s installs traefik from a [helm chart](https://github.com/helm/charts/tree/master/stable/traefik). From the README of that chart:

> ## Prerequisites
> You are deploying the chart to a cluster with a cloud provider capable of provisioning an external load balancer (e.g. AWS or GKE)

In K3s, traefik starts out as a **deployment** that runs a single replica. That pod will often be running on the master to begin with, but once worker nodes join the cluster it may get rescheduled (you can force this by deleting the pod). Due to this bug, it is not possible to reliably serve HTTP traffic using a vanilla K3s cluster of more than 1 node.

Possible workarounds:
* document the issue prominently
* `kubectl scale deployment/traefik --replicas=<insert a large number and hope for the best>`
* Install k3s using `--no-deploy traefik` and set up a more appropriate ingress controller yourself
*  mess with pod anti-affinities or something

How to fix the issue:
* Run traefik as a daemonset (has been proposed multiple times for the helm chart, but was rejected by the Traefik team in https://github.com/helm/charts/pull/11813#issuecomment-530001942)
* Don't ship K3s with traefik #1466 (got reverted in #1519)

**Comment by brandond** [comment]
This is not a bug, this is how kubernetes is designed to work. High availability for doesn't mean that every cluster member hosts a service endpoint.  If you don't have an external load balancer available to drive traffic to the correct nodes, you can use something like MetalLB to serve Traefik on a virtual IP that is hosted by whichever node is running the pod.

**Comment by ocisly** [comment]
Thanks for the response. I agree that this isn't a bug in Kubernetes. I don't presume to speak for other user of K3s, but personally I was expecting this to work out of the box.

In case anyone else is facing the same issue, the way I got around this was to install K3s with `--disable traefik`, then deployed the [haproxy kubernetes ingress helm chart](https://github.com/haproxytech/helm-charts/tree/master/kubernetes-ingress) from the following manifest:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: haproxy-ingress
  namespace: kube-system
spec:
  chart: kubernetes-ingress
  repo: https://haproxytech.github.io/helm-charts
  targetNamespace: kube-system
  set:
    controller.kind: DaemonSet
    controller.service.type: LoadBalancer
```

**Comment by samirsss** [comment]
@brandond would it be possible that for k3s with multiple masters there is an easier way to have traefik running on all the master nodes to not have a single point of failure and a slower failover time. 

The more I'm trying to look at k3s from HA/failover perspective (with 2 or more master nodes)  , I find that there are gaps that will cause a failure or a very long downtime (which isnt true HA). 

One way to do this is wherever we have the taint node-role.kubernetes.io/master=true run traefik as a daemonset. This way we atleast dont have downtimes there.

Similar comment applies to core-dns, since we can do with metrics-server taking time to failover.

If folks use the local-path-provisioner from k3s then it would apply there to.

**Comment by brandond** [comment]
@samirsss you might read through the discussion here: https://github.com/containous/traefik/issues/5426#issuecomment-534154022

**Comment by samirsss** [comment]
Thanks @brandond I was able to get it working through using pod antiaffinity and replicas. Just had to patch Traefik and Core-dns after deployment to get it to do what we needed.

**Comment by dirtbag** [comment]
So Im trying to run k3s on 2 servers, and I have run into this issue where the traffic gets load-balanced, but only works on one of the servers.. I have tried the install with the --no-deploy traefik and installed the metallb.. but i still seem to have the same issue?
does anyone have any updates on this?

**Comment by mousiefasil** [comment]
Hi have you read the discussion in [issue](https://github.com/rancher/k3s/issues/1613) ? This helped me to get that routing problem fixed.

**Comment by dirtbag** [comment]
trying it now

**Comment by cawoodm** [comment]
I am having the same issue with a fresh 2-node K3S installation. By default only one pod of the deployment `traefik` exists and if I reboot that node then none of my services (via ingress) are accessible because the ingress controller is gone.

If I scale the deployment to 2 replicas the problem is solved temporarily until I reboot both servers and then the replica count goes back to 1. How can I persist the replica count of the traefik ingress controller (deployment)?

```
kubectl scale --replicas=2 deployment/traefik -n kube-system
```

**Comment by Cory-Christensen** [comment]
> I am having the same issue with a fresh 2-node K3S installation. By default only one pod of the deployment `traefik` exists and if I reboot that node then none of my services (via ingress) are accessible because the ingress controller is gone.
> 
> If I scale the deployment to 2 replicas the problem is solved temporarily until I reboot both servers and then the replica count goes back to 1. How can I persist the replica count of the traefik ingress controller (deployment)?
> 
> ```
> kubectl scale --replicas=2 deployment/traefik -n kube-system
> ```

I was able to configure the helm chart values to set replicas & podAntiAffinity.

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  set:
    controller.replicaCount: 3
  valuesContent: |-
      deployment:
      replicas: 3
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - traefik
          topologyKey: kubernetes.io/hostname
```

**Comment by cawoodm** [comment]
Yep, that's what we did. Other options are:

* Edit /var/lib/rancher/k3s/server/manifests/traefik.yaml
* Don't install traefik with k3s but deploy it manually as a DaemonSet

**Comment by asreich** [comment]
Commenting with links because I found myself here again feeling surprised this wasn't addressed natively in k3s yet. But as of v1.19.0+k3s1 it has with the [HelmChartConfig CRD](https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig). The "HA" piece the mentioned here https://github.com/traefik/traefik/issues/5426#issuecomment-534154022 is specific to a LetsEncrypt integration and there should be no issues in functionality related to increasing the replica counts of these pods.

Related issue: #1317

**Comment by VuiDJi** [comment]
More simple traefik-config.yaml:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
      deployment:
        kind: DaemonSet
```
