### ISSUE TITLE
The "/bin/k3s server" command is not generating a "./kubeconfig.yaml" file when "--bind-address 0.0.0.0" is included ...

### ISSUE THREAD

**Issue by nmvega** [k3s-io/k3s#1791]
Hello Friends:

Using the below `docker-compose.yaml` file (available [here](https://github.com/rancher/k3s/blob/master/docker-compose.yml)), if I modify the directive `command: server` to include this `--bind-address 0.0.0.0` (as shown), the service no longer generates a `./kubeconfig.yaml` file when started up (i.e. when I run `docker-compose up`).

Now if I remove the modification, it generates the file fine.

Note that in either case, the services themselves start fine; only the `./kubeconfig.yaml` is affected (i.e not generated when I append `--bind-address 0.0.0.0`). Also note that I'm using the latest `rancher/k3s:latest` image available on `dockerhub` (downloaded today). I didn't try building from the source `Dockerfile` because I don't it will make a difference.

I found this out by accident today, when trying to narrow `--bind-address` to just the interface I need.

Any ideas? Thank you in advance! =:)

```
version: '3'
services:

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
   #command: server                         # Before
    command: server --bind-address 0.0.0.0  # After
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=${K3S_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:?err}

volumes:
  k3s-server: {}
```
