### ISSUE TITLE
hostPath type check failed: dir/file is not a file/dir

### ISSUE THREAD

**Issue by theAkito** [k3s-io/k3s#1810]
**Version:**

`k3s version v1.17.4+k3s1 (3eee8ac3)`

**K3s arguments:**

`k3s server --tls-san 1.2.3.4 --tls-san domain --write-kubeconfig-mode 644`

**Describe the bug**

```
      volumes:
        - name: customer
          hostPath:
            path: /instance/{{ .Release.Namespace }}/customerProfile.json
            type: File
```
If the `type` is empty, the system will scream, that `customerProfile.json` is not a directory!
If the `type` is set to `File`, the system will scream, that `customerProfile.json` is not a file!

So if it is neither a file, nor a directory, what kind of alien breed is it?

Tested this thoroughly and this is extremely frustrating because this error is extremely stupid. 
Just let me mount the damn file.

**To Reproduce**

1. Mount a File as a volume within a Helm template.
a. With type check on: File is not a `file`!
b. With type check off: File is not a `directory`!
 
**Expected behavior**

The system mounting a file as a file without complaints!

**Actual behavior**

**Additional context / logs**

This has happened so many times before on standard Kubernetes. However, the fix of removing the type check does not work on k3s.

Partial `deployment.yaml`:
```
...
      volumes:
        - name: customer
          hostPath:
            path: /instances/{{ .Release.Namespace }}/customerProfile.json
            type: File # Again: does not matter, both options fail
...
          volumeMounts:
            - name: customer
              mountPath: /customer/profile.json
...
```

k3s error with type check off:
```
Error: failed to create containerd task: OCI runtime create 
failed: container_linux.go:346: starting
 container process caused 
"process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting 
\\\"/instances/test-1/customerProfile.json\\\" 
to rootfs \\\"/run/k3s/containerd
/io.containerd.runtime.v2.task/k8s.io/test/rootfs\\\" 
at \\\"/run/k3s/containerd
/io.containerd.runtime.v2.task/k8s.io/test/rootfs/customer/profile.json\\\" 
caused \\\"not a directory\\\"\"": unknown
```
k3s error with type check on, as `File`:
```
Unable to attach or mount volumes: unmounted volumes=[customer], 
unattached volumes=[app-prep default-token-f86kj app-archive 
app-data app-webdav app-random customer]: timed out waiting for the condition
```
and
```
MountVolume.SetUp failed for volume "customer" :
hostPath type check failed: /instances/app-210-rc3/customerProfile.json is not a file
```
(Wrapped, for easier readability.)
