### ISSUE TITLE
Using "local-path" in persistent volume requires sudo to edit files on host node?

### ISSUE THREAD

**Issue by leeallen337** [k3s-io/k3s#1823]
**Version:**
k3s version v1.18.2+k3s1 (698e444a)

**K3s arguments:**
Installed with `curl -sfL https://get.k3s.io | sh -`

**Describe the bug**
When running a persistent volume with a persistent volume claim using [local-path](https://rancher.com/docs/k3s/latest/en/storage/), the files on the host node are read only and require `sudo` to edit

**To Reproduce**

```
// persistent-volume.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo
  labels:
    directory: some-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: local-path
  local:
    path: /home/<username>/configuration
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ubuntu
  persistentVolumeReclaimPolicy: Retain
```

```
// persistent-volume-claim.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: some-storage
```

```
// service.yaml

apiVersion: v1
kind: Service
metadata:
  name: foo-service
  labels:
    foo: baz
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    foo: baz
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP

```

```
// deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
  labels:
    foo: baz
spec:
  replicas: 1
  selector:
    matchLabels:
      foo: baz
  template:
    metadata:
      labels:
        foo: baz
    spec:
      volumes:
        - name: foo-config
          persistentVolumeClaim:
            claimName: foo-claim
      containers:
        - name: foo
          image: <some image>
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: foo-config
              mountPath: /config

```

**Expected behavior**
When I have files in the host node's `/configuration` directory without the deployment and persistent volumes running. I can edit the files fine without `sudo`. I thought it would be more like sharing files in `volume`s in Docker where, when editing files on the host machine, no privileges are required.

**Actual behavior**
Once I run the manifests and the `/configuration` directory is being shared as a persistent volume, when editing the files it states the files are read only and require `sudo` to write and save.

**Additional context / logs**
Let me know if this is the actual expected behavior. I also tried to sanitize my manifests a little so if anything is confusing let me know
