### ISSUE TITLE
k3s use containerd as container runitime:  statefulset pod hostname was not a fqdn style domain name

### ISSUE THREAD

**Issue by zengyongjie** [k3s-io/k3s#1834]
**Version:**
k3s version v1.17.3+k3s1 (5b17a175)

**K3s arguments:**
default

**Describe the bug**
I deployed apache flink cluster in k3s cluster.
Flink jobmanager is Deployment, Flink taskamanger is statefullset.
Flink taskmanager registe to Flink jobmanger with a FQDN style domain name.

In normal circumustance( k3s using docker as container runtime), It is like this:
![image](https://user-images.githubusercontent.com/62204644/82973322-a1ec7700-a009-11ea-906b-9901af801396.png)

instance name was a full FQDN name.  `statefullset-pod-1.headless-service-name`

But when I use containerd as k3s contaniner runtime, It is liske this:

absolutely the instance name is just the pod name without headless service name(which was expected to), so the jobmanager cannot communicate with taskmanager because it cannot resolve the hostname just with pod name.    `statefullset-pod-1`
![image](https://user-images.githubusercontent.com/62204644/82973438-f68ff200-a009-11ea-96ee-41ad16a0270a.png)

**To Reproduce**
Install the k3s cluster using containerd as container runtime,   and using my chart can reproduce this problem.

**Expected behavior**
it was normal when using docker as container runtime

**Actual behavior**
It was not normal when using containerd as container runtime.

**Comment by zengyongjie** [comment]
[root@hjg1 ~]# kubectl -n edge exec flink-taskmanager-1 -- hostname -f
flink-taskmanager-1.flink-taskmanager-headless.edge.svc.cluster.local
[root@hjg1 ~]# kubectl -n edge exec flink-taskmanager-1 -- hostname
flink-taskmanager-1
[root@hjg1 ~]#


it seems like when using docker , it used the `hostname -f`, which returns a full fqdn style domain name to register.

but with containerd,   it uses a short hostname to register to the cluster.

**Comment by brandond** [comment]
Can you show the manifest for the headless service and statefulset? I suspect that there's some sort of mismatch - most likely the headless service's name doesn't match the subdomain on the statefulset pods.

From the docs: 
> If there exists a headless service in the same namespace as the pod and with the same name as the subdomain, the cluster’s DNS Server also returns an A or AAAA record for the Pod’s fully qualified hostname. For example, given a Pod with the hostname set to “busybox-1” and the subdomain set to “default-subdomain”, and a headless Service named “default-subdomain” in the same namespace, the pod will see its own FQDN as “busybox-1.default-subdomain.my-namespace.svc.cluster-domain.example”. DNS serves an A or AAAA record at that name, pointing to the Pod’s IP. Both pods “busybox1” and “busybox2” can have their distinct A or AAAA records.

**Comment by zengyongjie** [comment]
@brandond Hi, following are my files:

headless service:
```yaml
apiVersion: v1
kind: Service
  name: flink-taskmanager-headless
spec:
  clusterIP: None
  ports:
  - name: data
    port: 6121
    protocol: TCP
    targetPort: 6121
  - name: rpc
    port: 6122
    protocol: TCP
    targetPort: 6122
  - name: query
    port: 6125
    protocol: TCP
    targetPort: 6125
  selector:
    app: flink-taskmanager
  sessionAffinity: None
  type: ClusterIP

```


statefullset:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-taskmanager
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  selector:
    matchLabels:
      app: flink-taskmanager
  serviceName: flink-taskmanager-headless
  template:
    metadata:
      labels:
        app: flink-taskmanager
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - $FLINK_HOME/bin/taskmanager.sh start; while :; do if [[ -f $(find log -name
          '*taskmanager*.log' -print -quit) ]]; then tail -f -n +1 log/*taskmanager*.log;
          fi; done
        image: my.registry.com/big-data/flink:master-20200224-230
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 30
        livenessProbe:
          failureThreshold: 12
          initialDelaySeconds: 100
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: rpc
          timeoutSeconds: 3
        name: taskmanager
        ports:
        - containerPort: 6122
          name: rpc
          protocol: TCP
        - containerPort: 6121
          name: data
          protocol: TCP
        - containerPort: 6125
          name: query
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 3
          tcpSocket:
            port: rpc
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "2"
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - mountPath: /opt/flink/conf/
          name: flink-config-volume
        workingDir: /opt/flink
      volumes:
      - configMap:
          defaultMode: 420
          name: flink-config
        name: flink-config-volume
```

**Comment by brandond** [comment]
Do you see any different behavior if you set the subdomain on the StatefulSet podSpec? Setting the serviceName **should** do it, but I'm curious what you get.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-taskmanager
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  selector:
    matchLabels:
      app: flink-taskmanager
  serviceName: flink-taskmanager-headless
  template:
    metadata:
      labels:
        app: flink-taskmanager
    spec:
      subdomain: flink-taskmanager-headless
      containers:
        - /bin/bash
<...rest of your manifest...>
```
