### ISSUE TITLE
Upgrade from v1.17.4+k3s1 to "stable" on Alpine failing

### ISSUE THREAD

**Issue by hamid-elaosta** [k3s-io/k3s#1851]
**Version:**
v1.17.4+k3s1 (3eee8ac3)

**K3s arguments:**
`server --no-deploy servicelb`

**Describe the bug**
Installed the upgrade controller following documentation [here](https://rancher.com/docs/k3s/latest/en/upgrades/automated/), created and applied the server and agent plans as detailed below and wait. Checking the job log shows upgrade script failing, details below.

**To Reproduce**
Follow instructions at: https://rancher.com/docs/k3s/latest/en/upgrades/automated/ to upgrade from a working cluster on Alpine to "stable" channel.

**Expected behavior**
Upgrade to stable (currently v1.18.2+k3s1)

**Actual behavior**
Upgrade doesn't happen after some time, checked job logs to find script errors shown below.

**Additional context / logs**
Deployed the controller using: kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/v0.4.0/system-upgrade-controller.yaml

apply server plan:
```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
```
apply agent plan:
```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
```
Server job error logs:
```
kubectl -n system-upgrade logs apply-server-plan-on-alpine-1-with-3c86883a4bc8d1001df268-4x2pk 
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E 'k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver)'
+ awk '{print $1}'
+ K3S_PID='2732
2738'
+ '[' -z '2732
2738' ]
+ info 'K3S binary is running with pid 2732
2738'
+ echo '[INFO] ' 'K3S binary is running with pid 2732
2738'
[INFO]  K3S binary is running with pid 2732
2738
+ cat /host/proc/2732 2738/cmdline
+ awk '{print $1}'
+ head -n 1
cat: read error: Is a directory
cat: can't open '2738/cmdline': No such file or directory
+ K3S_BIN_PATH=
+ '[' '2732
2738' '==' 1 ]
+ '[' -z  ]
+ fatal 'Failed to fetch the k3s binary path from process 2732
2738'
+ echo '[ERROR] ' 'Failed to fetch the k3s binary path from process 2732
2738'
[ERROR]  Failed to fetch the k3s binary path from process 2732
2738
+ exit 1
```
