### ISSUE TITLE
Customize servicelb daemonset tolerations (traefik)

### ISSUE THREAD

**Issue by david-martyn-ford** [k3s-io/k3s#1988]
**Is your feature request related to a problem? Please describe.**
Unable to schedule servicelb pods on nodes which have user defined taints. 

I am currently running a multi arch k3s cluster which consists of both amd64 and arm64. A taint has been added to the arm64 nodes to stop pods being scheduled onto those nodes unintentionally.

This results in the pods for the default traefik ingress controller only being scheduled on a couple of nodes. 

Node taint:
```
kubectl taint nodes <worker-node> kubernetes.io/arch=arm64:NoSchedule
```

Deployment toleration example:
```
tolerations:
  - key: kubernetes.io/arch
    operator: Equal
    value: arm64
    effect: NoSchedule
```
 
**Describe the solution you'd like**
I would like to be able to add user defined tolerations when creating the daemonset.

If there is an alternative way to do this please let me know, I couldn't see anything on it.

**Comment by louiznk** [comment]
@david-martyn-ford is it a trouble with this taint on <master-node> ?
```
kubectl taint nodes <master-node>  node-role.kubernetes.io/master=effect:NoSchedule
```
(see #1989 and his fix #1990 )

**Comment by david-martyn-ford** [comment]
@louiznk Unfortunately not, ultimately it is the same problem, but with a custom or user defined taint instead of the node role taint.

My arm64 nodes have the following taint:
`kubectl taint nodes <worker-node> kubernetes.io/arch=arm64:NoSchedule`

Applications which I choose to run on the arm64 nodes then have the following toleration:
```
tolerations:
  - key: kubernetes.io/arch
    operator: Equal
    value: arm64
    effect: NoSchedule
```

This works fine for my applications but the servicelb doesn't take into account user defined tolerations, so when the daemonset is created it can't be scheduled on the arm64 nodes.

**Comment by louiznk** [comment]
I understand. It's not very difficult to add some toleration on klipper but it's actually a programatic way. 

I imagine that if you want to add some "standard" taint the k3s team could be agree, but perhaps if it's custom taint toleration they would prefere to use an external way to configure this. They could answer to this before making some dev.

**Comment by brandond** [comment]
I believe this was fixed in #1892

**Comment by raptium** [comment]
Is there any update on this issue? I have the same problem with a multi arch k3s cluster.

**Comment by brandond** [comment]
Rather than tainting the arm64 nods as NoSchedule, the proper way to do this would be to put a nodeSelector on your workload pod spec:
```yaml
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: test
          image: test
```
