### ISSUE TITLE
registry mirror of * does not override "docker.io" default

### ISSUE THREAD

**Issue by oskapt** [k3s-io/k3s#2088]
**Environmental Info:**
K3s Version: v1.18.6+k3s1

**Describe the bug:**
A registry mirror config with `*` as the key is added, and does not supersede the configuration for `docker.io`

**Steps To Reproduce:**

drop this into `/etc/rancher/k3s/registries.yaml`:

```
mirrors:
  "*":
    endpoint:
      - "https://registry.cl.monach.us"
```

**Expected behavior:**
The expected behavior is that all queries go through the cache.

**Actual behavior:**
A default configuration is left in the containerd config, along with the new one:
```
    "registry": {
      "mirrors": {
        "*": {
          "endpoint": [
            "https://registry.cl.monach.us"
          ]
        },
        "docker.io": {
          "endpoint": [
            "https://registry-1.docker.io"
          ]
        }
      },
      "configs": null,
      "auths": null
    },
```

As a result, anything from Docker Hub is *not* pulled through the cache. In order to make this work, a second entry has to be added:
```
mirrors:
  "docker.io":
    endpoint:
      - "https://registry.cl.monach.us"
  "*":
    endpoint:
      - "https://registry.cl.monach.us"
```
