### ISSUE TITLE
Change localhost by master ip in config file

### ISSUE THREAD

**Issue by itwars** [k3s-io/k3s#212]
Hi,
Could you please change localhost by master ip il config file:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJ ....
    server: https://192.168.1.26:6443
                              ^^^^^^^^^^^^
                               localhost
```

To avoid any change when scp to remote management computer:
```
scp debian@192.168.1.26:/etc/rancher/k3s/k3s.yaml /home/adm/.kube/config
```

Many thx
