### ISSUE TITLE
Registry mirror mechanic considerations 

### ISSUE THREAD

**Issue by stefanvangastel** [k3s-io/k3s#2161]
**Is your feature request related to a problem? Please describe.**
We are in an offline air-gap environment using Gitlab as registry on `registry.company.io` and have a `docker-images` group with a `rancher` project containing all the Rancher infra images.

So to pull images, this is the absolute tag: `registry.company.io/docker-images/rancher/coredns-coredns:1.6.3`. the `registries.yml` ([docs](https://rancher.com/docs/k3s/latest/en/installation/private-registry/)) looked like this and **DID NOT** work:

```yml
mirrors:
  docker.io:
    endpoint:
      - "https://registry.company.io/docker-images"
```

Next, we deployed a Harbor instance under `harbor.company.io` and created a root level project called `rancher`. We then populated that registry with the images creating absolute tags like: `harbor.company.io/rancher/coredns-coredns:1.6.3`

The `registries.yml` for this setup looks like this and DOES WORK:

```yml
mirrors:
  docker.io:
    endpoint:
      - "https://harbor.company.io"
```

So we now expect an issue that occurs when providing a deeper path then the root of the registry. I can confirm hat creating a sub-project in Harbor called `docker-images` and pushing `rancher/coredns-coredns:1.6.3` within that `docker-images` creates the same problem we have with Gitlab.

We then created a `rancher` root level Gitlab group and child projects for the images to confirm the subpath is the actual issue as we speak.

And now we can confirm that using a Gitlab group called `rancher` and creating a project for each of the images (which is a hell of a job) so we get `registry.company.io/rancher/coredns-coredns:1.6.3` and a `registries.yml` like this:

```yml
mirrors:
  docker.io:
    endpoint:
      - "https://registry.company.io"
```

**WORKS!**

**Describe the solution you'd like**
So its clear the subdirectory or extra namepath is causing issues. 

Our suggestion is to make it work more like Rancher Server that accepts a `systemDefaultRegistry` (Helm) `CATTLE_SYSTEM_DEFAULT_REGISTRY` (Docker) which on its turn accepts paths like `registry.company.io/docker-images`.

In k3s this is already done for the pause image with the `--pause-image` argument when running k3s. A default registry argument could fix this entire issue just like it does for Rancher Server and provide flexibility for users to put Rancher / k3s images in deeper levels of a registry. 

**Additional context**
This issue was discussed on Slack in #k3s and in depth with Sheldon Lo-A-Njoe.
