### ISSUE TITLE
glusterfs provisioner not found

### ISSUE THREAD

**Issue by PPCM** [k3s-io/k3s#2282]
**Environmental Info:**
K3s Version: k3s version v1.19.1+k3s1 (b66760fc)

Node(s) CPU architecture, OS, and Version: Linux cluster01 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
3 workers

**Describe the bug:**
no volume plugin matched name: kubernetes.io/glusterfs

**Steps To Reproduce:**
Install GlusterFS servers and Heketi

Add a storage class with a provider : 
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gluster-heketi
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  resturl: "http://cluster01:8080"
  restuser: "admin"
  secretName: "Secret_Password"
  secretNamespace: "default"
  volumetype: "replicate:3"
  volumenameprefix: "k8s-dev"
  clusterid: "d439d81257011a1e7a2d300197b3d1ed"
```
Create a persistent volume claim
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
```

No volume is created

But in kubernetes official document GlusterFS type is supported by default since v1.6

**Additional context / logs:**
Log file

```
Sep 18 23:30:02 cluster01 k3s[2555]: I0918 23:30:02.737904    2555 event.go:291] "Event occurred" object="default/gluster-pvc" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="no volume plugin matched name: kubernetes.io/glusterfs"
```
