### ISSUE TITLE
Kube-proxy couldn't route to node name and port

### ISSUE THREAD

**Issue by birdkiller** [k3s-io/k3s#2297]
**Environmental Info:**
K3s Version: v1.18.8+k3s1 (6b595318) / v1.16.13+k3s1 (b720367f)

Node(s) CPU architecture, OS, and Version: 
test1 with k3s 1.18: Linux ubuntu-workspace 4.4.0-131-generic
test2 with k3s 1.16: Linux dev-mng-1 3.10.0-957.el7.x86_64 

Cluster Configuration:
both test 1 master 0 workers

**Describe the bug:**
K3S cluster could not provide the route to a hostPort or nodePort through kube-apiserver and kube-proxy. Such as:
```
https://[api-server-ip]:6443/api/v1/nodes/[node-name]:[port]/proxy/[sub-path]
```

**Steps To Reproduce:**

- Setup hostname `echo ubuntu-workspace >/etc/hostname && hostname ubuntu-workspace`
- Installed K3s:  `curl -sfL https://get.k3s.io | sh - `
- Create ns: `k3s kubectl create ns kce-system`
- Create obj: `k3s kubectl create -f ds.yml` the yaml content is following:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kce-system
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - args:
        - --web.listen-address=0.0.0.0:9100
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
        - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
        image: quay.io/prometheus/node-exporter:v0.18.1
        imagePullPolicy: IfNotPresent
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/sys
          name: sys
        - mountPath: /host/proc
          name: proc
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /sys
          type: ""
        name: sys
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: kce-system
spec:
  ports:
  - name: node-exporter-cluster
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: node-exporter
  sessionAffinity: None
  type: ClusterIP
```
- Access the port with browser or postman(fill the authorization with username and password you get in the /etc/rancher/k3s/k3s.yaml ): `https://172.20.158.87:6443/api/v1/nodes/ubuntu-workspace:9100/proxy/metrics`

**Expected behavior:**

http response state 200 and get metrics

**Actual behavior:**

```Error trying to reach service: 'dial tcp: lookup ubuntu-workspace: Try again'```

**Additional context / logs:**

- If I use services instead, it works!
```
https://172.20.158.87:6443/api/v1/namespaces/kce-system/services/node-exporter:9100/proxy/metrics
```
- If I put a hosts in /etc/hosts, it works eigther!
```
echo 127.0.0.1 ubuntu-workspace  >> /etc/hosts
```
- But it works in the original k8s cluster without any hosts.
