### ISSUE TITLE
Unable to use JSON key with GCR

### ISSUE THREAD

**Issue by Stono** [k3s-io/k3s#2367]
Exactly the same issue as: https://github.com/rancher/k3s/issues/1610 however that is closed, so creating a new issue for visibility.

We still get this issue too; the json key is being incorrectly encoded with "{" rather than '{" so we can't use gcr.

We've tried v1.16 and latest

**Comment by brandond** [comment]
Can you attempt the modification suggested here: https://github.com/rancher/k3s/issues/1610#issuecomment-705694804

**Comment by Stono** [comment]
We haven't attempted that, what we did in the end is remove the use of single quotes and escape the doubles, eg `'{"type"` became `"{\"type\"`.

So we've "worked around" it, but it's less than ideal for new folks coming along, they'd expect the yaml in `registries.yaml` to be parsed quite literally

**Comment by brandond** [comment]
It is parsed literally as a string when we parse the yaml, but apparently the toml format doesn't like having it specified as an escaped string as golang's %q format string outputs it?

**Comment by simt2** [comment]
For anyone coming across this using k3os and writing `registries.yaml` via `write_files`, as per k3os v0.11.1 you need to escape those quotes *thrice*:

```yaml
write_files:
- encoding: ""
  content: |-
    configs:
      eu.gcr.io:
        auth:
          username: _json_key
          password: "{\\\"type\\\":\\\"service_account\\\",\\\"project_id\\\":\\\"project-foo\\\"}"
  owner: root
  path: /etc/rancher/k3s/registries.yaml
  permissions: '0755'
``` 
(I omitted the sensitive parts of the password field.)

**Comment by ejose19** [comment]
For those running `k3s` in GCE, it may be desirable to use the service account of the instance instead of managing key files, I got it working following the pointer on https://github.com/k3s-io/k3s/issues/3314#issuecomment-840067308, here are the files I used:

`credential-provider-config.yaml`
```yaml
kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1alpha1
providers:
  - name: custom-credential-provider
    matchImages:
      - "*.gcr.io"
      - "gcr.io"
    defaultCacheDuration: "60m"
    apiVersion: credentialprovider.kubelet.k8s.io/v1alpha1
```

`custom-credential-provider` (must be marked as executable)
```sh
#!/bin/sh

set -e

password=$(gcloud auth print-access-token)

cat <<EOF
{
  "kind": "CredentialProviderResponse",
  "apiVersion": "credentialprovider.kubelet.k8s.io/v1alpha1",
  "cacheKeyType": "Registry",
  "cacheDuration": "60m",
  "auth": {
    "*.gcr.io": { "username": "_dcgcloud_token", "password": "$password" },
    "gcr.io": { "username": "_dcgcloud_token", "password": "$password" }
  }
}
EOF
```

supposing the files were placed in `/etc/rancher/k3s/` & `/usr/bin/` respectively, install `k3s` with

```sh
export INSTALL_K3S_CHANNEL=latest
export INSTALL_K3S_EXEC="
  server \
  --kubelet-arg feature-gates=KubeletCredentialProviders=true \
  --kubelet-arg image-credential-provider-config=/etc/rancher/k3s/credential-provider-config.yaml \
  --kubelet-arg image-credential-provider-bin-dir=/usr/bin/
"

curl -sfL https://get.k3s.io | sh -
```
