### ISSUE TITLE
had to reinstall k3s after someone turned on firewalld - Centos7

### ISSUE THREAD

**Issue by MikeCongdon1** [k3s-io/k3s#2394]
**Environmental Info:**
K3s Version:  k3s version v1.18.9+k3s1 (630bebf9)

Node(s) CPU architecture, OS, and Version: 
Centos 7  3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single node running as master/worker

**Describe the bug:**
Ingress Service didn't restore operation after fixing firewall settings on the server.

**Steps To Reproduce:**
On Centos7, while running multiple services with traefik as ingress, as well as a declared ingress to route the services by url:
turn on firewalld on the server. (I know that firewalld with Centos7 is not compatible with k3s, other admin didn't realize the issue yet).
Turn off firewalld and restored iptables as the functioning firewall, the service did not restore.
from the server, curl a valid url:
`curl mydomain.local`
and, get connection refused mydomain.local:80

I then deleted and reapplied my ingress (not traefik, my declared one). it looks like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: mydomain.local
    http:
      paths:
      - path: /
        backend:
          serviceName: goservice
          servicePort: 80
```
I checked kubectl logs on my running pods and they all looked good (except for not having any external / inbound traffic, as expected here).

I also tried restarting k3s:
`systemctl restart k3s`

**Expected behavior:**
I expected my service to start working again after fixing the firewall settings.
I also expected that I might need to restart k3s.

**Actual behavior:**
None of the above steps brought my service back online.
I had to run ` k3s-uninstall.sh ` followed by the installation script I had initially used: `curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 -d /home/k3s`

**Additional context / logs:**
I recognize that this may be a bug with traefik, or with k8s & not so much with k3s.
Is there a better way to solve my problem should it come up in the future (rather than reinstalling k3s?)
