### ISSUE TITLE
Missing logs

### ISSUE THREAD

**Issue by adi90x** [k3s-io/k3s#2745]
Hello, 

Since v1.19 version , it seems I can't get any logs from any pods, kubectl logs do not return any error : just empty.
Is there anything I can do to debug that ? 

Regards,

**Comment by brandond** [comment]
I'm not aware of any issue that would cause logs to be unavailable. Can you share any more information about what you've tried, or error messages that you're getting?

**Comment by adi90x** [comment]
Hello @brandond ,
Not sure what kind of error message I can send , everything seems fine , pod are up and running fine, except logs don't seems to be available... 
For example, I have run this file : 

```
apiVersion: v1
kind: Pod
metadata:
  name: logging-app-pod
spec:
  containers:
  - name: example
    image: busybox
    args: [/bin/sh, -c, 'while true; do echo $(date); sleep 1; done']

```
Which is supposed to just run date to stdout , however when doing `kubectl logs logging-app-pod` it don't show anything...
So either, it can't connect to the pod logs ? or I am redirecting stdout to something without even noticing it ? 
Any debug/test/idea would be appreciated :)

Thanks a lot
