### ISSUE TITLE
cert-manager fails to work with flannel+ipsec

### ISSUE THREAD

**Issue by cjyar** [k3s-io/k3s#2753]
**Environmental Info:**
K3s Version: 
k3s version v1.19.5+k3s2 (746cf403)

Node(s) CPU architecture, OS, and Version: 
Linux node01 4.4.167-1213-rockchip-ayufan-g34ae07687fce #1 SMP Tue Jun 18 20:44:49 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
1 master, 4 workers. /var is on USB flash. Using the default storage backend. Cluster was initialized with `--flannel-backend=ipsec`.

**Describe the bug:**
After cert-manager is loaded, it fails to validate a simple ClusterIssuer.
I think this is because the apiserver can't contact the coreDNS pod over the encrypted flannel connection, but that's just a hunch.

**Steps To Reproduce:**
1. `K3S_TOKEN=$token ./k3s.sh server --disable-local-storage --flannel-backend=ipsec` on control node.
2. `K3S_TOKEN=$token ./k3s.sh agent --server $server` on worker nodes.
3. Install and configure system upgrade controller, velero, and longhorn.
4. `kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml`
5. Apply this ClusterIssuer:
    ```yaml
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt
    spec:
      acme:
        email: $email
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: letsencrypt-account-key
        solvers:
        - http01:
            ingress:
              class: traefik
    ```

**Expected behavior:**
```
clusterissuer.cert-manager.io/letsencrypt created
```

**Actual behavior:**
```
Error from server (InternalError): error when creating "cert-manager-cfg.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded
```

**Additional context / logs:**
