### ISSUE TITLE
HelmChart CRD doesn't support objects in `spec.set`

### ISSUE THREAD

**Issue by mxplusb** [k3s-io/k3s#276]
**Describe the bug**

With this manifest at `/var/lib/rancher/k3s/server/manifests/sql.yaml:

```yaml
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata: 
  name: sql
  namespace: kube-system
spec:
  chart: stable/mssql-linux
  targetNamespace: aperture-system
  set:
    acceptEula:
      value: "y"
    edition:
      value: Express
    collation: SQL_Latin1_General_CP1_CI_AS
    lcid: 1033
    hadr: 0
    image:
      repository: microsoft/mssql-server-linux
      tag: 2017-CU5
      pullPolicy: IfNotPresent
    service:
      headless: false
      type: ClusterIP
      port: 1433
```

k3s does not deploy the chart. This manifest works:

```yaml
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata: 
  name: sql
  namespace: kube-system
spec:
  chart: stable/mssql-linux
  targetNamespace: aperture-system
  valuesContent: |-
    acceptEula:
      value: "y"
    edition:
      value: Express
    collation: SQL_Latin1_General_CP1_CI_AS
    lcid: 1033
    hadr: 0
    image:
      repository: microsoft/mssql-server-linux
      tag: 2017-CU5
      pullPolicy: IfNotPresent
    service:
      headless: false
      type: ClusterIP
      port: 1433
```

**To Reproduce**

1. Create `sql.yaml` from first manifest.
1. `/usr/local/bin/k3s-uninstall.sh`
1. `curl -sfL https://get.k3s.io | sh -`
1. Deploy the local storage provisioner so the chart will deploy.
    1. `kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml`
    1. `kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'`
1. `cp sql.yaml /var/lib/rancher/k3s/server/manifests/`

**Expected behavior**

I expect the HelmChart CRD to pick up the chart and deploy it.

**Additional context**

Looking at the spec, there's a `Set` field:

```go
type HelmChartSpec struct {
	TargetNamespace string                        `json:"targetNamespace,omitempty"`
	Chart           string                        `json:"chart,omitempty"`
	Version         string                        `json:"version,omitempty"`
	Repo            string                        `json:"repo,omitempty"`
	Set             map[string]intstr.IntOrString `json:"set,omitempty"`
	ValuesContent   string                        `json:"valuesContent,omitempty"`
}
```

And it is [supported](https://github.com/rancher/k3s/blob/93cc6462be62fa95a3bdfc91f1de09a5a1666799/pkg/helm/controller.go#L300-L307), but I'm not sure why it's not working as intended. Unfortunately I can't find the logs or I would share them.

**Comment by erikwilson** [comment]
I think it may support only key: value pairs instead of objects.

**Comment by erikwilson** [comment]
Some more info, the set spec works as described, but if we try to flatten the keys for set using yaml and something like:
```yaml
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata: 
  name: sql
  namespace: kube-system
spec:
  chart: stable/mssql-linux
  targetNamespace: aperture-system
  set:
    acceptEula.value: y
    edition.value: Express
    collation: SQL_Latin1_General_CP1_CI_AS
    lcid: 1033
    hadr: 0
  valuesContent: |-
    image:
      repository: microsoft/mssql-server-linux
      tag: 2017-CU5
      pullPolicy: IfNotPresent
    service:
      headless: false
      type: ClusterIP
      port: 1433
```
The above will never deploy because of dot notation. :(

If it is converted to json:
```json
{
	"apiVersion": "k3s.cattle.io/v1",
	"kind": "HelmChart",
	"metadata": {
		"name": "sql",
		"namespace": "kube-system"
	},
	"spec": {
		"chart": "stable/mssql-linux",
		"targetNamespace": "aperture-system",
		"set": {
			"acceptEula.value": "y",
			"edition.value": "Express",
			"collation": "SQL_Latin1_General_CP1_CI_AS",
			"lcid": 1033,
			"hadr": 0
		},
		"valuesContent": "image:\n  repository: microsoft/mssql-server-linux\n  tag: 2017-CU5\n  pullPolicy: IfNotPresent\nservice:\n  headless: false\n  type: ClusterIP\n  port: 1433"
	}
}
```
Strangely enough that will deploy. 

It may be possible to use some escaping in the yaml to fix the behavior, but I am going to mark this is an enhancement to support nested keys for set, perhaps we can flatten the object before to generate the --set args.

**Comment by mxplusb** [comment]
Ah, yeah, I missed that it didn't support nested keys, which would explain my results. Good to know for sure. :)

**Comment by erikwilson** [comment]
I was able to get it to work using only set, but if the value isn't an int or string it needs to be quoted ("y" and "false"):
```yaml
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata: 
  name: sql
  namespace: kube-system
spec:
  chart: stable/mssql-linux
  targetNamespace: aperture-system
  set:
    acceptEula.value: "y"
    edition.value: Express
    collation: SQL_Latin1_General_CP1_CI_AS
    lcid: 1033
    hadr: 0
    image.repository: microsoft/mssql-server-linux
    image.tag: 2017-CU5
    image.pullPolicy: IfNotPresent
    service.headless: "false"
    service.type: ClusterIP
    service.port: 1433
```
