### ISSUE TITLE
Help need to add a private registry to containerd / k3s

### ISSUE THREAD

**Issue by docfactory37** [k3s-io/k3s#2839]
Hi All,

i have deplyed k3s with containerd backend and i have a Nexus private registry on http.

i have been able to locate this doc https://github.com/containerd/cri/blob/master/docs/registry.md

**Environmental Info:**
K3s Version: 
1.20 latest stable 

and i have add the below to `/etc/containerd/config.toml`

```
# Config file is parsed as version 1 by default.
# To use the long form of plugin names set "version = 2"
# explicitly use v2 config format
version = 2

[plugin."io.containerd.grpc.v1.cri".registry.mirrors]
  [plugin."io.containerd.grpc.v1.cri".registry.mirrors."test.http-registry.io"]
    endpoint = ["http://<<IP>>:32000"]
[plugin."io.containerd.grpc.v1.cri".registry.configs."test.http-registry.io".tls]
  insecure_skip_verify = true
```

```
failed to resolve reference "<<IP>>:32000/prod/jacket:1": failed to do request: Head "https://<<IP>>:32000/v2/prod/jacket/manifests/1": http: server gave HTTP response to HTTPS client
```
helping someone will be able to help me to get it to work.

**Comment by brandond** [comment]
https://rancher.com/docs/k3s/latest/en/installation/private-registry/

**Comment by docfactory37** [comment]
Hey @brandond I have tried this setup without tls and still get the same outcome :) 

Im able to access my provide registry out side on k3s and pull images

**Comment by brandond** [comment]
Can you provide an example of both your registries.yaml, and the pod spec referencing the image on your private registry that is failing to pull?

**Comment by docfactory37** [comment]
@brandond 

If I do the below

`sudo crictl pull <<IP>>:32000/prod/jacket:1` to pull the image into containerd I get the error advised in the first post.

if I do it with docker as I have allowed docker to connect to the registry on http it will pull the image.

So I know there is no issue with the nexus registry

Just having issue with containerd being able to connect over http as my k3s is using the  containerd backend not docker backend.

Nexus deployment yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: utilities
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      volumes:
        - name: utilities-nexus
          persistentVolumeClaim:
            claimName: utilities-nexus
      containers:
        - name: nexus
          image: docfactory/nexus:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: 'Australia/Sydney'
            - name: DOCKUID
              value: '1000'
            - name: DOCKGID
              value: '1000'
            - name: DOCKUPGRADE
              value: '1'
          resources:
            limits:
              cpu: '4' 
              memory: 2Gi
            requests:
              cpu: '200m' 
              memory: 500Mi
          ports:
           - containerPort: 8081
           - containerPort: 32000
              # Use the localhost:32000 path to use image from registry service
              # e.g.  image: localhost:32000/hello-app:v3
          volumeMounts:
            - name: utilities-nexus
              mountPath: "/nexus-work"
```
Deployment reference private registry

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett-deployment
  namespace: media
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      volumes:
        - name: media-jackett
          persistentVolumeClaim:
            claimName: media-jackett
        - name: media-download
          persistentVolumeClaim:
            claimName: media-download
      containers:
        - name: jackett
          image: 192.168.1.101:32000/jackett:1
          imagePullPolicy: Always
          env:
            - name: DOCKUID
              value: '112'
            - name: DOCKGID
              value: '115'
            - name: DOCKUPGRADE
              value: '1'
          resources:
            limits:
              cpu: '100m'
              memory: '1Gi'
            requests:
              cpu: '50m'
              memory: '500Mi'
          ports:
           - containerPort: 9117  
              # Use the localhost:32000 path to use image from registry service
              # e.g.  image: localhost:32000/hello-app:v3
          volumeMounts:
            - name: media-jackett
              mountPath: "/config"
            - name: media-download
              mountPath: "/downloads"
```

**Comment by brandond** [comment]
What does your registries.yaml look like? You need to tell containerd to use http for 192.168.1.101:32000 in the endpoint list. By default it assumes https.

**Comment by docfactory37** [comment]
Not sure what you mean by registries.yaml look like ?
As I'm using Nexus docker registry.

So are you say the the image should be ?http://192.168.1.101:32000/jackett:1

**Comment by docfactory37** [comment]
@brandond  sorry I just realized what you mean be registry.yaml see below

```
mirrors:                                                                          
  docker.io:                                                                      
    endpoint:                                                                     
      - "http://192.168.1.101:32000"
```
