### ISSUE TITLE
Traefik Dashboard Ingress

### ISSUE THREAD

**Issue by theobouwman** [k3s-io/k3s#2868]
I just deployed and activated traefik dashboard for k3s.

Now I want to create an ingress to access the traefik dashboard on `/traefik`, how can I do this?

**Comment by brandond** [comment]
https://github.com/k3s-io/k3s/issues/1894#issuecomment-768903789

**Comment by theobouwman** [comment]
@bradtopol why can't I access the dashboard via `nuc.local/traefik` with this config?:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
      domain: "nuc.local"
      ingress:
        annotations:
          traefik.frontend.rule: "PathPrefix(`/traefik`)"
```

**Comment by brandond** [comment]
Are those backticks in your rule instead of single quotes?

**Comment by theobouwman** [comment]
Yes

**Comment by brandond** [comment]
I don't see that as a valid ingress annotation. Where are you getting that from?
https://doc.traefik.io/traefik/v1.7/configuration/backends/kubernetes/#general-annotations

**Comment by theobouwman** [comment]
I have this configuration:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
      domain: "nuc.local"
      ingress:
        annotations:
          traefik.frontend.rule: Host('nuc.local') && Path('/traefik')
```
Which results in:
<img width="1127" alt="Screenshot 2021-01-29 at 10 21 48" src="https://user-images.githubusercontent.com/16098190/106256623-cdb8a000-621b-11eb-8d93-94f2a40ae561.png">

But it still doesn't work when I reach `nuc.local/traefik`
