### ISSUE TITLE
K3s does not load Helm customizations on startup requiring edit

### ISSUE THREAD

**Issue by carlosedp** [k3s-io/k3s#2893]
**Environmental Info:**
K3s Version: 
k3s version v1.20.2+k3s1 (1d4adb03)
go version go1.15.5

Node(s) CPU architecture, OS, and Version: 
Linux OdroidN2 4.9.236+ #1 SMP PREEMPT Mon Oct 26 00:29:43 CET 2020 aarch64 GNU/Linux

Cluster Configuration:
Single node

**Describe the bug:**
I've applied a Helm customization to enable Traefik dashboard and allow insecure backends (https backend with self-signed certificate). Whenever I restart K3s or the its host, this customization is not picked up and the default Traefik settings are applied. I need to re-edit the created yaml (adding a space or newline on `/var/lib/rancher/k3s/server/manifests/traefik-config.yaml`) and then k3s picks-up the changes.

My customization manifest:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
    # New TLS skip verify certificate setting
    ssl.insecureSkipVerify: "true"
```

**Steps To Reproduce:**

1. Create a Helm customization as described on https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig
2. K3s will apply the changes restarting Traefik
3. Restart node
4. Check that the changes configured on the manifest are not applied

**Expected behavior:**

Customizations to be applied on startup

**Actual behavior:**

Default config is applied.

**Comment by a01fe** [comment]
Have you looked at k3s server logs?

I've had trouble with `spec.set` and data types. You might try this instead:

```yaml
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
  valuesContent: |-
    rbac.enabled: true
    ssl.enabled: true
    metrics.prometheus.enabled: true
    kubernetes.ingressEndpoint.useDefaultPublishedService: true
    ssl.insecureSkipVerify: true
```

**Comment by brandond** [comment]
If you want to customize the packaged Helm chart, you should be creating a `HelmChartConfig` resource, and only specifying in the valuesContent the options that you need to override. The manifest that you provided is a `HelmChart`, which means that you are installing a **second** copy of the packaged Traefik helm chart with different options. Whichever one is updated most recently will win.

Please take another look at the docs page you linked.

**Comment by carlosedp** [comment]
Confirming that using `HelmChartConfig` solves it, sorry about the noise.

My config:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    rbac.enabled: true
    metrics.prometheus.enabled: true
    kubernetes.ingressEndpoint.useDefaultPublishedService: true
    ssl:
      insecureSkipVerify: true
      enabled: true
      permanentRedirect: false
    dashboard:
      enabled: "true"
      domain: "traefik.mydomain.com"
```
