### ISSUE TITLE
Can't pull from private registry as default.

### ISSUE THREAD

**Issue by JulianZhang** [k3s-io/k3s#2981]
**Environmental Info:**
K3s Version: 
k3s version v1.17.17+k3s1 (e8c94840)

Node(s) CPU architecture, OS, and Version: 
arm64, ubuntu 16.04

Cluster Configuration:
K3S with containerd

**Describe the bug:**
I had set private registry in k3s, I can pull image with registryip:port.
But even I set private registry as docker.io's endpoint, I can't pull image without registryip:port.

```
#it worked 
crictl  pull  ip:5000/coredns-coredns:1.6.3-t2

#it fail
crictl  pull  coredns-coredns:1.6.3-t2
```

The 1.6.3-t2 is a tag I had push tu private registry for test.

My config file is :

```
cat /etc/rancher/k3s/registries.yaml
mirrors:
  docker.io:
    endpoint:
      - "https://ip:5000"
configs:
  "ip:5000":
    tls:
      cert_file: /root/registry/certs/docker/ca.cert
      key_file: /root/registry/certs/docker/ca.key
      ca_file: /root/registry/certs/docker/ca.crt
```

**Steps To Reproduce:**
Set a private registry as default

**Expected behavior:**
All image write in pod file can be the same with out private registry.
But pull form the private registry.

**Actual behavior:**
Didn't pull from the private registry.
