### ISSUE TITLE
kubeconfig Error: Kubernetes cluster unreachable 

### ISSUE THREAD

**Issue by Mel-Github** [k3s-io/k3s#3016]
**Environmental Info:**

K3s Version: 

`k3s version v1.20.2+k3s1 (1d4adb03).       
go version go1.15.5`

Node(s) CPU architecture, OS, and Version: 

`Linux machperson-dev-k3s-master-0 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration: 
```
melmeow@Melvins-MacBook-Pro ~ [1]> k get nodes
NAME                          STATUS   ROLES                  AGE   VERSION
machperson-dev-k3s-node-0     Ready    <none>                 13d   v1.20.2+k3s1
machperson-dev-k3s-node-1     Ready    <none>                 13d   v1.20.2+k3s1
machperson-dev-k3s-master-0   Ready    control-plane,master   13d   v1.20.2+k3s1
```

**Describe the bug:**

Attempting to connect to. the cluster using `kubeconfig` argument failed with the error 
```bash
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Steps To Reproduce:**

After setup cluster, i copied the `/etc/rancher/k3s/k3s.yaml` to my local desktop and modified the IP address to point to my cluster. Below is part of the `k3s.yaml`

``` yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTVRNMk1qQXhPRE13SGhjTk1qRXdNakU0TURNME9UUXpXaGNOTXpFd01qRTJNRE0wT1RRegpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTVRNMk1qQXhPRE13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTVEFoK3JRZklBbEFKOXdOdmYwaDBvblBCOUVPZEt0UVVHdVNmeDRScTIKWlZMckFTTUxBVEF3L2x2Rk5yQ3QvZ0t1QTVzRjQxVUl5WHlNUDAzQ2xvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUNjQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVkyaG5kS1VzbVNnR2MwZVBQSGdtClUxaXdnaEV3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUlNeW1EZmdKMmJ6RStYdFdXajFNM2xpNWxsSEsyNEUKK241c2hCbVdNQUtzQWlFQTJGS2hrZmtiSHdPZHFRQ045blhEcy8xbHZUS3BXYXhkQlg1QkZSMDB1Vjg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.20.101:6443
```

I have similar configurations to access multiple cluster. My `KUBECONFIG`
```bash
echo $KUBECONFIG
/Users/melmeow/.kube/config:/Users/melmeow/.kube/config_k3s:/Users/melmeow/.kube/gloo:/Users/melmeow/.kube/woodland-gloo
``` 

I am using `kubectx` to switch between clusters and am able to perform all operations normally. However attempting to use `kubeconfig`, the operation will fail. 

```bash
➜  .kube k cluster-info
Kubernetes master is running at https://192.168.20.101:6443
CoreDNS is running at https://192.168.20.101:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://192.168.20.101:6443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

➜  .kube k cluster-info --kubeconfig ./config_k3s
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
Not sure where it is reading localhost:8080 

**Expected behavior:**

Able to access the cluster using the `kubeconfig` method.

**Actual behavior:**

K8s cluster Connection refused. 

**Additional context / logs:**

Full k3s logs available upon request.

closest similar issues [here](https://github.com/k3s-io/k3s/issues/1126) but the resolution in that issue does not work.
