### ISSUE TITLE
HelmChart key from "set" imported with whitespace in the middle of the string

### ISSUE THREAD

**Issue by oskapt** [k3s-io/k3s#3027]
**Environmental Info:**
K3s Version: 1.19.4+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux demo-a 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 master, 1 worker, embedded etcd

**Describe the bug:**

I created a HelmChart for cert-manager and dropped it in the `manifests` directory. It was converted to a HelmChart but never installed. I noticed that `installCRDs: true` had become `installCR Ds: true`. I changed from `set` to `valuesConfig` and it installed correctly.

**Steps To Reproduce:**

- Installed K3s: 
```
k3sup install --host=demo-a --user=root --k3s-version=v1.19.4+k3s1 --local-path=config.a.yaml --context a --cluster --tls-san 10.68.0.240 --k3s-extra-args="--disable servicelb --node-taint node-role.kubernetes.io/master=true:NoSchedule"
```

Installed this:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  targetNamespace: cert-manager                                                   
  repo: https://charts.jetstack.io
  set:
    installCRDs: true
```

This is what showed up:

```
➤ k describe helmchart/cert-manager -n kube-system
Name:         cert-manager
Namespace:    kube-system
Labels:       objectset.rio.cattle.io/hash=4fc8903e84e6d3a7fcf0070cf4fbe4b769b43899
Annotations:  objectset.rio.cattle.io/applied:
                {"apiVersion":"helm.cattle.io/v1","kind":"HelmChart","metadata":{"annotations":{"objectset.rio.cattle.io/id":"","objectset.rio.cattle.io/o...
              objectset.rio.cattle.io/id:
              objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
              objectset.rio.cattle.io/owner-name: cert-manager
              objectset.rio.cattle.io/owner-namespace: kube-system
API Version:  helm.cattle.io/v1
Kind:         HelmChart
Metadata:
  Creation Timestamp:  2021-03-06T18:46:54Z
  Generation:          1
  Managed Fields:
    API Version:  helm.cattle.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:objectset.rio.cattle.io/applied:
          f:objectset.rio.cattle.io/id:
          f:objectset.rio.cattle.io/owner-gvk:
          f:objectset.rio.cattle.io/owner-name:
          f:objectset.rio.cattle.io/owner-namespace:
        f:labels:
          .:
          f:objectset.rio.cattle.io/hash:
      f:spec:
        .:
        f:chart:
        f:repo:
        f:set:
          .:
          f:installCRDs:
        f:targetNamespace:
    Manager:         k3s
    Operation:       Update
    Time:            2021-03-06T18:46:54Z
  Resource Version:  5781
  Self Link:         /apis/helm.cattle.io/v1/namespaces/kube-system/helmcharts/cert-manager
  UID:               cbfc9406-0465-43cd-9496-05516acc7fe9
Spec:
  Chart:  cert-manager
  Repo:   https://charts.jetstack.io
  Set:
    Install CR Ds:   true
  Target Namespace:  cert-manager
Events:              <none>
```

**Expected behavior:**

I expected cert-manager to install via Helm

**Actual behavior:**

Nothing happened. I couldn't find any logs but finally just guessed that it was failing on whatever caused that key to show up with the space. I replaced the HelmChart with this, and it installed:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  targetNamespace: cert-manager
  repo: https://charts.jetstack.io
  valuesContent: |-
    installCRDs: true
```

The HelmChart Spec now looks like this:

```
Spec:
  Chart:             cert-manager
  Repo:              https://charts.jetstack.io
  Target Namespace:  cert-manager
  Values Content:    installCRDs: true
```

**Additional context / logs:**

**Comment by brandond** [comment]
I can't report this. The HelmChart manifest is loaded via upstream Kubernetes code, same as if you did a `kubectl apply -f` on the command line. Is it possible you had some sort of hidden whitespace in there from wherever you copy-pasted from?

**Comment by oskapt** [comment]
I can reproduce it reliably. I just did so on a new 1.19.4+k3s1 cluster. There's no whitespace - I typed `installCRDs: true` by hand. The YAML shows correct, but `kubectl describe` doesn't, and the chart never installs.  If something is throwing an error, where would I see it?

```
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: true
  targetNamespace: cert-manager
```

```
Spec:
  Chart:  cert-manager
  Repo:   https://charts.jetstack.io
  Set:
    Install CR Ds:   true
  Target Namespace:  cert-manager
```

**Comment by brandond** [comment]
Oh, you're doing describe. Describe pretty-prints things; there may be an extra space in the 'human readable' field description but that has absolutely nothing to do with the internal representation of the field.

If you want yaml, you should do `kubectl get -o yaml`

**Comment by oskapt** [comment]
Yes. I know `-o yaml` - the actual issue is "When I drop this into `/var/lib/rancher/k3s/server/manifests` and it's using `set` it never installs." I assumed, perhaps incorrectly, that it was somehow tied to whatever is also causing that field to be shown weirdly. It just never installs. Ever. But as soon as I change that to `valuesContent` it installs fine.

Here's the YAML if you'd like to try. I have no idea where to look for a log msg about why this might be making K3s angry. There's nothing in `/var/log/syslog`.

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  targetNamespace: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: true
```
