### ISSUE TITLE
in HA cluster, new node joining hits  "etcdserver: unhealthy cluster" but etcd reports healthy via etcdctl

### ISSUE THREAD

**Issue by ryanrhee** [k3s-io/k3s#3074]
**Environmental Info:**
K3s Version of new node joining is:
```
k3s version v1.19.5+k3s2 (746cf403)
```
K3s Version of two existing nodes are:
```
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8
```

Node(s) CPU architecture, OS, and Version: 

```sh
# "main" node
Linux ubuntu.localdomain 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
# second node
Linux desktop 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# 3rd one failing the add
Linux rpi3b.localdomain 5.4.0-1030-raspi #33-Ubuntu SMP PREEMPT Wed Feb 24 11:20:11 UTC 2021 aarch64 GNU/Linux
```

Cluster Configuration:

trying to run a 3 node HA cluster.
- 1 ubuntu VM on proxmox
- 1 ubuntu WSL VM on win10 pro
- 1 k3OS ARM overlay on raspberry pi 3b

**Describe the bug:**

after 3-node HA cluster loses unhealthy member, adding a new member fails due to "etcdserver: unhealthy cluster".

**Steps To Reproduce:**

raspberry pi previously ran regular ubuntu but died. re-imaged with k3OS in hopes it would consume less resources. rpi k3os came up fine but fails to join the cluster.

when the rpi died, i removed the node via `kubectl delete node`. i then checked on the etcd cluster by `kubectl exec`'ing etcdctl and listing the members etc. etcd reports a healthy cluster. one is a leader, one is a follower, no hosts are learners.

k3s config was done at install time. 

on first node:
```
curl -sfL https://get.k3s.io | K3S_TOKEN=<token> sh -s - --cluster-init
```

second node: (needs external ip bc WSL is NAT'd behind host OS); all ports are forwarded (even udp)
```
curl -sfL https://get.k3s.io | K3S_TOKEN=<token> sh -s - \
  --server https://ubuntu.localdomain:6443 \
  --node-external-ip 192.168.1.196
```

third node is a k3OS install with ARM overlay. config:
```yaml
ssh_authorized_keys:
  - ssh-rsa ...
write_files:
  - path: /var/lib/connman/default.config
    content: |-
      [service_eth0]
      Type=ethernet
      IPv4=192.168.1.3/255.255.255.0/192.168.1.1
      IPv6=off
      Nameservers=192.168.1.192
hostname: rpi3b.localdomain

k3os:
  server_url: https://ubuntu.localdomain:6443
  token: '<token>'
  ntp_servers:
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
  k3s_args:
    - server
```

**Expected behavior:**

i expect the raspi node to join the ha k3s cluster

**Actual behavior:**

raspi k3s server fails to join cluster

**Additional context / logs:**

full error text:

```
$ K3S_TOKEN=<token> k3s server --server https://ubuntu.localdomain:6443 --disable-agent
INFO[2021-03-16T09:58:03.237632444Z] Starting k3s v1.19.5+k3s2 (746cf403)
INFO[2021-03-16T09:58:03.416356927Z] Managed etcd cluster not yet initialized
INFO[2021-03-16T09:58:03.487489952Z] Adding https://192.168.1.3:2380 to etcd cluster [ubuntu-3b4c5ab6=https://192.168.1.2:2380 desktop-3ccd48c4=https://172.22.72.201:2380]
{"level":"warn","ts":"2021-03-16T09:58:03.488Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-c550df21-86b0-4d88-8757-40800e0b75b0/192.168.1.2:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: unhealthy cluster"}
FATA[2021-03-16T09:58:03.489392232Z] starting kubernetes: preparing server: start managed database: joining etcd cluster: etcdserver: unhealthy cluster
```
