### ISSUE TITLE
Having ErrImagePull when trying to pull a private docker image

### ISSUE THREAD

**Issue by tanqhnguyen** [k3s-io/k3s#3123]
**Environmental Info:**
K3s Version: 
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

**Node(s) CPU architecture, OS, and Version:** 
**Master**: Linux dev-1 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
**Worker**: Linux dev-2 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Cluster Configuration:**
1 master, 1 worker

Example deployment manifest (I use krane to deploy)
```yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: account-app
  template:
    metadata:
      labels:
        app: account-app
    spec:
      imagePullSecrets:
        - name: gitlab-credentials
      containers:
        - name: account
          image: <%= registry_image %>:<%= commit_short_sha %>
          envFrom:
            - configMapRef:
                name: account-config
            - secretRef:
                name: account-secret
          env:
            - name: VERSION
              value: "<%= commit_short_sha %>"
          command: ["gunicorn", "main:app", "-b", "0.0.0.0:5000", "-w", "4"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "196Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
```

**Describe the bug:**
I am using gitlab's private docker registry to deploy my application to k3s.
With the above deployment I'm unable to pull the image to my master node for some reason (ErrImagePull error). It works fine for my worker node. Before I updated to 1.20 it was the other way around, my master node can pull the image but my worker node can't.

During the deployment if it happens to deploy to the master node, the pod is stuck there for a while (until timeout), and if I delete that stuck pod, the deployment went through because it automatically rolls out a new pod on the other node. For example, if the pod is stuck on the master node, and I delete it, there will be a new node deployed to the worker node (which happens to be the working node now)

**Steps To Reproduce:**
I installed k3s using this command `curl -sfL https://get.k3s.io | sh -s - --docker`
Not sure how to replicate this because it happens kinda random

**Expected behavior:**
Pulling a private docker image should work consistently

**Actual behavior:**
At the moment, the master node is not able to pull the private docker image, and the worker is able to pull the private image.

**Additional context / logs:**
I have no ideas which logs are necessary to debug this one, feel free to ask for it and I will try to provide as much as I can
