### ISSUE TITLE
Duplicate podCIDR ranges assigned to cluster nodes.

### ISSUE THREAD

**Issue by jgreat** [k3s-io/k3s#3131]
**Environmental Info:**
K3s Version: 
```
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8
```

Also on version `v1.20.2+k3s1`

Node(s) CPU architecture, OS, and Version:
Running in Azure.  Ubuntu 18.04 

```
Linux k3s-ingress-zone-2000000 5.4.0-1043-azure #45~18.04.1-Ubuntu SMP Sat Mar 20 16:16:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

**Control-Plane**

- PostgreSQL Database (4 core)
- VMSS with 2 control-plane (4 core) 
- Control-pane nodes are behind a private load-balancer. Worker (agent) nodes connect to load-balancer.

**Workers** 

- 3  VMSS with 12 total workers (4 and 8 core in various zones)

**Describe the bug:**

Worker nodes are being assigned duplicate podCIDR ranges.  As you can imagine, this is causing quite a networking nightmare.

In this example `k3s-general-zone-2000001` and `k3s-general-zone-2000000` were assigned duplicate podCIDR ranges.

```
➜ kubectl get nodes -o custom-columns=Name:.metadata.name,CIDR:.spec.podCIDR --sort-by='{.spec.podCIDR}'
Name                          CIDR
k3s-control000000             10.42.0.0/24
k3s-control000001             10.42.1.0/24
k3s-ingress-zone-1000000      10.42.2.0/24
k3s-worker-zone-1000000          10.42.3.0/24
k3s-monitoring-zone-1000000   10.42.4.0/24
k3s-general-zone-1000000      10.42.5.0/24
k3s-ingress-zone-2000000      10.42.6.0/24
k3s-worker-zone-1000001          10.42.7.0/24
k3s-monitoring-zone-1000001   10.42.8.0/24
k3s-general-zone-1000001      10.42.9.0/24
k3s-worker-zone-2000000          10.42.10.0/24
k3s-worker-zone-2000001          10.42.11.0/24
k3s-general-zone-2000001      10.42.13.0/24
k3s-general-zone-2000000      10.42.13.0/24
```

My guess is that there is a race condition where both of the k3s-general-zone-2 nodes in the azure vmss come up at the same time and end up getting assigned the same range? 

**Steps To Reproduce:**

Launch Nodes in parallel with multiple Virtual Machine Scale Sets. Nodes install k3s in `cloud-init`.

control plane config.yaml

```yaml
agent-token: Redacted
datastore-endpoint: "postgres://Redacted"
disable-cloud-controller: true
disable:
- servicelb
- local-storage
- traefik
kube-apiserver-arg:
- "cloud-provider=external"
kubelet-arg:
- "cloud-provider=external"
- "cloud-config=/etc/kubernetes/azure.json"
tls-san:
- 172.20.128.19
token: redacted
node-taint:
- "node-role.kubernetes.io/master=true:NoSchedule"
write-kubeconfig-mode: 644
```

client k3s config.yaml

```yaml
server: "https://172.20.128.19:6443"
token: "redacted"
kubelet-arg:
- "cloud-provider=external"
- "cloud-config=/etc/kubernetes/azure.json"
"node-taint": []

"node-label":
- "node.kubernetes.io/exclude-from-external-load-balancers=true"
```

**Expected behavior:**
Nodes to be assigned unique podCIDR IP spaces.

Let me know if you need any other data to troubleshoot.
