### ISSUE TITLE
"kuebectl logs podName" verify serving-kubelet.crt failed  that signed by k3s apiserver 

### ISSUE THREAD

**Issue by cfw11** [k3s-io/k3s#3173]
Hi
**Environmental Info:**
K3s Version: 

v1.20.5+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux DESKTOP-12M812R 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master

**Describe the bug:**

I want to use [VIrtualKubelet ](https://github.com/virtual-kubelet/virtual-kubelet) create a virtualNode in my cluster,  in order to use kubectl logs with TLS,  so I use CertificateSigningRequest to create a serving-kubelet.crt by [document](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#client-and-serving-certificates),
this is my CertificateSigningRequest：
```
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: test
spec:
  username: system:node:test
  groups:
    - system:nodes
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJRTR6Q0NBc3NDQVFBd2ZERUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdUQ2xOdmJXVXRVM1JoZEdVeApEekFOQmdOVkJBY1RCazE1UTJsMGVURVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVJVd0V3WURWUVFMCkV3eHplWE4wWlcwNmJtOWtaWE14R1RBWEJnTlZCQU1URUhONWMzUmxiVHB1YjJSbE9uUmxjM1F3Z2dJaU1BMEcKQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUN2M1gxWjhEMTZ6dDlLM3laYU53c09MYVkrOEFPcwo1a0oxYjVUU1RBTUlLcGk0a2M4M0J1STlkeGNTb0UrZXBlVHN3QmR3S0lybWJ1UzA0M01vcFBSMEdXNHpXYW5SCkErOU5HVGVFS3haUUptaFkvMUpMU3VZMGxIdlYzRldzanQ5cll0OEFpMUpSb2dxSHlWMHkweEZGYXB4T1lvMUcKVEVyZkVDbGdpSCtmK1FzdTJ3aXpyNGJ1bmJKcVh3ay9nd1MvdjRhQWVzVHJNZWt1RE94Y2p4MmlmdXp0L1RkeApDTC8zUXEyVmJCK1JHcnVjMVZIbnlTd3BZRTZpTTRETW5kcmhkWXk5eU4rbm5zSFluN00zeUw3bnFuc3VOQ2l1CnlvaXdLelY5RmN6NGdRN043aldSKzZpR1VaL1I1NDFyN2huWStSc2lVMUVjd3F3TVV5NUlhSFFtN1ZSZ09waUwKaW5XV0Qwb29oZUtFUWdiZyt4N0tTNk5JRElJMkxtOEpZV2dpaW5tRGQ2cVJoVlNXMTQzYXc5VndnZm1UNWRzZApoOEZ0ZFNSS3ZpL05NUE5kK1VrbkZSQzFkL3dqVncvRE5FNVFQczBBNHR4eTY2REpuUDRKRXpHRDBRYmJINlNKCkxTZFVkSjhKYytMNUhUT1JhbWxvcUVVR0p5cWZ1U3VqYk1SOTdTQ3JXdmVLdlpQOXFzempkd2JqZElpM0oyVmQKODBuODEzeHoyN3JUU3p0MGg5amo5SHJ6MUhYN1l3NG9UUzMzR3pmcWd3emc4MXJsbGsrTEdPUUxJdkFLZzhEcQp2Q29LTEQ0SkNkSmVObGNpa0NEa2xMcWI5UC9WSUZ0VDVZUmFJU3Y3VWREYWVPYklXMGpna0ZNS3kvY0lZWXg2CmpqdlB6OFg1ME1ZaHZRSURBUUFCb0NJd0lBWUpLb1pJaHZjTkFRa09NUk13RVRBUEJnTlZIUkVFQ0RBR2h3U3MKRVFBQ01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXZMN0E2dXlEM1VkOTRIU3gyT1ZUNS9OQ1k3Ykp3d0hXLwpMQ1JtNWJtRk9HUmI3SG8xT0JhLzA5aHQvRWlEb1FkRGYxRDc3UjBHeFlBWlNwRFBFcWZ4cHc3ZEhiQnJVMC9MCnNKODcrTXdMRE5wVVlabE1zckswOGpXbEorcjBsMGtDOXppdi80RlNKa25qV0tRY3E1RndDSk9mOFRKRUlyY1cKS1ZJdjE1MnlHRC90TzBNbTZvdWhRZldQUnhlb3dQKy80Y1J1ZUNlbUpqcUp2MVEraGtWcnB3aHZsRGFZemcxVAptblRjaFlYK0dTN2JtaGNWUnNyV3dNTkY5SEIrZndockdUcGZRK1lDaEhXK2xMajRvU0FqSzZpa2tHbkxXQi84CndzbjAreXhpcUlyVno1YTE4VHE1dndDb2hBdFRoNXNMSXJIV0l5VVRSdm9GdnNoZFkrWWxqVXEwZ1JpOVBLT00KeitCYWxZS24yWXNJMlppTmNIeXNUa3c3YzlORHhHdTg4a2ZCQjVZdnA0Q1pnWEZGc2kvbEtqaU5RcHFyV3lyNgo0NVlNaWQyM0NCVFFHbGg2K2t0YUpTbWlnZDBOZVFnOUN5ZDBJR0l5YXllVVZLQjZqSDFpRU53QlBOUFZBeVB2Cm1TMkJ1bi9GZmpBd3hsUGVOVUI5WVNqM012Q21jZzN2aXRPUSs2RGJtRDcxa1lWUmF2UE9GSzl3bDkwUVZzeW4KYitEbzVKNmxyeno2Sm1FQ1JXdTdhUHd5bGdIbS9MdzVQN0tpU3pOZkE5OEtyeTNXZXc0OUFwK2E2cWNwdml5dgpMdFZYQnRzQVdhek9OMFFxSmJZcFZVQ0g4NkJJQ04zcFRpTjBNc3Q4UEl4S1lqRmFxSytQMDlKdFN4Qkx6QnFWCmFpdUppUlBFT0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KClByb2Nlc3MgZmluaXNoZWQgd2l0aCBleGl0IGNvZGUgMAo=
  signerName: kubernetes.io/kubelet-serving
  usages:  ["digital signature", "key encipherment", "server auth"]
EOF
```

after approve CSR, I get certificate from `status.certificate`, then I use the certificate and priKey to start my VirtualNode, when I use kubectl logs podName print error:    
**certificate signed by unknown authority.**  

but when I use the  **/var/lib/rancher/k3s/agent/serving-kubelet.crt** and  **/var/lib/rancher/k3s/agent/serving-kubelet.key** to start my virtualNode, it is work。
So i compare the diff of certificate:  
the  Issuer of  /var/lib/rancher/k3s/agent/serving-kubelet.crt is **k3s-server-ca@1617977826**
the  Issuer of  my certificate is **k3s-client-ca@1617977826**
So cause by Issuer ? 

**Steps To Reproduce:**

use a user (that is binding to clusterrole system:node) to create CSR:

```
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: test
spec:
  username: system:node:test
  groups:
    - system:nodes
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJRTR6Q0NBc3NDQVFBd2ZERUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdUQ2xOdmJXVXRVM1JoZEdVeApEekFOQmdOVkJBY1RCazE1UTJsMGVURVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVJVd0V3WURWUVFMCkV3eHplWE4wWlcwNmJtOWtaWE14R1RBWEJnTlZCQU1URUhONWMzUmxiVHB1YjJSbE9uUmxjM1F3Z2dJaU1BMEcKQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUN2M1gxWjhEMTZ6dDlLM3laYU53c09MYVkrOEFPcwo1a0oxYjVUU1RBTUlLcGk0a2M4M0J1STlkeGNTb0UrZXBlVHN3QmR3S0lybWJ1UzA0M01vcFBSMEdXNHpXYW5SCkErOU5HVGVFS3haUUptaFkvMUpMU3VZMGxIdlYzRldzanQ5cll0OEFpMUpSb2dxSHlWMHkweEZGYXB4T1lvMUcKVEVyZkVDbGdpSCtmK1FzdTJ3aXpyNGJ1bmJKcVh3ay9nd1MvdjRhQWVzVHJNZWt1RE94Y2p4MmlmdXp0L1RkeApDTC8zUXEyVmJCK1JHcnVjMVZIbnlTd3BZRTZpTTRETW5kcmhkWXk5eU4rbm5zSFluN00zeUw3bnFuc3VOQ2l1CnlvaXdLelY5RmN6NGdRN043aldSKzZpR1VaL1I1NDFyN2huWStSc2lVMUVjd3F3TVV5NUlhSFFtN1ZSZ09waUwKaW5XV0Qwb29oZUtFUWdiZyt4N0tTNk5JRElJMkxtOEpZV2dpaW5tRGQ2cVJoVlNXMTQzYXc5VndnZm1UNWRzZApoOEZ0ZFNSS3ZpL05NUE5kK1VrbkZSQzFkL3dqVncvRE5FNVFQczBBNHR4eTY2REpuUDRKRXpHRDBRYmJINlNKCkxTZFVkSjhKYytMNUhUT1JhbWxvcUVVR0p5cWZ1U3VqYk1SOTdTQ3JXdmVLdlpQOXFzempkd2JqZElpM0oyVmQKODBuODEzeHoyN3JUU3p0MGg5amo5SHJ6MUhYN1l3NG9UUzMzR3pmcWd3emc4MXJsbGsrTEdPUUxJdkFLZzhEcQp2Q29LTEQ0SkNkSmVObGNpa0NEa2xMcWI5UC9WSUZ0VDVZUmFJU3Y3VWREYWVPYklXMGpna0ZNS3kvY0lZWXg2CmpqdlB6OFg1ME1ZaHZRSURBUUFCb0NJd0lBWUpLb1pJaHZjTkFRa09NUk13RVRBUEJnTlZIUkVFQ0RBR2h3U3MKRVFBQ01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQXZMN0E2dXlEM1VkOTRIU3gyT1ZUNS9OQ1k3Ykp3d0hXLwpMQ1JtNWJtRk9HUmI3SG8xT0JhLzA5aHQvRWlEb1FkRGYxRDc3UjBHeFlBWlNwRFBFcWZ4cHc3ZEhiQnJVMC9MCnNKODcrTXdMRE5wVVlabE1zckswOGpXbEorcjBsMGtDOXppdi80RlNKa25qV0tRY3E1RndDSk9mOFRKRUlyY1cKS1ZJdjE1MnlHRC90TzBNbTZvdWhRZldQUnhlb3dQKy80Y1J1ZUNlbUpqcUp2MVEraGtWcnB3aHZsRGFZemcxVAptblRjaFlYK0dTN2JtaGNWUnNyV3dNTkY5SEIrZndockdUcGZRK1lDaEhXK2xMajRvU0FqSzZpa2tHbkxXQi84CndzbjAreXhpcUlyVno1YTE4VHE1dndDb2hBdFRoNXNMSXJIV0l5VVRSdm9GdnNoZFkrWWxqVXEwZ1JpOVBLT00KeitCYWxZS24yWXNJMlppTmNIeXNUa3c3YzlORHhHdTg4a2ZCQjVZdnA0Q1pnWEZGc2kvbEtqaU5RcHFyV3lyNgo0NVlNaWQyM0NCVFFHbGg2K2t0YUpTbWlnZDBOZVFnOUN5ZDBJR0l5YXllVVZLQjZqSDFpRU53QlBOUFZBeVB2Cm1TMkJ1bi9GZmpBd3hsUGVOVUI5WVNqM012Q21jZzN2aXRPUSs2RGJtRDcxa1lWUmF2UE9GSzl3bDkwUVZzeW4KYitEbzVKNmxyeno2Sm1FQ1JXdTdhUHd5bGdIbS9MdzVQN0tpU3pOZkE5OEtyeTNXZXc0OUFwK2E2cWNwdml5dgpMdFZYQnRzQVdhek9OMFFxSmJZcFZVQ0g4NkJJQ04zcFRpTjBNc3Q4UEl4S1lqRmFxSytQMDlKdFN4Qkx6QnFWCmFpdUppUlBFT0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KClByb2Nlc3MgZmluaXNoZWQgd2l0aCBleGl0IGNvZGUgMAo=
  signerName: kubernetes.io/kubelet-serving
  usages:  ["digital signature", "key encipherment", "server auth"]
EOF
```

**Expected behavior:**

the serving-kubelet.crt that create by CRS can verify by apiserver.

**Actual behavior:**

certificate signed by unknown authority.

**Additional context / logs:**
