### ISSUE TITLE
Parameter --default-local-storage-path does not work in k3s.service file

### ISSUE THREAD

**Issue by iamatsundere** [k3s-io/k3s#3185]
**Environmental Info:**
K3s Version: 
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc-deployment
spec:
  selector:
    matchLabels:
      app: orthanc
  replicas: 1
  template:
    metadata:
      labels:
        app: orthanc
    spec:
      volumes:
        - name: orthanc-pvc
          persistentVolumeClaim:
            claimName: orthanc-pvc
      containers:
        - name: orthanc
          image: osimis/orthanc
          ports:
            - containerPort: 8042
              name: orthanc-port
            - containerPort: 4242
              name: dicomweb-port
          env:
            - name: ORTHANC__AUTHENTICATION_ENABLED
              value: "false"
            - name: ORTHANC__DICOM_WEB__ENABLE
              value: "true"
            - name: ORTHANC__DICOM_WEB__ROOT
              value: "/dicom-web"
            - name: ORTHANC__DICOM_WEB__ENABLE_WADO
              value: "true"
            - name: ORTHANC__DICOM_WEB__WADO_ROOT
              value: "/wado"
            - name: ORTHANC__DICOM_WEB__STUDIES_METADATA
              value: "Extrapolate"
          volumeMounts:
            - name: orthanc-pvc
              mountPath: /var/lib/orthanc/db
```

**Describe the bug:**
I've updated the file: `sudo nano /etc/systemd/system/k3s.service` then edited to:
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--write-kubeconfig-mode' \
        '644' \
        '--disable' \
        'traefik' \
        '--default-local-storage-path' \
        '/media/hdd/' \
```
Then I restarted the k3s.service by `systemctl restart k3s.service` but the k3s does not store data to `/media/hdd`. It still stores data to `/var/lib/rancher/k3s/storage`

**Expected behavior:**
Data is stored at `/media/hdd`

**Actual behavior:**
Data is stored at `/var/lib/rancher/k3s/storage` instead of `/media/hdd` from the configure.
