### ISSUE TITLE
network policy is not additive

### ISSUE THREAD

**Issue by BoleynSu** [k3s-io/k3s#3227]
**Environmental Info:**
K3s Version: v1.20.6+k3s1

Node(s) CPU architecture, OS, and Version:
1 node Fedora CoreOS

Cluster Configuration:
1 node as master

**Describe the bug:**
According to <https://kubernetes.io/docs/concepts/services-networking/network-policies/>

> Network policies do not conflict; they are additive. If any policy or policies select a pod, the pod is restricted to what is allowed by the union of those policies' ingress/egress rules. Thus, order of evaluation does not affect the policy result.

However, it is not the cases in my setup.

**Steps To Reproduce:**
NP for mariadb:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mariadb-network-policy
spec:
  podSelector:
    matchLabels:
      app: mariadb
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress: []
```
NP for wordpress
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wordpress-network-policy
spec:
  podSelector:
    matchLabels:
      app: wordpress
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/instance: ingress-nginx
          app.kubernetes.io/component: controller
    ports:
    - port: 80
      protocol: TCP
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: mariadb
    ports:
    - port: 3306
      protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
```

**Expected behavior:**
With both NP, wordpress can access mariadb.

**Actual behavior:**
wordpress can access mariadb only if NP for mariadb is deleted.
