### ISSUE TITLE
Hardened cluster deployed in SLES15SP2 does not have tls-cert in kube-apiserver process

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#3248]
**Environmental Info:**
K3s Version: 

```
k3s version v1.20.6+k3s1 (8d043282)
go version go1.15.10
```

Node(s) CPU architecture, OS, and Version:

`Linux ip-172-31-37-54 5.3.18-24.37-default #1 SMP Wed Nov 4 09:38:41 UTC 2020 (c145e08) x86_64 x86_64 x86_64 GNU/Linux`
```
# cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
```

**Cluster Configuration:**

1 server

**Describe the bug:**

kube-apiserver process in k3s should have arguments for both `tls-cert-file` and `tls-private-key-file` but on this OS it does not. `sudo journalctl -u k3s | grep "Running kube-apiserver" | tail -n1 | grep -E 'tls-cert-file|tls-private-key-file'` produces nothing. 
In a multinode setup of this same OS, it does have this set.

**Steps To Reproduce:**

- Setup cluster to be hardened: https://rancher.com/docs/k3s/latest/en/security/hardening_guide/
- Install k3s using embedded etcd: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.6+k3s1 INSTALL_K3S_EXEC="server --cluster-init --write-kubeconfig-mode 644" sh -`
- Run: `journalctl -u k3s | grep "Running kube-apiserver" | tail -n1 | grep -E 'tls-cert-file|tls-private-key-file'` -- Expect an output but there is not one.

**Additional context / logs:**

This was found initially by running a CIS scan through Rancher on a cluster created this way. 
In a non-hardened cluster brought up this way, it does have these values:
```
... --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
```

These files are both present on the hardened node, just not in the kube-apiserver process:
```
sudo ls -la /var/lib/rancher/k3s/server/tls/
total 116
drwx------ 4 root root 4096 Apr 29 15:39 .
drwxr-xr-x 7 root root  101 Apr 29 15:39 ..
...
-rw-r--r-- 1 root root 1283 Apr 29 15:39 serving-kube-apiserver.crt
-rw------- 1 root root  227 Apr 29 15:39 serving-kube-apiserver.key
...
```

Config.yaml in hardened setup:
```yaml
protect-kernel-defaults: true
secrets-encryption: true
kube-apiserver-arg:
  - 'audit-log-path=/var/lib/rancher/k3s/server/logs/audit-log'
  - 'audit-log-maxage=30'
  - 'audit-log-maxbackup=10'
  - 'audit-log-maxsize=100'
  - 'request-timeout=300s'
  - 'service-account-lookup=true'
  - 'enable-admission-plugins=NodeRestriction,PodSecurityPolicy,NamespaceLifecycle,ServiceAccount'
kube-controller-manager-arg:
  - 'terminated-pod-gc-threshold=10'
  - 'use-service-account-credentials=true'
kubelet-arg:
  - 'streaming-connection-idle-timeout=5m'
  - 'make-iptables-util-chains=true'
```
