### ISSUE TITLE
Pulling Multi-Stage docker image from private registry

### ISSUE THREAD

**Issue by armourshield** [k3s-io/k3s#3326]
Problem faced explained in brief:

Runtime used containerd.
Pulling a multi stage docker image for mysql gets ignored of the COPY layer which is in private-registry. 

When pulled in a different env with clean installation of only docker, docker pull gives the full images with the COPY layer.

**Environmental Info:**
K3s Version: 
```
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8
```

Node(s) CPU architecture, OS, and Version: 
```
Linux k3master.124 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
```
1 Server - Name: k3master in Ubuntu 20.04 LTS
```

**Describe the bug:**
Multi stage docker image for mysql only pulls the last stage without the COPY layer when containerd is the runtime for k3s. Switching to docker runtime the images show the COPY layer, but facing authentication required issue. registries.yaml has been placed in /etc/rancher/k3s/. As well as docker/daemon.json has been uploaded as secret for K3s.

**Steps To Reproduce:**
- Installed K3s with HA DB (PostgreSQL): 
```bash
curl -sfL https://get.k3s.io | sh -s - --datastore-endpoint=postgres://<postgresql:connectionstring> --kube-apiserver-arg enable-aggregator-routing=true --disable metrics-server
```
- Adding TLS verified registry
```yaml
mirrors:
  registry.com:443:
    endpoint:
      - "https://registry.com:443"
configs:
  "registry.com:443":
     auth:
       username: username # this is the registry username
       password: password # this is the registry password
     tls:
       cert_file: "/etc/docker/certs.d/registry.com/domain.cert"
       key_file: "/etc/docker/certs.d/registry.com/domain.key"
       ca_file: "/etc/docker/certs.d/registry.com/ca.crt"
       insecure_skip_verify: true
```

- Adding insecure registry for self signed certs
```
{
  "insecure-registries" : ["https://registry.com443"]
}
```

- Build docker file and push to registry using the following link
[Dockerfile Info](https://github.com/iamdvr/prepopulated-mysql-container-example)

- Basic deployment yaml for the current image
I have left out the parts spec.container[0].env for mysql. This just demo of the yaml which is being used.
```yaml
apiVersion: apps/v1beta2
  kind: Deployment
  metadata:
    name: mysql-prepopulated-demo
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mysql
    template:
      metadata:
        labels:
          app: mysql
      spec:
        containers:
        - name: mysql
          image: registry.com443/docker-repo/mysql-populated
          ports: []
          resources:
            limits: {}
        imagePullSecrets:
        - name: myregistrykey
```

**Expected behavior:**
To pull the full image from the private registry and run the deployment. The mysql-pod will have a prepopulated DB which was burned as layer in the image.

**Actual behavior:**
- With containerd runtime:
  - Authentication works.
  - The image pulled doesn't not contain the COPY layer data. instead just has vanilla mysql image
 
- With docker runtime
   - Authentication Failed:
   - Failed to pull the image (ImagePullBackOff), due to authentication required error.
   - With only docker in a different server the whole image is pulled and container reflect COPY layer from the image.
   - When running command from crictl
   ```
   k3s crictl img
   ```
   Shows full image which was pulled during containerd runtime

**Additional context / logs:**
Container version
```
k3s crictl version

Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.4.3-k3s3
RuntimeApiVersion:  v1alpha2
```
