### ISSUE TITLE
DNS resolution not working from within a Pod when a specific `NetworkPolicy` exists

### ISSUE THREAD

**Issue by mic4ael** [k3s-io/k3s#3361]
**Environmental Info:**

K3s Version:
```
k3s version v1.20.7+k3s1 (aa768cbd)
go version go1.15.12
```

Node(s) CPU architecture, OS, and Version: 
```
Linux raspberrypi 5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux
```

Cluster Configuration:

`1 master (rpi 3 1GB of RAM), 2 agents (rpi 4, 2GB of RAM)`

**Describe the bug:**

`NetworkPolicy` blocks DNS resolution from within pods.

**Steps To Reproduce:**

1. Create a namespace (not necessary)
2. Create a `NetworkPolicy` to allow all outgoing and ingoing traffic to/from pods inside the namespace

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: np
spec:
  egress:
  - {}
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

```bash
kubectl describe NetworkPolicy -n np 
Name:         allow-egress
Namespace:    np
Created on:   2021-05-22 19:00:32 +0200 CEST
Labels:       <none>
Annotations:  <none>
Spec:
  PodSelector:     <none> (Allowing the specific traffic to all pods in this namespace)
  Allowing ingress traffic:
    To Port: <any> (traffic allowed to all ports)
    From:
      PodSelector: <none>
  Allowing egress traffic:
    To Port: <any> (traffic allowed to all ports)
    To: <any> (traffic not restricted by destination)
  Policy Types: Ingress, Egress
```

3. Create a temporary `busybox` pod

```bash
kubectl run -it -n np --rm busybox --restart=Never --image=busybox
```

4. `wget -O- google.com` results in `wget: bad address 'google.com'`. However if I do `kubectl run busybox -it -n np --rm --restart=Never --image=busybox --command -- ping example.com` it works without any issues

**Expected behavior:**

I can resolve any domain from within a pod without any issues.

**Actual behavior:**

Internal DNS server can't be reached due to the `NetworkPolicy`.

**Additional context / logs:**
