### ISSUE TITLE
[k3s-upgrade] v1.17.2 -> v1.20.7+k3s1 - kube api - high request duration

### ISSUE THREAD

**Issue by BeardyC** [k3s-io/k3s#3365]
**Environmental Info:**
K3s Version: 
v1.20.7+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 masters, 2 agents, 3 external etcd cluster

**Describe the bug:**
Was on v1.17.2 and upgraded using [k3s-upgrade](https://github.com/k3s-io/k3s-upgrade). Everything upgraded as expected however the api response time seems to be way too high on one of the nodes post upgrade.

**Steps To Reproduce:**

- Installed K3s: 
- Upgraded k3s with the following plan:
```yaml
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
    name: k3s-server
    namespace: system-upgrade
    labels:
        k3s-upgrade: server
spec:
    concurrency: 1
    version: v1.20.7+k3s1
    nodeSelector:
        matchExpressions:
            - { key: k3s-upgrade, operator: Exists }
            - {
                  key: k3s-upgrade,
                  operator: NotIn,
                  values: ['disabled', 'false'],
              }
            - { key: k3s.io/hostname, operator: Exists }
            - { key: k3os.io/mode, operator: DoesNotExist }
            - {
                  key: node-role.kubernetes.io/master,
                  operator: In,
                  values: ['true'],
              }
    serviceAccountName: system-upgrade
    cordon: true
    #  drain:
    #    force: true
    upgrade:
        image: rancher/k3s-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
    name: k3s-agent
    namespace: system-upgrade
    labels:
        k3s-upgrade: agent
spec:
    concurrency: 1 # in general, this should be the number of workers - 1
    version: v1.20.7+k3s1
    nodeSelector:
        matchExpressions:
            - { key: k3s-upgrade, operator: Exists }
            - {
                  key: k3s-upgrade,
                  operator: NotIn,
                  values: ['disabled', 'false'],
              }
            - { key: k3s.io/hostname, operator: Exists }
            - { key: k3os.io/mode, operator: DoesNotExist }
            - {
                  key: node-role.kubernetes.io/master,
                  operator: NotIn,
                  values: ['true'],
              }
    serviceAccountName: system-upgrade
    prepare:
        # Since v0.5.0-m1 SUC will use the resolved version of the plan for the tag on the prepare container.
        # image: rancher/k3s-upgrade:v1.17.4-k3s1
        image: rancher/k3s-upgrade
        args: ['prepare', 'k3s-server']
    drain:
        force: true
        skipWaitForDeleteTimeout: 60 # set this to prevent upgrades from hanging on small clusters since k8s v1.18
    upgrade:
        image: rancher/k3s-upgrade

```
I've set the debug flag on the master nodes but nothing is screaming out at me.

Metrics post upgrade - upgrade finishes at 12:35
![image](https://user-images.githubusercontent.com/26225459/119358003-1222ec80-bca0-11eb-9ce9-fc1536498afb.png)

Comparison vs other cluster which hasn't been upgraded yet 
![image](https://user-images.githubusercontent.com/26225459/119358473-91b0bb80-bca0-11eb-9c71-e080282881bf.png)

Any ideas of why this would be a thing post upgrade?
