### ISSUE TITLE
Some of the options in config.toml seem to be ignored

### ISSUE THREAD

**Issue by nsoubelet** [k3s-io/k3s#3378]
**Environmental Info:**
K3s Version: v1.19.5+k3s2 (746cf403)

Node(s) CPU architecture, OS, and Version: 
Linux 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
5 masters - 15+ nodes

**Describe the bug:**
When using Google's gVisor for container sandboxing, there is a way to activate certain flags via configuration. That config location can be specified in ` [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc.options]` but in my case that option is being ignored and I do not know where to see the reason. Logs show nothing in particular.

**Steps To Reproduce:**
- Edit the file /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
- Add: 
```
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc.options]
    TypeUrl = "io.containerd.runsc.v1.options"
    ConfigPath = "/etc/containerd/runsc.toml"
```
- Create the file /etc/containerd/runsc.toml
- Add something to it like:
```
[runsc_config]
  net-raw = "true"
[debug]
  level = "debug"
```
- Restart the agent
- Run a pod using gVisor `runtimeClassName` and try to add NET_RAW CAP. This won't be possible since the config is not being picked up.

**Expected behavior:**
Configuration passed to gVisor being added when calling `runsc` and loaded from k3s toml template, since I guess that's the only place where it can be configured.

**Actual behavior:**
gVisor works fine but configuration is being ignored. K3s logs shows no errors or warning messages.

**Comment by brandond** [comment]
What steps did you follow to install runsc and install the plugin such that the containerd build into k3s can find it?

**Comment by brandond** [comment]
Well, you can always look at the config file used by containerd - its right next to the template file at `/var/lib/rancher/rke2/agent/etc/containerd/config.toml`. If you see the sections in there, they should be used. If they're not, then that's an issue with containerd.

**Comment by nsoubelet** [comment]
Hello @brandond, the file you are pointing out here is dynamically created using the template. I had a look and effectively all the values I put in the template are written in that file during agent's initialization.
If containerd reads configuration from that file and k3s does nothing in the middle, then as you say it is probably related to containerd/gVisor rather than k3s.

**Comment by brandond** [comment]
Yes, all k3s does is process the template to generate the config file, then runs containerd pointed at that file. Are there any additional logs or behaviors that might suggest where the problem lies?

**Comment by nsoubelet** [comment]
Hi @brandond,
What I would need to figure out how to do is confirm that effectively contained is picking up those values from `/var/lib/rancher/k3s/agent/etc/containerd/config.toml`, so where could I see containerd's logs? (not actual logs from containers, but containerd's process logs since maybe there I can find messages regarding the gVisor configuration section).

**Comment by kristofre** [comment]
I have a slightly related question here: https://github.com/k3s-io/k3s/discussions/3507

**Comment by nsoubelet** [comment]
Yes, @kristofre seems to be the same root problem. As I said the previous comment I am not able to find logs re the `config.tml` loading process, maybe there resides the key to the problem.

**Comment by brumhard** [comment]
Worked fine for me.
I just copied the [default template](https://github.com/k3s-io/k3s/blob/master/pkg/agent/templates/templates_linux.go) from to `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl`.
Then I added the following lines to the end of it:
```toml
[plugins.cri.containerd.runtimes.runsc]
  runtime_type = "io.containerd.runsc.v1"
```

After I reloaded the service (`sudo systemctl restart k3s.service`) containerd picked up the new config from `/var/lib/rancher/k3s/agent/etc/containerd/config.toml`. The configuration can be confirmed by running `sudo k3s crictl info |jq '.config.containerd.runtimes'` which should now display `runsc` as additional runtime.

**Comment by nsoubelet** [comment]
@brumhard, apparently you did not capture the problem.
It clearly says **"some of the options"** but you say that worked for you just because one thing worked.
Please read the issue's body carefully, there it's explained what the problem is, which is not certainly the one you are describing.

**Comment by Oats87** [comment]
@nsoubelet 

`containerd` logs should be located in `/var/lib/rancher/k3s/agent/containerd/containerd.log` by default.

**Comment by nsoubelet** [comment]
@Oats87 yes, that one I know.
What I mentioned in this thread is that I am not able to find logs entries related to `config.tml` loading process, not the containerd's log file itself.
Thanks

**Comment by rlex** [comment]
This seems to work for me:
```toml
[plugins.opt]
  path = "/var/lib/rancher/k3s/agent/containerd"
[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "rancher/mirrored-pause:3.1"
[plugins.cri.containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true
[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
[plugins.cri.containerd.runtimes.runsc]
  runtime_type = "io.containerd.runsc.v1"
[plugins.cri.containerd.runtimes.runsc-hostnetwork]
  runtime_type = "io.containerd.runsc.v1"
#gvisor stuff 
[plugins.cri.containerd.runtimes.runsc.options]
  TypeUrl = "io.containerd.runsc.v1.options"
  ConfigPath = "/var/lib/rancher/k3s/agent/etc/containerd/runsc.toml"
[plugins.cri.containerd.runtimes.runsc-hostnetwork.options]
  TypeUrl = "io.containerd.runsc.v1.options"
  ConfigPath = "/var/lib/rancher/k3s/agent/etc/containerd/runsc-hostnetwork.toml"
```

I have two gvisor runsc because one is full isolation and 2nd have host-network capabilities

hostnetwork version config:
```toml
[runsc_config]
  network = "host"
```

And it picks it up correctly and works with host-network.
