### ISSUE TITLE
traefik config help

### ISSUE THREAD

**Issue by liyin37** [k3s-io/k3s#3379]
**Environmental Info:**
K3s Version: 
k3s version v1.21.1+k3s1 (75dba57f)
go version go1.16.4

Node(s) CPU architecture, OS, and Version: 
Linux k3s 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
only one server

**Describe the bug:**
when I config the ingressroute and tlsstore，the application I visit，the tls is not mine，it shows default traefik cert

**Steps To Reproduce:**
use below yaml to create it :
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: apisix-tlsstore
spec:
  defaultCertificate:
    secretName: example-com
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-apisix-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: apisix 
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`apisix.172.24.64.73.nip.io`)
    kind: Rule
    services:
    - name: apisix
      port: 9080
    middlewares: 
    - name: redirect-apisix-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: apisix-tls   
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`apisix.172.24.64.73.nip.io`)
    kind: Rule
    services:
    - name: apisix
      port: 9080
tls:
  store:
    name: apisix-tlsstore
```
###
web  visit it  shows this
![image](https://user-images.githubusercontent.com/42507175/120095103-90770700-c156-11eb-8a0f-7f0db46653d1.png)

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**
