### ISSUE TITLE
Port 53 not working from external IP

### ISSUE THREAD

**Issue by Slyke** [k3s-io/k3s#3384]
Sorry if this is the wrong repo to ask this. I'm quite new to Kubernetes and not sure where the problem is. I have been at this for a few days now and after learning a lot about Kubernetes, I'm stuck trying to troubleshoot this issue. I suspect it is a bug, as I've had to install newer versions (of MetalLB, k3s etc) due to various bugs (selfRef Link issues, Traefik messing with MetalLB etc).

The problem is that I can login to Pihole with the browser, but when doing DNS queries using the same IP, the queries timeout. I have checked that the dnsmasq service is running inside Pihole by exec'ing into the pod and testing dig to localhost. The port configuration is the same for http as it is for DNS (with the exception that the DNS port allows for TCP and UDP traffic). I'm not sure why it's not working.

**Environmental Info:**
K3s Version: 
k3s version v1.20.7+k3s1 (aa768cbd)
go version go1.15.12

Node(s) CPU architecture, OS, and Version: 
Linux k-m-001 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux

Cluster Configuration:
3 RPis (RPi4 8GB). 1 Master, 2 Workers.
Cluster installed with MetalLB (Config below).
traefik and servicelb not deployed (Master was installed with `--no-deploy=traefik,servicelb`)

**Describe the bug:**
Port 80 works fine on the assigned IP and can login to PiHole. Port 53 doesn't work (Tested with Dig on Master). I know Pihole is working correctly since dig command works fine from within the pod:
```
[2021-06-01T03:00:25+0100] [pi@k-m-001] k3s_config $ kubectl exec --stdin --tty pihole-64c4755945-2hlzv -n home -- /bin/bash
root@pihole-64c4755945-2hlzv:/# dig @localhost google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u3-Debian <<>> @localhost google.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32906
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             268     IN      A       142.250.217.78

;; Query time: 32 msec
;; SERVER: ::1#53(::1)
;; WHEN: Tue Jun 01 02:01:09 UTC 2021
;; MSG SIZE  rcvd: 55

root@pihole-64c4755945-2hlzv:/# exit
exit
```

Namespace with Pihole running:
```
[2021-06-01T03:07:16+0100] [pi@k-m-001] k3s_config $ kubectl get services,pods,deployments -n home -o wide
NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                     AGE   SELECTOR
service/pihole-tcp   LoadBalancer   10.43.24.147   10.7.7.245    53:30535/TCP,80:31154/TCP   18h   app=pihole

NAME                          READY   STATUS    RESTARTS   AGE   IP          NODE      NOMINATED NODE   READINESS GATES
pod/pihole-64c4755945-2hlzv   1/1     Running   0          18h   10.42.3.6   k-w-002   <none>           <none>

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES          SELECTOR
deployment.apps/pihole   1/1     1            1           18h   pihole       pihole/pihole   app=pihole
```

MetalLB namespace:
```
[2021-06-01T03:07:31+0100] [pi@k-m-001] k3s_config $ kubectl get services,pods,deployments -n metallb-system -o wide
NAME                              READY   STATUS    RESTARTS   AGE   IP          NODE      NOMINATED NODE   READINESS GATES
pod/speaker-lbs6c                 1/1     Running   0          19h   10.7.5.10   k-m-001   <none>           <none>
pod/controller-64f86798cc-h4jlh   1/1     Running   0          19h   10.42.0.5   k-m-001   <none>           <none>
pod/speaker-d4x7g                 1/1     Running   0          18h   10.7.5.21   k-w-001   <none>           <none>
pod/speaker-gzf9q                 1/1     Running   0          18h   10.7.5.22   k-w-002   <none>           <none>

NAME                         READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                      SELECTOR
deployment.apps/controller   1/1     1            1           19h   controller   metallb/controller:v0.9.6   app=metallb,component=controller
```

Nothing weird showing up in the metallb controller logs.

**Steps To Reproduce:**

- Installed K3s: 
Installed MetalLB with the standard install (version `0.9.6`):
Config Map:
```
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.7.7.10-10.7.7.254
```

PiHole deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: home
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pihole
    spec:
      containers:
      - env:
        - name: ServerIP
          value: 10.7.7.245
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-webpassword
        image: pihole/pihole
        imagePullPolicy: IfNotPresent
        name: pihole
        ports:
        - containerPort: 80
          name: pihole-http
          protocol: TCP
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 443
          name: pihole-ssl
          protocol: TCP
        - containerPort: 67
          name: client-udp
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pihole
          name: config
        - mountPath: /etc/dnsmasq.d/02-custom.conf
          name: custom-dnsmasq
          subPath: 02-custom.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pihole-config
      - configMap:
          defaultMode: 420
          name: pihole-custom-dnsmasq
        name: custom-dnsmasq
status: {}
```

Pihole service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-tcp
  namespace: home
spec:
  externalTrafficPolicy: Local
  ports:
  - name: dns
    protocol: TCP
    port: 53
    targetPort: dns
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: dns-udp
  - name: pihole-http
    protocol: TCP
    port: 80
    targetPort: pihole-http
  selector:
    app: pihole
  loadBalancerIP: 10.7.7.245
  type: LoadBalancer
```

**Expected behavior:**
Should be able to use dig, or nslookup (on Windows) to `10.7.7.245` and have it resolve domain names such as google.com

**Actual behavior:**
Dig command fails with timeout

**Additional context / logs:**
```
[2021-06-01T03:11:39+0100] [pi@k-m-001] k3s_config $ kubectl describe service/pihole-tcp -n home
Name:                     pihole-tcp
Namespace:                home
Labels:                   app=pihole
Annotations:              <none>
Selector:                 app=pihole
Type:                     LoadBalancer
IP Families:              <none>
IP:                       10.43.24.147
IPs:                      10.43.24.147
IP:                       10.7.7.245
LoadBalancer Ingress:     10.7.7.245
Port:                     dns  53/TCP
TargetPort:               dns/TCP
NodePort:                 dns  30535/TCP
Endpoints:                10.42.3.6:53
Port:                     pihole-http  80/TCP
TargetPort:               pihole-http/TCP
NodePort:                 pihole-http  31154/TCP
Endpoints:                10.42.3.6:80
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     32563
Events:
  Type    Reason        Age                 From             Message
  ----    ------        ----                ----             -------
  Normal  nodeAssigned  18m (x32 over 18h)  metallb-speaker  announcing from node "k-w-002"
```
