### ISSUE TITLE
GitLab dependency proxy as docker.io mirror leads to "unexpected commit digest"

### ISSUE THREAD

**Issue by mrtndwrd** [k3s-io/k3s#3490]
I'm trying to use the [private registry feature](https://rancher.com/docs/k3s/latest/en/installation/private-registry/) together with a [GitLab dependency proxy](https://docs.gitlab.com/ee/user/packages/dependency_proxy/#authenticate-with-the-dependency-proxy). The GitLab dependency proxy is a piece of software that automatically serves images from its cache, or if it does not have them, downloads them from docker.io and then serves them.

My goal is for k3s to download images from `docker.io` from my GitLab dependency proxy instead.

This is my `/etc/rancher/k3s/registries.yaml`:

```yaml
---
mirrors:
  docker.io:
    endpoint:
      - "https://open.greenhost.net/openappstack/dependency_proxy/containers"
configs:
  "open.greenhost.net":
    auth:
      username: <username>
      password: <password>
```

With this configuration, I can successfully pull images from the dependency proxy directly: 

```
root@422-cache-docker-images-for-ci:~# crictl pull open.greenhost.net/openappstack/dependency_proxy/containers/hello-world
Image is up to date for sha256:d1165f2212346b2bab48cb01c1e39ee8ad1be46b87873d9ca7a4e434980a7726
```

But it is my understanding that I should also be able to pull the same image running the following: 

```
root@422-cache-docker-images-for-ci:~# crictl pull hello-world
FATA[2021-06-22T09:07:52.560236493Z] pulling image: rpc error: code = FailedPrecondition desc = failed to pull and unpack image "docker.io/library/hello-world:latest": failed commit on ref "unknown-sha256:1374183ca5faaa9233660c2393a54c0f128a1c04eefa88ccfbdd9f0bd15b9953": unexpected commit digest sha256:23beff2f7645b0ec794d7100613f5d51f513a41da24debc57f18f953e00f4c6e, expected sha256:1374183ca5faaa9233660c2393a54c0f128a1c04eefa88ccfbdd9f0bd15b9953: failed precondition 
```

But as you can see, it does not work.

My theory is that there is a problem with how k3s authenticates against the dependency proxy. GitLab likes us to authenticate against `open.greenhost.net` (in my case), but download the images from `https://open.greenhost.net/openappstack/dependency_proxy/containers`. Could that discrepancy cause the problem, or did I just configure something wrong?

### System info: 

OS: Debian 10

```
k3s --version
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8
```

**Comment by brandond** [comment]
I would suggest taking this question to the [containerd repo](https://github.com/containerd/containerd/), as authentication and image pulling is all handled by the embedded containerd, not any code present in k3s itself.

**Comment by mrtndwrd** [comment]
Thank you @brandond ! 

While I was rewriting this issue for that repository, I actually found out that a newer version of k3s supported exactly what I need. 

I stumbled upon https://github.com/k3s-io/k3s/pull/3064 and rewrote my `registries.yaml`:

```yaml
---
mirrors:
  docker.io:
    endpoint:
      # Hardcoded, should be fixed before merging
      - "open.greenhost.net:443"
    rewrite:
      # We need to remove the `server` part from the `endpoint` part, so what we
      # end up with is a path like ""/openappstack/dependency_proxy/containers/$1"
      "^(.*)$": "/openappstack/dependency_proxy/containers/$1"
configs:
  "open.greenhost.net:443":
    auth:
      username: xxx
      password: xxx
```

Now the endpoint and configs are the same, and my containers are pulled from the right address.
