### ISSUE TITLE
Provide an example how to use k3s (to run a web-app)

### ISSUE THREAD

**Issue by bluepuma77** [k3s-io/k3s#3504]
**Is your feature request related to a problem? Please describe.**
As a developer I would like to use k3s to run my web-app in a cluster. k3s has some pre-configurations and some included tools like Traefik, but there is no example available of how to run a web-app with k3s. 

When searching for k3s and Traefik, about 80% of the results tell you how to disable Traefik, but nothing shows how to simply use k3s with Traefik. 

I am not sure about search results with k8s and Traefik. I want to make sure to use k3s best practice solution and stay as close to bare-bone k3s as possible. I am sure you have good reasons to include Traefik.

For me as a developer k3s is a tool to run and scale my web-app, but somehow the current documentation falls just short of the last bit.

**Describe the solution you'd like**
I would like to see a page in the Rancher k3s docs that shows how to run a web-app in a k3s cluster, with the required CLI commands and yaml files (ingress, service, deployment) as example. Simply route SSL-enabled requests via domain to containers of a web-app. Could be within the Helm section.

**Describe alternatives you've considered**
- As stated above, search results for k3s and Traefik didn't provide any examples (using Traefik)
- Rancher Academy has multi-hour courses (how to replace Traefik ;-), I want a page with the CLI and yaml templates
- Requests to Rancher and Suse sales stayed unanswered, even though I am willing to pay for support

**Additional context**
![Rancher-k3s](https://user-images.githubusercontent.com/5221187/123233416-58a37b00-d4da-11eb-8e9f-e9fa9352c931.png)

**Comment by zhonghuali** [comment]
@dweomer  I cannot find a useful example how to use ingress with  k3s and Traefik ingress

**Comment by pedroresende** [comment]
> @dweomer I cannot find a useful example how to use ingress with k3s and Traefik ingress

I also have that problem, so far what I've got is the following but it's not working

```
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: resendebiz
  #  namespace: resendebiz
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resendebiz
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: resendebiz
  #  namespace: resendebiz
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: traefiklabs
    task: resendebiz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resendebiz
  #  namespace: resendebiz
  labels:
    app: resendebiz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resendebiz
  template:
    metadata:
      labels:
        app: resendebiz
    spec:
      containers:
        - name: resendebiz
          image: pmmresende/resende.biz:latest
          ports:
            - containerPort: 3000
```

since

```
kubectl get all --all-namespaces
NAMESPACE     NAME                                          READY   STATUS      RESTARTS   AGE
kube-system   pod/local-path-provisioner-84bb864455-jnxmj   1/1     Running     0          12h
kube-system   pod/helm-install-traefik-crd--1-j7svg         0/1     Completed   0          12h
kube-system   pod/helm-install-traefik--1-wxbts             0/1     Completed   2          12h
kube-system   pod/svclb-traefik-hh7pq                       2/2     Running     0          12h
kube-system   pod/metrics-server-ff9dbcb6c-jt8f7            1/1     Running     0          12h
kube-system   pod/coredns-96cc4f57d-gfdd2                   1/1     Running     0          12h
kube-system   pod/traefik-56c4b88c4b-s2mp2                  1/1     Running     0          12h
default       pod/resendebiz-67d7fdbb5f-8vkdt               1/1     Running     0          2m19s
default       pod/resendebiz-67d7fdbb5f-bj9bb               1/1     Running     0          2m19s

NAMESPACE     NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
default       service/kubernetes       ClusterIP      10.43.0.1       <none>          443/TCP                      12h
kube-system   service/kube-dns         ClusterIP      10.43.0.10      <none>          53/UDP,53/TCP,9153/TCP       12h
kube-system   service/metrics-server   ClusterIP      10.43.124.179   <none>          443/TCP                      12h
kube-system   service/traefik          LoadBalancer   10.43.91.227    192.168.1.252   80:32391/TCP,443:30399/TCP   12h
default       service/resendebiz       ClusterIP      10.43.85.199    <none>          80/TCP                       2m20s

NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          12h

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           12h
kube-system   deployment.apps/metrics-server           1/1     1            1           12h
kube-system   deployment.apps/coredns                  1/1     1            1           12h
kube-system   deployment.apps/traefik                  1/1     1            1           12h
resendebiz    deployment.apps/resendebiz               0/0     0            0           12h
default       deployment.apps/resendebiz               2/2     2            2           2m20s

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/local-path-provisioner-84bb864455   1         1         1       12h
kube-system   replicaset.apps/metrics-server-ff9dbcb6c            1         1         1       12h
kube-system   replicaset.apps/coredns-96cc4f57d                   1         1         1       12h
kube-system   replicaset.apps/traefik-56c4b88c4b                  1         1         1       12h
resendebiz    replicaset.apps/resendebiz-67d7fdbb5f               0         0         0       12h
default       replicaset.apps/resendebiz-67d7fdbb5f               2         2         2       2m20s

NAMESPACE     NAME                                 COMPLETIONS   DURATION   AGE
kube-system   job.batch/helm-install-traefik-crd   1/1           6m30s      12h
kube-system   job.batch/helm-install-traefik       1/1           7m38s      12h
```

You can see the 

```
default       service/resendebiz       ClusterIP      10.43.85.199    <none>          80/TCP                       2m20s
```

has no external IP and if I attempt to connect to the IP, I get a 404
