### ISSUE TITLE
0.3.0 : serviceaccount "tiller" not found

### ISSUE THREAD

**Issue by deas** [k3s-io/k3s#351]
**Describe the bug**
After installation of k3s `0.3.0`, tiller replicaset fails to create pods due to a missing service account

`Error creating: pods "tiller-deploy-7575566df7-" is forbidden: error looking up service account kube-system/tiller: serviceaccount "tiller" not found`

Hence, you cannot use the helm cli with tiller at all.

**To Reproduce**
Install 0.3.0 and try 

```
λ ~/ helm init --service-account tiller
$HELM_HOME has been configured at /home/deas/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
λ ~/ helm list                         
Error: could not find tiller
λ ~/  
```
**Expected behavior**
Tiller pod running and working.

**Comment by superseb** [comment]
Did you follow the steps to install using RBAC as described on https://github.com/helm/helm/blob/master/docs/rbac.md? The command also shows it is already installed (possibly in a wrong way). If you run `helm reset --force` and retry using the correct prerequisites, does that work? If not, can you supply exact commands used?

**Comment by deas** [comment]
Applying the rbac yaml and deleting the ReplicaSet fixed the issue for me. Just wanted to mention the issue because using helm might be one of the first things people might be trying so this should probably be working out of the box.

Thanks!

**Comment by giminni** [comment]
@deas can you explain how to install tiller on k3s. 
I tried applying the tiller serviceaccount over a fresh k3s installation. 
The tiller deploy pod is crashing. 
Is it true to set KUBECONFIG to /etc/rancher/k3s/k3s.yaml before installing helm?

**Comment by egeneralov** [comment]
Hello.

This not a k8s/k3s business. Only RBAC set-up for helm.

```
cat << EOF | kubectl apply -f -
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
EOF
```

And you be able to run `helm init --service-account tiller --upgrade --wait`
