### ISSUE TITLE
forwardedHeaders.insecure to true

### ISSUE THREAD

**Issue by papapumpnz** [k3s-io/k3s#3570]
**Environmental Info:**
K3s Version: k3s version v1.21.2+k3s1 (5a67e8dc)

**Describe the bug:**
Hi, I have nginx terminating SSL and forwarding to traefik in a k3s cluster. Traefik is overwriting the X-Forwarded-* headers and passing on X-Forwarded-Proto: http instead of passing this through from nginx.

**Steps To Reproduce:**
How do I enable forwardedHeaders.insecure to true using the K3s helm chart thats installed by default.

I have created a trafik-config.yaml file in /var/lib/rancher/k3s/server/manifests/ with
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    entryPoints:
      web:
        address: ":80"
        forwardedHeaders:
          insecure: true
```
This appears to be picked up and the helm-install-traefik pod is detecting the change in config and restarting but I never get the forwarded headers from nginx.

Any help would be appreciated.
