### ISSUE TITLE
Rancher UI inaccessible with default hardened k3s settings

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#3583]
**Environmental Info:**
K3s Version: 

v1.20.8+k3s1

Node(s) CPU architecture, OS, and Version: 

`Linux ip-172-31-15-125 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Ubuntu 20.04 LTS

Cluster Configuration:

2 servers, 1 agent, CIS hardened per https://rancher.com/docs/k3s/latest/en/security/hardening_guide/

**Describe the bug:**

Rancher UI fails to load when traefik is used as the ingress controller (which is the default). However, when ingress-nginx is used, rancher UI loads successfully.

**Steps To Reproduce:**

1. Install k3s as per the hardening guide. For simplicity's sake, this the config.yaml and policy.yaml (remove relevant flags when joining additional nodes)
    ```yaml
    # /etc/rancher/k3s/config.yaml
    cluster-init: true
    tls-san: <redacted>
    protect-kernel-defaults: true
    secrets-encryption: true
    kube-apiserver-arg:
      - 'audit-log-path=/var/lib/rancher/k3s/server/logs/audit-log'
      - 'audit-log-maxage=30'
      - 'audit-log-maxbackup=10'
      - 'audit-log-maxsize=100'
      - 'request-timeout=300s'
      - 'service-account-lookup=true'
      - 'enable-admission-plugins=NodeRestriction,PodSecurityPolicy,NamespaceLifecycle,ServiceAccount'
    kube-controller-manager-arg:
      - 'terminated-pod-gc-threshold=10'
      - 'use-service-account-credentials=true'
    kubelet-arg:
      - 'streaming-connection-idle-timeout=5m'
      - 'make-iptables-util-chains=true'
    ```
    ```yaml
    # /var/lib/rancher/k3s/server/manifests/policy.yaml
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: default-network-dns-policy
      namespace: kube-system
    spec:
      ingress:
      - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
      podSelector:
        matchLabels:
          k8s-app: kube-dns
      policyTypes:
      - Ingress
    ---
    apiVersion: policy/v1beta1
    kind: PodSecurityPolicy
    metadata:
      name: cis1.5-compliant-psp
    spec:
      privileged: false
      allowPrivilegeEscalation: false
      requiredDropCapabilities:
        - ALL
      volumes:
        - 'configMap'
        - 'emptyDir'
        - 'projected'
        - 'secret'
        - 'downwardAPI'
        - 'persistentVolumeClaim'
      hostNetwork: false
      hostIPC: false
      hostPID: false
      runAsUser:
        rule: 'MustRunAsNonRoot'
      seLinux:
        rule: 'RunAsAny'
      supplementalGroups:
        rule: 'MustRunAs'
        ranges:
          - min: 1
            max: 65535
      fsGroup:
        rule: 'MustRunAs'
        ranges:
          - min: 1
            max: 65535
      readOnlyRootFilesystem: false
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: psp:restricted
      labels:
        addonmanager.kubernetes.io/mode: EnsureExists
    rules:
    - apiGroups: ['extensions']
      resources: ['podsecuritypolicies']
      verbs:     ['use']
      resourceNames:
      - cis1.5-compliant-psp
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: default:restricted
      labels:
        addonmanager.kubernetes.io/mode: EnsureExists
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: psp:restricted
    subjects:
    - kind: Group
      name: system:authenticated
      apiGroup: rbac.authorization.k8s.io
    ---
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: intra-namespace
      namespace: kube-system
    spec:
      podSelector: {}
      ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                name: kube-system
    ---
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: intra-namespace
      namespace: default
    spec:
      podSelector: {}
      ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                name: default
    ---
    kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: intra-namespace
      namespace: kube-public
    spec:
      podSelector: {}
      ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                name: kube-public
    ---
    apiVersion: policy/v1beta1
    kind: PodSecurityPolicy
    metadata:
      name: system-unrestricted-psp
    spec:
      allowPrivilegeEscalation: true
      allowedCapabilities:
      - '*'
      fsGroup:
        rule: RunAsAny
      hostIPC: true
      hostNetwork: true
      hostPID: true
      hostPorts:
      - max: 65535
        min: 0
      privileged: true
      runAsUser:
        rule: RunAsAny
      seLinux:
        rule: RunAsAny
      supplementalGroups:
        rule: RunAsAny
      volumes:
      - '*'
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: system-unrestricted-node-psp-rolebinding
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system-unrestricted-psp-role
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:nodes
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: system-unrestricted-psp-role
    rules:
    - apiGroups:
      - policy
      resourceNames:
      - system-unrestricted-psp
      resources:
      - podsecuritypolicies
      verbs:
      - use
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: system-unrestricted-svc-acct-psp-rolebinding
      namespace: kube-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system-unrestricted-psp-role
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts
    ```
2. Install Rancher HA:
    ```
    helm repo add rancher-latest https://releases.rancher.com/server-charts/latest && \
    helm repo add jetstack https://charts.jetstack.io && \
    helm repo update && \
    kubectl create namespace cattle-system && \
    kubectl create namespace cert-manager && \
    kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.1/cert-manager.crds.yaml && \
    helm install \
      cert-manager jetstack/cert-manager \
      --namespace cert-manager \
      --version v1.1.1

    kubectl get pods --namespace cert-manager

    helm install rancher rancher-latest/rancher \
      --namespace cattle-system \
      --set hostname=<tls-san record>

    kubectl -n cattle-system rollout status deploy/rancher
    ```
3. After rancher is rolled out, all pods are up and running but the UI is not accessible at the hostname like it should be.

**Expected behavior:**

I expect Rancher UI to be accessible at the specified hostname.

**Actual behavior:**

UI is not accessible. I don't see any errors in Rancher logs. 

**Additional context / logs:**

If I deploy k3s without traefik: `disable: traefik` and then apply the below manifest to deploy ingress-nginx instead, the rancher UI is accessible:
```
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: kube-system
  set:
  valuesContent: |-
    fullnameOverride: ingress-nginx
    controller:
      kind: DaemonSet
      admissionWebhooks:
        failurePolicy: Ignore
      hostNetwork: true
      hostPort:
        enabled: true
      publishService:
        enabled: false
      service:
        enabled: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      config:
        use-forwarded-headers: "true"
        server-tokens: "false"
```

This is only a problem when using HARDENED k3s. 

Additionally, I can deploy the following manifest in the default namespace on the ingress-nginx cluster and access the pods via the ingress, but I get connection refused when deploying the same manifest in the traefik cluster:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: othertest-deploy
  labels:
    app: othertest
spec:
  selector:
    matchLabels:
      app: othertest
  template:
    metadata:
      labels:
        app: othertest
    spec:
      containers:
      - name: othertest
        image: maxross/mytestcontainer:unprivileged
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
 name: othertest-ingress-svc
 labels:
   app: othertest
spec:
 ports:
 - port: 8080
   targetPort: 8080
   protocol: TCP
   name: http
 selector:
   app: othertest
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: othertest-ingress
spec:
  rules:
  - host: test1.com
    http:
      paths:
      - backend:
          serviceName: othertest-ingress-svc
          servicePort: 8080
        pathType: ImplementationSpecific
```

traefik =cluster:
```
$ curl -H 'Host: test1.com' http://<ingress public ip>/name.html
curl: (7) Failed to connect to <ingress public ip> port 80: Connection refused
```
ingress-nginx cluster (resulting pod is running on the node whose IP is hit):
```
$ curl -H 'Host: test1.com' http://<ingress public ip>/name.html
othertest-deploy-sgntb
```
