### ISSUE TITLE
Expose kube-scheduler, kube-proxy and kube-controller metrics endpoints

### ISSUE THREAD

**Issue by onedr0p** [k3s-io/k3s#3619]
**Is your feature request related to a problem? Please describe.**

Unable to monitor the following components using `kube-prometheus-stack`:
- kube-scheduler
- kube-proxy
- kube-controller

**Describe the solution you'd like**

Add configuration options like in PR https://github.com/k3s-io/k3s/pull/2750 for each component so they are not only being bound to `127.0.0.1`

E.g.

```
k3s server \
--kube-controller-expose-metrics true
--kube-proxy-expose-metrics true
--kube-scheduler-expose-metrics true
```

In kube-prometheus-stack configuration all you have to do is configure the following:

```yaml
kubeControllerManager:
  enabled: true
  endpoints:
  - 192.168.42.10
  - 192.168.42.11
  - 192.168.42.12
  service:
    enabled: true
    port: 10252
    targetPort: 10252
kubeScheduler:
  enabled: true
  endpoints:
  - 192.168.42.10
  - 192.168.42.11
  - 192.168.42.12
  service:
    enabled: true
    port: 10252
    targetPort: 10252
kubeProxy:
  enabled: true
  endpoints:
  - 192.168.42.10
  - 192.168.42.11
  - 192.168.42.12
  service:
    enabled: true
    port: 10252
    targetPort: 10252
```

**Describe alternatives you've considered**

Deploying rancher-pushprox to get these metrics exposed but it's not very easy to do, or user-friendly

**Additional context**

I am willing to give a shot at opening a PR as it should be pretty close to https://github.com/k3s-io/k3s/pull/2750

Related to https://github.com/k3s-io/k3s/issues/425

**Comment by brandond** [comment]
That was necessary because we don't have a facility to pass raw arguments through to the embedded etcd. For Kubernetes components, you can already just do something like:
`--kube-controller-manager-arg=address=10.0.1.2 --kube-controller-manager-arg=bind-address=10.0.1.2`

**Comment by onedr0p** [comment]
@brandond I am probably mis-reading the code here but it looks like it hardcoded to `127.0.0.1`

https://github.com/k3s-io/k3s/blob/238dc2086e94a06b2e625bd46473ec24ba67eb86/pkg/daemons/control/server.go#L134-L135

Will setting the above options override this?

**Comment by brandond** [comment]
Yes, if you look a few lines down you can see where the user-provided args are appended to the slice. Since the user args come last, they are preferred over the defaults we provide..

https://github.com/k3s-io/k3s/blob/238dc2086e94a06b2e625bd46473ec24ba67eb86/pkg/daemons/control/server.go#L142

**Comment by onedr0p** [comment]
Thanks @brandond 🙏🏼 

# kube-prometheus-stack helm values

```yaml
kubeApiServer:
  enabled: true
kubeControllerManager:
  enabled: true
  endpoints:
  - 192.168.42.10
  - 192.168.42.11
  - 192.168.42.12
kubeScheduler:
  enabled: true
  endpoints:
  - 192.168.42.10
  - 192.168.42.11
  - 192.168.42.12
kubeProxy:
  enabled: true
  endpoints:
  - 192.168.42.10
  - 192.168.42.11
  - 192.168.42.12
kubeEtcd:
  enabled: true
  endpoints:
  - 192.168.42.10
  - 192.168.42.11
  - 192.168.42.12
  service:
    enabled: true
    port: 2381
    targetPort: 2381
```

# k3s settings

```yaml
kube-controller-manager-arg:
- "address=0.0.0.0"
- "bind-address=0.0.0.0"
kube-proxy-arg:
- "metrics-bind-address=0.0.0.0"
kube-scheduler-arg:
- "address=0.0.0.0"
- "bind-address=0.0.0.0"
etcd-expose-metrics: true
```

**Comment by rlex** [comment]
For anyone stumbling upon same issue (because it pops on google first search page)
In case of v1.22 you will also need to add 
```
          serviceMonitor:
            enabled: true
            https: true
            insecureSkipVerify: true
```
to both kubeControllerManager and kubeScheduler because now it forces https. Also, ports have changed, so my config looks like:

```
      - kubeControllerManager:
          enabled: true
          endpoints:
            - 172.25.25.61
            - 172.25.25.62
            - 172.25.25.63
          service:
            enabled: true
            port: 10257
            targetPort: 10257
          serviceMonitor:
            enabled: true
            https: true
            insecureSkipVerify: true
      - kubeScheduler:
          enabled: true
          endpoints:
            - 172.25.25.61
            - 172.25.25.62
            - 172.25.25.63
          service:
            enabled: true
            port: 10259
            targetPort: 10259
          serviceMonitor:
            enabled: true
            https: true
            insecureSkipVerify: true
```

Additionally, "address=0.0.0.0" can be dropped because it's deprecated now, see https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

Verified on kube-prometheus-stack 20.0.1 and k3s 1.22.3

**Comment by untcha** [comment]
@onedr0p: how do I exactly set the k3s controller settings on my master nodes? Not during installation but in an running environment. With the k3s `config.yaml`?

from your and @rlex comments I understand that the configuration needs to look like this, correct?:

```yaml
kube-controller-manager-arg:
- "bind-address=0.0.0.0"
kube-proxy-arg:
- "metrics-bind-address=0.0.0.0"
kube-scheduler-arg:
- "bind-address=0.0.0.0"
etcd-expose-metrics: true
```

**Comment by onedr0p** [comment]
Yes but I'm k3s 1.22 some defaults in kube prometheus stack need to be changed:

https://github.com/onedr0p/home-ops/issues/2378

**Comment by untcha** [comment]
The changes in the kube prometheus stack seem to be clear to me. I am /was struggling with the k3s config.
Is it enough to create the config.yaml with just the above configuration, or do I need to restart k3s on each master, or the node itself?

**Comment by onedr0p** [comment]
Depends on how you installed k3s, you need to tell k3s to look for the `config.yaml`

**Comment by brandond** [comment]
You don't need to tell k3s to look for config.yaml if you place it at `/etc/rancher/k3s/config.yaml`. A restart is required to make any changes, regardless of whether you use CLI flags, or a config file, or both.

**Comment by untcha** [comment]
Worked like charm. Thank you guys!

**Comment by kladiv** [comment]
@onedr0p does this solution hit the problem explained in the issue below?
- https://github.com/k3s-io/k3s/issues/2262

Thank you

**Comment by Jojoooo1** [comment]
seems like event after following all the configuration it still does not detect kube-state-metrics  -> 

    **serviceMonitor/observability/prometheus-stack-kube-state-metrics/0 (0 / 18 active targets)**
    serviceMonitor/observability/prometheus-stack-alertmanager/0 (1 / 18 active targets)
    serviceMonitor/observability/prometheus-stack-apiserver/0 (1 / 1 active targets)
    serviceMonitor/observability/prometheus-stack-coredns/0 (1 / 14 active targets)
    serviceMonitor/observability/prometheus-stack-kube-controller-manager/0 (1 / 14 active targets)
    serviceMonitor/observability/prometheus-stack-kube-etcd/0 (1 / 14 active targets)
    serviceMonitor/observability/prometheus-stack-kube-proxy/0 (1 / 14 active targets)
    serviceMonitor/observability/prometheus-stack-kube-scheduler/0 (1 / 14 active targets)
    serviceMonitor/observability/prometheus-stack-kubelet/0 (1 / 14 active targets)
    serviceMonitor/observability/prometheus-stack-kubelet/1 (1 / 14 active targets)
    serviceMonitor/observability/prometheus-stack-kubelet/2 (1 / 14 active targets)
    serviceMonitor/observability/prometheus-stack-operator/0 (1 / 18 active targets)
    serviceMonitor/observability/prometheus-stack-prometheus-node-exporter/0 (1 / 18 active targets)
    serviceMonitor/observability/prometheus-stack-prometheus/0 (1 / 18 active targets)
    serviceMonitor/observability/prometheus-stack-grafana/0 (0 / 18 active targets)

**Comment by Jojoooo1** [comment]
Event after setting the kubeEtcd with server config and helm chart as defined few messages earlier seems to not work correctly.


![Screenshot from 2022-01-17 19-07-08](https://user-images.githubusercontent.com/17641873/149842037-f2190b40-3b01-4bae-8979-4b5adde78bd2.png)

**Comment by kladiv** [comment]
@Jojoooo1 did you setup single-node or multi-node cluster?
In single-node setup there's no etcd.

**Comment by Jojoooo1** [comment]
Thanks! I actually had a single node!

**Comment by rlex** [comment]
strictly speaking, k3s single-node can have etcd, but only if you added cluster-init parameter to k3s args / config / env

**Comment by rthamrin** [comment]
where can I edit this file, for my k3s controller manager?

```
k3s controllers settings
kube-controller-manager-arg:
- "address=0.0.0.0"
- "bind-address=0.0.0.0"
kube-proxy-arg:
- "metrics-bind-address=0.0.0.0"
kube-scheduler-arg:
- "address=0.0.0.0"
- "bind-address=0.0.0.0"
etcd-expose-metrics: true
```

**Comment by rthamrin** [comment]
> > where can I edit this file, for my k3s controller manager?
> > ```
> > k3s controllers settings
> > kube-controller-manager-arg:
> > - "address=0.0.0.0"
> > - "bind-address=0.0.0.0"
> > kube-proxy-arg:
> > - "metrics-bind-address=0.0.0.0"
> > kube-scheduler-arg:
> > - "address=0.0.0.0"
> > - "bind-address=0.0.0.0"
> > etcd-expose-metrics: true
> > ```
> 
> https://rancher.com/docs/k3s/latest/en/installation/install-options/#configuration-file
> 
> ```
> 
> etcd-expose-metrics: true
> kube-controller-manager-arg:
> - bind-address=0.0.0.0
> kube-proxy-arg:
> - metrics-bind-address=0.0.0.0
> kube-scheduler-arg:
> - bind-address=0.0.0.0
> ```

thanks man, anyway I don't have that file config, but i only have /etc/rancher/k3s/k3s.yaml and /etc/systemd/system/k3s.sservice and some files in /var/lib/rancher/k3s

Is it possible to create it manually or do I need to upgrade my K3S ( v1.21.7) to my current version

**Comment by rlex** [comment]
@rthamrin config file is not installed by default, you need to manually create it.

**Comment by macrokernel** [comment]
I had the same issue with a K3s cluster, and tried following the above solution, but after adding endpoints to the prometheus operator values file, the helm would fail to deploy with the following error:
`Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Endpoints "prometheus-stack-kube-prom-kube-controller-manager" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "prometheus-stack"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "monitoring"
` 

I found a working solution at this page: https://picluster.ricsanfre.com/docs/prometheus/#k3s-components-monitoring. Leaving it here in case if anyone runs it to the same issue with the helm chart.

**Comment by onedr0p** [comment]
@macrokernel this error means helm does not have ownership, try to re-install KPS or add the helm annotations to the existing resources it is complaining about.

```
Endpoints "prometheus-stack-kube-prom-kube-controller-manager" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "prometheus-stack"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "monitoring"
```

**Comment by macrokernel** [comment]
@onedr0p I tried completely uninstalling KPS by removing the monitoring namespace where the helm chart was installed and installing it from scratch, but this did not help. I wish I knew which annotations it is missing and how to add them ;)

**Comment by onedr0p** [comment]
The error specifically says endpoints in the kube-system namespace.

**Comment by macrokernel** [comment]
@onedr0p thanks for guiding me through it :) Adding the following annotation and similar ones for `kubeScheduler` and `kubeProxy` did the trick:
```
kubeControllerManager:
  annotations:
    meta.helm.sh/release-name: monitoring
```
Helm chart update was successful after the modifications. Yet to check if Prometheus is getting the data.

**Comment by macrokernel** [comment]
@onedr0p, could you please give another hint? I tried adding the annotations all over the values file to no avail.

**Comment by onedr0p** [comment]
Don't add helm annotations in those values, **delete the specific endpoint in the kube-system namespace** and redeploy the chart.

**Comment by macrokernel** [comment]
@onedr0p, I removed the operator and everything with **prometheus** in the **kube-system** namespace, then reinstalled the operator helm chart. Helm install went without errors, however, **prometheus-stack-kube-prom-operator** pod is in CrashLoopBackOff state due to the following error:
```
level=warn ts=2022-08-13T08:13:19.199185707Z caller=operator.go:329 component=prometheusoperator msg="failed to check if the API supports the endpointslice resources" err="converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion"
level=info ts=2022-08-13T08:13:19.199261268Z caller=operator.go:331 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=false
listening failed:10250listen tcp :10250: bind: address already in use
```

**Comment by chemicstry** [comment]
I spent a couple of days figuring out how to make default `kube-prometheus-stack` metrics to work with k3s and found a couple of important things that are not mentioned here.

Firstly, `k3s` exposes all metrics combined (apiserver, kubelet, kube-proxy, kube-scheduler, kube-controller) on each metrics endpoint. The only separate metric is embedded etcd database on port `2831`, if you are using it. So if you follow the advice given in this issue and setup scrape jobs for each component separately, you are collecting all metrics duplicated 5 times and wasting prometheus resources.

Now to fix this properly is a bit difficult. All default grafana charts filter data by job name. I.e. the kube-proxy dashboard has `job = "kube-proxy"` in all queries. So my first attempt was to rename jobs based on metric name. I added this config to helm values:
```yaml
kubelet:
  serviceMonitor:
    metricRelabelings:
      # k3s exposes all metrics on all endpoints, relabel jobs that belong to other components
      - sourceLabels: [__name__]
        regex: "scheduler_(.+)"
        targetLabel: "job"
        replacement: "kube-scheduler"
      - sourceLabels: [__name__]
        regex: "kubeproxy_(.+)"
        targetLabel: "job"
        replacement: "kube-proxy"
```

This simply sets job label to `kube-scheduler` for all metrics that start with `scheduler_`, and to `kube-proxy` for all metrics that start with `kubeproxy_`.

But there is another problem. Instance variable in grafana charts uses `up` metric to find all instances of the component (`label_values(up{job="kube-scheduler", cluster="$cluster"}, instance)`). You can't rename job of `up` metric or other, in this case kubelet, dashboards will stop working. I couldn't find a way to multiply metrics with prometheus rules to create `up` metric for each job. So the only way is to edit grafana dashboards and change variable queries to (`label_values(up{job="kubelet", cluster="$cluster"}, instance)`).

There are also other metrics, which are shared between components such as `rest_client_requests_total`, which are global to entire `k3s-server` (all components) and do not make sense in single-component dashboards.

Also keep in mind that default `kube-prometheus-stack` configuration already duplicates data 2 times by collecting `kubeApiServer` and `kubelet` metrics, which are the same. It is best to disable only `kubeApiServer`, which collects data only from master nodes, while `kubelet` collects from both master and agent nodes. Disabling `kubeApiServer` automatically removes apiserver alerts and grafana dashboard so you have to re-import these manually.

It is really unfortunate that k3s makes it so complicated to use `kube-prometheus-stack`. If someone has a better solution to make this work without duplicating data, please share.

**Comment by onedr0p** [comment]
@chemicstry Thanks for the details, I suppose we could re-open this issue but I am not sure if it is something the k3s maintainers are will to "fix". Ideally this should all would out of the box with the `kube-prometheus-stack` helm chart.

**Comment by brandond** [comment]
There isn't really anything we can fix on our side. The prometheus go libraries use a global metrics configuration, so any metrics registered by any component in a process are exposed by all metrics listeners. There's no way to bind specific metrics to a specific metrics endpoint, when they're all running in the same process. A core efficiency of K3s is that we run all the components in the same process, and we're not planning on changing that.

**Comment by mrclrchtr** [comment]
Has anyone here found a good solution? 

What do you think about this? https://github.com/portefaix/portefaix-kubernetes/issues/4682  https://github.com/portefaix/portefaix-kubernetes/commit/dc767bdd3f8e6d0ffe3fe53e36e116ea7f5e6533#diff-725c569b96f4a66ed07e1a4d1a5d8d24b3a500f1a1dae5b80444a2109ce94c17

**Comment by mrclrchtr** [comment]
If others come here by googling, I have found what seems to be a good solution.
The solution also addresses two other issues with dashboards.

```
prometheus:
  serviceMonitor:
    # fix for https://github.com/prometheus-community/helm-charts/issues/4221
    relabelings:
      - action: replace
        targetLabel: cluster
        replacement: yourClusterNameHere

# fix for https://github.com/prometheus-community/helm-charts/issues/3800
grafana:
  serviceMonitor:
    labels:
      release: kube-prometheus-stack

kubeApiServer:
  serviceMonitor:
    metricRelabelings:
      - action: drop
        regex: (apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_sli_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: "etcd_request_duration_seconds_bucket"
        sourceLabels: [__name__]
      - action: drop
        regex: (scheduler_plugin_execution_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: (workqueue_work_duration_seconds_bucket)
        sourceLabels: [__name__]

kubelet:
  serviceMonitor:
    cAdvisorRelabelings:
      - action: replace
        sourceLabels: [__metrics_path__]
        targetLabel: metrics_path
      - action: replace
        targetLabel: instance
        sourceLabels:
          - "node"
    relabelings:
      - action: replace
        sourceLabels: [__metrics_path__]
        targetLabel: metrics_path
    metricRelabelings:
      - action: drop
        regex: (apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_sli_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: "etcd_request_duration_seconds_bucket"
        sourceLabels: [__name__]
      - action: drop
        regex: (scheduler_plugin_execution_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: (workqueue_work_duration_seconds_bucket)
        sourceLabels: [__name__]

kubeControllerManager:
  # Add all Control Plane IPs
  endpoints:
    - 10.255.0.101
    - 10.255.0.102
    - 10.255.0.103
  service:
    enabled: true
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    metricRelabelings:
      - action: drop
        regex: (apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_sli_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: "etcd_request_duration_seconds_bucket"
        sourceLabels: [__name__]
      - action: drop
        regex: (scheduler_plugin_execution_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: (workqueue_work_duration_seconds_bucket)
        sourceLabels: [__name__]

kubeEtcd:
  # Add all Control Plane IPs
  endpoints:
    - 10.255.0.101
    - 10.255.0.102
    - 10.255.0.103
  service:
    enabled: true
    port: 2381
    targetPort: 2381
  serviceMonitor:
    metricRelabelings:
      - action: drop
        regex: (apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_sli_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: "etcd_request_duration_seconds_bucket"
        sourceLabels: [__name__]
      - action: drop
        regex: (scheduler_plugin_execution_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: (workqueue_work_duration_seconds_bucket)
        sourceLabels: [__name__]

kubeScheduler:
  # Add all Control Plane IPs
  endpoints:
    - 10.255.0.101
    - 10.255.0.102
    - 10.255.0.103
  service:
    enabled: true
    port: 10259
    targetPort: 10259
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    metricRelabelings:
      - action: drop
        regex: (apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_sli_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: "etcd_request_duration_seconds_bucket"
        sourceLabels: [__name__]
      - action: drop
        regex: (scheduler_plugin_execution_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: (workqueue_work_duration_seconds_bucket)
        sourceLabels: [__name__]

kubeProxy:
  # Add all Control Plane IPs
  endpoints:
    - 10.255.0.101
    - 10.255.0.102
    - 10.255.0.103
  service:
    enabled: true
    port: 10249
    targetPort: 10249
    selector:
      k8s-app: kube-proxy
  serviceMonitor:
    metricRelabelings:
      - action: drop
        regex: (apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_sli_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: "etcd_request_duration_seconds_bucket"
        sourceLabels: [__name__]
      - action: drop
        regex: (scheduler_plugin_execution_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: (workqueue_work_duration_seconds_bucket)
        sourceLabels: [__name__]

coreDns:
  serviceMonitor:
    metricRelabelings:
      - action: drop
        regex: (apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_sli_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: "etcd_request_duration_seconds_bucket"
        sourceLabels: [__name__]
      - action: drop
        regex: (scheduler_plugin_execution_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: (workqueue_work_duration_seconds_bucket)
        sourceLabels: [__name__]

kubeDns:
  serviceMonitor:
    metricRelabelings:
      - action: drop
        regex: (apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_sli_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: "etcd_request_duration_seconds_bucket"
        sourceLabels: [__name__]
      - action: drop
        regex: (scheduler_plugin_execution_duration_seconds_bucket)
        sourceLabels: [__name__]
      - action: drop
        regex: (workqueue_work_duration_seconds_bucket)
        sourceLabels: [__name__]

kube-state-metrics:
  prometheus:
    monitor:
      relabelings:
        - action: replace
          targetLabel: "instance"
          sourceLabels:
            - "__meta_kubernetes_pod_node_name"

prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
        - action: replace
          targetLabel: "instance"
          sourceLabels:
            - "__meta_kubernetes_pod_node_name"

```

**Comment by onedr0p** [comment]
@mrclrchtr if I understand this correctly you are still going to have duplicate metrics, this can lead to absolutely insane high memory usage with Prometheus. I recently switch my cluster from k3s to Talos and saw 2-3GB less usage in memory per Prometheus instance since Talos exports these metrics the "standard" way.

The best method I found was to do the analysis across what needs to be kept on each component and write relabelings based upon that research. For example https://github.com/onedr0p/home-ops/blob/e6716b476ff1432ddbbb7d4efa0e10d0ac4e9a66/kubernetes/storage/apps/observability/kube-prometheus-stack/app/helmrelease.yaml However this isn't perfect as well and will not dedupe all metric labels across the components, it's prone to error and when updates to Kubernetes happen won't capture any new metrics being emitted. FWIW even with these relabelings I was still seeing a 3-4GB RAM usage per prometheus instance with them applied.

**Comment by mrclrchtr** [comment]
Damn... I was hoping this would be the solution... I'll probably have to look for alternatives too... I've invested way too much time in this already....

But thanks for the info! I'll have a look at Talos too.

**Comment by denniseffing** [comment]
> There isn't really anything we can fix on our side. The prometheus go libraries use a global metrics configuration, so any metrics registered by any component in a process are exposed by all metrics listeners. There's no way to bind specific metrics to a specific metrics endpoint, when they're all running in the same process. 

@brandond I've never worked with the Prometheus Go library but reading some documentation and issues has left me quite confused. Are you 100% certain that the library does not allow binding specific metrics to a specific metrics endpoint?

Here are some issues/PRs regarding this issue:
- https://github.com/prometheus/client_golang/issues/163 
- https://github.com/prometheus/client_golang/issues/46
- https://github.com/prometheus/client_golang/pull/214

Apparently, this has already been resolved in 2016. 
The following example explicitly mentions that it's possible to create non-global registries and bind them to their own HTTP endpoint respectively.

https://github.com/prometheus/client_golang/blob/main/examples/simple/main.go#L30-L45

@onedr0p Continuing our short discussion in https://github.com/prometheus-community/helm-charts/issues/2865#issuecomment-2596308842 I agree that this would be the real fix for k3s & kube-prometheus-stack compatibility.

**Comment by brandond** [comment]
Like I said, we don't modify the upstream Kubernetes code to the extent that this is possible. We just call the main entrypoints:

* https://github.com/k3s-io/k3s/blob/08c30f5ae671b8425e8067f4f5684f3aac4c0c7e/pkg/daemons/executor/embed.go#L123-L125
* https://github.com/k3s-io/k3s/blob/08c30f5ae671b8425e8067f4f5684f3aac4c0c7e/pkg/daemons/executor/embed.go#L167-L169
* and so on.

Internally each of these components call the same shared code to register metrics: https://github.com/kubernetes/kubernetes/blob/v1.32.1/staging/src/k8s.io/component-base/metrics/legacyregistry/registry.go

Because the high-level cli entrypoints don't allow passing in metrics registerer/gatherers (and why should they these are just CLI entrypoints) we cannot override them per component.

**Comment by denniseffing** [comment]
Thank you for clarifying, that makes sense. Sorry for the naive questions, I guess I kind of knew that I am missing something, but didn't exactly know where to look.

**Comment by nickjanssen** [comment]
So what is the conclusion? It's not k3s, but prometheus's fault?

```A core efficiency of K3s is that we run all the components in the same process, and we're not planning on changing that.```

I have no choice but to move to Talos because of this. The workarounds above are terrible. What use is a cluster if I can't monitor it properly?

**Comment by brandond** [comment]
What exactly is so onerous about this? The metrics for everything are all in one place. That doesn't seem SUPER hard to deal with. Why is your monitoring configuration so inflexible that you can't either disable some of the unnecessary duplicate scraping, or add a relabel config to drop the duplicate metrics? It's not rocket science, there are thousands of organizations successfully using and monitoring K3s without issue.

**Comment by nickjanssen** [comment]
Thank you for your reply. Let me start by saying that I appreciate the work that you put into k3s. With that said:

> I recently switch my cluster from k3s to Talos and saw 2-3GB less usage in memory per Prometheus instance

Doesn't this challenge the claim of "core efficiency"? If K3s is meant to be lightweight, but this architecture results in a much higher memory consumption, it would seem like there is room for improvement.

> Why is your monitoring configuration so inflexible

I prefer solutions that work out of the box. If I wanted to spend time tweaking configurations, I would have gone with kubeadm and read Kubernetes the Hard Way. A major benefit of K3s is its simplicity, and expecting users to implement workarounds for basic monitoring goes against that philosophy.

> That doesn't seem SUPER hard to deal with. 

Judging by the number of comments in this thread, it seems like many people find it problematic. If something requires workarounds, it’s usually a sign that there’s an opportunity to improve the experience.

**Comment by rlex** [comment]
Not speaking as k3s dev, but i think the whole point is that k3s is k8s _distribution_, not k3s _fork_.
If changes need to be added to core (even tiny ones) that will change k3s to fork, which might pose issues using it in different scenarios. 

There is also multiple pretty much copypaste solutions with relabeling for standard tools like kube-prometheus-stack in this thread.

Not everything is out-of-the-box solution.

**Comment by brandond** [comment]
> f K3s is meant to be lightweight, but this architecture results in a much higher memory consumption, it would seem like there is room for improvement.

K3s doesn't use more memory. Period. Scraping ANYTHING multiple times with different labels will increase your Prometheus metric cardinality, but that is not something we manage in this project.

> I prefer solutions that work out of the box.

K3s works out of the box. It is your monitoring stack that has issues. I would recommend you direct your criticism at whatever chart or operator is managing the over-aggressive scraping. K3s works with monitoring built into Rancher. We do not have the cycles to identify all of the many tools that people might be using to monitor K3s with, figure out if they have issues, and fix them if so.

 As we've made clear multiple times, the problem is NOT how k3s exposes metrics. The k3s metrics accurately represent the components that are being scraped. Problems occur ONLY when you scrape it multiple times with distinct labels, which balloons the metric cardinality.

> Judging by the number of comments in this thread, it seems like many people find it problematic.

K3s is open source. Lots of people use it. Some small subset of them find it problematic enough to complain about it. Apparently no one (including you) has found it problematic enough to contribute a solution.

**Comment by janosmiko** [comment]
Did anyone found a solution to use kube-prometheus-stack to monitor all kube-proxy instances of k3s (including autoscaling nodes)?
This is not a problem for etcd, scheduler, api-server and so on, as they only run on the control plane nodes, but what about kube-proxy that runs on all nodes (just as it's true for kubelet).

I see that the kubelet service endpoints are managed by prometheus-operator, so it doesn't seem to be a viable way for kube-proxy.
https://github.com/prometheus-operator/prometheus-operator/blob/712a2c1664dfe9aaf34fd216603f2953070eaf85/pkg/prometheus/server/operator.go#L606

**Comment by brandond** [comment]
kube-proxy and kubelet metrics should be available as usual. Are you seeing otherwise?

**Comment by kladiv** [comment]
> Did anyone found a solution to use kube-prometheus-stack to monitor all kube-proxy instances of k3s (including autoscaling nodes)? This is not a problem for etcd, scheduler, api-server and so on, as they only run on the control plane nodes, but what about kube-proxy that runs on all nodes (just as it's true for kubelet).
> 
> I see that the kubelet service endpoints are managed by prometheus-operator, so it doesn't seem to be a viable way for kube-proxy. https://github.com/prometheus-operator/prometheus-operator/blob/712a2c1664dfe9aaf34fd216603f2953070eaf85/pkg/prometheus/server/operator.go#L606
> 
> Would it be possible to expose and maintain a kubernetes metrics service and the endpoints by k3s? (Just thinking loudly.)

@janosmiko Below the way i did the setup (i run k3s _v1.30.5+k3s1_ cluster). Probabily it produce some duplicate metrics (as already discussed in this issue) so you could detect an high memory usage with Prometheus.

1. k3s config settings in Master/Control-Plane nodes:

    ```yaml
    etcd-expose-metrics: true
    kube-controller-manager-arg:
      - "bind-address=0.0.0.0"
    kube-proxy-arg:
      - "metrics-bind-address=0.0.0.0"
    kube-scheduler-arg:
      - "bind-address=0.0.0.0"
    ```

2. deploy **Rancher PushProx** helm chart in the k3s cluster to `kube-system` namespace:

    Repo: https://charts.rancher.io
    Chart: rancher-pushprox
    Release name: pushprox-kube-proxy
    Version: 103.0.1

    > you can use helm CLI or k3s Helm Controller (kind: HelmChart)

    rancher-pushprox helm values:

    ```yaml
    metricsPort: 10249
    component: kube-proxy
    serviceMonitor:
      enabled: false
    clients:
      port: 10013
      useLocalhost: true
      https:
        enabled: false
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
    ```

3. kube-prometheus-stack helm values:

    ```yaml
    kubeControllerManager:
      # Add all k3s Control-Plane IPs
      endpoints:
        - <k3s_master1_IP>
        - <k3s_master2_IP>
        - <k3s_master3_IP>
      service:
        port: 10257
        targetPort: 10257
      serviceMonitor:
        https: true
        insecureSkipVerify: true
    kubeScheduler:
      # Add all k3s Control-Plane IPs
      endpoints:
        - <k3s_master1_IP>
        - <k3s_master2_IP>
        - <k3s_master3_IP>
      service:
        port: 10259
        targetPort: 10259
      serviceMonitor:
        https: true
        insecureSkipVerify: true
    kubeEtcd:
      # Add all k3s Control-Plane IPs
      endpoints:
        - <k3s_master1_IP>
        - <k3s_master2_IP>
        - <k3s_master3_IP>
      service:
        port: 2381
        targetPort: 2381
    kubeProxy:
      service:
        port: 10249
        targetPort: 10249
        selector:
          k8s-app: pushprox-kube-proxy-client
      serviceMonitor:
        proxyUrl: http://pushprox-kube-proxy-proxy.kube-system.svc:8080
        https: false
        relabelings:
          - action: replace
            sourceLabels:
              - __meta_kubernetes_pod_ip
            targetLabel: pod_ip
          - action: replace
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: instance

    prometheus-node-exporter:
      hostNetwork: false
      hostPID: false
      prometheus:
        monitor:
          relabelings:
            - action: replace
              sourceLabels:
                - __meta_kubernetes_pod_ip
              targetLabel: pod_ip
            - action: replace
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: instance
    ```
