### ISSUE TITLE
Documentation linking to outdated Traefik helm chart documentation

### ISSUE THREAD

**Issue by mathiasringhof** [k3s-io/k3s#3766]
**Describe the bug:**
https://rancher.com/docs/k3s/latest/en/networking/ links to the following URL to give on overview over available parameters:
https://github.com/helm/charts/tree/master/stable/traefik#configuration

The correct repository doesn't have a proper markdown yet but the values file itself is self-explanatory and above all lists the correct parameters:
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

**Steps To Reproduce:**
Tried giving Traefik a defined load balancer IP by doing:
```
   valuesContent: |-
    rbac:
      enabled: true
    ports:
      websecure:
        tls:
          enabled: true
    loadBalancerIP: 192.168.1.244
```
in `/var/lib/rancher/k3s/server/manifests/traefik.yaml`- doesn't work.

What works is:
```
  valuesContent: |-
    rbac:
      enabled: true
    ports:
      websecure:
        tls:
          enabled: true
    service:
      spec:
        loadBalancerIP: 192.168.1.244
```

as can be seen in the 2nd URL.

**Expected behavior:**
Link to the correct values.yaml.

**Actual behavior:**
Link to old version of the helm chart.

**Backporting**
Documentation might want to differentiate between <1.21 and  >=1.21 - my understanding is the link described the correct helm chart for older versions of k3s using Traefik 1.x.

- [ ] Needs backporting to older releases
