### ISSUE TITLE
Override the klipper-helm image used in default HelmCharts

### ISSUE THREAD

**Issue by mddamato** [k3s-io/k3s#3865]
**Is your feature request related to a problem? Please describe.**
I need to be able to override the `klipper-helm` image to use a custom registry without adding a docker.io mirror

**Describe the solution you'd like**
I can pass in `--klipper-helm-image=X` which  adds the `spec.jobImage` property to the default HelmChart files in  `/var/lib/rancher/rke2/server/manifests`

**Describe alternatives you've considered**

add to config (RKE2 in the example but applies to k3s):

```
disable:
- rke2-canal
- rke2-coredns
- rke2-ingress-nginx
- rke2-metrics-server
```

`cp /var/lib/rancher/rke2/data/v1.21.3-rke2r1-789f04a3cde2/charts/rke2-canal.yaml /var/lib/rancher/rke2/server/manifests/rke2-canal.yaml` (repeat for other charts).

add the `spec.jobImage` parameter to the 4 charts.

start rke2-server.

**Additional context**
This would allow for a rebuilt image to be used without setting up a mirror for docker.io such as using IronBank images

**Backporting**
no
- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
@FruityWelsh is correct, if you use the same names for your custom manifest as the rke2 bundled charts manifests that you've disabled, your custom manifests will be disabled and deleted as well. If you're providing custom manifests, you should be sure that they don't use the rke2- prefix, as that is essentially reserved for packaged components.

**Comment by FruityWelsh** [comment]
Are there some good methods to trouble shoot the add-ons resource not adding the helm installation jobs?
I changed the charts to no longer have the rke2 prefix, and it does show up successfully when running ```kubectl get addon -A```, but does not install the service or the helm install pod at all in kube-system.

Quick description (```kubectl -n kube-system describe addon canal```):
```
Name:         canal
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
API Version:  k3s.cattle.io/v1
Kind:         Addon
Metadata:
  Creation Timestamp:  2021-09-02T17:57:03Z
  Generation:          1
  Managed Fields:
    API Version:  k3s.cattle.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:source:
      f:status:
    Manager:         deploy@rke2-dev-0.tfe.dev
    Operation:       Update
    Time:            2021-09-02T17:57:03Z
  Resource Version:  749
  UID:               06c2de18-e8b8-4147-8e5e-646c77c78636
Spec:
  Source:  /var/lib/rancher/rke2/server/manifests/canal.yaml
Status:
Events:  <none>
```

**Comment by brandond** [comment]
You can look at the k3s service log on the server to see if perhaps the yaml is malformed. With 1.22 releases, you should see events as well, to save having to go grep through log files.

**Comment by FruityWelsh** [comment]
is that available in any of the rke2 releases as well?

I am not seeing anything besides Traifek erroring from helm.

What my canal.yaml looks like:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    flannel:
      image:
        repository: {{ RKE2_FLANNEL_IMAGE }}
        tag: {{ RKE2_FLANNEL_IMAGE_TAG }}
    calico:
      cniImage:
        repository: {{ RKE2_CALICO_IMAGE }}
        tag: {{ RKE2_CALICO_IMAGE_TAG }}
      nodeImage:
        repository: {{ RKE2_CALICO_IMAGE }}
        tag: {{ RKE2_CALICO_IMAGE_TAG }}
      flexvolImage:
        repository: {{ RKE2_CALICO_IMAGE }}
        tag: {{ RKE2_CALICO_IMAGE_TAG }}
```
