### ISSUE TITLE
failed to create containerd container: load apparmor profile tmp/cri-containerd.apparmor.d*****: exit status 243:

### ISSUE THREAD

**Issue by lixia755324** [k3s-io/k3s#3884]
**Environmental Info:**
alpine linux
openrc (OpenRC [DOCKER]) 0.42.1.6b66f6314a

K3s Version: 

k3s version v1.21.4-rc1+k3s1 (3e250fdb)
go version go1.16.6

Node(s) CPU architecture, OS, and Version: 

Linux node1 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 Linux

Cluster Configuration:

1 server only

**Describe the bug:**

I start a server node user this command:   k3s server --snapshotter=native &
run kubectl get nodes get this : node1   Ready    control-plane,master   20s   v1.21.4-rc1+k3s1
aflter i try to create a rc use this file :

mysql-rc.yaml

``` yml
apiVersion: v1
kind: ReplicationController 
metadata:
  name: mysql 
spec:
  replicas: 1 
  selector:
    app: mysql 
  template: 
    metadata:
      labels:
        app: mysql 
    spec:
      containers: 
      - name: mysql 
        image: mysql:5.7 
        ports:
        - containerPort: 3306 
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        resources: 
          requests: 
            memory: "64Mi"
            cpu: "256m" 
          limits: 
            memory: "128Mi"
            cpu: "500m"
```

When i run kubectl get pods i get this messages:

```
  Normal   Pulled     59s               kubelet            Successfully pulled image "mysql:5.7" in 39.065859433s
  Normal   Pulled     9s (x4 over 53s)  kubelet            Container image "mysql:5.7" already present on machine
  Warning  Failed     7s (x5 over 54s)  kubelet Warning Failed 3m7s   kubelet Error: failed to create containerd container: load apparmor profile /tmp/cri-containerd.apparmor.d210494137: exit status 243
```

**Steps To Reproduce:**

- Installed K3s: 

1. access   https://labs.play-with-docker.com/   
2. add a new instance
3. run `apk add openrc`
4. run `mkdir /run/openrc/`
5. run `touch /run/openrc/softlevel`
6. run `openrc`
7. run `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.4-rc1+k3s1 sh -s - server --snapshotter=native`
8. run `cat http://dl-cdn.alpinelinux.org/alpine/edge/testing > /etc/openrc/repositories`
9. run `apk add apparmor`
10. create file mysql-rc.yaml   as i show before
11. run `kubectl create -f mysql-rc.yaml`
12. run `kubectl get pods mysql`

**Expected behavior:**

i expected kubectl create one pod successfully

**Actual behavior:**

but  i got an error message like i show before, 

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases
