### ISSUE TITLE
unable to figure out how to configure credentials for dockerhub

### ISSUE THREAD

**Issue by itai-codefresh** [k3s-io/k3s#3937]
i am trying to configure credentials for dockerhub in registry configuration file so that i will not hit rate limit

i have tried endless configuration without success.

what am i doing wrong?

```
mirrors:
  docker.io:
    endpoint:
      - https://registry-1.docker.io
configs:
  docker.io:
    auth:
      username: ***
      password: ***
```
