### ISSUE TITLE
Support dual-stack in klipper-lb

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#4021]
**Is your feature request related to a problem? Please describe.**

Dual-stack services in load-balanced mode are not working because klipper-lb does not support it:

```
+ iptables -t nat -I PREROUTING '!' -s 2001:cafe:42:1::def/32 -p TCP --dport 8080 -j DNAT --to 2001:cafe:42:1::def:8080
iptables v1.6.2: Port `cafe:42:1::def:8080' not valid
```

**Describe the solution you'd like**

klipper-lb is able to apply an ipv6 config

**Additional context**

https://github.com/k3s-io/k3s/issues/1405

**Comment by manuelbuil** [comment]
This task requires two things:
1 - Update klipper-lb so that it creates an iptable rule for ipv6 addresses as well
2 - Update k3s so that nodes get the ipv6 address of the main interface as internal ip too. Otherwise, the loadBalancer service will always have the ipv4 as the external ip

**Comment by brandond** [comment]
Upstream requires that users manually specify the desired ipv6 address: they do not plan to have the kubelet or kubeadm attempt to autodetect it. I think we should follow suit.

* https://github.com/kubernetes/kubeadm/issues/1612#issuecomment-786540060

**Comment by manuelbuil** [comment]
> Upstream requires that users manually specify the desired ipv6 address: they do not plan to have the kubelet or kubeadm attempt to autodetect it. I think we should follow suit.
> 
>     * [Dual-Stack support for Kubeadm kubernetes/kubeadm#1612 (comment)](https://github.com/kubernetes/kubeadm/issues/1612#issuecomment-786540060)

Yes, via node-ip. I discussed this with Antonio a few hours ago and I was testing this:
```
status:
  addresses:
  - address: 10.0.10.5
    type: InternalIP
  - address: 2a05:d012:c6f:4611:89e7:e55f:c55d:aa6
    type: InternalIP
```
Note that in case of no ipv4, it autodetecs ipv6:
```
status:
  addresses:
  - address: 10.0.10.5
    type: InternalIP
  - address: 2a05:d012:c6f:4611:89e7:e55f:c55d:aa6
    type: InternalIP
```
