### ISSUE TITLE
deploy mount cephfs  failed to get Plugin from volumeSpec for volume "data" err=no volume plugin matched

### ISSUE THREAD

**Issue by egoisz** [k3s-io/k3s#4263]
**Environmental Info:**
K3s Version: 

k3s version v1.21.5+k3s1 (acad8ef8)
go version go1.16.8
Node(s) CPU architecture, OS, and Version: 

Linux k3s-20-223 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

2 servers，1agents
**Describe the bug:**

my deploy yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        imagePullPolicy: IfNotPresent
        image: nginx
        volumeMounts:
        - mountPath: "/data"
          name: data
        ports:
        - containerPort: 80
      volumes:
        - name: data
          cephfs:
            monitors:
              - 10.5.10.117:6789
              - 10.5.10.236:6789
              - 10.5.10.227:6789
            path: /data
            user: admin
            secretRef:
              name: ceph-secret
```
describe pod
```
  Warning  FailedMount  18s   kubelet            Unable to attach or mount volumes: unmounted volumes=[data kube-api-access-ql2jg], unattached volumes=[data kube-api-access-ql2jg]: failed to get Plugin from volumeSpec for volume "data" err=no volume plugin matched
```

my yaml can work successfully  on k8s-v1.21.
Is k3s need some plugin  to install ?
