### ISSUE TITLE
Traefik /ping 404 not found on new install

### ISSUE THREAD

**Issue by lucasarnulphy** [k3s-io/k3s#4332]
**Version**
k3s version v1.21.5+k3s2 (724ef700)

**Describe the bug**
Traefik has a builtin /ping endpoint which should return a 200 code if reachable. I have older k3s versions installed which show this behavior actually working (/ping returns a 200 code). On a brand new install with the latest version, /ping returns a 404 page not found error on http (and https).

```
curl http://host/ping
curl : 404 page not found
```

I have tried enabling `--ping` using HelmChartConfig but it doesn't work any better.

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
    name: traefik
    namespace: kube-system
spec:
    valuesContent: |-
        startupArguments:
        - "--ping=true"
```

This actually made me realize "--ping" was actually enabled by default by running :
```
kubectl get deployment traefik -n kube-system -o yaml
```

```
    spec:
      containers:
      - args:
        - --global.checknewversion
        - --global.sendanonymoususage
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --providers.kubernetescrd
        - --providers.kubernetesingress
        - --providers.kubernetesingress.ingressendpoint.publishedservice=kube-system/traefik
        - --entrypoints.websecure.http.tls=true
```

**To Reproduce**

Set up a k3s cluster, use default option of traefik as the ingress controller. (don't pass --disable traefik).
Curl with /ping.

**Expected behavior**
/ping should return a 200 code.

**Actual behavior**

/ping returns 404 page not found.
