### ISSUE TITLE
Ingress-Nginx IPv6 issues with K3S 1.22.3+

### ISSUE THREAD

**Issue by smbambling** [k3s-io/k3s#4400]
**Environmental Info:**
K3s Version: v1.22.3+k3s1

Node(s) CPU architecture, OS, and Version: 
inux prometheus.example.net 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: Single node cluster

**Describe the bug:**
Issues with Nginx Controller LoadBalancer obtaining IPv4 and IPv6 addresses with PreferDualStack
 is configured in the ingress-nginx-controller service

**Steps To Reproduce:**

- Installed K3s: 
```
export INSTALL_K3S_VERSION="v1.22.3+k3s1"
  
curl -sfL https://get.k3s.io | sh -s - --disable traefik \
--cluster-cidr=10.42.0.0/16,fc15:1::/56 \
--service-cidr=10.43.0.0/16,fc15:2::/112 \
--node-ip=10.1.22.110,2001:500:110:604::110 \
--disable-network-policy \
--kube-controller-manager-arg="bind-address=::" \
--kube-proxy-arg="metrics-bind-address=::" \
--kube-scheduler-arg="address=::" \
--kube-scheduler-arg="bind-address=::"
```
- Installed Ingress-Nginx Controller
```
helm repo add stable https://charts.helm.sh/stable
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update

cat <<EOF > /tmp/ingress-nginx-values.yml
---
controller:
  admissionWebhooks: 
    enabled: false
  allowSnippetAnnotations: false
  config:
    use-forwarded-headers: "true"
    use-http2: "false"
  kind: DaemonSet
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: kube-prometheus-stack
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  service:
    externalTrafficPolicy: Local
EOF

helm upgrade --install --atomic ingress-nginx ingress-nginx/ingress-nginx -n ingress-nginx --create-namespace \
-f /tmp/ingress-nginx-values.yml --version 4.0.6 --kubeconfig /etc/rancher/k3s/k3s.yaml
```
- Updated the ingress-nginx-controller service to have ipFamilyPolicy set to  PreferDualStack
```
kubectl --namespace ingress-nginx edit services -o wide ingress-nginx-controller -o yaml
```

**Expected behavior:**
Both IPv4 and IPv6 address families are assigned as External-Addresses

**Note: With version: v1.22.2+k3s2 I get the following without the need to set PreferDualStack**
```
kubectl --namespace ingress-nginx get services -o wide ingress-nginx-controller

NAME                       TYPE           CLUSTER-IP    EXTERNAL-IP                         PORT(S)                      AGE   SELECTOR
ingress-nginx-controller   LoadBalancer   10.43.44.87   10.1.22.110,2001:500:110:604::110   80:30595/TCP,443:31971/TCP   46m   app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
```

**Actual behavior:**
The ingress-nginx-controller never gets an address assigned form the LB (Klipper)
```
kubectl --namespace ingress-nginx get services -o wide ingress-nginx-controller

NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE   SELECTOR
ingress-nginx-controller   LoadBalancer   10.43.107.199   <pending>     80:32289/TCP,443:32522/TCP   15m   app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
```

**Additional context / logs:**
When looking at the svclb-ingress-nginx-controller-*****  pod I see its in a CrashLoop
```
[root@prometheus ~]# kubectl get pods -A | grep 'svclb-ingress-nginx-controller'
ingress-nginx   svclb-ingress-nginx-controller-kqtqn     0/2     CrashLoopBackOff   14 (29s ago)   11m
```

Doing a describe I see the following
```
- containerID: containerd://f303a3f2d671ed844382b7529a3667793233b01327d3abc64e7e9db97c9d40dd
    image: docker.io/rancher/klipper-lb:v0.3.4
    imageID: docker.io/rancher/klipper-lb@sha256:d5ec8350ee1a80ec783effe95a2fefae371d1498ac04865cb6024499882f291c
    lastState:
      terminated:
        containerID: containerd://f303a3f2d671ed844382b7529a3667793233b01327d3abc64e7e9db97c9d40dd
        exitCode: 1
        finishedAt: "2021-11-04T16:46:29Z"
        reason: Error
        startedAt: "2021-11-04T16:46:29Z"
    name: lb-port-80
    ready: false
    restartCount: 6
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=lb-port-80 pod=svclb-ingress-nginx-controller-62h7p_ingress-nginx(25012e75-42db-4d3f-a7d3-33c4db113468)
        reason: CrashLoopBackOff
  hostIP: 10.1.22.110
  phase: Running
  podIP: 10.42.0.16
  podIPs:
  - ip: 10.42.0.16
  - ip: fd42::10
  qosClass: BestEffort
  startTime: "2021-11-04T16:40:34Z"
```
