### ISSUE TITLE
[release-1.21] etcd extra args should be supported

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#4474]
Backport: https://github.com/k3s-io/k3s/issues/4462

**Comment by Oats87** [comment]
https://github.com/k3s-io/k3s/pull/4471

**Comment by ShylajaDevadiga** [comment]
Validated using commit in release1.21 branch, passing extra-args through command line **--etcd-arg quota-backend-bytes=858993459 --etcd-arg "experimental-initial-corrupt-check=true"  --etcd-arg "log-rotation-config-json={\"maxsize\": 100, \"maxage\": 0, \"maxbackups\": 0, \"localtime\": false, \"compress\": false}" --etcd-arg "log-outputs=[default]"**
```
 $ sudo cat /var/lib/rancher/k3s/server/db/etcd/config
advertise-client-urls: https://172.31.30.39:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
experimental-initial-corrupt-check: true
heartbeat-interval: 500
initial-advertise-peer-urls: https://172.31.30.39:2380
initial-cluster: ip-172-31-30-39-ea1cd9d1=https://172.31.30.39:2380
initial-cluster-state: new
listen-client-urls: https://172.31.30.39:2379,https://127.0.0.1:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://172.31.30.39:2380
log-outputs:
- default
log-rotation-config-json: '{"maxsize": 100, "maxage": 0, "maxbackups": 0, "localtime":
  false, "compress": false}'
logger: zap
name: ip-172-31-30-39-ea1cd9d1
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
quota-backend-bytes: 858993459
```
From the logs
```
Nov 16 23:38:26 ip-172-31-30-39 k3s[1870]: {"level":"info","ts":"2021-11-16T23:38:26.606Z","caller":"embed/etcd.go:302","msg":"starting an etcd server","etcd-version":"3.4.13","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.16.8","go-os":"linux","go-arch":"amd64","max-cpu-set":2,"max-cpu-available":2,"member-initialized":false,"name":"ip-172-31-30-39-ea1cd9d1","data-dir":"/var/lib/rancher/k3s/server/db/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/k3s/server/db/etcd/member","force-new-cluster":false,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["https://172.31.30.39:2380"],"listen-peer-urls":["https://172.31.30.39:2380"],"advertise-client-urls":["https://172.31.30.39:2379"],"listen-client-urls":["https://127.0.0.1:2379","https://172.31.30.39:2379"],"listen-metrics-urls":["http://127.0.0.1:2381"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"ip-172-31-30-39-ea1cd9d1=https://172.31.30.39:2380","initial-cluster-state":"new","initial-cluster-token":"etcd-cluster","quota-size-bytes":858993459,"pre-vote":false,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":""}
```
Passing data-dir
```
$ curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=88e77fdbfd4f54b5317390f828835cdfb8e83bfe sh -s - server --cluster-init --etcd-arg data-dir=/mnt10
$ sudo ls /mnt10
member
$ kubectl get nodes
NAME              STATUS   ROLES                       AGE   VERSION
ip-172-31-30-39   Ready    control-plane,etcd,master   77m   v1.21.6+k3s-88e77fdb
$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   coredns-7448499f4d-74jww                  1/1     Running     0          77m
kube-system   helm-install-traefik-crd-x2fz4            0/1     Completed   0          77m
kube-system   helm-install-traefik-m279g                0/1     Completed   1          77m
kube-system   local-path-provisioner-5ff76fc89d-t677x   1/1     Running     0          77m
kube-system   metrics-server-86cbb8457f-qpqrs           1/1     Running     0          77m
kube-system   svclb-traefik-xh4ft                       2/2     Running     0          77m
kube-system   traefik-97b44b794-67g9k                   1/1     Running     0          77m
```
From the Logs:
```
...
"data-dir":"/mnt10","wal-dir":"","wal-dir-dedicated":"","member-dir":"/mnt10/member"
```
Using config.yaml
```
$ sudo cat /etc/rancher/k3s/config.yaml
etcd-arg: 
  - "quota-backend-bytes=858993459"
  - "data-dir=/mnt13"
```
From the logs:
```
Nov 17 04:55:23 ip-172-31-30-39 k3s[104256]: {"level":"info","ts":"2021-11-17T04:55:23.658Z","caller":"embed/etcd.go:302","msg":"starting an etcd server","etcd-version":"3.4.13","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.16.8","go-os":"linux","go-arch":"amd64","max-cpu-set":2,"max-cpu-available":2,"member-initialized":false,"name":"ip-172-31-30-39-bdf21075","data-dir":"/mnt13","wal-dir":"","wal-dir-dedicated":"","member-dir":"/mnt13/member","force-new-cluster":false,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["https://172.31.30.39:2380"],"listen-peer-urls":["https://172.31.30.39:2380"],"advertise-client-urls":["https://172.31.30.39:2379"],"listen-client-urls":["https://127.0.0.1:2379","https://172.31.30.39:2379"],"listen-metrics-urls":["http://127.0.0.1:2381"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"ip-172-31-30-39-bdf21075=https://172.31.30.39:2380","initial-cluster-state":"new","initial-cluster-token":"etcd-cluster","quota-size-bytes":858993459,"pre-vote":false,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":""}
```
While passing data-dir, config and name dir continues to stay in the default location. 
```
$ sudo ls /var/lib/rancher/k3s/server/db/etcd
config	name
```

**Comment by VestigeJ** [comment]
k3s version v1.21.6+k3s-88e77fdb (88e77fdb) - validated this is writing args passed into the installer into the config file located at `/var/lib/rancher/k3s/server/db/etcd/config`
Gotta say it feels pretty verbose to repeatedly pass --etcd-arg but how often is someone doing that vs a config file? One of those has way fewer changes of errors on installations. I also intentionally overwrote different values that were present in `/etc/rancher/k3s/config.yaml` ie quota-backend-bytes=8888888


`curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=88e77fdbfd4f54b5317390f828835cdfb8e83bfe  sh -s - server --cluster-init --etcd-arg name=vegetable --etcd-arg snapshot-count=7 --etcd-arg=proxy=off --etcd-arg quota-backend-bytes=7777777`

sudo cat /var/lib/rancher/k3s/server/db/etcd/config
```
advertise-client-urls: https://172.31.23.97:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
heartbeat-interval: 500
initial-advertise-peer-urls: https://172.31.23.97:2380
initial-cluster: ip-172-31-23-97-ea706841=https://172.31.23.97:2380
initial-cluster-state: new
listen-client-urls: https://172.31.23.97:2379,https://127.0.0.1:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://172.31.23.97:2380
log-outputs:
- stderr
logger: zap
name: ip-172-31-23-97-ea706841
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
quota-backend-bytes: 777777777
```
