### ISSUE TITLE
[design doc] Support multiple cnis

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#4490]
## PROBLEM ##
k3s only supports automatic deployments with flannel CNI plugin. It is possible to deploy with other CNI plugins but it requires manual intervention. We would like to change this and be able to automatically deploy other CNI plugins.

## USE CASE ##
As as user, I'd like to have a config parameter (--cni) that I can set to "cilium", "calico", "multus,cilium" or "multus,calico". When that happens:
1 - Flannel will not get deployed (flannel-backend=none)
2 - Network policy controller will be disabled (disable-network-policy=true)
3 - The set CNI plugin will get installed

## IMPLEMENTATION ##
Flannel remains embedded in k3s binary but the rest of the CNI plugins will not. They will be consumed using helm in a similar way as we do in rke2. However, to avoid k3s depending on rke2, k3s will consume charts from a different chart repo.

One manifest for each new CNI plugin will be placed in the manifests directory. These manifests will contain a `HelmChart` object pointing to the chart tarball using spec.chart. For example:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: calico
  namespace: kube-system
spec:
  chart: $url_to_calico_tarball.tgz
  set:
    global.systemDefaultRegistry: "%{SYSTEM_DEFAULT_REGISTRY_RAW}%"
```

In `func run` of `pkg/cli/server/server.go`, there will be a switch based on the cni value and if `case "calico"`, cilium and multus will be part of `serverConfig.ControlConfig.Skips`, `serverConfig.ControlConfig.FlannelBackend = "none"`, etc.

## QUESTIONS ##
1 - Should flannel be treated as a different CNI plugin? I.e. we don't change how we are currently deploying flannel
2 - How to maintain the k3s charts? Should we create some sort of k3s-charts similar to rke2-charts?
