### ISSUE TITLE
We should set --peer-cert-file, --peer-key-file, and peer-client-cert-auth arguments when running with embedded etcd

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#4526]
`peer-client-cert-auth` should be set to `true`, and `peer-cert-file` and `peer-key-file` should be configured appropriately for tls communication.

The reasoning is twofold:
1. To pass CIS checks 2.4 and 2.5
2. Following the rationalie from CIS, this would allow our etcd objects to be TLS encrypted in transit and also among peers in the etcd cluster.

This setting is not recommended for one etcd server in the environment, but our recommendation is to run embedded etcd or use an external datastore when running HA k3s, so there should be multiple nodes in the etcd cluster. If running a single node, users are primarily using sqlite. 

I believe k3s not setting these values right now is unintentional and they are meant to be set. See for reference config taken from a node using embedded etcd in k3s on v1.21.6+k3s1:
```
# cat /var/lib/rancher/k3s/server/db/etcd/config
advertise-client-urls: https://<redacted>:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
heartbeat-interval: 500
initial-advertise-peer-urls: https://<redacted>:2380
initial-cluster: ip-<redacted>-c5d1979f=https://<redacted>:2380
initial-cluster-state: new
listen-client-urls: https://<redacted>:2379,https://127.0.0.1:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://<redacted>:2380
log-outputs:
- stderr
logger: zap
name: ip-<redacted>-c5d1979f
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
```
