### ISSUE TITLE
CoreDNS name resolution fails, NodePort is not available on nodes without the pod

### ISSUE THREAD

**Issue by VladimirKorzh** [k3s-io/k3s#4588]
<!-- Thanks for helping us to improve K3S! We welcome all bug reports. Please fill out each area of the template so we can better help you. Comments like this will be hidden when you post but you can delete them if you wish. -->

**Environmental Info:**
K3s Version: 
<!-- Provide the output from "k3s -v" -->
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8

Node(s) CPU architecture, OS, and Version: 
<!-- Provide the output from "uname -a" on the node(s) -->
Linux vova-test 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
<!-- Provide some basic information on the cluster configuration. For example, "3 servers, 2 agents". -->
Looking for a way to orchestrate a fleet of odroid. Trying to set up a webapi that will make requests to payload running on odroid.
In this example I've used two cloud machine from equinix (bare metal), personal VM Ware virtual machine and an odroid XU4 

**Describe the bug:**
<!-- A clear and concise description of what the bug is. -->
1. nslookup kubernetes.cluster fails from nodes that don't have coredns running
2. Cannot access nodeport services on nodes that don't have them running
3. it appear as if some overlay network issue.
4. spent 24h+ on trying. 
5. tried k8s rancher as well, same issue. 
6. Tried the following IP Tables fixes
```
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
sudo update-alternatives --set arptables /usr/sbin/arptables-legacy
sudo update-alternatives --set ebtables /usr/sbin/ebtables-legacy
sudo iptables -P FORWARD ACCEPT
```


![image](https://user-images.githubusercontent.com/3537332/143624168-45ee45f0-814e-4e5e-b652-bdca267772be.png)



**Steps To Reproduce:**
<!-- Steps to reproduce the behavior. Please include as the first step how you installed K3s on the node(s) (including all flags or environment variables). If you have customized configuration via systemd drop-ins or overrides (https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html) please include those as well. -->
- Installed K3s: 
curl -sfL https://get.k3s.io | sh -

**Expected behavior:**
<!-- A clear and concise description of what you expected to happen. -->
```exec into busybox container and curl -X GET  http://some-service:port```
OR  
```curl -X GET http://any-node-ip-in-cluster:port ```
to get access to the target service

**Actual behavior:**
<!-- A clear and concise description of what actually happened. -->
works only on the node that is running the service

**Additional context / logs:**
<!-- Add any other context and/or logs about the problem here. -->
```
root@vova-test:~# kubectl run -it --rm --restart=Never busybox --image=radial/busyboxplus:curl sh
If you don't see a command prompt, try pressing enter.
[ root@busybox:/ ]$ curl -X GET http://147.75.87.81:30009
^C
[ root@busybox:/ ]$ curl -X GET http://147.75.87.81:30009/api/magicbox/healthcheck
^C
[ root@busybox:/ ]$ curl -X GET http://magicbox-1:30009/api/magicbox/healthcheck
```
-
```
root@vova-test:~# kubectl exec -i -t dnsutils -- nslookup kubernetes.default
;; connection timed out; no servers could be reached

command terminated with exit code 1
```

```
apiVersion: v1
kind: Service
metadata:
  name: magicbox-1
spec:
  type: NodePort
  selector:
    app: magicbox-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009                                                                                                                                                                                                            
```

```
apiVersion: v1
kind: Pod
metadata:
  name: magicbox-1
  labels:
    app: magicbox-1
spec:
  containers:
  - name: pm0
    image: #################
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /dev/LOCKER
      name: locker
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: true
      readOnlyRootFilesystem: false
  volumes:
  - name: locker
    hostPath:
      path: /dev/ttyUSB0
      type: ""
  imagePullSecrets:
    - name: externaljustin
  nodeSelector:
    server: "odroid"
```
