### ISSUE TITLE
How to customize traefik2 config

### ISSUE THREAD

**Issue by zeromake** [k3s-io/k3s#4589]
**Environmental Info:**
K3s Version: 
```
k3s version v1.22.3+k3s1 (61a2aab2)
go version go1.16.8
```

Node(s) CPU architecture, OS, and Version: 
```
Linux k3s-zeromake-1 5.10.78-0-lts #1-Alpine SMP Thu, 11 Nov 2021 14:31:09 +0000 x86_64 Linux
```

Cluster Configuration:

1 servers, 0 agents. 

**Describe the issue:**
I need use `traefik2` export kubernetes-dashboard https port, but It was not found [insecureskipverify](https://doc.traefik.io/traefik/routing/overview/#insecureskipverify) option.
kubernetes-ingress
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dashboard-ingress
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/protocol: "https"
spec:
  tls:
    - hosts:
      - dashboard.zeromake.com
      secretName: dashboard-ingress-certs
  rules:
    - host: dashboard.zeromake.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
```

apply kubernetes-dashboard log
```
2021/11/27 02:14:55 http: TLS handshake error from 10.42.0.35:60538: remote error: tls: bad certificate
2021/11/27 02:14:55 http: TLS handshake error from 10.42.0.35:60540: remote error: tls: bad certificate
2021/11/27 02:16:27 http: TLS handshake error from 10.42.0.35:60920: remote error: tls: bad certificate
2021/11/27 02:17:27 http: TLS handshake error from 10.42.0.35:32942: remote error: tls: bad certificate
```

try:
### change manifests

 `/var/lib/rancher/k3s/server/manifests/traefik.yaml` but system `reboot` file is reset.

### use traefik2 crd

apply yml

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-servers-transport
  namespace: kubernetes-dashboard
spec:
  serverName: "test"
  insecureSkipVerify: true
```

**Comment by ChristianCiach** [comment]
This is more a question about Traefik and less about K3s. Anyway, some general advise:

* Use `IngressRoute` instead of `Ingress` to make such things easier when using Traefik.
* If you want to use `insecureSkipVerify` anyway, consider deploying your kubernetes-dashboard using plain `http` instead `https`. Let traefik terminate wireguard. If you need encryption *within* your cluster, consider configuring Flannel with the `wireguard` or `ipsec` backends.
* you should not edit the manifests at `/var/lib/rancher/k3s/server/manifests/`, because these changes are not persistent (will be reset when updating K3s). Consider deploying a `HelmChartConfig` to customize Traefik. 

But to answer your question: You are not telling Traefik to actually *use* your `ServersTransport`. When your `Ingress` you have to put the following annotation on your `Service`, *not* your `Ingress`. 

```
traefik.ingress.kubernetes.io/service.serverstransport: traefik-servers-transport@kubernetescrd
```
See the documentation: https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/ 

Again, this is easier when using `IngressRoute`, because there you can reference the `ServersTransport` directly from the `IngressRoute` resource.

**Comment by zeromake** [comment]
@ChristianCiach 
Thank you so much, I change to `IngressRoute` and set `ServersTransport` now the access is normal.
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-servers-transport
  namespace: kubernetes-dashboard
spec:
  serverName: "test"
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-dashboard-route
  namespace: kubernetes-dashboard
spec:
  entryPoints:
    - websecure
  tls:
    secretName: dashboard-ingress-certs
  routes:
  - match: Host(`dashboard.zeromake.com`)
    kind: Rule
    services:
      - name: kubernetes-dashboard
        port: 443
        scheme: https
        serversTransport: traefik-servers-transport
```
