### ISSUE TITLE
Dind not working

### ISSUE THREAD

**Issue by speedfl** [k3s-io/k3s#4789]
**Environmental Info:**
K3s Version: 
```
k3s version v1.22.4+k3s1 (bec170bc)
go version go1.16.10
```

Node(s) CPU architecture, OS, and Version: 
```
Linux linuxdegeoff 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
Local dev. One node

**Describe the bug:**
I cannot use docker dind.

**Steps To Reproduce:**

Start k3s:
```
sudo k3s server --data-dir /home/gmuselli/.rancher/k3s
```
Create the following template:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-dind
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 10
  volumes:
  - name: dind-storage
    emptyDir: {}
  containers:
  - name: dind
    image: docker:dind
    securityContext:
      privileged: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /var/lib/docker
      name: dind-storage
    command: [ "tail" ]
    args: [ "-f" ]
  - name: my-container
    image: docker
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    command: [ "tail" ]
    args: [ "-f" ]
```
```
kubectl create -f pod.yaml
```

Connect to pod
```
kubectl exec -it test-dind -c ​my-container sh 
docker  images
# Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?
```

If you connect to dind:

```
kubectl exec -it test-dind -c ​dind sh 
docker  images
# Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Expected behavior:**
Might be able to use dind

**Actual behavior:**
```
Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?
```

**Backporting**
- [X] Needs backporting to older releases
