### ISSUE TITLE
Traefik 2.5.0 fetching

### ISSUE THREAD

**Issue by gelleson** [k3s-io/k3s#4834]
**Environmental Info:**
K3s Version: 
k3s version v1.22.5+k3s1
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
Linux k3s 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:30:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
single server

**Describe the bug:**
k3s cannot to up traefik becauserequested  version of traefik is 2.5.0
k3s tried to pull rancher/library-traefik:2.5.0 but it doesn't exist in docker hub last presented version is 2.4.9

**Steps To Reproduce:**
I have install with default 
```bash
k3sup install --ip {ip_address} --user test --ssh-key ./keys/test --local-path={local_path} --k3s-channel stable
```
**Expected behavior:**
i have expected to up traefik :) 
**Actual behavior:**
k3s is pull 2.5.0
**Additional context / logs:**
Error: ImagePullBackOff
**Backporting**
I think we need to backort or just create image :)
- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Have you customized the Traefik helm chart to override the image name or tag? Recent releases of K3s, including all releases in the 1.22 branch, use `rancher/mirrored-library-traefik`, not `rancher/library-traefik`.

https://github.com/k3s-io/k3s/blob/c4d58001cc0ca46c219befb12c83ccb19c63d92e/manifests/traefik.yaml#L35

**Comment by gelleson** [comment]
@brandond I haven't customized anything :) I just used default config but just used helm config to override args

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.le.acme.dnschallenge.provider=netlify"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
    env:
      - name: NETLIFY_TOKEN
        valueFrom:
          secretKeyRef:
            name: netlify
            key: token
    rbac:
      enabled: true
    ports:
      websecure:
        tls:
          enabled: true
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      name: "rancher/library-traefik"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

```
