### ISSUE TITLE
the field `ttlSecondsAfterFinished` is dropped when creating a job in k3s 1.20 

### ISSUE THREAD

**Issue by jiaqiluo** [k3s-io/k3s#4837]
**Environmental Info:**
K3s Version:  v1.20.14-k3s1
 

Node(s) CPU architecture, OS, and Version: use k3d to run it on Mac: `k3d cluster create --image rancher/k3s:v1.20.14-k3s1`

Cluster Configuration: 1 server 

**Describe the bug:**

K3s does not recognize the field `ttlSecondsAfterFinished` in Job and drops the values 

**Steps To Reproduce:**

create a Job by using the following YAML:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-ttl
spec:
  ttlSecondsAfterFinished: 900
  template:
    spec:
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
      - key: "node.kubernetes.io/unschedulable"
        operator: "Exists"
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
```
Once the Job is created, run `kubectl get job pi-with-ttl -o yaml` 

**Expected behavior:**

The field  `Spec.ttlSecondsAfterFinished` should be set 

**Actual behavior:**

The field  `Spec.ttlSecondsAfterFinished` does not exist. 

**Additional context / logs:**

`v1.21.5+k3s2 ` and `v1.22.5+k3s1` do not have the issue. 
 

**Backporting**

- [ ] Needs backporting to older releases
