### ISSUE TITLE
Consider adding EXPOSE to Dockerfile for GitLab CI compatibility

### ISSUE THREAD

**Issue by DylanGriffith** [k3s-io/k3s#492]
People may benefit from using k3s [as a service in GitLab CI](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service). This can be really neat when running tests against a Kubernetes cluster.

In order for this to work GitLab CI expects to see an exposed port from the container. If we could expose port `6443` this would make it super simple to use `k3s` in a CI job like so:

```yml
variables:
  DOCKER_DRIVER: overlay2

test:
  stage: test
  image: image-with-kubectl
  services:
    - name: docker:stable-dind
    - name: rancher/k3s:v0.5.0
      command: ["server", "--cluster-secret", "some-secret"]
  script:
    - kubectl config set-cluster k3s --server https://node:some-secret@k3s:6443 --insecure-skip-tls-verify
    - kubectl config set-context k3s --cluster=k3s
    - kubectl config use-context k3s
    - kubectl version
```
