### ISSUE TITLE
Update packaged image versions

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#4938]
Update packaged images for 1.23 releases:
* rancher/local-path-provisioner:v0.0.21
* rancher/mirrored-coredns-coredns:1.8.6
* rancher/mirrored-library-busybox:1.34.1
* rancher/mirrored-metrics-server:0.5.2
* rancher/mirrored-library-traefik:2.5.6
* rancher/mirrored-pause:3.6

**Comment by VestigeJ** [comment]
$ k3s -v
```
k3s version v1.23.1+k3s-01388fee (01388fee)
go version go1.17.5
```

$ cat volume-test.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: kube-system
spec:
  containers:
  - name: volume-test
    image: rancher/mirrored-pause:3.6
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc
```

$ sudo k3s crictl images
```
IMAGE                                        TAG                    IMAGE ID            SIZE
docker.io/rancher/klipper-helm               v0.6.6-build20211022   194c895f8d63f       84.5MB
docker.io/rancher/klipper-lb                 v0.3.4                 746788bcc27e2       3.33MB
docker.io/rancher/local-path-provisioner     v0.0.21                fb9b574e03c34       11.4MB
docker.io/rancher/mirrored-coredns-coredns   1.8.6                  a4ca41631cc7a       13.6MB
docker.io/rancher/mirrored-library-busybox   1.34.1                 beae173ccac6a       777kB
docker.io/rancher/mirrored-library-traefik   2.5.6                  2cd4bc25ad14d       30MB
docker.io/rancher/mirrored-metrics-server    v0.5.2                 f73640fb50619       26MB
docker.io/rancher/mirrored-pause             3.6                    6270bb605e12e       301kB
```
