### ISSUE TITLE
Support image registry path rewriting in containerd

### ISSUE THREAD

**Issue by cruzanstx** [k3s-io/k3s#4961]
**Is your feature request related to a problem? Please describe.**
I am attempting to mirror a repo to a specific namespace within an image registry. ie docker.io/ ---> git.companyx.com/Group/Project/ .

**Describe the solution you'd like**
This feature has been solved on under rancher rke2 (https://github.com/rancher/rke2/issues/741) by exposing the rewrite option in the registries.yaml config file. 

Example: 

```
---
mirrors:
  docker.io:
    endpoint:
      - "https://my.registry.com"
    rewrite:
      "^rancher/(.*)": "testing/maxtest/$1"
configs:
  "my.registry.com":
    auth:
      username: fakeuser
      password: fakepass
    tls:
      ca_file: /etc/docker/certs.d/my.registry.com/ca.crt
```

**Describe alternatives you've considered**
There are some alternatives that involve using a nginx proxy to rewrite the path on request but increase complexity and adds more external requirements. 

**Additional context**
If you run ```crictl info``` the rewrite flag exists but is null.

```
    "registry": {
      "mirrors": {
        "docker.io": {
          "endpoint": [
            "http://gitlab.local:5050/local/docker"
          ],
          "rewrite": null
        },
        "gitlab.local:5050": {
          "endpoint": [
            "http://gitlab.local:5050"
          ],
          "rewrite": null
        }
      },
```

**Backporting**
No back porting is required as current versions ignore the rewrite key in registries.yaml.
