### ISSUE TITLE
flannel-backend=wireguard doesn't correctly set reduced mtu.

### ISSUE THREAD

**Issue by jgreat** [k3s-io/k3s#5101]
**Environmental Info:**
K3s Version: v1.23.3+k3s1, v1.22.6+k3s1, v1.21.9+k3s1

Node(s) CPU architecture, OS, and Version: 

```
Linux k3s-control000000 5.11.0-1027-azure #30~20.04.1-Ubuntu SMP Wed Jan 12 20:56:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

Cluster nodes don't really matter,  Single node or 2 control-plane and 10+ workers. 

**Describe the bug:**

We found that when running in Azure we need to reduce the MTU on eth0 to 1400 and allow flannel interfaces to auto set MTU to 1350 to avoid large amounts of fragmentation which causes a pretty big drop in network performance.  

The [azure network performance guide](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-tcpip-performance-tuning) says that you _shouldn't_ have to do this, but :shrug: 

Looks like the wireguard settings are not properly detecting the MTU and defaulting to 1420 (1500 - 80?).

--flannel-backend=vxlan (default)
```
root@k3s-control000000:~# ip addr 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:a8:f2:b9 brd ff:ff:ff:ff:ff:ff
    inet 172.20.160.10/21 brd 172.20.167.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:fea8:f2b9/64 scope link 
       valid_lft forever preferred_lft forever
3: enP58095s1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1400 qdisc mq master eth0 state UP group default qlen 1000
    link/ether 00:0d:3a:a8:f2:b9 brd ff:ff:ff:ff:ff:ff
    altname enP58095p0s2
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1350 qdisc noqueue state UNKNOWN group default 
    link/ether d2:09:d1:0d:22:97 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::d009:d1ff:fe0d:2297/64 scope link 
       valid_lft forever preferred_lft forever
```

--flannel-backend=wireguard

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:a8:f2:b9 brd ff:ff:ff:ff:ff:ff
    inet 172.20.160.10/21 brd 172.20.167.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:fea8:f2b9/64 scope link 
       valid_lft forever preferred_lft forever
3: enP58095s1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1400 qdisc mq master eth0 state UP group default qlen 1000
    link/ether 00:0d:3a:a8:f2:b9 brd ff:ff:ff:ff:ff:ff
    altname enP58095p0s2
4: flannel.1: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.42.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
5: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default qlen 1000
    link/ether be:f3:bc:4a:a5:5e brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.1/24 brd 10.42.0.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::bcf3:bcff:fe4a:a55e/64 scope link 
       valid_lft forever preferred_lft forever
6: veth926ba952@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master cni0 state UP group default 
    link/ether 9a:5e:7c:e6:1f:b2 brd ff:ff:ff:ff:ff:ff link-netns cni-c3acb8c7-67e8-4496-c778-e98b81bb490b
    inet6 fe80::985e:7cff:fee6:1fb2/64 scope link 
       valid_lft forever preferred_lft forever
```

Digging into the wireguard set up looks like there's a PostStartupCommand for flannel that runs wg-add.sh, and that script is some really arcane bash that i'm guessing is falling through to `[[ $mtu -gt 0 ]] || mtu=1500`?

/var/lib/rancher/k3s/agent/etc/flannel/net-conf.json
```json
{
	"Network": "10.42.0.0/16",
	"EnableIPv6": false,
	"IPv6Network": "::/0",
	"Backend": {
	"Type": "extension",
	"PreStartupCommand": "wg genkey | tee /var/lib/rancher/k3s/agent/etc/flannel/privatekey | wg pubkey",
	"PostStartupCommand": "export SUBNET_IP=$(echo $SUBNET | cut -d'/' -f 1); ip link del flannel.1 2>/dev/null; echo $P
ATH >&2; wg-add.sh flannel.1 && wg set flannel.1 listen-port 51820 private-key /var/lib/rancher/k3s/agent/etc/flannel/privat
ekey && ip addr add $SUBNET_IP/32 dev flannel.1 && ip link set flannel.1 up && ip route add $NETWORK dev flannel.1",
	"ShutdownCommand": "ip link del flannel.1",
	"SubnetAddCommand": "read PUBLICKEY; wg set flannel.1 peer $PUBLICKEY endpoint $PUBLIC_IP:51820 allowed-ips $SUBNET 
persistent-keepalive 25",
	"SubnetRemoveCommand": "read PUBLICKEY; wg set flannel.1 peer $PUBLICKEY remove"
}
}
```

So wg-add.sh is being run with `wg-add.sh flannel.1` 

/var/lib/rancher/k3s/data/current/bin/aux/wg-add.sh
```
#!/usr/bin/env bash

auto-mtu() {
	local mtu=0 endpoint output
	while read -r _ endpoint; do
		[[ $endpoint =~ ^\[?([a-z0-9:.]+)\]?:[0-9]+$ ]] || continue
		output="$(ip route get "${BASH_REMATCH[1]}" || true)"
		[[ ( $output =~ mtu\ ([0-9]+) || ( $output =~ dev\ ([^ ]+) && $(ip link show dev "${BASH_REMATCH[1]}") =~ mtu\ ([0-9]+) ) ) && ${BASH_REMATCH[1]} -gt $mtu ]] && mtu="${BASH_REMATCH[1]}"
	done < <(wg show "$1" endpoints)
	if [[ $mtu -eq 0 ]]; then
		read -r output < <(ip route show default || true) || true
		[[ ( $output =~ mtu\ ([0-9]+) || ( $output =~ dev\ ([^ ]+) && $(ip link show dev "${BASH_REMATCH[1]}") =~ mtu\ ([0-9]+) ) ) && ${BASH_REMATCH[1]} -gt $mtu ]] && mtu="${BASH_REMATCH[1]}"
	fi
	[[ $mtu -gt 0 ]] || mtu=1500
	ip link set mtu $(( mtu - 80 )) up dev "$1"
}

# probe for any modules that may be needed
modprobe wireguard
modprobe tun

# try wireguard kernel module first
ip link add "$1" type wireguard && exit

# try boringtun and let it drop privileges
boringtun "$1" && auto-mtu "$1" && exit

# try boringtun w/o dropping privileges
WG_SUDO=1 boringtun "$1" && auto-mtu "$1" && exit

# try wireguard-go - p.s. should not use wireguard-go, it leaks memory
WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD=1 wireguard-go "$1" && auto-mtu "$1" && exit

exit 1
```

I think its trying 
- first to see if flannel.1 is a wireguard device and get mtu? (I'm not sure why since the first step in PostStartup is to tear down the flannel.1)
- If not get mtu for device with the default route? 
- else set mtu to 1500?
- then set detected mtu to (mtu - 80) on flannel.1

I'm not sure why it seems like its falling through to the default `mtu=1500`

Running the auto-mtu() manually seems to get the proper 1400 value.

**Steps To Reproduce:**

Cloud-init 

```yaml
#cloud-config
packages:
- wireguard
write_files:
- path: /etc/rancher/k3s/config.yaml
  owner: root:root
  permissions: '0600'
  encoding: gz+b64
  content: |
    ${k3s_config_yaml}
- path: /usr/local/sbin/k3s-install.sh
  owner: root:root
  permissions: '0700'
  encoding: gz+b64
  content: |
    ${k3s_install_sh}
- path: /etc/netplan/40-mtu-override.yaml
  owner: root:root
  permissions: '0644'
  encoding: gz+b64
  content: |
    ${netplan_mtu_override_yaml}
runcmd:
- netplan generate
- netplan apply
- /usr/local/sbin/k3s-install.sh
- ${rancher_join_command}
```

/etc/netplan/40-mtu-override.yaml
```yaml
network:
    version: 2
    ethernets:
        eth0:
            mtu: 1400
```

- Installed K3s: 

/etc/rancher/k3s/config.yaml  - without wireguard
```yaml
agent-token: ${k3s_agent_token}
datastore-endpoint: "${k3s_db_url}"
datastore-cafile: /etc/rancher/k3s/ca-cert.pem
disable:
- servicelb
- local-storage
- traefik
flannel-iface: eth0
token: ${k3s_server_token}
node-taint:
- "node-role.kubernetes.io/master=true:NoSchedule"
write-kubeconfig-mode: "644"
```

/etc/rancher/k3s/config.yaml  - with wireguard
```yaml
agent-token: ${k3s_agent_token}
datastore-endpoint: "${k3s_db_url}"
datastore-cafile: /etc/rancher/k3s/ca-cert.pem
disable:
- servicelb
- local-storage
- traefik
flannel-iface: eth0
flannel-backend: wireguard
token: ${k3s_server_token}
node-taint:
- "node-role.kubernetes.io/master=true:NoSchedule"
write-kubeconfig-mode: "644"
```

Install k3s:
```
export INSTALL_K3S_VERSION=${k3s_version}
export INSTALL_K3S_EXEC="server --config /etc/rancher/k3s/config.yaml"
curl --retry 5 -fL https://get.k3s.io | sh -
```

**Expected behavior:**
Expect interface MTUs to be set to less that "physical" interfaces.

**Actual behavior:**
eth0 is set to 1400
flannel1.1 is set to 1420
veth interfaces are set to 1400

**Comment by brandond** [comment]
We're actually working on dropping the hacky shell-extension-based wireguard backend, in favor of using the native flannel wireguard backend. I suspect that will handle this properly.
cc @manuelbuil

**Comment by manuelbuil** [comment]
yep, I'm waiting on this user to address the comment about upgrades https://github.com/k3s-io/k3s/pull/5011. If he does not reply soon, I might take it over

**Comment by rbrtbnfgl** [comment]
I didn't tested when mtu is greater than 1500 I only tested when it's lower. The CNI calculate the right MTU for the pod interfaces and in case of MTU lower than 1500 even if flannel-wg has an higher MTU the traffic is generated by the pods that has the right MTU configured.
I did a quick test with an higher MTU like yours and we have that flannel-wg interface will fragment the packets using its lower MTU.
If we want to support MTU higher than 1500 without fragmentation we have to modify flannel directly, but I don't know if it is a valid setup.

**Comment by katran001** [comment]
@ShylajaDevadiga is this resolved or should I move it to next milestone?

**Comment by rbrtbnfgl** [comment]
you can move it on the next milestone. It's fixed on the newer version of flannel but we didn't update it on K3s yet.

**Comment by katran001** [comment]
Leave as is. Need to update flannel. Should be released in June release

**Comment by VestigeJ** [comment]
**Environment Details-**
 
*Node(s) CPU architecture, OS, and Version:*

Linux 5.4.0-1009-aws x86_64 GNU/Linux-Ubuntu 20.04.4 LTS

*Cluster Configuration:*
```
NAME             STATUS   ROLES                  AGE   VERSION
ip-1-1-1-7   Ready    control-plane,master   67s   v1.23.7+k3s-4dda76b0 
```
*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: coolclouds
disable-netowrk-policy: true
flannel-iface: eth0
flannel-backend: wireguard-native
```

**Validated with COMMIT=4dda76b0a9870a6724a3c0846578384380c430d6**
```
   $  sudo apt install wireguard
   $  COMMIT=4dda76b0a9870a6724a3c0846578384380c430d6
   $  sudo vim /etc/netplan/40-mtu-override.yaml
   $  sudo service networking restart
   $  sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=server sh - ./install-k3s.sh 
   $  ip a | grep mtu
```

**Results:**
$ ip a | grep mtu
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc mq state UP group default qlen 1000
22: flannel-wg: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default 
23: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1320 qdisc noqueue state UP group default qlen 1000
24: veth5567e8c4@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1320 qdisc noqueue master cni0 state UP group default 
27: vethe6e9a0eb@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1320 qdisc noqueue master cni0 state UP group default 
28: vethe91e75c0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1320 qdisc noqueue master cni0 state UP group default 
29: vethf2f575a8@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1320 qdisc noqueue master cni0 state UP group default 
30: vethd0542631@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1320 qdisc noqueue master cni0 state UP group default 
```

**Additional context / logs:**
note this can also be achieved temporarily by passing an mtu to ifconfig with the interface to target.
$ ifconfig eth0 mtu 1400 up
$ sudo cat /etc/netplan/40-mtu-override.yaml 
```
network:
    version: 2
    ethernets:
        eth0:
            mtu: 1400
```
