### ISSUE TITLE
Traefik Service and Pod deployed, but not IngressController

### ISSUE THREAD

**Issue by OneCricketeer** [k3s-io/k3s#5131]
**Environmental Info:**
K3s Version: 

```
# k3s -v
k3s version v1.22.6+k3s1 (3228d9cb)
go version go1.16.10
```

Node(s) CPU architecture, OS, and Version: 

```
Linux dietpi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
```

Cluster Configuration:

1 server

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s via dietpi and have a SystemD process running `k3s server` without any obvious flags for things being disabled. 

**Expected behavior:**

Wanting to access a publicly addressable Traefik dashboard

This should show an Ingress, according to the docs

>  The Traefik ingress controller will use ports 80 and 443 on the host (i.e. these will not be usable for HostPort or NodePort).

And it appears that the service itself uses different port mappings. I have nothing else running on 80/443 (checked netstat)

```
$ kubectl get -n kube-system svc | grep traefik
traefik          LoadBalancer   10.43.199.240   192.168.2.248   80:30576/TCP,443:31861/TCP   22h
$ curl http://192.168.2.248:30576  # What is this?
404 page not found
$ kubectl get ingresses -A
No resources found
```

**Actual behavior:**

There's nothing bound to ports 80/443

**Additional context / logs:**

Seems the probes are failing

```yml
$ kubectl -n kube-system describe po/traefik-55fdc6d984-r6dhv
Name:                 traefik-55fdc6d984-r6dhv
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 xx/x.x.x.x
Start Time:           Tue, 15 Feb 2022 14:26:24 -0600
Labels:               app.kubernetes.io/instance=traefik
                      app.kubernetes.io/managed-by=Helm
                      app.kubernetes.io/name=traefik
                      helm.sh/chart=traefik-10.9.100
                      pod-template-hash=55fdc6d984
Annotations:          prometheus.io/path: /metrics
                      prometheus.io/port: 9100
                      prometheus.io/scrape: true
Status:               Running
IP:                   10.42.0.13
IPs:
  IP:           10.42.0.13
Controlled By:  ReplicaSet/traefik-55fdc6d984
Containers:
  traefik:
    Container ID:  containerd://ea5ec224dd5e8628475ad9d08535c665ee2aea392a4fe12ff03741187a109898
    Image:         rancher/mirrored-library-traefik:2.5.6
    Image ID:      docker.io/rancher/mirrored-library-traefik@sha256:b02bfc3350c6d343e42bfab5f3ae5dad4674e49b81b093b00b0e09be8d120525
    Ports:         9100/TCP, 9000/TCP, 8000/TCP, 8443/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      --global.checknewversion
      --global.sendanonymoususage
      --entryPoints.metrics.address=:9100/tcp
      --entryPoints.traefik.address=:9000/tcp
      --entryPoints.web.address=:8000/tcp
      --entryPoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --metrics.prometheus=true
      --metrics.prometheus.entrypoint=metrics
      --providers.kubernetescrd
      --providers.kubernetesingress
      --providers.kubernetesingress.ingressendpoint.publishedservice=kube-system/traefik
      --entrypoints.websecure.http.tls=true
    State:          Running
      Started:      Wed, 16 Feb 2022 11:39:27 -0600
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 16 Feb 2022 11:37:48 -0600
      Finished:     Wed, 16 Feb 2022 11:39:20 -0600
    Ready:          True
    Restart Count:  5
    Liveness:       http-get http://:9000/ping delay=10s timeout=2s period=10s #success=1 #failure=3
    Readiness:      http-get http://:9000/ping delay=10s timeout=2s period=10s #success=1 #failure=1
    Environment:    <none>
    Mounts:
      /data from data (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8jq6s (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-8jq6s:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 CriticalAddonsOnly op=Exists
                             node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  7m53s (x12 over 17h)  kubelet  Liveness probe failed: Get "http://10.42.0.13:9000/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  7m53s (x21 over 17h)  kubelet  Readiness probe failed: Get "http://10.42.0.13:9000/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Backporting**

- [ ] Needs backporting to older releases
