### ISSUE TITLE
registries.yaml gcr auth credential

### ISSUE THREAD

**Issue by gfrankliu** [k3s-io/k3s#5141]
When using registries.yaml to setup mirror to GCR, we use username: _json_key, but paste the content from the service account key json file. It would be easier to introduce something like:

```
  password_from_file: /etc/google/auth/application_default_credentials.json
```
so k3s can read the json content from the file, instead of relying on engineers to paste the content into the config.

Also, GCR can use multiple endpoints for different regions. It would be nice if we can configure all of them with same credential, something like:

```
mirrors:
  my_gcr:
    endpoint:
      - "https://eu.gcr.io"
      - "https://us.gcr.io"
      - "https://gcr.io"
configs:
  my_gcr:
    auth:
      username: _json_key
      password: 'XXXXXX'
```

**Comment by brandond** [comment]
For the second ask - I think you kind of have it the wrong way around, unless you want to specifically pull all your images from `my_gcr` instead of `grc.io`, and have it try all the regional endpoints in order.

However, this being YAML, I think you could get what you want with anchors. Specifying endpoints isn't necessary since you're just using the defaults.
```yaml
configs:
  gcr.io: &gcr
    auth:
      username: _json_key
      password: 'XXXXXX'
  eu.gcr.io:
     <<: *gcr
  us.gcr.io:
    <<: *gcr
```

**Comment by gfrankliu** [comment]
Ah, I thought my_gcr was just a "tag", and the endpoint was the actual URL. 

If I understand you correct, the my_gcr really should be the "frontend" url that image puller uses, and endpoint is the "backend "urls, more like a reverse proxy setup. 

When you said `Specifying endpoints isn't necessary since you're just using the defaults`, does "defaults" mean frontend and backend urls equal?

**Comment by brandond** [comment]
https://github.com/containerd/containerd/blob/main/docs/cri/registry.md

> As an example, for the image `gcr.io/library/busybox:latest`, the endpoints are:
> *  `gcr.io` is configured: endpoints for gcr.io + default endpoint `https://gcr.io/v2`.
> *  `*` is configured, and gcr.io is not: endpoints for `*` + default endpoint `https://gcr.io/v2`.
> *  None of above is configured: default endpoint `https://gcr.io/v2`.

**Comment by gfrankliu** [comment]
That works, now we just need add `password_from_file` feature so that the credential can be loaded directly from the key.json file.

**Comment by gfrankliu** [comment]
If I use gcr in many different regions, is it possible to use wildcard?, something like
```
configs:
  *.gcr.io:
    auth:
      username: _json_key
      password: 'XXXXXX'
```
