### ISSUE TITLE
Volume subPath not working for NFS volumes

### ISSUE THREAD

**Issue by StefanNienhuis** [k3s-io/k3s#5165]
**Environmental Info:**
```
k3s version v1.22.6+k3s1 (3228d9cb)
go version go1.16.10
```

Node(s) CPU architecture, OS, and Version: 

- Single node, almost fresh RHEL install. - `Linux HomeServer.local 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Mon Jan 17 07:06:06 EST 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
1 master node

**Describe the bug:**
When specifying a subPath for an nfs volume mount, the pod fails to start with the error event:
```
Error: failed to prepare subPath for volumeMount "data" of container "test"
```

The k3s.service log:
```
Feb 25 10:23:27 HomeServer.local k3s[29612]: E0225 10:23:27.660252   29612 kubelet_pods.go:218] "Could not determine if subPath exists, will not attempt to change its permissions" path="/var/lib/kubelet/pods/a7358fc5-5558-405c-a4f8-9a146bfe519b/volumes/kubernetes.io~nfs/nfs/testdata"
Feb 25 10:23:27 HomeServer.local k3s[29612]: E0225 10:23:27.660819   29612 kubelet_pods.go:245] "Failed to prepare subPath for volumeMount of the container" err="error resolving symlinks in \"/var/lib/kubelet/pods/a7358fc5-5558-405c-a4f8-9a146bfe519b/volumes/kubernetes.io~nfs/nfs/testdata\": lstat /var/lib/kubelet/pods/a7358fc5-5558-405c-a4f8-9a146bfe519b/volumes/kubernetes.io~nfs/nfs/testdata: permission denied" containerName="test" volumeMountName="data"
```

The last line of the service log says `permission denied`, but the folders are configured with `1000:1001` (default user, with custom group) and `770` permissions. From what I could find, K3s runs as root, so I would assume it has access to this. Unless the volume mount is somehow running as another user, in which case I'd like to add it to the group that can access the file.

**Steps To Reproduce:**

- Installed K3s (disabled Traefik and ServiceLB)
- Have a running NFS server
- Deploy the following resources:
```yaml
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nfs

spec:
  capacity:
    storage: 32Gi

  accessModes:
    - ReadWriteMany

  nfs:
    server: HomeServer
    path: /data/kubernetes-data

  mountOptions:
    - nfsvers=4.2
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nfs

spec:
  volumeName: nfs
  storageClassName: ''

  resources:
    requests:
      storage: 1Mi
  
  accessModes:
    - ReadWriteMany
```

```yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: test

  labels:
    app: test

spec:
  selector:
    matchLabels:
      app: test

  template:
    metadata:
      labels:
        app: test

    spec:
      containers:
        - name: test
          image: ubuntu
          workingDir: /testdata
          command: ['sh', '-c', 'ls']

          volumeMounts:
            - name: data
              mountPath: /testdata
              subPath: testdata

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs

      securityContext:
        fsGroup: 1001
```

Running this all without the `subPath: testdata` runs fine, so I doubt it's a permission issue.

**Expected behavior:**

I expected the container to start with the subPath volume mount.

**Actual behavior:**

The container fails to start with the subPath volume mount.

**Additional context / logs:**

See above

**Backporting**

- [ ] Needs backporting to older releases
