### ISSUE TITLE
Enable http3 support for Traefik 

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5184]
**Is your feature request related to a problem? Please describe.**

Ask for by the community in this PR: https://github.com/k3s-io/k3s/pull/5069
**Describe the solution you'd like**

https://github.com/k3s-io/k3s/pull/5069/files#diff-950b8e60144da8e48c9c65a3e25d0c4cd3264400aca9bbf94d6f30e7dc2f030cR24

**Describe alternatives you've considered**

**Additional context**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
http3 support is no longer experimental as of v18.0.0 of the chart, but it still is not enabled by default.

Note that due to an issue in how helm patches the service spec, you may need to delete the traefik service before applying the following config in order to get the UDP port created correctly. If you don't it simply won't expose the udp port for http3.

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        http3:
          enabled: true
          advertisedPort: 443
```
