### ISSUE TITLE
NFS subPath mount fails

### ISSUE THREAD

**Issue by adyanth** [k3s-io/k3s#5212]
**Environmental Info:**
K3s Version: 
k3s version v1.22.7+k3s1 (8432d7f2)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
`Linux kratos-master 5.10.93-6.ph4-esx #1-photon SMP Thu Feb 17 02:54:43 UTC 2022 x86_64 GNU/Linux`

Cluster Configuration:
1 server (sqlite), 2 workers

**Describe the bug:**
Attempting to mount a subpath of an existing NFS share fails with the error:
Error: failed to prepare subPath for volumeMount "data" of container "pod"

**Steps To Reproduce:**

- Installed K3s: using k3sup, --disable servicelb --disable traefik

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
        - name: test
          nfs:
            server: nas.adyanth.lan
            path: /export/Folder
      containers:
        - name: test
          image: alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: test
              mountPath: /test
              subPath: completed
```

**Expected behavior:**
I expect the mount to work

**Actual behavior:**
```bash
$ k describe pod -l app=test | tail -1
Warning  Failed     6s (x3 over 27s)  kubelet            Error: failed to prepare subPath for volumeMount "test" of container "test"
```

**Additional context / logs:**
Removing the subPath works fine. The subPath folder already exists.

https://github.com/kubernetes/kubernetes/issues/108374

**Backporting**

- [ ] Needs backporting to older releases
