### ISSUE TITLE
CertificateSigningRequest not issuing the cert

### ISSUE THREAD

**Issue by networkop** [k3s-io/k3s#524]
**Description**: certificates.k8s.io does not work as expected
I can create and approve CSR requests, but I can't see certificate being issued.

**To reproduce**
procedure from the [official guide](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/)
1. Generate CSR
```
cat <<EOF | cfssl genkey - | cfssljson -bare server
{
  "hosts": [
    "my-svc.my-namespace.svc.cluster.local",
    "my-pod.my-namespace.pod.cluster.local",
    "192.0.2.24",
    "10.0.34.2"
  ],
  "CN": "my-pod.my-namespace.pod.cluster.local",
  "key": {
    "algo": "ecdsa",
    "size": 256
  }
}
EOF
```

2. Create CSR resource
```
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
```

3. Approve CSR:
```
kubectl certificate approve  my-svc.my-namespace
```
4. Check CSR status 
Supposed to be Approved,Issued
```
k get csr
NAME                  AGE   REQUESTOR   CONDITION
my-svc.my-namespace   18m   admin       Approved
```
Certificate field is missing:
```
kubectl get csr my-svc.my-namespace -o jsonpath='{.status}'            
map[conditions:[map[lastUpdateTime:2019-06-06T09:48:13Z message:This CSR was approved by kubectl certificate approve. reason:KubectlApprove type:Approved]]]
```
**Expected behaviour**

Certificate status is approved and issued
```
kubectl get csr
NAME                  AGE       REQUESTOR               CONDITION
my-svc.my-namespace   10m       yourname@example.com    Approved,Issued
```
