### ISSUE TITLE
Job backofflimit is not working

### ISSUE THREAD

**Issue by simsicon** [k3s-io/k3s#5276]
**Environmental Info:**
K3s Version: 
k3s version v1.22.6+k3s1 (3228d9cb)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
Linux node1 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

Cluster Configuration:
standalone server

**Describe the bug:**
The config of job backofflimit is not working with k3s, if the job failed, it just keep creating new pods to try to restart.

**Steps To Reproduce:**

Given a job.yaml
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-backofflimit-1
spec:
  template:
    spec:
      containers:
      - name: test-job-backofflimit-1
        image: alpine
        command: ["python",  "nothisfile.py"]
      restartPolicy: Never
  backoffLimit: 1
```

```
kubectl apply -f job.yaml
```

Expected behaviors it should backoff only 1 pods when it fails, but it keep creating, neither 1 nor default 6, it can goes to 10+

**Comment by simsicon** [comment]
I am wondering if this issue is already fixed with the latest version? I am using the stable version, not sure if I should upgrade to the latest version.

**Comment by brandond** [comment]
If this is indeed an issue it would be in upstream Kubernetes, we don't customize the code of the core Kubernetes Job controller in any way.

**Comment by brandond** [comment]
I do note that the pods in your example show as being in status StartError, not Failed. I wonder if perhaps the job controller doesn't respect the backoff limit of the pods fail to start, as opposed to failing after successfully starting.

>   Warning  Failed     3m50s  kubelet            Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "python": executable file not found in $PATH: unknown

**Comment by brandond** [comment]
Hmm, looks like I get the wrong behavior from this also:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-backofflimit-1
spec:
  template:
    spec:
      containers:
      - name: test-job-backofflimit-1
        image: alpine
        command: ["sh", "-c", "sleep 10; exit 1"]
      restartPolicy: Never
  backoffLimit: 1
```

With that Job spec I get 4 pods created before it stops:
```console
/ # kubectl get pods
NAME                               READY   STATUS   RESTARTS   AGE
test-job-backofflimit-1--1-j7dvt   0/1     Error    0          3m45s
test-job-backofflimit-1--1-jh2kt   0/1     Error    0          3m33s
test-job-backofflimit-1--1-hn77b   0/1     Error    0          3m20s
test-job-backofflimit-1--1-kdpxg   0/1     Error    0          3m8s
```

You might consider checking for and/or reporting this upstream?
