### ISSUE TITLE
registries.yaml has no effect with ctr but crictl

### ISSUE THREAD

**Issue by Alceatraz** [k3s-io/k3s#5277]
# Server info

### K3S
```
k3s version v1.22.7+k3s1 (8432d7f2)
go version go1.16.10
```

### Kernel
```
Linux micro1 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### os-release
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Repository (Nexus oss)
- http://nexus:5000
- http://nexus:8080

# Issue

## Follow this doc
`https://rancher.com/docs/k3s/latest/en/installation/private-registry/` Without TLS and WITH AUTHENTICATION section

None of those config working ( I use `systemctl restart k3s`, To make sure `In order for the registry changes to take effect, you need to restart K3s on each node.`)

They all have same issue: 
`crictl info` or `crictl pull` working proper, But `ctr` or the k3s response (kube describe) with: `http: server gave HTTP response to HTTPS client" host="nexus:5000"`. Seems like #3133, But compare that issue to modify my config not working.

```yaml
mirrors:
  "nexus":
    endpoint:
      - "http://nexus:5000"
configs:
  "nexus":
    auth:
      username: admin
      password: admin
```

```yaml
mirrors:
  "nexus:5000":
    endpoint:
      - "http://nexus:5000"
configs:
  "nexus:5000":
    auth:
      username: admin
      password: admin
```

```yaml
mirrors:
  nexus:
    endpoint:
      - "http://nexus:5000"
      - "http://nexus:8080"
configs:
  "nexus":
    auth:
      username: admin
      password: admin
```

```yaml
mirrors:
  "nexus":
    endpoint:
    - "http://nexus:5000"
  "nexus":
    endpoint:
    - "http://nexus:8080"
configs:
  "nexus:5000":
    auth:
      username: admin
      password: admin
  "nexus:8080":
    auth:
      username: admin
      password: admin
```

```yaml
mirrors:
  "nexus:5000":
    endpoint:
    - "http://nexus:5000"
  "nexus:8080":
    endpoint:
    - "http://nexus:8080"
configs:
  "nexus:5000":
    auth:
      username: admin
      password: admin
  "nexus:8080":
    auth:
      username: admin
      password: admin
```

# Issue
Because there two issue mixed so I can't report an accurate issue, Sorry.

## Edit 1 : 

The same thing with origin containerd toml config working fine (K8S using ctr github.com/containerd/containerd 1.5.5-0ubuntu3~20.04.2 and cluster init with kubeadm `--cri-socket=/run/containerd/containerd.sock`):
```toml
[plugins."io.containerd.grpc.v1.cri".registry.configs]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."nexus:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."nexus:5000".auth]
      username = "admin"
      password = "admin"
  [plugins."io.containerd.grpc.v1.cri".registry.configs."nexus:8080"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."nexus:8080".auth]
      username = "admin"
      password = "admin"
[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."nexus:5000"]
    endpoint = ["http://nexus:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."nexus:8080"]
    endpoint = ["http://nexus:8080"]
```

## Edit 2 :

Another try:

```yaml
mirrors:
  "nexus:5000":
    endpoint:
      - "http://nexus:5000"
  "nexus:8080":
    endpoint:
      - "http://nexus:8080"
configs:
  "nexus:5000":
    auth:
      username: admin
      password: admin
  "nexus:8080":
    auth:
      username: admin
      password: admin
```
`/var/lib/rancher/k3s/agent/etc/containerd/config.toml` shows: 

```toml
[plugins.opt]
  path = "/var/lib/rancher/k3s/agent/containerd"
[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "rancher/mirrored-pause:3.6"
[plugins.cri.containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true
[plugins.cri.cni]
  bin_dir = "/var/lib/rancher/k3s/data/31ff0fd447a47323a7c863dbb0a3cd452e12b45f1ec67dc55efa575503c2c3ac/bin"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"
[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
[plugins.cri.registry.mirrors]
[plugins.cri.registry.mirrors."nexus:5000"]
  endpoint = ["http://nexus:5000"]
[plugins.cri.registry.mirrors."nexus:8080"]
  endpoint = ["http://nexus:8080"]
[plugins.cri.registry.configs."nexus:5000".auth]
  username = "admin"
  password = "admin"
[plugins.cri.registry.configs."nexus:8080".auth]
  username = "admin"
  password = "admin"
```

But still

```text
k3s ctr --debug i pull nexus:5000/alpine:latest
DEBU[0000] fetching                                      image="nexus:5000/alpine:latest"
DEBU[0000] resolving                                     host="nexus:5000"
DEBU[0000] do request                                    host="nexus:5000" request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/v1.5.9-k3s1 request.method=HEAD url="https://nexus:5000/v2/alpine/manifests/latest"
INFO[0000] trying next host                              error="failed to do request: Head \"https://nexus:5000/v2/alpine/manifests/latest\": http: server gave HTTP response to HTTPS client" host="nexus:5000"
ctr: failed to resolve reference "nexus:5000/alpine:latest": failed to do request: Head "https://nexus:5000/v2/alpine/manifests/latest": http: server gave HTTP response to HTTPS client
```
