### ISSUE TITLE
Getting Unauthorized error when connecting to k3s cluster using OIDC

### ISSUE THREAD

**Issue by mohamedaminearous** [k3s-io/k3s#5278]
### What happened?
I'm willing to set up OIDC connection to kubernetes via an SSO tool (authentik) using kube-login.
So, I Installed kube-login with krew. Then, I added `oidc-groups-claim` and `oidc-username-claim` to kube-apiserver in the service file of k3s:
```yaml
ExecStart=/usr/local/bin/k3s \
    server \
    '--kube-apiserver-arg' 'oidc-username-claim=email'
    '--kube-apiserver-arg' 'oidc-groups-claim=groups'
```
Then I configured the kubeconfig:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CR***********************************S0tLS0K
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=http://sso.server.company.com/application/o/kubernetes/
      - --oidc-client-id=79cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx72
      - --oidc-client-secret=301e4a2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx093edb62
      - --oidc-extra-scope=email
      - --oidc-extra-scope=profile
      - --oidc-extra-scope=groups
      - --oidc-extra-scope=openid
      - --listen-address=0.0.0.0:8000
      - --oidc-redirect-url-hostname=cluster.server.company.com
      - --skip-open-browser
      command: kubectl
      env: null
      provideClusterInfo: false
```
Afterward, I deployed RBAC linked with groups in Authentik.
I got inspired by this [article](https://developer.okta.com/blog/2021/11/08/k8s-api-server-oidc#what-youll-need-to-get-started)

Unfortunately, I got this error with I use oidc user: `error: You must be logged in to the server (Unauthorized)`.

### What did you expect to happen?
I expect to be authorized to do anything I'm authorized to do respecting the set RBAC.

### Kubernetes version
- kubelogin version: v1.25.1

### Cloud provider
- local machine (k3s)

### OS version
- Debian 11

### Other used tools
- kubectl version: v1.21.7
- OpenID Connect provider: [Authentik](https://github.com/goauthentik/authentik) (SSO)

**Comment by brandond** [comment]
> ExecStart=/usr/local/bin/k3s \
    server \
    '--kube-apiserver-arg' 'oidc-username-claim=email'
    '--kube-apiserver-arg' 'oidc-groups-claim=groups'
    
 You changed the OIDC username and groups for the built-in OIDC provider, but I don't see where you actually configured Kubernetes to trust your provider. You appear to have only set 2 of the 5 flags listed in the documentation you linked to: https://developer.okta.com/blog/2021/11/08/k8s-api-server-oidc#preparing-the-cluster-for-oidc

**Comment by mohamedaminearous** [comment]
> > ExecStart=/usr/local/bin/k3s 
> >     server 
> >     '--kube-apiserver-arg' 'oidc-username-claim=email'
> > '--kube-apiserver-arg' 'oidc-groups-claim=groups'
> 
> You changed the OIDC username and groups for the built-in OIDC provider, but I don't see where you actually configured Kubernetes to trust your provider (oidc-issuer-url, oidc-ca-file, et cetera). You appear to have only set 2 of the 5 flags listed in the documentation you linked to: https://developer.okta.com/blog/2021/11/08/k8s-api-server-oidc#preparing-the-cluster-for-oidc

I did all this but I had the same error unfortunately

**Comment by mohamedaminearous** [comment]
this is my kubeconfig located in .kube/config:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXX
    server: https://127.0.0.1:6443 // I'am testing OIDC on the k8s master node
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=http://sso.server.company.com/application/o/kubernetes/
      - --oidc-client-id=79xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxaz72
      - --oidc-extra-scope=email
      - --oidc-extra-scope=profile
      - --oidc-extra-scope=groups
      - --oidc-extra-scope=openid
      - --listen-address=0.0.0.0:8000
      - --oidc-redirect-url-hostname=kubernetes.server.company.com // k8s master node
      - --skip-open-browser
      - --insecure-skip-tls-verify
      command: kubectl
      env: null
      provideClusterInfo: false
      ```
      k3s service file located in /etc/systemd/system/k3s.service:
      ```shell
      ................
      ................
      ................
      ExecStart=/usr/local/bin/k3s \
    server \
    '--kube-apiserver-arg' 'oidc-username-claim=email' \
    '--kube-apiserver-arg' 'oidc-groups-claim=groups' \
    '--kube-apiserver-arg' 'oidc-ca-file=/tmp/ca.pem' \
    '--kube-apiserver-arg' 'oidc-issuer-url=https://sso.server.company.com/application/o/kubernetes/'
    ```
    RBAC:
    ```yaml
    ---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oidc-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: "k8s-admins" // this group is already set in the sso server
  ```
