### ISSUE TITLE
Can't set custom hosts for coredns

### ISSUE THREAD

**Issue by 631068264** [k3s-io/k3s#5312]
**Environmental Info:**
K3s Version: v1.22.7+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux master 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

sigle
**Describe the bug:**

After `kubectl edit configmap coredns` when **restart k3s service** or **add new node** , the config will be rewrite as default.

**Steps To Reproduce:**
-  I have read https://github.com/k3s-io/k3s/issues/462 ,but not work for me.

**Expected behavior:**
I hope it can run like [this](https://docs.microsoft.com/de-de/azure/aks/coredns-custom#hosts-plugin)
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom # this is the name of the configmap you can overwrite with your changes
  namespace: kube-system
data:
    test.override: | # you may select any name here, but it must end with the .override file extension
          hosts { 
              10.0.0.1 example1.org
              10.0.0.2 example2.org
              10.0.0.3 example3.org
              fallthrough
          }
```

**Actual behavior:**

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases
