### ISSUE TITLE
Traefik ingress not working

### ISSUE THREAD

**Issue by pedroresende** [k3s-io/k3s#5516]
**Environmental Info:**
K3s Version: 
k3s version v1.22.7+k3s1 (8432d7f2)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
Linux pegasus 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server

**Describe the bug:**
No traefik route set

**Steps To Reproduce:**

deploy.yaml

```yaml
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: resendebiz
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resendebiz
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: resendebiz
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: traefiklabs
    task: resendebiz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resendebiz
  labels:
    app: resendebiz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resendebiz
  template:
    metadata:
      labels:
        app: resendebiz
    spec:
      containers:
        - name: resendebiz
          image: pmmresende/resende.biz:latest
          ports:
            - containerPort: 3000
```

when running `kubectl get all --all-namespaces`

```bash
NAMESPACE     NAME                                          READY   STATUS      RESTARTS   AGE
kube-system   pod/local-path-provisioner-84bb864455-jnxmj   1/1     Running     0          12h
kube-system   pod/helm-install-traefik-crd--1-j7svg         0/1     Completed   0          12h
kube-system   pod/helm-install-traefik--1-wxbts             0/1     Completed   2          12h
kube-system   pod/svclb-traefik-hh7pq                       2/2     Running     0          12h
kube-system   pod/metrics-server-ff9dbcb6c-jt8f7            1/1     Running     0          12h
kube-system   pod/coredns-96cc4f57d-gfdd2                   1/1     Running     0          12h
kube-system   pod/traefik-56c4b88c4b-s2mp2                  1/1     Running     0          12h
default       pod/resendebiz-67d7fdbb5f-8vkdt               1/1     Running     0          2m19s
default       pod/resendebiz-67d7fdbb5f-bj9bb               1/1     Running     0          2m19s

NAMESPACE     NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
default       service/kubernetes       ClusterIP      10.43.0.1       <none>          443/TCP                      12h
kube-system   service/kube-dns         ClusterIP      10.43.0.10      <none>          53/UDP,53/TCP,9153/TCP       12h
kube-system   service/metrics-server   ClusterIP      10.43.124.179   <none>          443/TCP                      12h
kube-system   service/traefik          LoadBalancer   10.43.91.227    192.168.1.252   80:32391/TCP,443:30399/TCP   12h
default       service/resendebiz       ClusterIP      10.43.85.199    <none>          80/TCP                       2m20s

NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          12h

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           12h
kube-system   deployment.apps/metrics-server           1/1     1            1           12h
kube-system   deployment.apps/coredns                  1/1     1            1           12h
kube-system   deployment.apps/traefik                  1/1     1            1           12h
resendebiz    deployment.apps/resendebiz               0/0     0            0           12h
default       deployment.apps/resendebiz               2/2     2            2           2m20s

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/local-path-provisioner-84bb864455   1         1         1       12h
kube-system   replicaset.apps/metrics-server-ff9dbcb6c            1         1         1       12h
kube-system   replicaset.apps/coredns-96cc4f57d                   1         1         1       12h
kube-system   replicaset.apps/traefik-56c4b88c4b                  1         1         1       12h
resendebiz    replicaset.apps/resendebiz-67d7fdbb5f               0         0         0       12h
default       replicaset.apps/resendebiz-67d7fdbb5f               2         2         2       2m20s

NAMESPACE     NAME                                 COMPLETIONS   DURATION   AGE
kube-system   job.batch/helm-install-traefik-crd   1/1           6m30s      12h
kube-system   job.batch/helm-install-traefik       1/1           7m38s      12h
```

has no external IP and if I attempt to connect to the IP, I get a 404

**Expected behavior:**
An external IP should have been added to the service/resendebiz

**Actual behavior:**
No IP is set

**Comment by ChristianCiach** [comment]
I don't know if that's the issue, but your selectors in your Service are wrong.

Instead of
```yaml
selector:
    app: traefiklabs
    task: resendebiz
```

you probably want
```yaml
selector:
    app: resendebiz
```
