### ISSUE TITLE
Traefik Installation not totally reloaded after a HelmChartConfig removal

### ISSUE THREAD

**Issue by davinkevin** [k3s-io/k3s#5534]
**Environmental Info:**
K3s Version: 
* k3s version v1.22.7+k3s1 (8432d7f2)
* go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
* Linux k3s 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

Cluster Configuration:
* 1 server, no agent, basic dev env.

**Describe the bug:**
This problem is about træfik + `HelmChartConfig` to change port. I discovered if I add a `HelmChartConfig` to change the port (see steps below for more details), everything is ok, `Service` with `type: LoadBalancer` is recreated and klipper-lb pod is restarted with the new configuration. 
But, if I remove this previous created `HelmChartConfig`, then nothing happen at klipper-lb level, so the wrong port is exposed and then, træfik is not reachable. 

**Steps To Reproduce:**

- Installed K3s: curl -sfL https://get.k3s.io | sh -s
- Check everything is ok, træfik is set on port `80` and `443`

```sh
$ kubectl get svc -n kube-system
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                      AGE
kube-dns         ClusterIP      10.43.0.10     <none>           53/UDP,53/TCP,9153/TCP       2m14s
metrics-server   ClusterIP      10.43.208.71   <none>           443/TCP                      2m13s
traefik          LoadBalancer   10.43.116.14   192.168.162.60   80:32159/TCP,443:30958/TCP   102s
```

- Apply the following YAML, named `change-port.yaml` and check the change is correctly applied to service:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        exposedPort: 1234
      websecure:
        exposedPort: 5555
```

```sh
$ kubectl apply -f change-port.yaml
helmchartconfig.helm.cattle.io/traefik created
$ kubectl get svc -n kube-system
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                         AGE
kube-dns         ClusterIP      10.43.0.10     <none>           53/UDP,53/TCP,9153/TCP          4m43s
metrics-server   ClusterIP      10.43.208.71   <none>           443/TCP                         4m42s
traefik          LoadBalancer   10.43.116.14   192.168.162.60   1234:32159/TCP,5555:30958/TCP   4m11s
```

- Then, I delete the previously created `HelmChartConfig/traefik` and I see old ports are still defined/used by the service (1234 & 5555 instead of 80 & 443):

```sh
kubectl delete helmchartconfig.helm.cattle.io/traefik -n kube-system
helmchartconfig.helm.cattle.io "traefik" deleted
root@k3s ~# kubectl get svc -n kube-system
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                         AGE
kube-dns         ClusterIP      10.43.0.10     <none>           53/UDP,53/TCP,9153/TCP          6m17s
metrics-server   ClusterIP      10.43.208.71   <none>           443/TCP                         6m16s
traefik          LoadBalancer   10.43.116.14   192.168.162.60   1234:32159/TCP,5555:30958/TCP   5m45s
```

**Expected behavior:**

I would expect the pod to be reset to its default value, like if the chart was applied again with this new configuration.

**Actual behavior:**

The `helmchartconfig.helm.cattle.io/traefik` deletion doesn't trigger anything, so no change at `service` of `type: loadbalancer`.

**Additional context / logs:**

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment]
Hmm, it should fire an update of the chart. We're watching for removal of HelmChartConfig resources here: https://github.com/k3s-io/helm-controller/blob/master/pkg/helm/controller.go#L127

Can you do a `kubectl describe HelmChart -n kube-system traefik` after deleting the HelmChartConfig resource, as well as checking the logs of the job pod that should be kicked off to update the chart configuration?

**Comment by davinkevin** [comment]
About the describe, I don't have anything relevant here:

```yaml
Name:         traefik
Namespace:    kube-system
Labels:       objectset.rio.cattle.io/hash=d54a3cde895c2fa53d0b51458a7ae1923737ef63
Annotations:  objectset.rio.cattle.io/applied:
                H4sIAAAAAAAA/4yRT2vcMBDFv4oZyM1rr+O4mxX0kKYLLYFS0j+nQBlLs2vVsmQ04w3p4u9e5IbSUrrtTcPM/N7TvBPgaD9TZBs8KOjIDYVGEUeFDeWxghx66w0oeENuuO0wCuQwkK...
              objectset.rio.cattle.io/id:
              objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
              objectset.rio.cattle.io/owner-name: traefik
              objectset.rio.cattle.io/owner-namespace: kube-system
API Version:  helm.cattle.io/v1
Kind:         HelmChart
Metadata:
  Creation Timestamp:  2022-05-05T09:51:09Z
  Finalizers:
    wrangler.cattle.io/helm-controller
  Generation:  2
  Managed Fields:
    API Version:  helm.cattle.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:objectset.rio.cattle.io/applied:
          f:objectset.rio.cattle.io/id:
          f:objectset.rio.cattle.io/owner-gvk:
          f:objectset.rio.cattle.io/owner-name:
          f:objectset.rio.cattle.io/owner-namespace:
        f:finalizers:
          .:
          v:"wrangler.cattle.io/helm-controller":
        f:labels:
          .:
          f:objectset.rio.cattle.io/hash:
      f:spec:
        .:
        f:chart:
        f:set:
          .:
          f:global.systemDefaultRegistry:
        f:valuesContent:
      f:status:
        .:
        f:jobName:
    Manager:         deploy@ip-172-31-42-3
    Operation:       Update
    Time:            2022-05-05T09:51:09Z
  Resource Version:  389
  UID:               a61ddc1d-002f-471b-9d5e-ff3bcab5ed10
Spec:
  Chart:  https://%{KUBERNETES_API}%/static/charts/traefik-10.19.300.tgz
  Set:
    global.systemDefaultRegistry:
  Values Content:                  rbac:
  enabled: true
ports:
  websecure:
    tls:
      enabled: true
podAnnotations:
  prometheus.io/port: "8082"
  prometheus.io/scrape: "true"
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
priorityClassName: "system-cluster-critical"
image:
  name: "rancher/mirrored-library-traefik"
  tag: "2.6.2"
tolerations:
- key: "CriticalAddonsOnly"
  operator: "Exists"
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"
- key: "node-role.kubernetes.io/master"
  operator: "Exists"
  effect: "NoSchedule"
Status:
  Job Name:  helm-install-traefik
Events:
  Type    Reason    Age                  From             Message
  ----    ------    ----                 ----             -------
  Normal  ApplyJob  33s (x25 over 109s)  helm-controller  Applying HelmChart using Job kube-system/helm-install-traefik
```

And I didn't see any job fired after this deletion neither.

FYI, the job list after the apply/deletion:

```
$ kub get jobs -o wide -A
NAMESPACE     NAME                       COMPLETIONS   DURATION   AGE     CONTAINERS   IMAGES                                      SELECTOR
kube-system   helm-install-traefik-crd   1/1           27s        7m34s   helm         rancher/klipper-helm:v0.7.1-build20220407   controller-uid=969b47a1-3ff4-43ad-a00f-181b7deecd90
kube-system   helm-install-traefik       1/1           5s         6m18s   helm         rancher/klipper-helm:v0.7.1-build20220407   controller-uid=9ed39234-2539-436c-9f59-a5ecc93d9a07
```

**Comment by brandond** [comment]
```
Events:
  Type    Reason    Age                  From             Message
  ----    ------    ----                 ----             -------
  Normal  ApplyJob  33s (x25 over 109s)  helm-controller  Applying HelmChart using Job kube-system/helm-install-traefik
```

OK, so it did update the job 33 seconds ago, presumably when you deleted the HelmChartConfig?

Can you look at the job **pod**, not the job itself. What's the describe output, and what do the logs show?

**Comment by davinkevin** [comment]
No, this `33s` is the moment I apply the `ChartConfig`, not when I deleted it. 

I've tried again, and the pod `helm-install-traefik--1-gvnn9` is only executed when I apply ChartConfig but not when I delete it.

Following your request, this is all the logs from the job **pod**, like previously said, terminated after the apply:

```log
CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
set +v -x
+ [[ '' != \t\r\u\e ]]
+ export HELM_HOST=127.0.0.1:44134
+ HELM_HOST=127.0.0.1:44134
+ helm_v2 init --skip-refresh --client-only --stable-repo-url https://charts.helm.sh/stable/
+ tiller --listen=127.0.0.1:44134 --storage=secret
[main] 2022/05/05 19:12:00 Starting Tiller v2.17.0 (tls=false)
[main] 2022/05/05 19:12:00 GRPC listening on 127.0.0.1:44134
[main] 2022/05/05 19:12:00 Probes listening on :44135
[main] 2022/05/05 19:12:00 Storage driver is Secret
[main] 2022/05/05 19:12:00 Max history per release is 0
Creating /home/klipper-helm/.helm
Creating /home/klipper-helm/.helm/repository
Creating /home/klipper-helm/.helm/repository/cache
Creating /home/klipper-helm/.helm/repository/local
Creating /home/klipper-helm/.helm/plugins
Creating /home/klipper-helm/.helm/starters
Creating /home/klipper-helm/.helm/cache/archive
Creating /home/klipper-helm/.helm/repository/repositories.yaml
Adding stable repo with URL: https://charts.helm.sh/stable/
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/klipper-helm/.helm.
Not installing Tiller due to 'client-only' flag having been set
++ timeout -s KILL 30 helm_v2 ls --all '^traefik$' --output json
++ jq -r '.Releases | length'
[storage] 2022/05/05 19:12:00 listing all releases with filter
+ V2_CHART_EXISTS=
+ [[ '' == \1 ]]
+ [[ '' == \v\2 ]]
+ [[ -n '' ]]
+ shopt -s nullglob
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/tmp/traefik.tgz
+ [[ ! -f /chart/traefik.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
chart path is a url, skipping repo update
+ echo 'chart path is a url, skipping repo update'
+ helm_v3 repo remove stable
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string global.systemDefaultRegistry=
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls --all -f ++ jq '^traefik$' -r --namespace kube-system '"\(.[0].app_version),\(.[0].status)"'--output
json
++ tr '[:upper:]' '[:lower:]'
+ LINE=2.6.0,deployed
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ 2.6.0 =~ ^(|null)$ ]]
+ [[ deployed =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]]
+ [[ deployed == \d\e\p\l\o\y\e\d ]]
+ echo 'Already installed traefik'
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
Already installed traefik
+ helm_v3 mapkubeapis traefik --namespace kube-system
2022/05/05 19:12:00 Release 'traefik' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2022/05/05 19:12:00 Get release 'traefik' latest version.
2022/05/05 19:12:00 Check release 'traefik' for deprecated or removed APIs...
2022/05/05 19:12:00 Finished checking release 'traefik' for deprecated or removed APIs.
2022/05/05 19:12:00 Release 'traefik' has no deprecated or removed APIs.
2022/05/05 19:12:00 Map of release 'traefik' deprecated or removed APIs to supported versions, completed successfully.
+ echo 'Upgrading traefik'
Upgrading traefik
+ shift 1
+ helm_v3 upgrade --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-10.14.100.tgz --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml
Release "traefik" has been upgraded. Happy Helming!
NAME: traefik
LAST DEPLOYED: Thu May  5 19:12:01 2022
NAMESPACE: kube-system
STATUS: deployed
REVISION: 8
TEST SUITE
```

**Comment by VestigeJ** [comment]
**Environment Details-**
 
*Node(s) CPU architecture, OS, and Version:*

Linux 5.4.0-117-generic x86_64 GNU/Linux-Ubuntu 20.04.4 LTS

 
*Cluster Configuration:*
```
"NAME   STATUS   ROLES                  AGE   VERSION
k3     Ready    control-plane,master   36m   v1.22.7+k3s1 
```
*$ cat config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: coolclouds
```

**Reproduced with k3s Version:**
VERSION=v1.22.7+k3s1 
**Steps To Reproduce:**
 
```
  $ VERSION=v1.22.7+k3s1
  $ set.figs
  $ sudo INSTALL_K3S_VERSION=$VERSION INSTALL_K3S_EXEC=server sh - ./install-k3s.sh 
  $ kgn (check cluster is Ready)
  $ vim testing.yaml (see below file contents)
  $ k apply -f testing.yaml 
  $ kg svc -A (check cluster config applied)
  $ k delete -f testing.yaml 
  $ w2 kg svc -A (watch to see the service doesn't change)
```
**Results:**
ubuntu@k3:~$ kg svc -A
```
NAMESPACE     NAME             TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
default       kubernetes       ClusterIP      10.43.0.1       <none>           443/TCP                      4m24s
kube-system   kube-dns         ClusterIP      10.43.0.10      <none>           53/UDP,53/TCP,9153/TCP       4m19s
kube-system   metrics-server   ClusterIP      10.43.252.214   <none>           443/TCP                      4m17s
kube-system   traefik          LoadBalancer   10.43.212.126   192.168.205.18   80:32025/TCP,443:31974/TCP   3m20s
```
ubuntu@k3:~$ kg svc -A
```
NAMESPACE     NAME             TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
default       kubernetes       ClusterIP      10.43.0.1       <none>        443/TCP                         8m59s
kube-system   kube-dns         ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP          8m54s
kube-system   metrics-server   ClusterIP      10.43.252.214   <none>        443/TCP                         8m52s
kube-system   traefik          LoadBalancer   10.43.212.126   <pending>     1234:32025/TCP,5555:31974/TCP   7m55s
```

**Validated with**
** k3s Version/Commit:**
 COMMIT= 2968a83bc046f43be62852b94d07c531de97c416
**Steps To Validate:**
 
- Installed k3s:
 
**Results:**

$ kubectl get svc -A                                                                                                                            
```
NAMESPACE     NAME             TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
default       kubernetes       ClusterIP      10.43.0.1       <none>           443/TCP                      10m
kube-system   kube-dns         ClusterIP      10.43.0.10      <none>           53/UDP,53/TCP,9153/TCP       10m
kube-system   metrics-server   ClusterIP      10.43.228.118   <none>           443/TCP                      10m
kube-system   traefik          LoadBalancer   10.43.63.185    192.168.205.18   80:30017/TCP,443:32222/TCP   4m54s
```
$ k apply -f testing.yaml
$ kubectl get svc -A
```
NAMESPACE     NAME             TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                         AGE
default       kubernetes       ClusterIP      10.43.0.1       <none>           443/TCP                         12m
kube-system   kube-dns         ClusterIP      10.43.0.10      <none>           53/UDP,53/TCP,9153/TCP          12m
kube-system   metrics-server   ClusterIP      10.43.228.118   <none>           443/TCP                         12m
kube-system   traefik          LoadBalancer   10.43.63.185    192.168.205.18   1234:30017/TCP,5555:32222/TCP   6m52s
```
 $ k delete -f testing.yaml
$ kg svc -A
```
NAMESPACE     NAME             TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
default       kubernetes       ClusterIP      10.43.0.1       <none>           443/TCP                      26m
kube-system   kube-dns         ClusterIP      10.43.0.10      <none>           53/UDP,53/TCP,9153/TCP       26m
kube-system   metrics-server   ClusterIP      10.43.228.118   <none>           443/TCP                      26m
kube-system   traefik          LoadBalancer   10.43.63.185    192.168.205.18   80:30017/TCP,443:32222/TCP   20m
```


**Additional context / logs:**
$ cat testing.yaml 
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        exposedPort: 1234
      websecure:
        exposedPort: 5555
```
