### ISSUE TITLE
[Release 1.22] Traefik Ingress should process IPv6 traffic

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/k3s#5536]
Backport: https://github.com/k3s-io/k3s/issues/1162

**Comment by VestigeJ** [comment]
**Validated with COMMIT=beaed3c5ed766241a44b4df19dee66329b117e33**

$ k3s -v
```
k3s version v1.22.9+k3s-beaed3c5 (beaed3c5)
go version go1.16.10
```

k3s config:
``` 
write-kubeconfig-mode: 644
debug: true
token: chunkysoupsarereallystews
cluster-cidr: 10.20.0.0/16,2022:aced:7::/56
service-cidr: 10.30.0.0/16,2022:aced:8::/112
cni: canal
node-ip: 192.168.10.114,2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998
disable-networkpolicy: true
node-external-ip: 154.17.19.15,2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998
```

$ kga -o wide
```
NAMESPACE     NAME                                          READY   STATUS      RESTARTS   AGE   IP          NODE                NOMINATED NODE   READINESS GATES
kube-system   pod/local-path-provisioner-84bb864455-w7ftw   1/1     Running     0          73m   10.20.0.5   ip-192-168-10-114   <none>           <none>
kube-system   pod/coredns-7796b77cd4-t6c5j                  1/1     Running     0          73m   10.20.0.3   ip-192-168-10-114   <none>           <none>
kube-system   pod/helm-install-traefik-crd--1-lhdzd         0/1     Completed   0          73m   10.20.0.6   ip-192-168-10-114   <none>           <none>
kube-system   pod/metrics-server-ff9dbcb6c-fclqt            1/1     Running     0          73m   10.20.0.2   ip-192-168-10-114   <none>           <none>
kube-system   pod/helm-install-traefik--1-v8vnk             0/1     Completed   1          73m   10.20.0.4   ip-192-168-10-114   <none>           <none>
kube-system   pod/svclb-traefik-jbt7d                       2/2     Running     0          72m   10.20.0.7   ip-192-168-10-114   <none>           <none>
kube-system   pod/traefik-d497b4cb6-fh8f4                   1/1     Running     0          72m   10.20.0.8   ip-192-168-10-114   <none>           <none>
whoami        pod/whoami-7d666f84d8-sgh9s                   1/1     Running     0          68m   10.20.0.9   ip-192-168-10-114   <none>           <none>

NAMESPACE     NAME                          TYPE           CLUSTER-IP          EXTERNAL-IP                                             PORT(S)                      AGE   SELECTOR
default       service/kubernetes            ClusterIP      10.30.0.1           <none>                                                  443/TCP                      73m   <none>
kube-system   service/kube-dns              ClusterIP      10.30.0.10          <none>                                                  53/UDP,53/TCP,9153/TCP       73m   k8s-app=kube-dns
kube-system   service/metrics-server        ClusterIP      10.30.172.65        <none>                                                  443/TCP                      73m   k8s-app=metrics-server
kube-system   service/traefik               LoadBalancer   10.30.199.125       2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998,154.17.19.15   80:30616/TCP,443:30488/TCP   72m   app.kubernetes.io/instance=traefik,app.kubernetes.io/name=traefik
whoami        service/whoami                ClusterIP      10.30.80.53         <none>                                                  80/TCP                       68m   app=traefiklabs,task=whoami
whoami        service/whoami-v6             ClusterIP      2022:aced:8::ccbd   <none>                                                  80/TCP                       68m   app=traefiklabs,name=whoami
whoami        service/whoami-require-dual   ClusterIP      10.30.80.136        <none>                                                  80/TCP                       68m   app=traefiklabs
whoami        service/whoami-prefer-dual    ClusterIP      10.30.156.173       <none>                                                  80/TCP                       68m   app=traefiklabs

NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE   CONTAINERS               IMAGES                                                SELECTOR
kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          72m   lb-port-80,lb-port-443   rancher/klipper-lb:v0.3.5,rancher/klipper-lb:v0.3.5   app=svclb-traefik

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS               IMAGES                                   SELECTOR
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           73m   local-path-provisioner   rancher/local-path-provisioner:v0.0.21   app=local-path-provisioner
kube-system   deployment.apps/coredns                  1/1     1            1           73m   coredns                  rancher/mirrored-coredns-coredns:1.9.1   k8s-app=kube-dns
kube-system   deployment.apps/metrics-server           1/1     1            1           73m   metrics-server           rancher/mirrored-metrics-server:v0.5.2   k8s-app=metrics-server
kube-system   deployment.apps/traefik                  1/1     1            1           72m   traefik                  rancher/mirrored-library-traefik:2.6.2   app.kubernetes.io/instance=traefik,app.kubernetes.io/name=traefik
whoami        deployment.apps/whoami                   1/1     1            1           68m   whoami                   traefik/whoami                           app=traefiklabs,task=whoami

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE   CONTAINERS               IMAGES                                   SELECTOR
kube-system   replicaset.apps/local-path-provisioner-84bb864455   1         1         1       73m   local-path-provisioner   rancher/local-path-provisioner:v0.0.21   app=local-path-provisioner,pod-template-hash=84bb864455
kube-system   replicaset.apps/coredns-7796b77cd4                  1         1         1       73m   coredns                  rancher/mirrored-coredns-coredns:1.9.1   k8s-app=kube-dns,pod-template-hash=7796b77cd4
kube-system   replicaset.apps/metrics-server-ff9dbcb6c            1         1         1       73m   metrics-server           rancher/mirrored-metrics-server:v0.5.2   k8s-app=metrics-server,pod-template-hash=ff9dbcb6c
kube-system   replicaset.apps/traefik-d497b4cb6                   1         1         1       72m   traefik                  rancher/mirrored-library-traefik:2.6.2   app.kubernetes.io/instance=traefik,app.kubernetes.io/name=traefik,pod-template-hash=d497b4cb6
whoami        replicaset.apps/whoami-7d666f84d8                   1         1         1       68m   whoami                   traefik/whoami                           app=traefiklabs,pod-template-hash=7d666f84d8,task=whoami

NAMESPACE     NAME                                 COMPLETIONS   DURATION   AGE   CONTAINERS   IMAGES                                      SELECTOR
kube-system   job.batch/helm-install-traefik-crd   1/1           40s        73m   helm         rancher/klipper-helm:v0.7.1-build20220407   controller-uid=6ac8ae27-45fe-41a6-a826-6e4f0d79cdc3
kube-system   job.batch/helm-install-traefik       1/1           45s        73m   helm         rancher/klipper-helm:v0.7.1-build20220407   controller-uid=19873503-334a-43d4-acaa-5f2a6f6378d3
```

$ cat whoami.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  name: whoami
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: traefiklabs
    name: whoami

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefiklabs
      task: whoami
  template:
    metadata:
      labels:
        app: traefiklabs
        task: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: traefiklabs
    task: whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-six
  namespace: whoami
spec:
  selector:
    app: traefiklabs
    task: whoami
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-require-dual
  namespace: whoami
spec:
  selector:
    app: traefiklabs
    task: whoami
  ipFamilyPolicy: RequireDualStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-prefer-dual
  namespace: whoami
spec:
  selector:
    app: traefiklabs
    task: whoami
  ipFamilyPolicy: PreferDualStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: whoami
  namespace: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - http:
        paths:
          - path: /qa
            pathType: Exact
            backend:
              service:
                name: whoami
                port:
                  number: 80
          - path: /test
            pathType: Exact
            backend:
              service:
                name: whoami
                port:
                  number: 80
          - path: /who-six
            pathType: Exact
            backend:
              service:
                name: whoami-six
                port:
                  number: 80
          - path: /require-dual
            pathType: Exact
            backend:
              service:
                name: whoami-require-dual
                port:
                  number: 80
          - path: /prefer-dual
            pathType: Exact
            backend:
              service:
                name: whoami-prefer-dual
                port:
                  number: 80
```

$ curl http://[2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]/who-six
```
Hostname: whoami-7d666f84d8-sgh9s
IP: 127.0.0.1
IP: ::1
IP: 10.20.0.9
IP: 2022:aced:7::9
IP: fe80::389c:8aff:fe5e:f97e
RemoteAddr: [2022:aced:7::8]:37246
GET /who-six HTTP/1.1
Host: [2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]
User-Agent: curl/7.68.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 2022:aced:7::1
X-Forwarded-Host: [2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-d497b4cb6-fh8f4
X-Real-Ip: 2022:aced:7::1
```

$ curl http://[2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]/qa
```
Hostname: whoami-7d666f84d8-sgh9s
IP: 127.0.0.1
IP: ::1
IP: 10.20.0.9
IP: 2022:aced:7::9
IP: fe80::389c:8aff:fe5e:f97e
RemoteAddr: 10.20.0.8:47752
GET /qa HTTP/1.1
Host: [2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]
User-Agent: curl/7.68.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 2022:aced:7::1
X-Forwarded-Host: [2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-d497b4cb6-fh8f4
X-Real-Ip: 2022:aced:7::1
```

$ curl http://[2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]/require-dual
```
Hostname: whoami-7d666f84d8-sgh9s
IP: 127.0.0.1
IP: ::1
IP: 10.20.0.9
IP: 2022:aced:7::9
IP: fe80::389c:8aff:fe5e:f97e
RemoteAddr: 10.20.0.8:47752
GET /require-dual HTTP/1.1
Host: [2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]
User-Agent: curl/7.68.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 2022:aced:7::1
X-Forwarded-Host: [2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-d497b4cb6-fh8f4
X-Real-Ip: 2022:aced:7::1
```

$ curl http://[2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]/prefer-dual
```
Hostname: whoami-7d666f84d8-sgh9s
IP: 127.0.0.1
IP: ::1
IP: 10.20.0.9
IP: 2022:aced:7::9
IP: fe80::389c:8aff:fe5e:f97e
RemoteAddr: 10.20.0.8:47752
GET /prefer-dual HTTP/1.1
Host: [2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]
User-Agent: curl/7.68.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 2022:aced:7::1
X-Forwarded-Host: [2600:1fec:abe:ee4e:2b5c:a0e0:cb5e:3998]
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-d497b4cb6-fh8f4
X-Real-Ip: 2022:aced:7::1
```
