### ISSUE TITLE
Create by default `traefik` `ingressClass` when creating a cluster.

### ISSUE THREAD

**Issue by dllegru** [k3s-io/k3s#5562]
**Is your feature request related to a problem? Please describe.**
- k3s uses by default `traefik` as an `Ingress Controller`
- It works fine using `kubernetes.io/ingress.class` annotation in the `Ingress`. This has been [deprecated](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) by Kubernetes.
- The way to use it now is to define a `ingressClassName` in the `Ingress` spec.
- There is no default `ingressClassName` created when creating a k3s cluster, thus the `traefik ingress` is not able to create the ingress requested when using `ingressClassName`
- FR is to create a default `traefik` `ingressClass` in order to be compliant with current Kubernetes standards.

**Describe the solution you'd like**
Just adding this resource to the cluster, `traefik` is able to operate, add this resource by default when creating a cluster.
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: traefik.io/ingress-controller
```

**Comment by brandond** [comment]
If you want to opt into this, you can get it from the chart by deploying the following chart config:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ingressClass:
      enabled: true
      isDefaultClass: true
```
Ref:
* https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig
* https://github.com/traefik/traefik-helm-chart/blob/v10.19.3/traefik/values.yaml#L70-L73
