### ISSUE TITLE
[Release-1.23] - Objects removed from a manifest file aren't removed from the cluster

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5599]
Backport fix for Objects removed from a manifest file aren't removed from the cluster

* #5559

**Comment by VestigeJ** [comment]
**Validated with COMMIT=f7dc7b95566a2a36ded376d52ca2734c44ca4824**

$ k3s -v
```
k3s version v1.23.6+k3s-f7dc7b95 (f7dc7b95)
go version go1.17.5
```

$ cat whowho.yaml && sudo cp /var/lib/rancher/k3s/server/manifests/
```
apiVersion: v1
kind: Namespace
metadata:
  name: second
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: second
  namespace: second
  labels:
    app: traefiklabs
    name: whoami

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefiklabs
      task: whoami
  template:
    metadata:
      labels:
        app: traefiklabs
        task: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: second
  namespace: second

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: traefiklabs
    task: whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-six
  namespace: second
spec:
  selector:
    app: traefiklabs
    task: whoami
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-require-dual
  namespace: second
spec:
  selector:
    app: traefiklabs
    task: whoami
  ipFamilyPolicy: RequireDualStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-prefer-dual
  namespace: second
spec:
  selector:
    app: traefiklabs
    task: whoami
  ipFamilyPolicy: PreferDualStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: whoami
  namespace: second
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - http:
        paths:
          - path: /qa
            pathType: Exact
            backend:
              service:
                name: whoami
                port:
                  number: 80
          - path: /test
            pathType: Exact
            backend:
              service:
                name: whoami
                port:
                  number: 80
          - path: /who-six
            pathType: Exact
            backend:
              service:
                name: whoami-six
                port:
                  number: 80
          - path: /require-dual
            pathType: Exact
            backend:
              service:
                name: whoami-require-dual
                port:
                  number: 80
          - path: /prefer-dual
            pathType: Exact
            backend:
              service:
                name: whoami-prefer-dual
                port:
                  number: 80
```

Confirm the yaml is deployed

$ kg all -n second -o wide
```
NAMESPACE     NAME                                          READY   STATUS              RESTARTS       AGE    IP                NODE              NOMINATED NODE   READINESS GATES
second        pod/second-f6d6584b-dqzsc                     0/1     ContainerCreating   0              1s     <none>            ip-192-168-0-71   <none>           <none>

NAMESPACE     NAME                         TYPE           CLUSTER-IP          EXTERNAL-IP                             PORT(S)                      AGE    SELECTOR
second        service/second               ClusterIP      2022:aced:8::b150   <none>                                  80/TCP                       1s     app=traefiklabs,task=whoami
second        service/whoami-prefer-dual   ClusterIP      2022:aced:8::3d23   <none>                                  80/TCP                       1s     app=traefiklabs,task=whoami
second        service/whoami-six           ClusterIP      2022:aced:8::b71d   <none>                                  80/TCP                       1s     app=traefiklabs,task=whoami

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS               IMAGES                                   SELECTOR
second        deployment.apps/second                   0/1     1            0           1s     whoami                   traefik/whoami                           app=traefiklabs,task=whoami

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE    CONTAINERS               IMAGES                                   SELECTOR
second        replicaset.apps/second-f6d6584b                     1         1         0       1s     whoami                   traefik/whoami                           app=traefiklabs,pod-template-hash=f6d6584b,task=whoami
```

edit and remove services from the whowho.yaml deployment
$ sudo vim /var/lib/rancher/k3s/server/manifests/whowho.yaml
cut out all but one service from the whowho.yaml deployment

$ kg all -n second
```
$ kg all -n second
NAME                        READY   STATUS    RESTARTS   AGE
pod/second-f6d6584b-dqzsc   1/1     Running   0          15m

NAME             TYPE        CLUSTER-IP          EXTERNAL-IP   PORT(S)   AGE
service/second   ClusterIP   2022:aced:8::b150   <none>        80/TCP    15m

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/second   1/1     1            1           15m

NAME                              DESIRED   CURRENT   READY   AGE
replicaset.apps/second-f6d6584b   1         1         1       15m
```

edit and removed the last service from the whowho.yaml
$ sudo vim /var/lib/rancher/k3s/server/manifests/whowho.yaml

$ kg all -n second
```
NAME                        READY   STATUS    RESTARTS   AGE
pod/second-f6d6584b-dqzsc   1/1     Running   0          18m

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/second   1/1     1            1           18m

NAME                              DESIRED   CURRENT   READY   AGE
replicaset.apps/second-f6d6584b   1         1         1       18m
```

before deleting the ingress from the whowho.yaml

$ kg ing -A
```
NAMESPACE   NAME     CLASS    HOSTS   ADDRESS                                 PORTS   AGE
second      whoami   <none>   *       2600:1f1c:ab4:eeee:cccc:6e1c:c7b:1cc7   80      15s
```

after deleting ingress from whowho.yaml
$ kg ing -A
```
No resources found
```
