### ISSUE TITLE
[Question] Using HelmChart template doesn't create namespace

### ISSUE THREAD

**Issue by dodalovic** [k3s-io/k3s#5623]
As documented [here](https://rancher.com/docs/k3s/latest/en/helm/#using-the-helm-crd), I tried to create something like this:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: caddy
  namespace: kube-system
spec:
  repo: https://charts.sagikazarmark.dev
  chart: skm/caddy
  targetNamespace: caddy
```

Such a file I put inside my app's `helm` directory, alongside other template files. 
My `helm upgrade` command failed, saying that 

`namespaces "caddy" not found`

Is this expected? Did I get it all wrong?

**Comment by dodalovic** [comment]
Yes, tried it, that failed as well.
Helm upgrade command has this flag --create-namespace though

**Comment by brandond** [comment]
Are you sure that your updated manifest is getting loaded? The change wouldn't be reflected unless the manifest was applied and the namespace created.

How did this **previously** work without the namespace present? Are you trying to change the namespace on an already installed chart?

**Comment by dodalovic** [comment]
Sorry, you're right. Now, with the templates being picked up, I can see some pods created, but not really the things I need:

![image](https://user-images.githubusercontent.com/6358061/171274597-7ac093f7-31b0-4243-80cb-c57fe6890755.png)

I'm not sure what are these pods actually, but they don't seem to be `caddy`, `postgres` etc, that I expect. 🤔

**Comment by dodalovic** [comment]
For some reason I see this in logs:

```shell
+ helm_v3 repo add postgresql https://charts.bitnami.com/bitnami
"postgresql" has been added to your repositories
```

I would expect helm_v3 repo add **bitnami** https://charts.bitnami.com/bitnami

**Comment by brandond** [comment]
I think you just want `chart: postgresql`. When you're using the helm CLI yourself, the format is <repo>/<chart>. In the Chart spec, you should just specify the chart, without the repo.

**Comment by dodalovic** [comment]
Sorry, I could not understand what you're saying. 
So, what would be the correct version of this one?

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgresql
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: bitnami/postgresql
  targetNamespace: postgresql
  set:
    auth.database: "invoicer"
    auth.username: {{ .Values.db.username }}
    auth.password: {{ .Values.db.password }}
    auth.postgresPassword: {{ .Values.db.postgresPassword }}
```
