### ISSUE TITLE
[release-1.23] embedded etcd should not accept connections from other nodes while resetting or restoring

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5695]
Backport to branch `release-1.23`:
* #5693

**Comment by rancher-max** [comment]
### Validated on v1.23.8-rc1+k3s1
 
## Environment Details

 
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux ip-172-31-4-149 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 
*Cluster Configuration:*

```
3 servers
1 agent
```
 
*Config.yaml:*

```
# server 1
cluster-init: true
token: faketoken
```

```
# servers 2 & 3 and agents
server: https://$SERVER1_IP:6443
token: faketoken
```
 
*Additional files*

```
# np.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app-node
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-app-node
    spec:
      containers:
      - name: nginx
        image: ranchertest/mytestcontainer:unprivileged
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app-node
  name: nginx-nodeport-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30096
      name: http
  selector:
    app: nginx-app-node
```
 
## Testing Steps

1. Install k3s on initial server
2. Join 2 servers and 1 agent to the cluster
3. On steps 4-8 below, use server1 only:
4. Deploy some workloads:
```
kubectl apply -f np.yaml
kubectl run nginx --image=nginx
```
5. Take an etcd snapshot: `sudo k3s etcd-snapshot save`
6. Deploy another workload that won't be present in the snapshot: `kubectl run other --image-nginx`
7. Stop k3s: `sudo systemctl stop k3s`
8. Restore the snapshot that was taken: `sudo k3s server --cluster-reset --cluster-reset-restore-path="/var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-172-31-15-79-1656003182"`
9. (run following on servers 2 and 3) Stop the k3s process on servers 2 and 3 and remove the DB dirs as directed by the end of the cluster-reset command:
```
sudo k3s-killall.sh
sudo rm -rf /var/lib/rancher/k3s/server/db/
```
10. (run following on agents) Stop the k3s process on agent 1: `sudo k3s-killall.sh`
11. (on server 1) Restart the k3s process: `sudo systemctl start k3s`
12. (on servers 2 and 3) Restart the k3s process: `sudo systemctl enable k3s --now`
13. (on agents) Restart the k3s process: `sudo systemctl enable k3s-agent --now`
14. Deploy another pod: `kubectl run new --image-nginx`
 
**Replication Results:**

- On step 8, during the cluster-reset, there are log spams as part of the command, regarding peer servers:
```
{"level":"warn","ts":"2022-06-23T16:41:47.835Z","caller":"rafthttp/http.go:500","msg":"request cluster ID mismatch","local-member-id":"671519b553971560","local-member-cluster-id":"5f30368fa48db9fa","local-member-server-version":"3.5.4","local-member-server-minimum-cluster-version":"3.0.0","remote-peer-server-name":"3d2dee1321d5e6f0","remote-peer-server-version":"3.5.4","remote-peer-server-minimum-cluster-version":"3.0.0","remote-peer-cluster-id":"62b3d4bbaa56fa51"}
```
- Looking at the k3s logs (`journalctl -u k3s -f`) of another server while the initial server is performing the cluster-reset (step 8) also has log spam regarding peer servers:
```
Jun 23 16:41:46 ip-172-31-8-210 k3s[2516]: {"level":"warn","ts":"2022-06-23T16:41:46.534Z","caller":"rafthttp/stream.go:653","msg":"request sent was ignored by remote peer due to cluster ID mismatch","remote-peer-id":"5ebd5d526f809f60","remote-peer-cluster-id":"5f30368fa48db9fa","local-member-id":"50e74fcc8eb00d91","local-member-cluster-id":"62b3d4bbaa56fa51","error":"cluster ID mismatch"}
```
- After performing all of the steps through step 13, all of the nodes are back in Ready state, all back joined into the cluster, and the data from `np.yaml` and the `nginx` pod is running (but not the `other` pod).
- After performing step 14, the `new` pod shows up as running (along with everything else) when using `kubectl get pod` from any of the three server nodes
 
 
**Validation Results:**

The below two observations are indication that the issue is resolved:
- On step 8, during the cluster-reset, there are NO LONGER log spams as part of the command
- Looking at the k3s logs of another server while the initial server is performing the cluster-reset (step 8) NO LONGER has log spam regarding peer servers

These below two observations are indications that cluster-reset continues to function properly when finishing the full flow:
- After performing all of the steps through step 13, all of the nodes are back in Ready state, all back joined into the cluster, and the data from `np.yaml` and the `nginx` pod is running (but not the `other` pod).
- After performing step 14, the `new` pod shows up as running (along with everything else) when using `kubectl get pod` from any of the three server nodes
