### ISSUE TITLE
[release-1.22] embedded etcd should not accept connections from other nodes while resetting or restoring

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5696]
Backport to branch `release-1.22`:
* #5693

**Comment by VestigeJ** [comment]
##Environment Details
 
*Infrastructure*
- [x] Cloud
- [ ] Hosted 

*Node(s) CPU architecture, OS, and Version:*

Linux 5.4.0-1009-aws x86_64 GNU/Linux-Ubuntu 20.04 LTS

**Validated with VERSION=v1.22.11-rc1+k3s1**
 
*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE   VERSION
ip-1-1-1-2   Ready    control-plane,etcd,master   17m   v1.22.11-rc1+k3s1
ip-1-1-1-7   Ready    <none>                      17m   v1.22.11-rc1+k3s1
ip-1-1-1-22   Ready    control-plane,etcd,master   17m   v1.22.11-rc1+k3s1
ip-1-1-1-13   Ready    control-plane,etcd,master   18m   v1.22.11-rc1+k3s1 
```
*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: coolclouds
cluster-init: true
```
## Replication Steps
 
```
$  VERSION=v1.22.11-rc1+k3s1
$  sudo INSTALL_K3S_VERSION=$VERSION INSTALL_K3S_EXEC=server sh - ./install-k3s.sh 
$  echo $VERSION
$  kgn
$  vim wasm.yaml
$  k apply -f wasm.yaml 
$  vim np.yaml
$  k apply -f np.yaml 
$  k run nginx --image=nginx
$  kga -o wide
$  sudo k3s etcd-snapshot
$  vim who.yaml
$  k apply -f who.yaml 
$  kga -o wide
$  sudo systemctl stop k3s
$  sudo k3s server --cluster-reset --cluster-reset-restore-path="/var/lib/rancher/k3s/server/db/snapshots/on-demand-ip-1-1-1-13-1656085542"
$  sudo systemctl start k3s
$  kgn
```

```
(on nodes 2/3)
$ sudo k3s-killall.sh
$ sudo rm -rf /var/lib/rancher/k3s/server/db/
$ sudo journalctl -u k3s | grep -e "request cluster ID mismatch" (hunting for this particular log spam)
$ sudo systemctl start k3s
```
 
**Results:**
Note that due to the nature of this the validation is a lack of data being present in the logs. 
Confirmed that the requests from other nodes during a cluster-reset-restore are greatly minimized before previous behavior. 


 
**Additional context / logs:**
$ cat np.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app-node
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-app-node
    spec:
      containers:
      - name: nginx
        image: ranchertest/mytestcontainer:unprivileged
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app-node
  name: nginx-nodeport-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30096
      name: http
  selector:
    app: nginx-app-node
```

$ cat wasm.yaml

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
---
# Source: wasmcloud-host/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: washboard
      protocol: TCP
      name: washboard
    - port: 8080
      targetPort: client
      name: client
  selector:
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
---
# Source: wasmcloud-host/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasmcloud-host
      app.kubernetes.io/instance: wasmcloud-host-1644521927
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wasmcloud-host
        app.kubernetes.io/instance: wasmcloud-host-1644521927
    spec:
      serviceAccountName: wasmcloud-host-1644521927
      securityContext:
        {}
      containers:
        - name: wasmcloud-host
          securityContext:
            {}
          image: "wasmcloud/wasmcloud_host:0.51.4"
          imagePullPolicy: IfNotPresent
          env: 
            - name: WASMCLOUD_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_PROV_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_PROV_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_CTL_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_CTL_PORT
              value: "4222"
            - name: HOST_kubernetes
              value: "true"
            - name: DASHBOARD_HOST
              value: "3.143.108.83" #change for each depoloyment to public ip
          ports:
            - name: washboard
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/livez
              port: washboard
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: washboard
          resources:
            {}
        - name: nats
          securityContext:
            {}
          image: "nats:2.6-alpine"
          imagePullPolicy: IfNotPresent
          args:
            - "-js"
          ports:
            - name: client
              containerPort: 4222
            - name: clustering
              containerPort: 6222
            - name: management
              containerPort: 8222
          resources:
            {}
```

$ cat who.yaml ( this was applied after the snapshot was taken and it has known features that will not deploy correctly )

```
apiVersion: v1
kind: Namespace
metadata:
  name: whoami
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: traefiklabs
    name: whoami

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefiklabs
      task: whoami
  template:
    metadata:
      labels:
        app: traefiklabs
        task: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami

spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    app: traefiklabs
    task: whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-six
  namespace: whoami
spec:
  type: LoadBalancer
  selector:
    app: traefiklabs
    task: whoami
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-require-dual
  namespace: whoami
spec:
  type: LoadBalancer
  selector:
    app: traefiklabs
    task: whoami
  ipFamilyPolicy: RequireDualStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-prefer-dual
  namespace: whoami
spec:
  type: LoadBalancer
  selector:
    app: traefiklabs
    task: whoami
  ipFamilyPolicy: PreferDualStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: whoami
  namespace: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - http:
        paths:
          - path: /qa
            pathType: Exact
            backend:
              service:
                name: whoami
                port:
                  number: 80
          - path: /test
            pathType: Exact
            backend:
              service:
                name: whoami
                port:
                  number: 80
          - path: /who-six
            pathType: Exact
            backend:
              service:
                name: whoami-six
                port:
                  number: 80
          - path: /require-dual
            pathType: Exact
            backend:
              service:
                name: whoami-require-dual
                port:
                  number: 80
          - path: /prefer-dual
            pathType: Exact
            backend:
              service:
                name: whoami-prefer-dual
                port:
                  number: 80
```
