### ISSUE TITLE
Missing image labels from cadvisor metrics with 1.24

### ISSUE THREAD

**Issue by spasche** [k3s-io/k3s#5782]
**Environmental Info:**
K3s Version: 

k3s version v1.24.2+k3s1 (b0ed1348)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 

Linux k3s 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Single node cluster on Ubuntu 22.04

**Describe the bug:**

After updating from 1.23 to 1.24, I noticed issues on Grafana dashboards.
It looks like this is due to missing `image` labels on cadvisor metrics (example Prometheus rule which expects a non-empty image label: https://github.com/prometheus-community/helm-charts/blob/e2af4613e9c79f3f663c697c2e33b711a676b142/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml#L29)

**Steps To Reproduce:**

- Install K3s from latest channel: `curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -`
- Retrieve cadvisor metrics with non-empty `image` labels:
  ```
  NODE=$(kubectl get no -ojsonpath='{..name}')
  kubectl get --raw /api/v1/nodes/$NODE/proxy/metrics/cadvisor|grep 'image="[^"]'
  ```

**Expected behavior:**

Command above should return a list of metrics with non-empty `image` labels.
Example on working cluster:
```
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod0bddcbd9_2699_4ea9_bce1_dee3414ec787.slice/cri-containerd-ce34008849af6e09b13cb3bbf16193ea27ff4c7c34a11999b98a73f145ce6053.scope",image="k8s.gcr.io/pause:3.6",name="ce34008849af6e09b13cb3bbf16193ea27ff4c7c34a11999b98a73f145ce6053",namespace="kube-system",pod="kube-proxy-qm8sc"} 0.018418 1656522816116
```

**Actual behavior:**

No metrics are returned with non-empty `image` labels.

**Additional context / logs:**

- Tried on Ubuntu 20.04: also broken
- Tried settings `SystemdCgroup = true` in containerd configuration: also broken

**Backporting**

- [ ] Needs backporting to older releases

**Comment by spasche** [comment]
I searched for a bit but couldn't find something related yet.
I also tried with kind 1.24.2 and microk8s 1.24 on Ubuntu 22.04 and with both the image labels are present.
So for now I only see the issue on k3s.

**Comment by brandond** [comment]
it may be related to the containerd version then. I'm not sure what version either of them are using.

**Comment by spasche** [comment]
That's good clue. Microk8s has an older containerd, but kind is using the exact same version.
```
# microk8s
microk8s ctr version
Client:
  Version:  v1.5.11
  Revision: 3df54a852345ae127d1fa3092b95168e4a88e2f8
  Go version: go1.17.9

Server:
  Version:  v1.5.11
  Revision: 3df54a852345ae127d1fa3092b95168e4a88e2f8
  UUID: a354254d-f037-467c-bb7f-7e9dfdda4ace

# kind
docker exec -it kind-control-plane ctr version
Client:
  Version:  v1.6.6
  Revision: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
  Go version: go1.17.11

Server:
  Version:  v1.6.6
  Revision: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
  UUID: b9d7368d-e4b9-4f49-8ec8-8ba43c72a5e4

# k3s
ctr version
Client:
  Version:  v1.6.6-k3s1
  Revision:
  Go version: go1.18.1

Server:
  Version:  v1.6.6-k3s1
  Revision:
  UUID: d70c6a83-4b64-4f0e-813b-5ae7696ce439
```

**Comment by brandond** [comment]
hmm, that is interesting. This may take a bit more investigation to nail down.

**Comment by brandond** [comment]
Confirmed that k3s 1.24.2-k3s1 with contiainerd `1.5.13-k3s1` does not set the image label either. I suspect it's something on the kubelet/cadvisor side, but these things are notoriously hard to track down.

**Comment by bkupidura** [comment]
Hey, looks like `image` is not only one label missing. Also `container` label is not set
```
container_memory_working_set_bytes{container="",id="/kubepods/pod65322060-244e-4066-a47d-a758470180e0",image="",name="",namespace="metallb-system",pod="metallb-speaker-hscf2"} 2.0750336e+07 1657055281236
container_memory_working_set_bytes{container="",id="/kubepods/pod65322060-244e-4066-a47d-a758470180e0/d295499b1772402abaaefd1caf40802f48a9327d65e4501204dfa0b1be2b7b22",image="",name="",namespace="",pod=""} 741376 1657055291214
container_memory_working_set_bytes{container="",id="/kubepods/pod65322060-244e-4066-a47d-a758470180e0/f0ae08f6752f47a53f4c6ae31c1e047c6ad95ee8063dbad1887f292aa6c147b7",image="",name="",namespace="",pod=""} 2.0205568e+07 1657055296724
```

**Comment by brandond** [comment]
Yeah, I'm still researching. I think it's something with how we're configuring the cgroup root. Vanilla containerd 1.6.6 works fine if I point k3s at it as the --container-runtime-endpoint, while using the exact same configuration as k3s generates for our packaged containerd. If I copy that same containerd binary into `/var/lib/rancher/k3s/data/current/bin/` the stats do not work... which leaves me assuming the difference is some of the cgroup arguments that we pass to the kubelet when we manage the runtime endpoint.

**Comment by brandond** [comment]
The above-linked issue should resolve this. In the mean time, you can add the following flag to k3s: `--kubelet-arg=containerd=/run/k3s/containerd/containerd.sock`

**Comment by est-suse** [comment]
*Infrastructure*
- [ ] Cloud
- [X] Hosted

*Node(s) CPU architecture, OS, and Version:*

Linux ip-172-31-32-188 5.13.0-1029-aws #32~20.04.1-Ubuntu SMP Thu Jun 9 13:03:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

*Cluster Configuration:*
1 server

*Config.yaml:*

write-kubeconfig-mode: 644
token: test


## Testing Steps

Install K3s from latest channel: curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -
Retrieve cadvisor metrics with non-empty image labels:
NODE=$(kubectl get no -o jsonpath='{..name}')
kubectl get --raw /api/v1/nodes/$NODE/proxy/metrics/cadvisor|grep 'image="[^"]'


**Replication Results:**
After the running the commands above, no results are displayed.

![image](https://user-images.githubusercontent.com/106194120/179295298-1494b058-7c8d-4457-9cf5-b5f6fafc3949.png)


**Validation Results:**
- k3s version used for validation:
Validated with RC 1.24.3-rc1+k3s1

Steps to test:

NODE=$(kubectl get no -o jsonpath='{..name}')
kubectl get --raw /api/v1/nodes/$NODE/proxy/metrics/cadvisor|grep 'image="[^"]'

After running the commands above the following output is displayed"

![image](https://user-images.githubusercontent.com/106194120/179295503-d0bbbf86-54af-4b78-97be-0a403950fe4c.png)


**Additional context / logs:**
```
```

**Comment by huapox** [comment]
Help Please, my situation: Kind mode with containerd v1.6.15, with `--container-runtime-endpoint /run/containerd/containerd.sock `, but still got none image matched

```bash
[root@node194 k3s]# dcp exec server bash
root@node194:/srv/local/k3s# ctr version
Client:
  Version:  v1.6.15
  Revision: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
  Go version: go1.18.9

Server:
  Version:  v1.6.15
  Revision: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
  UUID: 6a44b764-8a56-4a24-bcea-1442a8528963


[root@(?.|default:kubesphere-system) ~]NODE=$(kubectl get no -ojsonpath='{..name}' |awk '{print $1}')
[root@(?.|default:kubesphere-system) ~]$ echo $NODE 
172.25.23.194
[root@(?.|default:kubesphere-system) ~]kubectl get --raw /api/v1/nodes/$NODE/proxy/metrics/cadvisor|grep 'image="[^"]'
```

**Comment by huapox** [comment]
- there be values! (after drop `--kubelet-arg containerd=/run/containerd/containerd.sock`)

```bash
[root@(?.|default:kubesphere-system) ~]$ kubectl get --raw /api/v1/nodes/172.25.23.194/proxy/metrics/cadvisor |grep container_cpu_load_averag10s
...
container_cpu_load_average_10s{container="coredns",id="/k8s.io/cd7d7ae303e9d470c8987de7568f2986f03b367a2a3a7e0cb3bf9927737f443c",image="server.k8s.local:18443/infrasync/coredns-coredns:1.8.0",name="cd7d7ae303e9d470c8987de7568f2986f03b367a2a3a7e0cb3bf9927737f443c",namespace="kube-system",pod="coredns-858ddbb876-2dhsk"} 0 1679719566851
container_cpu_load_average_10s{container="install-cni",id="/k8s.io/2252e77a3fb5fbc5ff7d80d57ea16f467aada5fecd19b71a0855d5603d164d4a",image="docker.io/istio/install-cni:1.11.1",name="2252e77a3fb5fbc5ff7d80d57ea16f467aada5fecd19b71a0855d5603d164d4a",namespace="istio-system",pod="istio-cni-node-tskf4"} 0 1679719565885
container_cpu_load_average_10s{container="minio",id="/k8s.io/64548b73e4e0e0d0767239d3666460ae901f45e38ad06e7eba74195866b50ebf",image="docker.io/minio/minio:RELEASE.2019-08-07T01-59-21Z",name="64548b73e4e0e0d0767239d3666460ae901f45e38ad06e7eba74195866b50ebf",namespace="kubesphere-system",pod="minio-7879c5dd65-rpxsr"} 0 1679719565189
```

- the former

```bash
# [root@(?.|default:kubesphere-system) ~]$ kubectl get --raw /api/v1/nodes/172.25.23.194/proxy/metrics/cadvisor |grep container_cpu_load_averag10s
container_cpu_load_average_10s{container="",id="/k8s.io/ffdfa16db13df74900a9f7e58eefc9dd5044ee45fb5884bfb97a11a3bc3455ea",image="",name="",namespace="",pod=""} 0 1679713874582
container_cpu_load_average_10s{container="",id="/k8s.io/ffed61034733ffd9e497d12d7b6d0c7e49a574774fc75f6216a436567a5ac843",image="",name="",namespace="",pod=""} 0 1679713875254
container_cpu_load_average_10s{container="",id="/system.slice/zookeeper-cluster.service",image="",name="",namespace="",pod=""} 0 1679710387257
container_cpu_load_average_10s{container="",id="/user.slice",image="",name="",namespace="",pod=""} 0 1679710398000
```

**Comment by huapox** [comment]
- it works after my attch conf to ctd's config.toml

```toml
#ref k3s's inner ctd's config:
[plugins."io.containerd.grpc.v1.cri"]
  ...
  # ++
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
	SystemdCgroup = false
```

- full Kind containerd's config:

```toml
# copy: fk-edgecore-indocker
# explicitly use v2 config format
version = 2
root = "/var/lib/containerd"

[plugins."io.containerd.grpc.v1.cri".containerd]
  # save disk space when using a single snapshotter
  discard_unpacked_layers = true
  # explicitly use default snapshotter so we can sed it in entrypoint
  snapshotter = "native"
  # explicit default here, as we're configuring it below
  default_runtime_name = "runc"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  # set default runtime handler to v2, which has a per-pod shim
  runtime_type = "io.containerd.runc.v2"
  # Generated by "ctr oci spec" and modified at base container to mount poduct_uuid
  base_runtime_spec = "/etc/containerd/cri-base.json"

# Setup a runtime with the magic name ("test-handler") used for Kubernetes
# runtime class tests ...
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler]
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri"]
  # use fixed sandbox image
  sandbox_image = "registry.cn-shenzhen.aliyuncs.com/infrasync/rancher-pause:3.2"
  # allow hugepages controller to be missing
  # see https://github.com/containerd/cri/pull/1501
  tolerate_missing_hugepages_controller = true
  # restrict_oom_score_adj needs to be true when running inside UserNS (rootless)
  restrict_oom_score_adj = false

  # ++
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  


# https://huaweicloud.csdn.net/63311a7dd3efff3090b521fa.html
#配置ca文件路径和用户名密码
[plugins."io.containerd.grpc.v1.cri".registry.configs]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."server.k8s.local:18443".tls]
    ca_file = "/etc/docker/certs.d/server.k8s.local:18443/cert.crt"
  [plugins."io.containerd.grpc.v1.cri".registry.configs."server.k8s.local:18443".auth]
    username = "admin"
    password = "xxxxxx"



# [plugins.cri.containerd.runtimes.runc.options]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
	SystemdCgroup = false
```
