### ISSUE TITLE
[release-1.22] Observed a panic: "invalid memory address or nil pointer dereference" repeated in syslog

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5803]
Backport to branch `release-1.23`:
* #5762

**Comment by rancher-max** [comment]
### Validated on v1.22.11-rc1+k3s2
 
## Environment Details

 
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

Ubuntu 22.04 LTS
 
*Cluster Configuration:*

1 server
 
*Config.yaml:*

N/A
 
*Additional files*

```
# test.yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  type: ExternalName
  externalName: test.example.com
```
 
## Testing Steps

1. Install k3s using a previous version: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.10+k3s1 sh -`
2. Upgrade to newer version: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.11-rc1+k3s2 sh -`
3. Apply test.yaml: `kubectl apply -f test.yaml`
 
 
**Replication Results:**
- I was not able to see the panic when upgrading to v1.22.x, but I was able to see it when upgrading to v1.24.x. 

 
 
**Validation Results:**
- Continued to not be able to see the panic when upgrading to v1.22.11-rc1+k3s2
