### ISSUE TITLE
getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by wang-xiaowu** [k3s-io/k3s#5897]
**Environmental Info:**
K3s Version: v1.21.7+k3s1

Node(s) CPU architecture, OS, and Version:  Linux k3s-prod-master1 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 servers, 3 agents

**Describe the bug:**

```
getaddrinfo EAI_AGAIN
```

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

i use jmeter to do the pressure test
the nodejs's httpclient is axios
cni is flannel
and kube-proxy use iptables
this is my dockerfile
```Dockerfile
FROM node:12.22.0-alpine3.12 as build
WORKDIR /user/src/app
RUN set -eux \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk add --no-cache curl gcc g++ make linux-headers python2 python3 python3-dev git \
    && npm install -g pm2
COPY package.json package-lock.json ./
RUN npm install
FROM node:12.22.0-alpine3.12 as runtime
WORKDIR /user/src/app
RUN set -eux \
    && apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  \
    && apk del tzdata
COPY --from=build /user/src/app/node_modules ./node_modules/
COPY --from=build /usr/local/lib/node_modules/pm2 /usr/local/lib/node_modules/pm2/
RUN ln -s /usr/local/lib/node_modules/pm2/bin/pm2-runtime /usr/local/bin/pm2-runtime \
    && ln -s /usr/local/lib/node_modules/pm2/bin/pm2-docker /usr/local/bin/pm2-docker \
    && ln -s /usr/local/lib/node_modules/pm2/bin/pm2-dev /usr/local/bin/pm2-dev \
    && ln -s /usr/local/lib/node_modules/pm2/bin/pm2 /usr/local/bin/pm2 \
    && chmod +x /usr/local/bin/pm2*
COPY . .
CMD [ "pm2-runtime", "start", "pm2.json" ]
```
this is my devployment.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  selector:
    app: xxx
  type: ClusterIP
  ports:
    - port: 34017
      protocol: TCP
      targetPort: 34017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
  labels:
    app: xxx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xxx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
        - image: $REGISTRY_ADDRESS/${NODE_ENV}/${CI_PROJECT_NAME}:v${CI_PIPELINE_ID}
          envFrom:
            - configMapRef:
                name: xxx-configmap
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 34017
          readinessProbe:
            tcpSocket:
              port: 34017
          name: xxx
          ports:
            - containerPort: 34017
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/xxx
              name: xxx-log
      volumes:
        - name: xxx-log
          persistentVolumeClaim:
            claimName: xxx-log
            readOnly: false
      imagePullSecrets:
        - name: nexus3secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
```
test data like
![image](https://user-images.githubusercontent.com/44340137/180400434-3b61a884-41e5-4fd7-87ce-51707e51357e.png)

**Backporting**

- [ ] Needs backporting to older releases
