### ISSUE TITLE
Cant setup Dependency Proxy from gitlab

### ISSUE THREAD

**Issue by gawsoftpl** [k3s-io/k3s#5899]
I can't setup k3s to download container via gitlab dependency proxy.
https://docs.gitlab.com/ee/user/packages/dependency_proxy/

```yml
    configs:
      registry.example.com:
        auth:
          username: token
          password: greg34g34g545g54
    mirrors:
      docker.io:
        endpoint:
          - "https://registry.example.com"
        rewrite:
          "^(.*)": "company/dependency_proxy/containers/$1"
```

I received logs:
```
E0724 01:19:30.513755      60 kuberuntime_manager.go:815] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = fail │
│ ed to get sandbox image \"rancher/mirrored-pause:3.6\": failed to pull image \"rancher/mirrored-pause:3.6\": failed to pull and unpack │
│  image \"docker.io/rancher/mirrored-pause:3.6\": failed to resolve reference \"docker.io/rancher/mirrored-pause:3.6\": pull access den │
│ ied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" pod="kube-syste │
│ m/local-path-provisioner-7b7dc8d6f5-5g27d"                                                                                             │
│ E0724 01:19:30.513937      60 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"local-path-p │
│ rovisioner-7b7dc8d6f5-5g27d_kube-system(b5421ea0-48a1-4906-907b-83a847f282b1)\" with CreatePodSandboxError: \"Failed to create sandbox │
│  for pod \\\"local-path-provisioner-7b7dc8d6f5-5g27d_kube-system(b5421ea0-48a1-4906-907b-83a847f282b1)\\\": rpc error: code = Unknown  │
│ desc = failed to get sandbox image \\\"rancher/mirrored-pause:3.6\\\": failed to pull image \\\"rancher/mirrored-pause:3.6\\\": failed │
│  to pull and unpack image \\\"docker.io/rancher/mirrored-pause:3.6\\\": failed to resolve reference \\\"docker.io/rancher/mirrored-pau │
│ se:3.6\\\": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorizat │
│ ion failed\"" pod="kube-system/local-path-provisioner-7b7dc8d6f5-5g27d" podUID=b5421ea0-48a1-4906-907b-83a847f282b1  
```
