### ISSUE TITLE
Docker compose with docker as container runtime

### ISSUE THREAD

**Issue by max201920** [k3s-io/k3s#592]
I am trying to run docker compose file with container runtime as docker.  Aim is to  better package application with k3s

Docker compose file is as follows

```
version: '3'
services:
  server:
    image: rancher/k3s:v0.6.1
    command: server --disable-agent --docker
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - /:/rootfs
    - /var/run:/var/run:rw
    - /sys:/sys
    - /var/lib/docker/:/var/lib/docker
    - /run:/run
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  node:
    image: rancher/k3s:v0.6.1
    command: agent  --docker
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker

    privileged: true
    depends_on:
    - server
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
    #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c
```

Following is error received.

```
node_2    | I0630 19:09:13.320886       1 docker_service.go:271] Setting cgroupDriver to cgroupfs
node_2    | F0630 19:09:13.321006       1 server.go:263] failed to run Kubelet: failed to create kubelet: failed to listen on "unix:///var/run/dockershim.sock": failed to unlink socket file "/var/run/dockershim.sock": read-only file system
server_1  | time="2019-06-30T19:09:13.335102714Z" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"
k3s_node_1 exited with code 255
k3s_node_2 exited with code 255
```

Is it possible to execute k3s such with such configuration?
