### ISSUE TITLE
No exponential backoff delay between job pods

### ISSUE THREAD

**Issue by ariep** [k3s-io/k3s#5945]
**Environmental Info:**
K3s Version: 
k3s version v1.23.3+k3s1 (5fb370e5)
go version go1.17.5

Node(s) CPU architecture, OS, and Version:
Linux stackspin-arie 5.10.104 #3 SMP Tue May 31 05:39:41 UTC 2022 x86_64 GNU/Linux

Cluster Configuration:
single node

**Describe the bug:**
When a Job's pod fails, Kubernetes prescribes an exponential backoff delay before the next pod for the job is created (5 seconds, 10 seconds, 20 seconds, etc.). Indeed that happens on a non-k3s cluster (I tried with a mostly default kubespray install). However, with k3s no delay is observed at all, and pods are created in rapid succession until the backofflimit is reached.

**Steps To Reproduce:**
- Installed K3s: installed via an ansible playbook as a part of [stackspin](https://open.greenhost.net/stackspin/stackspin). I don't have the full expanded installation command ready, though it can be reproduced on request.
- Submit the following Job to the cluster:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: delay-test
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: test
        image: busybox
        command:
        - /bin/cat
        - /nope
      restartPolicy: Never
```

**Expected behavior:**
After each failing pod, a delay is observed before the next pod for this job is created, and that delay increases (doubles) at every try.

**Actual behavior:**
After each failing pod, no significant delay is observed and the next pod is created immediately.

**Backporting**

- [ ] Needs backporting to older releases
