### ISSUE TITLE
not create tokens & secret with create service-account 

### ISSUE THREAD

**Issue by vast0906** [k3s-io/k3s#6021]
k3s not create secret and token with create service-account.

gitlab-admin-service-account.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitlab
    namespace: kube-system
```
```
 # kubectl apply -f gitlab-admin-service-account.yaml
serviceaccount/gitlab created
clusterrolebinding.rbac.authorization.k8s.io/gitlab-admin created

# kubectl -n kube-system get secret
NAME                                      TYPE                 DATA   AGE
k3s-serving                               kubernetes.io/tls    2      47m
xxxxxde.node-password.k3s   Opaque               1      47m
sh.helm.release.v1.traefik-crd.v1         helm.sh/release.v1   1      46m
sh.helm.release.v1.traefik.v1             helm.sh/release.v1   1      46m
# kubectl -n kube-system describe sa gitlab
Name:                gitlab
Namespace:           kube-system
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
# k3s -version
k3s version v1.24.3+k3s1 (990ba0e8)
go version go1.18.1
```
