### ISSUE TITLE
Multiple external ips are ignored

### ISSUE THREAD

**Issue by Northcode** [k3s-io/k3s#6032]
**Environmental Info:**
K3s Version: 
v1.24.3+k3s1

Node(s) CPU architecture, OS, and Version: 
```
5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
```

Cluster Configuration:
1 master `node A`
1 agent `node B`
different networks connected via manual wireguard, flannel with vxlan over the wireguard channel

**Describe the bug:**
Specifying multiple external ips in `--node-external-ip` only uses the first one.
This is needed because I would like LoadBalancer services to have both the external interface ip for accessing it from the cluster externally, as well as the wireguard-ip to be able to access it from inside the vpn network.

If there is any way to work around this for LoadBalancer services I'd accept it as a workaround.

**Steps To Reproduce:**
- Installed K3s
- Set `--node-external-ip` on node A to `'1.2.3.4,10.0.0.1'` (where 1.2.3.4 would be the external interface, and 10.0.0.1 would be the vpn interface)
- Set `--node-external-ip` on node B to `'1.2.3.5,10.0.0.2'` (where 1.2.3.5 would be the external interface, and 10.0.0.2 would be the vpn interface)
- Install a LoadBalancer service like nginx-ingress

**Expected behavior:**
LoadBalancer service should have external-ips: `1.2.3.4,10.0.0.1,1.2.3.5,10.0.0.2`, being reachable from all external ips in the cluster

**Actual behavior:**
LoadBalancer service only has external-ips: `10.0.0.1,10.0.0.2`

**Additional context / logs:**

**Comment by manuelbuil** [comment]
> **Environmental Info:** K3s Version: v1.24.3+k3s1
> 
> Node(s) CPU architecture, OS, and Version:
> 
> ```
> 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
> 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
> ```
> 
> Cluster Configuration: 1 master `node A` 1 agent `node B` different networks connected via manual wireguard, flannel with vxlan over the wireguard channel
> 
> **Describe the bug:** Specifying multiple external ips in `--node-external-ip` only uses the first one. This is needed because I would like LoadBalancer services to have both the external interface ip for accessing it from the cluster externally, as well as the wireguard-ip to be able to access it from inside the vpn network.
> 
> If there is any way to work around this for LoadBalancer services I'd accept it as a workaround.
> 
> **Steps To Reproduce:**
> 
> * Installed K3s
> * Set `--node-external-ip` on node A to `'1.2.3.4,10.0.0.1'` (where 1.2.3.4 would be the external interface, and 10.0.0.1 would be the vpn interface)
> * Set `--node-external-ip` on node B to `'1.2.3.5,10.0.0.2'` (where 1.2.3.5 would be the external interface, and 10.0.0.2 would be the vpn interface)
> * Install a LoadBalancer service like nginx-ingress
> 
> **Expected behavior:** LoadBalancer service should have external-ips: `1.2.3.4,10.0.0.1,1.2.3.5,10.0.0.2`, being reachable from all external ips in the cluster
> 
> **Actual behavior:** LoadBalancer service only has external-ips: `10.0.0.1,10.0.0.2`
> 
> **Additional context / logs:**

Can you show me the annotations of one of your nodes?

**Comment by Northcode** [comment]
Here are the ones for the vps, real external ip replaced with 1.2.3.4:
```
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      alpha.kubernetes.io/provided-node-ip: 10.0.0.1
      csi.volume.kubernetes.io/nodeid: '{"zfs.csi.openebs.io":"northcode.no"}'
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"16:24:14:42:8d:a8"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 10.0.0.1
      k3s.io/external-ip: 1.2.3.4,10.0.0.1
      k3s.io/hostname: northcode.no
      k3s.io/internal-ip: 10.0.0.1
      k3s.io/node-args: '["server","--node-ip","10.0.0.1","--advertise-address","10.0.0.1","--node-external-ip","1.2.3.4,10.0.0.1","--flannel-iface","wg0","--write-kubeconfig-mode","664","--default-local-storage-path","/kube","--node-label","nettype=external","--disable","traefik"]'
      k3s.io/node-config-hash: SLN6277C5Y5LJOCLC2IQUIOYBU3FIRUNPY2PYXE2CZQMVFWMF5QA====
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/1d787a9b6122e3e3b24afe621daa97f895d85f2cb9cc66860ea5ff973b5c78f2"}'
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
```
