### ISSUE TITLE
node-ip kubelet flag is not working as expected

### ISSUE THREAD

**Issue by riuvshyn** [k3s-io/k3s#6067]
**Environmental Info:**
K3s Version:  v1.23.9+rke2r1

Node(s) CPU architecture, OS, and Version: 
```
Linux ip-172-29-204-225 5.4.0-1083-aws #90~18.04.1-Ubuntu SMP Fri Aug 5 08:12:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
3 servers 3 workers

k3s config:
```
egress-selector-mode: disabled
node-name: ip-xxx-xx-xxx-xxx.eu-central-1.compute.internal
flannel-backend: none
disable-cloud-controller: true
node-ip: xxx.xx.xxx.xxx
node-external-ip: xxx.xx.xxx.xxx
kube-apiserver-arg:
- "service-account-key-file=/etc/rancher/service-account.pub"
- "service-account-issuer=https://xxxxxx.s3.eu-central-1.amazonaws.com"
- "service-account-signing-key-file=/etc/rancher/service-account.key"
- "enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,Priority,TaintNodesByCondition,PersistentVolumeClaimResize,PodSecurityPolicy"
- "audit-log-path=/var/log/k8s-audit/audit.log"
- "audit-policy-file=/etc/rancher/k3s/audit_policy.yaml"
- "audit-log-maxage=90"
- "audit-log-maxbackup=10"
- "audit-log-maxsize=500"
kube-controller-arg:
- "service-account-private-key-file=/etc/rancher/service-account.key"
kubelet-arg:
- "cloud-provider=external"
- "provider-id=aws:///eu-central-1c/i-xxxx"
- "node-ip=xxx.xx.xxx.xxx"
- "max-pods=60"

tls-san:
- "int-xxxxxxxxxx.elb.eu-central-1.amazonaws.com"
no-deploy:
- "traefik"
- "metrics-server"
- "servicelb"
```

CNI plugin: [aws eni cni](https://github.com/aws/amazon-vpc-cni-k8s)
CCM: [cloud-provider-aws](https://github.com/kubernetes/cloud-provider-aws)

**Describe the bug:**
When using aws vpc cni k3s nodes gets all pods IPs in to node `status.addresses`, example:
```
 status:
    addresses:
    - address: xxx.xxx.xxx.xxx              <--- actual node IP
      type: InternalIP
    - address: zzz.zz.zzz.zzz              <--- some POD IP
      type: InternalIP
    - address: zzz.zz.zzz.zzz              <--- some POD IP
      type: InternalIP
    - address: zzz.zz.zzz.zzz              <--- some POD IP
      type: InternalIP
    - address: zzz.zz.zzz.zzz              <--- some POD IP
      type: InternalIP
    - address: yyy.yy.yyy.yyy              <--- some POD IP
      type: InternalIP
    - address: ip-xxx-xxx-xxx-xxx.eu-central-1.compute.internal
      type: InternalDNS
    - address: ip-xxx-xxx-xxx-xxx.eu-central-1.compute.internal
      type: Hostname
```
and this sometime causing weird issues like this:

```
Error from server: Get "https://xxxxxxxxxx:10250/containerLogs/my-deployment/my-deployment-75b555c4b9-5fp2v/my-pod": x509: certificate is valid for 127.0.0.1, xxx.xx.xxx.xxx, xxx.xx.xxx.xxx, not yyy.yy.yyy.yyy
```
where `xxx.xx.xxx.xxx` is the actual node IP and `yyy.yy.yyy.yyy` is some pod IP running on the same node and listed in node `status.addresses`

Usually passing `--node-ip`  flag to the kubelet makes sure that the only `InternalIP` node will have in `status.addresses` is going to be that IP passed with `--node-ip`, but that does not work for k3s. I've tried passing it via `kubelet-arg:` as well as `node-ip` and `node-external-ip` in my k3s config but every node still get all pods IPs running on the same now listed in node `status.addresses`

**Steps To Reproduce:**
Installed K3s with aws vpc CNI, configure kubelet with `node-ip` and describe node to see node `status.addresses`

**Expected behavior:**
Once kubelet flag `--node-ip` is supposed to set only one internalIP for the node addresses to the value passed via flag.

**Actual behavior:**
kubelet flag `--node-ip` seems ignored and with AWS VPC CNI node gets all pods IPs running on that node in node `status.addresses`

**Additional context / logs:**
