### ISSUE TITLE
helm-controller does not pickup helm.cattle.io/v1/HelmChart defenitions

### ISSUE THREAD

**Issue by ivan-sirosh** [k3s-io/k3s#6087]
**Environmental Info:**
K3s Version: 
k3s version v1.24.4+k3s1 (c3f830e9)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 
Linux 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 single node

**Describe the bug:**
I want to deploy a helm chart to my cluster by using the integrated helm-controller, but it does not work as expected.  

**Steps To Reproduce:**
- Installed K3s: 
`curl -sfL https://get.k3s.io | sh -`
- define new manifest:
```
apiVersion: v1
kind: Namespace
metadata:
  name: whoami
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: whoami
  namespace: kube-system
spec:
  repo: https://charts.philippwaller.com
  chart: whoami
  targetNamespace: whoami
```
- put manifest to `/var/lib/rancher/k3s/server/manifests/` folder

**Expected behavior:**
pod `whoami` is deployed

**Actual behavior:**
nothing happened

**Additional context / logs:**
```
get po -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   coredns-b96499967-x4tt2                   1/1     Running     0          110m
kube-system   local-path-provisioner-7b7dc8d6f5-sxm6n   1/1     Running     0          110m
kube-system   metrics-server-668d979685-4rllg           1/1     Running     0          110m
kube-system   helm-install-traefik-crd-q5nqn            0/1     Completed   0          110m
kube-system   helm-install-traefik-h5lh2                0/1     Completed   1          110m
kube-system   svclb-traefik-7057123b-v2j9d              2/2     Running     0          109m
kube-system   traefik-7cd4fcff68-78k7k                  1/1     Running     0          109m
```
