### ISSUE TITLE
Updated k3s from 1.22.9+k3s1 to 1.22.13+k3s1 = getting "incompatible CNI versions; config is "1.0.0", plugin supports ["0.1.0" ... "0.4.0"]

### ISSUE THREAD

**Issue by lsascha** [k3s-io/k3s#6118]
**Environmental Info:**
K3s Version: 1.22.13+k3s1

Node(s) CPU architecture, OS, and Version: 
`Linux k3s-agent-0 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
5 Servers, 3 agents

**Describe the bug:**
after the Update, no Pod starts on the agents
Error is
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "d14c777ef68a41666f234d7200d00dc4ab2773b55e050a7a539efded8ed784d6": plugin type="flannel" failed (add): incompatible CNI versions; config is "1.0.0", plugin supports ["0.1.0" "0.2.0" "0.3.0" "0.3.1" "0.4.0"]
```

**Steps To Reproduce:**
- Installed K3s: 
```
curl -sfL https://get.k3s.io | K3S_TOKEN="${random_password.k3s_cluster_secret.result}" INSTALL_K3S_VERSION="${var.k3s_version}" sh -s - server --cluster-init --disable local-storage --disable-cloud-controller --disable traefik --disable servicelb --kubelet-arg="cloud-provider=external" --kube-apiserver-arg="service-node-port-range=1-65535
```
using a slightly modified https://github.com/StarpTech/k-andy version.

**Expected behavior:**
all Pods to start without errors after a minor update

**Actual behavior:**
getting Errors on Pod startups

**Additional context / logs:**
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "d14c777ef68a41666f234d7200d00dc4ab2773b55e050a7a539efded8ed784d6": plugin type="flannel" failed (add): incompatible CNI versions; config is "1.0.0", plugin supports ["0.1.0" "0.2.0" "0.3.0" "0.3.1" "0.4.0"]

error killing pod: failed to "KillPodSandbox" for "769d61d7-1485-4111-b5b3-77447ea3b219" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"62a016d90aad89403444279f728d4fffd1b778f5ebe1bea88b7d0ee16f2d3e8e\": plugin type=\"portmap\" failed (delete): incompatible CNI versions; config is \"1.0.0\", plugin supports [\"0.1.0\" \"0.2.0\" \"0.3.0\" \"0.3.1\" \"0.4.0\"]"
```

when i change in `/var/lib/rancher/k3s/agent/etc/cni/net.d/10-flannel.conflist`
`"cniVersion":"1.0.0"` to `"cniVersion":"0.4.0"`
the file is just reset back to contain 1.0.0

but i think that would be the wrong solution anyway.

any ideas except reverting the update?

thanks in advance

**Comment by brandond** [comment]
Have you customized your containerd config template as described at https://rancher.com/docs/k3s/latest/en/advanced/#configuring-containerd? The only time I've seen this error, it was due to someone providing a containerd config template that hardcoded the CNI bin directory to point at an older version of the plugins that doesn't support the updated CNI config version. If you're are providing a containerd config template, make sure that it is actually a template (as described in the docs), and not just a copy of an already-rendered containerd config file with some values changed.

**Comment by lsascha** [comment]
at least i did not provide a containerd config template on purpose. But i don't know if the hetzner CCM https://github.com/hetznercloud/hcloud-cloud-controller-manager maybe does something there.

at least in the k-andy deployment i could not find any containerd config deploying as well. and also not in my modified version. (i basically only added longhorn and nginx ingress and autoscaler)

question is how i could find out and fix it. Or should i also upgrade the hetzner CCM?

**Comment by brandond** [comment]
You would need to check on the node; it's not something that's deployed to the cluster or that could be managed by something within it. Check for the existence of `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl` and confirm that it does not have a hardcoded `bin_dir` in the `[plugins.cri.cni]` section.

Another possibility is that you've disabled flannel and have deployed your own CNI that doesn't support this version. Is that the case?

**Comment by lsascha** [comment]
I checked that folder and it only has an config.toml file with the following content:
```toml

[plugins.opt]
  path = "/var/lib/rancher/k3s/agent/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "rancher/mirrored-pause:3.6"

[plugins.cri.containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true


[plugins.cri.cni]
  bin_dir = "/var/lib/rancher/k3s/data/bf2a81605f06fcea11ce22b07b34d65fc0b871b806e342c80a2db6e575d1f0f3/bin"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"


[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins.cri.containerd.runtimes.runc.options]
        SystemdCgroup = true

```

i also checked `/var/lib/rancher/k3s/data/bf2a81605f06fcea11ce22b07b34d65fc0b871b806e342c80a2db6e575d1f0f3/`
where `/var/lib/rancher/k3s/data/current` symlinks to exactly that folder mentioned in the toml file.

so to me that all looks okay. Never wrote any `config.toml.tmpl`
