### ISSUE TITLE
Unable to upgrade K3s from 1.24 to 1.25 with system-upgrade-controller

### ISSUE THREAD

**Issue by est-suse** [k3s-io/k3s#6121]
**Environmental Info:**
K3s Version: 

K3s v1.24.4

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

3 servers / 2 agents
**Describe the bug:**

When trying to upgrade from 1.24 to 1.25 via SUC, the servers display the following error:

resource mapping not found for name: “k3s-server” namespace: “system-upgrade” from “xxx.yaml”: no matches for kind “Plan” in version.

**Steps To Reproduce:**

- Have  1.24 cluster up and running.
-Apply SUC
-Apply the upgrade Plan

The error below will be displayed:

resource mapping not found for name: “k3s-server” namespace: “system-upgrade” from “xxx.yaml”: no matches for kind “Plan” in version.

**Expected behavior:**

Should Upgrade without any issue.

**Actual behavior:**

Cluster is not longer accesible.

**Workaround**

There is a workaround to mitigate this, reference here:

Setup a cluster with single cluster (CIS Mode) with previous stable version (v1.24.4+k3s1) by following https://rancher.com/docs/k3s/latest/en/security/hardening_guide/

Ensure the cluster is up and running
Once the SUC and plan are applied, follow the next steps:

Add cluster-level-pss.yaml on /var/lib/rancher/k3s/server

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1beta1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "baseline"
      enforce-version: "latest"
      audit: "restricted"
      audit-version: "latest"
      warn: "restricted"
      warn-version: "latest"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: [kube-system]

```
Update /etc/rancher/k3s/config.yaml by replacing kube-apiserver-arg with below (replaces PSP with PS
and adds admission-control-config-file)
```
kube-apiserver-arg:
  - 'audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log'
  - 'audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml'
  - 'audit-log-maxage=30'
  - 'audit-log-maxbackup=10'
  - 'audit-log-maxsize=100'
  - 'request-timeout=300s'
  - 'service-account-lookup=true'
  - 'enable-admission-plugins=NodeRestriction,PodSecurity,NamespaceLifecycle,ServiceAccount'
  - 'admission-control-config-file=/var/lib/rancher/k3s/server/cluster-level-pss.yaml'
```

Replace /var/lib/rancher/k3s/server/manifests/policy.yaml with below (removes PSP and RBAC) by following the next steps:
Kubectl get psp -A (you will get results)
Kubectl delete -f policy.yaml
rm policy.yaml (in soon succession)
create the new policy.yaml file (code below)
Policy will be applied automatically

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-network-dns-policy
  namespace: kube-system
spec:
  ingress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
  - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace
  namespace: kube-system
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-system
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace
  namespace: default
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: default
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace
  namespace: kube-public
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-public
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-svclbtraefik-ingress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app: svclb-traefik
  ingress:
  - {}
  policyTypes:
  - Ingress
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-metrics-server
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: metrics-server
  ingress:
  - {}
  policyTypes:
  - Ingress
---
```
