### ISSUE TITLE
deploy hpa failed  "did not receive metrics for any ready pods"

### ISSUE THREAD

**Issue by wang-xiaowu** [k3s-io/k3s#6148]
**Environmental Info:**
K3s Version:  1.24.4+k3s1

Node(s) CPU architecture, OS, and Version: linux core 5.4, centos 7.2

Cluster Configuration: 3 servers, 3 agents

**Describe the bug:**

```
deploy hpa failed
# kubectl describe hpa app-manager -n sopei-biz
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Normal   SuccessfulRescale             56s                horizontal-pod-autoscaler  New size: 2; reason: Current number of replicas below Spec.MinReplicas
  Warning  FailedGetResourceMetric       11s (x3 over 41s)  horizontal-pod-autoscaler  failed to get cpu utilization: did not receive metrics for any ready pods
  Warning  FailedComputeMetricsReplicas  11s (x3 over 41s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: did not receive metrics for any ready pods

top is ok! 
# kubectl top pods -n sopei-biz
NAME                                            CPU(cores)   MEMORY(bytes)   
api-auth-7454f758b6-ctr9v                       82m          165Mi           
api-auth-7454f758b6-xh9sr                       74m          156Mi 

metric-server has no error log
```

this is my deploy.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: app-manager
  namespace: sopei-biz
spec:
  selector:
    app: app-manager
  type: NodePort
  ports:
    - port: 32201
      targetPort: 32201
      protocol: TCP
      nodePort: 32201
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-manager
  namespace: sopei-biz
  labels:
    app: app-manager
spec:
  selector:
    matchLabels:
      app: app-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-manager
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                namespaces:
                  - sopei-biz
                labelSelector:
                  matchLabels:
                    app: app-manager
              weight: 100
      containers:
        - image: $REGISTRY_ADDRESS/${NODE_ENV}/${CI_PROJECT_NAME}:v${CI_PIPELINE_ID}
          envFrom:
            - configMapRef:
                name: sopei-biz-configmap
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 15m
              memory: 510Mi
            limits:
              cpu: 15m
              memory: 510Mi
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "while [ $(netstat -plunt | grep tcp | wc -l | xargs) -ne 0 ]; do sleep 1; done"
          livenessProbe:
            tcpSocket:
              port: 32201
          readinessProbe:
            tcpSocket:
              port: 32201
          name: app-manager
          ports:
            - containerPort: 32201
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/sopei
              name: sopei-log
      volumes:
        - name: sopei-log
          persistentVolumeClaim:
            claimName: sopei-log
            readOnly: false
      imagePullSecrets:
        - name: nexus3secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-manager
  namespace: sopei-biz
  labels:
    app: app-manager
spec:
  # 指定要控制的deployment信息
  scaleTargetRef:
    apiVersion: apps/v1
    name: app-manager
    kind: Deployment
  # 允许最大副本数
  maxReplicas: 10
  # 允许最小副本数
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # 期望的 CPU 平均值,当整体的资源利用率超过这个百分比的时候，会进行扩容
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0  # 默认为 0，只使用当前值进行扩缩容
      policies:
        - periodSeconds: 180  # 每 3 分钟最多扩容 5% 的 Pods
          type: Percent
          value: 5
        - periodSeconds: 60  # 每分钟最多扩容 1 个 Pod，扩的慢一点主要是为了一个个地预热，避免一次扩容太多未预热的 Pods 导致服务可用率剧烈抖动
          type: Pods
          value: 1
      selectPolicy: Min  # 选择最小的策略
    # 以下的一切配置，都是为了更平滑地缩容
    scaleDown:
      stabilizationWindowSeconds: 600  # 使用过去 10 mins 的最大 cpu 值进行缩容计算，避免过快缩容
      policies:
        - type: Percent  # 每 3 mins 最多缩容 `ceil[当前副本数 * 5%]` 个 pod（20 个 pod 以内，一次只缩容 1 个 pod）
          value: 5
          periodSeconds: 180
        - type: Pods  # 每 1 mins 最多缩容 1 个 pod
          value: 1
          periodSeconds: 60
      selectPolicy: Min  # 上面的 policies 列表，只生效其中最小的值作为缩容限制（保证平滑缩容）
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-manager
  namespace: sopei-biz
  labels:
    app: app-manager
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app-manager
```

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**
