### ISSUE TITLE
[release-1.23] Move servicelb into cloudprovider

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6201]
Backport to release-1.23:
*  #6199

**Comment by mdrahman-suse** [comment]
### Validated using v1.23.13-rc2+k3s1

#### /etc/rancher/k3s/config.yaml
```yaml
# config.yaml 1
write-kubeconfig-mode: 644
cluster-init: true
disable:
  - servicelb

# config.yaml 2
write-kubeconfig-mode: 644
cluster-init: true
disable-cloud-controller: true

# config.yaml 3
write-kubeconfig-mode: 644
cluster-init: true
disable:
  - servicelb
disable-cloud-controller: true

# config.yaml 4
write-kubeconfig-mode: 644
cluster-init: true
```

#### Additional Files
```yaml
# lb.yaml
kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 81
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: ranchertest/mytestcontainer:unprivileged
```

#### Steps
1. Ensure config.yaml is written appropriately (performed 4 separate scenarios so used 4 separate config.yamls)
2. Start k3s `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.13-rc2+k3s1 sh -`
3. Check providerid on node: `kubectl describe node | grep -i providerid`. This should succeed when cloud-controller is enabled and fail when it is disabled.
4. Check lb. When disabled, all of the below should fail. When enabled, it should all succeed.
```
# Check whether there is a svclb pod for traefik, such as "pod/svclb-traefik-6a31e74f-nxb9x"
# Deploy lb.yaml via "kubectl apply -f lb.yaml"
# Check if the service gets an IP associated via "kubectl get svc -o wide"
# curl the endpoint if there is an IP on the service: "curl <IP>:81/name.html"
```

#### Validation Results
- When both are disabled, there is no providerid on the node and there is no IP on the service. curl command fails even when using the node ip (as expected).
- When both are enabled, there is a providerid and the service receives an external IP. Curl'ing that succeeds.
- Expected results as mentioned in the steps above are achieved when only one is disabled.

- In all cases, the Node goes to a `Ready` state and all other pods are `Ready`
