### ISSUE TITLE
K3s with traefik IngressRouteTCP (TCP router) on metallb does not work

### ISSUE THREAD

**Issue by FSeidinger** [k3s-io/k3s#6206]
**Environmental Info:**
K3s Version: v1.24.6+k3s1 (a8e0c66d)

Node(s) CPU architecture, OS, and Version: Linux concierge 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1. One server with embedded etcd and three agents.
1. Using kube-proxy in `ipvs` mode.
1. Using metallb as loadbalancer in BGP mode.
1. Using traefik as ingress with external loadbalancer IP.
1. Netplan based multihomed network setup running on bridge `br0` using untagged management network on `192.168.1.0/24` and tagged node network on `192.168.10.0/24`.
1. Restricted flannel o interface `vlan.10` with option `--flannel-iface=vlan.10`.

Netplan setup:
```
---
network:
  version: 2
  ethernets:
    enp3s0:
      dhcp4: no
      dhcp6: no

  bridges:
    br0:
      interfaces:
        - enp3s0
      addresses:
        - 192.168.1.2/24
      routes:
        - to: default
          via: 192.168.1.1

  vlans:
    vlan.10:
      id: 10
      link: br0
      addresses:
        - 192.168.10.2/24
```

**Describe the bug:**

### Context

I want to host an MQTT broker service on K3s with listening on TCP ports `1883` and `8883`, whereas the second port uses TLS.

### Prerequisites

Added the ports `1883` and `8833` as entry ports to traefik, using the HelmChartConfig.

Deployed the Eclipse Mosquitto MQTT broker image image .

**Steps To Reproduce:**
- Installed K3s:
  ```
  curl -sfL https://get.k3s.io | sh -s - \
  --flannel-iface=vlan.10  \
  --write-kubeconfig-mode 644 \
  --resolv-conf /run/systemd/resolve/resolv.conf \
  --disable servicelb \
  --kube-proxy-arg proxy-mode=ipvs \
  --disable local-storage \
  --cluster-init
  ```
- Installed K3s agents on three nodes: 
  ```
  curl -sfL https://get.k3s.io | sh -s - \
  agent \
  --token secret \
  --flannel-iface=vlan.10 \
  --resolv-conf /run/systemd/resolve/resolv.conf \
  --server https://my-ip:6443
  ```
- Configured my edge router with BGP neighbors matching my cluster nodes.
- Created namespace metallb-system.
- Installed official metallb distribution using helm:
  ```
  helm repo add metallb https://metallb.github.io/metallb
  helm upgrade --install --namespace metallb-system metallb metallb/metallb
  ```
- Configured metallb using `metallb-configuration.yaml`:
  ```
  ---
  apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    name: k3s-pool
    namespace: metallb-system
  spec:
    addresses:
      - 192.168.10.32-192.168.10.223
    avoidBuggyIPs: true
  ---
  apiVersion: metallb.io/v1beta2
  kind: BGPPeer
  metadata:
    name: k3s-peer
    namespace: metallb-system
  spec:
    myASN: 64512
    peerASN: 64512
    peerAddress: 192.168.10.1
  ---
  apiVersion: metallb.io/v1beta1
  kind: BGPAdvertisement
  metadata:
    name: k3s-advertisement
    namespace: metallb-system
  spec:
    ipAddressPools:
      - k3s-pool
  ```
- Configured traefik entry points and load balancer IP using helm chart configuration `/var/lib/rancher/k3s/server/manifests/traefik-override.yaml`:
  ```
  ---
  apiVersion: helm.cattle.io/v1
  kind: HelmChartConfig
  metadata:
    name: traefik
    namespace: kube-system
  spec:
    valuesContent: |-
      ports:
        mqtt:
          protocol: TCP
          port: 1833
          expose: true
        mqtts:
          protocol: TCP
          port: 8883
          expose: true
      service:
        spec:
          loadBalancerIP: 192.168.10.32
  ```
- Deployed official Eclipse Mosquitto MQTT broker with deployment, service and traefik IngressRouteTCP (TCP router):
  ```
  apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRouteTCP
    name: mqtt
    namespace: default
  spec:
    entryPoints:
    - mqtt
    routes:
    - match: HostSNI(`*`)
      services:
      - name: mqtt
        port: 1883
  ```

**Expected behavior:**

I can connect to the loadbalancer IP on port `1883`.

**Actual behavior:**

Port `1883` is not listening on the loadbalancer IP.

**Additional context / logs:**

I used nmap to see if ports are open on the IP addresses involved. My findings are that the MQTT pod is listening on port `1883` on its cluster IP, the MQTT service is listening on port `1883` as well, but traefik neither listens for port `1883` on its cluster IP nor its loadbalancer IP.

***Testing the MQTT pod:***

```
kubectl get pods -o wide
NAME                    READY   STATUS    RESTARTS   AGE   IP           NODE        NOMINATED NODE   READINESS GATES
mqtt-75455fffbc-qgrls   1/1     Running   0          20h   10.42.0.33   concierge   <none>           <none>

nmap -p 1883 10.42.0.33
Starting Nmap 7.80 ( https://nmap.org ) at 2022-10-02 10:41 CEST
Nmap scan report for 10.42.0.33
Host is up (0.000055s latency).

PORT     STATE SERVICE
1883/tcp open  mqtt
MAC Address: C2:4B:22:7F:FF:EC (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 0.19 seconds
```
Also testing with the `mosquitto_pub` command line client showed, that I can connect to the pod using the master nodes network.

***Testing the MQTT service:***

```
kubectl get svc
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
mqtt         ClusterIP   10.43.78.188   <none>        1883/TCP   20h

nmap -p 1883 10.43.78.188
Starting Nmap 7.80 ( https://nmap.org ) at 2022-10-02 10:40 CEST
Nmap scan report for concierge (10.43.78.188)
Host is up.

PORT     STATE    SERVICE
1883/tcp filtered mqtt

Nmap done: 1 IP address (1 host up) scanned in 2.13 seconds

```
Same result here. The `mosquitto_pub` command line client can connect to the pod using the master nodes network.

***Testing traefik service on cluster port:***

```
kubectl -n kube-system get svc
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                    AGE
traefik          LoadBalancer   10.43.169.177   192.168.10.32   1833:31612/TCP,8883:31291/TCP,80:30096/TCP,443:32654/TCP   37h

nmap -p 1883 10.43.81.131
Starting Nmap 7.80 ( https://nmap.org ) at 2022-10-02 10:44 CEST
Nmap scan report for concierge (10.43.81.131)
Host is up (0.000033s latency).

PORT     STATE  SERVICE
1883/tcp closed mqtt

Nmap done: 1 IP address (1 host up) scanned in 0.10 seconds
```

Port seems not be mapped on the cluster address of the traefik service. The `mosquitto_pub` command line client tries to connect but never can establish a broker connection.

***Testing traefik service on loadbalancer port:***

```
nmap -p 1883 192.168.10.32
Starting Nmap 7.80 ( https://nmap.org ) at 2022-10-02 10:44 CEST
Nmap scan report for k3s.cluster.frank-seidinger.de (192.168.10.32)
Host is up (0.000035s latency).

PORT     STATE  SERVICE
1883/tcp closed mqtt

Nmap done: 1 IP address (1 host up) scanned in 0.08 seconds
```

Same result here. Port seems not be mapped on the cluster address of the traefik service. The `mosquitto_pub` command line client tries to connect but never can establish a broker connection.

**Comment by brandond** [comment]
> traefik neither listens for port 1883 on its cluster IP nor its loadbalancer IP.

If Traefik isn't listening on that port, that sounds like an issue with your Traefik configuration, not with K3s?

**Comment by FSeidinger** [comment]
> If Traefik isn't listening on that port, that sounds like an issue with your Traefik configuration, not with K3s?

It's kind of a gray area here. Sure it might be a traefik problem, but it comes as a bundled component. Bundling method, default configuration and the helm chart configuration advises are a k3s thing.

> Note that just adding ports to the values in the HelmChart config doesn't actually tell traefik to listen on those ports, you will probably need to add extra args to enable those entrypoints.

There is nothing special here. The default ports are configured by the default helm chart config coming with k3s in the `/var/lib/rancher/k3s/server/manifest/` directory an are only extended as described in the k3s documentation in the same way.

I can see the additional ports, the TCP ingress router and the traefik service connecting to the MQTT service on the traefik dashboard.

**Comment by brandond** [comment]
> It's kind of a gray area here. Sure it might be a traefik problem, but it comes as a bundled component. 

The helm chart is not ours, it is bundled in from the upstream project at https://github.com/traefik/traefik-helm-chart/tree/v10.19.3/traefik - our packaging just handles installing/updating the chart and passing values into it. If you have any questions on how to configure Traefik or its chart, I would probably take them there - we're not Traefik or Ingress experts by any means.

> Same result here. Port seems not be mapped on the cluster address of the traefik service.

I'm not sure what you mean by this? What are you looking at?

**Comment by FSeidinger** [comment]
> The helm chart is not ours, it is bundled in from the upstream project at https://github.com/traefik/traefik-helm-chart/tree/v10.19.3/traefik - our packaging just handles installing/updating the chart and passing values into it. If you have any questions on how to configure Traefik or its chart, I would probably take them there - we're not Traefik or Ingress experts by any means.

I kinda get it. You are only packaging and the responsibility if with the products.

> > Same result here. Port seems not be mapped on the cluster address of the traefik service.
> 
> I'm not sure what you mean by this? What are you looking at?

I forgot to mention my use case. I have some services left, that I cannot simply pack into containers and run it under kubernetes. Mainly because they have special network requirements like owning a network interface, doing broadcast, UPNP and stuff like that.

To host them I put them into VMs and let them access infrastructure, like databases, via kubernetes.

I guess I know now, where the problem is located. The VMs are on the same nodes than the k3s nodes and the way k3s works with SDN (flannel) and securing the cluster is by a lot of iptables rules.

Simply the rules forbid the VM to access the clusters. And the tests I ran show the view from one of the nodes. The cluster services can be pinged (ICMP) and the ports can be seen by nmap, but the connection is blocked by the firewall rules of k3s and flannel.

I guess there is no easy workaround for this and so I moved the VMs to machines outside the cluster. Everything works than as expected.

So if the coexcistance of cluster and VMs on the same bare metal machines is not one of the supported uses cases, I guess I can close this issue. I will just wait for your response.

Kind regards.

**Comment by brandond** [comment]
> Simply the rules forbid the VM to access the cluster services. And the tests I ran show the view from one of the nodes. The cluster services can be pinged (ICMP) and the ports can be seen by nmap, but the connection is blocked by the firewall rules of k3s and flannel.

I don't think they're blocked on purpose, it's probably just that some of the iptables rules aren't matching the traffic when it comes from another virtual interface.

> I guess there is no easy workaround for this and so I moved the VMs to machines outside the cluster. Everything works than as expected.

This is probably the easiest fix.

**Comment by abdennour** [comment]
Thanks guys! any news?

**Comment by brandond** [comment]
> the coexcistance of cluster and VMs on the same bare metal machines is not one of the supported uses cases, I guess I can close this issue. I will just wait for your response.

The kubelet-managed iptables rules don't really expect other virtualization stuff to be running on the same node. I think this is something that users would need to resolve on their own with custom iptables rules, or just don't run the VMs on the same node as the cluster if you're not using a Kubernetes-native VM platform (ie KubeVirt),

**Comment by stevenlafl** [comment]
How to get custom ports for STCP/TCP/UDP to work

```
    ...
    additionalArguments:
    - "--entrypoints.netbios-ns.address=:137/udp"
    - "--entrypoints.netbios-dgm.address=:138/udp"
    - "--entrypoints.netbios-ssn.address=:139/tcp"
    - "--entrypoints.microsoft-ds.address=:445/tcp"
    ports:
      netbios-ns:
        expose: true
        port: 137
        protocol: UDP
      netbios-dgm:
        expose: true
        port: 138
        protocol: UDP
      netbios-ssn:
        expose: true
        port: 139
        protocol: TCP
      microsoft-ds:
        expose: true
        port: 445
        protocol: TCP
    ...
 ```
 
 Both `additionalArguments` and `ports` with `expose` appear to be necessary.
