### ISSUE TITLE
k3s-killall.sh does not stop containers

### ISSUE THREAD

**Issue by std4453** [k3s-io/k3s#6218]
**Environmental Info:**
K3s Version:
k3s version v1.23.4+k3s1 (43b1cb48)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 
Linux home 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux

Cluster Configuration:
1 node for development

**Describe the bug:**
Running `k3s-killall.sh` does not kill the containers.

**Steps To Reproduce:**
- Installed K3s with `curl -sfL https://get.k3s.io | sh -`
- Start some pods
- Run `k3s-killall.sh`

**Expected behavior:**
All containerd processes should be gone.

**Actual behavior:**
They're still there.

**Additional context / logs:**
On my system, the containerd processes are like:

```
root     1149329  0.0  0.0 708952  6656 ?        Sl   11:16   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/236cbef7cabe9346c9ee753db698d5c52951d03ac98c7d52cc38c171d64098ec -address /run/k3s/containerd/containerd.sock -containerd-binary /var/lib/rancher/k3s/data/4012316506613ee8c3cffc1e5b5eca706270685d33585804b257e93ea98d1917/bin/containerd
```

By looking at `k3s-killall.sh`, I can see:

https://github.com/k3s-io/k3s/blob/7710bcee06425109be4bbdb476ab307c343ac922/install.sh#L649-L651

Looks like it searches for processes containing `k3s/data/[^/]*/bin/containerd-shim`, where it finds none, and thus containers are not stopped.

I modified `k3s-killall.sh` to search for `k3s/data/[^/]*/bin/containerd` instead and it works without problems.

More context: In order to use nvidia GPU in cluster, I modified `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` to be:

```toml
[plugins.cri.containerd.runtimes.runc]
  # ---- changed from 'io.containerd.runc.v2' for GPU support
  runtime_type = "io.containerd.runtime.v1.linux"

# ---- added for GPU support
[plugins.linux]
  runtime = "nvidia-container-runtime"
```

Anyway, I think `k3s-killall.sh` could just perhaps check for both `.../containerd-shim` as well as `.../containerd` to find all the container processes to kill.
