### ISSUE TITLE
Private registry not reachable with crictl

### ISSUE THREAD

**Issue by bbremerfullstaq** [k3s-io/k3s#6219]
**Problem**
Currently I'm facing a problem with reaching a private registry.
When we want to pull images from the registry I get a forbidden error.
It seems that this is caused by the TLS settings, that aren't applied correctly.
I've tested several scenario's, where the ContainerD based scenario's fail, while others succeed.

Below the scenario's, configs and environment information are shown.

**Scenario's**
- Pull the image by applying a Kubernetes pod manifest, **without success**;
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: testimage
spec:
  containers:
  - name: testimage
    image: privateregistry/path/image:1.0.0
```

- Pull image with crictl with the private registry settings, **without success**;
```sh
crictl pull privateregistry/path/image:1.0.0
```

- Pull the image with docker (based on docker config), **with success**;
```sh
docker pull privateregistry/path/image:1.0.0
```

- Pull the image with ctr, **with success**.
```sh
ctr i pull privateregistry/path/image:1.0.0 -u username:password -k
```

**Configs**
registries.yaml
```yaml
mirrors:
  privateregistry:
    endpoint:
      - "privateregistry"
configs:
  "privateregistry":
    auth:
      username: username
      password: password
    tls:
      insecure_skip_verify: true
```

**Environment information**
- k3s version 1.23.6+k3s1
- ContainerD version 1.5.11-k3s2
- Crictl version: 1.22.0-k3s1
- Docker version: 20.10.12
