### ISSUE TITLE
Unready pods still used by service (nodePort)

### ISSUE THREAD

**Issue by minininja** [k3s-io/k3s#6260]
**Environmental Info:**
K3s Version: v1.24.6+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux yourhostnamehere 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Single server no agents

**Describe the bug:**

I am experimenting with readiness and liveness probes.  

With a failing liveness probe the pod is restarted without issue.  

With a failing readiness probe the deployment is marked as unheathly with pods that are not ready.  This is all good.  However when using a service to access the pods (nodePort) the unhealth pod is appears to be included in the set of pods that can service the request.  Shouldn't unready pods be evicted from the pool the service sends traffic to?

**Steps To Reproduce:**
1) Deploy this manifest, the container is a trivial rest service which utilizes timed-self resetting latches to implement the endpoints utilized for the liveness and readiness probes.  The container image is available on dockerhub.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toggler
  labels:
    app: toggler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toggler
  template:
    metadata:
      labels:
        app: toggler
    spec:
      containers:
        - name: toggler
          image: mikej091/toggler:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /get/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /get/ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 1

---

apiVersion: v1
kind: Service
metadata:
  name: toggler-service-nodeport
spec:
  type: NodePort
  selector:
    app: toggler
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31010
```
2) Wait until the pods are up and healthy.
```
yournamehere@avias:~/personal/toggler$ kubectl get pods
NAME                                               READY   STATUS      RESTARTS       AGE
toggler-577c8497d4-k5992                           1/1     Running     0              92s
toggler-577c8497d4-995qt                           1/1     Running     0              92s
```
3) `curl "http://server31010/get/ready"` and see a 200 response.
4) Execute `curl "http://server:31010/set/ready/false"` to set a single pod to be unready.
5) Verify that the pod is not showing in a ready state.
```
yournamehere@avias:~/personal/toggler$ kubectl get pods
NAME                                               READY   STATUS      RESTARTS       AGE
toggler-577c8497d4-k5992                           1/1     Running     0              92s
toggler-577c8497d4-995qt                           0/1     Running     0              92s
```
6) `curl "http://server31010/get/ready"` and see a 404.
7) Wait a minute
8) `curl "http://server31010/get/ready"` and see a 200 response.

**Expected behavior:**

Step 6 should result in a 200 with the unready pod essentially being evicted from the service.

**Actual behavior:**

Instead of the expected 200 I am seeing a 404.  I'm expecting that the unready pod should be essentially evicted from the pods that the service will send traffic to due to the unready state.  It furthermore seems as though all the traffic is going to the single pod as the only response seen was 404 rather than alternating between 200 and 404.

Also tested this using `https://killercoda.com/` which appears to evict the unready pod from the pool used by the service.

**Additional context / logs:**

Ask me for files and I'll get them.
