### ISSUE TITLE
Deploy controller stuck at `the server could not find the requested resource` when manifest includes removed resource

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6273]
**Environmental Info:**
K3s Version: 
v1.25.x

Node(s) CPU architecture, OS, and Version: 
n/a

Cluster Configuration:
n/a

**Describe the bug:**
Deploy controller stuck at `the server could not find the requested resource` when manifest includes removed resource type.

**Steps To Reproduce:**
* On a 1.24 cluster, create a manifest in /var/lib/rancher/k3s/server/manifests that includes a PodSecurityPolicy resource
* Upgrade the cluster to v1.25
* Note that the manifest (correctly) fails to apply with a `the server could not find the requested resource` error (PSPs have been removed). 
* Edit the manifest to remove the PSP resource definition.
* Note that the manifest still fails to apply, as the PSP GVK is still listed in the Addon status field:
```yaml
apiVersion: k3s.cattle.io/v1
kind: Addon
metadata:
  creationTimestamp: "2020-06-06T10:33:41Z"
  generation: 3
  name: metallb
  namespace: kube-system
  resourceVersion: "257656465"
  uid: 68133412-ed4b-4c21-b08f-9976e7541e4b
spec:
  checksum: a03e368da715b9a288c04a6e085c6b7d1bdf773bfa32fdfd843422b60999700a
  source: /var/lib/rancher/k3s/server/manifests/metallb.yaml
status:
  gvks:
  - Group: ""
    Kind: Namespace
    Version: v1
  - Group: policy
    Kind: PodSecurityPolicy
    Version: v1beta1
```

The deploy controller is stuck trying to add the PSP GVK at https://github.com/k3s-io/k3s/blob/64403978cdd4d098fa31cf3a6978a80e74327e2a/pkg/deploy/controller.go#L204

You can edit the addon to remove the GVK, at which point the deploy will succeed.

**Expected behavior:**
GVKs handled properly when missing

**Actual behavior:**
deploy controller gets stuck in a loop

**Additional context / logs:**

**Comment by brandond** [comment]
Simple test to reproduce:

```console
/ # kubectl apply -f -
apiVersion: k3s.cattle.io/v1
kind: Addon
metadata:
  name: test
  namespace: kube-system
status:
  gvks:
  - Group: invalid
    Kind: BogusKind
    Version: v1
addon.k3s.cattle.io/test created

/ # echo '# test' > /var/lib/rancher/k3s/server/manifests/test.yaml
```

**Comment by rancher-max** [comment]
### Validated on `master` branch with commit `13c633da126870ae487b78e050dfa5587c665764`
 
## Environment Details

 
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

Ubuntu 22.04 LTS
 
*Cluster Configuration:*

1 server
 
*Config.yaml:*

```yaml
# Initial config.yaml on v1.24.7+k3s1
write-kubeconfig-mode: "0644"
protect-kernel-defaults: true
secrets-encryption: true
kube-apiserver-arg:
  - 'audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log'
  - 'audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml'
  - 'audit-log-maxage=30'
  - 'audit-log-maxbackup=10'
  - 'audit-log-maxsize=100'
  - 'request-timeout=300s'
  - 'service-account-lookup=true'
  - 'enable-admission-plugins=NodeRestriction,PodSecurityPolicy,NamespaceLifecycle,ServiceAccount'
kube-controller-manager-arg:
  - 'terminated-pod-gc-threshold=10'
  - 'use-service-account-credentials=true'
kubelet-arg:
  - 'streaming-connection-idle-timeout=5m'
  - 'make-iptables-util-chains=true'
```

```yaml
# Updated config.yaml after upgrading 
write-kubeconfig-mode: "0644"
protect-kernel-defaults: true
secrets-encryption: true
kube-apiserver-arg:
  - 'audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log'
  - 'audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml'
  - 'audit-log-maxage=30'
  - 'audit-log-maxbackup=10'
  - 'audit-log-maxsize=100'
  - 'request-timeout=300s'
  - 'service-account-lookup=true'
  - 'enable-admission-plugins=NodeRestriction,PodSecurity,NamespaceLifecycle,ServiceAccount'
kube-controller-manager-arg:
  - 'terminated-pod-gc-threshold=10'
  - 'use-service-account-credentials=true'
kubelet-arg:
  - 'streaming-connection-idle-timeout=5m'
  - 'make-iptables-util-chains=true'
```
 
*Additional files*

```yaml
# Original policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-network-dns-policy
  namespace: kube-system
spec:
  ingress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
  - Ingress
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted-psp
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'csi'
    - 'persistentVolumeClaim'
    - 'ephemeral'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:restricted-psp
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default:restricted-psp
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:restricted-psp
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace
  namespace: kube-system
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-system
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace
  namespace: default
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: default
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace
  namespace: kube-public
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-public
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: system-unrestricted-psp
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-unrestricted-node-psp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system-unrestricted-psp-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-unrestricted-psp-role
rules:
- apiGroups:
  - policy
  resourceNames:
  - system-unrestricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-unrestricted-svc-acct-psp-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system-unrestricted-psp-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
---
# Reference https://rancher.com/docs/k3s/latest/en/security/hardening_guide/#networkpolicies
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-svclbtraefik-ingress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      svccontroller.k3s.cattle.io/svcname: traefik
  ingress:
  - {}
  policyTypes:
  - Ingress
---
# Reference https://rancher.com/docs/k3s/latest/en/security/hardening_guide/#networkpolicies
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-metrics-server
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: metrics-server
  ingress:
  - {}
  policyTypes:
  - Ingress
---
```

```yaml
# Updated policy.yaml (just includes a single comment)
# test update
```
 
## Testing Steps

1. Copy files to correct locations. For this test, I did full hardened mode. Follow https://docs.k3s.io/security/hardening-guide for more guidance.
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
$ sudo mkdir -p /var/lib/rancher/k3s/server/manifest && sudo cp policy.yaml /var/lib/rancher/k3s/server/manifest
```
2. Install k3s v1.24.7+k3s1: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.7+k3s1 sh -`
3. After it is up and running, upgrade the cluster:
```sh
# For issue validation:
$ curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=13c633da126870ae487b78e050dfa5587c665764 sh -

# For reproduction:
$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.3+k3s1 sh -
```
4. K3s will fatal error due to PodSecurityPolicies being part of the config.yaml, so edit `/etc/rancher/k3s/config.yaml` to change the `PodSecurityPolicy` part of the configuration to just `PodSecurity`
5. K3s will start, but there will be an error in the logs like: `level=error msg="Failed to process config: failed to process /var/lib/rancher/k3s/server/manifests/policy.yaml: the server could not find the requested resource"`
6. Update `/var/lib/rancher/k3s/server/manifest/policy.yaml` to the updated file (just a comment is fine) and check k3s logs
 
 
**Replication Results:**
- After step 6, the logs still had the error:
```
Nov 04 22:35:17 ip-172-31-1-199 k3s[6539]: time="2022-11-04T22:35:17Z" level=error msg="Failed to process config: failed to process /var/lib/rancher/k3s/server/manifests/policy.yaml: the server could not find the requested resource"
```
 
 
**Validation Results:**
- After step 6, the logs did not have the error and actually had proof of the manifest applying:
```
Nov 04 22:35:04 ip-172-31-8-218 k3s[6489]: time="2022-11-04T22:35:04Z" level=warning msg="Pruned unknown GVK from k3s.cattle.io/v1, Kind=Addon kube-system/policy: policy/v1beta1, Kind=PodSecurityPolicy"
Nov 04 22:35:04 ip-172-31-8-218 k3s[6489]: I1104 22:35:04.322748    6489 event.go:294] "Event occurred" object="kube-system/policy" fieldPath="" kind="Addon" apiVersion="k3s.cattle.io/v1" type="Normal" reason="ApplyingManifest" message="Applying manifest at \"/var/lib/rancher/k3s/server/manifests/policy.yaml\""
Nov 04 22:35:04 ip-172-31-8-218 k3s[6489]: I1104 22:35:04.383992    6489 event.go:294] "Event occurred" object="kube-system/policy" fieldPath="" kind="Addon" apiVersion="k3s.cattle.io/v1" type="Normal" reason="AppliedManifest" message="Applied manifest at \"/var/lib/rancher/k3s/server/manifests/policy.yaml\""
```
