### ISSUE TITLE
v1.25.3+k3s1 fails with helm based calico / nginx ingress

### ISSUE THREAD

**Issue by EugenMayer** [k3s-io/k3s#6389]
version:
v1.25.3+k3s1 
(i did not try .0 / 1 / .2 of the 1.25 series yet, i was upgrading from 1.24.4 to 1.25.3 directly, so it might be 1.25 in common)

Node(s) CPU architecture, OS, and Version: 
Single node, ubunut 22.04

Cluster Configuration:
single node, 1 server

**Describe the bug:**
When using 1.25.3 neither calico nor the nginx ingress come up. If i downgrading to 1.24.7, everything works fine again.

**Steps To Reproduce:**

Install latest (1.25.3)

```bash
curl -fL https://get.k3s.io | K3S_KUBECONFIG_MODE="640" INSTALL_K3S_EXEC="server --disable-kube-proxy --disable=servicelb --disable=servicelb --disable-network-policy --flannel-backend=none --disable traefik" sh
```

When you know install calico / nginx ingress from the official helm charts (latest versions)

- https://artifacthub.io/packages/helm/projectcalico/tigera-operator (using v3.24.3, also tried v3.24.2) 
- https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx (using 4.2.5).

calico and nginx ingress will fail to come up

When you downgrade to 1.24.7 via

```bash
curl -fL https://get.k3s.io | K3S_KUBECONFIG_MODE="640" INSTALL_K3S_VERSION="v1.24.7+k3s1" INSTALL_K3S_EXEC="server --disable-kube-proxy --disable=servicelb --disable=servicelb --disable-network-policy --flannel-backend=none --disable traefik" sh
```

everything will be up and running again.

**Expected behavior:**
1.25 should work without any issues

**Actual behavior:**
calico and nginx ingress will fail to come up

**Additional context / logs:**
calico node

```
2022-10-31 10:16:15.923 [ERROR][7053] felix/discovery.go 153: Didn't find any ready Typha instances.
2022-10-31 10:16:15.923 [ERROR][7053] felix/daemon.go 323: Typha discovery enabled but discovery failed. error=Kubernetes service missing IP or port
```

calico operator
```
2022/10/31 10:16:09 [INFO] Version: v1.28.3
2022/10/31 10:16:09 [INFO] Go Version: go1.18.7b7
2022/10/31 10:16:09 [INFO] Go OS/Arch: linux/amd64
2022/10/31 10:16:39 [ERROR] Get "[https://10.43.0.1:443/api?timeout=32s](https://10.43.0.1/api?timeout=32s)": dial tcp 10.43.0.1:443: i/o timeout
```

nginx logs
```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v1.3.1
  Build:         92534fa2ae799b502882c8684db13a25cde68155
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.10

-------------------------------------------------------------------------------

W1031 10:16:54.938970       7 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1031 10:16:54.939191       7 main.go:209] "Creating API client" host="[https://10.43.0.1:443](https://10.43.0.1/)"
```

**Comment by brandond** [comment]
Are you sure that the releases you're using support Kubernetes 1.25? Are you configuring your installation properly? We haven't changed anything between the two minor versions that would prevent Calico from working. 

Note that ingress-nginx won't work until the calico CNI is functional.

**Comment by EugenMayer** [comment]
@brandond calico v3.24.3 is suppose to work with 1.25 - AFAIR k3s (and rke2) bundle with prebuild calico, which will be supported in 1.25 too, right?

So i would assume that calico 3.24.x is supporting k8s 1.25. My configuration does not change from using 1.24 to 1.25, it is applied via terraform. My calico configuration is fairly standard and includes a couple of fixes that have been added to rke2/k3s too

```yaml
# see https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec
# also see https://github.com/rancher/rke2-charts/blob/main/charts/rke2-calico/rke2-calico/v3.22.101/values.yaml for RKE2 defaults
installation:
  controlPlaneTolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/etcd"
      operator: "Exists"
      effect: "NoExecute"
  enabled: true
  kubernetesProvider: ""
  calicoNetwork:
    bgp: Disabled
    linuxDataplane: ${dataPlane}
    hostPorts: ${hostPorts}
    ipPools:
      - blockSize: 26
        cidr: ${clusterCidr}
        encapsulation: ${encapsulation}
        natOutgoing: Enabled
        nodeSelector: all()
apiServer:
  enabled: true

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

global:
  systemDefaultRegistry: ""
  clusterCIDRv4: ""
  clusterCIDRv6: ""

felixConfiguration:
  wireguardEnabled: false
  # Config required to fix RKE2 issue #1541
  # @see https://github.com/rancher/rke2/blob/master/docs/known_issues.md#calico-with-vxlan-encapsulation
  featureDetectOverride: "ChecksumOffloadBroken=true"
```

**Comment by manuelbuil** [comment]
The errors you show are expected. You are deploying k3s without kube-proxy, so unless you enable something that replaces it (e.g. eBPF), there is no way for pods to reach services. The endpoint `https://10.43.0.1:443` is the kubernetes service (kube-api) and it calico require connecting to it. It should also not work on v1.24.x, unless some old iptable rules remained uncleaned for some reason

**Comment by EugenMayer** [comment]
**UPDATE:**
i have seen that my values are outdated, updated them to the latest changes in https://github.com/rancher/rke2-charts/blob/main/charts/rke2-calico/rke2-calico/v3.24.102/values.yaml

```yaml
installation:
  kubeletVolumePluginPath: "None"
```

```yaml
apiServer:
  enabled: true
```

```yaml
felixConfiguration:
  healthPort: 9099
  defaultEndpointToHostAction: "Drop"
  failsafeInboundHostPorts: ""
  failsafeOutboundHostPorts: ""
  logSeveritySys: "Info"
  xdpEnabled: true
```

```yaml
tolerations:
  - effect: NoExecute
  operator: Exists
  - effect: NoSchedule
  operator: Exists
```

from the current rke2 templates. I would not say that i see anything responsible but i will try to update my 1.24 based installation with this configuration and if that works, i will try a 1.25 based on and see if that fixed anything

**Comment by EugenMayer** [comment]
@manuelbuil i'am using BPF here

```
  calico_dataPlane           = "BPF"
  encapsulation              = "VXLANCrossSubnet"
```

that is why the kube-proxy is disabled (in both cases_

**Comment by EugenMayer** [comment]
I was calling it to soon. It was only working before i restarted the node. The it failed as before with the

calico node throwing

```
2022-10-31 17:21:13.215 [INFO][1773] tunnel-ip-allocator/config.go 60: Found FELIX_TYPHAK8SSERVICENAME=calico-typha
2022-10-31 17:21:13.215 [INFO][1773] tunnel-ip-allocator/config.go 60: Found FELIX_TYPHAK8SNAMESPACE=calico-system
2022-10-31 17:21:13.215 [INFO][1773] tunnel-ip-allocator/config.go 60: Found FELIX_TYPHAKEYFILE=/felix-certs/key.key
2022-10-31 17:21:13.215 [INFO][1773] tunnel-ip-allocator/config.go 60: Found FELIX_TYPHACERTFILE=/felix-certs/cert.crt
2022-10-31 17:21:13.216 [INFO][1773] tunnel-ip-allocator/config.go 60: Found FELIX_TYPHACAFILE=/typha-ca/caBundle
2022-10-31 17:21:13.216 [INFO][1773] tunnel-ip-allocator/config.go 60: Found FELIX_TYPHACN=typha-server
2022-10-31 17:21:13.224 [ERROR][1773] tunnel-ip-allocator/discovery.go 153: Didn't find any ready Typha instances.
2022-10-31 17:21:13.224 [FATAL][1773] tunnel-ip-allocator/startsyncerclient.go 48: Typha discovery enabled but discovery failed. error=Kubernetes service missing IP or port
```

and the typha server

```
2022-10-31 17:21:50.395 [INFO][7] watchercache.go 188: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices" error=resource does not exist: KubernetesEndpointSlice with error: the server could not find the requested resource
2022-10-31 17:21:51.395 [INFO][7] watchercache.go 175: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices"
2022-10-31 17:21:51.397 [INFO][7] watchercache.go 188: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices" error=resource does not exist: KubernetesEndpointSlice with error: the server could not find the requested resource
2022-10-31 17:21:52.399 [INFO][7] watchercache.go 175: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices"
2022-10-31 17:21:52.401 [INFO][7] watchercache.go 188: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices" error=resource does not exist: KubernetesEndpointSlice with error: the server could not find the requested resource
```

So right now, i'am still stuck with the 1.25 upgrade

**Comment by EugenMayer** [comment]
Just to be on one page, my current configuration looks like this

```yaml
# see https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec
# also see https://github.com/rancher/rke2-charts/blob/main/charts/rke2-calico/rke2-calico/v3.24.102/values.yaml for RKE2 defaults
installation:
  controlPlaneTolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/etcd"
      operator: "Exists"
      effect: "NoExecute"
  enabled: true
  kubernetesProvider: ""
## not working right now, maybe we have outdated CRDS, we get
## Error: error validating "": error validating data: ValidationError(Installation.spec): unknown field "kubeletVolumePluginPath" in io.tigera.operator.v1.Installation.spec
# kubeletVolumePluginPath: "None"
  calicoNetwork:
    bgp: Disabled
    linuxDataplane: ${dataPlane}
    hostPorts: ${hostPorts}
    ipPools:
      - blockSize: 26
        cidr: ${clusterCidr}
        encapsulation: ${encapsulation}
        natOutgoing: Enabled
        nodeSelector: all()

apiServer:
  enabled: false

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

# Tolerations for the tigera/operator pod.
tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists

nodeSelector:
  kubernetes.io/os: linux

global:
  systemDefaultRegistry: ""
  clusterCIDRv4: ""
  clusterCIDRv6: ""

felixConfiguration:
  wireguardEnabled: false
  # Config required to fix RKE2 issue #1541
  # @see https://github.com/rancher/rke2/blob/master/docs/known_issues.md#calico-with-vxlan-encapsulation
  featureDetectOverride: "ChecksumOffloadBroken=true"
  healthPort: 9099
  defaultEndpointToHostAction: "Drop"
  failsafeInboundHostPorts: ""
  failsafeOutboundHostPorts: ""
  logSeveritySys: "Info"
  xdpEnabled: true
```

with 

- dataplane being BPF
- and encapsulation being VXLANCrossSubnet

I guess the most reasonable (again) thing to be falsy is eBPF

**Comment by manuelbuil** [comment]
One thing that I'm missing is the place where you set the kube-api endpoint to Calico, so that it does not fall back to `10.43.0.1`, are you doing that somewhere? According to the Calico docs:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "<API server host>"
  KUBERNETES_SERVICE_PORT: "<API server port>"
```
