### ISSUE TITLE
fsGroup does not work with local-path volume

### ISSUE THREAD

**Issue by benzman81** [k3s-io/k3s#6401]
**Environmental Info:**
K3s Version: v1.24.6 used in Rancher Desktop

Node(s) CPU architecture, OS, and Version: 
Windows WSL Ubuntu with Rancher Desktop

Cluster Configuration:
Not relevant

**Describe the bug:**
`fsGroup` does not work with `local-path` volume.

**Steps To Reproduce:**
Create a simple non-root pod with a persistent volume claim using `local-path` storage. Then try to write a file into this mounted directory as non root user. This will not work as permissions of the mounted directory is still `root:root`.

**Expected behavior:**
Use Local Path Provisioner `v0.0.23`. With this version you can annotate a volume claim to use `local` instead of `hostPath`. Using `local` works with `fsGroup` and a non root user can write to the mounted directory.

**Actual behavior:**
With current Local Path Provisioner `v0.0.21` the storage class `local-path` mounts with `hostPath`. This prevents the use of `fsGroup` and causes permission problems.

**Additional context / logs:**
Manually upgrading to Local Path Provisioner `v0.0.23`  works:

Create a file patch.yaml:
```
spec:
  template:
    spec:
      containers:
        - name: local-path-provisioner
          image: rancher/local-path-provisioner:v0.0.23
```

Then run `kubectl -n kube-system patch deployment local-path-provisioner --patch-file patch.yaml`.
