### ISSUE TITLE
Traefik fails to install on RC builds

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#6484]
**Description:**
Traefik fails to install. The helm-install pod logs give:
```
+ helm_v3 install --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-19.0.000.tgz --values /config/values-01_HelmChart.yaml
Error: INSTALLATION FAILED: execution error at (traefik/templates/ingressclass.yaml:10:8): ERROR: You must use at least Kubernetes v1.16 with this Chart
```

Can workaround this by applying the following manifest:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ingressClass:
      enabled: false
```

I believe the error occurs due to k8s version including the `rcX` in the semver:
```
$ kubectl version --short
Client Version: v1.25.4-rc1+k3s1
Kustomize Version: v4.5.7
Server Version: v1.25.4-rc1+k3s1
```

**Versions:**
Confirmed this happens on v1.25.4-rc1+k3s1, but likely not limited to that so including v1.23.14-rc1+k3s1 and v1.24.8-rc1+k3s1 as well.
