### ISSUE TITLE
Pod is OOMKilled with no obvious reason

### ISSUE THREAD

**Issue by strainovic** [k3s-io/k3s#6513]
Hi all,

Thank you for this great product! We started using it daily, and now, we run into issues with Pod's memory consumption.

This is the test Pod we've created:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo1
spec:
  containers:
    - name: mem
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
        limits:
          memory: "300Mi"
      command: ["stress"]
      args: ["--vm", "2", "--vm-bytes", "250M", "--vm-hang", "0"]
```

When we deploy it on k3s, we're getting OOMKilled all of the time.

k3s

OS Image: Ubuntu 22.04.1 LTS
Container runtime version: containerd://1.6.8-k3s1
kubelet version: v1.24.6+k3s1

```console
k3s -v
k3s version v1.24.7+k3s1 (7af5b167)
go version go1.18.7
```

```console
uname -a
Linux dev-k8s-worker-01 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

![image](https://user-images.githubusercontent.com/10864240/202201615-60a33655-57b4-454d-a0bf-b8cf0a001006.png)

When we deploy it on microk8s, it works without any issue at 300Mi memory usage.

microk8s

OS Image: Ubuntu 22.04.1 LTS
Container runtime version: containerd://1.6.6
kubelet version: v1.25.3

![image](https://user-images.githubusercontent.com/10864240/202201867-71838a4f-9715-44f7-9708-13858bfb6962.png)

We think it can be related to cgroup v2 but this is all that we have at the moment.

We have the same issue with java and node services running on k3s.

Do you know what can be an issue here? 

Thanks!
