### ISSUE TITLE
[k3s-upgrade] upgrade not working on tainted k3s nodes

### ISSUE THREAD

**Issue by andi-blafasl** [k3s-io/k3s#6514]
**Environmental Info:**
K3s Version: 
v1.23.13+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux host01 5.15.70-flatcar #1 SMP Thu Oct 27 12:53:14 -00 2022 x86_64 Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz GenuineIntel GNU/Linux

Cluster Configuration:
3 Servers (tainted with [CriticalAddonsOnly](https://docs.k3s.io/installation/ha#:~:text=By%20default%2C%20server,CriticalAddonsOnly%3Dtrue%3ANoExecute.)
2 Nodes

**Describe the bug:**
upgrade no working, pod "apply..." not starting

**Steps To Reproduce:**
Setup HA k3s cluster with version 1.23.12+k3s1 embedded DB and taint the Server nodes as described in [https://docs.k3s.io/installation/](https://docs.k3s.io/installation/ha#:~:text=By%20default%2C%20server,CriticalAddonsOnly%3Dtrue%3ANoExecute.)
install upgrade controller with 
```
kubectl apply -f https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml
```
use plan
```
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-latest
  namespace: system-upgrade
spec:
  concurrency: 1
  version: v1.24.7+k3s1
  nodeSelector:
    matchExpressions:
      - {key: k3s-upgrade, operator: Exists}
  serviceAccountName: system-upgrade
  drain:
    force: true
  upgrade:
    image: rancher/k3s-upgrade
```

**Expected behavior:**
run the upgrade on all cluster nodes

**Actual behavior:**
apply... Pod not starting

**Additional context / logs:**
0/5 nodes are available: 2 node(s) didn't match Pod's node affinity/selector, 3 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate.
