### ISSUE TITLE
NetworkPolicy is blocking traffic to ingress IP

### ISSUE THREAD

**Issue by ameyp** [k3s-io/k3s#6546]
**Environmental Info:**
K3s Version: v1.24.1+k3s1 (0581808f)

Node(s) CPU architecture, OS, and Version: Linux leader 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 1 on the control plane, 5 agents

**Describe the bug:**
I'm running a Pod with two containers: a VPN container (using [gluetun](https://github.com/qdm12/gluetun)) and another container. The VPN is configured to not tunnel traffic headed for CIDR `192.168.0.0/16`. I'm applying a network policy that denies all egress other than:
- UDP traffic, VPN port, all IPs
- UDP traffic, DNS port, `10.0.0.0/8`
- TCP traffic, HTTPS port, `192.168.99.99/32`

My goal is to allow all external traffic via the VPN, and internal traffic only too `192.168.99.99`, which is the LoadBalancer IP for Traefik running on my cluster as an ingress controller. With this policy applied, VPN traffic works as expected, but any traffic to any ingress is blocked with `connection refused`. If I delete the policy, I'm able to reach all ingresses from the pod.

**Steps To Reproduce:**

- Installed K3s: Using https://github.com/k3s-io/k3s-ansible 

Apply the following YAML:

```
apiVersion: v1
kind: Namespace
metadata:
  name: policy
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: policy-test
  name: policy
  namespace: policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: policy-test
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: 10.0.0.0/8
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
---
apiVersion: v1
kind: Pod
metadata:
  name: policy-test
  namespace: policy
  labels:
    app.kubernetes.io/name: policy-test
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
```

Inside the running pod, execute `wget https://ingress.hostname.cluster.com`

**Expected behavior:**
Get a valid HTTP response

**Actual behavior:**
```
Connecting to ingress.hostname.cluster.com (192.168.99.99:443)
wget: can't connect to remote host (192.168.99.99): Connection refused
```

**Additional context / logs:**
