### ISSUE TITLE
Update to Traefik 18.x breaks Ingress access for setups with TCP and UDP entrypoints

### ISSUE THREAD

**Issue by bvehse** [k3s-io/k3s#6550]
**Environmental Info:**
K3s Version: v1.25.4+k3s1 (0dc63334)

Node(s) CPU architecture, OS, and Version: 
Linux master-1 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
- 3 servers: 1 master, 2 agents
- using https://github.com/rancher/system-upgrade-controller

**Describe the bug:**
Configuring multiple UDP entrypoints for Traefik in addition to the default TCP 80/443 ports initially created separate DaemonSets (`svclb-traefik-*` and `svclb-traefik-udp-*`) and Services (`traefik` and `traefik-udp`) in the namespace `kube-system` in earlier versions of the Traefik Helm Chart.

The recent k3s update included a bump of the Traefik Helm Chart (see https://github.com/k3s-io/k3s/releases/tag/v1.25.4%2Bk3s1). After this update was applied automatically by `System Upgrade Controller` all external access to UDP and TCP ports was lost. This is caused by version 18.x of the Traefik Helm Chart now creating one single LoadBalancer Service using the `MixedProtocolLBService` feature gate (see https://github.com/traefik/traefik-helm-chart#upgrading-from-17x-to-18x) but only deleting the TCP DaemonSet beforehand. As the UDP ports are still blocked by the old deployment, the new pods are in a pending state with the following error:

```
root@master-1:~# kubectl -n kube-system get ds
NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
svclb-traefik-cdc29417       3         3         0       3            0           <none>          3h59m
svclb-traefik-udp-d7e6e84e   3         3         3       3            3           <none>          45h
[other ds ..]

root@master-1:~# kubectl -n kube-system get pods
NAMESPACE              NAME                                                     READY   STATUS             RESTARTS        AGE
kube-system            helm-install-traefik-crd-r6wxl                           0/1     Completed          0               4h4m
kube-system            svclb-traefik-cdc29417-7ks5t                             0/7     Pending            0               4h3m
kube-system            svclb-traefik-cdc29417-xfzwp                             0/7     Pending            0               4h3m
kube-system            svclb-traefik-cdc29417-qdxfn                             0/7     Pending            0               4h3m
kube-system            helm-install-traefik-vlcrt                               0/1     Completed          1               4h4m
kube-system            svclb-traefik-udp-d7e6e84e-8mxqc                         5/5     Running            0               45h
kube-system            svclb-traefik-udp-d7e6e84e-fd7dz                         5/5     Running            0               45h
kube-system            svclb-traefik-udp-d7e6e84e-bgxdd                         5/5     Running            0               45h
kube-system            traefik-bd4c47dc4-skt8b                                  1/1     Running            1 (12m ago)     4h3m
[other pods ..]

kubectl -n kube-system describe pod svclb-traefik-cdc29417-7ks5t
[...]
 Warning  FailedScheduling  15m                  default-scheduler  0/3 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.
```

This can be solved or prevented by setting `service.single` to `false` in Traefik Helm Chart values or by deleting the leftover `svclb-traefik-udp-*` DaemonSet.

I assume that this is only an issue for setups with additional UDP entrypoints configured. Is there something I could have done beforehand to prevent this unexpected downtime or should the the old default behavior with two services be retained during an automatic update? Let me know if I should provide additional information.

In any case: Thanks so much for all the great on work on this project!

**Steps To Reproduce:**
- Installed K3s (master): 
```
curl -sfL https://get.k3s.io | sh -s - server \
--disable-cloud-controller \
--write-kubeconfig-mode=644 \
--disable local-storage \
--node-name="$(hostname -f)" \
--cluster-cidr="10.244.0.0/16" \
--kube-proxy-arg="metrics-bind-address=0.0.0.0" \
--kubelet-arg="cloud-provider=external" \
--token="<secret_token>" \
--tls-san="$(hostname -I | awk '{print $2}')" \
--flannel-iface=ens10
```

- Setup System Upgrade Controller server and agent plan:

```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
```

- Configured multiple UDP entrypoints for traefik in `/var/lib/rancher/k3s/server/manifests/traefik-config.yaml`:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
    ports:
      web:
        redirectTo: websecure
      exampleudp1:
        port: 1234
        expose: true
        exposedPort: 1234
        protocol: UDP
      exampleudp2:
        port: 2345
        expose: true
        exposedPort: 2345
        protocol: UDP
      [additional UDP ports ..]
    additionalArguments:
      - "--entryPoints.exampleudp1 address=:1234/udp"
      - "--entryPoints.exampleudp2.address=:2345/udp"
      [additional UDP entrypoints ..]
```

**Expected behavior:**
External access via Traefik Ingress to TCP and UDP ports remains possible after automatic update of Traefik Helm Chart.

**Actual behavior:**
External access via Traefik Ingress to TCP and UDP ports is **not** possible after automatic update of Traefik Helm Chart.
