### ISSUE TITLE
Unexpected server behaviour with `--disable-cloud-controller` flag

### ISSUE THREAD

**Issue by c0depwn** [k3s-io/k3s#6554]
**Environmental Info:**
K3s Version:  
- 1.25.4+k3s1  
- 1.25.3+k3s1

Node(s) CPU architecture, OS, and Version: 

Kernel: 5.10.96-flatcar
OS: Flatcar  3033.2.2

```
core@control-plane-637e8da30f2be ~ $ uname -a
Linux control-plane-637e8da30f2be 5.10.96-flatcar #1 SMP Thu Feb 3 20:00:07 -00 2022 x86_64 Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS) GenuineIntel GNU/Linux
```

Cluster Configuration: 1 master / 3 agents

I use a `docker-compose.yaml` file to manage k3s on each instance, the following is the master configuration:
Notice that some flags are omitted.
```
version: '3'

services:
  k3s:
    container_name: k3s
    image: rancher/k3s:v1.25.4-k3s1
    command:
      - 'server'
      - '--disable-cloud-controller'
      - '--disable=local-storage'
      - '--node-taint=node-role.kubernetes.io/master=true:NoSchedule'
      - '--tls-san=<OMITTED>'
      - '--kube-scheduler-arg=config=/var/lib/scheduler/kube-scheduler.yaml'
      - '--kubelet-arg=cloud-provider=external'
      - '--kubelet-arg=container-log-max-files=5'
      - '--kubelet-arg=container-log-max-size=10Mi'
    restart: on-failure
    network_mode: host
    privileged: true
```

**Describe the bug:**

K3s seems to ignore `--disable-cloud-controller` unless `--disable=servicelb` is also supplied. I came across this issue because I use a custom CCM and when running the cluster with v1.25.3 or v1.25.4 the custom CCM reports the following logs:
```
cloud-controller-manager
I1124 09:28:48.381554 1 serving.go:313] Generated self-signed cert in-memory
cloud-controller-manager
failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use
```

This seemed strange at first but after some more investigation I found that on the master node (host) the port 10258 (official ccm port) is already bound:
```
control-plane-637e8da30f2be /opt # sudo lsof -i -P -n | grep LISTEN | grep 10258
exe       4278            root  305u  IPv4  38520      0t0  TCP 127.0.0.1:10258 (LISTEN)
```

The process which binds these ports is the k3s server:
```
control-plane-637e8da30f2be /opt # ls -l /proc/4278/exe
lrwxrwxrwx. 1 root root 0 Nov 24 12:12 /proc/4278/exe -> /bin/k3s
```
The logs of `k3s` confirm that the port was initially bound:
```
control-plane-637e8da30f2be /opt # docker logs k3s 2>&1| grep 10258
...(omitted)...
I1124 12:09:41.089202      38 secure_serving.go:210] Serving securely on 127.0.0.1:10258
```

After adding the `--disable=servicelb` the CCM starts working as expected and there are no port binding issues or errors from k3s or the CCM itself. This lead me to believe that there might be some issue regarding the processing or honoring of the supplied flags. After some digging in the `k3s` code I came across the following commit: https://github.com/k3s-io/k3s/commit/d963cb2f707efcbd94b42c888214c1719484b20e. Especially the following changes seem very suspicious: (inside https://github.com/k3s-io/k3s/commit/d963cb2f707efcbd94b42c888214c1719484b20e#diff-750227e174e9fe230c0aede7c189127dff9b587b03449ecf875002d740dd59e7R365)

Before:
```
if serverConfig.ControlConfig.DisableCCM {
    serverConfig.ControlConfig.Skips["ccm"] = true
    serverConfig.ControlConfig.Disables["ccm"] = true
}
```

After:
```
if serverConfig.ControlConfig.DisableCCM && serverConfig.ControlConfig.DisableServiceLB {
    serverConfig.ControlConfig.Skips["ccm"] = true
    serverConfig.ControlConfig.Disables["ccm"] = true
}
```
The versions effected by this bug, as seen in the commit, would be:
[v1.25.4-rc4+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.4-rc4%2Bk3s1) [v1.25.4-rc3+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.4-rc3%2Bk3s1) [v1.25.4-rc2+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.4-rc2%2Bk3s1) [v1.25.4-rc1+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.4-rc1%2Bk3s1) [v1.25.3+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.3%2Bk3s1) [v1.25.3-rc4+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.3-rc4%2Bk3s1) [v1.25.3-rc3+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.3-rc3%2Bk3s1) [v1.25.3-rc2+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.3-rc2%2Bk3s1) [v1.25.3-rc1+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.3-rc1%2Bk3s1)

The behaviour was as expected when using the exact same configuration on `v1.25.2`, no port binding issues, no CCM issues.

**Steps To Reproduce:**

- Installed K3s: 
- start k3s server with the following flags:  `--disable-cloud-controller`, `--kubelet-arg=cloud-provider=external`
- deploy any out-of-tree CCM
- the port bind error should appear in your CCM pod logs
- stop k3s
- add the following flag to the k3s server: '--disable=servicelb'
- restart k3s
- re-create the CCM pod
- CCM starts working without any port related issues

**Expected behavior:**
The flags:  `--disable-cloud-controller` and '--disable=servicelb' should be independent and disabling the `servicelb` should not influence the desired CCM behaviour.

**Actual behavior:**
Passing  `--disable-cloud-controller` without '--disable=servicelb' will not allows a custom/external CCM to bind the port as the internal CCM has already taken the same port.

**Additional context / logs:**
see description
