### ISSUE TITLE
[release-1.23] Backport changes from master for 2022-12 release

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6601]
Backport fixes for the following issues:
* https://github.com/k3s-io/k3s/issues/3117
* https://github.com/k3s-io/k3s/issues/6467
* https://github.com/traefik/traefik-helm-chart/issues/719
* https://github.com/k3s-io/k3s/issues/6487
* https://github.com/k3s-io/k3s/issues/6488
* https://github.com/k3s-io/k3s/issues/6499
* https://github.com/k3s-io/k3s/issues/3117
* https://github.com/k3s-io/k3s/issues/6554
* https://github.com/k3s-io/k3s/issues/5056
* https://github.com/k3s-io/k3s/issues/6027

**Comment by VestigeJ** [comment]
Environment Details
VERSION=v1.23.15-rc1+k3s1

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*
```
Linux 4.18.0-193.el8.x86_64 x86_64 GNU/Linux Red Hat Enterprise Linux 8.7 (Ootpa)
``` 

*Cluster Configuration:*
```
NAME                                         STATUS   ROLES                       AGE     VERSION
ip-7-33-33-7.us-east-2.compute.internal   Ready    control-plane,etcd,master   65m     v1.23.15-rc1+k3s1
ip-7-33-31-3.us-east-2.compute.internal   Ready    <none>                      4m51s   v1.23.15-rc1+k3s1 
```

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: epicsnow
protect-kernel-defaults: true
cluster-init: true
prefer-bundled-bin: true
```

<details>
<summmary><h4>STEPS</h4></summary>

```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \nkernel.keys.root_maxbytes=25000000" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo sysctl -p /etc/sysctl.d/90-kubelet.conf
$ iptables -V
$ VERSION=v1.23.15-rc1+k3s1
$ sudo INSTALL_K3S_VERSION=$VERSION INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ sudo iptables -L | wc -l
$ sudo ps faux | grep 'k3s server' ** or grep 'k3s agent' respectively**
$ sudo cat /proc/17791/environ | tr '\0' '\n'
```

**Results:**

**Additional context / logs:**

** before adding prefer-bundled-bin:true to config.yaml server node**
config.yaml
```
write-kubeconfig-mode: 644
debug: true
token: epicsnow
protect-kernel-defaults: true
cluster-init: true
```

$ sudo cat /proc/45522/environ | tr '\0' '\n'
```
PATH=/var/lib/rancher/k3s/data/f8e42a76a3d19563f39821f14fd09f0f7205cd72f7f8d8828d86e01c8545d1bb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/var/lib/rancher/k3s/data/f8e42a76a3d19563f39821f14fd09f0f7205cd72f7f8d8828d86e01c8545d1bb/bin/aux
NOTIFY_SOCKET=/run/systemd/notify
INVOCATION_ID=17d00a2b72574ee3a325a2f1f915015b
JOURNAL_STREAM=9:247610
RES_OPTIONS= 
K3S_DATA_DIR=/var/lib/rancher/k3s/data/f8e42a76a3d19563f39821f14fd09f0f7205cd72f7f8d8828d86e01c8545d1bb
```
** agent node **
agent config.yaml with flag
```
token: epicsnow
server: https://8.222.222.8:6443
protect-kernel-defaults: true
```

$ sudo cat /proc/19545/environ | tr '\0' '\n'
```
PATH=/var/lib/rancher/k3s/data/f8e42a76a3d19563f39821f14fd09f0f7205cd72f7f8d8828d86e01c8545d1bb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/var/lib/rancher/k3s/data/f8e42a76a3d19563f39821f14fd09f0f7205cd72f7f8d8828d86e01c8545d1bb/bin/aux
NOTIFY_SOCKET=/run/systemd/notify
INVOCATION_ID=35270be0d8d74403964dbdb2b6cb990d
JOURNAL_STREAM=9:259946
RES_OPTIONS= 
K3S_DATA_DIR=/var/lib/rancher/k3s/data/f8e42a76a3d19563f39821f14fd09f0f7205cd72f7f8d8828d86e01c8545d1bb
```

** after adding prefer-bundled-bin:true to config.yaml **
$ sudo cat /proc/17791/environ | tr '\0' '\n' **note bin/aux prefixing rest of PATH**
```
PATH=/var/lib/rancher/k3s/data/f8e42a76a3d19563f39821f14fd09f0f7205cd72f7f8d8828d86e01c8545d1bb/bin:/var/lib/rancher/k3s/data/f8e42a76a3d19563f39821f14fd09f0f7205cd72f7f8d8828d86e01c8545d1bb/bin/aux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
NOTIFY_SOCKET=/run/systemd/notify
INVOCATION_ID=eff595740f394342a693e836741ef46d
JOURNAL_STREAM=9:128555
RES_OPTIONS= 
K3S_DATA_DIR=/var/lib/rancher/k3s/data/f8e42a76a3d19563f39821f14fd09f0f7205cd72f7f8d8828d86e01c8545d1bb
```

agent config.yaml with flag
```
token: epicsnow
server: https://8.222.222.8:6443
protect-kernel-defaults: true
prefer-bundled-bin: true
```


</details>

**Comment by VestigeJ** [comment]
$ helm ls -A
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
traefik         kube-system     1               2022-12-12 22:50:03.262861769 +0000 UTC deployed        traefik-20.3.1+up20.3.0         v2.9.4     
traefik-crd     kube-system     1               2022-12-12 22:50:00.58925587 +0000 UTC  deployed        traefik-crd-20.3.1+up20.3.0     v2.9.4  
```

$ sudo k3s ctr i ls | grep 'traefik'
```
docker.io/rancher/mirrored-library-traefik:2.9.4                                                                   application/vnd.docker.distribution.manifest.list.v2+json sha256:0842af6afcdf4305d17e862bad4eaf379d0817c987eedabeaff334e2273459c1 36.9 MiB  linux/amd64,linux/arm/v6,linux/arm64/v8,linux/s390x            io.cri-containerd.image=managed 
docker.io/rancher/mirrored-library-traefik@sha256:0842af6afcdf4305d17e862bad4eaf379d0817c987eedabeaff334e2273459c1 application/vnd.docker.distribution.manifest.list.v2+json sha256:0842af6afcdf4305d17e862bad4eaf379d0817c987eedabeaff334e2273459c1 36.9 MiB  linux/amd64,linux/arm/v6,linux/arm64/v8,linux/s390x            io.cri-containerd.image=managed 
```

$ sudo cat /var/lib/rancher/k3s/server/manifests/traefik.yaml
```
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-crd-20.3.1+up20.3.0.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-20.3.1+up20.3.0.tgz
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      name: "rancher/mirrored-library-traefik"
      tag: "2.9.4"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      ipFamilyPolicy: "PreferDualStack"
```
