### ISSUE TITLE
Service LB seems redirecting traffic to other nodes, even externalTrafficPolicy is Local

### ISSUE THREAD

**Issue by rinsuki** [k3s-io/k3s#6633]
**Environmental Info:**
K3s Version: 
```
k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3
```

Node(s) CPU architecture, OS, and Version: 

* `Linux k3sserver 5.10.0-19-arm64 #1 SMP Debian 5.10.149-2 (2022-10-21) aarch64 GNU/Linux`
* `Linux k3sagent 5.10.0-19-arm64 #1 SMP Debian 5.10.149-2 (2022-10-21) aarch64 GNU/Linux`

both machine running Debian 11.

Cluster Configuration:
* Server: 192.168.222.131 `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --disable local-storage" sh -s -`
* Agent: 192.168.222.132 `curl -sfL https://get.k3s.io | K3S_URL=https://192.168.222.131:6443 K3S_TOKEN=<snip> INSTALL_K3S_EXEC="agent" sh -s -`

**Describe the bug:**

Service LB seems redirecting traffic to other nodes, even `Service`'s `externalTrafficPolicy` is `Local`.

I think, If target pod is not running on local, connection should be fail instead of redirect to another node.

Note, I'm new to Kubernetes/k3s, so probably missing something...

**Steps To Reproduce:**
- Installed K3s: please see "Cluster Configuration:" section
- Apply this yaml:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: front-nginx

---
apiVersion: v1
kind: Service
metadata:
  namespace: front-nginx
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      appProtocol: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: front-nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.2-alpine
          ports:
            - containerPort: 80
```
- Access 80/tcp of both nodes, like `curl http://192.168.222.131; curl http://192.168.222.132`

**Expected behavior:**

since nginx only runs on one pod, one of requests should fail.

**Actual behavior:**

both of requests will success. one of request are preserves source IP, but other one is not preserving source IP.
```
10.42.0.4 - - [10/Dec/2022:21:35:19 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.85.0" "-"
192.168.222.1 - - [10/Dec/2022:21:35:28 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.85.0" "-"
```

**Additional context / logs:**

**Comment by brandond** [comment]
ServiceLB does not support ExternalServicePolicy. As described in the docs, the service will be exposed on all nodes with the requested ports available.

**Comment by brandond** [comment]
I took a quick shot at this and it is actually not all that easy, as ExternalTrafficPolicy has a fair bit of overhead on the LB side with regards to watching to ensure that the svclb pods stay in sync with ready pods. Right now the pods are deployed to all available nodes without regards for the service state. If we wanted to do this properly we would have to do a bunch more work to watch EndpointSlices and manually schedule pods onto nodes based on endpoint readiness. This is possible but non-trivial.

**Comment by brandond** [comment]
@rinsuki  if you are up for it, try installing K3s with `INSTALL_K3S_COMMIT=cc544c0e9b8e7e5305cc670f621b3f7521d67c8b` and see if the behavior is closer to what you were hoping for.

**Comment by VestigeJ** [comment]
##Environment Details
Reproduced with VERSION=v1.26.1+k3s1
Validated with COMMIT=be7f751863df7296300675484a87f6de07f1f5f5

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

```
Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux 
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
```
 
*Cluster Configuration:*

```
NAME               STATUS   ROLES                       AGE    VERSION
ip-SERVER          Ready    control-plane,etcd,master   9m2s   v1.26.1+k3s1
ip-AGENT           Ready    <none>                      8m8s   v1.26.1+k3s1 
```

*Config.yaml:*

```
write-kubeconfig-mode: 644
debug: true
token: garlicbreadisgood
selinux: true
protect-kernel-defaults: true
cluster-init: true
disable: 
  - traefik
  - local-storage
```

<details>
<summmary><h4> Reproduced using latest v1.26.1+k3s1 release </h4></summary>


```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/60-rke2-cis.conf
$ sudo cp 60-rke2-cis.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ conf //write config.yaml values as above
$ VERSION=v1.26.1+k3s1
$ sudo INSTALL_K3S_VERSION=$VERSION INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ set_kubefig //KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ kgn //kubectl get nodes
$ kgp -A -o wide --sort-by="{.spec.nodeName}"
$ vim issue.yaml //paste included file below
$ k apply -f issue.yaml // kubectl apply
$ w2 kgp -A -o wide --sort-by="{.spec.nodeName}" //watch -n 2 kubectl get pods -A -o wide --sort-by="{.spec.nodeName}"
```

**Results:**
Curling both endpoints on both nodes returns despite 

$ kgp -A -o wide --sort-by="{.spec.nodeName}"
```
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE   IP          NODE               NOMINATED NODE   READINESS GATES
kube-system   coredns-5c6b6c5476-79wjz          1/1     Running   0          11m   10.42.0.3   ip-SERVER          <none>           <none>
kube-system   metrics-server-7b67f64457-bmjph   1/1     Running   0          11m   10.42.0.2   ip-SERVER          <none>           <none>
kube-system   svclb-nginx-224bca8b-d54pl        1/1     Running   0          10m   10.42.0.4   ip-SERVER          <none>           <none>
front-nginx   nginx-6f985f7658-7b4tn            1/1     Running   0          10m   10.42.1.3   ip-AGENT           <none>           <none>
kube-system   svclb-nginx-224bca8b-vfdg8        1/1     Running   0          10m   10.42.1.2   ip-AGENT           <none>           <none>
```


$ curl http://SERVER_IP //curling server node
```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

$ curl http://AGENT_IP //curling agent node 
```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

$ cat issue.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  name: front-nginx

---
apiVersion: v1
kind: Service
metadata:
  namespace: front-nginx
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      appProtocol: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: front-nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.2-alpine
          ports:
            - containerPort: 80
```
</details>

<details>
<summmary><h4> Validated successfully with latest commit on branch </h4></summary> 
## Validation Steps

used existing cluster configuration from the reproduction
 
```
$ k delete -f issue.yaml //kubectl delete the previously deployed manifest
$ COMMIT=be7f751863df7296300675484a87f6de07f1f5f5
$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=agent ./install-k3s.sh
$ kgn //kubectl get nodes
$ kgp -A -o wide --sort-by="{.spec.nodeName}" //ensure cluster is up to date and waiting for re-applying the manifest
$ k apply -f issue.yaml //kubectl apply
$ kgp -A -o wide --sort-by="{.spec.nodeName}" //observe pods are Running before issue-ing curl commands from a third console
``` 
 
**Additional context / logs:**

$ kgn 
```
NAME               STATUS   ROLES                       AGE   VERSION
ip-SERVER          Ready    control-plane,etcd,master   31m   v1.26.1+k3s-be7f7518
ip-AGENT           Ready    <none>                      30m   v1.26.1+k3s-be7f7518
```

$ kubectl get pods -A -o wide --sort-by={.spec.nodeName}                                          
```
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE     IP          NODE               NOMINATED NODE   READINESS GATES
kube-system   coredns-5c6b6c5476-79wjz          1/1     Running   0          30m     10.42.0.3   ip-SERVER               <none>           <none>
kube-system   metrics-server-7b67f64457-bmjph   1/1     Running   0          30m     10.42.0.2   ip-SERVER               <none>           <none>
kube-system   svclb-nginx-f4abeab4-z4nz4        1/1     Running   0          4m28s   10.42.0.5   ip-SERVER       <none>           <none>
front-nginx   nginx-6f985f7658-srfld            1/1     Running   0          4m28s   10.42.1.5   ip-AGENT         <none>           <none>
kube-system   svclb-nginx-f4abeab4-dsb8j        1/1     Running   0          4m28s   10.42.1.4   ip-AGENT         <none>           <none>
```

$ curl http://SERVER_IP
```
curl: (28) Failed to connect to SERVER_IP port 80 after 8103 ms: Operation timed out
```

$ curl http://AGENT_IP 
```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

</details>
