### ISSUE TITLE
Getting the error message "Unauthorized" after creating a new certified user

### ISSUE THREAD

**Issue by Hpd0ger** [k3s-io/k3s#6672]
**Environmental Info:**
K3s Version: 
```
k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3
```
Node(s) CPU architecture, OS, and Version: 
```
Linux k3s-master 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1server and 2 agents

**Describe the bug:**
I created a common user according to the method provided in the [document](https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user), and exported the `kubeconfig` configuration file. When I use `kubectl get pods --kubeconfig=myconfig.conf` to operate the cluster, it prompts an error error: `You must be logged in to the server (Unauthorized)`

**Steps To Reproduce:**
Here are steps for me to create the user:
0x01：create pki secret and csr
```
openssl genrsa -out myuser.key 2048
openssl req -new -key myuser.key -out myuser.csr
```
0x02：create `CertificateSigningRequest` Object yaml
```yaml
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: guest
spec:
  groups:
  - system:authenticated
  #  request is from cat myuser.csr | base64 | tr -d "\n"
  request: xxxxx 
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 108000  # one day
  usages:
  - client auth
```
then , using kubectl to apply for it
```
[root@k3s-master roles]# kubectl apply -f certificate_guest.yaml 
certificatesigningrequest.certificates.k8s.io/guest created
[root@k3s-master roles]# kubectl certificate approve guest
certificatesigningrequest.certificates.k8s.io/guest approved
```

0x03：export the certificate from csr created for user `guest`
```
kubectl get csr guest -o jsonpath='{.status.certificate}'| base64 -d > myuser.crt
```

0x04：make a `kubeconfig `file for this certificate 
```
[root@k3s-master roles]# kubectl config set-credentials guest --client-certificate=myuser.crt --client-key=myuser.key --embed-certs=true --kubeconfig=guest.conf
User "guest" set.
[root@k3s-master roles]# kubectl config set-cluster default --server=https://127.0.0.1:6443 --certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --embed-certs=true --kubeconfig=guest.conf
Cluster "default" set.
[root@k3s-master roles]# kubectl config set-context kubernetes --cluster=default --user=guest --kubeconfig=guest.conf 
Context "kubernetes" modified.
[root@k3s-master roles]# kubectl config use-context kubernetes  --kubeconfig=guest.conf
Switched to context "kubernetes".
```

0x05：use the `kubeconfig` to interact with the Kubernetest Server and got error message like that
```
[root@k3s-master roles]# kubectl get pods --kubeconfig guest.conf 
error: You must be logged in to the server (Unauthorized)
```

**Expected behavior:**
Get pods information or read pod permission error, not this authentication error

**Actual behavior:**
error: You must be logged in to the server (Unauthorized)

**Additional context / logs:**
I don't know what other logs to provide
