### ISSUE TITLE
traefik dashboard 404

### ISSUE THREAD

**Issue by PahaCore** [k3s-io/k3s#6677]
traefik dashboard does not work according to the instructions in k3s (Kubernetes) - error 404, I read on the Internet this is a massive problem, maybe it's worth making the instructions better?

links to instructions and procedure :

1 - curl -sfL https://get.k3s.io | sh -
2 - https://doc.traefik.io/traefik/operations/dashboard/#dashboard-router-rule

k3s kubectl apply -f dashboard.yaml

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`domains.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService

3 - domains.com = 404

I tried a lot of options that I found on the web - it didn't work out
therefore, I wrote here the simplest and described instructions and it also does not work

**Comment by cctomato** [comment]
After install K3S,  Traefik automatically creates an IngressRoute resource to access Traefik DashBoard.
You can edit the resource named traefik-dashboard.
````bash
kubectl edit ingressroute/traefik-dashboard -oyaml -n kube-system
````
Then modify the content in the spec, as shown below
````yaml
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`domains.com`)
    services:
    - kind: TraefikService
      name: api@internal
````
Finally, save it and exit editing. You can access it through domains.com
