### ISSUE TITLE
Cannot open TCP and UDP ports on same port number

### ISSUE THREAD

**Issue by cskwrd** [k3s-io/k3s#6757]
**Environmental Info:**
K3s Version: 
```
k3s version v1.25.4+k3s1 (0dc63334)
go version go1.19.3
```

Node(s) CPU architecture, OS, and Version: 
`Linux server1 6.1.4-1-default #1 SMP PREEMPT_DYNAMIC Mon Jan  9 11:00:31 UTC 2023 (4b9b43c) x86_64 x86_64 x86_64 GNU/Linux`
`Linux agent1 6.1.4-1-default #1 SMP PREEMPT_DYNAMIC Mon Jan  9 11:00:31 UTC 2023 (4b9b43c) x86_64 x86_64 x86_64 GNU/Linux`
`Linux agent2 6.1.0-1-default #1 SMP PREEMPT_DYNAMIC Wed Dec 21 16:29:21 UTC 2022 (ab10a11) x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
1 server, 2 agents

**Describe the bug:**
Trying to open a UDP port and TCP on the same port number doesn't work. It appears that only the TCP port is actually open.

**Steps To Reproduce:**

- Installed K3s: Followed the quickstart guide, https://docs.k3s.io/quick-start
- After install SFTP following as `/var/lib/rancher/k3s/server/manifests/traefik-customizations.yaml`
```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      general:
        level: INFO
      access:
        enabled: true
    ports:
      random-tcp:
        port: 8999
        expose: true
        exposedPort: 8999
        protocol: TCP
      random-udp:
        port: 8999
        expose: true
        exposedPort: 8999
        protocol: UDP

```
- Finally `kubectl apply -f ./port-test.yaml`:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    owner-email: tcp@example.com
  labels:
    istio-injection: enabled
  name: whoami-tcp
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    owner-email: udp@example.com
  labels:
    istio-injection: enabled
  name: whoami-udp
---
apiVersion: v1
kind: Service
metadata:
  name: svc-whoami-tcp
  namespace: whoami-tcp
spec:
  ports:
  - port: 8080
  selector:
    app: app-whoami-tcp
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: svc-whoami-udp
  namespace: whoami-udp
spec:
  ports:
  - port: 8080
  selector:
    app: app-whoami-udp
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-whoami-tcp
    version: v1
  name: whoami-tcp-v1
  namespace: whoami-tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-whoami-tcp
      version: v1
  template:
    metadata:
      labels:
        app: app-whoami-tcp
        version: v1
    spec:
      containers:
      - image: traefik/whoamitcp:latest
        imagePullPolicy: IfNotPresent
        name: whoamitcp
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-whoami-udp
    version: v1
  name: whoami-udp-v1
  namespace: whoami-udp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-whoami-udp
      version: v1
  template:
    metadata:
      labels:
        app: app-whoami-udp
        version: v1
    spec:
      containers:
      - image: traefik/whoamiudp:latest
        imagePullPolicy: IfNotPresent
        name: whoamiudp
        ports:
        - containerPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroute-tcp-whoami
  namespace: whoami-tcp
spec:
  entryPoints:
  - random-tcp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: svc-whoami-tcp
      port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: ingressroute-udp-whoami
  namespace: whoami-udp
spec:
  entryPoints:
  - random-udp
  routes:
  - services:
    - name: svc-whoami-udp
      port: 8080

```

**Expected behavior:**
Both the TCP and UDP pods should be reachable at `server1:8999`

**Actual behavior:**
Only the TCP port works.

**Additional context / logs:**
`kubectl` commands used remotely from Windows 10.
