### ISSUE TITLE
[release-1.25] Fail-closed webhooks blocking resource creates/writes can cause k3s to be unstartable

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6820]
Backport:
*  #6815

**Comment by mdrahman-suse** [comment]
### Validated on release-1.25 branch with commit 97100de8d06117ecff5f94eeb7a38e8cbd073fec
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-45-8 5.15.0-1026-aws #30-Ubuntu SMP Wed Nov 23 14:15:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.1 LTS"
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
token: summer
cluster-init: true
```
 
*Additional files*

- webhook.yaml
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-mutating-webhook-config
webhooks:
  - name: example.mutating.webhook.com
    clientConfig:
      service:
        namespace: webhook
        name: example-mutating-webhook-svc
        path: /mutate
    admissionReviewVersions:
      - v1
      - v1beta1
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods", "namespaces", "serviceaccounts" ]
    failurePolicy: Fail
    sideEffects: None
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
3. Check cluster is up and running
4. Apply webhook.yaml
5. Kill k3s: `sudo k3s-killall.sh`
6. Restart k3s service: `sudo systemctl restart k3s`
7. Check service status: `sudo systemctl status k3s`
8. Check for errors in log
 
**Replication Results:**
- k3s version used for replication:

```
k3s version v1.25.6+k3s1 (9176e03c)
go version go1.19.5
```
 

- Observed k3s is stuck in activating with failure
```
k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2023-02-16 19:40:03 UTC; 2s ago
       Docs: https://k3s.io
    Process: 4438 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 4440 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 4441 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
    Process: 4442 ExecStart=/usr/local/bin/k3s server (code=exited, status=1/FAILURE)
   Main PID: 4442 (code=exited, status=1/FAILURE)
```
- Observed error in log
```
Feb 16 19:40:03 ip-172-31-45-8 k3s[4442]: W0216 19:40:03.702040    4442 dispatcher.go:195] Failed calling webhook, failing closed example.mutating.webhook.com: failed calling webhook "example.mutating.webhook.com": failed to call webhook: Post "https://example-mutating-webhook-svc.webhook.svc:443/mutate?timeout=10s": service "example-mutating-webhook-svc" not found
Feb 16 19:40:03 ip-172-31-45-8 k3s[4442]: time="2023-02-16T19:40:03Z" level=fatal msg="Failed to register service-controller handlers: Internal error occurred: failed calling webhook \"example.mutating.webhook.com\": failed to call webhook: Post \"https://example-mutating-webhook-svc.webhook.svc:443/mutate?timeout=10s\": service \"example-mutating-webhook-svc\" not found"
```
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.25.6+k3s-97100de8 (97100de8)
go version go1.19.5
```
 

- Observed k3s is activated successfully
- Observed NO errors in logs related to webhook failure
