### ISSUE TITLE
[release-1.24] Service LB seems redirecting traffic to other nodes, even externalTrafficPolicy is Local

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6902]
Backport:
*  #6633

**Comment by bguzman-3pillar** [comment]
### Validated on 77dbe648
```
$ k3s -v
k3s version v1.24.10+k3s-77dbe648 (77dbe648)
go version go1.19.5
```
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
```
 
*Cluster Configuration:*

```
1 server, 1 agent
```
 
*Config.yaml:*

```
$ cat config.yaml 
write-kubeconfig-mode: 644
debug: true
token: puravida
cluster-init: true
disable: 
  - traefik
  - local-storage
```
 
*Additional files*

```
apiVersion: v1
kind: Namespace
metadata:
  name: front-nginx

---
apiVersion: v1
kind: Service
metadata:
  namespace: front-nginx
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      appProtocol: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: front-nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.2-alpine
          ports:
            - containerPort: 80
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s and join the agent node
3. Ensure cluster is up then apply the yaml
4. Ensure pod are running 
 
 
 
**Validation Results:**

```
$ kubectl get nodes
NAME               STATUS   ROLES                       AGE   VERSION
ip-172-31-36-177   Ready    control-plane,etcd,master   19m   v1.24.10+k3s-77dbe648
ip-172-31-40-199   Ready    <none>                      12m   v1.24.10+k3s-77dbe648

$ kubectl get pod -A -o wide
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE   IP          NODE               NOMINATED NODE   READINESS GATES
front-nginx   nginx-7986788845-22wh6            1/1     Running   0          11m   10.42.1.3   ip-<AGENT>   <none>           <none>
kube-system   coredns-7b5bbc6644-pzwdp          1/1     Running   0          19m   10.42.0.3   ip-<SERVER>   <none>           <none>
kube-system   metrics-server-667586758d-hnwrr   1/1     Running   0          19m   10.42.0.2   ip-<SERVER>   <none>           <none>
kube-system   svclb-nginx-72a92347-mhnwn        1/1     Running   0          11m   10.42.1.2   ip-<AGENT>   <none>           <none>
kube-system   svclb-nginx-72a92347-r4jvj        1/1     Running   0          11m   10.42.0.4   ip-<SERVER>   <none>           <none>
```
 
```
Curl server

$ curl http://172.31.36.177
curl: (7) Failed to connect to 172.31.36.177 port 80 after 0 ms: Connection refused


Curl Agent
$ curl http://172.31.40.199
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

```

```
```
