### ISSUE TITLE
[release-1.23] Service LB seems redirecting traffic to other nodes, even externalTrafficPolicy is Local

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6903]
Backport:
*  #6633

**Comment by rancher-max** [comment]
## Validated on `release-1.23` branch with commit https://github.com/k3s-io/k3s/commit/0f7514e08f5e1b21f0caa7dc6bfd1c91456b2ced
 
### Environment Details

 
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
$ uname -a && cat /etc/os-release
Linux ip-172-31-8-206 5.15.0-1028-aws #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
 
*Cluster Configuration:*

```
1 server, 1 agent
```
 
*Config.yaml:*

```yaml
# server node
write-kubeconfig-mode: 644
disable:
  - traefik
  - local-storage
token: test
```
```yaml
# agent node
sever: https://serverIP:6443
token: test
```
 
*Additional files*

```yaml
# test.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: front-nginx

---
apiVersion: v1
kind: Service
metadata:
  namespace: front-nginx
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      appProtocol: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: front-nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.2-alpine
          ports:
            - containerPort: 80
```
 
### Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
3. Apply test.yaml: `kubectl apply -f test.yaml`
4. Access 80/tcp on both node ips:
```
$ curl 172.31.10.98
$ curl 172.31.8.206
```
 
 
### **Replication Results:**
- k3s version used for replication:

```
$ k3s -v
k3s version v1.23.16+k3s1 (64b0feeb)
go version go1.19.5
```
 
- Both nodes returned a 200 result and the nginx default page
- Querying the service confirmed that both nodes are configured as part of it:
```
$ k get pods,svc -n front-nginx -o wide
NAME                        READY   STATUS    RESTARTS   AGE     IP          NODE              NOMINATED NODE   READINESS GATES
pod/nginx-78bd9f5bc-4x2sk   1/1     Running   0          5m44s   10.42.1.2   ip-172-31-9-158   <none>           <none>

NAME            TYPE           CLUSTER-IP      EXTERNAL-IP                  PORT(S)        AGE     SELECTOR
service/nginx   LoadBalancer   10.43.132.253   172.31.14.128,172.31.9.158   80:32162/TCP   5m44s   app=nginx
```
 
 
### **Validation Results:**
- k3s version used for validation:

```
$ k3s -v
k3s version v1.23.16+k3s-0f7514e0 (0f7514e0)
go version go1.19.5
```
 
- Only one node is present within the service definition:
```
$ k get pods,svc -n front-nginx -o wide
NAME                        READY   STATUS    RESTARTS   AGE     IP          NODE              NOMINATED NODE   READINESS GATES
pod/nginx-78bd9f5bc-g6kg7   1/1     Running   0          6m42s   10.42.1.2   ip-172-31-8-206   <none>           <none>

NAME            TYPE           CLUSTER-IP   EXTERNAL-IP    PORT(S)        AGE     SELECTOR
service/nginx   LoadBalancer   10.43.4.25   172.31.8.206   80:32285/TCP   6m42s   app=nginx
```
- Accessing 80/tcp only returned a successful result on the node where the pod is running, as expected:
```
$ curl 172.31.10.98
curl: (7) Failed to connect to 172.31.10.98 port 80 after 0 ms: Connection refused

$ curl 172.31.8.206
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
