### ISSUE TITLE
Since v1.22.10-k3s1 and v1.23.7-k3s1 is not possible deploy Traefik with own HelmChartConfig

### ISSUE THREAD

**Issue by piotrminkina** [k3s-io/k3s#6928]
**Environmental Info:**
K3s Version: 
k3s version v1.22.10+k3s1 (b004f4d5)
go version go1.16.10

K3d Version:
k3d version v5.3.0
k3s version v1.22.6-k3s1 (default)

Docker Version:
```
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:37 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Node(s) CPU architecture, OS, and Version: 
Linux awa1b1421 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
```yaml
---
kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: k3s-local
servers: 1
agents: 2
kubeAPI:
  hostIP: 127.0.0.1
  hostPort: '6443'
#image: rancher/k3s:v1.21.4-k3s1 # works
#image: rancher/k3s:v1.21.14-k3s1 # works
#image: rancher/k3s:v1.22.2-k3s2 # works
#image: rancher/k3s:v1.22.5-k3s2 # works
#image: rancher/k3s:v1.22.7-k3s1 # works
#image: rancher/k3s:v1.22.8-k3s1 # works
#image: rancher/k3s:v1.22.9-k3s1 # works
image: rancher/k3s:v1.22.10-k3s1 # NOT works (logs attached from this version)
#image: rancher/k3s:v1.22.17-k3s1 # NOT works
#image: rancher/k3s:v1.23.1-k3s2 # works
#image: rancher/k3s:v1.23.5-k3s1 # works
#image: rancher/k3s:v1.23.6-k3s1 # works
#image: rancher/k3s:v1.23.7-k3s1 # NOT works
#image: rancher/k3s:v1.23.8-k3s2 # NOT works
#image: rancher/k3s:v1.23.16-k3s1 # NOT works
#image: rancher/k3s:v1.24.1-k3s1 # NOT works
#image: rancher/k3s:v1.24.10-k3s1 # NOT works
#image: rancher/k3s:v1.25.2-k3s1 # NOT works
#image: rancher/k3s:v1.25.6-k3s1 # NOT works
#image: rancher/k3s:v1.26.1-k3s1 # NOT works
volumes:
  # Absolute path to the ./manifests/ directory in the project root directory (${K3D_PROJECT_DIR})
  - volume: "${K3D_PROJECT_DIR}/manifests/:/var/lib/rancher/k3s/server/manifests/k3s-local/"
    nodeFilters:
      - server:*
ports:
  - port: 127.0.0.1:80:80
    nodeFilters:
      - loadbalancer
  - port: 127.0.0.1:443:443
    nodeFilters:
      - loadbalancer
  - port: 127.0.0.1:9000:9000
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
  runtime:
    serversMemory: 2Gi
    agentsMemory: 4Gi
registries:
  create:
    host: 127.0.0.1
    hostPort: '5000'
```

**Describe the bug:**
Since v1.22.10-k3s1 and v1.23.7-k3s1 versions it is not possible to deploy own Traefik configuration using _HelmChartConfig_ via _manifests_ directory. Additionally, attempting to force the deployment of this file, by executing a `touch` command on it, results in the HelmChart resources named _traefik_ and _traefik-crd_ being removed, but HelmChartConfig itself is then deployed. All the k3s versions I tested are noted in the cluster configuration file.

**Steps To Reproduce:**

1. Put the above cluster configuration in the _k3s-local.k3d.yaml_ file and correct the path under the comment "Absolute path to the ./manifests/" (Why can't it be relative on the host side?)
2. Put below HelmChartConfig configuration in the _./manifests/traefik.helmchartconfig.k8s.yaml_.
    ```yaml
    ---
    apiVersion: helm.cattle.io/v1
    kind: HelmChartConfig
    metadata:
      name: traefik
      namespace: kube-system
    spec:
      # See https://github.com/traefik/traefik-helm-chart/tree/master/traefik for details
      # language=yaml
      valuesContent: |-
        logs:
          access:
            enabled: true
        ports:
          traefik:
            expose: true
        additionalArguments:
          - --metrics.prometheus=true
          - --tracing.jaeger=true
    ```
3. Deploy the cluster based on the above configuration using the command: `k3d cluster create -c k3s-local.k3d.yaml`

**Expected behavior:**

After the creation of the k3s cluster, I expect the following results:

```console
$ kubectl -n kube-system get helmchart,helmchartconfig                
NAME                                   AGE
helmchart.helm.cattle.io/traefik       24s
helmchart.helm.cattle.io/traefik-crd   24s

NAME                                     AGE
helmchartconfig.helm.cattle.io/traefik   27s
```

**Actual behavior:**

After the creation of the k3s cluster, I see the following results:

```console
$ kubectl -n kube-system get helmchart,helmchartconfig                    
NAME                                   AGE
helmchart.helm.cattle.io/traefik       25s
helmchart.helm.cattle.io/traefik-crd   25s
```

After touching _traefik.helmchartconfig.k8s.yaml_ file, using command `docker exec k3d-k3s-local-server-0 touch /var/lib/rancher/k3s/server/manifests/k3s-local/traefik.helmchartconfig.k8s.yaml` I see the following results:

```console
$ kubectl -n kube-system get helmchart,helmchartconfig
NAME                                     AGE
helmchartconfig.helm.cattle.io/traefik   31s
```

**Additional context / logs:**

[k3d-k3s-local-server-0-after-cluster-create.log](https://github.com/k3s-io/k3s/files/10696887/k3d-k3s-local-server-0-after-cluster-create.log)
[k3d-k3s-local-server-0-after-touch-file.log](https://github.com/k3s-io/k3s/files/10696888/k3d-k3s-local-server-0-after-touch-file.log)
