### ISSUE TITLE
ServiceLB advertises node IPs that do not match the service IPFamily

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6978]
ServiceLB is advertising node IPv6 addresses even when the service itself only supports IPv4. For example, when the node has an IPv6 address, but the cluster is not configured for dual-stack operation, we see:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels: {}
  name: traefik
  namespace: kube-system
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.167.89
  clusterIPs:
  - 10.43.167.89
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: web
    nodePort: 31112
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 31233
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.2
    - ip: fd7c:53a5:aef5::242:ac11:2
```

The IPv6 address cannot actually be reached, despite being advertised.

```console
brandond@dev01:~$ curl -kS 'http://172.17.0.2:80'
404 page not found

brandond@dev01:~$ curl -kS 'http://[fd7c:53a5:aef5::242:ac11:2]:80'
curl: (7) Failed to connect to fd7c:53a5:aef5::242:ac11:2 port 80 after 0 ms: Couldn't connect to server
```

This probably goes back to the original addition of dual-stack support to ServiceLB in https://github.com/k3s-io/k3s/pull/4114 - it should have looked at the ipFamilies list to determine what families are actually in use, as opposed to just looking at what the service wanted.
