### ISSUE TITLE
Add support for PodSelector in DrainSpec for SUC Upgrades

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#7099]
**Description:**
Currently there is no PodSelector support in the Drain Spec of the system-upgrade-controller chart. We should add support for that so that we can specify which pods should be drained as an opt-in. 

**Testing Considerations:**
1. Setting the arg to be one specific pod that is part of a Deployment, such as `app.kubernetes.io/name=testpod1` and ensure only that pod gets drained from the node.
2. Setting the arg to be a batch of pods that are part of multiple workloads (including both Deployments and Daemonsets), such as `app.kubernetes.io/type=testbatch1` and ensure only those pods get drained from the node. The Daemonsets should come back before the node is uncordoned, but the deployments should not.
3. Not setting the arg at all.
4. Setting multiple selectors to ensure it can delete a comma separated list, such as `app.kubernetes.io/name=testpod1,app.kubernetes.io/name=testpod2`

**Comment by aganesh-suse** [comment]
Ubuntu 22.4
Upgrading from 1.25.9+k3s1 to 1.26.1+k3s1 through 1.26.4+k3s1 versions.

Will be posting different scenario results, as and when we complete them. 

Scenario: Error check for both localDeleteDir and localEmptyDir in the drain params
Observed: Plan/Pod did not get created. instead foll error message was displayed. 
```
Error from server (BadRequest): error when creating "p.yaml": Plan in version "v1" cannot be handled as a Plan: strict decoding error: unknown field "spec.drain.deleteEmptyDir", unknown field "spec.drain.deleteLocalDir"
``` 

Scenario: Error in plan (yaml format error) - if 2 comma separated values for 1 key in matchLabels
Plan description for the same: 
```
status:
    conditions:
    - lastUpdateTime: "2023-05-26T17:47:35Z"
      message: 'values[0][app1]: Invalid value: "clusterip-demo, wrong": a valid label
        must be an empty string or consist of alphanumeric characters, ''-'', ''_''
        or ''.'', and must start and end with an alphanumeric character (e.g. ''MyValue'',  or
        ''my_value'',  or ''12345'', regex used for validation is ''(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'')'
      reason: Error
      status: "False"
      type: Validated
```

**Comment by aganesh-suse** [comment]
**Scenario**: Drain – with only force param. No podselector section
**Observed**: All pods were drained as expected.

**Comment by aganesh-suse** [comment]
**Scenario**: No drain section at all 
**Observed**:  no drain container should be in the system-upgrade pod

**Comment by aganesh-suse** [comment]
**Scenario**: Both matchExpressions and matchLabels in podseclector section. 
drain section in plan.yaml
```
  drain:
    podSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values: 
            - clusterip-pod-demo
            - clusterip-pod-demo-2
      matchLabels:
        app1: clusterip-demo
    force: true
```

**Observed**: 
drain container logs: 
```
kup logs pod/apply-k3s-agent-on-ip-172-31-10-88-with-2d64411f8c5dbe3fd-r9zx8 drain
node/ip-172-31-10-88 cordoned
WARNING: deleting Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: default/clusterip-pod-demo
evicting pod default/clusterip-pod-demo
pod/clusterip-pod-demo evicted
node/ip-172-31-10-88 evicted
```

**Comment by aganesh-suse** [comment]
Scenario: Drain pods matched for a Deployment
Observed: 
```
kup logs pod/apply-k3s-agent-on-ip-172-31-10-88-with-fffd7522514e0137a-8r6cj drain
node/ip-172-31-10-88 cordoned
evicting pod default/busydep-65474b5cbc-bwjhq
pod/busydep-65474b5cbc-bwjhq evicted
node/ip-172-31-10-88 evicted
```

**Comment by aganesh-suse** [comment]
**Scenario**: Drain pods matching daemonset- ignoreDaemonSet - true (Default)
**Observed**: 
```
kup logs pod/apply-k3s-agent-on-ip-172-31-10-88-with-fffd7522514e0137a-fcqt8 drain
node/ip-172-31-10-88 cordoned
WARNING: ignoring DaemonSet-managed Pods: default/othertest-deploy-7bdd9
node/ip-172-31-10-88 drained
```

**Comment by aganesh-suse** [comment]
**Scenario**: Drain pods matching daemonset - ignoreDaemonSets - false
**Observed**: 
```
kup logs pod/apply-k3s-agent-on-ip-172-31-10-88-with-0dad339c1ba5b8256-f4s46 drain
node/ip-172-31-10-88 cordoned
error: unable to drain node "ip-172-31-10-88", aborting command...

There are pending nodes to be drained:
 ip-172-31-10-88
error: cannot delete DaemonSet-managed Pods (use --ignore-daemonsets to ignore): default/othertest-deploy-7bdd9
```

**Comment by aganesh-suse** [comment]
**Scenario**: matchExpressions in podSelector
**Observed**: 
```
kup logs pod/apply-k3s-agent-on-ip-172-31-10-88-with-fffd7522514e0137a-x9wpc drain
node/ip-172-31-10-88 cordoned
WARNING: ignoring DaemonSet-managed Pods: default/othertest-deploy-7bdd9, kube-system/svclb-traefik-03d85d0d-tn98m; deleting Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: default/clusterip-pod-demo-3, default/clusterip-pod-demo, default/clusterip-pod-demo-2
evicting pod default/clusterip-pod-demo-2
evicting pod kube-system/local-path-provisioner-5d56847996-52tvn
evicting pod kube-system/helm-install-traefik-crd-mh7wr
evicting pod kube-system/helm-install-traefik-nqn5f
evicting pod kube-system/coredns-5c6b6c5476-b8tdw
evicting pod default/clusterip-pod-demo-3
evicting pod default/clusterip-pod-demo
pod/helm-install-traefik-nqn5f evicted
pod/helm-install-traefik-crd-mh7wr evicted
pod/coredns-5c6b6c5476-b8tdw evicted
pod/clusterip-pod-demo-2 evicted
pod/clusterip-pod-demo-3 evicted
pod/clusterip-pod-demo evicted
```
```
drain
     ip-172-31-10-88
     --pod-selector
     app.kubernetes.io/name notin (clusterip-pod-demo,clusterip-pod-demo-2),!upgrade.cattle.io/controller
     --ignore-daemonsets
     --delete-emptydir-data
     --force
```

**Comment by aganesh-suse** [comment]
Scenario: matchLabels used for a deployment with a podDisruptionBudget Set
```
    Args:
      drain
      ip-172-31-10-88
      --pod-selector
      app=busy,!upgrade.cattle.io/controller
      --ignore-daemonsets
      --delete-emptydir-data
      --force
    State:          Terminated
      Reason:       Completed
```
```
kup logs pod/apply-k3s-agent-on-ip-172-31-10-88-with-345a6302ca25eb378-whkjr drain
node/ip-172-31-10-88 cordoned
evicting pod default/busydep-65474b5cbc-nxs26
evicting pod default/busydep-65474b5cbc-zx2kg
error when evicting pods/"busydep-65474b5cbc-zx2kg" -n "default" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod default/busydep-65474b5cbc-zx2kg
```

**Comment by endawkins** [comment]
matchExpressions validation:

```
kup logs pod/apply-k3s-agent-on-ip-172-31-7-71-with-0dad339c1ba5b8256b-8tn4d drain
node/ip-172-31-7-71 cordoned
WARNING: deleting Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: default/clusterip-pod-demo
evicting pod default/clusterip-pod-demo
pod/clusterip-pod-demo evicted
node/ip-172-31-7-71 evicted
```

**Comment by endawkins** [comment]
matchLabels validation:

```
AME                   STATUS   ROLES                       AGE     VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
node/ip-172-31-1-230   Ready    control-plane,etcd,master   9m12s   v1.25.8+k3s1   172.31.1.230   <none>        Ubuntu 22.04.2 LTS   5.19.0-1025-aws   containerd://1.6.19-k3s1
node/ip-172-31-7-71    Ready    <none>                      8m13s   v1.25.8+k3s1   172.31.7.71    <none>        Ubuntu 22.04.2 LTS   5.19.0-1025-aws   containerd://1.6.19-k3s1

NAMESPACE        NAME                                             READY   STATUS      RESTARTS   AGE     IP           NODE              NOMINATED NODE   READINESS GATES
default          pod/clusterip-pod-demo                           1/1     Running     0          7m23s   10.42.1.3    ip-172-31-7-71    <none>           <none>
default          pod/clusterip-pod-demo-2                         1/1     Running     0          7m23s   10.42.1.4    ip-172-31-7-71    <none>           <none>
default          pod/clusterip-pod-demo-3                         1/1     Running     0          7m23s   10.42.1.5    ip-172-31-7-71    <none>           <none>
default          pod/othertest-deploy-86fjx                       1/1     Running     0          6m40s   10.42.1.6    ip-172-31-7-71    <none>           <none>
default          pod/othertest-deploy-l692w                       1/1     Running     0          6m40s   10.42.0.9    ip-172-31-1-230   <none>           <none>
kube-system      pod/coredns-597584b69b-mlv8q                     1/1     Running     0          8m57s   10.42.0.4    ip-172-31-1-230   <none>           <none>
kube-system      pod/helm-install-traefik-9m9t8                   0/1     Completed   1          8m58s   10.42.0.3    ip-172-31-1-230   <none>           <none>
kube-system      pod/helm-install-traefik-crd-t2lcj               0/1     Completed   0          8m58s   10.42.0.2    ip-172-31-1-230   <none>           <none>
kube-system      pod/local-path-provisioner-79f67d76f8-7w5jt      1/1     Running     0          8m57s   10.42.0.5    ip-172-31-1-230   <none>           <none>
```

```
NAME                   STATUS                     ROLES                       AGE   VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
node/ip-172-31-1-230   Ready                      control-plane,etcd,master   11m   v1.25.9+k3s1   172.31.1.230   <none>        Ubuntu 22.04.2 LTS   5.19.0-1025-aws   containerd://1.6.19-
k3s1
node/ip-172-31-7-71    Ready,SchedulingDisabled   <none>                      10m   v1.25.9+k3s1   172.31.7.71    <none>        Ubuntu 22.04.2 LTS   5.19.0-1025-aws   containerd://1.6.19-
k3s1

NAMESPACE        NAME                                                                  READY   STATUS        RESTARTS   AGE     IP             NODE              NOMINATED NODE   READINESS
 GATES
default          pod/clusterip-pod-demo                                                1/1     Running       0          10m     10.42.1.3      ip-172-31-7-71    <none>           <none>
default          pod/clusterip-pod-demo-2                                              1/1     Running       0          10m     10.42.1.4      ip-172-31-7-71    <none>           <none>
default          pod/othertest-deploy-86fjx                                            1/1     Running       0          9m24s   10.42.1.6      ip-172-31-7-71    <none>           <none>
default          pod/othertest-deploy-l692w                                            1/1     Running       0          9m24s   10.42.0.9      ip-172-31-1-230   <none>           <none>
kube-system      pod/coredns-8b9777675-p74dp                                           1/1     Running       0          28s     10.42.1.7      ip-172-31-7-71    <none>           <none>
kube-system      pod/helm-install-traefik-crd-lw5z2                                    0/1     Completed     0          28s     10.42.1.10     ip-172-31-7-71    <none>           <none>
```

```
drain:
    Container ID:  containerd://76ee87bee27b7ad0faac69a06d5e9e82b3d53080caf1665e115ab6647950a0ce
    Image:         rancher/kubectl:v1.21.9
    Image ID:      docker.io/rancher/kubectl@sha256:5f09121733a01a3b0588a92274e44269dc2b82904b8a061b164dbe5d270cce1b
    Port:          <none>
    Host Port:     <none>
    Args:
      drain
      ip-172-31-7-71
      --pod-selector
      app.kubernetes.io/name=clusterip3,!upgrade.cattle.io/controller
      --ignore-daemonsets
      --delete-emptydir-data
      --force
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 26 May 2023 18:33:05 +0000
      Finished:     Fri, 26 May 2023 18:33:09 +0000
```

pod deployment used:
```
apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc-demo
  labels:
    app: clusterip-demo
    app.kubernetes.io/name: clusterip
    app.kubernetes.io/kind: service
spec:
  #ipFamilyPolicy: PreferDualStack
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
  selector:
    app: clusterip-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: clusterip-pod-demo
  labels:
    app1: clusterip-demo
    app.kubernetes.io/name: clusterip1
    app.kubernetes.io/kind: pod
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "sleep 5"]
  containers:
  - name: nginx-container
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: clusterip-pod-demo-2
  labels:
    app2: clus-2
    app.kubernetes.io/name: clusterip2
    app.kubernetes.io/kind: pod
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "sleep 5"]
  containers:
  - name: nginx-container
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: clusterip-pod-demo-3
  labels:
    app3: clus-3
    app.kubernetes.io/name: clusterip3
    app.kubernetes.io/kind: pod
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "sleep 5"]
  containers:
  - name: nginx-container
    image: nginx
```

plan.yaml:

```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  version: v1.25.9+k3s1
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/master, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  cordon: true
  #drain:
  #  force: true
  upgrade:
    image: rancher/k3s-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  concurrency: 1
  version: v1.25.9+k3s1
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/master, operator: NotIn, values: ["true"]}
  serviceAccountName: system-upgrade
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "k3s-server"]
  drain:
    podSelector:
    #   matchExpressions:
    #     - key: app.kubernetes.io/name
    #       operator: NotIn
    #       values: 
    #         - clusterip-pod-demo
    #         - clusterip-pod-demo-2
      matchLabels:
        app.kubernetes.io/name: clusterip3
      # label can be only 1 key/value pair
    force: true
  upgrade:
    image: rancher/k3s-upgrade
```
