### ISSUE TITLE
Service internalTrafficPolicy set to Local still load balances between pods on all nodes

### ISSUE THREAD

**Issue by oasisvali** [k3s-io/k3s#7253]
**Environmental Info:**
K3s Version: 

k3s version v1.26.3+k3s1 (01ea3ff2)
go version go1.19.7

Node(s) CPU architecture, OS, and Version: 

Linux ip-172-26-13-42 5.15.0-1030-aws #34-Ubuntu SMP Mon Jan 23 20:13:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server, 1 agent
flannel with wireguard-native backend, in external-ip mode
traefik disabled
service-node-port-range overridden to 80-32767 to allow ingress-controller (nginx) to bind to port 80/443

**Describe the bug:**

My aim is to run our stateless application pod on each node in the cluster via a Daemonset. Our cluster contains multiple nodes across different regions and we are running the application pod on each node so that it can serve requests originating from its region to reduce latency. The nodes all have public IPs and `flannel-external-ip` has been set to `true`. `flannel-backend` is also set to `wireguard-native` to ensure communication between nodes is encrypted since it is happening through public IPs

For the latency to be low, I want to eliminate any cross-node hops during the request cycle. For this, I have bound ingress-nginx-controller to the host ports 80/443 and installed it as a NodePort service with `externalTrafficPolicy` set to `true`. The controller pods themselves are run via a Daemonset so that incoming requests to any node get handled by the controller pod on the same node. I have verified this is working as expected via the controller pod logs.

To eliminate cross-node hops when the request is forwarded to the application service, I have set `internalTrafficPolicy` to `true` on the application service. Since the application pods backing this service are also run via Daemonset, all nodes are running an instance of the application pod, and my expectation is that requests to any node would go from the ingress controller pod on that node to the application pod on the same node via the application service. However, this is not the observed behaviour. The request is forwarded to the application service by the ingress controller pod, which load balances between the application pods running across all nodes, leading to cross-node hops for half of the requests. 

**Steps To Reproduce:**

- Installed K3s: 
Server install
```
curl -sfL https://get.k3s.io | K3S_TOKEN='<SECRET>' INSTALL_K3S_EXEC="server --cluster-init --config ~/config.yaml" INSTALL_K3S_VERSION=v1.26.3+k3s1 sh -
```
Server config file:
```
tls-san: <public-ip-address-of-server-node>
disable:
  - traefik
write-kubeconfig: <home-dir>/kubeconfig
flannel-external-ip: true
node-external-ip: <public-ip-address-of-server-node>
flannel-backend: wireguard-native
kube-apiserver-arg: 'service-node-port-range=80-32767'
```

Agent install
```
curl -sfL https://get.k3s.io | K3S_URL=https://<server-node-public-ip-address>:6443 K3S_TOKEN=<cluster-token> INSTALL_K3S_EXEC="--config ~/config.yaml" INSTALL_K3S_VERSION=v1.26.3+k3s1  sh -
```
Agent config file:
```
node-external-ip: <public-ip-address-of-agent-node>
```

**Expected behavior:**

When an https request is made to any node, the ingress-controller pod on that node should handle it, and route it to the Application Service. The Application Service should forward that request always to the Application pod on the same node. 

**Actual behavior:**

When an https request is made to any node, the ingress-controller pod on that node handles it (verified by ingress-controller logs), and routes it to the Application Service. The Application Service then load-balances the request among the Application pods running across all nodes resulting in cross-node hops. 

**Additional context / logs:**

Nginx Ingress Contoller NodePort service:
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-nginx-ingress-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-query-staging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-8.0.7
  annotations:
status:
  loadBalancer: {}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
      nodePort: 443
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: nginx-ingress-controller
  clusterIP: 10.43.12.72
  clusterIPs:
    - 10.43.12.72
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
```

Application Service:
```
apiVersion: v1
kind: Service
status:
  loadBalancer: {}
spec:
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 9001
    - name: health-check
      protocol: TCP
      port: 3333
      targetPort: 3333
  clusterIP: 10.43.203.168
  clusterIPs:
    - 10.43.203.168
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Local
```

Ingress Controller Logs showing load-balancing among application pods:
```
210.186.143.29 - - [09/Apr/2023:05:29:08 +0000] "GET /ready HTTP/2.0" 200 78 "-" "curl/7.79.1" 43 0.210 [<>-3333] [] 10.42.0.25:3333 89 0.208 200 fdc534056da3317db46fe920ef1b45e9
210.186.143.29 - - [09/Apr/2023:05:29:11 +0000] "GET /ready HTTP/2.0" 200 78 "-" "curl/7.79.1" 43 0.334 [<>-3333] [] 10.42.1.8:3333 89 0.336 200 59205a20c409aca2d0b9a8e31b46034a
```

The above 2 requests were made to the public IP of the agent node, and 1 got routed to the application pod on the agent (10.42.1.8) and another got routed to the application pod on the server (10.42.0.25)
