### ISSUE TITLE
Packaged Traefik 2.9.4 has incorrect access logs

### ISSUE THREAD

**Issue by taoyouh** [k3s-io/k3s#7301]
**Environmental Info:**
K3s Version: 

> k3s version v1.26.3+k3s1 (01ea3ff2)
> go version go1.19.7

Node(s) CPU architecture, OS, and Version: 
> Linux ecs-wulanchabu-1 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

> Single node. 1 server.

**Describe the bug:**
The access logs of Traefik (the packaged 2.9.4 version) do not have all status codes recorded correctly. Some status codes are recorded as 0. Traefik maintainers said they had a bug before 2.9.5 and suggested to try 2.9.10 (see [issue](https://github.com/traefik/traefik/issues/9842)). My try of 2.9.10 seemed to be good. k3s should update the packaged traefik version soon.

**Steps To Reproduce:**

- Installed K3s:
```
curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s - --cluster-cidr=xxx --service-cidr=xxx --flannel-ipv6-masq 
```
- Enabled Traefik access log by adding this file in manifest:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        externalTrafficPolicy: Local
    logs:
      access:
        enabled: true
```
- Waited for many requests to come in (e.g. the internal "ping" request) and checked Traefik access log:
```
sudo kubectl logs -l app.kubernetes.io/name=traefik -n kube-system
```

**Expected behavior:**
The access log should record the status codes:
> {IP address hidden} - - [18/Apr/2023:02:51:04 +0000] "GET /ping HTTP/1.1" **200** 2 "-" "-" 173 "ping@internal" "-" 0ms
> {IP address hidden} - - [18/Apr/2023:02:51:04 +0000] "GET /ping HTTP/1.1" **200** 2 "-" "-" 172 "ping@internal" "-" 0ms

**Actual behavior:**
Some log lines has 0 status codes:
> {IP address hidden} - - [15/Apr/2023:08:27:57 +0000] "GET /ping HTTP/1.1" **0** 0 "-" "-" 69237 "ping@internal" "-" 0ms

**Additional context / logs:**

Tried to update traefik to 2.9.10 by changing the manifest above to:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      registry: docker.io
      name: traefik
      tag: 2.9.10
    service:
      spec:
        externalTrafficPolicy: Local
    logs:
      access:
        enabled: true
```

The access logs seemed correct.
