### ISSUE TITLE
adding a docker provider to traefik k3s error docker.sock access

### ISSUE THREAD

**Issue by PahaCore** [k3s-io/k3s#7302]
**Environmental Info:**
K3s Version: 
k3s version v1.26.3+k3s1 
Docker version 23.0.3, build 
Traefik 2.9.4

Node(s) CPU architecture, OS, and Version: 
Linux 5.15.0-69-generic -Ubuntu SMP  x86_64

Cluster Configuration:
1 server

**Describe the bug:**
```
level=error msg="Provider connection error Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?, retrying in 1.642087069s" providerName=docker
```

**Steps To Reproduce:**
using the instruction traefik added a docker provider

```
https://doc.traefik.io/traefik/providers/docker/

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - --accesslog=true
      - --global.checknewversion
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.http.redirections.entryPoint.to=:443
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
---------------
I 've tried it like this
--providers.docker.endpoint=unix:///var/run/docker.sock
```

- Installed K3s: 

curl -sfL https://get.k3s.io | sh - 
# Check for Ready node, takes ~30 seconds 
sudo k3s kubectl get node 

**Expected behavior:**

I expect that it is possible to use k3s traefik as kubernetes and docker on the same host

**Actual behavior:**
traefik can 't connect to docker
the user is a member of the docker group and executes docker commands , just like root

**Additional context / logs:**

`level=error msg="Provider connection error Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?, retrying in 1.642087069s" providerName=docker`
