### ISSUE TITLE
UDP ports that have matching TCP ports, hostPort value gets ignored for UDP

### ISSUE THREAD

**Issue by stavros-k** [k3s-io/k3s#7381]
**Environmental Info:**
K3s Version: v1.25.4+k3s1

Node(s) CPU architecture, OS, and Version: 

AMD x86 (AMD Ryzen™ 7 5800U)
Linux IdeaPad-5-Pro-14ACN6 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

While this is one of the machine I used to replicate, it happens on others too. (All x86 arch)

Cluster Configuration:

1 Node, started with the k3s oneliner

**Describe the bug:**

After disabling hostNetwork on an already deployed Deployment, hostPorts are not cleared up.
Even if I explicitly set hostPort(s) to `null`, Ports that have the same number for TCP and UDP, only the TCP gets cleared up.
See below an example:

Container Ports section:
```yaml
            - name: web
              containerPort: 8384
            - name: tcp
              containerPort: 22000
              protocol: TCP
            - name: udp
              containerPort: 22000
              protocol: UDP
            - name: somerando
              containerPort: 25000
              protocol: UDP
```
(The `somerando` port will be used to demo something in a bit)

Installing a Helm Chart (deployment) with `hostNetwork` to true will create a pod that has the defined `containerPorts` as `hostPort` aswell. eg:
(k3s kubectl describe pod)
```yaml
    Ports:          8384/TCP, 22000/TCP, 22000/UDP, 25000/UDP
    Host Ports:     8384/TCP, 22000/TCP, 22000/UDP, 25000/UDP
```

Upgrading the chart after setting `hostNetwork` to false, it still keeps the hostPorts there (Not expected but I get the logic, helm didn't add those ports, so it won't remove it). That's fine. Let's add `hostPort: null` to all these 3 ports.

Container Ports section:
```yaml
            - name: web
              containerPort: 8384
              hostPort: null
            - name: tcp
              containerPort: 22000
              protocol: TCP
              hostPort: null
            - name: udp
              containerPort: 22000
              protocol: UDP
              hostPort: null
            - name: somerando
              containerPort: 25000
              protocol: UDP
              hostPort: null
```

Lets upgrade again.

```yaml
    Ports:          8384/TCP, 22000/TCP, 22000/UDP, 25000/UDP
    Host Ports:     0/TCP, 0/TCP, 22000/UDP, 0/UDP
```
As you can see only the UDP that had matching TCP port didn't got the null applied. (The same happens if I do `kubectl edit deploy...`)

**Steps To Reproduce:**

Check the example above

**Expected behavior:**

hostPorts to get cleaned up when explicitly set to null

**Actual behavior:**

UDP ports that have matching TCP ports, only the TCP's hostport gets cleaned up
Furthermore, (for testing) if you set different hostPort for UDP and TCP the UDP's host port number gets ignored

**Additional context / logs:**
