### ISSUE TITLE
kube-router: ipset will only contain one IP if port name is used.

### ISSUE THREAD

**Issue by BoleynSu** [k3s-io/k3s#7446]
The line causing the issue is at https://github.com/cloudnativelabs/kube-router/blob/cced939a8ba10642afc171c484c0e885a7beb11f/pkg/controllers/netpol/policy.go#L862

Example: https://github.com/BoleynSu-Org/monorepo/blob/badcd3b721a4941724f19fd300de4e072813c1d2/deploy/oj/k3s-cuhk/common/network-policy.yaml#L21

Seems like k3s is using its own fork of kube-router?

**Comment by brandond** [comment]
It's a fork, but just so that we can embed it in the main process. Have you reported this issue upstream?

**Comment by brandond** [comment]
cc @manuelbuil @rbrtbnfgl

**Comment by brandond** [comment]
You linked to a line of code in the upstream project, not in our fork. Can you point to where in our fork it might be, if you think it only exists there?

Our fork is at https://github.com/k3s-io/kube-router/tree/v2.0.0+k3sr3, and has only a few commits that differ from the kube-router 2.0.0 release candidate tag that it was forked at.

**Comment by cwayne18** [comment]
As Brad mentioned our fork has minimal changes and the linked code is actually existing upstream. I understand that bugs exist and that they can be quite frustrating, but going out of one's way to specifically call something "buggy" doesn't seem necessary to me in this case.

**Comment by brandond** [comment]
I think this might be a duplicate of https://github.com/k3s-io/k3s/issues/7391

**Comment by brandond** [comment]
Yes, it's a tag, not a branch. You can find the upstream tag at https://github.com/cloudnativelabs/kube-router/tree/v2.0.0-rc3 but you will notice it too does not yet belong to a branch that they have pushed. This is just how they have chosen to develop the 2.0 release candidates.

**Comment by rbrtbnfgl** [comment]
What the meaning of containing only one IP?
What type of traffic do you want to block an how are you trying to test the network policy?
Consider that the node traffic to the pods that are executed on that node is always allowed.

**Comment by rbrtbnfgl** [comment]
No my questions were related to your deployment. How are you testing that the policy actually works?

**Comment by rbrtbnfgl** [comment]
Should it be translated to 80 instead of 8080?

**Comment by rbrtbnfgl** [comment]
could you please give us the steps that you are doing to reproduce the issue? Maybe you are right that the bug could be related to that line of the code but I don't have enough info.

**Comment by rbrtbnfgl** [comment]
If you try to check the iptables rule on the node for that specific policy what do you get?
`sudo iptables-save | grep oj-server-network-policy`

**Comment by rbrtbnfgl** [comment]
I don't know if it strictly related to that line of code but the line that you mentioned it's also upstream
https://github.com/cloudnativelabs/kube-router/blob/prep-v2.0/pkg/controllers/netpol/policy.go#L862
it's related to v2 that supports dualstack we can't use the master branch because it's not supporting it.
In case we found a fix it will be better to fix it upstream and then on our fork.

**Comment by rbrtbnfgl** [comment]
yes that's the same that I have done to fix it.

**Comment by rbrtbnfgl** [comment]
I'll update the fix on our fork to have it solved for the next release.

**Comment by est-suse** [comment]
### Validated on <branch-name> branch with commit <commit-id> / version <version>
 


## Environment Details

```
Validated on Master Branch 1.27 10fb39ae60abfc60592497903ba734c7e9a17bdf
k3s version v1.27.1+k3s-10fb39ae (10fb39ae)
go version go1.20.3
```

 
*Infrastructure*
- [X ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-33-29 5.15.0-1033-aws #37~20.04.1-Ubuntu SMP Fri Mar 17 11:39:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
```
 
*Additional files*

```
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
3.
 
 
**Replication Results:**
- k3s version used for replication:

```
Run the script:

#!/bin/bash
set -euo pipefail

kubectl delete sts/wordpress || true
kubectl delete deployment/busybox || true
kubectl delete service/wordpress-service || true
kubectl delete networkpolicy/wordpress-network-policy || true

kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  serviceName: wordpress-service
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - name: http
          containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        - infinity
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  clusterIP: None
  selector:
    app: wordpress
EOF

kubectl rollout status sts/wordpress
kubectl rollout status deployment/busybox
! (
    kubectl exec -it deployment/busybox -- wget -O - wordpress-0.wordpress-service.default.svc.cluster.local >/dev/null || echo "failed"
    kubectl exec -it deployment/busybox -- wget -O - wordpress-1.wordpress-service.default.svc.cluster.local >/dev/null || echo "failed"
) | grep failed

kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wordpress-network-policy
spec:
  podSelector:
    matchLabels:
      app: wordpress
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: busybox
    ports:
    - port: http
EOF

sleep 30
! (
    kubectl exec -it deployment/busybox -- wget -O - wordpress-0.wordpress-service.default.svc.cluster.local >/dev/null || echo "failed"
    kubectl exec -it deployment/busybox -- wget -O - wordpress-1.wordpress-service.default.svc.cluster.local >/dev/null || echo "failed"
) | grep failed
```
 

```

```
 
 
**Validation Results:**
- k3s version used for validation:

```
![image](https://github.com/k3s-io/k3s/assets/106194120/96c3652f-6076-413c-9307-4923c323a7a0)


```
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-957fdf8bc-dhx5f   1/1     Running     0          7m40s
kube-system   coredns-77ccd57875-q2q2j                 1/1     Running     0          7m40s
kube-system   helm-install-traefik-crd-fbc7g           0/1     Completed   0          7m41s
kube-system   helm-install-traefik-pdqv7               0/1     Completed   1          7m41s
kube-system   svclb-traefik-53b1fa17-5dlqt             2/2     Running     0          7m27s
kube-system   traefik-64f55bb67d-ktncm                 1/1     Running     0          7m28s
kube-system   metrics-server-54dc485875-f9k8z          1/1     Running     0          7m40s
default       busybox-f7db5bc95-tc5ws                  1/1     Running     0          119s
default       wordpress-0                              1/1     Running     0          119s
default       wordpress-1                              1/1     Running     0          108s
```

```
 

```
```
 
**Additional context / logs:**
```
```
