### ISSUE TITLE
Unable to parse HelmChartConfig

### ISSUE THREAD

**Issue by Ludea** [k3s-io/k3s#7447]
**Environmental Info:**
K3s Version: 

k3s version v1.26.4+k3s1 (8d0255af)
go version go1.19.8

Node(s) CPU architecture, OS, and Version: 

Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Cluster Configuration:

Single master node

**Describe the bug:**

I get ```+ helm_v3 upgrade --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-20.3.1+up20.3.0.tgz --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml
Error: failed to parse /config/values-10_HelmChartConfig.yaml: error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context ```

**Steps To Reproduce:**

- Installed K3s: 
Create HelmChartConfig :
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    persistence:
      enabled: true
      storageClass: local-path
    certResolvers:
      letsencrypt:
       dnsChallenge:
         provider: duckdns
      storage: /data/acme.json
    env:
      - name:
        valueFrom: DUCKDNS_TOKEN
          secretKeyRef:
          name: duckdns
          key: token
    deployment:
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["sh", "-c", "touch /data/acme.json"] 
```
Following this https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#use-traefik-native-lets-encrypt-integration-without-cert-manager

**Expected behavior:**

Traefik pod with above config 

**Actual behavior:**

helm-install-traefik-qcg8z always crash with issue

**Additional context / logs:**
