### ISSUE TITLE
[Release-1.25] - /var/lib/rancher/k3s/storage should not be world-readable.

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#7470]
Backport fix for /var/lib/rancher/k3s/storage should not be world-readable.

* #2348

**Comment by est-suse** [comment]
### Validated on <branch-name> branch with commit <commit-id> / version <version>
 ```
k3s version v1.25.10-rc1+k3s1 (613a3bc8)
go version go1.19.9
```
## Environment Details

 
*Infrastructure*
- [X] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-5-68 5.15.0-1026-aws #30-Ubuntu SMP Wed Nov 23 14:15:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
```
 
*Additional files*

```

```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
3.
 
 
**Replication Results:**
- k3s version used for replication:

```
token: secret
write-kubeconfig-mode: 644
selinux: true
cluster-init: true
```
 

```
```
 
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.25.10-rc1+k3s1 (613a3bc8)
go version go1.19.9
```
 
**Additional Files**
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc
```
 
**Additional context / logs:**
```
https://github.com/k3s-io/k3s/issues/3704
```
