### ISSUE TITLE
[release-1.25] Register K3s CRDs with schema

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7496]
* Backport #7310

**Comment by endawkins** [comment]
### Validated on branch 1.25 with commit 3ce8dd1 / version 1.25
 
## Environment Details

 
*Infrastructure*
- [X] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-10-48 5.14.21-150400.24.46-default #1 SMP PREEMPT_DYNAMIC Thu Feb 9 08:38:18 UTC 2023 (2d95137) x86_64 x86_64 x86_64 GNU/Linux
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
DOCUMENTATION_URL="https://documentation.suse.com/"
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
debug: true
token: test
selinux: true
protect-kernel-defaults: true
```
 
*Additional files*

```
bad_boolean.yaml:

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  targetNamespace: cert-manager
  version: v1.9.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: true
    webhook.timeoutSeconds: 4
```
```
good_boolean.yaml:

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  targetNamespace: cert-manager
  version: v1.9.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
    webhook.timeoutSeconds: 4
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
3. Run the following command:
```
kubectl apply -f bad_boolean.yaml
```
4. Run the following command (on fixed version):
```
kubectl apply -f good_boolean.yaml
```
 
 
**Replication Results:**
- k3s version used for replication:

```
k3s -v
k3s version v1.25.9+k3s1 (7502ce6a)
go version go1.19.8
```
 

```
kubectl apply -f bad_boolean.yaml

namespace/cert-manager created
helmchart.helm.cattle.io/cert-manager created
```
 
 
**Validation Results:**
- k3s version used for validation:

```
k3s -v
k3s version v1.25.9+k3s-3ce8dd17 (3ce8dd17)
go version go1.19.8
```
 

```
kubectl apply -f bad_boolean.yaml
namespace/cert-manager created
The HelmChart "cert-manager" is invalid: spec.set.installCRDs: Invalid value: "boolean": spec.set.installCRDs in body must be of type integer,string: "boolean"

kubectl apply -f good_boolean.yaml
namespace/cert-manager unchanged
helmchart.helm.cattle.io/cert-manager created
```
 
**Additional context / logs:**
```
N/A
```
