### ISSUE TITLE
frequent tcp timeouts from Pods to internet

### ISSUE THREAD

**Issue by thewilli** [k3s-io/k3s#7543]
**Environmental Info:**
K3s Version:  
```
k3s version v1.26.4+k3s1 (8d0255af)
go version go1.19.8
```
The same behaviour occurs with `v1.27.1`.

Node(s) CPU architecture, OS, and Version: 
```
Linux k8s01 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

* single-node cluster
* Ubuntu 22.04 LTS
* physical hardware
* single NIC with IPv4 only

The same effect could be reproduced on another machine with a similar configuration

**Describe the bug:**

* TCP Connections to the API Server timeout on a regular basis (success rate varies between ~ 20% and 80%)
* TCP Connections to the Internet timeout on a regular basis (success rate varies between ~ 20% and 80%)
* TCP Connections to Kubernetes Services (except of the API Server) succeed with 100 %

**Steps To Reproduce:**

- Installed K3s: 

```yaml
# /etc/rancher/k3s/config.yaml
disable: [traefik, servicelb]
flannel-backend: vxlan
```

```bash
curl -sfL https://get.k3s.io | sh -s - server
```

* Setup curl Pods

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  &name curltest
  namespace: default
  labels:
    app:  *name
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
      - name:  *name
        image: curlimages/curl:8.00.1
        command: [tail, -f, /dev/null]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  &name curltest-host
  namespace: default
  labels:
    app:  *name
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      hostNetwork: true
      containers:
      - name:  *name
        image: curlimages/curl:8.00.1
        command: [tail, -f, /dev/null]
```

* Run the following common on the 2 curl pods: 

```bash
for x in $(seq 1 20); do
 curl -s --connect-timeout 5 -H "Host: google.com" http://142.250.186.46/ > /dev/null;
 echo $?;
done
```

**Expected behavior:**

* The return code / output is 0 (successful connection) for the runs on both pods

**Actual behavior:**

* The return code / output is 0 for each run on the `curltest-host` pods
* The return code / output is 28 (timeout) for more than 1/3 of the runs on the `curltest` pods

**Additional context / logs:**

* I tried to upgrade the k3s version to `v1.27.1`, but the behavior stays the same
* A network capture shows many retransmissions and DUP ACKs whenever the Pod IP (10.42.0.6) is involved. 
  * The same dump does not show any issues at all, when the `curltest-host` pods are used.

![CleanShot 2023-05-14 at 16 37 07@2x](https://github.com/k3s-io/k3s/assets/1206639/8cb3f3f4-7e6d-4658-b85c-4f3d824632b4)
