### ISSUE TITLE
Scheduled etcd snapshots are not uploaded to S3, only manual ones

### ISSUE THREAD

**Issue by thewilli** [k3s-io/k3s#7568]
**Environmental Info:**
K3s Version: 

```
k3s version v1.26.4+k3s1 (8d0255af)
go version go1.19.8
```

Node(s) CPU architecture, OS, and Version: 
```
Linux k8s01 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
* 3 server nodes

**Describe the bug:**
When I configure an S3 target for etcd snapshots, I can confirm the setting is actually working by creating a manual snapshot via `k3s etcd-snapshot save`. Still, for the scheduled snapshots (`etcd-snapshot-schedule-cron` setting) the snapshots are not uploaded to the S3 bucket and remain local. 

**Steps To Reproduce:**

- Install k3s using HA etcd setup
- Add the following configuration and restart k3s afterwards

```yaml
# /etc/rancher/k3s/config.yaml.d/etcd-backup.yaml
etcd-s3: true
etcd-s3-access-key: <my-access-key>
etcd-s3-secret-key: <my-secret-key>
etcd-s3-bucket: <my-etcd-backup-bucket>
etcd-snapshot-schedule-cron: "0 /6 * * *"
```

**Expected behavior:**
- Manual etcd snapshots (`k3s etcd-snapshot save`) are uploaded to configured s3 bucket
- Scheduled etcd snapshots are uploaded to configured s3 bucket

**Actual behavior:**
- Manual etcd snapshots (`k3s etcd-snapshot save`) are uploaded to configured s3 bucket
- Scheduled etcd snapshots are **not** uploaded to configured s3 bucket and remain local
