### ISSUE TITLE
Failing secret webhook causes unexpected behavior

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7654]
K3s tracking issue for:
* https://github.com/rancher/rke2/issues/4266

To test:
1. Create a cluster (any number of servers/agents)
2. Create a bad webhook configuration (this one just calls out to httpbin.org for a 502 error response):
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: rancher.cattle.io
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: https://httpbin.org/status/502
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rancher.cattle.io.secrets
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - secrets
    scope: Namespaced
  sideEffects: NoneOnDryRun
  timeoutSeconds: 5
```
3. Attempt to join a new agent
4. Note that the agent is unable to join the cluster - When node registration is blocked by the failing webhook, the error on the server isn't clear what's going on:
```
May 22 22:15:40 systemd-node-1 rke2[223]: time="2023-05-22T22:15:40Z" level=error msg="Internal error occurred: failed calling webhook \"rancher.cattle.io.secrets\": failed to call webhook: an error on the server (\"\") has prevented the request from succeeding"
```
The error log on the agent does indicate that the password was rejected, but not why:
```
May 22 22:17:15 systemd-node-2 rke2[222]: time="2023-05-22T22:17:15Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password' may not match server node-passwd entry, try enabling a unique node name with the --with-node-id flag"
```
