### ISSUE TITLE
[release-1.26] Bump helm-controller version 

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7700]
* #7699 backport

**Comment by aganesh-suse** [comment]
RHEL 9.2
Branch release-1.26: 

go.mod file has: 
```
github.com/k3s-io/helm-controller v0.15.0
```

```
sudo cat /var/lib/rancher/k3s/server/manifests/web-helmchart.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: apache
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: apache
  targetNamespace: web
  valuesContent: |-
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: www.example.com
    metrics:
      enabled: true
```

```
kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-76d776f6f9-6jnqq   1/1     Running     0          2m57s
kube-system   coredns-59b4f5bbd5-7jbdc                  1/1     Running     0          2m57s
kube-system   helm-install-traefik-crd-n6hdt            0/1     Completed   0          2m57s
kube-system   svclb-traefik-c8c5447b-crt66              2/2     Running     0          2m45s
kube-system   helm-install-traefik-mj8fv                0/1     Completed   1          2m57s
kube-system   traefik-57c84cf78d-9dq9g                  1/1     Running     0          2m45s
kube-system   metrics-server-68cf49699b-fqfdf           1/1     Running     0          2m57s
kube-system   svclb-traefik-c8c5447b-tzqm7              2/2     Running     0          2m
kube-system   helm-install-apache-wq7tc                 0/1     Completed   0          37s
web           apache-bc5c7bb89-tsv77                    1/2     Running     0          29s
```
