### ISSUE TITLE
container exit with code 137 when use nvidia gpu with memory and cpu limit.

### ISSUE THREAD

**Issue by cmsxbc** [k3s-io/k3s#7746]
**Environmental Info:**
K3s Version: 
k3s version v1.26.5+k3s1 (7cefebea)
go version go1.19.9

Node(s) CPU architecture, OS, and Version: 
Archlinux up to date.
```
Linux node 6.3.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000 x86_64 GNU/Linux
```
NVIDIA associate version:
```
local/egl-wayland 2:1.1.11-4
local/libnvidia-container 1.13.1-1
local/libnvidia-container-tools 1.13.1-1
local/nvidia 530.41.03-15
local/nvidia-container-runtime 3.13.1-1
local/nvidia-container-toolkit 1.13.1-1
local/nvidia-utils 530.41.03-1
```

Cluster Configuration: 1 servers, additional 1 agents.

**Describe the bug:**

when request nvidia gpu and set cpu&memory limit&request, the container exit with code 137 even it only run a `sleep`.
But if remove cpu&memroy limit&request, it never occurs.

**Steps To Reproduce:**

- Installed K3s: use default config.
- create the pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: strange-crash
spec:
  restartPolicy: Never
  runtimeClassName: nvidia
  containers:
  - name: trainer
    image: nvidia/cuda:11.8.0-devel-ubuntu20.04
    args: ["bash", "-c", "while true; do nvidia-smi; sleep 1; done"]
    resources:
      limits:
        nvidia.com/gpu: 1
        cpu: 16
        memory: 40Gi
      requests:
        cpu: 8
        memory: 30Gi
```
- wait about 40s.

**Expected behavior:**

Run normally.

**Actual behavior:**

Exit with code 137. And there is no log saying oom occurs.

**Additional context / logs:**

![image](https://github.com/k3s-io/k3s/assets/3500109/cbc0274c-8ca4-4d7d-b750-f4befe6cf6e6)

![image](https://github.com/k3s-io/k3s/assets/3500109/57b717ff-c240-43a8-9ed9-ad7673cca04c)
