### ISSUE TITLE
The resource limit of k3s is not effective

### ISSUE THREAD

**Issue by jack331200** [k3s-io/k3s#7779]
My service has set limits, but in actual deployment, top monitoring found that the Java running in Pod still exceeds the limit.

```
yc-core-account.yaml
......
        resources:                                                       
          limits:                                                        
            cpu: "1"                                                     
            memory: 2Gi                                                  
          requests:                                                      
            cpu: 100m                                                    
            memory: 1Gi                                                  
......
```
![1686746538476](https://github.com/k3s-io/k3s/assets/82639323/4b428ac7-8a35-46cb-9766-2b257c71d26b)
![1686746514691](https://github.com/k3s-io/k3s/assets/82639323/4afc9aec-34ae-4c9a-9705-2f95b8f89c9e)

The environment I deployed is as follows:

![image](https://github.com/k3s-io/k3s/assets/82639323/8ce02b82-3923-4036-95a7-edf31df0e661)

The deployment configuration of k3s is as follows:
```
ExecStart=/usr/local/bin/k3s \
    agent \
        '--datastore-endpoint=mysql://xxxxx/k3s_new' \
        '--docker' \
        '--cluster-cidr' \
        '10.30.0.0/16' \
        '--service-cidr' \
        '10.30.0.0/16' \
        '--cluster-dns' \
        '10.30.0.2' \
        '--tls-san' \
        '172.168.30.31' \
        '--kube-apiserver-arg' \
        'service-node-port-range=10000-65000' \
        '--no-deploy' \
        'traefik' \
        '--write-kubeconfig' \
        '/root/.kube/config' \
        '--write-kubeconfig-mode' \
        '666' \
        '--kubelet-arg=kube-reserved=cpu=500m,memory=1Gi,ephemeral-storage=2Gi' \
        '--kubelet-arg=system-reserved=cpu=200m,memory=1Gi' \
        '--kubelet-arg=eviction-hard=memory.available<300Mi,nodefs.available<10%' \
```

docker 部署使用的 Cgroup Driver: `cgroupfs`
![image](https://github.com/k3s-io/k3s/assets/82639323/3b744f16-ca26-4050-aa14-ed6eeb3ed951)
