### ISSUE TITLE
[k3s-upgrade]  Upgrade broken when multiple processes match pattern `k3s .*(server|agent)`

### ISSUE THREAD

**Issue by tuupola** [k3s-io/k3s#7809]
**Environmental Info:**
K3s Version: 
v1.21.5-k3s2 

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04.3 LTS 

Cluster Configuration: 
1 server

**Describe the bug:**

Upgrade process is broken if a node is running any process where a commandline switch contains the string `"k3s"`. Culprit is too wide regexp on the following line which wrongly detects multiple running K3S instances.

https://github.com/k3s-io/k3s-upgrade/blob/master/scripts/upgrade.sh#L15

If the script detects multiple pids it will do a fatal exit. This causes the upgrade process to get stuck and requires manual intervention to get the node working properly again.

https://github.com/k3s-io/k3s-upgrade/blob/master/scripts/upgrade.sh#L25

Example from one of our affected systems:

```
$ ps -ef | grep -E "k3s .*(server|agent)" | grep -E -v "(init|grep|channelserver|supervise-daemon)"
 1460 root      1d19 {k3s-server} /usr/local/bin/k3s server
 6209 root     26:20 /usr/local/bin/zfs-driver --nodename=xx-yyyy-zzzzzzzzzz.k3s --endpoint=unix:///plugin/csi.sock --plugin=agent
``` 

A quick and dirty fix would be to add yet another entry to the exclusion list.

```
  K3S_PID=$(ps -ef | grep -E "k3s .*(server|agent)" | grep -E -v "(init|grep|channelserver|supervise-daemon|zfs-driver)" | awk '{print $2}')
```

However this approach would only fix our specific case and is not universal. In the end the exclusion list would grow indefinitily. Better approach would be to make the original regexp more accurate.  We could for example assume binaries are installed in `bin/` folder.

```
  K3S_PID=$(ps -ef | grep -E "bin\/k3s .*(server|agent)" | grep -E -v "(init|grep|channelserver|supervise-daemon)"" | awk '{print $2}')
```

Also instead of exiting fatally when multiple pids are found, could check each pid if binary name is `k3s`.

**Comment by brandond** [comment]
> Upgrade process is broken if a node is running any process where a commandline switch contains the string "k3s"

To be fair, it's specifically looking for `k3s .*(server|agent)` not just `k3s`. False positives have so far been pretty rare but your args here definitely match that pattern: `--nodename=xx-yyyy-zzzzzzzzzz.k3s --endpoint=unix:///plugin/csi.sock --plugin=agent`. Do your nodes really use .k3s as the domain name?

> We could for example assume binaries are installed in bin/ folder.

The upgrade image is designed to be as flexible as possible, so it tries not to make too many assumptions about the host, and bail out if it cannot locate the correct binary to replace. Perhaps anchoring the k3s portion of the pattern to the end of the first argument would be safe, though.

**Comment by tuupola** [comment]
> Do your nodes really use .k3s as the domain name?

Yes.

There is an old bug with similar problem: https://github.com/k3s-io/k3s/issues/2007

**Comment by tuupola** [comment]
Ok super, thanks!

Quickly testing this might work too: `grep -E "k3s.*(\s+server\s+|\s+agent\s+)"`

**Comment by brandond** [comment]
I was thinking `(^|/)k3s .*(server|agent)`

**Comment by brandond** [comment]
Will require an RC tag to test.

**Comment by VestigeJ** [comment]
Trying to validate this fix but hitting an issue with the pods. This may be related to the most recent .12 SUC upgrade images missing some related assets but I'm unsure where to isolate the upgrade.sh within the pods I'd assume? Please advise @brandond 

$ kgp -n system-upgrade
```
NAME                                                              READY   STATUS    RESTARTS   AGE
apply-server-plan-on-ip-172-31-29-94-with-6a0821fc1c84e95-2vm64   0/1     Error     0          17m
apply-server-plan-on-ip-172-31-29-94-with-6a0821fc1c84e95-4q2qk   0/1     Error     0          6m7s
apply-server-plan-on-ip-172-31-29-94-with-6a0821fc1c84e95-9jh2j   0/1     Error     0          16m
apply-server-plan-on-ip-172-31-29-94-with-6a0821fc1c84e95-c4vdz   0/1     Error     0          11m
apply-server-plan-on-ip-172-31-29-94-with-6a0821fc1c84e95-d9dc7   0/1     Error     0          17m
apply-server-plan-on-ip-172-31-29-94-with-6a0821fc1c84e95-hz85g   0/1     Error     0          15m
apply-server-plan-on-ip-172-31-29-94-with-6a0821fc1c84e95-nwb8t   0/1     Error     0          14m
apply-server-plan-on-ip-172-31-29-94-with-6a0821fc1c84e95-zbfc5   0/1     Error     0          16m
system-upgrade-controller-5dfb565685-s7fvg                        1/1     Running   0          18m
```

Getting the logs from one of the pods 

$ k logs pod/apply-server-plan-on-ip-172-31-29-94-with-6a0821fc1c84e95-2vm64 -n 
```
system-upgrade
Defaulted container "upgrade" out of: upgrade, cordon (init)
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E -v '(init|grep|channelserver|supervise-daemon)'
+ awk '{print $2}'
+ grep -E '( |/)k3s .*(server|agent)'
+ K3S_PID=10196
+ echo 10196
+ wc -w
+ '[' 1 '!=' 1 ]
+ '[' -z 10196 ]
+ wc -w
+ echo 10196
+ '[' 1 '!=' 1 ]
+ ps -p 10196 -o 'ppid='
+ awk '{print $1}'
+ K3S_PPID=1
+ info 'K3S binary is running with pid 10196, parent pid 1'
+ echo '[INFO] ' 'K3S binary is running with pid 10196, parent pid 1'
+ '[' 1 '!=' 1 ]
+ '[' 10196 '==' 1 ]
[INFO]  K3S binary is running with pid 10196, parent pid 1
+ awk 'NR==1 {print $1}' /host/proc/10196/cmdline
[INFO]  Comparing old and new binaries
+ K3S_BIN_PATH=/usr/local/bin/k3s
+ '[' -z /usr/local/bin/k3s ]
+ return
+ replace_binary
+ NEW_BINARY=/opt/k3s
+ FULL_BIN_PATH=/host/usr/local/bin/k3s
+ '[' '!' -f /opt/k3s ]
+ info 'Comparing old and new binaries'
+ echo '[INFO] ' 'Comparing old and new binaries'
+ sha256sum /opt/k3s /host/usr/local/bin/k3s
+ BIN_CHECKSUMS='f1fa8a48a0e8390cad239cac9a17d17a1ca2fa124a05411d6aad102c2c3e45f4  /opt/k3s
5964dae1b062d7c4f7e622e777acd2d1223cc08a7ec3ad09f4240b394ba5a56f  /host/usr/local/bin/k3s'
+ '[' 0 '!=' 0 ]
+ echo 'f1fa8a48a0e8390cad239cac9a17d17a1ca2fa124a05411d6aad102c2c3e45f4  /opt/k3s
5964dae1b062d7c4f7e622e777acd2d1223cc08a7ec3ad09f4240b394ba5a56f  /host/usr/local/bin/k3s'
+ awk '{print $1}'
+ uniq
+ wc -l
+ BIN_COUNT=2
+ '[' 2 '==' 1 ]
+ /opt/k3s+  -v
grep -Po 'k3s version v\K[\d.]+'
grep: unrecognized option: P
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A|B|C N] { PATTERN | -e PATTERN... | -f FILE... } [FILE]...

Search for PATTERN in FILEs (or stdin)

        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -R      Recurse and dereference symlinks
        -i      Ignore case
        -w      Match whole words only
        -x      Match whole lines only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file
+ NEW_BIN_SEMVER=
```

**Comment by brandond** [comment]
@osodracnai this is a regression caused by https://github.com/k3s-io/k3s-upgrade/pull/66 - I forgot that the BusyBox grep doesn't support PCRE's with the -P flag.

**Comment by VestigeJ** [comment]
Hitting a new problem on the semver comparison

```
k logs pod/apply-server-plan-on-ip-172-31-31-241-with-c28aa30ddb220b-pjzzc -n system-upgrade
Defaulted container "upgrade" out of: upgrade, cordon (init)
+ upgrade
+ get_k3s_process_info
+ grep -E '( |/)k3s .*(server|agent)'
+ awk '{print $2}'
+ grep -E -v '(init|grep|channelserver|supervise-daemon)'
+ ps -ef
+ K3S_PID=53819
+ wc -w
+ echo 53819
+ '[' 1 '!=' 1 ]
+ '[' -z 53819 ]
+ echo 53819
+ wc -w
+ '[' 1 '!=' 1 ]
+ ps+ awk '{print $1}'
 -p 53819 -o 'ppid='
[INFO]  K3S binary is running with pid 53819, parent pid 1
+ K3S_PPID=1
+ info 'K3S binary is running with pid 53819, parent pid 1'
+ echo '[INFO] ' 'K3S binary is running with pid 53819, parent pid 1'
+ '[' 1 '!=' 1 ]
+ '[' 53819 '==' 1 ]
+ awk 'NR==1 {print $1}' /host/proc/53819/cmdline
+ K3S_BIN_PATH=/usr/local/bin/k3s
+ '[' -z /usr/local/bin/k3s ]
+ return
+ replace_binary
+ NEW_BINARY=/opt/k3s
+ FULL_BIN_PATH=/host/usr/local/bin/k3s
+ '[' '!' -f /opt/k3s ]
+ info 'Comparing old and new binaries'
+ echo '[INFO] ' 'Comparing old and new binaries'
[INFO]  Comparing old and new binaries
+ sha256sum /opt/k3s /host/usr/local/bin/k3s
+ BIN_CHECKSUMS='57778330175bc566109bd4b628026ce04bb409253ba08c583ecf84441977cec0  /opt/k3s
56f834a8978824444cf656c277ecbad3383736ce61483ba18430372207f47e5e  /host/usr/local/bin/k3s'
+ '[' 0 '!=' 0 ]
+ awk '{print $1}'
+ wc -l
+ uniq
+ echo '57778330175bc566109bd4b628026ce04bb409253ba08c583ecf84441977cec0  /opt/k3s
56f834a8978824444cf656c277ecbad3383736ce61483ba18430372207f47e5e  /host/usr/local/bin/k3s'
+ BIN_COUNT=2
+ '[' 2 '==' 1 ]
+ grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+'
+ /opt/k3s -v
+ NEW_BIN_SEMVER=v1.27.4
+ + /host/usr/local/bin/k3s -v
grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+'
+ FULL_BIN_SEMVER=v1.26.7
+ compare_versions v1.26.7 v1.27.4
+ version1=v1.26.7
+ version2=v1.27.4
+ '[' v1.26.7 '=' v1.27.4 ]
+ IFS=.
+ set -- v1 26 7
+ version1_parts=3
+ set -- v1 27 4
+ version2_parts=3
+ '[' 3 -lt 3 ]
+ '[' 3 -lt 3 ]
+ IFS=.
+ set -- v1 26 7
+ version1_parts=3
+ set -- v1 27 4
+ version2_parts=3
+ seq 1 3
+ eval echo '$1
2
3'
+ echo v1
+ 2
/bin/upgrade.sh: eval: line 198: 2: not found
+ 3
/bin/upgrade.sh: eval: line 199: 3: not found
+ num1=v1
```

**Comment by VestigeJ** [comment]
Just updating for visibility - dev is aware of this current state

$ k logs apply-server-plan-on-ip-172-31-30-73-with-fb4a7457fe155f9-6sqzj -n system-upgrade

```
Defaulted container "upgrade" out of: upgrade, cordon (init)
+ upgrade
+ get_k3s_process_info
+ grep -E -v '(init|grep|channelserver|supervise-daemon)'
+ ps -ef
+ grep -E '( |/)k3s .*(server|agent)'
+ awk '{print $2}'
+ K3S_PID=3679
+ wc -w
+ echo 3679
+ '[' 1 '!=' 1 ]
+ '[' -z 3679 ]
+ echo 3679
+ wc -w
+ '[' 1 '!=' 1 ]
+ ps -p 3679 -o 'ppid='
+ awk '{print $1}'
[INFO]  K3S binary is running with pid 3679, parent pid 1
+ K3S_PPID=1
+ info 'K3S binary is running with pid 3679, parent pid 1'
+ echo '[INFO] ' 'K3S binary is running with pid 3679, parent pid 1'
+ '[' 1 '!=' 1 ]
+ '[' 3679 '=' 1 ]
+ awk 'NR==1 {print $1}' /host/proc/3679/cmdline
[INFO]  Comparing old and new binaries
+ K3S_BIN_PATH=/usr/local/bin/k3s
+ '[' -z /usr/local/bin/k3s ]
+ return
+ replace_binary
+ NEW_BINARY=/opt/k3s
+ FULL_BIN_PATH=/host/usr/local/bin/k3s
+ '[' '!' -f /opt/k3s ]
+ info 'Comparing old and new binaries'
+ echo '[INFO] ' 'Comparing old and new binaries'
+ sha256sum /opt/k3s /host/usr/local/bin/k3s
+ BIN_CHECKSUMS='e88f1e29f50da2a832978ad217cdb6693a96ced42bc1c4f2237ebbc7b68ddd85  /opt/k3s
e9a240d72181bbeccffe941055f63d7a1d7a1970f66954c45c1545442bd009ee  /host/usr/local/bin/k3s'
+ '[' 0 '!=' 0 ]
+ echo 'e88f1e29f50da2a832978ad217cdb6693a96ced42bc1c4f2237ebbc7b68ddd85  /opt/k3s
e9a240d72181bbeccffe941055f63d7a1d7a1970f66954c45c1545442bd009ee  /host/usr/local/bin/k3s'
+ awk '{print $1}'
+ uniq
+ wc -l
+ BIN_COUNT=2
+ '[' 2 '=' 1 ]
+ set +e
+ /opt/k3s -v+ grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+'

+ NEW_BIN_SEMVER=v1.27.4
+ + /host/usr/local/bin/k3s -v
grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+'
+ FULL_BIN_SEMVER=v1.26.7
+ compare_versions v1.26.7 v1.27.4
+ version1=v1.26.7
+ version2=v1.27.4
+ '[' v1.26.7 '=' v1.27.4 ]
+ IFS=.
+ set -- v1 26 7
+ version1_parts=3
+ set -- v1 27 4
+ version2_parts=3
+ '[' 3 -lt 3 ]
+ '[' 3 -lt 3 ]
+ IFS=.
+ set -- v1 26 7
+ version1_parts=3
+ set -- v1 27 4
+ version2_parts=3
+ seq 1 3
+ num1=v1
+ shift
+ num2=27
+ shift
+ echo+  v1
sed 's/^0*//'
+ num1=v1
+ + sed 's/^0*//'
echo 27
+ num2=27
+ '[' -z v1 ]
+ '[' -z 27 ]
+ '[' v1 -lt 27 ]
sh: v1: out of range
+ '[' v1 -gt 27 ]
sh: v1: out of range
+ return 0
+ '[' 0 -eq 1 ]
+ /opt/k3s kubectl version '--client=true'+  -o yaml
cut '-d"' -f2
+ grep -Eo 'buildDate:[[:space:]]+"([^"]+)'
time="2023-07-26T17:14:32Z" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
time="2023-07-26T17:14:32Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/af49417e180a039c71be2f5c646953bff7072d4b7d38cdd075239bef823cc6f7"
+ NEW_BIN_RELEASE_DATE=2023-07-25T22:00:15Z
+ /host/usr/local/bin/k3s kubectl version '--client=true'+ cut '-d"' -f2
 -o yaml
+ grep -Eo 'buildDate:[[:space:]]+"([^"]+)'
time="2023-07-26T17:14:34Z" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
time="2023-07-26T17:14:34Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/a11a8c9d18d5ad4c708edfbd71d89e454517446384945db123f2a7da555b8ff1"
+ FULL_BIN_RELEASE_DATE=2023-07-25T22:46:58Z
+ compare_build_dates 2023-07-25T22:46:58Z 2023-07-25T22:00:15Z
+ convert_date_format 2023-07-25T22:46:58Z
+ date_str=2023-07-25T22:46:58Z
+ echo 2023-07-25T22:46:58Z
+ sed 's/T/ /; s/Z//'
+ build_date1='2023-07-25 22:46:58'
+ convert_date_format 2023-07-25T22:00:15Z
+ date_str=2023-07-25T22:00:15Z
+ + echo 2023-07-25T22:00:15Z
sed 's/T/ /; s/Z//'
+ build_date2='2023-07-25 22:00:15'
+ date -u -d '2023-07-25 22:46:58' '+%s'
+ timestamp1=1690325218
+ '[' -z 1690325218 ]
+ date -u -d '2023-07-25 22:00:15' '+%s'
+ timestamp2=1690322415
+ '[' -z 1690322415 ]
+ '[' 1690325218 -le 1690322415 ]
+ return 1
+ '[' 1 -eq 1 ]
+ echo 'Error: Current build date 2023-07-25T22:46:58Z is more recent than 2023-07-25T22:00:15Z'
+ exit 1
Error: Current build date 2023-07-25T22:46:58Z is more recent than 2023-07-25T22:00:15Z
```

**Comment by VestigeJ** [comment]
##Environment Details
VERSION=v1.26.7-rc3+k3s1
VERSION=v1.27.4-rc3+k3s1

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

ami-097a2df4ac947655f

Linux 5.15.0-1019-aws x86_64 GNU/Linux 

PRETTY_NAME="Ubuntu 22.04.1 LTS"
 
*Cluster Configuration:*

```
NAME               STATUS   ROLES                       AGE   VERSION
ip-9-9-9-1         Ready    control-plane,etcd,master   19m   v1.27.4-rc3+k3s1
ip-9-9-9-3         Ready    control-plane,etcd,master   18m   v1.27.4-rc3+k3s1
ip-9-9-9-5         Ready    control-plane,etcd,master   18m   v1.27.4-rc3+k3s1 
```

*Config.yaml:*
```
server: https://9.9.9.1:6443
write-kubeconfig-mode: 644
debug: true
token: overmorrowslostmanual
protect-kernel-defaults: true
```

<details><summmary><h4>Validation</h4></summary>

```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ conf //sudo vim /etc/rancher/k3s/config.yaml
$ sudo INSTALL_K3S_VERSION=v1.26.7-rc3+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ wget https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml
$ vim system-upgrade-controller.yaml //attention  image: rancher/system-upgrade-controller:v0.13.0 view full file below 
$ set_labels //kubectl label node -l node-role.kubernetes.io/master==true k3s-upgrade=server
$ k apply -f system-upgrade-controller.yaml 
$ vim plan.yaml //view file below
$ get_fluent //audit your curls don't just send rando http to shells 👀 
./install-fluent.sh 
$ sudo vim /lib/systemd/system/k3s-fluent-k3s.service //view file contents below
$ sudo vim /etc/fluent-bit/agent.conf //view file contents below
$ sudo mv /opt/fluent-bit/bin/fluent-bit /opt/fluent-bit/bin/fluent-bit-k3s //renaming the binary to aid in false positive on the grep
$ sudo systemctl enable k3s-fluent-k3s.service --now //activate the service so it's returned by the ps output
$ set_kubefig //export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ kgn //kubectl get nodes
$ kgp -A //kubectl get pods -A
$ k apply -f plan.yaml // kubectl apply -f plan.yaml 
$ w2 kgn //watch nodes status changes and version changes during upgrade
$ ps -ef | grep -E "k3s .*(server|agent)" | grep -E -v "(init|grep|channelserver|supervise-daemon)"
$ kg events -n system-upgrade
$ ps -ef | grep -E "k3s .*(server|agent)" | grep -E -v "(init|grep|channelserver|supervise-daemon)"
$ get_report //generate this template
```

**Results:**

Cluster SUC upgrade passed with multiple process values matching the upgrades checks

</details>

**Additional context / logs:**

```
set_labels() {
    _product="${1:-$PRODUCT}"
    has_bin kubectl
    kubectl label node -l node-role.kubernetes.io/master==true "${_product}"-upgrade=server 
    kubectl label node -l node-role.kubernetes.io/master!=true "${_product}"-upgrade=agent
}
```

$ cat system-upgrade-controller.yaml

``` 
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: system-upgrade
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: v1
data:
  SYSTEM_UPGRADE_CONTROLLER_DEBUG: "false"
  SYSTEM_UPGRADE_CONTROLLER_THREADS: "2"
  SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS: "900"
  SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT: "99"
  SYSTEM_UPGRADE_JOB_IMAGE_PULL_POLICY: Always
  SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: rancher/kubectl:v1.25.4
  SYSTEM_UPGRADE_JOB_PRIVILEGED: "true"
  SYSTEM_UPGRADE_JOB_TTL_SECONDS_AFTER_FINISH: "900"
  SYSTEM_UPGRADE_PLAN_POLLING_INTERVAL: 15m
kind: ConfigMap
metadata:
  name: default-controller-env
  namespace: system-upgrade
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  selector:
    matchLabels:
      upgrade.cattle.io/controller: system-upgrade-controller
  template:
    metadata:
      labels:
        upgrade.cattle.io/controller: system-upgrade-controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - env:
        - name: SYSTEM_UPGRADE_CONTROLLER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['upgrade.cattle.io/controller']
        - name: SYSTEM_UPGRADE_CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: default-controller-env
        image: rancher/system-upgrade-controller:v0.13.0
        imagePullPolicy: IfNotPresent
        name: system-upgrade-controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /etc/ssl
          name: etc-ssl
          readOnly: true
        - mountPath: /etc/pki
          name: etc-pki
          readOnly: true
        - mountPath: /etc/ca-certificates
          name: etc-ca-certificates
          readOnly: true
        - mountPath: /tmp
          name: tmp
      serviceAccountName: system-upgrade
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/ssl
          type: DirectoryOrCreate
        name: etc-ssl
      - hostPath:
          path: /etc/pki
          type: DirectoryOrCreate
        name: etc-pki
      - hostPath:
          path: /etc/ca-certificates
          type: DirectoryOrCreate
        name: etc-ca-certificates
      - emptyDir: {}
        name: tmp
```

$ cat plan.yaml 

```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.27.4-rc3-k3s1
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.27.4-rc3-k3s1
```

$ sudo cat /lib/systemd/system/k3s-fluent-k3s.service
```
[Unit]
Description=Fluent Bit
Documentation=https://docs.fluentbit.io/manual/
Requires=network.target
After=network.target

[Service]
Type=simple
EnvironmentFile=-/etc/sysconfig/fluent-bit
EnvironmentFile=-/etc/default/fluent-bit
ExecStart=/opt/fluent-bit/bin/fluent-bit-k3s -c //etc/fluent-bit/agent.conf
Restart=always

[Install]
WantedBy=multi-user.target
```

$ sudo cat /etc/fluent-bit/agent.conf

```
[SERVICE]
    Flush        1
    Log_Level    trace
    Parsers_File parsers.conf

[INPUT]
    Name            systemd
    Tag             host.*
    Systemd_Filter  _SYSTEMD_UNIT=k3s.service

[OUTPUT]
    Name   file
    Match  *
    Path /home/ubuntu
```
