### ISSUE TITLE
[Release-1.26] - Helm controller bootstrap option is broken when using port other than 6443

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#7871]
Backport fix for Helm controller bootstrap option is broken when using port other than 6443

* #7835

**Comment by aganesh-suse** [comment]
Ubuntu 22.4

1 server. 
Validation: 
<details>

```
cat config.yaml
token: secret
https-listen-port: 6543
write-kubeconfig-mode: "0644"
node-label:
- k3s-upgrade=server

$ curl -sfL https://get.k3s.io | sudo INSTALL_K3S_COMMIT='66bdd32d193c70ac5e1aa8a4fc7751024db06025' sh -s - server
```
Deploy boostrap chart
```
cat web.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: apache
  namespace: kube-system
spec:
  bootstrap: true
  repo: https://charts.bitnami.com/bitnami
  chart: apache
  targetNamespace: web
  valuesContent: |-
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: www.example.com
    metrics:
      enabled: true
```

```
$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-76d776f6f9-zsgjk   1/1     Running     0          2m16s
kube-system   coredns-59b4f5bbd5-z7q49                  1/1     Running     0          2m16s
kube-system   helm-install-traefik-crd-6lwqr            0/1     Completed   0          2m16s
kube-system   helm-install-traefik-rf5kl                0/1     Completed   1          2m16s
kube-system   svclb-traefik-fd4db6da-v564l              2/2     Running     0          117s
kube-system   metrics-server-68cf49699b-bmrm6           1/1     Running     0          2m16s
kube-system   helm-install-apache-6bmrw                 0/1     Completed   0          2m5s
kube-system   traefik-57c84cf78d-5jxvr                  1/1     Running     0          118s
web           apache-7d4f4c6666-5mvt9                   2/2     Running     0          115s

$ k3s -v
k3s version v1.26.6+k3s-66bdd32d (66bdd32d)
go version go1.19.10
```

</details>

Reproduction:
<details>

```
$ k3s -v
k3s version v1.26.6+k3s1 (3b1919b0)
go version go1.19.10

$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS             RESTARTS      AGE
kube-system   coredns-59b4f5bbd5-fvmdq                  1/1     Running            0             3m19s
kube-system   local-path-provisioner-76d776f6f9-2hfjp   1/1     Running            0             3m19s
kube-system   helm-install-traefik-crd-kbr2r            0/1     Completed          0             3m20s
kube-system   helm-install-traefik-qcppc                0/1     Completed          1             3m20s
kube-system   svclb-traefik-20c9ab2b-59fx9              2/2     Running            0             3m5s
kube-system   traefik-57c84cf78d-qwc5s                  1/1     Running            0             3m5s
kube-system   metrics-server-68cf49699b-64v4q           1/1     Running            0             3m19s
kube-system   helm-install-apache-gwcqw                 0/1     CrashLoopBackOff   4 (57s ago)   2m43s
```

</details>
