### ISSUE TITLE
K3S fails to start with error "yaml: line 9: could not find expected ':'" when install config file is used

### ISSUE THREAD

**Issue by MasterMann** [k3s-io/k3s#7932]
**Environmental Info:**
K3s Version: ```v1.27.3+k3s1 (fe9604ca)```

Node(s) CPU architecture, OS, and Version: 
```Linux <hostname> 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux```

Cluster Configuration:
1 server (node)

**Describe the bug:**
K3S systemd service fails to start when using a custom configuration file.
Install arguments:
```curl -sfL https://get.k3s.io | sh -s - --config=<data-dir-path>/cluster-config.yml```

cluster-config.yml contents:
```
node-name: "[redacted]"
cluster-init: true
flannel-backend: "wireguard-native"
flannel-external-ip: true
node-external-ip: "[redacted]"
prefer-bundled-bin: true
write-kubeconfig: "/home/[redacted]/.kube/config"
debug: true
data-dir: "[redacted]"
secrets-encryption: true
cluster-cidr: "10.1.0.0/16"
service-cidr: "10.2.0.0/16"
service-node-port-range: "20000-59999"
cluster-dns: "10.2.0.1"
cluster-domain: "[redacted]"
default-local-storage-path: "<data-dir-path>/storage-root"
protect-kernel-defaults: true
kube-apiserver-arg:
  - "admission-control-config-file=<data-dir-path>/config/pod-admission.yml"
  - "audit-log-path=<data-dir-path>/server/logs/audit.log"
  - "audit-policy-file=<data-dir-path>/config/server-logs.yml"
  - "audit-log-maxage=10"
  - "audit-log-maxbackup=5"
  - "audit-log-maxsize=100"
  - "request-timeout=300s"
  - "service-account-lookup=true"
kube-controller-manager-arg:
  - "terminated-pod-gc-threshold=10"
  - "use-service-account-credentials=true"
kubelet-arg:
  - "streaming-connection-idle-timeout=5m"
  - "make-iptables-util-chains=true"
```

<data-dir-path>/server/manifests also contains NetworkPolicy configs.
All yml files have been checked via https://codebeautify.org/yaml-validator and have valid syntax.

**Steps To Reproduce:**
1. ```apt install curl -y```
2. add to file: ```/etc/sysctl.d/90-kubelet.conf```:
```
vm.panic_on_oom=0
vm.overcommit_memory=1
kernel.panic=10
kernel.panic_on_oops=1
kernel.keys.root_maxbytes=25000000
```
3. ```sysctl -p /etc/sysctl.d/90-kubelet.conf```
4. add to file: ```<data-dir-path>/server/manifests/traffic-allow-intra-system.yml```:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: intra-namespace
  namespace: kube-system
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-system
```
5. add to file: ```<data-dir-path>/server/manifests/traffic-allow-dns-ingress.yml```:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-network-dns-policy
  namespace: kube-system
spec:
  ingress:
    ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
    - Ingress
```
6. add to file: ```<data-dir-path>/server/manifests/traffic-allow-metrics-access.yml```:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-metrics-server
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: metrics-server
  ingress:
    - {}
  policyTypes:
    - Ingress
```
7. add to file: ```<data-dir-path>/server/manifests/traffic-allow-svclb-access.yml```:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-svclbtraefik-ingress
  namespace: kube-system
spec:
  podSelector: 
    matchLabels:
      svccontroller.k3s.cattle.io/svcname: traefik
  ingress:
    - {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-traefik-v121-ingress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  ingress:
    - {}
  policyTypes:
    - Ingress
```
8. add to file: ```<data-dir-path>/config/pod-admission.yml```:
```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1beta1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "baseline"
      enforce-version: "latest"
      audit: "restricted"
      audit-version: "latest"
      warn: "restricted"
      warn-version: "latest"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: ["kube-system"]
```
9. add to file: ```<data-dir-path>/config/server-logs.yml```:
```
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
```
10. add to file: ```<data-dir-path>/config/cluster-config.yml```:
(see cluster-config.yml contents above)
11. run cmd: ```curl -sfL https://get.k3s.io | sh -s - --config=<data-dir-path>/config/cluster-config.yml```

**Expected behavior:**
K3S starts successfully.

**Actual behavior:**
```
[INFO]  Finding release for channel stable
[INFO]  Using v1.27.3+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.27.3+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.27.3+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.
```

**Additional context / logs:**
- journalctl -xe output:
```
Jul 08 09:45:47 localtest sh[1860]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Jul 08 09:45:47 localtest sh[1861]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Jul 08 09:45:48 localtest k3s[1864]: time="2023-07-08T09:45:48+03:00" level=fatal msg="yaml: line 9: could not find expected ':'"
Jul 08 09:45:48 localtest systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
```
- tried removing files from ```<data-dir-path>/server/manifests```, other yml files except for cluster-config.yml, tried launching with cmdline args instead of config file, no changes.
