### ISSUE TITLE
使用k3d部署mysql,mysql日志无法写入除安装目录(/var/lib/mysql)以外的目录,导致启动不成功

### ISSUE THREAD

**Issue by twbworld** [k3s-io/k3s#7959]
## 问题
使用k3d部署mysql,mysql日志无法写入除安装目录(/var/lib/mysql)以外的目录,导致启动不成功,而且没有相关报错信息, 退出代码为`exit(1)`;

但是日志保存路径为mysql安装目录,则启动成功,如:  

``` txt
[mysqld]
log_error = /var/www/logs/error.log
```
改为
``` txt
[mysqld]
log_error = /var/lib/mysql/error.log
```
> 本人怀疑是k3s镜像出现问题, 感兴趣的大佬可以帮我查查问题所在, 衷心感谢!

## 环境
k3s image version: rancher/k3s:v1.26.6-k3s1
k3d version: v5.5.1

## k8s配置:
```  yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    log_error = /var/www/logs/error.log #!!!指定路径, 如果这改为"/var/lib/mysql/error.log"则启动成功
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
spec:
  ...
  serviceName: mysql-svc
  selector:
    matchLabels:
      app: mysql-container
  volumeClaimTemplates:
    - metadata:
        name: mysql-log
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: mysql-container
    spec:
      volumes:
        - name: conf
          configMap:
            name: mysql-config
      containers:
        - name: mysql-container
          image: mysql:8.0-debian
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pwd"
          volumeMounts:
            - name: conf
              mountPath: /etc/mysql/conf.d/
            - name: mysql-log
              mountPath: /var/www/logs/ #对应log_error配置
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql-container
  clusterIP: None
  ports:
    - port: 3306
```

## 部署后,启动失败
![image](https://github.com/k3s-io/k3s/assets/52546134/1560c949-8f96-43a2-bd65-3f1ddefbdea5)
![image](https://github.com/k3s-io/k3s/assets/52546134/7da72442-c861-41de-8419-1badd970b79e)
![image](https://github.com/k3s-io/k3s/assets/52546134/3213ede7-e940-4052-82ad-b6b753496929)
