### ISSUE TITLE
Don't set `enable-aggregator-routing=true` when `egress-selector-mode=disabled`

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7971]
> K3s sets the apiserver's `enable-aggregator-routing` flag to true by default, in order to allow the apiserver to tunnel connections to cluster services, as described at https://docs.k3s.io/installation/network-options#control-plane-egress-selector-configuration.

> If you want to disable this, and make use of API services outside the cluster, you should start the servers with `--egress-selector-mode=agent --kube-apiserver-arg=enable-aggregator-routing=false`

_Originally posted by @brandond in https://github.com/k3s-io/k3s/discussions/7829#discussioncomment-6286219_

We shouldn't set this flag to true when not using the pod or cluster egress selector modes, as it disables some functionality that doesn't need to be disabled if we're not using the egress tunnel to route connections to service endpoints.

Specifically, this breaks routing to APIServices and Webhooks hosted behind ExternalName Services, as the `enable-aggregator-routing` flag tells the apiserver to connect directly to service endpoints - but ExternalName services don't have endpoints.

### Steps to Reproduce:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: kube-system
spec:
  type: ExternalName
  externalName: httpbin.org
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-mutating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      namespace: kube-system
      name: example-service
      path: /status/502
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: example-mutating-webhook.k3s.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - secrets
    scope: Namespaced
  sideEffects: NoneOnDryRun
  timeoutSeconds: 5
```

After deploying the above, note the following error:
```console
brandond@dev01:~$ kubectl create secret generic -n kube-system test
error: failed to create secret Internal error occurred: failed calling webhook "example-mutating-webhook.k3s.io": 
failed to call webhook: Post "https://example-service.kube-system.svc:443/status/502?timeout=5s": 
unsupported service type "ExternalName"
```

On a fixed release, if you start k3s with the `--egress-selector-mode=disabled` flag, you should get the following error when creating a secret:
```console
brandond@dev01:~$ kubectl create secret generic -n kube-system test
error: failed to create secret Internal error occurred: failed calling webhook "example-mutating-webhook.k3s.io": 
failed to call webhook: Post "https://example-service.kube-system.svc:443/status/502?timeout=5s": 
tls: failed to verify certificate: x509: certificate is valid for httpbin.org, *.httpbin.org, not example-service.kube-system.svc
```
This is an expected error due to using httpbin as a dummy backend for the webhook service.
