### ISSUE TITLE
registries.yaml and imagePullSecret

### ISSUE THREAD

**Issue by strowi** [k3s-io/k3s#8026]
**Environmental Info:**
K3s Version: 

k3s version v1.27.3+k3s1 (fe9604ca)
go version go1.20.5

Node(s) CPU architecture, OS, and Version: 

Linux agent-medium-nbg1-spj 6.4.2-1-default #1 SMP PREEMPT_DYNAMIC Mon Jul 10 10:03:25 UTC 2023 (b97b894) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master, 2 nodes

**Describe the bug:**

Using a registries.yaml with mirror (for registry.gitlab.com) & credentials (for the mirror)

- `crictl pull` on the node works.

BUT in kubernetes:

- `kubectl run --image=...` works (without any imagePullSecret)
- Creating a Deployment with same image, containing imagePullSecret for registry.gitlab.com gives an ImagePullError
- Adding a imagePullSecret for the mirror also breaks.
- imagePullSecret **only** containing the mirror-credentials works!

So it seems the mirror is only useable if there is no imagePullSecret defined for the Pod?

**Steps To Reproduce:**
1. setup a mirror/pull-through docker-registry that requires authentication
1. setup k3s with a registries.yaml:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://core.harbor.$TLD"
    rewrite:
      "^(.*)": "proxy.docker.io/$1"
  gcr.io:
    endpoint:
      - "https://core.harbor.$TLD"
    rewrite:
      "^(.*)": "proxy.gcr.io/$1"
  registry.k8s.io:
    endpoint:
      - "https://core.harbor.$TLD"
    rewrite:
      "^(.*)": "proxy.registry.k8s.io/$1"
  registry.gitlab.com:
    endpoint:
      - "https://core.harbor.$TLD"
    rewrite:
      "^(.*)": "proxy.registry.gitlab.com/$1"

configs:
  "core.harbor.$TLD":
    auth:
      username: "xyz"
      password: "xyz"
```
1. block registry.gitlab.com (e.g. with `/etc/hosts` containing `127.0.0.1 registry.gitlab.com`)
1. create a deployment/pod with image + imagePullSecret for `registry.gitlab.com`.
1. see pod failing with ErrImagePull
1. add credentials for the mirror to the pod
1. see pod still failing to authenticate against the mirror

**Expected behavior:**

Kubernetes should be able to authenticate and pull from the mirror when an imagePullSecret is defined.

**Actual behavior:**

Kubernetes fails authenticating to the mirror. It seems to be always only using the original credentials if present and ignore imagePullSecret for the mirror.

**Additional context / logs:**

I can pull those images fine directly with docker login & pull,  or crictl pull on the node, but k3s fails to do so when there is an imagePullSecret attached. Sadly this makes the mirror kind of unusuable for private registries if i have to delete all imagePullSecrets from a pod.

And Yes it is possible to ONLY add the pullSecret for the mirror, but then the "upstream" server will be ignored completey, which defeats the purpose of a fallback-mirror.

```bash
66m         Normal    Pulling                  pod/workers-scheduler-9b766fd95-skkr7                                      Pulling image "registry.gitlab.com/xyz:tag"
66m         Warning   Failed                   pod/workers-scheduler-9b766fd95-skkr7                                      Failed to pull image "registry.gitlab.com/xyz:tag": rpc error: code = Unknown desc = failed to pull and unpack image "registry.gitlab.com/xyz:tag": failed to resolve reference "registry.gitlab.com/xyz:tag": unexpected status from HEAD request to https://core.harbor.$TLD/v2/proxy.registry.gitlab.com/xyz/manifests/$tag?ns=registry.gitlab.com: 401 Unauthorized
```
