### ISSUE TITLE
Add the documentation for make traefik auto redirect to https

### ISSUE THREAD

**Issue by yodatak** [k3s-io/k3s#8071]
Aswome job  for make kubernetes easier to all 
I want to be able to find easy on k3s documentation how to auto redirect to https with traefik without modifing manifest 

Like this way 
`kubectl apply -f httpstraefik.yaml`
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        tls:
          enabled: true
      web:
        redirectTo: websecure
```

Its a common issue why people don't use the bundled traefik because they can't find how to make http to https redirection 

Like we see in some forums 
https://stackoverflow.com/questions/68575472/k3s-redirect-http-to-https/71989847#71989847
