### ISSUE TITLE
[Release-1.26] - GO 1.20.6 breaks cri-dockerd

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8102]
Backport fix for GO 1.20.6 breaks cri-dockerd

* #8089

**Comment by mdrahman-suse** [comment]
### Validated on release-1.26 branch with commit 52e2c08a
 
## Environment Details

 
*Infrastructure*
- [x] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
cluster-init: true
docker: true
```
 
*Additional files*

- nginx-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
3. Ensure k3s is up and running
4. Deploy `nginx-deployment.yaml`
5. Check cri-dockerd version
6. Check deployments
```
$ kubectl get pods -A | grep nginx
default       nginx-deployment-85996f8dbd-nwf9r         1/1     Running     0          11s
default       nginx-deployment-85996f8dbd-pjssq         1/1     Running     0          11s
```
 
**Replication Results:**
- k3s version used for replication:

```
k3s version v1.26.7+k3s1 (e47cfc09)
go version go1.20.6
```
 

- cri-dockerd version from logs
```
cri-dockerd version v0.3.2-0.20230123224936-bcd78c2d21d8 (HEAD)
```
- Execute command in Pod's container via kubectl exec, observed the error `http: invalid Host header`
```
$ kubectl exec -it -n default nginx-deployment-85996f8dbd-nwf9r -- bash
error: Internal error occurred: error executing command in container: http: invalid Host header
```
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.26.7+k3s-52e2c08a (52e2c08a)
go version go1.20.6
```


- cri-dockerd version from logs
```
cri-dockerd version v0.3.4-k3s1 (HEAD)
```

- Execute command in Pod's container via kubectl exec, observed no error
```
$ kubectl exec -it -n default nginx-deployment-85996f8dbd-nwf9r -- bash
root@nginx-deployment-85996f8dbd-nwf9r:/#
```
 
**Additional context / logs:**
- Tested on new install and upgrades
