### ISSUE TITLE
[Release-1.24] - GO 1.20.6 breaks cri-dockerd

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8104]
Backport fix for GO 1.20.6 breaks cri-dockerd

* #8089

**Comment by mdrahman-suse** [comment]
### Validated on release-1.24 branch with commit 9fc75e74
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
cluster-init: true
docker: true
```
 
*Additional files*

- nginx-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
3. Ensure k3s is up and running
4. Deploy `nginx-deployment.yaml`
5. Check cri-dockerd version
6. Check deployments
```
$ kubectl get pods -A | grep nginx
default       nginx-deployment-6595874d85-kk8x6         1/1     Running     0          4m
default       nginx-deployment-6595874d85-vf78c         1/1     Running     0          4m
```
 
**Replication Results:**
- k3s version used for replication:

```
k3s version v1.24.16+k3s1 (ccae12ed)
go version go1.20.6
```
 

- cri-dockerd version from logs
```
cri-dockerd version v0.3.2-0.20230123224751-84abd1adca2f (HEAD)
```
- Execute command in Pod's container via kubectl exec, observed the error `http: invalid Host header`
```
$ kubectl exec -it -n default nginx-deployment-6595874d85-kk8x6 -- bash
error: Internal error occurred: error executing command in container: http: invalid Host header
```
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.24.16+k3s-9fc75e74 (9fc75e74)
go version go1.20.6
```


- cri-dockerd version from logs
```
cri-dockerd version v0.3.2-0.20230123224751-84abd1adca2f (HEAD)
```

- Execute command in Pod's container via kubectl exec, observed no error
```
$ kubectl exec -it -n default nginx-deployment-6595874d85-kk8x6 -- bash
root@nginx-deployment-6595874d85-kk8x6:/# 
```
 
**Additional context / logs:**
- Tested on new install and upgrades
