### ISSUE TITLE
Embedded ctr binary tries to push to a private registry URL using HTTP instead of using HTTPS

### ISSUE THREAD

**Issue by aalcaraz97** [k3s-io/k3s#8226]
**Environmental Info:**
K3s Version:
```bash
k3s version v1.27.4+k3s1 (36645e73)
go version go1.20.6
```

Node(s) CPU architecture, OS, and Version: 
```bash
Linux <nodeName> 4.18.0-372.64.1.el8_6.x86_64 #1 SMP Thu Jun 29 14:42:09 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 server node with SQLite DB

**Describe the bug:**
I am installing a K3s server node with SQLite. I install Calico as the cluster CNI.

In my cluster, I deploy a private Docker Registry using the official Docker Registry image (`docker.io/library/registry:2.8.1`). 
I configure the local registry with a TLS cert/key and with basic user/password authentication.
I deploy the private Docker Registry as a Deployment in the cluster, and I expose it using a NodePort Service, which is exposed to the port tcp/30000 in the host.

I want all the other Pods in the K3s cluster to download the images from the private Docker Registry, so I configure it as a mirror in the cluster, using the `/etc/rancher/k3s/registries.yaml` file. These are the file contents:
```yaml
mirrors:
  "localhost:30000":
    endpoint:
      - "https://localhost:30000"
configs:
  "localhost:30000":
    tls:
      ca_file: /etc/rancher/k3s/cert.d/ca.crt
      cert_file: /etc/rancher/k3s/cert.d/registry.crt
      key_file: /etc/rancher/k3s/cert.d/registry.key
```

The `ca_file`, `cert_file` and `key_file` files have been generated manually by me before deploying the private Docker Registry in the cluster.

I use the embedded "ctr" binary to push all the other cluster images into the private Docker Registry. For pushing a image into the private Docker Registry, I perform the following steps:
1) Import the image (which is saved in a TAR file) into the K3s containerd:
```bash
sudo k3s ctr image import --all-platforms <image-tar-path>
```

2) Tag the image to point to the private Docker Registry address (an example using `docker.io/library/alpine:3.18`)
```bash
sudo k3s ctr image tag --force docker.io/library/alpine:3.18 localhost:30000/alpine:3.18
```

3) Push the tagged image into the private Docker Registry (an example using `docker.io/library/alpine:3.18`)
```bash
sudo k3s ctr image push \
--tlscacert /etc/rancher/k3s/cert.d/ca.crt \
--tlscert /etc/rancher/k3s/cert.d/registry.crt \
--tlskey /etc/rancher/k3s/cert.d/registry.key \
--user ${user}:${password} \
localhost:30000/alpine:3.18
```

I get a ctr error while pushing the image:
```bash
ctr: unexpected status from HEAD request to http://localhost:30000/v2/alpine/blobs/<blob>: 400 Bad Request
```

It seems that ctr is trying to push the image using an HTTP URL instead of an HTTPS URL.

The `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` file has the following content (some spaces have been removed for readability):
```code:yaml
# File generated by k3s. DO NOT EDIT. Use config.toml.tmpl instead.
version = 2

[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/k3s/agent/containerd"
[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = true
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true
  sandbox_image = "rancher/mirrored-pause:3.6"

[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = true

[plugins."io.containerd.grpc.v1.cri".registry.mirrors]

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:30000"]
  endpoint = ["https://localhost:30000"]

[plugins."io.containerd.grpc.v1.cri".registry.configs."localhost:30000".tls]
  ca_file = "/etc/rancher/k3s/cert.d/ca.crt"
  cert_file = "/etc/rancher/k3s/cert.d/registry.crt"
  key_file = "/etc/rancher/k3s/cert.d/registry.key"
```

The `localhost:30000` registry mirror appears to be correctly configured with an HTTPS URL, and with the same config as the one located in the `registries.yaml` file.

The described procedure for pushing an image into the private registry **was working for me in K3s v1.24.10 (the K3s previous version I was using)**. 
I'm not sure if anything has been changed regarding ctr/registries.yaml between the two K3s releases.

Is there any way I can solve this issue? Or any flag in the "ctr" binary that I can use to force the push to use HTTPS addresses? I'm not sure if I'm doing anything wrong here...

**Steps To Reproduce:**

- Install K3S with the following command:
```bash
INSTALL_K3S_SKIP_DOWNLOAD=true \
INSTALL_K3S_SKIP_SELINUX_RPM=true \
INSTALL_K3S_SYMLINK=force \
INSTALL_K3S_EXEC='--config /etc/rancher/k3s/config.yaml' \
install.sh
```
using the following `config.yaml` file:
```yaml
kube-apiserver-arg:
  - 'service-node-port-range=1-65535'
  - 'enable-admission-plugins=NodeRestriction,PodSecurity'
  - 'profiling=false'
  - 'audit-log-path=/var/log/apiserver/audit.log'
  - 'audit-log-maxage=30'
  - 'audit-log-maxbackup=10'
  - 'audit-log-maxsize=100'
  - 'request-timeout=300s'

kube-scheduler-arg:
  - 'profiling=false'

kube-controller-manager-arg:
  - 'profiling=false'
  - 'terminated-pod-gc-threshold=10'
  - 'use-service-account-credentials=true'

kubelet-arg:
  - 'protect-kernel-defaults=true'
  - 'streaming-connection-idle-timeout=5m'
  - 'make-iptables-util-chains=true'

secrets-encryption: true
selinux: true
disable: traefik

flannel-backend: none
disable-network-policy: true
cluster-cidr: 10.42.0.0/16
```

- Deploy Calico CNI
- Deploy a private Docker Registry in the cluster
- Import, tag and push an image into the private Docker Registry using "ctr"

**Expected behavior:**
Images should be pushed to the private Docker Registry using ctr image push

**Actual behavior:**
Images are not being pushed to the private Docker Registry

**Additional context / logs:**
Additional information on how the private Docker Registry is deployed can be provided if required, but nothing has changed from the previous deployments using K3s v1.24.10 (when everything was working)
