### ISSUE TITLE
allowedUnsafeSysctls Kubelet config ignored

### ISSUE THREAD

**Issue by KarstenB** [k3s-io/k3s#8340]
**Environmental Info:**
K3s Version: 
k3s version v1.27.5+k3s1 (8d074ecb)

Node(s) CPU architecture, OS, and Version: 
Linux ryzen 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux

Cluster Configuration:
single-node configuration

**Describe the bug:**
Given the following `/etc/rancher/k3s/config.yaml`:
```yaml
kubelet-arg:
  - 'config=/etc/rancher/k3s/kubelet.config'
```

and the following `/etc/rancher/k3s/kubelet.config`:
```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 99
allowedUnsafeSysctls:
  - 'fs.mqueue.*'
  - 'fs.inotify.*'
  - 'net.ipv6.conf.all.disable_ipv6'
  - 'net.ipv4.conf.all.arp_*'
  - 'net.ipv4.tcp_*'
```

I would expect the following pod yaml to load:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  securityContext:
    sysctls:
    - name: fs.mqueue.msg_max
      value: "16776"
    - name: net.ipv6.conf.all.disable_ipv6
      value: "1"
  restartPolicy: Never
  containers:
    - name: nginx
      image: nginx
```
**Steps To Reproduce:**
1. Update your config.yaml to the given snippet
2. Create the Kubelet config file
3. Restart your k3s
4. Apply the nginx example pod

**Expected behavior:**
I get:
```
Events:
  Type     Reason           Age   From               Message
  ----     ------           ----  ----               -------
  Normal   Scheduled        24s   default-scheduler  Successfully assigned default/nginx to ryzen
  Warning  SysctlForbidden  25s   kubelet            forbidden sysctl: "fs.mqueue.msg_max" not allowlisted
```

**Actual behavior:**
Pod actually starting

**Additional context / logs:**
I updated the maxPods just to see if the config has been used at all, and instead of 110, I get 99 with:
```bash
kubectl get nodes ryzen -o jsonpath='{.status.allocatable.pods}'                                                                                                       
99
```
