### ISSUE TITLE
k3s versions >v1.27.3 ignore Tailscale IPv6 addresses on IPv4-only hosts, causing new fatal errors

### ISSUE THREAD

**Issue by lorenzo-w** [k3s-io/k3s#8459]
**Environmental Info:**
K3s Version: 
```
k3s version v1.27.6+k3s1 (bd04941a)\
go version go1.20.8
```

Node(s) CPU architecture, OS, and Version: 
- `Linux cloudlane-one-s0 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Node only supports IPv4

Cluster Configuration:
3 servers with embedded etcd, 2 agents, affected node is an agent
```yaml
vpn-auth: "name=tailscale,joinKey=OMITTED"
node-external-ip: OMITTED
cluster-cidr: "10.42.0.0/16,2001:cafe:42:0::/56"
service-cidr: "10.43.0.0/16,2001:cafe:42:1::/112"
disable:
  - traefik
  - local-storage
etcd-expose-metrics: true
secrets-encryption: true
kube-apiserver-arg:
  - "oidc-issuer-url=OMITTED"
  - "oidc-client-id=OMITTED"
  - "oidc-groups-claim=groups"
kube-controller-manager-arg:
  - "bind-address=0.0.0.0"
  - "horizontal-pod-autoscaler-tolerance=0.3"
kube-proxy-arg:
  - "metrics-bind-address=0.0.0.0"
kube-scheduler-arg:
  - "bind-address=0.0.0.0"
tls-san: "k8s.cloudlane.one"
kubelet-arg:
  - "node-ip=0.0.0.0"
  - "eviction-hard=memory.available<100Mi,nodefs.available<5%"
  - "eviction-soft=memory.available<300Mi,nodefs.available<10%"
  - "eviction-soft-grace-period=memory.available=1m0s,nodefs.available=10m0s"
  - "eviction-max-pod-grace-period=120"
  - "system-reserved=cpu=200m,memory=400Mi,ephemeral-storage=8Gi"
  - "kube-reserved=cpu=0.3,memory=1.1Gi,ephemeral-storage=4Gi"
```

**Describe the bug:**
Dual stack IP did work on earlier versions of k3s v1.27.x via Tailscale VPN, even if the host system did not support IPv6. With newer versions it seems that k3s does not extract the IPv6 supplied by `tailscale status --json`, but only IPv4. I have several nodes, which don't support IPv6 but my cluster CIDR is dual stack, so updating these nodes renders them unusable.

**Steps To Reproduce:**

- Installed K3s v1.27.3+k3s1 on arbitrary server node + one or more agent-nodes without IPv4 support; with tailscale vpn and a dual stack cluster CIDR; installed via official installer script
- Verified that cluster is working as expected
- Upgraded to v1.27.6+k3s1

**Expected behavior:**
k3s-agent is able to start.

**Actual behavior:**
k3s-agent fails with a fatal error saying that the node IP, which is IPv4 only, is incompatible with dual stack cluster CIDR..

**Additional context / logs:**

Relevant error messages:
```
Sep 26 21:59:36 cloudlane-one-s0 k3s[149080]: time="2023-09-26T21:59:36Z" level=debug msg="Output from tailscale status --json: {\n  \"Version\": \"1.50.0-ta920f0231-geb5b0beea\",\n  \"TUN\": true,\n  \"BackendState\": \"Running\",\n  \"AuthURL\": \"\",\n  \"TailscaleIPs\": [\n    \"100.104.255.34\",\n    \"fd7a:115c:a1e0:ab12:4843:cd96:6268:ff22\"\n  ],\n ... REST OF LINE OMITTED
Sep 26 21:59:36 cloudlane-one-s0 k3s[149080]: time="2023-09-26T21:59:36Z" level=info msg="Node-ip changed to [100.104.255.34] due to VPN"
Sep 26 21:59:36 cloudlane-one-s0 k3s[149080]: time="2023-09-26T21:59:36Z" level=warning msg="VPN provider overrides node-external-ip parameter"
Sep 26 21:59:37 cloudlane-one-s0 k3s[149080]: time="2023-09-26T21:59:37Z" level=fatal msg="cluster-cidr: [10.42.0.0/16 2001:cafe:42::/56] and node-ip: [100.104.255.34], must share the same IP version (IPv4, IPv6 or dual-stack)"
```

As you can see the output of tailscale contains both IP versions, but k3s only picks the IPv4.

I have a suspicion that this commit could be responsible: https://github.com/k3s-io/k3s/commit/f21a01474d2c9c79cfc5e99d9eea4116458dccca
But I am far from fluent in Go, so this should be taken as a mere guess.

The error seems to not happen on host systems supporting IPv6.
