### ISSUE TITLE
failing to retrieve pods with nftables

### ISSUE THREAD

**Issue by ymohl-cl** [k3s-io/k3s#8742]
**Environmental Info:**
K3s Version: 

k3s version v1.27.6+k3s1 (bd04941a)
go version go1.20.8

Node(s) CPU architecture, OS, and Version: 

Linux [my-domain] 6.1.0-13-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

Cluster Configuration:

1 node (vps ovh)
vCores: 4
Ram: 8
Stockage: 80
OS: Debian bookworm
Kube ingress: traefik

**Describe the bug:**

After a fresh installation of k3s, helm and cert-manager, i trying to install prometheus and grafana.

If i disable all rules for the chain forward from nftables, all is work. My certificate is valid and i can connect to the grafana dashboard.

If i use my rules from nftables, the certificaterequest stay lock on: Waiting on certificate issuance from order monitoring/grafana-tls-1-632796568: "pending"

**Steps To Reproduce:**

- Installed K3s: 

``` bash
## Install debian packages
sudo apt update && sudo apt upgrade -y
sudo apt install curl -y
sudo apt install git -y
#sudo apt install mkcert -y

## Install k3s
mkdir -p ~/.kube
curl -sfL https://get.k3s.io | sh -
sudo kubectl config view --raw > ~/.kube/config
chmod 400 ~/.kube/config

## Install helm
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

## install cert-manager
helm repo add jetstack https://charts.jetstack.io
helm repo update
sudo kubectl create ns cert-manager
sudo kubectl config set-context --current --namespace=cert-manager
helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.13.1 --set installCRDs=true

## install promethues-grafana
sudo kubectl create ns monitoring
sudo kubectl config set-context --current --namespace=monitoring

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add grafana https://grafana.github.io/helm-charts

helm repo update

helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring
helm upgrade --install loki grafana/loki-stack --namespace monitoring

## apply cluster-issuer.yaml (see in follow)
sudo kubectl apply -f ./$FOLDER_KUBECONFIG/cluster-issuer.yaml

## apply grafana-ingress.yaml (see in follow)
sudo kubectl apply -f ./$FOLDER_KUBECONFIG/grafana-ingress.yaml
```

cluster-issuer.yaml:

``` yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt
  namespace: cert-manager
spec: 
  acme: 
    email: VAR_EMAIL_REPLACER
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: letsencrypt
    solvers:
    - http01:
       ingress:
         class: traefik
           ingressTemplate:
             metadata:
               namespace: cert-manager
               annotations:
                 traefik.ingress.kubernetes.io/router.entrypoints: web
```

grafana-ingress.yaml

``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/common-name: VAR_GRAFANA_HOST_REPLACER
    acme.cert-manager.io/http01-edit-in-place: "true"
    #cert-manager.io/subject-organizations: VAR_CERT_ORGANIZATION_REPLACER
    #cert-manager.io/subject-countries: VAR_CERT_COUNTRY_REPLACER
    #cert-manager.io/subject-localities: VAR_CERT_CITY_REPLACER
    #cert-manager.io/subject-provinces: VAR_CERT_PROVINCE_REPLACER
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  name: grafana-ingress
  namespace: monitoring
spec:
  ingressClassName: traefik
  rules:
  - host: VAR_GRAFANA_HOST_REPLACER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80
  tls:
  - hosts:
    - VAR_GRAFANA_HOST_REPLACER
    secretName: grafana-tls
```

my nftables configuration:

``` nft
#!/usr/sbin/nft -f

table inet firewall {
	chain input {
		type filter hook input priority 0; policy drop

		## Permit inbound traffic to loopback interface (localhost)
		iif lo accept

		## Permit established and related connections
		ct state established,related counter accept

		## Drop traffic with invalid connection state
		ct state invalid counter drop

		## Permit IPv4 ping/ping responses but rate limit to 2000 PPS
		ip protocol icmp icmp type { echo-reply, echo-request } \
			limit rate 2000/second \
			counter accept

		## Permit all other inbound IPv4 ICMP
		ip protocol icmp counter accept

		#ip saddr 10.42.0.0/16 counter accept 
		#ip saddr 10.43.0.0/16 counter accept

		## Permit IPv6 ping/ping responses but rate limit to 2000 PPS
		icmpv6 type { echo-reply, echo-request } \
			limit rate 2000/second \
			counter accept

		## Permit all other inbound IPv6 ICMP
		meta l4proto { icmpv6 } counter accept

		## Permit inbound SSH connections
		tcp dport ssh ct state new counter accept

		## Permit inbound HTTP and HTTPS connections
		tcp dport {80, 443} ct state new counter accept

		# Permit inbound API Kubernetes connections
		tcp dport {6443, 2379, 2380, 10250, 10259, 10257} ct state new counter accept

		## Count the unmatched traffic
		counter
	}
	chain forward {
		type filter hook forward priority 0; policy drop

		## Permit inbound traffic to loopback interface (localhost)
		iif lo accept

		## Permit established and related connections
		ct state established,related counter accept

		## Drop traffic with invalid connection state
		ct state invalid counter drop

		# Autoriser le trafic HTTP/HTTPS sortant
		tcp dport {80, 443} ct state new,established accept

		# Permit inbound API Kubernetes connections
		tcp dport {6443, 2379, 2380, 10250, 10259, 10257} ct state new counter accept

		# Autoriser le trafic DNS sortant
		udp dport 53 ct state new,established accept

		# Autoriser le trafic NTP sortant
		udp dport 123 ct state new,established accept

		## Count the unmatched traffic
		counter
	}
	chain output {
		type filter hook output priority 0; policy accept

		## Count all outbound traffic
		counter
	}
}
```

**Expected behavior:**

I could validate the certificate validation process and access to the grafana dashboard

**Actual behavior:**

The certificate validation stay in "pending" status with the following message: Waiting on certificate issuance from order monitoring/grafana-tls-1-632796568: "pending"

**Additional context / logs:**

Probably they are inconsistent rules in nftable cause a lot of tests ;)  But if i disables all rules for the forward chain, it works.
I see some possible incompatible with nftable on old issues. It's possible to fix my error or it's stay a bug ?

Thanks a lot for your help
