### ISSUE TITLE
[Release-1.25] "can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#8768]
Backport fix for [v1.28.3+k3s1] "can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"

* #8754

**Comment by VestigeJ** [comment]
##Environment Details
Reproduced using VERSION=v1.25.14+k3s1 -> v1.25.15+k3s1
Validated using COMMIT=f62d0e8e04f3ca3e995b77f58438497e11993032

*Infrastructure*
- [X] Cloud


*Node(s) CPU architecture, OS, and version:*

```
Linux 5.15.0-1045-aws x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 20.04.6 LTS"
```

*Cluster Configuration:*

```
NAME                    STATUS   ROLES                       AGE     VERSION
node/ip-17-31-27-215    Ready    control-plane,etcd,master   8m55s   v1.25.15+k3s-f62d0e8e
```

*Config.yaml:*

```
write-kubeconfig-mode: 644
debug: true
token: YOUR_TOKEN_HERE
cluster-init: true
```

<details><summmary><h4>Validation</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.25.14+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh
$ kgp -A //kubectl get pods -A
$ helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
$ helm repo update
$ helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator --set driver.nvidiaDriverCRD.enabled=true
$ set_kubefig //export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ kgn //kubectl get nodes
$ kgp -A //kubectl get pods -A
$ k create -f usual.yaml
$ k create -f cuda-sample-2004.yaml
$ sudo apt install nvidia-container-toolkit nvidia-container-runtime
$ sudo INSTALL_K3S_VERSION=v1.25.15+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh //observe failure in journalctl and cluster fails to come up properly with new version
$ sudo INSTALL_K3S_COMMIT=f62d0e8e04f3ca3e995b77f58438497e11993032 INSTALL_K3S_EXEC=server ./install-k3s.sh
$ kubectl delete -f cuda-sample-2004.yaml -f usually.yaml
$ kubectl create -f cuda-sample-2004.yaml -f usually.yaml
```


**Results:**

```
NAME                    STATUS   ROLES                       AGE     VERSION
node/ip-17-31-27-215    Ready    control-plane,etcd,master   8m55s   v1.25.15+k3s-f62d0e8e

NAMESPACE      NAME                                                                  READY   STATUS      RESTARTS        AGE
default        pod/test-cuda-vector-add                                              0/1     Completed   0               57s
default        pod/test2                                                             1/1     Running     0               57s
gpu-operator   pod/gpu-feature-discovery-2sxh5                                       1/1     Running     0               7m25s
gpu-operator   pod/gpu-operator-1699044758-node-feature-discovery-gc-bf98dd56k5cpx   1/1     Running     0               7m36s
gpu-operator   pod/gpu-operator-1699044758-node-feature-discovery-master-5d845hmw2   1/1     Running     0               7m36s
gpu-operator   pod/gpu-operator-1699044758-node-feature-discovery-worker-bwpwm       1/1     Running     2 (3m53s ago)   7m36s
gpu-operator   pod/gpu-operator-78b6d94c54-hbtpk                                     1/1     Running     2 (4m4s ago)    7m36s
gpu-operator   pod/nvidia-container-toolkit-daemonset-jsv25                          1/1     Running     0               7m25s
gpu-operator   pod/nvidia-cuda-validator-m9m5z                                       0/1     Completed   0               7m11s
gpu-operator   pod/nvidia-dcgm-exporter-5lrjk                                        1/1     Running     0               7m25s
gpu-operator   pod/nvidia-device-plugin-daemonset-9jjrc                              1/1     Running     0               7m25s
gpu-operator   pod/nvidia-operator-validator-wwkt4                                   1/1     Running     0               7m25s
kube-system    pod/coredns-8b9777675-w55w7                                           1/1     Running     0               8m39s
kube-system    pod/helm-install-traefik-crd-746ml                                    0/1     Completed   0               3m56s
kube-system    pod/helm-install-traefik-q2gmt                                        0/1     Completed   2               3m56s
kube-system    pod/local-path-provisioner-69dff9496c-lfbs2                           1/1     Running     0               8m39s
kube-system    pod/metrics-server-854c559bd-vnj6s                                    1/1     Running     0               8m39s
kube-system    pod/svclb-traefik-19c74b0b-dl77v                                      2/2     Running     0               8m29s
kube-system    pod/traefik-5546784db6-vjcrw                                          1/1     Running     0               3m39s
```

$ k logs pod/test-cuda-vector-add

```
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

$ cat cuda-sample-2004.yaml

```
apiVersion: v1
kind: Pod
metadata:
 name: test-cuda-vector-add
spec:
  restartPolicy: "OnFailure"
  runtimeClassName: "nvidia"
  terminationGracePeriodSeconds: 15
  containers:
  - name: vectoradd-cuda
    image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04"
    resources:
      limits:
         nvidia.com/gpu: 1
         
```


$ cat usually.yaml

```
apiVersion: v1
kind: Pod
metadata:
 name: test2
spec:
  restartPolicy: "Never"
  runtimeClassName: "nvidia"
  terminationGracePeriodSeconds: 5
  containers:
  - name: nvidia-smi
    image: "nvidia/cuda:12.1.0-base-ubuntu18.04"
    command:
      - "sleep"
    args:
      - "infinity"
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
```

</details>
