### ISSUE TITLE
[Release-1.26] "can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#8769]
Backport fix for [v1.28.3+k3s1] "can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"

* #8754

**Comment by VestigeJ** [comment]
##Environment Details
Reproduced using VERSION=v1.26.9+k3s1 -> v1.26.10+k3s1
Validated using COMMIT=2d883cd53748e8f2da82a2878112a72c925b16ea

*Infrastructure*
- [X] Cloud


*Node(s) CPU architecture, OS, and version:*

```
Linux 5.15.0-1045-aws x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 20.04.6 LTS"
```

*Cluster Configuration:*

```
NAME               STATUS   ROLES                       AGE     VERSION
ip-1-20-110-87     Ready    control-plane,etcd,master   7m37s   v1.27.7+k3s-1f0c784a
```

*Config.yaml:*

```
write-kubeconfig-mode: 644
debug: true
token: YOUR_TOKEN_HERE
cluster-init: true
```

<details><summmary><h4>Validation</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.26.9+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh
$ kgp -A //kubectl get pods -A
$ helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
$ helm repo update
$ helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator --set driver.nvidiaDriverCRD.enabled=true
$ set_kubefig //export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ kgn //kubectl get nodes
$ kgp -A //kubectl get pods -A
$ k create -f usual.yaml
$ k create -f cuda-sample-2004.yaml
$ sudo apt install nvidia-container-toolkit nvidia-container-runtime
$ sudo INSTALL_K3S_VERSION=v1.26.10+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh //observe failure in journalctl and cluster fails to come up properly with new version
$ sudo INSTALL_K3S_COMMIT=2d883cd53748e8f2da82a2878112a72c925b16ea INSTALL_K3S_EXEC=server ./install-k3s.sh
$ kubectl delete -f cuda-sample-2004.yaml -f usually.yaml
$ kubectl create -f cuda-sample-2004.yaml -f usually.yaml
```


**Results:**

```
NAME                    STATUS   ROLES                       AGE     VERSION
node/ip-1-20-110-87     Ready    control-plane,etcd,master   9m26s   v1.26.10+k3s-2d883cd5

NAMESPACE      NAME                                                                  READY   STATUS      RESTARTS        AGE
default        pod/test-cuda-vector-add                                              0/1     Completed   0               3m34s
default        pod/test2                                                             1/1     Running     0               3m34s
gpu-operator   pod/gpu-feature-discovery-j6ms6                                       1/1     Running     0               8m12s
gpu-operator   pod/gpu-operator-1699043625-node-feature-discovery-gc-747f5965ws2db   1/1     Running     0               8m23s
gpu-operator   pod/gpu-operator-1699043625-node-feature-discovery-master-d6f6vln5f   1/1     Running     0               8m23s
gpu-operator   pod/gpu-operator-1699043625-node-feature-discovery-worker-f6j6r       1/1     Running     0               8m23s
gpu-operator   pod/gpu-operator-5bf756f64d-pp4n2                                     1/1     Running     1 (4m10s ago)   8m23s
gpu-operator   pod/nvidia-container-toolkit-daemonset-94fq9                          1/1     Running     0               8m12s
gpu-operator   pod/nvidia-cuda-validator-ghdzd                                       0/1     Completed   0               7m58s
gpu-operator   pod/nvidia-dcgm-exporter-8cw4b                                        1/1     Running     0               8m12s
gpu-operator   pod/nvidia-device-plugin-daemonset-7mn2g                              1/1     Running     0               8m12s
gpu-operator   pod/nvidia-operator-validator-9sxzp                                   1/1     Running     0               8m12s
kube-system    pod/coredns-59b4f5bbd5-w476m                                          1/1     Running     0               9m12s
kube-system    pod/helm-install-traefik-88xwb                                        0/1     Completed   2               3m37s
kube-system    pod/helm-install-traefik-crd-28w8n                                    0/1     Completed   0               3m37s
kube-system    pod/local-path-provisioner-76d776f6f9-b54hj                           1/1     Running     0               9m12s
kube-system    pod/metrics-server-68cf49699b-9gf5c                                   1/1     Running     0               9m12s
kube-system    pod/svclb-traefik-4dad84ae-qn924                                      2/2     Running     0               9m3s
kube-system    pod/traefik-69c6f6996-pbdw9                                           1/1     Running     0               3m16s
```

$ k logs pod/test-cuda-vector-add

```
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

$ cat cuda-sample-2004.yaml

```
apiVersion: v1
kind: Pod
metadata:
 name: test-cuda-vector-add
spec:
  restartPolicy: "OnFailure"
  runtimeClassName: "nvidia"
  terminationGracePeriodSeconds: 15
  containers:
  - name: vectoradd-cuda
    image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04"
    resources:
      limits:
         nvidia.com/gpu: 1
         
```


$ cat usually.yaml

```
apiVersion: v1
kind: Pod
metadata:
 name: test2
spec:
  restartPolicy: "Never"
  runtimeClassName: "nvidia"
  terminationGracePeriodSeconds: 5
  containers:
  - name: nvidia-smi
    image: "nvidia/cuda:12.1.0-base-ubuntu18.04"
    command:
      - "sleep"
    args:
      - "infinity"
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
```

</details>
