### ISSUE TITLE
[Release-1.27]  "can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#8770]
Backport fix for [v1.28.3+k3s1] "can't evaluate field SystemdCgroup in type templates.ContainerdRuntimeConfig"

* #8754

**Comment by VestigeJ** [comment]
##Environment Details
Reproduced using VERSION=v1.27.6+k3s1
Validated using COMMIT=1f0c784a9323fb10a5da455a4f473170c04d2cce

*Infrastructure*
- [X] Cloud


*Node(s) CPU architecture, OS, and version:*

```
Linux 5.15.0-1045-aws x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 20.04.6 LTS"
```

*Cluster Configuration:*

```
NAME               STATUS   ROLES                       AGE     VERSION
ip-172-30-20-10    Ready    control-plane,etcd,master   7m37s   v1.27.7+k3s-1f0c784a
```

*Config.yaml:*

```
write-kubeconfig-mode: 644
debug: true
token: YOUR_TOKEN_HERE
cluster-init: true
```

<details><summmary><h4>Validation</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.27.6+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh
$ kgp -A //kubectl get pods -A
$ helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
$ helm repo update
$ helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator --set driver.nvidiaDriverCRD.enabled=true
$ set_kubefig //export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ kgn //kubectl get nodes
$ kgp -A //kubectl get pods -A
$ k create -f usual.yaml
$ k create -f cuda-sample-2004.yaml
$ sudo apt install nvidia-container-toolkit nvidia-container-runtime
$ sudo INSTALL_K3S_COMMIT=1f0c784a9323fb10a5da455a4f473170c04d2cce INSTALL_K3S_EXEC=server ./install-k3s.sh
$ kubectl delete -f cuda-sample-2004.yaml -f usually.yaml
$ kubectl create -f cuda-sample-2004.yaml -f usually.yaml
```


**Results:**

```
NAME                    STATUS   ROLES                       AGE   VERSION
node/ip-172-30-20-10    Ready    control-plane,etcd,master   11m   v1.27.7+k3s-1f0c784a

NAMESPACE      NAME                                                                  READY   STATUS      RESTARTS        AGE
default        pod/test-cuda-vector-add                                              0/1     Completed   0               4m25s
default        pod/test2                                                             1/1     Running     0               4m25s
gpu-operator   pod/gpu-feature-discovery-wpb9v                                       1/1     Running     0               9m58s
gpu-operator   pod/gpu-operator-1699042624-node-feature-discovery-gc-589f6dddkjq77   1/1     Running     0               10m
gpu-operator   pod/gpu-operator-1699042624-node-feature-discovery-master-5944d96mb   1/1     Running     0               10m
gpu-operator   pod/gpu-operator-1699042624-node-feature-discovery-worker-wwbg4       1/1     Running     0               10m
gpu-operator   pod/gpu-operator-58d5c4689b-xs4sr                                     1/1     Running     3 (5m21s ago)   10m
gpu-operator   pod/nvidia-container-toolkit-daemonset-2wqxf                          1/1     Running     0               9m58s
gpu-operator   pod/nvidia-cuda-validator-jqmsn                                       0/1     Completed   0               9m45s
gpu-operator   pod/nvidia-dcgm-exporter-67rk6                                        1/1     Running     0               9m58s
gpu-operator   pod/nvidia-device-plugin-daemonset-282c5                              1/1     Running     0               9m58s
gpu-operator   pod/nvidia-operator-validator-d2f4m                                   1/1     Running     0               9m58s
kube-system    pod/coredns-77ccd57875-xsw4b                                          1/1     Running     0               11m
kube-system    pod/helm-install-traefik-crd-j7dcf                                    0/1     Completed   0               5m57s
kube-system    pod/helm-install-traefik-nlm6d                                        0/1     Completed   2               5m57s
kube-system    pod/local-path-provisioner-957fdf8bc-22s4b                            1/1     Running     0               11m
kube-system    pod/metrics-server-648b5df564-qldsf                                   1/1     Running     0               11m
kube-system    pod/svclb-traefik-b1aa7b6f-65dlt                                      2/2     Running     0               11m
kube-system    pod/traefik-64f575f954-gcmkt                                          1/1     Running     0               5m39s
```

$ k logs pod/test-cuda-vector-add

```
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

$ cat cuda-sample-2004.yaml

```
apiVersion: v1
kind: Pod
metadata:
 name: test-cuda-vector-add
spec:
  restartPolicy: "OnFailure"
  runtimeClassName: "nvidia"
  terminationGracePeriodSeconds: 15
  containers:
  - name: vectoradd-cuda
    image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04"
    resources:
      limits:
         nvidia.com/gpu: 1
         
```


$ cat usually.yaml

```
apiVersion: v1
kind: Pod
metadata:
 name: test2
spec:
  restartPolicy: "Never"
  runtimeClassName: "nvidia"
  terminationGracePeriodSeconds: 5
  containers:
  - name: nvidia-smi
    image: "nvidia/cuda:12.1.0-base-ubuntu18.04"
    command:
      - "sleep"
    args:
      - "infinity"
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
```

</details>
