### ISSUE TITLE
[Release-1.25] - K3s v1.27.7+k3s1 and v1.28.3+k3s1 bundle old Traefik CRDs, causing kubernetes api connection issues

### ISSUE THREAD

**Issue by galal-hussein** [k3s-io/k3s#8774]
Backport fix for K3s v1.27.7+k3s1 and v1.28.3+k3s1 bundle old Traefik CRDs, causing kubernetes api connection issues

* #8755

**Comment by ShylajaDevadiga** [comment]
### Validated using k3s version v1.25.15-rc1+k3s2 (f62d0e8e)
```
ec2-user@ip-172-31-0-90:~> k3s -v
k3s version v1.25.15-rc1+k3s2 (f62d0e8e)
go version go1.20.10
ec2-user@ip-172-31-0-90:~> kubectl get crd |grep traefik
ingressroutes.traefik.containo.us       2023-11-06T08:03:02Z
ingressroutes.traefik.io                2023-11-06T08:03:02Z
ingressroutetcps.traefik.containo.us    2023-11-06T08:03:02Z
ingressroutetcps.traefik.io             2023-11-06T08:03:02Z
ingressrouteudps.traefik.containo.us    2023-11-06T08:03:02Z
ingressrouteudps.traefik.io             2023-11-06T08:03:02Z
middlewares.traefik.containo.us         2023-11-06T08:03:02Z
middlewares.traefik.io                  2023-11-06T08:03:02Z
middlewaretcps.traefik.containo.us      2023-11-06T08:03:02Z
middlewaretcps.traefik.io               2023-11-06T08:03:02Z
serverstransports.traefik.containo.us   2023-11-06T08:03:02Z
serverstransports.traefik.io            2023-11-06T08:03:02Z
serverstransporttcps.traefik.io         2023-11-06T08:03:02Z
tlsoptions.traefik.containo.us          2023-11-06T08:03:02Z
tlsoptions.traefik.io                   2023-11-06T08:03:02Z
tlsstores.traefik.containo.us           2023-11-06T08:03:02Z
tlsstores.traefik.io                    2023-11-06T08:03:02Z
traefikservices.traefik.containo.us     2023-11-06T08:03:02Z
traefikservices.traefik.io              2023-11-06T08:03:02Z
ec2-user@ip-172-31-0-90:~> kubectl get clusterrole -o yaml |grep -i apiGroup -A 2|grep traefik
    - traefik.io
    - traefik.containo.us
ec2-user@ip-172-31-0-90:~> 
```
Accessing the resources using old and new api is successful as seen below
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: test-ingress
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`<IP>.nip.io`) && PathPrefix(`/notls`)
    kind: Rule
    services:
    - name: whoami
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: test-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`<IP>.nip.io`) && PathPrefix(`/tls`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    certResolver: myresolver


```
```
➜  ~ curl -k http://<IP>.nip.io/notls    
Hostname: whoami-5dfdf459f4-hd6zf
IP: 127.0.0.1
IP: ::1
IP: 10.42.1.10
IP: fe80::d4ef:d0ff:fecf:a382
RemoteAddr: 10.42.0.8:43116
GET /notls HTTP/1.1
Host: <IP>.nip.io
User-Agent: curl/7.64.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.42.0.7
X-Forwarded-Host: <IP>.nip.io
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-5546784db6-98blp
X-Real-Ip: 10.42.0.7

➜  ~ curl -k https://<IP>.nip.io/tls     
Hostname: whoami-5dfdf459f4-2ssrd
IP: 127.0.0.1
IP: ::1
IP: 10.42.2.9
IP: fe80::1830:62ff:feb5:363e
RemoteAddr: 10.42.0.8:35744
GET /tls HTTP/1.1
Host: <IP>.nip.io
User-Agent: curl/7.64.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.42.0.7
X-Forwarded-Host: <IP>.nip.io
X-Forwarded-Port: 443
X-Forwarded-Proto: httpsG
X-Forwarded-Server: traefik-5546784db6-98blp
X-Real-Ip: 10.42.0.7
```
Using new apiGroup

```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: test-ingress
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`<IP>.nip.io`) && PathPrefix(`/notls`)
    kind: Rule
    services:
    - name: whoami
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: test-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`<IP>.nip.io`) && PathPrefix(`/tls`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    certResolver: myresolver
```
```
➜  ~ curl -k https://<IP>.nip.io/tls    
Hostname: whoami-5dfdf459f4-2pq28
IP: 127.0.0.1
IP: ::1
IP: 10.42.2.10
IP: fe80::2098:e7ff:fe74:b2ba
RemoteAddr: 10.42.0.8:60076
GET /tls HTTP/1.1
Host: <IP>.nip.io
User-Agent: curl/7.64.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.42.0.7
X-Forwarded-Host: <IP>.nip.io
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-5546784db6-98blp
X-Real-Ip: 10.42.0.7

➜  ~ curl -k http://<IP>.nip.io/notls    
Hostname: whoami-5dfdf459f4-p7kvr
IP: 127.0.0.1
IP: ::1
IP: 10.42.1.11
IP: fe80::8894:7eff:fe71:ccc
RemoteAddr: 10.42.0.8:46188
GET /notls HTTP/1.1
Host: <IP>nip.io
User-Agent: curl/7.64.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.42.0.7
X-Forwarded-Host: <IP>.nip.io
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-5546784db6-98blp
X-Real-Ip: 10.42.0.7

```

**Upgrade results:**
```
ec2-user@ip-172-31-13-64:~> k3s -v
k3s version v1.25.15-rc1+k3s2 (f62d0e8e)
go version go1.20.10
ec2-user@ip-172-31-13-64:~> kubectl get nodes
NAME               STATUS   ROLES                       AGE     VERSION
ip-172-31-0-7      Ready    control-plane,etcd,master   6h54m   v1.25.15-rc1+k3s2
ip-172-31-13-64    Ready    control-plane,etcd,master   6h57m   v1.25.15-rc1+k3s2
ip-172-31-15-134   Ready    control-plane,etcd,master   6h54m   v1.25.15-rc1+k3s2
ip-172-31-7-171    Ready    <none>                      6h53m   v1.25.15-rc1+k3s2
ec2-user@ip-172-31-13-64:~> kubectl get crd |grep traefik
ingressroutes.traefik.containo.us       2023-11-06T08:04:55Z
ingressroutes.traefik.io                2023-11-06T14:53:34Z
ingressroutetcps.traefik.containo.us    2023-11-06T08:04:55Z
ingressroutetcps.traefik.io             2023-11-06T14:53:34Z
ingressrouteudps.traefik.containo.us    2023-11-06T08:04:55Z
ingressrouteudps.traefik.io             2023-11-06T14:53:34Z
middlewares.traefik.containo.us         2023-11-06T08:04:55Z
middlewares.traefik.io                  2023-11-06T14:53:34Z
middlewaretcps.traefik.containo.us      2023-11-06T08:04:55Z
middlewaretcps.traefik.io               2023-11-06T14:53:34Z
serverstransports.traefik.containo.us   2023-11-06T08:04:55Z
serverstransports.traefik.io            2023-11-06T14:53:35Z
serverstransporttcps.traefik.io         2023-11-06T14:53:35Z
tlsoptions.traefik.containo.us          2023-11-06T08:04:55Z
tlsoptions.traefik.io                   2023-11-06T14:53:35Z
tlsstores.traefik.containo.us           2023-11-06T08:04:55Z
tlsstores.traefik.io                    2023-11-06T14:53:35Z
traefikservices.traefik.containo.us     2023-11-06T08:04:55Z
traefikservices.traefik.io              2023-11-06T14:53:35Z
ec2-user@ip-172-31-13-64:~> kubectl get clusterrole -o yaml |grep -i apiGroup -A 2|grep traefik
    - traefik.io
    - traefik.containo.us
```
