### ISSUE TITLE
Use `status.hostIPs` for ServiceLB pods

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8823]
There is a FeatureGate that is alpha in 1.28 that will improve dual-stack support for `externalTrafficPolicy: Local`

https://kubernetes.io/docs/concepts/workloads/pods/downward-api/
> `status.hostIPs`
> the IP addresses is a dual-stack version of status.hostIP, the first is always the same as status.hostIP. The field is available if you enable the PodHostIPs [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/).

Once that feature-gate goes beta and is on by default, we can evaluate how to best make use of it in servicelb.

Ref: https://github.com/kubernetes/enhancements/issues/2681

_Originally posted by @brandond in https://github.com/k3s-io/k3s/issues/8809#issuecomment-1809359169_

**Comment by VestigeJ** [comment]
Hey @brandond I saw your verification command on the links but want to confirm a couple parameters with you. 

1) Apart from passing in the below command to start the k3s server there should be no additional configuration values passed in by the user on a dual stack node to take advantage of this feature correct? 

2) The below mentioned line for --controller-manager-arg=feature-gates=CloudDualStackNodeIPs=true,PodHostIPs=true results in a flag provided but not defined error on the CLI on existing releases and the latest commit ID. Is that expected to function?

3) On existing release v1.29.0+k3s1 if I start a single node server I should not expect to see the hostIPs populated in the serviceLB pod like this below? I do see and recognize the klipper-lb:v0.4.4 vs 4.5 image version change between the commit id and the existing release but I'm trying to pin down where I should see the behavioral change in the cluster. 

```
    state:
      running:
        startedAt: "2024-01-12T19:07:28Z"
  hostIP: 192.168.4.94
  hostIPs:
  - ip: 192.168.4.94
  - ip: 3600:2600:2600:ee48:2359:714d:aced:cafe
  phase: Running
  podIP: 10.42.0.7
  podIPs:
  - ip: 10.42.0.7
  - ip: 2001:cafe:42::7
  qosClass: BestEffort
  startTime: "2024-01-12T19:07:25Z"
```

```
k3s server \
  --cluster-cidr=10.42.0.0/16,2001:cafe:42::/56 \
  --service-cidr=10.43.0.0/16,2001:cafe:43::/112 \
  --kubelet-arg=feature-gates=CloudDualStackNodeIPs=true,PodHostIPs=true \
  --kube-apiserver-arg=feature-gates=CloudDualStackNodeIPs=true,PodHostIPs=true \
  --controller-manager-arg=feature-gates=CloudDualStackNodeIPs=true,PodHostIPs=true \
  --kube-cloud-controller-manager-arg=feature-gates=CloudDualStackNodeIPs=true,PodHostIPs=true
```
