### ISSUE TITLE
K3s official Traefik docs broken.

### ISSUE THREAD

**Issue by gavan1** [k3s-io/k3s#9029]
As per 
https://docs.k3s.io/helm

traefik-config.yaml

```
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: v2.8.5
    forwardedHeaders:
      enabled: true
      trustedIPs:
        - 10.0.0.0/8
    ssl:
      enabled: true
      permanentRedirect: false
```

Adding the above to server/manifests/ dir causes ErrImagePull.

commenting out “tag:v2.8.5” is current workaround.
