### ISSUE TITLE
Example Traefik chart config is out of date

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9030]
@brandond I’m following the k3s.io docs.
When creating the traefik-config.yaml in /var/lib/rancher/k3s/server/manifests/traefik-config.yaml

```
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: v2.8.5
    forwardedHeaders:
      enabled: true
      trustedIPs:
        - 10.0.0.0/8
    ssl:
      enabled: true
      permanentRedirect: false
```

official guide needs to be updated as I get an image pull error and back off.

There must be an overlooked step that is missing from that guide.

_Originally posted by @gavan1 in https://github.com/k3s-io/k3s/issues/1313#issuecomment-1848362432_
