### ISSUE TITLE
HELP: Docker private registry

### ISSUE THREAD

**Issue by MalikaML** [k3s-io/k3s#9050]
**Environmental Info:**
K3s Version: 
k3s version v1.26.3+k3s1 
go version go1.19.7
Operating System: Debian GNU/Linux 12

```
#docker version
Client: Docker Engine - Community
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:34:13 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Cluster configuration: only one master node 

**Configuration done:**
To prepare docker private registry:
First I generated a public certificate for my registry, in `/home/user/`
I have the three files drancher.xxx.fr-chain.pem  drancher.xxx.fr.key  drancher.xxx.fr.pem
To install the docker private registry, I followed these steps: 
```
#nano docker-compose.yaml
version: '3.0'

services:

  registry:
    container_name: docker-registry
    restart: always
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /home/user/drancher.xxx.fr.pem
      REGISTRY_HTTP_TLS_KEY: /home/user/drancher.xxx.fr.key
      REGISTRY_HTTP_TLS_CA: /home/user/drancher.xxx.fr-chain.pem
    ports:
      - 5000:5000
    volumes:
      - docker-registry-data:/var/lib/registry
      - /home/user:/certs

volumes:
  docker-registry-data: {}

#docker-compose up -d
```
On my node, I placed the registries.yaml in /etc/rancher/k3s/ 
```
mirrors:
  "drancher.xxx.fr:5000":
    endpoint:
      - "https://drancher.xxx.fr:5000"

configs:
  drancher.xxx.fr:5000:
    tls:
      insecure_skip_verify: true
```
Then I restarted the k3s service 
` systemctl restart k3s`
I checked with `crictl info`

```
"registry": {
      "configPath": "",
      "mirrors": {
        "drancher.xxx.fr:5000": {
          "endpoint": [
            "https://drancher.xxx.fr:5000"
          ],
          "rewrite": null
        }
      },
      "configs": {
        "drancher.xxx.fr:5000": {
          "auth": null,
          "tls": {
            "insecure_skip_verify": true,
            "caFile": "",
            "certFile": "",
            "keyFile": ""
          }
        }
      },
```
 To make sure that kubectl will pull the image I've build and push earlier in  the docker registry:
```
#nano mydebian.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mytest
  name: mytest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mytest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mytest
    spec:
      containers:
      - image: drancher.xxx.fr:5000/mydebian:v1
        name: mytest

```
When running `kubectl describe pods `
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  14m                   default-scheduler  Successfully assigned default/mytest-8656785ff8-rvzvr to dworker3
  Warning  Failed     13m (x6 over 14m)     kubelet            Error: ImagePullBackOff
  Normal   Pulling    13m (x4 over 14m)     kubelet            Pulling image "drancher.grenoble.cnrs.fr:5000/mydebian:v1"
  Warning  Failed     13m (x4 over 14m)     kubelet            Failed to pull image "drancher.xxx.fr:5000/mydebian:v1": rpc error: code = Unknown desc = failed to pull and unpack image "drancher.xxx.fr:5000/mydebian:v1": failed to resolve reference "drancher.xxx.fr:5000/mydebian:v1": failed to do request: Head "https://drancher.xxx.fr:5000/v2/mydebian/manifests/v1": dial tcp x.x.x.x:5000: connect: connection refused
  Warning  Failed     13m (x4 over 14m)     kubelet            Error: ErrImagePull
  Normal   BackOff    4m26s (x44 over 14m)  kubelet            Back-off pulling image "drancher.xxx.fr:5000/mydebian:v1"

```
After looking for the reason why I get that error, I realized that I have a problem here, the registry is not up: 
```
#docker ps
CONTAINER ID   IMAGE        COMMAND                  CREATED          STATUS                          PORTS     NAMES
9bdef5c855d1   registry:2   "/entrypoint.sh /etc…"   22 minutes ago   Restarting (1) 29 seconds ago             docker-registry
```
When running `docker logs 9bdef5c855d1` I can see this line:
```time="2023-12-13T17:18:32.738983852Z" level=fatal msg="open /home/user/drancher.xxx.fr.pem: no such file or directory" ```

Also, I think Im missing the part of config tls in `registries.yaml ` but I don't know how to fix it since the registry certificate is public so maybe would be recognized by the node ? 

Thank you
