### ISSUE TITLE
FR: Expand #7991 to not just append blindly

### ISSUE THREAD

**Issue by samip5** [k3s-io/k3s#9246]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I tried to include new cri options, but instead it results in duplicate entries.

**Describe the solution you'd like**
I would like it to be smarter when appending, so that it would merge the values together if otherwise would result in duplicates.

**Describe alternatives you've considered**
N/A

**Additional context**
Related to: #7991

I tried to configure cri with:

```toml
[plugins."io.containerd.grpc.v1.cri"]
device_ownership_from_security_context = true
```

but that results in duplicates with the existing cri definition.
