### ISSUE TITLE
Improve how custom AddOns are disabled

### ISSUE THREAD

**Issue by rorosen** [k3s-io/k3s#9359]
**Is your feature request related to a problem? Please describe.**

I use k3s on an appliance in combination with A/B updates and control all deployments via the great [auto deploying manifests](https://docs.k3s.io/installation/packaged-components#auto-deploying-manifests-addons) feature by placing files in the manifest directory. The filesystem is prepared so that any AddOn file is present when k3s is started. An update could introduce new AddOns, but also delete AddOns that previously were deployed. Most times everything works as expected, but I am struggling when deleting an AddOn via the [--disable flag](https://docs.k3s.io/installation/packaged-components#using-the---disable-flag). I understand that the AddOn controller requires the AddOn file to be present in `/var/lib/rancher/k3s/server/manifests/` in order to delete the AddOn, however, I fail to see the reason why the content of the file has to match the deployed resources.

If I place the following manifest file in `/var/lib/rancher/k3s/server/manifests/foo.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: bar
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
---
apiVersion: v1
kind: Pod
metadata:
  name: baz
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
``` 

An AddOn `foo` and the two pods will be created, which is fine. If I then decide to uninstall the foo AddOn via `--disable foo`, I have to make sure that `foo.yaml` still has the same content so that both pods are also deleted. If I place an empty `foo.yaml` file, the AddOn will be deleted but both pods remain as orphaned resources in the cluster. Likewise, only one pod is deleted with the AddOn, if I write only one Pod in `foo.yaml`.

**Describe the solution you'd like**

If I make an A/B update, I replace the whole root file system, including `/var/lib/rancher/k3s/server/manifests/`. In an ideal world, I would be able to delete AddOns during updates, e.g. the `foo` AddOn, by placing an empty file `foo.yaml` in the manifest directory and starting k3s with `--disable foo`. 

**Describe alternatives you've considered**

 I can't guarantee that the manifest of a disabled AddOn after an update contains all resources the AddOn has deployed before the update, so preserving the manifest file isn't an option. The closest match to my desired behavior was to let the manifest refer the AddOn resource and not starting k3s with the `--disable` flag.

E.g. placing the following in `/var/lib/rancher/k3s/server/manifests/foo.yaml` deletes everything the AddOn has deployed:
```yaml
apiVersion: k3s.cattle.io/v1
kind: Addon
metadata:
  name: foo
  namespace: kube-system
```

However, this is clearly a dirty hack, doesn't feel great at all and produces an error in the k3s logs.

Do you see any chance that the behavior of the AddOn controller can be modified? What is the reason for only deleting resources that are present in the manifest file?
