### ISSUE TITLE
[Release-1.27] - etcd status controller updates node status excessively frequently

### ISSUE THREAD

**Issue by vitorsavian** [k3s-io/k3s#9416]
Backport fix for etcd status controller updates node status excessively frequently

* #9240

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$ k3s version v1.27.10+k3s-f6303cf1 (f6303cf1)



```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"


*Cluster Configuration:*
1 server node 


 

 
## Steps to validate the fix
1. Install k3s
2. Validate heart beat time with `kubectl get node -o yaml | grep -A10 conditions`
3. Check that the time is updated every 5 minutes only
 

 
 
## **Reproduction Issue:**
<details>

```
 
k3s -v
k3s version v1.27.10+k3s-f6303cf1 (f6303cf1)
go version go1.20.13
 

#### Heart beat time is called always when ETCDisVoter runs ########

`TIME :...:41`

 $ kubectl get node -o yaml | grep -A10 conditions
    conditions:
    - lastHeartbeatTime: "2024-02-12T15:41:06Z"
      lastTransitionTime: "2024-02-12T15:30:06Z"
      message: Node is a voting member of the etcd cluster
      reason: MemberNotLearner
      status: "True"
      type: EtcdIsVoter
    - lastHeartbeatTime: "2024-02-12T15:41:02Z"
      lastTransitionTime: "2024-02-12T15:29:52Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory

`TIME :...:42`

~$ kubectl get node -o yaml | grep -A10 "conditions"
    conditions:
    - lastHeartbeatTime: "2024-02-12T15:42:06Z"
      lastTransitionTime: "2024-02-12T15:30:06Z"
      message: Node is a voting member of the etcd cluster
      reason: MemberNotLearner
      status: "True"
      type: EtcdIsVoter
    - lastHeartbeatTime: "2024-02-12T15:41:02Z"
      lastTransitionTime: "2024-02-12T15:29:52Z"
      message: kubelet has sufficient memory available

`TIME :...:43`
~$ kubectl get node -o yaml | grep -A10 "conditions"
    conditions:
    - lastHeartbeatTime: "2024-02-12T15:43:36Z"
      lastTransitionTime: "2024-02-12T15:30:06Z"
      message: Node is a voting member of the etcd cluster
      reason: MemberNotLearner
      status: "True"
      type: EtcdIsVoter
    - lastHeartbeatTime: "2024-02-12T15:41:02Z"
      lastTransitionTime: "2024-02-12T15:29:52Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory

 

```

 
## **Validation Results:**
<details>


``` 
k3s -v
k3s version v1.27.10+k3s-f6303cf1 (f6303cf1)
go version go1.20.13

 Updated every 5 minutes

   conditions:
    - lastHeartbeatTime: "2024-02-12T15:40:51Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2024-02-12T15:40:51Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure



          conditions:
    - lastHeartbeatTime: "2024-02-12T15:45:57Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2024-02-12T15:45:57Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure


- Still same time for lastHeartbeatTime

   conditions:
    - lastHeartbeatTime: "2024-02-12T15:45:57Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2024-02-12T15:45:57Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure

    conditions:
    - lastHeartbeatTime: "2024-02-12T15:45:57Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2024-02-12T15:45:57Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure



 - Updated with ...:51

   conditions:
    - lastHeartbeatTime: "2024-02-12T15:51:03Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2024-02-12T15:51:03Z"
      lastTransitionTime: "2024-02-12T15:18:05Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure

```
