### ISSUE TITLE
Consider Traefik pod "ready" only when all routes are setup

### ISSUE THREAD

**Issue by mossroy** [k3s-io/k3s#9475]
**Is your feature request related to a problem? Please describe.**
When Traefik is starting, it is considered "ready" even if all the routes are not configured.
So incoming HTTP requests can receive some HTTP 404, or the TLS certificate of another route, for the few seconds until all routes are setup.
This happens on startup but also for any change that requires a "rollout restart" of traefik pod.

**Describe the solution you'd like**
Adding a startupProbe on Traefik could probably solve that.
It might be necessary to upgrade traefik CRD to v26.0.0 to allow a startupProbe, see https://github.com/traefik/traefik-helm-chart/pull/956
The probe should check that Traefik is really ready.

**Describe alternatives you've considered**
I've manually added a startupProbe in Traefik deployment, that checks for one of my routes.
It works fine, but is specific to my use-case, and only checks one router

```yaml
    startupProbe:
      exec:
        command:
          - sh
          - "-c"
          - "wget -q --spider -O - http://127.0.0.1:9000/api/http/routers/myrouter@kubernetes"
        failureThreshold: 10
```

**Additional context**
Currently, Traefik pod only has a livenessProbe and a readinessProbe. Both check /ping on port 9000, which returns an HTTP 200 very early.
So, if all routes are not setup, Traefik can send HTTP requests to a wrong router, that would likely send wrong TLS certificate, return HTTP 404 etc.
Adding a startupProbe would allow for a specific check on startup, that could avoid that
