### ISSUE TITLE
ServiceLB: How to set securityContext's sysctls (net.ipv4.tcp_keepalive_intvl + net.core.somaxconn)

### ISSUE THREAD

**Issue by rstribrn** [k3s-io/k3s#9548]
I need a long-running synchronous HTTP to survive for at least 15-20 minutes. Setting TCP keepalive helped in non-K8S infrastructure, so I'm trying achieving this also for all parts in our on-premises environment.
I already did so on all other places, including traefik itself.

However, I guess KlipperLB/ServiceLB is missing:
```
kubectl exec -n kube-system pod/svclb-traefik-a82de10b-mfxk4 -- cat /proc/sys/net/core/somaxconn
Defaulted container "lb-tcp-8080" out of: lb-tcp-8080, lb-tcp-8443
128
```

What am Itrying to do is setting following TCP settings into generated daemonset/pods (svclb-traefik*):
```
        securityContext:
          sysctls:
          - name: net.core.somaxconn
            value: "4096"
          - name: net.ipv4.tcp_keepalive_time
            value: "120"
          - name: net.ipv4.tcp_keepalive_intvl
            value: "75"
          - name: net.ipv4.tcp_keepalive_probes
            value: "6"
          - name: net.ipv4.tcp_fin_timeout
            value: "20"
...
```

I've tried looking "everywhere", but I'm still missing something (how/where K3S is generating this stuff).
Firstly, I'm still happy with ServiceLB. MetalLB is the last resort in my case.
...but now, I'm starting being desperate.

Any suggestion? Please.
