### ISSUE TITLE
Bump helm CLI in klipper-helm

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9549]
The version of helmv3 we're using in klipper-helm is old; a few moderate CVEs have been addressed in recent releases. We should bump it.

* [ ] https://github.com/k3s-io/klipper-helm/pull/75

Ref:
* [Dependency management path traversal](https://github.com/helm/helm/security/advisories/GHSA-v53g-5gjp-272r)
* [Missing YAML Content Leads To Panic](https://github.com/helm/helm/security/advisories/GHSA-r53h-jv2g-vpx6)

**Comment by cwayne18** [comment]
updatecli does this bump doesnt it?

**Comment by brandond** [comment]
it might bump it once we publish a new klipper-helm tag, but I'm not sure how regularly it checks. We need an issue to track the bump + backports anyways.

**Comment by cwayne18** [comment]
yeah, we definitely need the issue, I was just curious, but I think the updatecli action checks weekly for any tags

**Comment by fmoral2** [comment]
Results from klipper on version: k3s version v1.29.2+k3s-bba3e3c6 (bba3e3c6)
 go version go1.21.7
 ``` 
 {
 Command:
  kubectl get node -o yaml  --kubeconfig=/tmp/efmoraleeeee_kubeconfig  | grep klipper -A5
  
 Assertion:
 klipper
  
 Matched with result:
 - docker.io/rancher/klipper-helm@sha256:87db3ad354905e6d31e420476467aefcd8f37d071a8f1c8a904f4743162ae546
       - docker.io/rancher/klipper-helm:v0.8.3-build20240228
       sizeBytes: 91162124
     - names:
       - docker.io/rancher/mirrored-library-traefik@sha256:ca9c8fbe001070c546a75184e3fd7f08c3e47dfc1e89bff6fe2edd302accfaec
       - docker.io/rancher/mirrored-library-traefik:2.10.5
       sizeBytes: 43142359
 --
       - docker.io/rancher/klipper-lb@sha256:558dcf96bf0800d9977ef46dca18411752618cd9dd06daeb99460c0a301d0a60
       - docker.io/rancher/klipper-lb:v0.4.7
       sizeBytes: 4777465
     - names:
       - docker.io/rancher/mirrored-pause@sha256:74c4244427b7312c5b901fe0f67cbc53683d06f4f24c6faee65d4182bf0fa893
       - docker.io/rancher/mirrored-pause:3.6
       sizeBytes: 301463
 }
  ```
 ---------------------
