### ISSUE TITLE
servicelb with externalTrafficPolicy: Local forwards traffic from all nodes to a pod

### ISSUE THREAD

**Issue by dansimko** [k3s-io/k3s#9592]
**Environmental Info:**
K3s Version: `v1.28.7-rc3+k3s1` (running RC as v1.28.6 has a bug starting up without flannel)
Node(s) CPU architecture, OS, and Version: x86_64, Alma Linux 9.3
Cluster Configuration: 1 server, 1 agents

**Describe the bug:**
When exposing a service of type `LoadBalancer` with `externalTrafficPolicy: Local`, `svclb` pods capturing the exposed ports are scheduled on *all* nodes in the cluster and traffic from all nodes is forwarded to a pod running on one of the nodes.

**Steps To Reproduce:**

- Installed K3s: `--flannel-backend=none --disable traefik`, using `ingress-nginx` and customized flannel bound to different interface and `--ip-masq=false`
- `kubectl apply`
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service-nginx
  namespace: "default"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-service
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: test-service
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/bitnami/nginx:1.25.4-debian-12-r2
          imagePullPolicy: "IfNotPresent"
          env:
            - name: NGINX_HTTP_PORT_NUMBER
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-service-nginx
  namespace: "default"
  labels:
    app.kubernetes.io/instance: test-service
    app.kubernetes.io/name: nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/instance: test-service
    app.kubernetes.io/name: nginx
```

**Expected behavior:**
Load balancer attached to a service with external traffic policy set to `Local`, should route only node-local traffic to the pod.

**Actual behavior:**
Traffic from all nodes is routed to the pod with traffic received by other nodes showing in the pod as originating from client IP 10.42.0.0.

**Additional context / logs:**

Service shows correct IP associated:
```
$ kubectl describe svc test-service-nginx 
Name:                     test-service-nginx
Namespace:                default
Labels:                   app.kubernetes.io/instance=test-service
                          app.kubernetes.io/name=nginx
Annotations:              <none>
Selector:                 app.kubernetes.io/instance=test-service,app.kubernetes.io/name=nginx
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.49.37
IPs:                      10.43.49.37
LoadBalancer Ingress:     <agent-node-public-ip>
Port:                     http  8080/TCP
TargetPort:               http/TCP
NodePort:                 http  31664/TCP
Endpoints:                10.42.1.47:8080
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     32102
Events:
  Type    Reason                Age    From                Message
  ----    ------                ----   ----                -------
  Normal  EnsuringLoadBalancer  8m26s  service-controller  Ensuring load balancer
  Normal  AppliedDaemonSet      8m26s                      Applied LoadBalancer DaemonSet kube-system/svclb-test-service-nginx-3e5e41a6
  Normal  UpdatedLoadBalancer   8m9s                       Updated LoadBalancer with new IPs: [] -> [<agent-node-public-ip>]
```

servicelb pods get deployed to both nodes:
```
$ kubectl get pods -A -o wide
NAMESPACE       NAME                                            READY   STATUS    RESTARTS      AGE    IP           NODE                  NOMINATED NODE   READINESS GATES
...
kube-system     svclb-test-service-nginx-3e5e41a6-zvxg7         1/1     Running   0             5m6s   10.42.0.18   <master-node-host>    <none>           <none>
kube-system     svclb-test-service-nginx-3e5e41a6-z7cc9         1/1     Running   0             5m6s   10.42.1.46   <agent-node-host>     <none>           <none>
default         test-service-nginx-d497bb98f-vmd66              1/1     Running   0             5m7s   10.42.1.47   <agent-node-host>     <none>           <none>
```

Accessing the service at the node the pod is running on logs in the pod:
```
<actual_client_ip> - - [28/Feb/2024:18:44:49 +0000] "GET / HTTP/1.1" 200 409 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0" "-"
```
If accessed through different node:
```
10.42.0.0 - - [28/Feb/2024:18:45:02 +0000] "GET / HTTP/1.1" 200 409 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0" "-"
```
