### ISSUE TITLE
HelmChart doesn't render %{KUBERNETES_API}% value

### ISSUE THREAD

**Issue by Stefanqn** [k3s-io/k3s#9767]
**Environmental Info:**
K3s Version:   v1.29.2+k3s1

Node(s) CPU architecture, OS, and Version: 
intel

Cluster Configuration:
1 node

**Describe the bug:**
I'm trying to lift k3s templated values into a configmap, with a chart named `k3s-template-adapter`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: k3s-template-adapter
data:
  TEST:  "{{ .Values.test }}"
  SYSTEM_DEFAULT_REGISTRY: "{{ .Values.kubernetesapi }}"
```
and an wrapping `helm.cattle.io/v1/HelmChart`:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: k3s-template-adapter
  namespace: kube-system
spec:
  chart: k3s-template-adapter
  targetNamespace: kube-system
  chartContent: {{ (.Files.Get "k3s-template-adapter-0.1.0.tgz") | b64enc  }}
  valuesContent: |-
    test: me
    kubernetesapi: '%{KUBERNETES_API}%'
```
`.Values.kubernetesapi` isn't templated but contains `%{KUBERNETES_API}%`.

[k3s helm](https://docs.k3s.io/helm#using-the-helm-controller) mentions it's usage for `spec.chart`.
