### ISSUE TITLE
embedded registry for k3s agent..

### ISSUE THREAD

**Issue by ThomasADavis** [k3s-io/k3s#9796]
**Environmental Info:**
K3s Version: 
```
k3s version v1.28.8+k3s1 (653dd61a)
go version go1.21.8
```

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:
Combination of control planes and workers.  The workers are running k3s as agents.

**Describe the bug:**
```root@d8-r14-c1-n11:/etc/rancher/k3s/config.yaml.d# k3s server --help| grep embedded-reg
   --embedded-registry                        (experimental/components) Enable embedded distributed container registry; requires use of embedded containerd
root@d8-r14-c1-n11:/etc/rancher/k3s/config.yaml.d# k3s agent --help| grep embedded-reg
root@d8-r14-c1-n11:/etc/rancher/k3s/config.yaml.d# 
```
and

```
root@d8-r14-c1-n8:~# kubectl get --raw /api/v1/nodes/d8-r14-c1-n11/proxy/metrics | grep -F 'spegel'
root@d8-r14-c1-n8:~# 
```
Is the embedded registry supported on nodes running k3s as an agent?

**Expected behavior:**
k3s embedded registry on all server/agent nodes.

**Actual behavior:**
k3s embedded registry only on server nodes.

**Comment by ThomasADavis** [comment]
Let me see if understand this -

embedded registry runs just on control-planes aka `k3s server` nodes.

any workers aka `k3s agent` nodes, will then pull from the control-planes, if they are restarted after all the k3s server nodes are configured and running the embedded registry.

**Comment by brandond** [comment]
https://docs.k3s.io/installation/registry-mirror#enabling-the-distributed-oci-registry-mirror
> In order to enable the embedded registry mirror, server nodes must be started with the --embedded-registry flag, or with embedded-registry: true in the configuration file. This option **enables the embedded mirror for use on all nodes in the cluster**.

You enable the embedded registry mirror cluster-wide by setting the flag on servers. You then enable specific registries for mirroring by adding them to registries.yaml on individual nodes.

**Comment by clouedoc** [comment]
Sorry if I missed something, but I set the --embedded-registry flag on my "server nodes" (I assume this refers to the control plane?) but the embedded registry only gets activated on the control plane and not my workers.

The option doesn't seem to be available on workers (there is no `--embedded-registry` parameter on the `k3s agent` command).

## Configurations

In my SystemD config, here is how the agent is started:

```toml
ExecStart=/usr/local/bin/k3s \
    agent \
        '--node-label' \
        'dedicated=true' \
        '--node-ip' \
        '10.13.37.8' \
        '--node-external-ip' \
        'X.X.X.X'
```

And here is the one on my control plane nodes:

```toml
ExecStart=/usr/local/bin/k3s \
    server \
        '--disable-cloud-controller' \
        '--disable' \
        'traefik' \
        '--disable' \
        'servicelb' \
        '--disable' \
        'metrics-server' \
        '--write-kubeconfig-mode=644' \
        '--node-name=adc-master3' \
        '--cluster-cidr=10.244.0.0/16' \
        '--service-cidr=10.43.0.0/16' \
        '--cluster-dns=10.43.0.10' \
        '--kube-controller-manager-arg=bind-address=0.0.0.0' \
        '--kube-proxy-arg=metrics-bind-address=0.0.0.0' \
        '--kube-scheduler-arg=bind-address=0.0.0.0' \
        '--node-taint' \
        'CriticalAddonsOnly=true:NoExecute' \
        '--kubelet-arg' \
        'cloud-provider=external' \
        '--kubelet-arg' \
        'resolv-conf=/etc/k8s-resolv.conf' \
        '--etcd-expose-metrics=true' \
        '--etcd-snapshot-retention=24' \
        '--etcd-snapshot-schedule-cron=0 * * * *' \
        '--flannel-backend=none' \
        '--disable-network-policy' \
        '--disable-kube-proxy' \
        '--embedded-registry' \
        '--disable' \
        'local-storage' \
        '--advertise-address=10.13.0.2' \
        '--node-ip=10.13.0.2' \
        '--node-external-ip=X.X.X.X' \
        '--cluster-init' \
        '--tls-san=10.13.0.2' \
        '--tls-san=10.13.0.3' \
        '--tls-san=10.13.0.4' \
        '--tls-san=127.0.0.1' \
        '--tls-san=X.X.X.X' \
        '--tls-san=X.X.X.X' \
        '--tls-san=X.X.X.X' \
        '--tls-san=X.X.X.X' \
```

As you can see the "embedded-registry" flag is set

## Proof that the workers are not starting the embedded registry

On my master, I can see that the registry works:

```
root@adc-master3:~# curl 10.13.0.2:5001 # this is the internal IP of this master node
curl: (1) Received HTTP/0.9 when not allowed
```

It can also reach the registries of the other master nodes

```
root@adc-master3:~# curl 10.13.0.3:5001
curl: (1) Received HTTP/0.9 when not allowed
root@adc-master3:~# curl 10.13.0.4:5001
curl: (1) Received HTTP/0.9 when not allowed
```

My worker node can access the registry on the control plane:

```
root@adr-hel-5 ~ # curl 10.13.0.4:5001
curl: (1) Received HTTP/0.9 when not allowed
```

But my worker node doesn't seem to be hosting a registry itself:

root@adr-hel-5 ~ # curl 10.13.37.8:5001 # this is the internal IP of this worker node
curl: (7) Failed to connect to 10.13.37.8 port 5001 after 0 ms: Couldn't connect to server

## Versions

On the worker:

```
root@adr-hel-5 ~ # k3s --version
k3s version v1.33.4+k3s1 (148243c4)
go version go1.24.5
```

On the control plane:

```
root@adc-master3:~# k3s --version
k3s version v1.32.8+k3s1 (fe896f7e)
go version go1.23.11
```

I think those two are recent enough to both have the embedded registry (the worker being more recent than the control plane)

I wonder what mechanism is used to determine whether the start the embedded registry on worker/agent nodes.

**Comment by brandond** [comment]
The embedded registry is enabled on agents if:
* it is enabled on the server the agent is joining
* there are registries configured in registries.yaml on the agent

This is covered in the docs: https://docs.k3s.io/installation/registry-mirror#enabling-registry-mirroring
> In order to enable mirroring of images from an upstream container registry, nodes must have an entry in the mirrors section of registries.yaml for that registry. The registry does not need to have any endpoints listed, it just needs to be present.
> If no registries are enabled for mirroring on a node, that node does not participate in the distributed registry in any capacity.

**Comment by clouedoc** [comment]
@brandond Thank you for your answer !

1/ is it enabled on the server the agent is joining: yes it is, with the `--embedded-registry` flag
2/ there are registries configured in registries.yaml on the agent: yes, see below

It's, I should've sent the details earlier

```yaml
# /etc/rancher/k3s/registries.yaml
mirrors:
  # Enable Spegel mirroring for all registries
  "*":
  "memoire:5000":
    endpoint:
      - "http://memoire:5000"
configs:
  "memoire:5000":
    tls:
      insecure_skip_verify: true
```

The latest worker node I added was with the --embedded-registry flag enabled on the server nodes (I assume this is the controlplane nodes)

```
root@adr-hel-5 ~ # curl 10.13.37.8:5001 # Internal IP of the this worker node
curl: (7) Failed to connect to 10.13.37.8 port 5001 after 0 ms: Couldn't connect to server
root@adr-hel-5 ~ # ip addr | grep inet | grep enp
    inet 95.216.16.51/32 scope global enp98s0f0
    inet 10.13.37.8/24 brd 10.13.37.255 scope global enp0s31f6.4002
root@adr-hel-5 ~ # curl 95.216.16.51:5001 # External / public IP of the this worker node
curl: (7) Failed to connect to 95.216.16.51 port 5001 after 0 ms: Couldn't connect to server
```

I will try restarting the server nodes and then the worker nodes and report back.
