### ISSUE TITLE
Local path provisioner disallowed from reading Pods logs

### ISSUE THREAD

**Issue by zc-devs** [k3s-io/k3s#9834]
**Environmental Info:**
K3s Version: v1.29.3+k3s1
Local path provisioner: v0.0.26

Node(s) CPU architecture, OS, and Version: 
Linux 5.14.0-362.24.1.el9_3.x86_64 https://github.com/k3s-io/k3s/issues/1 SMP PREEMPT_DYNAMIC Wed Mar 20 04:52:13 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, embedded etcd

**Describe the bug:**
If helper pod fails, then Local path provisioner cannot get logs of it.

**Steps To Reproduce:**
1-8. The same as in #9833.
9. Check logs of Local path provisioner. Get error:
```
pods \"helper-pod-delete-pvc-3f2233a9-795e-4ba0-a52f-e4bf335979a4\" is forbidden: User \"system:serviceaccount:kube-system:local-path-provisioner-service-account\" cannot get resource \"pods/log\" in API group \"\" in the namespace \"kube-system\""
```
[local-path-provisioner.log](https://github.com/k3s-io/k3s/files/14808655/local-path-provisioner.log)

**Expected behavior:**
Logs of failed helper pod can be seen in Local path provisioner's logs.

**Actual behavior:**
Error in logs, no logs from child pod.

**Workaround:**
Add permissions to read Pod's logs:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "configmaps", "pods/log"]
    verbs: ["get", "list", "watch"]
```
