### ISSUE TITLE
Pods can't resolve DNS

### ISSUE THREAD

**Issue by jkleinkauff** [k3s-io/k3s#9921]
**Environmental Info:**
K3s Version: 
k3s version v1.28.8+k3s1 (653dd61a)
go version go1.21.8

Node(s) CPU architecture, OS, and Version: 
(docker agent)Linux 0b5bf15de242 6.6.16-linuxkit #1 SMP Fri Feb 16 11:54:02 UTC 2024 aarch64 GNU/Linux

Cluster Configuration:
- My cluster contains there rpis boards and they are working pretty well. Now I'm trying to add a new agent using [docker](https://github.com/k3s-io/k3s/blob/master/docker-compose.yml)
- This new agent is running on my machine (macOS 14.3.1 23D60 arm64)

**Describe the bug:**
The pods created on this new agent can't resolve dns. The way I'm testing is exec into the pod and nslookup something

**Steps To Reproduce:**
The docker-compose file I'm using is the following:
```
services:
  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command:
      - agent
      - --node-name
      - macmachine-docker1
      - --node-label
      - "machine=macmachine"
      - --node-taint
      - "isMacMachine=true:NoSchedule"
      - --resolv-conf
      - "/var/lib/rancher/k3s/agent/etc/resolv.conf"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://192.168.15.180:6443
    - K3S_TOKEN=${K3S_TOKEN:?err}
    - K3D_FIX_DNS=1
    volumes:
    - k3s-agent:/var/lib/rancher/k3s
```

The --resolv-conf value is probably wrong. I'm just playing with the parameter.
I have seen other similar issues but I just can't make it work. Sorry for opening another similar issue.

When deploying the pod with **hostNetwork: true** dns resolution is working as expected.

**Expected behavior:**
My pods could resolve any name.

**Actual behavior:**
nslookup inside the pod:
```
$ nslookup google.com
;; connection timed out; no servers could be reached
```

**Additional context / logs:**
/etc/resolv.conf inside the pod:
```
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5
```

agent:
```
nameserver 127.0.0.11
options ndots:0
```
