### ISSUE TITLE
k3s on OpenWrt can't find CPU cgroup - but it is enabled.

### ISSUE THREAD

**Issue by IngwiePhoenix** [k3s-io/k3s#9947]
**Environmental Info:**
K3s Version: k3s/1.29.3+k3s1, go/1.21.0

Node(s) CPU architecture, OS, and Version: aarch64, OpenWrt, 23.05.2

Cluster Configuration: Configuration is below; right now, single-node.

**Describe the bug:**
I was trying to get k3s running on my NanoPi R6s by basically doing this:
- Download the k3s aarch64 binary,
- write a bock standart procd init script,
- write config in `/etc/rancher/k3s/config.yaml[.d/*]`,
- run `k3s server --alsologtostderr` manually to confirm it working; it does not.

It is kind of a dupe of #8971 - however, I did verify if cgroups had the CPU enabled:
```
# cat /proc/cgroups
#subsys_name    hierarchy       num_cgroups     enabled
cpuset  1       2       1
cpu     2       2       1
cpuacct 3       2       1
blkio   4       2       1
memory  5       2       1
devices 6       2       1
freezer 7       2       1
net_cls 8       2       1
perf_event      9       2       1
net_prio        10      2       1
hugetlb 11      2       1
pids    12      2       1
```

**Steps To Reproduce:**
See above; but also, here is the contents of my config.
```yaml
# find . -type f | while read f; echo "### $f"; cat $f; end
### ./config.yaml.d/node-labels.yaml
node-label:
  - node-location=home
### ./config.yaml.d/storage.yaml
default-local-storage-path: "/srv/k3s"
### ./config.yaml.d/node-mame.yaml
node-name: "routerboi"
### ./config.yaml.d/node-ip.yaml
# node-ip:
node-external-ip: 100.64.0.2
### ./config.yaml.d/data-dir.yaml
data-dir: "/usb/k3s"
### ./config.yaml
log: "/var/log/k3s.log"
token: <snip>
write-kubeconfig-mode: 600
cluster-init: true
cluster-domain: "kube.birb.it"
flannel-external-ip: true
etcd-snapshot-compress: true
secrets-encryption: true
# TODO: egress-selector-mode: cluster?
# TODO: server: <tailscale ip>
# TODO: vpn-auth: "name=tailscale,joinKey=<headscale auth key>,controlServerURL=https://vpnurl"
### ./k3s.yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <snip>
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: <snip>
    client-key-data: <snip>
```

**Expected behavior:**
I expected k3s to stay running and not crash.

**Actual behavior:**
```
(...)
time="2024-04-14T11:24:19Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/usb/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/usb/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/usb/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kube-apiserver-client-key-file=/usb/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/usb/k3s/server/tls/client-ca.nochain.crt --cluster-signing-kubelet-client-key-file=/usb/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/usb/k3s/server/tls/server-ca.nochain.crt --cluster-signing-kubelet-serving-key-file=/usb/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/usb/k3s/server/tls/server-ca.nochain.crt --cluster-signing-legacy-unknown-key-file=/usb/k3s/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,tokencleaner,-service,-route,-cloud-node-lifecycle --kubeconfig=/usb/k3s/server/cred/controller.kubeconfig --profiling=false --root-ca-file=/usb/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/usb/k3s/server/tls/service.current.key --service-cluster-ip-range=10.43.0.0/16 --use-service-account-credentials=true"
I0414 11:24:19.603254   19366 options.go:222] external host was not specified, using 100.64.0.2
time="2024-04-14T11:24:19Z" level=info msg="Running cloud-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/usb/k3s/server/cred/cloud-controller.kubeconfig --authorization-kubeconfig=/usb/k3s/server/cred/cloud-controller.kubeconfig --bind-address=127.0.0.1 --cloud-config=/usb/k3s/server/etc/cloud-config.yaml --cloud-provider=k3s --cluster-cidr=10.42.0.0/16 --configure-cloud-routes=false --controllers=*,-route --feature-gates=CloudDualStackNodeIPs=true --kubeconfig=/usb/k3s/server/cred/cloud-controller.kubeconfig --leader-elect-resource-name=k3s-cloud-controller-manager --node-status-update-frequency=1m0s --profiling=false"
time="2024-04-14T11:24:19Z" level=info msg="Server node token is available at /usb/k3s/server/token"
time="2024-04-14T11:24:19Z" level=info msg="To join server node to cluster: k3s server -s https://...:6443 -t ${SERVER_NODE_TOKEN}"
time="2024-04-14T11:24:19Z" level=info msg="Agent node token is available at /usb/k3s/server/agent-token"
time="2024-04-14T11:24:19Z" level=info msg="To join agent node to cluster: k3s agent -s https://...:6443 -t ${AGENT_NODE_TOKEN}"
I0414 11:24:19.606557   19366 server.go:156] Version: v1.29.3+k3s1
I0414 11:24:19.606662   19366 server.go:158] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
time="2024-04-14T11:24:19Z" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
time="2024-04-14T11:24:19Z" level=info msg="Run: k3s kubectl"
time="2024-04-14T11:24:19Z" level=fatal msg="failed to find cpu cgroup (v2)"
```

**Additional context / logs:**
This OpenWrt node, a FriendlyElec NanoPi R6s, is suppsoed to be one of two CPs, the other one is a remote VPS. That is why it has this odd label in the config; I plan to use that for `nodeSelector`.
The image is technically vendor supplied; it's shipped by FriendlyElec. containerd and alike are installed and working just fine, so I am a little surprised why k3s isn't.

Hope you can help me here, thank you!
